<h1>What kind of data does pandas handle?</h1>

### <h4>I want to start using pandas</h4>

In [ ]:
import pandas as pd

<p>To load the pandas package and start working with it, import the
package. The community agreed alias for pandas is <code>pd</code>, so loading pandas as <code>pd</code> is assumed standard practice for all of the pandas documentation.</p>

# <h2>pandas data table representation</h2>

<img src="https://pandas.pydata.org/docs/_images/01_table_dataframe.svg">

### <h4>I want to store passenger data of the Titanic. For a number of passengers, I know the name (characters), age (integers) and sex (male/female) data.</h4>

In [ ]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

In [ ]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

<p>To manually store data in a table, create a <code>DataFrame</code>. When using a Python dictionary of lists, the dictionary keys will be used as column headers and the values in each list as columns of the <code>DataFrame</code>.</p>

<p>A <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, categorical data and more) in columns. It is similar to a spreadsheet, a SQL table or the <code>data.frame</code> in R.</p>

<ul>

<li><p>The table has 3 columns, each of them with a column label. The column labels are respectively <code>Name</code>, <code>Age</code> and <code>Sex</code>.</p></li>

<li><p>The column <code>Name</code> consists of textual data with each value a string, the column <code>Age</code> are numbers and the column <code>Sex</code> is textual data.</p></li>

</ul>

<p>In spreadsheet software, the table representation of our data would look very similar:</p>

<img src="https://pandas.pydata.org/docs/_images/01_table_spreadsheet.png">

# <h2>Each column in a <code>DataFrame</code> is a <code>Series</code></h2>

<img src="https://pandas.pydata.org/docs/_images/01_table_series.svg">

### <h4>I’m just interested in working with the data in the column <code>Age</code></h4>

In [ ]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

<p>When selecting a single column of a pandas <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>, the result is
a pandas <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>. To select the column, use the column label in
between square brackets <code>[]</code>.</p>

<div class="alert alert-block alert-info">
<p>Note</p>
<p>If you are familiar with Python <a href="https://docs.python.org/3/tutorial/datastructures.html#tut-dictionaries" title="(in Python v3.13)">dictionaries</a>, the selection of a single column is very similar to the selection of dictionary values based on the key.</p>
</div>

<p>You can create a <code>Series</code> from scratch as well:</p>

In [ ]:
ages = pd.Series([22, 35, 58], name="Age")

In [ ]:
ages

0    22
1    35
2    58
Name: Age, dtype: int64

<p>A pandas <code>Series</code> has no column labels, as it is just a single column of a <code>DataFrame</code>. A Series does have row labels.</p>

# <h2>Do something with a DataFrame or Series</h2>


### <h4>I want to know the maximum Age of the passengers</h4>

<p>We can do this on the <code>DataFrame</code> by selecting the <code>Age</code> column and
applying <code>max()</code>:</p>

In [ ]:
df["Age"].max()

58

<p>Or to the <code>Series</code>:</p>

In [ ]:
ages.max()

58

<p>As illustrated by the <code>max()</code> method, you can <em>do</em> things with a <code>DataFrame</code> or <code>Series</code>.
Pandas provides a lot of functionalities, each of them a <em>method</em> you can apply to a <code>DataFrame</code> or <code>Series</code>.
As methods are functions, do not forget to use parentheses <code>()</code>.</p>

### <h4>I’m interested in some basic statistics of the numerical data of my data table</h4>

In [ ]:
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</code></a> method provides a quick overview of the numerical data in a <code>DataFrame</code>. As the <code>Name</code> and <code>Sex</code> columns are textual data, these are by default not taken into account by the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</code></a> method.</p>

<p>Many pandas operations return a <code>DataFrame</code> or a <code>Series</code>. The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</code></a> method is an example of a pandas operation returning a pandas <code>Series</code> or a pandas <code>DataFrame</code>.</p>

<div>
    <p><b>To user guide</b> Check more options on <code>describe</code> in the user guide section about <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-describe">aggregations with describe</a></p>
</div>

<div class="alert alert-block alert-info">
<p>Note</p>
<p>This is just a starting point. Similar to spreadsheet
software, pandas represents data as a table with columns and rows. Apart
from the representation, also the data manipulations and calculations
you would do in spreadsheet software are supported by pandas. Continue
reading the next tutorials to get started!</p>
</div>

### <h4>REMEMBER</h4>
    
<ul>
<li><p>Import the package, aka <code>import pandas as pd</code></p></li>
<li><p>A table of data is stored as a pandas <code>DataFrame</code></p></li>
<li><p>Each column in a <code>DataFrame</code> is a <code>Series</code></p></li>
<li><p>You can do things by applying a method to a <code>DataFrame</code> or <code>Series</code></p></li>
</ul>
</div>

<div>
    <p><b>To user guide</b> A more extended explanation to <code>DataFrame</code> and <code>Series</code> is provided in the <a href="https://pandas.pydata.org/docs/user_guide/dsintro.html#dsintro">introduction to data structures</a>.</p>
</div>