In [1]:
import pandas as pd

<div>
<div><b>Air quality data</b></div>
<p></p>
<p>For this tutorial, air quality data about $NO_2$ is used, made available by <a href="https://openaq.org">OpenAQ</a> and using the <a href="http://dhhagan.github.io/py-openaq/index.html">py-openaq</a> package.
The <code>air_quality_no2.csv</code> data set provides $NO_2$ values for the measurement stations <em>FR04014</em>, <em>BETR801</em> and <em>London Westminster</em> in respectively Paris, Antwerp and London.</p>
<p></p>
<a href="https://github.com/pandas-dev/pandas/tree/main/doc/data/air_quality_no2.csv">To raw data</a>
</div>

In [3]:
!curl https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_no2.csv -o air_quality_no2.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31984  100 31984    0     0   286k      0 --:--:-- --:--:-- --:--:--  286k

In [5]:
air_quality = pd.read_csv("air_quality_no2.csv", index_col=0, parse_dates=True)

air_quality.head()

                     station_antwerp  station_paris  station_london
datetime
2019-05-07 02:00:00              NaN            NaN            23.0
2019-05-07 03:00:00             50.5           25.0            19.0
2019-05-07 04:00:00             45.0           27.7            19.0
2019-05-07 05:00:00              NaN           50.4            16.0
2019-05-07 06:00:00              NaN           61.9             NaN

<h1>How to create new columns derived from existing columns</h1>

<img class="align-center" src="https://pandas.pydata.org/docs/_images/05_newcolumn_1.svg">

### <h4>I want to express the $NO_2$ concentration of the station in London in $mg/m^3$.</h4>

<p>(<em>If we assume temperature of 25 degrees Celsius and pressure of 1013 hPa, the conversion factor is 1.882</em>)</p>

In [7]:
air_quality["london_mg_per_cubic"] = air_quality["station_london"] * 1.882

air_quality.head()

,station_antwerp,station_paris,station_london,london_mg_per_cubic
datetime,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN

<p>To create a new column, use the <code>[]</code> brackets with the new column name at the left side of the assignment.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The calculation of the values is done <strong>element-wise</strong>. This means all values in the given column are multiplied by the value 1.882 at once. You do not need to use a loop to iterate each of the rows!</p>
</div>

<img class="align-center" src="https://pandas.pydata.org/docs/_images/05_newcolumn_2.svg">

### <h4>I want to check the ratio of the values in Paris versus Antwerp and save the result in a new column.</h4>

In [8]:
air_quality["ratio_paris_antwerp"] = (
    air_quality["station_paris"] / air_quality["station_antwerp"]
)

In [9]:
air_quality.head()

,station_antwerp,station_paris,station_london,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

<p>The calculation is again element-wise, so the <code>/</code> is applied <em>for the values in each row</em>.</p>
    
<p>Also other mathematical operators (<code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>,…) or logical operators (<code>&lt;</code>, <code>&gt;</code>, <code>==</code>,…) work element-wise. The latter was already used in the <a href="https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html#min-tut-03-subset">subset data tutorial</a> to filter rows of a table using a conditional expression.</p>

<p>If you need more advanced logic, you can use arbitrary Python code via <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a>.</p>

### <h4>I want to rename the data columns to the corresponding station identifiers used by <a href="https://openaq.org/">OpenAQ</a>.</h4>

In [10]:
air_quality_renamed = air_quality.rename(
    columns={
        "station_antwerp": "BETR801",
        "station_paris": "FR04014",
        "station_london": "London Westminster",
    }
)

In [11]:
air_quality_renamed.head()

,BETR801,FR04014,London Westminster,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename" title="pandas.DataFrame.rename"><code>rename()</code></a> function can be used for both row labels and column labels. Provide a dictionary with the keys the current names and the values the new names to update the corresponding names.</p>
    
<p>The mapping should not be restricted to fixed names only, but can be a mapping function as well. For example, converting the column names to
lowercase letters can be done using a function as well:</p>

In [12]:
air_quality_renamed = air_quality_renamed.rename(columns=str.lower)

In [13]:
air_quality_renamed.head()

,betr801,fr04014,london westminster,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

<div>
<p><b>To user guide</b> Details about column or row label renaming is provided in the user guide section on <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-rename">renaming labels</a>.</p>
</div>

<div>
<h4>REMEMBER</h4><ul>
<li><p>Create a new column by assigning the output to the DataFrame with a new column name in between the <code>[]</code>.</p></li>
<li><p>Operations are element-wise, no need to loop over rows.</p></li>
<li><p>Use <code>rename</code> with a dictionary or function to rename row labels or column names.</p></li>
</ul>
</div>

<div>
<p><b>To user guide</b> The user guide contains a separate section on <a href="https://pandas.pydata.org/docs/user_guide/dsintro.html#basics-dataframe-sel-add-del">column addition and deletion</a>.</p>
</div>