<h1>Tidy data</h1>
            
<small>Source: <a href="https://github.com/tidyverse/tidyr/blob/pkgdown-v1.3.1/vignettes/tidy-data.Rmd"><code>vignettes/tidy-data.Rmd</code></a></small>
<div><code>tidy-data.Rmd</code></div>


<p>(This is an informal and code heavy version of the full <a href="https://vita.had.co.nz/papers/tidy-data.html">tidy data paper</a>. Please refer to that for more details.)</p>

# <h2 id="data-tidying">Data tidying<a href="#data-tidying"></a></h2>

<p>It is often said that 80% of data analysis is spent on the cleaning and preparing data. And it’s not just a first step, but it must be repeated many times over the course of analysis as new problems come to light or new data is collected. To get a handle on the problem, this paper focuses on a small, but important, aspect of data cleaning that I call data <strong>tidying</strong>: structuring datasets to facilitate analysis.</p>

<p>The principles of tidy data provide a standard way to organise data values within a dataset. A standard makes initial data cleaning easier because you don’t need to start from scratch and reinvent the wheel every time. The tidy data standard has been designed to facilitate initial exploration and analysis of the data, and to simplify the development of data analysis tools that work well together. Current tools often require translation. You have to spend time munging the output from one tool so you can input it into another. Tidy datasets and tidy tools work hand in hand to make data analysis easier, allowing you to focus on the interesting domain problem, not on the uninteresting logistics of data.</p>

# <h2 id="defining">Defining tidy data</h2>

<blockquote>
<p>Happy families are all alike; every unhappy family is unhappy in its own way — Leo Tolstoy</p>
</blockquote>

<p>Like families, tidy datasets are all alike but every messy dataset is messy in its own way. Tidy datasets provide a standardized way to link the structure of a dataset (its physical layout) with its semantics (its meaning). In this section, I’ll provide some standard vocabulary for describing the structure and semantics of a dataset, and then use those definitions to define tidy data.</p>


## <h3 id="data-structure">Data structure</h3>

<p>Most statistical datasets are data frames made up of <strong>rows</strong> and <strong>columns</strong>. The columns are almost always labeled and the rows are sometimes labeled. The following code provides some data about an imaginary classroom in a format commonly seen in the wild. The table has three columns and four rows, and both rows and columns are labeled.</p>

In [2]:
library(tibble)

classroom <- tribble(
  ~name,    ~quiz1, ~quiz2, ~test1,
  "Billy",  NA,     "D",    "C",
  "Suzy",   "F",    NA,     NA,
  "Lionel", "B",    "C",    "B",
  "Jenny",  "A",    "A",    "B"
  )

classroom

  name   quiz1 quiz2 test1
1 Billy  NA    D     C
2 Suzy   F     NA    NA
3 Lionel B     C     B
4 Jenny  A     A     B

<p>There are many ways to structure the same underlying data. The following table shows the same data as above, but the rows and columns have been transposed.</p>

In [3]:
tribble(
  ~assessment, ~Billy, ~Suzy, ~Lionel, ~Jenny,
  "quiz1",     NA,     "F",   "B",     "A",
  "quiz2",     "D",    NA,    "C",     "A",
  "test1",     "C",    NA,    "B",     "B"
  )

  assessment Billy Suzy Lionel Jenny
1 quiz1      NA    F    B      A
2 quiz2      D     NA   C      A
3 test1      C     NA   B      B

<p>The data is the same, but the layout is different. Our vocabulary of rows and columns is simply not rich enough to describe why the two tables represent the same data. In addition to appearance, we need a way to describe the underlying semantics, or meaning, of the values displayed in the table.</p>

## <h3 id="data-semantics">Data semantics</h3>

<p>A dataset is a collection of <strong>values</strong>, usually either numbers (if quantitative) or strings (if qualitative). Values are organised in two ways. Every value belongs to a <strong>variable</strong> and an <strong>observation</strong>. A variable contains all values that measure the same underlying attribute (like height, temperature, duration) across units. An observation contains all values measured on the same unit (like a person, or a day, or a race) across attributes.</p>

<p>A tidy version of the classroom data looks like this: (you’ll learn how the functions work a little later)</p>

In [4]:
library(tidyr)
library(dplyr)

Caricamento pacchetto: ‘dplyr’


I seguenti oggetti sono mascherati da ‘package:stats’:

    filter, lag


I seguenti oggetti sono mascherati da ‘package:base’:

    intersect, setdiff, setequal, union

In [5]:
classroom2 <- classroom |> 
  pivot_longer(quiz1:test1, names_to = "assessment", values_to = "grade") |> 
  arrange(name, assessment)

classroom2

   name   assessment grade
1  Billy  quiz1      NA
2  Billy  quiz2      D
3  Billy  test1      C
4  Jenny  quiz1      A
5  Jenny  quiz2      A
6  Jenny  test1      B
7  Lionel quiz1      B
8  Lionel quiz2      C
9  Lionel test1      B
10 Suzy   quiz1      F
11 Suzy   quiz2      NA
12 Suzy   test1      NA

<p>This makes the values, variables, and observations more clear. The dataset contains 36 values representing three variables and 12 observations. The variables are:</p>

<ol>
<li><p><code>name</code>, with four possible values (Billy, Suzy, Lionel, and Jenny).</p></li>
<li><p><code>assessment</code>, with three possible values (quiz1, quiz2, and test1).</p></li>
<li><p><code>grade</code>, with five or six values depending on how you think of the missing value (A, B, C, D, F, NA).</p></li>
</ol>

<p>The tidy data frame explicitly tells us the definition of an observation. In this classroom, every combination of <code>name</code> and <code>assessment</code> is a single measured observation. The dataset also informs us of missing values, which can and do have meaning. Billy was absent for the first quiz, but tried to salvage his grade. Suzy failed the first quiz, so she decided to drop the class. To calculate Billy’s final grade, we might replace this missing value with an F (or he might get a second chance to take the quiz). However, if we want to know the class average for Test 1, dropping Suzy’s structural missing value would be more appropriate than imputing a new value.</p>

<p>For a given dataset, it’s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general. For example, if the columns in the classroom data were <code>height</code> and <code>weight</code> we would have been happy to call them variables. If the columns were <code>height</code> and <code>width</code>, it would be less clear cut, as we might think of height and width as values of a <code>dimension</code> variable. If the columns were <code>home phone</code> and <code>work phone</code>, we could treat these as two variables, but in a fraud detection environment we might want variables <code>phone number</code> and <code>number type</code> because the use of one phone number for multiple people might suggest fraud. A general rule of thumb is that it is easier to describe functional relationships between variables (e.g., <code>z</code> is a linear combination of <code>x</code> and <code>y</code>, <code>density</code> is the ratio of <code>weight</code> to <code>volume</code>) than between rows, and it is easier to make comparisons between groups of observations (e.g., average of group a vs.&nbsp;average of group b) than between groups of columns.</p>

<p>In a given analysis, there may be multiple levels of observation. For example, in a trial of new allergy medication we might have three observational types: demographic data collected from each person (<code>age</code>, <code>sex</code>, <code>race</code>), medical data collected from each person on each day (<code>number of sneezes</code>, <code>redness of eyes</code>), and meteorological data collected on each day (<code>temperature</code>, <code>pollen count</code>).</p>

<p>Variables may change over the course of analysis. Often the variables in the raw data are very fine grained, and may add extra modelling complexity for little explanatory gain. For example, many surveys ask variations on the same question to better get at an underlying trait. In early stages of analysis, variables correspond to questions. In later stages, you change focus to traits, computed by averaging together multiple questions. This considerably simplifies analysis because you don’t need a hierarchical model, and you can often pretend that the data is continuous, not discrete.</p>


## <h3 id="tidy-data">Tidy data</h3>

<p>Tidy data is a standard way of mapping the meaning of a dataset to its structure. A dataset is messy or tidy depending on how rows, columns and tables are matched up with observations, variables and types. In <strong>tidy data</strong>:</p>

<ol>
<li><p>Each variable is a column; each column is a variable.</p></li>
<li><p>Each observation is a row; each row is an observation.</p></li>
<li><p>Each value is a cell; each cell is a single value.</p></li>
</ol>

<p>This is Codd’s 3rd normal form, but with the constraints framed in statistical language, and the focus put on a single dataset rather than the many connected datasets common in relational databases.
<strong>Messy data</strong> is any other arrangement of the data.</p> <p>Tidy data makes it easy for an analyst or a computer to extract needed variables because it provides a standard way of structuring a dataset. Compare the different versions of the classroom data: in the messy version you need to use different strategies to extract different variables. This slows analysis and invites errors. If you consider how many data analysis operations involve all of the values in a variable (every aggregation function), you can see how important it is to extract
these values in a simple, standard way. Tidy data is particularly well suited for vectorised programming languages like R, because the layout ensures that values of different variables from the same observation are always paired.</p>

<p>While the order of variables and observations does not affect analysis, a good ordering makes it easier to scan the raw values. One way of organising variables is by their role in the analysis: are values fixed by the design of the data collection, or are they measured during the course of the experiment? Fixed variables describe the experimental design and are known in advance. Computer scientists often call fixed variables dimensions, and statisticians usually denote them with subscripts on random variables. Measured variables are what we actually
measure in the study. Fixed variables should come first, followed by measured variables, each ordered so that related variables are contiguous. Rows can then be ordered by the first variable, breaking ties with the second and subsequent (fixed) variables. This is the convention adopted by all tabular displays in this paper.</p>

# <h2 id="tidying">Tidying messy datasets</h2>

<p>Real datasets can, and often do, violate the three precepts of tidy data in almost every way imaginable. While occasionally you do get a dataset that you can start analysing immediately, this is the exception, not the rule. This section describes the five most common problems with messy datasets, along with their remedies:</p>

<ul>
<li><p>Column headers are values, not variable names.</p></li>
<li><p>Multiple variables are stored in one column.</p></li>
<li><p>Variables are stored in both rows and columns.</p></li>
<li><p>Multiple types of observational units are stored in the same table.</p></li>
<li><p>A single observational unit is stored in multiple tables.</p></li>
</ul>

<p>Surprisingly, most messy datasets, including types of messiness not explicitly described above, can be tidied with a small set of tools: pivoting (longer and wider) and separating. The following sections illustrate each problem with a real dataset that I have encountered, and show how to tidy them.</p>


## <h3 id="column-headers-are-values-not-variable-names">Column headers are values, not variable names</h3>

<p>A common type of messy dataset is tabular data designed for presentation, where variables form both the rows and columns, and column headers are values, not variable names. While I would call this arrangement messy, in some cases it can be extremely useful. It provides efficient storage for completely crossed designs, and it can lead to
extremely efficient computation if desired operations can be expressed as matrix operations.</p>

<p>The following code shows a subset of a typical dataset of this form. This dataset explores the relationship between income and religion in the US. It comes from a report produced by the Pew Research Center, an American think-tank that collects data on attitudes to topics ranging from religion to the internet, and produces many reports that contain datasets in this format.</p>

In [6]:
relig_income

   religion                <$10k $10-20k $20-30k $30-40k $40-50k $50-75k
1  Agnostic                 27    34       60     81      76      137
2  Atheist                  12    27       37     52      35       70
3  Buddhist                 27    21       30     34      33       58
4  Catholic                418   617      732    670     638     1116
5  Don’t know/refused       15    14       15     11      10       35
6  Evangelical Prot        575   869     1064    982     881     1486
7  Hindu                     1     9        7      9      11       34
8  Historically Black Prot 228   244      236    238     197      223
9  Jehovah's Witness        20    27       24     24      21       30
10 Jewish                   19    19       25     25      30       95
11 Mainline Prot           289   495      619    655     651     1107
12 Mormon                   29    40       48     51      56      112
13 Muslim                    6     7        9     10       9       23
14 Orthodox                 13    17       23     32      32       47
15 Other Christian           9     7       11     13      13       14
16 Other Faiths             20    33       40     46      49       63
17 Other World Religions     5     2        3      4       2        7
18 Unaffiliated            217   299      374    365     341      528
   $75-100k $100-150k >150k Don't know/refused
1  122      109        84     96
2   73       59        74     76
3   62       39        53     54
4  949      792       633   1489
5   21       17        18    116
6  949      723       414   1529
7   47       48        54     37
8  131       81        78    339
9   15       11         6     37
10  69       87       151    162
11 939      753       634   1328
12  85       49        42     69
13  16        8         6     22
14  38       42        46     73
15  18       14        12     18
16  46       40        41     71
17   3        4         4      8
18 407      321       258    597

<p>This dataset has three variables, <code>religion</code>, <code>income</code> and <code>frequency</code>. To tidy it, we need to <strong>pivot</strong> the non-variable columns into a two-column key-value pair. This action is often described as making a wide dataset longer (or taller).</p>

<p>When pivoting variables, we need to provide the name of the new key-value columns to create. After defining the columns to pivot (every column except for religion), you will need the name of the key column, which is the name of the variable defined by the values of the column headings. In this case, it’s <code>income</code>. The second argument is the name of the value column, <code>frequency</code>.</p>

In [7]:
relig_income |>
  pivot_longer(-religion, names_to = "income", values_to = "frequency")

    religion              income             frequency
1   Agnostic              <$10k               27
2   Agnostic              $10-20k             34
3   Agnostic              $20-30k             60
4   Agnostic              $30-40k             81
5   Agnostic              $40-50k             76
6   Agnostic              $50-75k            137
7   Agnostic              $75-100k           122
8   Agnostic              $100-150k          109
9   Agnostic              >150k               84
10  Agnostic              Don't know/refused  96
11  Atheist               <$10k               12
12  Atheist               $10-20k             27
13  Atheist               $20-30k             37
14  Atheist               $30-40k             52
15  Atheist               $40-50k             35
16  Atheist               $50-75k             70
17  Atheist               $75-100k            73
18  Atheist               $100-150k           59
19  Atheist               >150k               74
20  Atheist               Don't know/refused  76
21  Buddhist              <$10k               27
22  Buddhist              $10-20k             21
23  Buddhist              $20-30k             30
24  Buddhist              $30-40k             34
25  Buddhist              $40-50k             33
26  Buddhist              $50-75k             58
27  Buddhist              $75-100k            62
28  Buddhist              $100-150k           39
29  Buddhist              >150k               53
30  Buddhist              Don't know/refused  54
⋮   ⋮                     ⋮                  ⋮
151 Other Faiths          <$10k               20
152 Other Faiths          $10-20k             33
153 Other Faiths          $20-30k             40
154 Other Faiths          $30-40k             46
155 Other Faiths          $40-50k             49
156 Other Faiths          $50-75k             63
157 Other Faiths          $75-100k            46
158 Other Faiths          $100-150k           40
159 Other Faiths          >150k               41
160 Other Faiths          Don't know/refused  71
161 Other World Religions <$10k                5
162 Other World Religions $10-20k              2
163 Other World Religions $20-30k              3
164 Other World Religions $30-40k              4
165 Other World Religions $40-50k              2
166 Other World Religions $50-75k              7
167 Other World Religions $75-100k             3
168 Other World Religions $100-150k            4
169 Other World Religions >150k                4
170 Other World Religions Don't know/refused   8
171 Unaffiliated          <$10k              217
172 Unaffiliated          $10-20k            299
173 Unaffiliated          $20-30k            374
174 Unaffiliated          $30-40k            365
175 Unaffiliated          $40-50k            341
176 Unaffiliated          $50-75k            528
177 Unaffiliated          $75-100k           407
178 Unaffiliated          $100-150k          321
179 Unaffiliated          >150k              258
180 Unaffiliated          Don't know/refused 597

<p>This form is tidy because each column represents a variable and each row represents an observation, in this case a demographic unit corresponding to a combination of <code>religion</code> and <code>income</code>.</p>

<p>This format is also used to record regularly spaced observations over time. For example, the Billboard dataset shown below records the date a song first entered the billboard top 100. It has variables for <code>artist</code>, <code>track</code>, <code>date.entered</code>, <code>rank</code> and <code>week</code>. The rank in each week after it enters the top 100 is recorded in 75 columns, <code>wk1</code> to <code>wk75</code>. This form of storage is not tidy, but it is useful for data entry. It reduces duplication since otherwise each song in each week would need its own row, and song metadata like title and artist would need to be repeated. This will be discussed in more depth in <a href="https://tidyr.tidyverse.org/articles/tidy-data.html#multiple-types">multiple types</a>.</p>

In [8]:
billboard

    artist               track                   date.entered wk1 wk2 wk3 wk4
1   2 Pac                Baby Don't Cry (Keep... 2000-02-26   87  82  72  77
2   2Ge+her              The Hardest Part Of ... 2000-09-02   91  87  92  NA
3   3 Doors Down         Kryptonite              2000-04-08   81  70  68  67
4   3 Doors Down         Loser                   2000-10-21   76  76  72  69
5   504 Boyz             Wobble Wobble           2000-04-15   57  34  25  17
6   98^0                 Give Me Just One Nig... 2000-08-19   51  39  34  26
7   A*Teens              Dancing Queen           2000-07-08   97  97  96  95
8   Aaliyah              I Don't Wanna           2000-01-29   84  62  51  41
9   Aaliyah              Try Again               2000-03-18   59  53  38  28
10  Adams, Yolanda       Open My Heart           2000-08-26   76  76  74  69
11  Adkins, Trace        More                    2000-04-29   84  84  75  73
12  Aguilera, Christina  Come On Over Baby (A... 2000-08-05   57  47  45  29
13  Aguilera, Christina  I Turn To You           2000-04-15   50  39  30  28
14  Aguilera, Christina  What A Girl Wants       1999-11-27   71  51  28  18
15  Alice Deejay         Better Off Alone        2000-04-08   79  65  53  48
16  Allan, Gary          Smoke Rings In The D... 2000-01-22   80  78  76  77
17  Amber                Sexual                  1999-07-17   99  99  96  96
18  Anastacia            I'm Outta Love          2000-04-01   92  NA  NA  95
19  Anthony, Marc        My Baby You             2000-09-16   82  76  76  70
20  Anthony, Marc        You Sang To Me          2000-02-26   77  54  50  43
21  Avant                My First Love           2000-11-04   70  62  56  43
22  Avant                Separated               2000-04-29   62  32  30  23
23  BBMak                Back Here               2000-04-29   99  86  60  52
24  Backstreet Boys, The Shape Of My Heart       2000-10-14   39  25  24  15
25  Backstreet Boys, The Show Me The Meaning ... 2000-01-01   74  62  55  25
26  Backstreet Boys, The The One                 2000-05-27   58  50  43  37
27  Badu, Erkyah         Bag Lady                2000-08-19   67  53  42  41
28  Baha Men             Who Let The Dogs Out    2000-07-22   99  92  85  76
29  Barenaked Ladies     Pinch Me                2000-09-09   77  76  69  45
30  Beenie Man           Girls Dem Sugar         2000-10-21   72  72  63  56
⋮   ⋮                    ⋮                       ⋮            ⋮   ⋮   ⋮   ⋮
288 Thomas, Carl         Emotional               2000-11-25   77  63  61   58
289 Thomas, Carl         I Wish                  2000-03-25   75  64  48   39
290 Thomas, Carl         Summer Rain             2000-09-23   82  82  86   80
291 Tippin, Aaron        Kiss This               2000-08-26   74  72  66   53
292 Train                Meet Virginia           1999-10-09   76  67  59   54
293 Trick Daddy          Shut Up                 2000-05-20   99  95  87   87
294 Trina                Pull Over               2000-09-09   97  93  96  100
295 Tritt, Travis        Best Of Intentions      2000-08-19   97  86  79   70
296 Tuesday              I Know                  2000-12-30   98  98  NA   NA
297 Urban, Keith         Your Everything         2000-07-15   81  80  73   73
298 Usher                Pop Ya Collar           2000-11-04   68  64  60   60
299 Vassar, Phil         Carlene                 2000-03-04   75  67  64   64
300 Vassar, Phil         Just Another Day In ... 2000-09-30   81  81  76   67
301 Vertical Horizon     Everything You Want     2000-01-22   70  61  53   46
302 Vertical Horizon     You're A God            2000-08-26   64  55  43   41
303 Vitamin C            Graduation (Friends ... 2000-04-15   81  64  54   54
304 Vitamin C            The Itch                2000-12-02   86  48  45   52
305 Walker, Clay         Live, Laugh, Love       1999-12-04   95  95  94   94
306 Walker, Clay         The Chain Of Love       2000-04-15   73  65  57   57
307 Wallflowers, The     Sleepwalker             2000-10-28   73  73  74   80
308 Westlife             Swear It Again          2000-04-01   96  82  66   55
309 Williams, Robbie     Angels                  1999-11-20   85  77  69   69
310 Wills, Mark          Back At One             2000-01-15   89  55  51   43
311 Worley, Darryl       When You Need My Lov... 2000-06-17   98  88  93   92
312 Wright, Chely        It Was                  2000-03-04   86  78  75   72
313 Yankee Grey          Another Nine Minutes    2000-04-29   86  83  77   74
314 Yearwood, Trisha     Real Live Woman         2000-04-01   85  83  83   82
315 Ying Yang Twins      Whistle While You Tw... 2000-03-18   95  94  91   85
316 Zombie Nation        Kernkraft 400           2000-09-02   99  99  NA   NA
317 matchbox twenty      Bent                    2000-04-29   60  37  29   24
    wk5 wk6 wk7 ⋯ wk67 wk68 wk69 wk70 wk71 wk72 wk73 wk74 wk75 wk76
1    87 94  99  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
2    NA NA  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
3    66 57  54  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
4    67 65  55  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
5    17 31  36  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
6    26 19   2  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
7   100 NA  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
8    38 35  35  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
9    21 18  16  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
10   68 67  61  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
11   73 69  68  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
12   23 18  11  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
13   21 19  20  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
14   13 13  11  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
15   45 36  34  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
16   92 NA  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
17  100 93  93  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
18   NA NA  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
19   82 81  74  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
20   30 27  21  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
21   39 33  26  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
22   26 30  35  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
23   38 34  28  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
24   12 12  10  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
25   16 14  12  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
26   31 30  39  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
27   48 42  34  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
28   65 54  61  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
29   51 37  33  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
30   62 63  54  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
⋮   ⋮   ⋮   ⋮   ⋱ ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮
288 54  47  53  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
289 32  28  24  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
290 82  83  84  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
291 52  47  47  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
292 48  45  40  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
293 83  83  89  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
294 NA  NA  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
295 63  56  50  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
296 NA  NA  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
297 67  64  60  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
298 62  79  93  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
299 57  53  47  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
300 53  46  43  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
301 40  33  31  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
302 37  31  30  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
303 46  40  40  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
304 57  58  76  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
305 94  95  82  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
306 51  48  44  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
307 90  96  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
308 55  46  44  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
309 62  56  56  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
310 37  37  36  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
311 85  85  84  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
312 71  69  64  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
313 83  79  88  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
314 81  91  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
315 84  78  74  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
316 NA  NA  NA  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
317 22  21  18  ⋯ NA   NA   NA   NA   NA   NA   NA   NA   NA   NA

<p>To tidy this dataset, we first use <code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code> to make the dataset longer. We transform the columns from <code>wk1</code> to <code>wk76</code>, making a new column for their names, <code>week</code>, and a new value for their values, <code>rank</code>:</p>

In [9]:
billboard2 <- billboard |> 
  pivot_longer(
    wk1:wk76, 
    names_to = "week", 
    values_to = "rank", 
    values_drop_na = TRUE
  )

billboard2

     artist          track                   date.entered week rank
1    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk1  87
2    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk2  82
3    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk3  72
4    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk4  77
5    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk5  87
6    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk6  94
7    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk7  99
8    2Ge+her         The Hardest Part Of ... 2000-09-02   wk1  91
9    2Ge+her         The Hardest Part Of ... 2000-09-02   wk2  87
10   2Ge+her         The Hardest Part Of ... 2000-09-02   wk3  92
11   3 Doors Down    Kryptonite              2000-04-08   wk1  81
12   3 Doors Down    Kryptonite              2000-04-08   wk2  70
13   3 Doors Down    Kryptonite              2000-04-08   wk3  68
14   3 Doors Down    Kryptonite              2000-04-08   wk4  67
15   3 Doors Down    Kryptonite              2000-04-08   wk5  66
16   3 Doors Down    Kryptonite              2000-04-08   wk6  57
17   3 Doors Down    Kryptonite              2000-04-08   wk7  54
18   3 Doors Down    Kryptonite              2000-04-08   wk8  53
19   3 Doors Down    Kryptonite              2000-04-08   wk9  51
20   3 Doors Down    Kryptonite              2000-04-08   wk10 51
21   3 Doors Down    Kryptonite              2000-04-08   wk11 51
22   3 Doors Down    Kryptonite              2000-04-08   wk12 51
23   3 Doors Down    Kryptonite              2000-04-08   wk13 47
24   3 Doors Down    Kryptonite              2000-04-08   wk14 44
25   3 Doors Down    Kryptonite              2000-04-08   wk15 38
26   3 Doors Down    Kryptonite              2000-04-08   wk16 28
27   3 Doors Down    Kryptonite              2000-04-08   wk17 22
28   3 Doors Down    Kryptonite              2000-04-08   wk18 18
29   3 Doors Down    Kryptonite              2000-04-08   wk19 18
30   3 Doors Down    Kryptonite              2000-04-08   wk20 14
⋮    ⋮               ⋮                       ⋮            ⋮    ⋮
5278 matchbox twenty Bent                    2000-04-29   wk10 12
5279 matchbox twenty Bent                    2000-04-29   wk11  8
5280 matchbox twenty Bent                    2000-04-29   wk12  6
5281 matchbox twenty Bent                    2000-04-29   wk13  1
5282 matchbox twenty Bent                    2000-04-29   wk14  2
5283 matchbox twenty Bent                    2000-04-29   wk15  3
5284 matchbox twenty Bent                    2000-04-29   wk16  2
5285 matchbox twenty Bent                    2000-04-29   wk17  2
5286 matchbox twenty Bent                    2000-04-29   wk18  3
5287 matchbox twenty Bent                    2000-04-29   wk19  4
5288 matchbox twenty Bent                    2000-04-29   wk20  5
5289 matchbox twenty Bent                    2000-04-29   wk21  4
5290 matchbox twenty Bent                    2000-04-29   wk22  4
5291 matchbox twenty Bent                    2000-04-29   wk23  6
5292 matchbox twenty Bent                    2000-04-29   wk24  9
5293 matchbox twenty Bent                    2000-04-29   wk25 12
5294 matchbox twenty Bent                    2000-04-29   wk26 13
5295 matchbox twenty Bent                    2000-04-29   wk27 19
5296 matchbox twenty Bent                    2000-04-29   wk28 20
5297 matchbox twenty Bent                    2000-04-29   wk29 20
5298 matchbox twenty Bent                    2000-04-29   wk30 24
5299 matchbox twenty Bent                    2000-04-29   wk31 29
5300 matchbox twenty Bent                    2000-04-29   wk32 28
5301 matchbox twenty Bent                    2000-04-29   wk33 27
5302 matchbox twenty Bent                    2000-04-29   wk34 30
5303 matchbox twenty Bent                    2000-04-29   wk35 33
5304 matchbox twenty Bent                    2000-04-29   wk36 37
5305 matchbox twenty Bent                    2000-04-29   wk37 38
5306 matchbox twenty Bent                    2000-04-29   wk38 38
5307 matchbox twenty Bent                    2000-04-29   wk39 48

<p>Here we use <code>values_drop_na = TRUE</code> to drop any missing values from the rank column. In this data, missing values represent weeks that the song wasn’t in the charts, so can be safely dropped.</p>

<p>In this case it’s also nice to do a little cleaning, converting the week variable to a number, and figuring out the date corresponding to each week on the charts:</p>

In [10]:
billboard3 <- billboard2 |>
  mutate(
    week = as.integer(gsub("wk", "", week)),
    date = as.Date(date.entered) + 7 * (week - 1),
    date.entered = NULL
  )

billboard3

     artist          track                   week rank date
1    2 Pac           Baby Don't Cry (Keep...  1   87   2000-02-26
2    2 Pac           Baby Don't Cry (Keep...  2   82   2000-03-04
3    2 Pac           Baby Don't Cry (Keep...  3   72   2000-03-11
4    2 Pac           Baby Don't Cry (Keep...  4   77   2000-03-18
5    2 Pac           Baby Don't Cry (Keep...  5   87   2000-03-25
6    2 Pac           Baby Don't Cry (Keep...  6   94   2000-04-01
7    2 Pac           Baby Don't Cry (Keep...  7   99   2000-04-08
8    2Ge+her         The Hardest Part Of ...  1   91   2000-09-02
9    2Ge+her         The Hardest Part Of ...  2   87   2000-09-09
10   2Ge+her         The Hardest Part Of ...  3   92   2000-09-16
11   3 Doors Down    Kryptonite               1   81   2000-04-08
12   3 Doors Down    Kryptonite               2   70   2000-04-15
13   3 Doors Down    Kryptonite               3   68   2000-04-22
14   3 Doors Down    Kryptonite               4   67   2000-04-29
15   3 Doors Down    Kryptonite               5   66   2000-05-06
16   3 Doors Down    Kryptonite               6   57   2000-05-13
17   3 Doors Down    Kryptonite               7   54   2000-05-20
18   3 Doors Down    Kryptonite               8   53   2000-05-27
19   3 Doors Down    Kryptonite               9   51   2000-06-03
20   3 Doors Down    Kryptonite              10   51   2000-06-10
21   3 Doors Down    Kryptonite              11   51   2000-06-17
22   3 Doors Down    Kryptonite              12   51   2000-06-24
23   3 Doors Down    Kryptonite              13   47   2000-07-01
24   3 Doors Down    Kryptonite              14   44   2000-07-08
25   3 Doors Down    Kryptonite              15   38   2000-07-15
26   3 Doors Down    Kryptonite              16   28   2000-07-22
27   3 Doors Down    Kryptonite              17   22   2000-07-29
28   3 Doors Down    Kryptonite              18   18   2000-08-05
29   3 Doors Down    Kryptonite              19   18   2000-08-12
30   3 Doors Down    Kryptonite              20   14   2000-08-19
⋮    ⋮               ⋮                       ⋮    ⋮    ⋮
5278 matchbox twenty Bent                    10   12   2000-07-01
5279 matchbox twenty Bent                    11    8   2000-07-08
5280 matchbox twenty Bent                    12    6   2000-07-15
5281 matchbox twenty Bent                    13    1   2000-07-22
5282 matchbox twenty Bent                    14    2   2000-07-29
5283 matchbox twenty Bent                    15    3   2000-08-05
5284 matchbox twenty Bent                    16    2   2000-08-12
5285 matchbox twenty Bent                    17    2   2000-08-19
5286 matchbox twenty Bent                    18    3   2000-08-26
5287 matchbox twenty Bent                    19    4   2000-09-02
5288 matchbox twenty Bent                    20    5   2000-09-09
5289 matchbox twenty Bent                    21    4   2000-09-16
5290 matchbox twenty Bent                    22    4   2000-09-23
5291 matchbox twenty Bent                    23    6   2000-09-30
5292 matchbox twenty Bent                    24    9   2000-10-07
5293 matchbox twenty Bent                    25   12   2000-10-14
5294 matchbox twenty Bent                    26   13   2000-10-21
5295 matchbox twenty Bent                    27   19   2000-10-28
5296 matchbox twenty Bent                    28   20   2000-11-04
5297 matchbox twenty Bent                    29   20   2000-11-11
5298 matchbox twenty Bent                    30   24   2000-11-18
5299 matchbox twenty Bent                    31   29   2000-11-25
5300 matchbox twenty Bent                    32   28   2000-12-02
5301 matchbox twenty Bent                    33   27   2000-12-09
5302 matchbox twenty Bent                    34   30   2000-12-16
5303 matchbox twenty Bent                    35   33   2000-12-23
5304 matchbox twenty Bent                    36   37   2000-12-30
5305 matchbox twenty Bent                    37   38   2001-01-06
5306 matchbox twenty Bent                    38   38   2001-01-13
5307 matchbox twenty Bent                    39   48   2001-01-20

<p>Finally, it’s always a good idea to sort the data. We could do it by artist, track and week:</p>

In [11]:
billboard3 |> arrange(artist, track, week)

     artist           track                   week rank date
1    2 Pac            Baby Don't Cry (Keep...  1   87   2000-02-26
2    2 Pac            Baby Don't Cry (Keep...  2   82   2000-03-04
3    2 Pac            Baby Don't Cry (Keep...  3   72   2000-03-11
4    2 Pac            Baby Don't Cry (Keep...  4   77   2000-03-18
5    2 Pac            Baby Don't Cry (Keep...  5   87   2000-03-25
6    2 Pac            Baby Don't Cry (Keep...  6   94   2000-04-01
7    2 Pac            Baby Don't Cry (Keep...  7   99   2000-04-08
8    2Ge+her          The Hardest Part Of ...  1   91   2000-09-02
9    2Ge+her          The Hardest Part Of ...  2   87   2000-09-09
10   2Ge+her          The Hardest Part Of ...  3   92   2000-09-16
11   3 Doors Down     Kryptonite               1   81   2000-04-08
12   3 Doors Down     Kryptonite               2   70   2000-04-15
13   3 Doors Down     Kryptonite               3   68   2000-04-22
14   3 Doors Down     Kryptonite               4   67   2000-04-29
15   3 Doors Down     Kryptonite               5   66   2000-05-06
16   3 Doors Down     Kryptonite               6   57   2000-05-13
17   3 Doors Down     Kryptonite               7   54   2000-05-20
18   3 Doors Down     Kryptonite               8   53   2000-05-27
19   3 Doors Down     Kryptonite               9   51   2000-06-03
20   3 Doors Down     Kryptonite              10   51   2000-06-10
21   3 Doors Down     Kryptonite              11   51   2000-06-17
22   3 Doors Down     Kryptonite              12   51   2000-06-24
23   3 Doors Down     Kryptonite              13   47   2000-07-01
24   3 Doors Down     Kryptonite              14   44   2000-07-08
25   3 Doors Down     Kryptonite              15   38   2000-07-15
26   3 Doors Down     Kryptonite              16   28   2000-07-22
27   3 Doors Down     Kryptonite              17   22   2000-07-29
28   3 Doors Down     Kryptonite              18   18   2000-08-05
29   3 Doors Down     Kryptonite              19   18   2000-08-12
30   3 Doors Down     Kryptonite              20   14   2000-08-19
⋮    ⋮                ⋮                       ⋮    ⋮    ⋮
5278 Yankee Grey      Another Nine Minutes     1   86   2000-04-29
5279 Yankee Grey      Another Nine Minutes     2   83   2000-05-06
5280 Yankee Grey      Another Nine Minutes     3   77   2000-05-13
5281 Yankee Grey      Another Nine Minutes     4   74   2000-05-20
5282 Yankee Grey      Another Nine Minutes     5   83   2000-05-27
5283 Yankee Grey      Another Nine Minutes     6   79   2000-06-03
5284 Yankee Grey      Another Nine Minutes     7   88   2000-06-10
5285 Yankee Grey      Another Nine Minutes     8   95   2000-06-17
5286 Yearwood, Trisha Real Live Woman          1   85   2000-04-01
5287 Yearwood, Trisha Real Live Woman          2   83   2000-04-08
5288 Yearwood, Trisha Real Live Woman          3   83   2000-04-15
5289 Yearwood, Trisha Real Live Woman          4   82   2000-04-22
5290 Yearwood, Trisha Real Live Woman          5   81   2000-04-29
5291 Yearwood, Trisha Real Live Woman          6   91   2000-05-06
5292 Ying Yang Twins  Whistle While You Tw...  1   95   2000-03-18
5293 Ying Yang Twins  Whistle While You Tw...  2   94   2000-03-25
5294 Ying Yang Twins  Whistle While You Tw...  3   91   2000-04-01
5295 Ying Yang Twins  Whistle While You Tw...  4   85   2000-04-08
5296 Ying Yang Twins  Whistle While You Tw...  5   84   2000-04-15
5297 Ying Yang Twins  Whistle While You Tw...  6   78   2000-04-22
5298 Ying Yang Twins  Whistle While You Tw...  7   74   2000-04-29
5299 Ying Yang Twins  Whistle While You Tw...  8   78   2000-05-06
5300 Ying Yang Twins  Whistle While You Tw...  9   85   2000-05-13
5301 Ying Yang Twins  Whistle While You Tw... 10   89   2000-05-20
5302 Ying Yang Twins  Whistle While You Tw... 11   97   2000-05-27
5303 Ying Yang Twins  Whistle While You Tw... 12   96   2000-06-03
5304 Ying Yang Twins  Whistle While You Tw... 13   99   2000-06-10
5305 Ying Yang Twins  Whistle While You Tw... 14   99   2000-06-17
5306 Zombie Nation    Kernkraft 400            1   99   2000-09-02
5307 Zombie Nation    Kernkraft 400            2   99   2000-09-09

<p>Or by date and rank:</p>

In [12]:
billboard3 |> arrange(date, rank)

     artist           track                   week rank date
1    Lonestar         Amazed                   1    81  1999-06-05
2    Lonestar         Amazed                   2    54  1999-06-12
3    Lonestar         Amazed                   3    44  1999-06-19
4    Lonestar         Amazed                   4    39  1999-06-26
5    Lonestar         Amazed                   5    38  1999-07-03
6    Lonestar         Amazed                   6    33  1999-07-10
7    Lonestar         Amazed                   7    29  1999-07-17
8    Amber            Sexual                   1    99  1999-07-17
9    Lonestar         Amazed                   8    29  1999-07-24
10   Amber            Sexual                   2    99  1999-07-24
11   Lonestar         Amazed                   9    32  1999-07-31
12   Amber            Sexual                   3    96  1999-07-31
13   Lonestar         Amazed                  10    27  1999-08-07
14   Amber            Sexual                   4    96  1999-08-07
15   Lonestar         Amazed                  11    26  1999-08-14
16   Amber            Sexual                   5   100  1999-08-14
17   Lonestar         Amazed                  12    24  1999-08-21
18   Amber            Sexual                   6    93  1999-08-21
19   Lonestar         Amazed                  13    27  1999-08-28
20   Amber            Sexual                   7    93  1999-08-28
21   Lonestar         Amazed                  14    32  1999-09-04
22   Houston, Whitney My Love Is Your Love     1    81  1999-09-04
23   Amber            Sexual                   8    96  1999-09-04
24   Lonestar         Amazed                  15    33  1999-09-11
25   Houston, Whitney My Love Is Your Love     2    68  1999-09-11
26   Creed            Higher                   1    81  1999-09-11
27   Lonestar         Amazed                  16    35  1999-09-18
28   Houston, Whitney My Love Is Your Love     3    44  1999-09-18
29   Creed            Higher                   2    77  1999-09-18
30   Houston, Whitney My Love Is Your Love     4    16  1999-09-25
⋮    ⋮                ⋮                       ⋮    ⋮    ⋮
5278 Dream            He Loves U Not          24   19   2001-03-10
5279 Creed            With Arms Wide Open     44   26   2001-03-10
5280 3 Doors Down     Kryptonite              49   28   2001-03-10
5281 Jay-Z            I Just Wanna Love U ... 20   30   2001-03-10
5282 Mya              Case Of The Ex (What... 30   35   2001-03-10
5283 N'Sync           This I Promise You      24   39   2001-03-10
5284 Thomas, Carl     Emotional               16   76   2001-03-10
5285 Avant            My First Love           19   81   2001-03-10
5286 Destiny's Child  Independent Women Pa... 26   22   2001-03-17
5287 Dream            He Loves U Not          25   23   2001-03-17
5288 Creed            With Arms Wide Open     45   28   2001-03-17
5289 3 Doors Down     Kryptonite              50   33   2001-03-17
5290 Jay-Z            I Just Wanna Love U ... 21   40   2001-03-17
5291 N'Sync           This I Promise You      25   41   2001-03-17
5292 Avant            My First Love           20   79   2001-03-17
5293 Thomas, Carl     Emotional               17   87   2001-03-17
5294 Dream            He Loves U Not          26   28   2001-03-24
5295 Destiny's Child  Independent Women Pa... 27   29   2001-03-24
5296 Creed            With Arms Wide Open     46   37   2001-03-24
5297 3 Doors Down     Kryptonite              51   42   2001-03-24
5298 N'Sync           This I Promise You      26   49   2001-03-24
5299 Thomas, Carl     Emotional               18   82   2001-03-24
5300 Destiny's Child  Independent Women Pa... 28   31   2001-03-31
5301 Dream            He Loves U Not          27   38   2001-03-31
5302 Creed            With Arms Wide Open     47   41   2001-03-31
5303 3 Doors Down     Kryptonite              52   42   2001-03-31
5304 Thomas, Carl     Emotional               19   91   2001-03-31
5305 Dream            He Loves U Not          28   46   2001-04-07
5306 3 Doors Down     Kryptonite              53   49   2001-04-07
5307 Thomas, Carl     Emotional               20   99   2001-04-07

## <h3 id="multiple-variables-stored-in-one-column">Multiple variables stored in one column</h3>

<p>After pivoting columns, the key column is sometimes a combination of multiple underlying variable names. This happens in the <code>tb</code> (tuberculosis) dataset, shown below. This dataset comes from the World Health Organisation, and records the counts of confirmed tuberculosis cases by <code>country</code>, <code>year</code>, and demographic group.
The demographic groups are broken down by <code>sex</code> (m, f) and <code>age</code> (0-14, 15-25, 25-34, 35-44, 45-54, 55-64, unknown).</p>

In [13]:
tb <- as_tibble(read.csv("tb.csv", stringsAsFactors = FALSE))

In [14]:
tb

     iso2 year m04 m514 m014 m1524 m2534 m3544 m4554 m5564 ⋯ f04 f514 f014
1    AD   1989 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
2    AD   1990 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
3    AD   1991 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
4    AD   1992 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
5    AD   1993 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
6    AD   1994 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
7    AD   1996 NA  NA    0    0     0     4     1     0    ⋯ NA  NA    0
8    AD   1997 NA  NA    0    0     1     2     2     1    ⋯ NA  NA    0
9    AD   1998 NA  NA    0    0     0     1     0     0    ⋯ NA  NA   NA
10   AD   1999 NA  NA    0    0     0     1     1     0    ⋯ NA  NA    0
11   AD   2000 NA  NA    0    0     1     0     0     0    ⋯ NA  NA   NA
12   AD   2001 NA  NA    0   NA    NA     2     1    NA    ⋯ NA  NA   NA
13   AD   2002 NA  NA    0    0     0     1     0     0    ⋯ NA  NA    0
14   AD   2003 NA  NA    0    0     0     1     2     0    ⋯ NA  NA    0
15   AD   2004 NA  NA    0    0     0     1     1     0    ⋯ NA  NA    0
16   AD   2005  0   0    0    0     1     1     0     0    ⋯  0   0    0
17   AD   2006  0   0    0    1     1     2     0     1    ⋯  0   0    0
18   AD   2007 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
19   AD   2008  0   0    0    0     0     0     1     0    ⋯  0   0    0
20   AE   1980 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
21   AE   1981 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
22   AE   1982 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
23   AE   1983 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
24   AE   1984 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
25   AE   1985 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
26   AE   1986 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
27   AE   1987 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
28   AE   1988 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
29   AE   1989 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
30   AE   1990 NA  NA   NA   NA    NA    NA    NA    NA    ⋯ NA  NA   NA
⋮    ⋮    ⋮    ⋮   ⋮    ⋮    ⋮     ⋮     ⋮     ⋮     ⋮     ⋱ ⋮   ⋮    ⋮
5740 ZM   2008 NA   NA  101  1120  3244  2094   737  299   ⋯ NA   NA  165
5741 ZW   1980 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5742 ZW   1981 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5743 ZW   1982 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5744 ZW   1983 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5745 ZW   1984 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5746 ZW   1985 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5747 ZW   1986 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5748 ZW   1987 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5749 ZW   1988 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5750 ZW   1989 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5751 ZW   1990 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5752 ZW   1991 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5753 ZW   1992 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5754 ZW   1993 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5755 ZW   1994 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5756 ZW   1995 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5757 ZW   1996 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5758 ZW   1997 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5759 ZW   1998 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5760 ZW   1999 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5761 ZW   2000 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5762 ZW   2001 NA   NA   NA    NA    NA    NA    NA   NA   ⋯ NA   NA   NA
5763 ZW   2002 NA   NA  191   600  2548  1662   744  315   ⋯ NA   NA  222
5764 ZW   2003 NA   NA  133   874  3048  2228   981  367   ⋯ NA   NA  180
5765 ZW   2004 NA   NA  187   833  2908  2298  1056  366   ⋯ NA   NA  225
5766 ZW   2005 NA   NA  210   837  2264  1855   762  295   ⋯ NA   NA  269
5767 ZW   2006 NA   NA  215   736  2391  1939   896  348   ⋯ NA   NA  237
5768 ZW   2007  6  132  138   500  3693     0   716  292   ⋯  7  178  185
5769 ZW   2008 NA   NA  127   614     0  3316   704  263   ⋯ NA   NA  145
     f1524 f2534 f3544 f4554 f5564 f65 fu
1    NA    NA    NA    NA    NA    NA  NA
2    NA    NA    NA    NA    NA    NA  NA
3    NA    NA    NA    NA    NA    NA  NA
4    NA    NA    NA    NA    NA    NA  NA
5    NA    NA    NA    NA    NA    NA  NA
6    NA    NA    NA    NA    NA    NA  NA
7     1     1     0     0     1     0  NA
8     1     2     3     0     0     1  NA
9    NA    NA    NA    NA    NA    NA  NA
10    0     0     1     0     0     0  NA
11   NA    NA    NA    NA    NA    NA  NA
12   NA    NA    NA    NA    NA    NA  NA
13    1     0     0     0     0     0  NA
14    1     1     1     0     0     0  NA
15    0     1     0     0     0     0  NA
16    1     1     1     0     0     0   0
17    0     1     0     1     0     0   0
18   NA     1    NA     1    NA    NA  NA
19    0     0     1     1     0     0   0
20   NA    NA    NA    NA    NA    NA  NA
21   NA    NA    NA    NA    NA    NA  NA
22   NA    NA    NA    NA    NA    NA  NA
23   NA    NA    NA    NA    NA    NA  NA
24   NA    NA    NA    NA    NA    NA  NA
25   NA    NA    NA    NA    NA    NA  NA
26   NA    NA    NA    NA    NA    NA  NA
27   NA    NA    NA    NA    NA    NA  NA
28   NA    NA    NA    NA    NA    NA  NA
29   NA    NA    NA    NA    NA    NA  NA
30   NA    NA    NA    NA    NA    NA  NA
⋮    ⋮     ⋮     ⋮     ⋮     ⋮     ⋮   ⋮
5740 1246  2062  1114  498   187   115  0
5741   NA    NA    NA   NA    NA    NA NA
5742   NA    NA    NA   NA    NA    NA NA
5743   NA    NA    NA   NA    NA    NA NA
5744   NA    NA    NA   NA    NA    NA NA
5745   NA    NA    NA   NA    NA    NA NA
5746   NA    NA    NA   NA    NA    NA NA
5747   NA    NA    NA   NA    NA    NA NA
5748   NA    NA    NA   NA    NA    NA NA
5749   NA    NA    NA   NA    NA    NA NA
5750   NA    NA    NA   NA    NA    NA NA
5751   NA    NA    NA   NA    NA    NA NA
5752   NA    NA    NA   NA    NA    NA NA
5753   NA    NA    NA   NA    NA    NA NA
5754   NA    NA    NA   NA    NA    NA NA
5755   NA    NA    NA   NA    NA    NA NA
5756   NA    NA    NA   NA    NA    NA NA
5757   NA    NA    NA   NA    NA    NA NA
5758   NA    NA    NA   NA    NA    NA NA
5759   NA    NA    NA   NA    NA    NA NA
5760   NA    NA    NA   NA    NA    NA NA
5761   NA    NA    NA   NA    NA    NA NA
5762   NA    NA    NA   NA    NA    NA NA
5763  914  2185  1095  421   140    65 NA
5764 1232  2856  1480  565   225   114 NA
5765 1140  2858  1565  622   214   111 NA
5766 1136  2242  1255  578   193   603 NA
5767 1020  2424  1355  632   230    96 NA
5768  739  3311     0  553   213    90 NA
5769  840     0  2890  467   174   105  0

<p>First we use <code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code> to gather up the non-variable columns:</p>

In [15]:
tb2 <- tb |> 
  pivot_longer(
    !c(iso2, year), 
    names_to = "demo", 
    values_to = "n", 
    values_drop_na = TRUE
  )
tb2

      iso2 year demo  n
1     AD   1996 m014  0
2     AD   1996 m1524 0
3     AD   1996 m2534 0
4     AD   1996 m3544 4
5     AD   1996 m4554 1
6     AD   1996 m5564 0
7     AD   1996 m65   0
8     AD   1996 f014  0
9     AD   1996 f1524 1
10    AD   1996 f2534 1
11    AD   1996 f3544 0
12    AD   1996 f4554 0
13    AD   1996 f5564 1
14    AD   1996 f65   0
15    AD   1997 m014  0
16    AD   1997 m1524 0
17    AD   1997 m2534 1
18    AD   1997 m3544 2
19    AD   1997 m4554 2
20    AD   1997 m5564 1
21    AD   1997 m65   6
22    AD   1997 f014  0
23    AD   1997 f1524 1
24    AD   1997 f2534 2
25    AD   1997 f3544 3
26    AD   1997 f4554 0
27    AD   1997 f5564 0
28    AD   1997 f65   1
29    AD   1998 m014  0
30    AD   1998 m1524 0
⋮     ⋮    ⋮    ⋮     ⋮
35721 ZW   2007 m2534 3693
35722 ZW   2007 m3544    0
35723 ZW   2007 m4554  716
35724 ZW   2007 m5564  292
35725 ZW   2007 m65    153
35726 ZW   2007 f04      7
35727 ZW   2007 f514   178
35728 ZW   2007 f014   185
35729 ZW   2007 f1524  739
35730 ZW   2007 f2534 3311
35731 ZW   2007 f3544    0
35732 ZW   2007 f4554  553
35733 ZW   2007 f5564  213
35734 ZW   2007 f65     90
35735 ZW   2008 m014   127
35736 ZW   2008 m1524  614
35737 ZW   2008 m2534    0
35738 ZW   2008 m3544 3316
35739 ZW   2008 m4554  704
35740 ZW   2008 m5564  263
35741 ZW   2008 m65    185
35742 ZW   2008 mu       0
35743 ZW   2008 f014   145
35744 ZW   2008 f1524  840
35745 ZW   2008 f2534    0
35746 ZW   2008 f3544 2890
35747 ZW   2008 f4554  467
35748 ZW   2008 f5564  174
35749 ZW   2008 f65    105
35750 ZW   2008 fu       0

<p>Column headers in this format are often separated by a non-alphanumeric character (e.g.&nbsp;<code>.</code>, <code>-</code>, <code>_</code>, <code>:</code>), or have a fixed width format, like in this dataset. <code><a href="https://tidyr.tidyverse.org/reference/separate.html">separate()</a></code> makes it easy to split a compound variables into individual variables. You can either pass it a regular expression to split on (the default is to split on non alphanumeric columns), or a vector of character positions. In this case we want to split after the first character:</p>

In [16]:
tb3 <- tb2 |> 
  separate(demo, c("sex", "age"), 1)

tb3

      iso2 year sex age  n
1     AD   1996 m   014  0
2     AD   1996 m   1524 0
3     AD   1996 m   2534 0
4     AD   1996 m   3544 4
5     AD   1996 m   4554 1
6     AD   1996 m   5564 0
7     AD   1996 m   65   0
8     AD   1996 f   014  0
9     AD   1996 f   1524 1
10    AD   1996 f   2534 1
11    AD   1996 f   3544 0
12    AD   1996 f   4554 0
13    AD   1996 f   5564 1
14    AD   1996 f   65   0
15    AD   1997 m   014  0
16    AD   1997 m   1524 0
17    AD   1997 m   2534 1
18    AD   1997 m   3544 2
19    AD   1997 m   4554 2
20    AD   1997 m   5564 1
21    AD   1997 m   65   6
22    AD   1997 f   014  0
23    AD   1997 f   1524 1
24    AD   1997 f   2534 2
25    AD   1997 f   3544 3
26    AD   1997 f   4554 0
27    AD   1997 f   5564 0
28    AD   1997 f   65   1
29    AD   1998 m   014  0
30    AD   1998 m   1524 0
⋮     ⋮    ⋮    ⋮   ⋮    ⋮
35721 ZW   2007 m   2534 3693
35722 ZW   2007 m   3544    0
35723 ZW   2007 m   4554  716
35724 ZW   2007 m   5564  292
35725 ZW   2007 m   65    153
35726 ZW   2007 f   04      7
35727 ZW   2007 f   514   178
35728 ZW   2007 f   014   185
35729 ZW   2007 f   1524  739
35730 ZW   2007 f   2534 3311
35731 ZW   2007 f   3544    0
35732 ZW   2007 f   4554  553
35733 ZW   2007 f   5564  213
35734 ZW   2007 f   65     90
35735 ZW   2008 m   014   127
35736 ZW   2008 m   1524  614
35737 ZW   2008 m   2534    0
35738 ZW   2008 m   3544 3316
35739 ZW   2008 m   4554  704
35740 ZW   2008 m   5564  263
35741 ZW   2008 m   65    185
35742 ZW   2008 m   u       0
35743 ZW   2008 f   014   145
35744 ZW   2008 f   1524  840
35745 ZW   2008 f   2534    0
35746 ZW   2008 f   3544 2890
35747 ZW   2008 f   4554  467
35748 ZW   2008 f   5564  174
35749 ZW   2008 f   65    105
35750 ZW   2008 f   u       0

<p>Storing the values in this form resolves a problem in the original data. We want to compare rates, not counts, which means we need to know the population. In the original format, there is no easy way to add a population variable. It has to be stored in a separate table, which makes it hard to correctly match populations to counts. In tidy form, adding variables for population and rate is easy because they’re just additional columns.</p>

<p>In this case, we could also do the transformation in a single step by supplying multiple column names to <code>names_to</code> and also supplying a grouped regular expression to <code>names_pattern</code>:</p>

In [17]:
tb |> pivot_longer(
  !c(iso2, year), 
  names_to = c("sex", "age"), 
  names_pattern = "(.)(.+)",
  values_to = "n", 
  values_drop_na = TRUE
)

      iso2 year sex age  n
1     AD   1996 m   014  0
2     AD   1996 m   1524 0
3     AD   1996 m   2534 0
4     AD   1996 m   3544 4
5     AD   1996 m   4554 1
6     AD   1996 m   5564 0
7     AD   1996 m   65   0
8     AD   1996 f   014  0
9     AD   1996 f   1524 1
10    AD   1996 f   2534 1
11    AD   1996 f   3544 0
12    AD   1996 f   4554 0
13    AD   1996 f   5564 1
14    AD   1996 f   65   0
15    AD   1997 m   014  0
16    AD   1997 m   1524 0
17    AD   1997 m   2534 1
18    AD   1997 m   3544 2
19    AD   1997 m   4554 2
20    AD   1997 m   5564 1
21    AD   1997 m   65   6
22    AD   1997 f   014  0
23    AD   1997 f   1524 1
24    AD   1997 f   2534 2
25    AD   1997 f   3544 3
26    AD   1997 f   4554 0
27    AD   1997 f   5564 0
28    AD   1997 f   65   1
29    AD   1998 m   014  0
30    AD   1998 m   1524 0
⋮     ⋮    ⋮    ⋮   ⋮    ⋮
35721 ZW   2007 m   2534 3693
35722 ZW   2007 m   3544    0
35723 ZW   2007 m   4554  716
35724 ZW   2007 m   5564  292
35725 ZW   2007 m   65    153
35726 ZW   2007 f   04      7
35727 ZW   2007 f   514   178
35728 ZW   2007 f   014   185
35729 ZW   2007 f   1524  739
35730 ZW   2007 f   2534 3311
35731 ZW   2007 f   3544    0
35732 ZW   2007 f   4554  553
35733 ZW   2007 f   5564  213
35734 ZW   2007 f   65     90
35735 ZW   2008 m   014   127
35736 ZW   2008 m   1524  614
35737 ZW   2008 m   2534    0
35738 ZW   2008 m   3544 3316
35739 ZW   2008 m   4554  704
35740 ZW   2008 m   5564  263
35741 ZW   2008 m   65    185
35742 ZW   2008 m   u       0
35743 ZW   2008 f   014   145
35744 ZW   2008 f   1524  840
35745 ZW   2008 f   2534    0
35746 ZW   2008 f   3544 2890
35747 ZW   2008 f   4554  467
35748 ZW   2008 f   5564  174
35749 ZW   2008 f   65    105
35750 ZW   2008 f   u       0

## <h3 id="variables-are-stored-in-both-rows-and-columns">Variables are stored in both rows and columns</h3>

<p>The most complicated form of messy data occurs when variables are stored in both rows and columns. The code below loads daily weather data from the Global Historical Climatology Network for one weather station (MX17004) in Mexico for five months in 2010.</p>

In [18]:
weather <- as_tibble(read.csv("weather.csv", stringsAsFactors = FALSE))
weather

   id                    year month element d1   d2   d3   d4   d5   d6   ⋯ d22
1  MX000017004201001TMAX 2010  1    tmax      NA   NA   NA   NA   NA   NA ⋯ NA
2  MX000017004201001TMIN 2010  1    tmin      NA   NA   NA   NA   NA   NA ⋯ NA
3  MX000017004201002TMAX 2010  2    tmax      NA 27.3 24.1   NA   NA   NA ⋯ NA
4  MX000017004201002TMIN 2010  2    tmin      NA 14.4 14.4   NA   NA   NA ⋯ NA
5  MX000017004201003TMAX 2010  3    tmax      NA   NA   NA   NA 32.1   NA ⋯ NA
6  MX000017004201003TMIN 2010  3    tmin      NA   NA   NA   NA 14.2   NA ⋯ NA
7  MX000017004201004TMAX 2010  4    tmax      NA   NA   NA   NA   NA   NA ⋯ NA
8  MX000017004201004TMIN 2010  4    tmin      NA   NA   NA   NA   NA   NA ⋯ NA
9  MX000017004201005TMAX 2010  5    tmax      NA   NA   NA   NA   NA   NA ⋯ NA
10 MX000017004201005TMIN 2010  5    tmin      NA   NA   NA   NA   NA   NA ⋯ NA
11 MX000017004201006TMAX 2010  6    tmax      NA   NA   NA   NA   NA   NA ⋯ NA
12 MX000017004201006TMIN 2010  6    tmin      NA   NA   NA   NA   NA   NA ⋯ NA
13 MX000017004201007TMAX 2010  7    tmax      NA   NA 28.6   NA   NA   NA ⋯ NA
14 MX000017004201007TMIN 2010  7    tmin      NA   NA 17.5   NA   NA   NA ⋯ NA
15 MX000017004201008TMAX 2010  8    tmax      NA   NA   NA   NA 29.6   NA ⋯ NA
16 MX000017004201008TMIN 2010  8    tmin      NA   NA   NA   NA 15.8   NA ⋯ NA
17 MX000017004201010TMAX 2010 10    tmax      NA   NA   NA   NA 27.0   NA ⋯ NA
18 MX000017004201010TMIN 2010 10    tmin      NA   NA   NA   NA 14.0   NA ⋯ NA
19 MX000017004201011TMAX 2010 11    tmax      NA 31.3   NA 27.2 26.3   NA ⋯ NA
20 MX000017004201011TMIN 2010 11    tmin      NA 16.3   NA 12.0  7.9   NA ⋯ NA
21 MX000017004201012TMAX 2010 12    tmax    29.9   NA   NA   NA   NA 27.8 ⋯ NA
22 MX000017004201012TMIN 2010 12    tmin    13.8   NA   NA   NA   NA 10.5 ⋯ NA
23 MX000017004201101TMAX 2011  1    tmax      NA   NA   NA   NA   NA   NA ⋯ NA
24 MX000017004201101TMIN 2011  1    tmin      NA   NA   NA   NA   NA   NA ⋯ NA
25 MX000017004201102TMAX 2011  2    tmax      NA   NA   NA   NA   NA   NA ⋯ NA
26 MX000017004201102TMIN 2011  2    tmin      NA   NA   NA   NA   NA   NA ⋯ NA
27 MX000017004201103TMAX 2011  3    tmax      NA   NA   NA   NA 33.2   NA ⋯ NA
28 MX000017004201103TMIN 2011  3    tmin      NA   NA   NA   NA 14.8   NA ⋯ NA
29 MX000017004201104TMAX 2011  4    tmax      NA 35.0   NA   NA   NA   NA ⋯ NA
30 MX000017004201104TMIN 2011  4    tmin      NA 16.8   NA   NA   NA   NA ⋯ NA
   d23  d24 d25  d26  d27  d28  d29  d30  d31
1    NA NA    NA   NA   NA   NA   NA 27.8   NA
2    NA NA    NA   NA   NA   NA   NA 14.5   NA
3  29.9 NA    NA   NA   NA   NA   NA   NA   NA
4  10.7 NA    NA   NA   NA   NA   NA   NA   NA
5    NA NA    NA   NA   NA   NA   NA   NA   NA
6    NA NA    NA   NA   NA   NA   NA   NA   NA
7    NA NA    NA   NA 36.3   NA   NA   NA   NA
8    NA NA    NA   NA 16.7   NA   NA   NA   NA
9    NA NA    NA   NA 33.2   NA   NA   NA   NA
10   NA NA    NA   NA 18.2   NA   NA   NA   NA
11   NA NA    NA   NA   NA   NA 30.1   NA   NA
12   NA NA    NA   NA   NA   NA 18.0   NA   NA
13   NA NA    NA   NA   NA   NA   NA   NA   NA
14   NA NA    NA   NA   NA   NA   NA   NA   NA
15 26.4 NA  29.7   NA   NA   NA 28.0   NA 25.4
16 15.0 NA  15.6   NA   NA   NA 15.3   NA 15.4
17   NA NA    NA   NA   NA 31.2   NA   NA   NA
18   NA NA    NA   NA   NA 15.0   NA   NA   NA
19   NA NA    NA 28.1 27.7   NA   NA   NA   NA
20   NA NA    NA 12.1 14.2   NA   NA   NA   NA
21   NA NA    NA   NA   NA   NA   NA   NA   NA
22   NA NA    NA   NA   NA   NA   NA   NA   NA
23   NA NA    NA   NA   NA   NA   NA   NA   NA
24   NA NA    NA   NA   NA   NA   NA   NA   NA
25   NA NA    NA   NA   NA   NA   NA   NA   NA
26   NA NA    NA   NA   NA   NA   NA   NA   NA
27   NA NA    NA 33.2   NA   NA   NA   NA 36.5
28   NA NA    NA 16.2   NA   NA   NA   NA 17.0
29   NA NA    NA   NA   NA   NA   NA   NA   NA
30   NA NA    NA   NA   NA   NA   NA   NA   NA

<p>It has variables in individual columns (<code>id</code>, <code>year</code>, <code>month</code>), spread across columns (<code>day</code>, d1-d31) and across rows (<code>tmin</code>, <code>tmax</code>) (minimum and maximum temperature). Months with fewer than 31 days have structural missing values for the last day(s) of the month.</p>

<p>To tidy this dataset we first use pivot_longer to gather the day columns:</p>

In [19]:
weather2 <- weather |>
  pivot_longer(
    d1:d31, 
    names_to = "day", 
    values_to = "value", 
    values_drop_na = TRUE
  )

weather2

   id                    year month element day value
1  MX000017004201001TMAX 2010 1     tmax    d30 27.8
2  MX000017004201001TMIN 2010 1     tmin    d30 14.5
3  MX000017004201002TMAX 2010 2     tmax    d2  27.3
4  MX000017004201002TMAX 2010 2     tmax    d3  24.1
5  MX000017004201002TMAX 2010 2     tmax    d11 29.7
6  MX000017004201002TMAX 2010 2     tmax    d23 29.9
7  MX000017004201002TMIN 2010 2     tmin    d2  14.4
8  MX000017004201002TMIN 2010 2     tmin    d3  14.4
9  MX000017004201002TMIN 2010 2     tmin    d11 13.4
10 MX000017004201002TMIN 2010 2     tmin    d23 10.7
11 MX000017004201003TMAX 2010 3     tmax    d5  32.1
12 MX000017004201003TMAX 2010 3     tmax    d10 34.5
13 MX000017004201003TMAX 2010 3     tmax    d16 31.1
14 MX000017004201003TMIN 2010 3     tmin    d5  14.2
15 MX000017004201003TMIN 2010 3     tmin    d10 16.8
16 MX000017004201003TMIN 2010 3     tmin    d16 17.6
17 MX000017004201004TMAX 2010 4     tmax    d27 36.3
18 MX000017004201004TMIN 2010 4     tmin    d27 16.7
19 MX000017004201005TMAX 2010 5     tmax    d27 33.2
20 MX000017004201005TMIN 2010 5     tmin    d27 18.2
21 MX000017004201006TMAX 2010 6     tmax    d17 28.0
22 MX000017004201006TMAX 2010 6     tmax    d29 30.1
23 MX000017004201006TMIN 2010 6     tmin    d17 17.5
24 MX000017004201006TMIN 2010 6     tmin    d29 18.0
25 MX000017004201007TMAX 2010 7     tmax    d3  28.6
26 MX000017004201007TMAX 2010 7     tmax    d14 29.9
27 MX000017004201007TMIN 2010 7     tmin    d3  17.5
28 MX000017004201007TMIN 2010 7     tmin    d14 16.5
29 MX000017004201008TMAX 2010 8     tmax    d5  29.6
30 MX000017004201008TMAX 2010 8     tmax    d8  29.0
⋮  ⋮                     ⋮    ⋮     ⋮       ⋮   ⋮
57 MX000017004201011TMAX 2010 11    tmax    d27 27.7
58 MX000017004201011TMIN 2010 11    tmin    d2  16.3
59 MX000017004201011TMIN 2010 11    tmin    d4  12.0
60 MX000017004201011TMIN 2010 11    tmin    d5   7.9
61 MX000017004201011TMIN 2010 11    tmin    d26 12.1
62 MX000017004201011TMIN 2010 11    tmin    d27 14.2
63 MX000017004201012TMAX 2010 12    tmax    d1  29.9
64 MX000017004201012TMAX 2010 12    tmax    d6  27.8
65 MX000017004201012TMIN 2010 12    tmin    d1  13.8
66 MX000017004201012TMIN 2010 12    tmin    d6  10.5
67 MX000017004201101TMAX 2011  1    tmax    d12 29.9
68 MX000017004201101TMAX 2011  1    tmax    d13 28.0
69 MX000017004201101TMIN 2011  1    tmin    d12 12.7
70 MX000017004201101TMIN 2011  1    tmin    d13 11.7
71 MX000017004201102TMAX 2011  2    tmax    d15 30.4
72 MX000017004201102TMAX 2011  2    tmax    d17 31.2
73 MX000017004201102TMAX 2011  2    tmax    d19 31.6
74 MX000017004201102TMIN 2011  2    tmin    d15 13.6
75 MX000017004201102TMIN 2011  2    tmin    d17 13.4
76 MX000017004201102TMIN 2011  2    tmin    d19 12.8
77 MX000017004201103TMAX 2011  3    tmax    d5  33.2
78 MX000017004201103TMAX 2011  3    tmax    d10 32.0
79 MX000017004201103TMAX 2011  3    tmax    d26 33.2
80 MX000017004201103TMAX 2011  3    tmax    d31 36.5
81 MX000017004201103TMIN 2011  3    tmin    d5  14.8
82 MX000017004201103TMIN 2011  3    tmin    d10 12.7
83 MX000017004201103TMIN 2011  3    tmin    d26 16.2
84 MX000017004201103TMIN 2011  3    tmin    d31 17.0
85 MX000017004201104TMAX 2011  4    tmax    d2  35.0
86 MX000017004201104TMIN 2011  4    tmin    d2  16.8

<p>For presentation, I’ve dropped the missing values, making them implicit rather than explicit. This is ok because we know how many days are in each month and can easily reconstruct the explicit missing values.</p>

<p>We’ll also do a little cleaning:</p>

In [28]:
weather3 <- weather2 |>
  mutate(day = as.integer(gsub("d", "", day))) |>
  mutate(id = gsub(".{3}$", "", id)) |>
  select(id, year, month, day, element, value)

weather3

   id                 year month day element value
1  MX000017004201001T 2010 1     30  tmax    27.8
2  MX000017004201001T 2010 1     30  tmin    14.5
3  MX000017004201002T 2010 2      2  tmax    27.3
4  MX000017004201002T 2010 2      3  tmax    24.1
5  MX000017004201002T 2010 2     11  tmax    29.7
6  MX000017004201002T 2010 2     23  tmax    29.9
7  MX000017004201002T 2010 2      2  tmin    14.4
8  MX000017004201002T 2010 2      3  tmin    14.4
9  MX000017004201002T 2010 2     11  tmin    13.4
10 MX000017004201002T 2010 2     23  tmin    10.7
11 MX000017004201003T 2010 3      5  tmax    32.1
12 MX000017004201003T 2010 3     10  tmax    34.5
13 MX000017004201003T 2010 3     16  tmax    31.1
14 MX000017004201003T 2010 3      5  tmin    14.2
15 MX000017004201003T 2010 3     10  tmin    16.8
16 MX000017004201003T 2010 3     16  tmin    17.6
17 MX000017004201004T 2010 4     27  tmax    36.3
18 MX000017004201004T 2010 4     27  tmin    16.7
19 MX000017004201005T 2010 5     27  tmax    33.2
20 MX000017004201005T 2010 5     27  tmin    18.2
21 MX000017004201006T 2010 6     17  tmax    28.0
22 MX000017004201006T 2010 6     29  tmax    30.1
23 MX000017004201006T 2010 6     17  tmin    17.5
24 MX000017004201006T 2010 6     29  tmin    18.0
25 MX000017004201007T 2010 7      3  tmax    28.6
26 MX000017004201007T 2010 7     14  tmax    29.9
27 MX000017004201007T 2010 7      3  tmin    17.5
28 MX000017004201007T 2010 7     14  tmin    16.5
29 MX000017004201008T 2010 8      5  tmax    29.6
30 MX000017004201008T 2010 8      8  tmax    29.0
⋮  ⋮                  ⋮    ⋮     ⋮   ⋮       ⋮
57 MX000017004201011T 2010 11    27  tmax    27.7
58 MX000017004201011T 2010 11     2  tmin    16.3
59 MX000017004201011T 2010 11     4  tmin    12.0
60 MX000017004201011T 2010 11     5  tmin     7.9
61 MX000017004201011T 2010 11    26  tmin    12.1
62 MX000017004201011T 2010 11    27  tmin    14.2
63 MX000017004201012T 2010 12     1  tmax    29.9
64 MX000017004201012T 2010 12     6  tmax    27.8
65 MX000017004201012T 2010 12     1  tmin    13.8
66 MX000017004201012T 2010 12     6  tmin    10.5
67 MX000017004201101T 2011  1    12  tmax    29.9
68 MX000017004201101T 2011  1    13  tmax    28.0
69 MX000017004201101T 2011  1    12  tmin    12.7
70 MX000017004201101T 2011  1    13  tmin    11.7
71 MX000017004201102T 2011  2    15  tmax    30.4
72 MX000017004201102T 2011  2    17  tmax    31.2
73 MX000017004201102T 2011  2    19  tmax    31.6
74 MX000017004201102T 2011  2    15  tmin    13.6
75 MX000017004201102T 2011  2    17  tmin    13.4
76 MX000017004201102T 2011  2    19  tmin    12.8
77 MX000017004201103T 2011  3     5  tmax    33.2
78 MX000017004201103T 2011  3    10  tmax    32.0
79 MX000017004201103T 2011  3    26  tmax    33.2
80 MX000017004201103T 2011  3    31  tmax    36.5
81 MX000017004201103T 2011  3     5  tmin    14.8
82 MX000017004201103T 2011  3    10  tmin    12.7
83 MX000017004201103T 2011  3    26  tmin    16.2
84 MX000017004201103T 2011  3    31  tmin    17.0
85 MX000017004201104T 2011  4     2  tmax    35.0
86 MX000017004201104T 2011  4     2  tmin    16.8

<p>This dataset is mostly tidy, but the <code>element</code> column is not a variable; it stores the names of variables. (Not shown in this example are the other meteorological variables <code>prcp</code> (precipitation) and <code>snow</code> (snowfall)). Fixing this requires widening the data: <code><a href="../reference/pivot_wider.html">pivot_wider()</a></code> is inverse of <code><a href="../reference/pivot_longer.html">pivot_longer()</a></code>, pivoting <code>element</code> and <code>value</code> back out across multiple columns:</p>

In [29]:
weather3 |>
  pivot_wider(names_from = element, values_from = value)

   id                 year month day tmax tmin
1  MX000017004201001T 2010  1    30  27.8 14.5
2  MX000017004201002T 2010  2     2  27.3 14.4
3  MX000017004201002T 2010  2     3  24.1 14.4
4  MX000017004201002T 2010  2    11  29.7 13.4
5  MX000017004201002T 2010  2    23  29.9 10.7
6  MX000017004201003T 2010  3     5  32.1 14.2
7  MX000017004201003T 2010  3    10  34.5 16.8
8  MX000017004201003T 2010  3    16  31.1 17.6
9  MX000017004201004T 2010  4    27  36.3 16.7
10 MX000017004201005T 2010  5    27  33.2 18.2
11 MX000017004201006T 2010  6    17  28.0 17.5
12 MX000017004201006T 2010  6    29  30.1 18.0
13 MX000017004201007T 2010  7     3  28.6 17.5
14 MX000017004201007T 2010  7    14  29.9 16.5
15 MX000017004201008T 2010  8     5  29.6 15.8
16 MX000017004201008T 2010  8     8  29.0 17.3
17 MX000017004201008T 2010  8    13  29.8 16.5
18 MX000017004201008T 2010  8    23  26.4 15.0
19 MX000017004201008T 2010  8    25  29.7 15.6
20 MX000017004201008T 2010  8    29  28.0 15.3
21 MX000017004201008T 2010  8    31  25.4 15.4
22 MX000017004201010T 2010 10     5  27.0 14.0
23 MX000017004201010T 2010 10     7  28.1 12.9
24 MX000017004201010T 2010 10    14  29.5 13.0
25 MX000017004201010T 2010 10    15  28.7 10.5
26 MX000017004201010T 2010 10    28  31.2 15.0
27 MX000017004201011T 2010 11     2  31.3 16.3
28 MX000017004201011T 2010 11     4  27.2 12.0
29 MX000017004201011T 2010 11     5  26.3  7.9
30 MX000017004201011T 2010 11    26  28.1 12.1
31 MX000017004201011T 2010 11    27  27.7 14.2
32 MX000017004201012T 2010 12     1  29.9 13.8
33 MX000017004201012T 2010 12     6  27.8 10.5
34 MX000017004201101T 2011  1    12  29.9 12.7
35 MX000017004201101T 2011  1    13  28.0 11.7
36 MX000017004201102T 2011  2    15  30.4 13.6
37 MX000017004201102T 2011  2    17  31.2 13.4
38 MX000017004201102T 2011  2    19  31.6 12.8
39 MX000017004201103T 2011  3     5  33.2 14.8
40 MX000017004201103T 2011  3    10  32.0 12.7
41 MX000017004201103T 2011  3    26  33.2 16.2
42 MX000017004201103T 2011  3    31  36.5 17.0
43 MX000017004201104T 2011  4     2  35.0 16.8

<p>This form is tidy: there’s one variable in each column, and each row represents one day.</p>

## <h3 id="multiple-types">Multiple types in one table</h3>

<p>Datasets often involve values collected at multiple levels, on different types of observational units. During tidying, each type of observational unit should be stored in its own table. This is closely related to the idea of database normalisation, where each fact is expressed in only one place. It’s important because otherwise inconsistencies can arise.</p>

<p>The billboard dataset actually contains observations on two types of observational units: the song and its rank in each week. This manifests itself through the duplication of facts about the song: <code>artist</code> is repeated many times.</p>

<p>This dataset needs to be broken down into two pieces: a song dataset which stores <code>artist</code> and <code>song name</code>, and a ranking dataset which gives the <code>rank</code> of the <code>song</code> in each <code>week</code>. We first extract a <code>song</code> dataset:</p>

In [33]:
song <- billboard3 |>
  distinct(artist, track) |>
  mutate(song_id = row_number())

song

    artist               track                   song_id
1   2 Pac                Baby Don't Cry (Keep...  1
2   2Ge+her              The Hardest Part Of ...  2
3   3 Doors Down         Kryptonite               3
4   3 Doors Down         Loser                    4
5   504 Boyz             Wobble Wobble            5
6   98^0                 Give Me Just One Nig...  6
7   A*Teens              Dancing Queen            7
8   Aaliyah              I Don't Wanna            8
9   Aaliyah              Try Again                9
10  Adams, Yolanda       Open My Heart           10
11  Adkins, Trace        More                    11
12  Aguilera, Christina  Come On Over Baby (A... 12
13  Aguilera, Christina  I Turn To You           13
14  Aguilera, Christina  What A Girl Wants       14
15  Alice Deejay         Better Off Alone        15
16  Allan, Gary          Smoke Rings In The D... 16
17  Amber                Sexual                  17
18  Anastacia            I'm Outta Love          18
19  Anthony, Marc        My Baby You             19
20  Anthony, Marc        You Sang To Me          20
21  Avant                My First Love           21
22  Avant                Separated               22
23  BBMak                Back Here               23
24  Backstreet Boys, The Shape Of My Heart       24
25  Backstreet Boys, The Show Me The Meaning ... 25
26  Backstreet Boys, The The One                 26
27  Badu, Erkyah         Bag Lady                27
28  Baha Men             Who Let The Dogs Out    28
29  Barenaked Ladies     Pinch Me                29
30  Beenie Man           Girls Dem Sugar         30
⋮   ⋮                    ⋮                       ⋮
288 Thomas, Carl         Emotional               288
289 Thomas, Carl         I Wish                  289
290 Thomas, Carl         Summer Rain             290
291 Tippin, Aaron        Kiss This               291
292 Train                Meet Virginia           292
293 Trick Daddy          Shut Up                 293
294 Trina                Pull Over               294
295 Tritt, Travis        Best Of Intentions      295
296 Tuesday              I Know                  296
297 Urban, Keith         Your Everything         297
298 Usher                Pop Ya Collar           298
299 Vassar, Phil         Carlene                 299
300 Vassar, Phil         Just Another Day In ... 300
301 Vertical Horizon     Everything You Want     301
302 Vertical Horizon     You're A God            302
303 Vitamin C            Graduation (Friends ... 303
304 Vitamin C            The Itch                304
305 Walker, Clay         Live, Laugh, Love       305
306 Walker, Clay         The Chain Of Love       306
307 Wallflowers, The     Sleepwalker             307
308 Westlife             Swear It Again          308
309 Williams, Robbie     Angels                  309
310 Wills, Mark          Back At One             310
311 Worley, Darryl       When You Need My Lov... 311
312 Wright, Chely        It Was                  312
313 Yankee Grey          Another Nine Minutes    313
314 Yearwood, Trisha     Real Live Woman         314
315 Ying Yang Twins      Whistle While You Tw... 315
316 Zombie Nation        Kernkraft 400           316
317 matchbox twenty      Bent                    317

<p>Then use that to make a <code>rank</code> dataset by replacing repeated song facts with a pointer to song details (a unique song id):</p>

In [34]:
rank <- billboard3 |>
  left_join(song, c("artist", "track")) |>
  select(song_id, date, week, rank)

rank

     song_id date       week rank
1    1       2000-02-26  1   87
2    1       2000-03-04  2   82
3    1       2000-03-11  3   72
4    1       2000-03-18  4   77
5    1       2000-03-25  5   87
6    1       2000-04-01  6   94
7    1       2000-04-08  7   99
8    2       2000-09-02  1   91
9    2       2000-09-09  2   87
10   2       2000-09-16  3   92
11   3       2000-04-08  1   81
12   3       2000-04-15  2   70
13   3       2000-04-22  3   68
14   3       2000-04-29  4   67
15   3       2000-05-06  5   66
16   3       2000-05-13  6   57
17   3       2000-05-20  7   54
18   3       2000-05-27  8   53
19   3       2000-06-03  9   51
20   3       2000-06-10 10   51
21   3       2000-06-17 11   51
22   3       2000-06-24 12   51
23   3       2000-07-01 13   47
24   3       2000-07-08 14   44
25   3       2000-07-15 15   38
26   3       2000-07-22 16   28
27   3       2000-07-29 17   22
28   3       2000-08-05 18   18
29   3       2000-08-12 19   18
30   3       2000-08-19 20   14
⋮    ⋮       ⋮          ⋮    ⋮
5278 317     2000-07-01 10   12
5279 317     2000-07-08 11    8
5280 317     2000-07-15 12    6
5281 317     2000-07-22 13    1
5282 317     2000-07-29 14    2
5283 317     2000-08-05 15    3
5284 317     2000-08-12 16    2
5285 317     2000-08-19 17    2
5286 317     2000-08-26 18    3
5287 317     2000-09-02 19    4
5288 317     2000-09-09 20    5
5289 317     2000-09-16 21    4
5290 317     2000-09-23 22    4
5291 317     2000-09-30 23    6
5292 317     2000-10-07 24    9
5293 317     2000-10-14 25   12
5294 317     2000-10-21 26   13
5295 317     2000-10-28 27   19
5296 317     2000-11-04 28   20
5297 317     2000-11-11 29   20
5298 317     2000-11-18 30   24
5299 317     2000-11-25 31   29
5300 317     2000-12-02 32   28
5301 317     2000-12-09 33   27
5302 317     2000-12-16 34   30
5303 317     2000-12-23 35   33
5304 317     2000-12-30 36   37
5305 317     2001-01-06 37   38
5306 317     2001-01-13 38   38
5307 317     2001-01-20 39   48

<p>You could also imagine a <code>week</code> dataset which would record background information about the week, maybe the total number of songs sold or similar “demographic” information.</p>

<p>Normalisation is useful for tidying and eliminating inconsistencies. However, there are few data analysis tools that work directly with relational data, so analysis usually also requires denormalisation or the merging the datasets back into one table.</p>

## <h3 id="one-type-in-multiple-tables">One type in multiple tables</h3>

<p>It’s also common to find data values about a single type of observational unit spread out over multiple tables or files. These tables and files are often split up by another variable, so that each represents a single year, person, or location. As long as the format for individual records is consistent, this is an easy problem to fix:</p>

<ol>
<li><p>Read the files into a list of tables.</p></li>
<li><p>For each table, add a new column that records the original file name (the file name is often the value of an important variable).</p></li>
<li><p>Combine all tables into a single table.</p></li>
</ol>

<p>Purrr makes this straightforward in R. The following code generates a vector of file names in a directory (<code>data/</code>) which match a regular expression (ends in <code>.csv</code>). Next we name each element of the vector with the name of the file. We do this because will preserve the names in the following step, ensuring that each row in the final data frame is labeled with its source. Finally, <code><a href="https://purrr.tidyverse.org/reference/map_dfr.html">map_dfr()</a></code> loops over each path, reading in the csv file and
combining the results into a single data frame.</p>

In [39]:
library(purrr)

paths <- dir("data", pattern = "\\.csv$", full.names = TRUE)
names(paths) <- basename(paths)
map_dfr(paths, read.csv, stringsAsFactors = FALSE, .id = "filename")

<p>Once you have a single table, you can perform additional tidying as needed. An example of this type of cleaning can be found at <a href="https://github.com/hadley/data-baby-names">https://github.com/hadley/data-baby-names</a> which takes 129 yearly baby name tables provided by the US Social Security Administration and combines them into a single file.</p>

<p>A more complicated situation occurs when the dataset structure changes over time. For example, the datasets may contain different variables, the same variables with different names, different file formats, or different conventions for missing values. This may require you to tidy each file to individually (or, if you’re lucky, in small groups) and then combine them once tidied. An example of this type of tidying is illustrated in <a href="https://github.com/hadley/data-fuel-economy">https://github.com/hadley/data-fuel-economy</a>, which shows the tidying of <span>epa</span> fuel economy data for over 50,000 cars from 1978 to 2008. The raw data is available online, but each year is stored in a separate file and there are four major formats with many minor variations, making tidying this dataset a considerable challenge.</p>