# Imports

In [186]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 10)

# Constants

In [187]:
CD_CONTA = 'Código da Conta'
DS_CONTA = 'Descrição da Conta'

# User defined functions

In [188]:
def get_len_key(df):
    return [len(key) for key in df[CD_CONTA]]

In [189]:
def get_min_len(len_key):
    return np.array(len_key).min()

In [190]:
def get_ind_min_len(df, min_len):
    len_key = get_len_key(df)
    return np.where(len_key==min_len)

In [191]:
def get_drop_mask(merge_df, len_key, min_len):
    can_drop = (merge_df[CD_CONTA] == merge_df.shift(-1)[CD_CONTA])
    return (len_key == min_len) & (can_drop == True)

# Read from file

In [192]:
try:
    df = pd.read_csv('Financial_Statement.csv', sep=';')
except Exception as e:
    print(f"Error: {e}")

In [193]:
df

,Código da Conta,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1,Ativo Total,2.775.558,2.369.285
1,1.01,Ativo Circulante,1.875.214,1.651.950
2,1.01.01,Caixa e Equivalentes de Caixa,815.476,683.412
3,1.01.03,Contas a Receber,258.104,206.005
4,1.01.03.01,Clientes,258.104,206.005
...,...,...,...,...
18,1.02.01.10.04,Instrumentos financeiros derivativos,893,0
19,1.02.01.10.05,Outras contas a receber,904,1.205
20,1.02.02,Investimentos,6.505,5.934
21,1.02.03,Imobilizado,786.627,619.172
22,1.02.04,Intangível,2.268,1.288

# Wrangling

## Round 1

In [194]:
round = 1

In [195]:
df

,Código da Conta,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1,Ativo Total,2.775.558,2.369.285
1,1.01,Ativo Circulante,1.875.214,1.651.950
2,1.01.01,Caixa e Equivalentes de Caixa,815.476,683.412
3,1.01.03,Contas a Receber,258.104,206.005
4,1.01.03.01,Clientes,258.104,206.005
...,...,...,...,...
18,1.02.01.10.04,Instrumentos financeiros derivativos,893,0
19,1.02.01.10.05,Outras contas a receber,904,1.205
20,1.02.02,Investimentos,6.505,5.934
21,1.02.03,Imobilizado,786.627,619.172
22,1.02.04,Intangível,2.268,1.288

### Merge

In [196]:
len_key = get_len_key(df)
min_len = get_min_len(len_key)
ind_min_len = get_ind_min_len(df, min_len)  # ind_min_len = index of key 'Código da Conta' with minimum length

In [197]:
df.iloc[ind_min_len]

  Código da Conta Descrição da Conta Trimestre Atual Exercício Anterior
0               1        Ativo Total       2.775.558          2.369.285

In [198]:
merge_keys = df[CD_CONTA].apply(lambda string: string[:min_len])
merge_df = pd.merge(merge_keys, df[[CD_CONTA, DS_CONTA]], how='left')

In [199]:
merge_df

   Código da Conta Descrição da Conta
0                1        Ativo Total
1                1        Ativo Total
2                1        Ativo Total
3                1        Ativo Total
4                1        Ativo Total
..             ...                ...
18               1        Ativo Total
19               1        Ativo Total
20               1        Ativo Total
21               1        Ativo Total
22               1        Ativo Total

[23 rows x 2 columns]

In [200]:
df.insert(round, f'{DS_CONTA} {round}', merge_df[DS_CONTA])

In [201]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1,Ativo Total,Ativo Total,2.775.558,2.369.285
1,1.01,Ativo Total,Ativo Circulante,1.875.214,1.651.950
2,1.01.01,Ativo Total,Caixa e Equivalentes de Caixa,815.476,683.412
3,1.01.03,Ativo Total,Contas a Receber,258.104,206.005
4,1.01.03.01,Ativo Total,Clientes,258.104,206.005
...,...,...,...,...,...
18,1.02.01.10.04,Ativo Total,Instrumentos financeiros derivativos,893,0
19,1.02.01.10.05,Ativo Total,Outras contas a receber,904,1.205
20,1.02.02,Ativo Total,Investimentos,6.505,5.934
21,1.02.03,Ativo Total,Imobilizado,786.627,619.172
22,1.02.04,Ativo Total,Intangível,2.268,1.288

### Drop

In [202]:
drop_mask = get_drop_mask(merge_df, len_key, min_len)

In [203]:
df[drop_mask]

,Código da Conta,Descrição da Conta 1,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1,Ativo Total,Ativo Total,2.775.558,2.369.285

In [204]:
df = df.drop(df[drop_mask].index)
df = df.reset_index(drop=True)

## Round 2

In [205]:
round = 2

In [206]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01,Ativo Total,Ativo Circulante,1.875.214,1.651.950
1,1.01.01,Ativo Total,Caixa e Equivalentes de Caixa,815.476,683.412
2,1.01.03,Ativo Total,Contas a Receber,258.104,206.005
3,1.01.03.01,Ativo Total,Clientes,258.104,206.005
4,1.01.04,Ativo Total,Estoques,629.601,617.289
...,...,...,...,...,...
17,1.02.01.10.04,Ativo Total,Instrumentos financeiros derivativos,893,0
18,1.02.01.10.05,Ativo Total,Outras contas a receber,904,1.205
19,1.02.02,Ativo Total,Investimentos,6.505,5.934
20,1.02.03,Ativo Total,Imobilizado,786.627,619.172
21,1.02.04,Ativo Total,Intangível,2.268,1.288

### Merge

In [207]:
len_key = get_len_key(df)
min_len = get_min_len(len_key)
ind_min_len = get_ind_min_len(df, min_len)

In [208]:
df.iloc[ind_min_len]

,Código da Conta,Descrição da Conta 1,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01,Ativo Total,Ativo Circulante,1.875.214,1.651.950
11,1.02,Ativo Total,Ativo Não Circulante,900.344,717.335

In [209]:
merge_keys = df[CD_CONTA].apply(lambda string: string[:min_len])
merge_df = pd.merge(merge_keys, df[[CD_CONTA, DS_CONTA]], how='left')

In [210]:
merge_df

   Código da Conta    Descrição da Conta
0             1.01      Ativo Circulante
1             1.01      Ativo Circulante
2             1.01      Ativo Circulante
3             1.01      Ativo Circulante
4             1.01      Ativo Circulante
..             ...                   ...
17            1.02  Ativo Não Circulante
18            1.02  Ativo Não Circulante
19            1.02  Ativo Não Circulante
20            1.02  Ativo Não Circulante
21            1.02  Ativo Não Circulante

[22 rows x 2 columns]

In [211]:
df.insert(round, f'{DS_CONTA} {round}', merge_df[DS_CONTA])

In [212]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01,Ativo Total,Ativo Circulante,Ativo Circulante,1.875.214,1.651.950
1,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,815.476,683.412
2,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,258.104,206.005
3,1.01.03.01,Ativo Total,Ativo Circulante,Clientes,258.104,206.005
4,1.01.04,Ativo Total,Ativo Circulante,Estoques,629.601,617.289
...,...,...,...,...,...,...
17,1.02.01.10.04,Ativo Total,Ativo Não Circulante,Instrumentos financeiros derivativos,893,0
18,1.02.01.10.05,Ativo Total,Ativo Não Circulante,Outras contas a receber,904,1.205
19,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,6.505,5.934
20,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,786.627,619.172
21,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,2.268,1.288

### Drop

In [213]:
drop_mask = get_drop_mask(merge_df, len_key, min_len)

In [214]:
df[drop_mask]

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01,Ativo Total,Ativo Circulante,Ativo Circulante,1.875.214,1.651.950
11,1.02,Ativo Total,Ativo Não Circulante,Ativo Não Circulante,900.344,717.335

In [215]:
df = df.drop(df[drop_mask].index)
df = df.reset_index(drop=True)

## Round 3

In [216]:
round = 3

In [217]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,815.476,683.412
1,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,258.104,206.005
2,1.01.03.01,Ativo Total,Ativo Circulante,Clientes,258.104,206.005
3,1.01.04,Ativo Total,Ativo Circulante,Estoques,629.601,617.289
4,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,92.690,80.862
...,...,...,...,...,...,...
15,1.02.01.10.04,Ativo Total,Ativo Não Circulante,Instrumentos financeiros derivativos,893,0
16,1.02.01.10.05,Ativo Total,Ativo Não Circulante,Outras contas a receber,904,1.205
17,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,6.505,5.934
18,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,786.627,619.172
19,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,2.268,1.288

### Merge

In [218]:
len_key = get_len_key(df)
min_len = get_min_len(len_key)
ind_min_len = get_ind_min_len(df, min_len)

In [219]:
df.iloc[ind_min_len]

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,815.476,683.412
1,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,258.104,206.005
3,1.01.04,Ativo Total,Ativo Circulante,Estoques,629.601,617.289
4,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,92.690,80.862
5,1.01.08,Ativo Total,Ativo Circulante,Outros Ativos Circulantes,79.343,64.382
10,1.02.01,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,104.944,90.941
17,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,6.505,5.934
18,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,786.627,619.172
19,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,2.268,1.288

In [220]:
merge_keys = df[CD_CONTA].apply(lambda string: string[:min_len])
merge_df = pd.merge(merge_keys, df[[CD_CONTA, DS_CONTA]], how='left')

In [221]:
merge_df

   Código da Conta              Descrição da Conta
0          1.01.01   Caixa e Equivalentes de Caixa
1          1.01.03                Contas a Receber
2          1.01.03                Contas a Receber
3          1.01.04                        Estoques
4          1.01.06            Tributos a Recuperar
..             ...                             ...
15         1.02.01  Ativo Realizável a Longo Prazo
16         1.02.01  Ativo Realizável a Longo Prazo
17         1.02.02                   Investimentos
18         1.02.03                     Imobilizado
19         1.02.04                      Intangível

[20 rows x 2 columns]

In [222]:
df.insert(round, f'{DS_CONTA} {round}', merge_df[DS_CONTA])

In [223]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta 3,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,Caixa e Equivalentes de Caixa,815.476,683.412
1,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,Contas a Receber,258.104,206.005
2,1.01.03.01,Ativo Total,Ativo Circulante,Contas a Receber,Clientes,258.104,206.005
3,1.01.04,Ativo Total,Ativo Circulante,Estoques,Estoques,629.601,617.289
4,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,Tributos a Recuperar,92.690,80.862
...,...,...,...,...,...,...,...
15,1.02.01.10.04,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,Instrumentos financeiros derivativos,893,0
16,1.02.01.10.05,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,Outras contas a receber,904,1.205
17,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,Investimentos,6.505,5.934
18,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,Imobilizado,786.627,619.172
19,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,Intangível,2.268,1.288

### Drop

In [224]:
drop_mask = get_drop_mask(merge_df, len_key, min_len)

In [225]:
df[drop_mask]

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta 3,Descrição da Conta,Trimestre Atual,Exercício Anterior
1,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,Contas a Receber,258.104,206.005
5,1.01.08,Ativo Total,Ativo Circulante,Outros Ativos Circulantes,Outros Ativos Circulantes,79.343,64.382
10,1.02.01,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,Ativo Realizável a Longo Prazo,104.944,90.941

In [226]:
df = df.drop(df[drop_mask].index)
df = df.reset_index(drop=True)

In [227]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta 3,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,Caixa e Equivalentes de Caixa,815.476,683.412
1,1.01.03.01,Ativo Total,Ativo Circulante,Contas a Receber,Clientes,258.104,206.005
2,1.01.04,Ativo Total,Ativo Circulante,Estoques,Estoques,629.601,617.289
3,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,Tributos a Recuperar,92.690,80.862
4,1.01.08.03,Ativo Total,Ativo Circulante,Outros Ativos Circulantes,Outros,79.343,64.382
...,...,...,...,...,...,...,...
12,1.02.01.10.04,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,Instrumentos financeiros derivativos,893,0
13,1.02.01.10.05,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,Outras contas a receber,904,1.205
14,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,Investimentos,6.505,5.934
15,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,Imobilizado,786.627,619.172
16,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,Intangível,2.268,1.288

## Round 4

In [228]:
round = 4

In [229]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta 3,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,Caixa e Equivalentes de Caixa,815.476,683.412
1,1.01.03.01,Ativo Total,Ativo Circulante,Contas a Receber,Clientes,258.104,206.005
2,1.01.04,Ativo Total,Ativo Circulante,Estoques,Estoques,629.601,617.289
3,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,Tributos a Recuperar,92.690,80.862
4,1.01.08.03,Ativo Total,Ativo Circulante,Outros Ativos Circulantes,Outros,79.343,64.382
...,...,...,...,...,...,...,...
12,1.02.01.10.04,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,Instrumentos financeiros derivativos,893,0
13,1.02.01.10.05,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,Outras contas a receber,904,1.205
14,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,Investimentos,6.505,5.934
15,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,Imobilizado,786.627,619.172
16,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,Intangível,2.268,1.288

### Merge

In [230]:
len_key = get_len_key(df)
min_len = get_min_len(len_key)
ind_min_len = get_ind_min_len(df, min_len)

In [231]:
df.iloc[ind_min_len]

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta 3,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,Caixa e Equivalentes de Caixa,815.476,683.412
2,1.01.04,Ativo Total,Ativo Circulante,Estoques,Estoques,629.601,617.289
3,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,Tributos a Recuperar,92.690,80.862
14,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,Investimentos,6.505,5.934
15,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,Imobilizado,786.627,619.172
16,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,Intangível,2.268,1.288