In [135]:
import numpy as np
import pandas as pd

pd.set_option('display.max_rows', 10)

In [136]:
try:
    df = pd.read_csv('Financial_Statement.csv', sep=';')
except Exception as e:
    print(f"Error: {e}")

In [137]:
df

,Código da Conta,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1,Ativo Total,2.775.558,2.369.285
1,1.01,Ativo Circulante,1.875.214,1.651.950
2,1.01.01,Caixa e Equivalentes de Caixa,815.476,683.412
3,1.01.03,Contas a Receber,258.104,206.005
4,1.01.03.01,Clientes,258.104,206.005
...,...,...,...,...
18,1.02.01.10.04,Instrumentos financeiros derivativos,893,0
19,1.02.01.10.05,Outras contas a receber,904,1.205
20,1.02.02,Investimentos,6.505,5.934
21,1.02.03,Imobilizado,786.627,619.172
22,1.02.04,Intangível,2.268,1.288

In [138]:
df['Código da Conta']

0                 1
1              1.01
2           1.01.01
3           1.01.03
4        1.01.03.01
          ...
18    1.02.01.10.04
19    1.02.01.10.05
20          1.02.02
21          1.02.03
22          1.02.04
Name: Código da Conta, Length: 23, dtype: object

In [139]:
CD_CONTA_1 = df['Código da Conta'].apply(lambda string: ".".join(string.split('.')[:1]))

In [140]:
CD_CONTA_1

0     1
1     1
2     1
3     1
4     1
     ..
18    1
19    1
20    1
21    1
22    1
Name: Código da Conta, Length: 23, dtype: object

In [141]:
DS_CONTA_1 = pd.merge(CD_CONTA_1, df[['Código da Conta', 'Descrição da Conta']], how='left')
DS_CONTA_1

   Código da Conta Descrição da Conta
0                1        Ativo Total
1                1        Ativo Total
2                1        Ativo Total
3                1        Ativo Total
4                1        Ativo Total
..             ...                ...
18               1        Ativo Total
19               1        Ativo Total
20               1        Ativo Total
21               1        Ativo Total
22               1        Ativo Total

[23 rows x 2 columns]

In [142]:
df.insert(1, 'Descrição da Conta 1', DS_CONTA_1['Descrição da Conta'])

In [143]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1,Ativo Total,Ativo Total,2.775.558,2.369.285
1,1.01,Ativo Total,Ativo Circulante,1.875.214,1.651.950
2,1.01.01,Ativo Total,Caixa e Equivalentes de Caixa,815.476,683.412
3,1.01.03,Ativo Total,Contas a Receber,258.104,206.005
4,1.01.03.01,Ativo Total,Clientes,258.104,206.005
...,...,...,...,...,...
18,1.02.01.10.04,Ativo Total,Instrumentos financeiros derivativos,893,0
19,1.02.01.10.05,Ativo Total,Outras contas a receber,904,1.205
20,1.02.02,Ativo Total,Investimentos,6.505,5.934
21,1.02.03,Ativo Total,Imobilizado,786.627,619.172
22,1.02.04,Ativo Total,Intangível,2.268,1.288

In [144]:
len_key = [len(key) for key in df['Código da Conta']]   # len_key = length of key
min_len = np.array(len_key).min()  # min_len = minimum length
ind_min_len = np.where(len_key==min_len)  # ind_min_len = index of key 'Código da Conta' with minimum length

In [145]:
df.iloc[ind_min_len]

,Código da Conta,Descrição da Conta 1,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1,Ativo Total,Ativo Total,2.775.558,2.369.285

In [146]:
df = df.drop(df.index[ind_min_len])
df.reset_index(inplace=True, drop=True)

In [147]:
CD_CONTA_2 = df['Código da Conta'].apply(lambda string: ".".join(string.split('.')[:2]))

In [148]:
CD_CONTA_2

0     1.01
1     1.01
2     1.01
3     1.01
4     1.01
      ...
17    1.02
18    1.02
19    1.02
20    1.02
21    1.02
Name: Código da Conta, Length: 22, dtype: object

In [149]:
DS_CONTA_2 = pd.merge(CD_CONTA_2, df[['Código da Conta', 'Descrição da Conta']], how='left')

In [150]:
DS_CONTA_2

   Código da Conta    Descrição da Conta
0             1.01      Ativo Circulante
1             1.01      Ativo Circulante
2             1.01      Ativo Circulante
3             1.01      Ativo Circulante
4             1.01      Ativo Circulante
..             ...                   ...
17            1.02  Ativo Não Circulante
18            1.02  Ativo Não Circulante
19            1.02  Ativo Não Circulante
20            1.02  Ativo Não Circulante
21            1.02  Ativo Não Circulante

[22 rows x 2 columns]

In [151]:
df.insert(2, 'Descrição da Conta 2', DS_CONTA_2['Descrição da Conta'])

In [152]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01,Ativo Total,Ativo Circulante,Ativo Circulante,1.875.214,1.651.950
1,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,815.476,683.412
2,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,258.104,206.005
3,1.01.03.01,Ativo Total,Ativo Circulante,Clientes,258.104,206.005
4,1.01.04,Ativo Total,Ativo Circulante,Estoques,629.601,617.289
...,...,...,...,...,...,...
17,1.02.01.10.04,Ativo Total,Ativo Não Circulante,Instrumentos financeiros derivativos,893,0
18,1.02.01.10.05,Ativo Total,Ativo Não Circulante,Outras contas a receber,904,1.205
19,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,6.505,5.934
20,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,786.627,619.172
21,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,2.268,1.288

In [153]:
len_key = [len(key) for key in df['Código da Conta']]   # len_key = length of key
min_len = np.array(len_key).min()  # min_len = minimum length
ind_min_len = np.where(len_key==min_len)  # ind_min_len = index of key 'Código da Conta' with minimum length

In [154]:
df.iloc[ind_min_len]

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior
0,1.01,Ativo Total,Ativo Circulante,Ativo Circulante,1.875.214,1.651.950
11,1.02,Ativo Total,Ativo Não Circulante,Ativo Não Circulante,900.344,717.335

In [155]:
df = df.drop(df.index[ind_min_len])
df.reset_index(inplace=True, drop=True)

In [156]:
CD_CONTA_3 = df['Código da Conta'].apply(lambda string: ".".join(string.split('.')[:3]))

In [157]:
CD_CONTA_3

0     1.01.01
1     1.01.03
2     1.01.03
3     1.01.04
4     1.01.06
       ...
15    1.02.01
16    1.02.01
17    1.02.02
18    1.02.03
19    1.02.04
Name: Código da Conta, Length: 20, dtype: object

In [158]:
DS_CONTA_3 = pd.merge(CD_CONTA_3, df[['Código da Conta', 'Descrição da Conta']], how='left')

In [159]:
DS_CONTA_3

   Código da Conta              Descrição da Conta
0          1.01.01   Caixa e Equivalentes de Caixa
1          1.01.03                Contas a Receber
2          1.01.03                Contas a Receber
3          1.01.04                        Estoques
4          1.01.06            Tributos a Recuperar
..             ...                             ...
15         1.02.01  Ativo Realizável a Longo Prazo
16         1.02.01  Ativo Realizável a Longo Prazo
17         1.02.02                   Investimentos
18         1.02.03                     Imobilizado
19         1.02.04                      Intangível

[20 rows x 2 columns]

In [160]:
df['Descrição da Conta 3'] = DS_CONTA_3['Descrição da Conta']

In [161]:
df

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior,Descrição da Conta 3
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,815.476,683.412,Caixa e Equivalentes de Caixa
1,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,258.104,206.005,Contas a Receber
2,1.01.03.01,Ativo Total,Ativo Circulante,Clientes,258.104,206.005,Contas a Receber
3,1.01.04,Ativo Total,Ativo Circulante,Estoques,629.601,617.289,Estoques
4,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,92.690,80.862,Tributos a Recuperar
...,...,...,...,...,...,...,...
15,1.02.01.10.04,Ativo Total,Ativo Não Circulante,Instrumentos financeiros derivativos,893,0,Ativo Realizável a Longo Prazo
16,1.02.01.10.05,Ativo Total,Ativo Não Circulante,Outras contas a receber,904,1.205,Ativo Realizável a Longo Prazo
17,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,6.505,5.934,Investimentos
18,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,786.627,619.172,Imobilizado
19,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,2.268,1.288,Intangível

In [162]:
len_key = [len(key) for key in df['Código da Conta']]   # len_key = length of key 'Código da Conta'
min_len = np.array(len_key).min()  # min_len = minimum length
ind_min_len = np.where(len_key==min_len)  # ind_min_len = index of key 'Código da Conta' with minimum length

In [163]:
df.iloc[ind_min_len]

,Código da Conta,Descrição da Conta 1,Descrição da Conta 2,Descrição da Conta,Trimestre Atual,Exercício Anterior,Descrição da Conta 3
0,1.01.01,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa,815.476,683.412,Caixa e Equivalentes de Caixa
1,1.01.03,Ativo Total,Ativo Circulante,Contas a Receber,258.104,206.005,Contas a Receber
3,1.01.04,Ativo Total,Ativo Circulante,Estoques,629.601,617.289,Estoques
4,1.01.06,Ativo Total,Ativo Circulante,Tributos a Recuperar,92.690,80.862,Tributos a Recuperar
5,1.01.08,Ativo Total,Ativo Circulante,Outros Ativos Circulantes,79.343,64.382,Outros Ativos Circulantes
10,1.02.01,Ativo Total,Ativo Não Circulante,Ativo Realizável a Longo Prazo,104.944,90.941,Ativo Realizável a Longo Prazo
17,1.02.02,Ativo Total,Ativo Não Circulante,Investimentos,6.505,5.934,Investimentos
18,1.02.03,Ativo Total,Ativo Não Circulante,Imobilizado,786.627,619.172,Imobilizado
19,1.02.04,Ativo Total,Ativo Não Circulante,Intangível,2.268,1.288,Intangível

In [164]:
# Agora preciso "dropar" os Códigos de comprimento 7, porém somente se eles são uma categoria superior de alguma subcategoria.
# Se não, não precisa cortar. Por exemplo: 1.01.01 não tem nenhuma outra subcategoria, então eu não vou cortar fora.
# 1.01.03, ao contrário, tem um elemento: 1.01.03.01. Logo, a linha correspondente pode ser cortada fora.
# Como fazer isso?
# Além disso: como resolver o problema dos NaN?