<h1><b>Indexing, Selecting &amp; Assigning</b></h1>
<span>Pro data scientists do this dozens of times a day. You can, too!</span>

# <h2 id="Introduction">Introduction</h2>

<p>Selecting specific values of a pandas DataFrame or Series to work on is an implicit step in almost any data operation you'll run, so one of the first things you need to learn in working with data in Python is how to go about selecting the data points relevant to you quickly and effectively.</p>

In [10]:
import pandas as pd
pd.set_option('display.max_rows', 5, 'display.max_columns', 10)

In [5]:
reviews = pd.read_csv("https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv", index_col=0)

# <h2 id="Native-accessors">Native accessors</h2>

<p>Native Python objects provide  good ways of indexing data. Pandas carries all of these over, which helps make it easy to start with.</p>

<p>Consider this DataFrame:</p>

In [11]:
reviews

        country                                        description   designation  points  price  ...        taster_name taster_twitter_handle                                              title         variety                  winery
0         Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco      87    NaN  ...      Kerin O’Keefe          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)     White Blend                 Nicosia
1      Portugal  This is ripe and fruity, a wine that is smooth...      Avidagos      87   15.0  ...         Roger Voss            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red     Quinta dos Avidagos
...         ...                                                ...           ...     ...    ...  ...                ...                   ...                                                ...             ...                     ...
65497        US  This wine wears its 15.8% alcohol better than ...      Block 24      90   31.0  ...                NaN                   NaN       Hendry 2004 Block 24 Primitivo (Napa Valley)       Primitivo                  Hendry
65498     Spain  A unique take on Manzanilla Sherry, which is o...    Manzanilla      90   10.0  ...  Michael Schachner           @wineschach  Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...          Sherry  Bodegas Dios Baco S.L.

[65499 rows x 13 columns]

<p>In Python, we can access the property of an object by accessing it as an attribute. A <code>book</code> object, for example, might have a <code>title</code> property, which we can access by calling <code>book.title</code>. Columns in a pandas DataFrame work in much the same way.</p>

<p>Hence to access the <code>country</code> property of <code>reviews</code> we can use:</p>

In [12]:
reviews.country

0           Italy
1        Portugal
           ...
65497          US
65498       Spain
Name: country, Length: 65499, dtype: object

<p>If we have a Python dictionary, we can access its values using the indexing (<code>[]</code>) operator. We can do the same with columns in a DataFrame:</p>

In [13]:
reviews['country']

0           Italy
1        Portugal
           ...
65497          US
65498       Spain
Name: country, Length: 65499, dtype: object

<p>These are the two ways of selecting a specific Series out of a DataFrame. Neither of them is more or less syntactically valid than the other, but the indexing operator <code>[]</code> does have the advantage that it can handle column names with reserved characters in them (e.g. if we had a <code>country providence</code> column, <code>reviews.country providence</code> wouldn't work).</p>

<p>Doesn't a pandas Series look kind of like a fancy dictionary? It pretty much is, so it's no surprise that, to drill down to a single specific value, we need only use the indexing operator <code>[]</code> once more:</p>

In [14]:
reviews['country'][0]

'Italy'

# <h2 id="Indexing-in-pandas">Indexing in pandas</h2>

<p>The indexing operator and attribute selection are nice because they work just like they do in the rest of the Python ecosystem. As a novice, this makes them easy to pick up and use. However, pandas has its own accessor operators, <code>loc</code> and <code>iloc</code>. For more advanced operations, these are the ones you're supposed to be using.</p>

## <h3 id="Index-based-selection">Index-based selection</h3>

<p>Pandas indexing works in one of two paradigms. The first is <strong>index-based selection</strong>: selecting data based on its numerical position in the data. <code>iloc</code> follows this paradigm.</p>

<p>To select the first row of data in a DataFrame, we may use the following:</p>

In [15]:
reviews.iloc[0]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

<p>Both <code>loc</code> and <code>iloc</code> are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.</p>

<p>This means that it's marginally easier to retrieve rows, and marginally harder to get retrieve columns. To get a column with <code>iloc</code>, we can do the following:</p>

In [16]:
reviews.iloc[:, 0]

0           Italy
1        Portugal
           ...
65497          US
65498       Spain
Name: country, Length: 65499, dtype: object

<p>On its own, the <code>:</code> operator, which also comes from native Python, means "everything". When combined with other selectors, however, it can be used to indicate a range of values. For example, to select the <code>country</code> column from just the first, second, and third row, we would do:</p>

In [17]:
reviews.iloc[:3, 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

<p>Or, to select just the second and third entries, we would do:</p>

In [18]:
reviews.iloc[1:3, 0]

1    Portugal
2          US
Name: country, dtype: object

<p>It's also possible to pass a list:</p>

In [19]:
reviews.iloc[[0, 1, 2], 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

<p>Finally, it's worth knowing that negative numbers can be used in selection. This will start counting forwards from the <em>end</em> of the values. So for example here are the last five elements of the dataset.</p>

In [20]:
reviews.iloc[-5:]

         country                                        description             designation  points  price  ...        taster_name taster_twitter_handle                                              title             variety                  winery
65494     France  Made from young vines from the Vaulorent porti...  Fourchaume Premier Cru      90   45.0  ...         Roger Voss            @vossroger  William Fèvre 2005 Fourchaume Premier Cru  (Ch...          Chardonnay           William Fèvre
65495  Australia  This is a big, fat, almost sweet-tasting Caber...                     NaN      90   22.0  ...     Joe Czerwinski                @JoeCz    Tapestry 2005 Cabernet Sauvignon (McLaren Vale)  Cabernet Sauvignon                Tapestry
65496         US  Much improved over the unripe 2005, Fritz's 20...                  Estate      90   20.0  ...                NaN                   NaN  Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...     Sauvignon Blanc                   Fritz
65497         US  This wine wears its 15.8% alcohol better than ...                Block 24      90   31.0  ...                NaN                   NaN       Hendry 2004 Block 24 Primitivo (Napa Valley)           Primitivo                  Hendry
65498      Spain  A unique take on Manzanilla Sherry, which is o...              Manzanilla      90   10.0  ...  Michael Schachner           @wineschach  Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...              Sherry  Bodegas Dios Baco S.L.

[5 rows x 13 columns]

## <h3 id="Label-based-selection">Label-based selection</h3>

<p>The second paradigm for attribute selection is the one followed by the <code>loc</code> operator: <strong>label-based selection</strong>. In this paradigm, it's the data index value, not its position, which matters.</p>

<p>For example, to get the first entry in <code>reviews</code>, we would now do the following:</p>

In [21]:
reviews.loc[0, 'country']

'Italy'

<p><code>iloc</code> is conceptually simpler than <code>loc</code> because it ignores the dataset's indices. When we use <code>iloc</code> we treat the dataset like a big matrix (a list of lists), one that we have to index into by position. <code>loc</code>, by contrast, uses the information in the indices to do its work. Since your dataset usually has meaningful indices, it's usually easier to do things using <code>loc</code> instead. For example, here's one operation that's much easier using <code>loc</code>:</p>

In [22]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

             taster_name taster_twitter_handle  points
0          Kerin O’Keefe          @kerinokeefe      87
1             Roger Voss            @vossroger      87
...                  ...                   ...     ...
65497                NaN                   NaN      90
65498  Michael Schachner           @wineschach      90

[65499 rows x 3 columns]

## <h3 id="Choosing-between-loc-and-iloc">Choosing between <code>loc</code> and <code>iloc</code></h3>

<p>When choosing or transitioning between <code>loc</code> and <code>iloc</code>, there is one "gotcha" worth keeping in mind, which is that the two methods use slightly different indexing schemes.</p>

<p><code>iloc</code> uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So <code>0:10</code> will select entries <code>0,...,9</code>. <code>loc</code>, meanwhile, indexes inclusively. So <code>0:10</code> will select entries <code>0,...,10</code>.</p>

<p>Why the change? Remember that loc can index any stdlib type: strings, for example. If we have a DataFrame with index values <code>Apples, ..., Potatoes, ...</code>, and we want to select "all the alphabetical fruit choices between Apples and Potatoes", then it's a lot more convenient to index <code>df.loc['Apples':'Potatoes']</code> than it is to index something like <code>df.loc['Apples', 'Potatoet']</code> (<code>t</code> coming after <code>s</code> in the alphabet).</p>
<p>This is particularly confusing when the DataFrame index is a simple numerical list, e.g. <code>0,...,1000</code>. In this case <code>df.iloc[0:1000]</code> will return 1000 entries, while <code>df.loc[0:1000]</code> return 1001 of them! To get 1000 elements using <code>loc</code>, you will need to go one lower and ask for <code>df.loc[0:999]</code>.</p>

<p>Otherwise, the semantics of using <code>loc</code> are the same as those for <code>iloc</code>.</p>

# <h2 id="Manipulating-the-index" tabindex="0">Manipulating the index</h2>

<p>Label-based selection derives its power from the labels in the index. Critically, the index we use is not immutable. We can manipulate the index in any way we see fit.</p>

<p>The <code>set_index()</code> method can be used to do the job. Here is what happens when we <code>set_index</code> to the <code>title</code> field:</p>

In [23]:
reviews.set_index("title")

                                                     country                                        description   designation  points  price  ... region_2        taster_name taster_twitter_handle         variety                  winery
title                                                                                                                                         ...
Nicosia 2013 Vulkà Bianco  (Etna)                      Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco      87    NaN  ...      NaN      Kerin O’Keefe          @kerinokeefe     White Blend                 Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro)       Portugal  This is ripe and fruity, a wine that is smooth...      Avidagos      87   15.0  ...      NaN         Roger Voss            @vossroger  Portuguese Red     Quinta dos Avidagos
...                                                      ...                                                ...           ...     ...    ...  ...      ...                ...                   ...             ...                     ...
Hendry 2004 Block 24 Primitivo (Napa Valley)              US  This wine wears its 15.8% alcohol better than ...      Block 24      90   31.0  ...     Napa                NaN                   NaN       Primitivo                  Hendry
Bodegas Dios Baco S.L. NV Manzanilla Sherry (Je...     Spain  A unique take on Manzanilla Sherry, which is o...    Manzanilla      90   10.0  ...      NaN  Michael Schachner           @wineschach          Sherry  Bodegas Dios Baco S.L.

[65499 rows x 12 columns]

<p>This is useful if you can come up with an index for the dataset which is better than the current one.</p>

# <h2 id="Conditional-selection">Conditional selection</h2>

<p>So far we've been indexing various strides of data, using structural properties of the DataFrame itself. To do <em>interesting</em> things with the data, however, we often need to ask questions based on conditions.</p>

<p>For example, suppose that we're interested specifically in better-than-average wines produced in Italy.</p>

<p>We can start by checking if each wine is Italian or not:</p>

In [24]:
reviews.country == 'Italy'

0         True
1        False
         ...
65497    False
65498    False
Name: country, Length: 65499, dtype: bool

<p>This operation produced a Series of <code>True</code>/<code>False</code> booleans based on the <code>country</code> of each record.  This result can then be used inside of <code>loc</code> to select the relevant data:</p>

In [25]:
reviews.loc[reviews.country == 'Italy']

      country                                        description   designation  points  price  ...    taster_name taster_twitter_handle                                             title      variety                winery
0       Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco      87    NaN  ...  Kerin O’Keefe          @kerinokeefe                 Nicosia 2013 Vulkà Bianco  (Etna)  White Blend               Nicosia
6       Italy  Here's a bright, informal red that opens with ...       Belsito      87   16.0  ...  Kerin O’Keefe          @kerinokeefe  Terre di Giurfo 2013 Belsito Frappato (Vittoria)     Frappato       Terre di Giurfo
...       ...                                                ...           ...     ...    ...  ...            ...                   ...                                               ...          ...                   ...
65477   Italy  Made of 65% Merlot, 25% Cabernet Sauvignon, 5%...     Ruit Hora      88   30.0  ...  Kerin O’Keefe          @kerinokeefe   Caccia al Piano 1868 2013 Ruit Hora  (Bolgheri)    Red Blend  Caccia al Piano 1868
65478   Italy  Aromas suggesting French oak, coconut and spic...           NaN      88   36.0  ...  Kerin O’Keefe          @kerinokeefe   Il Macchione 2012  Vino Nobile di Montepulciano   Sangiovese          Il Macchione

[10005 rows x 13 columns]

<p>This DataFrame has ~20,000 rows. The original had ~130,000. That means that around 15% of wines originate from Italy.</p>

<p>We also wanted to know which ones are better than average. Wines are reviewed on a 80-to-100 point scale, so this could mean wines that accrued at least 90 points.</p>

<p>We can use the ampersand (<code>&amp;</code>) to bring the two questions together:</p>

In [26]:
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]

      country                                        description            designation  points  price  ...    taster_name taster_twitter_handle                                              title    variety                                  winery
120     Italy  Slightly backward, particularly given the vint...    Bricco Rocche Prapó      92   70.0  ...            NaN                   NaN         Ceretto 2003 Bricco Rocche Prapó  (Barolo)   Nebbiolo                                 Ceretto
130     Italy  At the first it was quite muted and subdued, b...  Bricco Rocche Brunate      91   70.0  ...            NaN                   NaN       Ceretto 2003 Bricco Rocche Brunate  (Barolo)   Nebbiolo                                 Ceretto
...       ...                                                ...                    ...     ...    ...  ...            ...                   ...                                                ...        ...                                     ...
65365   Italy  Stunning and sophisticated, it leads with inte...         Sanct Valentin      94   40.0  ...  Kerin O’Keefe          @kerinokeefe  Cantina Produttori San Michele Appiano 2012 Sa...  Sauvignon  Cantina Produttori San Michele Appiano
65399   Italy  Aesthetics and elegance are important values t...             Nectar Dei      91   65.0  ...            NaN                   NaN       Fattoria Nittardi 2006 Nectar Dei  (Maremma)  Red Blend                       Fattoria Nittardi

[3479 rows x 13 columns]

<p>Suppose we'll buy any wine that's made in Italy <em>or</em> which is rated above average. For this we use a pipe (<code>|</code>):</p>

In [27]:
reviews.loc[(reviews.country == 'Italy') | (reviews.points >= 90)]

      country                                        description   designation  points  price  ...        taster_name taster_twitter_handle                                              title      variety                  winery
0       Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco      87    NaN  ...      Kerin O’Keefe          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)  White Blend                 Nicosia
6       Italy  Here's a bright, informal red that opens with ...       Belsito      87   16.0  ...      Kerin O’Keefe          @kerinokeefe   Terre di Giurfo 2013 Belsito Frappato (Vittoria)     Frappato         Terre di Giurfo
...       ...                                                ...           ...     ...    ...  ...                ...                   ...                                                ...          ...                     ...
65497      US  This wine wears its 15.8% alcohol better than ...      Block 24      90   31.0  ...                NaN                   NaN       Hendry 2004 Block 24 Primitivo (Napa Valley)    Primitivo                  Hendry
65498   Spain  A unique take on Manzanilla Sherry, which is o...    Manzanilla      90   10.0  ...  Michael Schachner           @wineschach  Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...       Sherry  Bodegas Dios Baco S.L.

[31430 rows x 13 columns]

<p>Pandas comes with a few built-in conditional selectors, two of which we will highlight here.</p>

<p>The first is <code>isin</code>. <code>isin</code> is lets you select data whose value "is in" a list of values. For example, here's how we can use it to select wines only from Italy or France:</p>

In [28]:
reviews.loc[reviews.country.isin(['Italy', 'France'])]

      country                                        description                 designation  points  price  ...    taster_name taster_twitter_handle                                              title      variety           winery
0       Italy  Aromas include tropical fruit, broom, brimston...                Vulkà Bianco      87    NaN  ...  Kerin O’Keefe          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)  White Blend          Nicosia
6       Italy  Here's a bright, informal red that opens with ...                     Belsito      87   16.0  ...  Kerin O’Keefe          @kerinokeefe   Terre di Giurfo 2013 Belsito Frappato (Vittoria)     Frappato  Terre di Giurfo
...       ...                                                ...                         ...     ...    ...  ...            ...                   ...                                                ...          ...              ...
65492  France  A rounded, fruity wine, packed with yellow pea...  Mont-de-Milieu Premier Cru      90   30.0  ...     Roger Voss            @vossroger  Simonnet-Febvre 2005 Mont-de-Milieu Premier Cr...   Chardonnay  Simonnet-Febvre
65494  France  Made from young vines from the Vaulorent porti...      Fourchaume Premier Cru      90   45.0  ...     Roger Voss            @vossroger  William Fèvre 2005 Fourchaume Premier Cru  (Ch...   Chardonnay    William Fèvre

[21179 rows x 13 columns]

<p>The second is <code>isnull</code> (and its companion <code>notnull</code>). These methods let you highlight values which are (or are not) empty (<code>NaN</code>). For example, to filter out wines lacking a price tag in the dataset, here's what we would do:</p>

In [29]:
reviews.loc[reviews.price.notnull()]

        country                                        description designation  points  price  ...        taster_name taster_twitter_handle                                              title         variety                  winery
1      Portugal  This is ripe and fruity, a wine that is smooth...    Avidagos      87   15.0  ...         Roger Voss            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red     Quinta dos Avidagos
2            US  Tart and snappy, the flavors of lime flesh and...         NaN      87   14.0  ...       Paul Gregutt           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris               Rainstorm
...         ...                                                ...         ...     ...    ...  ...                ...                   ...                                                ...             ...                     ...
65497        US  This wine wears its 15.8% alcohol better than ...    Block 24      90   31.0  ...                NaN                   NaN       Hendry 2004 Block 24 Primitivo (Napa Valley)       Primitivo                  Hendry
65498     Spain  A unique take on Manzanilla Sherry, which is o...  Manzanilla      90   10.0  ...  Michael Schachner           @wineschach  Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...          Sherry  Bodegas Dios Baco S.L.

[60829 rows x 13 columns]

# <h2 id="Assigning-data">Assigning data</h2>

<p>Going the other way, assigning data to a DataFrame is easy. You can assign either a constant value:</p>

In [30]:
reviews['critic'] = 'everyone'
reviews['critic']

0        everyone
1        everyone
           ...
65497    everyone
65498    everyone
Name: critic, Length: 65499, dtype: object

<p>Or with an iterable of values:</p>

In [31]:
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

0        65499
1        65498
         ...
65497        2
65498        1
Name: index_backwards, Length: 65499, dtype: int64