<h1><b>Summary Functions and Maps</b></h1>
<span>Extract insights from your data.</span>

# <h2 id="Introduction">Introduction</h2>

<p>In the last tutorial, we learned how to select relevant data out of a DataFrame or Series. Plucking the right data out of our data representation is critical to getting work done, as we demonstrated in the exercises.</p>

<p>However, the data does not always come out of memory in the format we want it in right out of the bat. Sometimes we have to do some more work ourselves to reformat it for the task at hand.  This tutorial will cover different operations we can apply to our data to get the input "just right".</p>

<p>We'll use the Wine Magazine data for demonstration.</p>

In [3]:
import pandas as pd
pd.set_option('display.max_rows', 5)
import numpy as np

In [2]:
reviews = pd.read_csv("https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv", index_col=0)

In [4]:
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,90,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,90,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

# <h2 id="Summary-functions" tabindex="0">Summary functions</h2>

<p>Pandas provides many simple "summary functions" (not an official name) which restructure the data in some useful way. For example, consider the <code>describe()</code> method:</p>

In [5]:
reviews.points.describe()

count    65499.000000
mean        88.434037
             ...
75%         91.000000
max        100.000000
Name: points, Length: 8, dtype: float64

<p>This method generates a high-level summary of the attributes of the given column. It is type-aware, meaning that its output changes based on the data type of the input. The output above only makes sense for numerical data; for string data here's what we get:</p>

In [7]:
reviews.taster_name.describe()

count          51856
unique            19
top       Roger Voss
freq           13045
Name: taster_name, dtype: object

<p>If you want to get some particular simple summary statistic about a column in a DataFrame or a Series, there is usually a helpful pandas function that makes it happen.</p>

<p>For example, to see the mean of the points allotted (e.g. how well an averagely rated wine does), we can use the <code>mean()</code> function:</p>

In [8]:
reviews.points.mean()

np.float64(88.43403716087269)

<p>To see a list of unique values we can use the <code>unique()</code> function:</p>

In [9]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

<p>To see a list of unique values <em>and</em> how often they occur in the dataset, we can use the <code>value_counts()</code> method:</p>

In [10]:
reviews.taster_name.value_counts()

taster_name
Roger Voss           13045
Michael Schachner     7752
                     ...
Fiona Adams             11
Christina Pickard        4
Name: count, Length: 19, dtype: int64

# <h2 id="Maps">Maps</h2>

<p>A <strong>map</strong> is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values. In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done!</p>

<p>There are two mapping methods that you will use often.</p>

<p><a href="https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.map.html" rel=" noreferrer nofollow"><code>map()</code></a> is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores the wines received to 0. We can do this as follows:</p>

In [13]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_mean)

0       -1.434037
1       -1.434037
           ...
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

<p>The function you pass to <code>map()</code> should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. <code>map()</code> returns a new Series where all the values have been transformed by your function.</p>

<p><a href="https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html" rel=" noreferrer nofollow"><code>apply()</code></a> is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.</p>

In [15]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row

In [16]:
reviews.apply(remean_points, axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.434037,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.434037,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,1.565963,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,1.565963,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

<p>If we had called <code>reviews.apply()</code> with <code>axis='index'</code>, then instead of passing a function to transform each row, we would need to give a function to transform each <em>column</em>.</p>

<p>Note that <code>map()</code> and <code>apply()</code> return new, transformed Series and DataFrames, respectively. They don't modify the original data they're called on. If we look at the first row of <code>reviews</code>, we can see that it still has its original <code>points</code> value.</p>

In [17]:
reviews.head(1)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

<p>Pandas provides many common mapping operations as built-ins. For example, here's a faster way of remeaning our points column:</p>

In [18]:
review_points_mean = reviews.points.mean()
reviews.points - review_points_mean

0       -1.434037
1       -1.434037
           ...
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

<p>In this code we are performing an operation between a lot of values on the left-hand side (everything in the Series) and a single value on the right-hand side (the mean value). Pandas looks at this expression and figures out that we must mean to subtract that mean value from every value in the dataset.</p>

<p>Pandas will also understand what to do if we perform these operations between Series of equal length. For example, an easy way of combining country and region information in the dataset would be to do the following:</p>

In [19]:
reviews.country + " - " + reviews.region_1

0            Italy - Etna
1                     NaN
               ...
65497    US - Napa Valley
65498       Spain - Jerez
Length: 65499, dtype: object

<p>These operators are faster than <code>map()</code> or <code>apply()</code> because they use speed ups built into pandas. All of the standard Python operators (<code>&gt;</code>, <code>&lt;</code>, <code>==</code>, and so on) work in this manner.</p>

<p>However, they are not as flexible as <code>map()</code> or <code>apply()</code>, which can do more advanced things, like applying conditional logic, which cannot be done with addition and subtraction alone.</p>