<h1>Create, modify, and delete columns</h1>

<small>Source: <a href="https://github.com/tidyverse/dplyr/blob/pkgdown-v1.1.4/R/mutate.R"><code>R/mutate.R</code></a></small>
<div><code>mutate.Rd</code></div>

<p><code>mutate()</code> creates new columns that are functions of existing variables. It can also modify (if the name is the same as an existing column) and delete columns (by setting their value to <code>NULL</code>).</p>

# <h2 id="ref-usage">Usage</h2>

<pre><code>mutate(.data, ...)

# S3 method for class 'data.frame'
mutate(
  .data,
  ...,
  .by = NULL,
  .keep = <a href="https://rdrr.io/r/base/c.html">c</a>("all", "used", "unused", "none"),
  .before = NULL,
  .after = NULL
)</code></pre>

# <h2 id="arguments">Arguments</h2>

<dl><dt id="arg--data">.data</dt>
<dd>
<p>A data frame, data frame extension (e.g. a tibble), or a
lazy data frame (e.g. from dbplyr or dtplyr). See <em>Methods</em>, below, for more details.</p>
</dd>

<dt id="arg--">...</dt>
<dd>
<p>&lt;<code><a href="https://rlang.r-lib.org/reference/args_data_masking.html">data-masking</a></code>&gt; Name-value pairs.
The name gives the name of the column in the output.</p>
<p>The value can be:</p><ul><li><p>A vector of length 1, which will be recycled to the correct length.</p></li>
<li><p>A vector the same length as the current group (or the whole data frame if ungrouped).</p></li>
<li><p><code>NULL</code>, to remove the column.</p></li>
<li><p>A data frame or tibble, to create multiple columns in the output.</p></li>
</ul>
</dd>

<dt id="arg--by">.by</dt>
<dd>
<p>&lt;<code><a href="https://dplyr.tidyverse.org/reference/dplyr_tidy_select.html">tidy-select</a></code>&gt; Optionally, a selection of columns to group by for just this operation, functioning as an alternative to <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code>. For details and examples, see <a href="https://dplyr.tidyverse.org/reference/dplyr_by.html">?dplyr_by</a>.</p>
</dd>

<dt id="arg--keep">.keep</dt>
<dd>
<p>Control which columns from <code>.data</code> are retained in the output. Grouping columns and columns created by <code>...</code> are always kept.</p>
<ul>
<li><p><code>"all"</code> retains all columns from <code>.data</code>. This is the default.</p></li>
<li><p><code>"used"</code> retains only the columns used in <code>...</code> to create new columns. This is useful for checking your work, as it displays inputs and outputs side-by-side.</p></li>
<li><p><code>"unused"</code> retains only the columns <em>not</em> used in <code>...</code> to create new columns. This is useful if you generate new columns, but no longer need the columns used to generate them.</p></li>
<li><p><code>"none"</code> doesn't retain any extra columns from <code>.data</code>. Only the grouping variables and columns created by <code>...</code> are kept.</p></li>
</ul>
</dd>

<dt id="arg--before-after">.before, .after</dt>
<dd>
<p>&lt;<code><a href="https://dplyr.tidyverse.org/reference/dplyr_tidy_select.html">tidy-select</a></code>&gt; Optionally, control where new columns should appear (the default is to add to the right hand side). See <code><a href="https://dplyr.tidyverse.org/reference/relocate.html">relocate()</a></code> for more details.</p>
</dd>
</dl>

# <h2 id="value">Value</h2>

<p>An object of the same type as <code>.data</code>. The output has the following properties:</p>

<ul>
<li><p>Columns from <code>.data</code> will be preserved according to the <code>.keep</code> argument.</p></li>
<li><p>Existing columns that are modified by <code>...</code> will always be returned in their original location.</p></li>
<li><p>New columns created through <code>...</code> will be placed according to the <code>.before</code> and <code>.after</code> arguments.</p></li>
<li><p>The number of rows is not affected.</p></li>
<li><p>Columns given the value <code>NULL</code> will be removed.</p></li>
<li><p>Groups will be recomputed if a grouping variable is mutated.</p></li>
<li><p>Data frame attributes are preserved.</p></li>
</ul>

# <h2 id="useful-mutate-functions">Useful mutate functions</h2>

<ul>
<li><p><code><a href="https://rdrr.io/r/base/Arithmetic.html">+</a></code>, <code><a href="https://rdrr.io/r/base/Arithmetic.html">-</a></code>, <code><a href="https://rdrr.io/r/base/Log.html">log()</a></code>, etc., for their usual mathematical meanings</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/lead-lag.html">lead()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/lead-lag.html">lag()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/row_number.html">dense_rank()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/row_number.html">min_rank()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/percent_rank.html">percent_rank()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/row_number.html">row_number()</a></code>,
<code><a href="https://dplyr.tidyverse.org/reference/percent_rank.html">cume_dist()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/ntile.html">ntile()</a></code></p></li>
<li><p><code><a href="https://rdrr.io/r/base/cumsum.html">cumsum()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/cumall.html">cummean()</a></code>, <code><a href="https://rdrr.io/r/base/cumsum.html">cummin()</a></code>, <code><a href="https://rdrr.io/r/base/cumsum.html">cummax()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/cumall.html">cumany()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/cumall.html">cumall()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/na_if.html">na_if()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/coalesce.html">coalesce()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/recode.html">recode()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code></p></li>
</ul>

# <h2 id="grouped-tibbles">Grouped tibbles</h2>

<p>Because mutating expressions are computed within groups, they may
yield different results on grouped tibbles. This will be the case as soon as an aggregating, lagging, or ranking function is involved. Compare this ungrouped mutate:</p>

<pre><code>starwars %&gt;%
  select(name, mass, species) %&gt;%
  mutate(mass_norm = mass / mean(mass, na.rm = TRUE))</code></pre><p></p>

<p>With the grouped equivalent:</p>

<pre><code>starwars %&gt;%
  select(name, mass, species) %&gt;%
  group_by(species) %&gt;%
  mutate(mass_norm = mass / mean(mass, na.rm = TRUE))</code></pre><p></p>

<p>The former normalises <code>mass</code> by the global average whereas the latter normalises by the averages within species levels.</p>

# <h2 id="methods">Methods</h2>

<p>This function is a <strong>generic</strong>, which means that packages can provide implementations (methods) for other classes.
See the documentation of individual methods for extra arguments and differences in behaviour.</p>

<p>Methods available in currently loaded packages:
dbplyr (<code><a href="https://dbplyr.tidyverse.org/reference/mutate.tbl_lazy.html">tbl_lazy</a></code>), dplyr (<code>data.frame</code>)
.</p>

# <h2 id="see-also">See also</h2>

<div class="dont-index"><p>Other single table verbs:
<code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/reframe.html">reframe</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/select.html">select</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a>()</code></p></div>

# <h2 id="ref-examples">Examples</h2>

In [2]:
library(dplyr)

# Newly created variables are available immediately
starwars |>
  select(name, mass) |>
  mutate(
    mass2 = mass * 2,
    mass2_squared = mass2 * mass2
  )

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

   name                  mass   mass2  mass2_squared
1  Luke Skywalker          77.0  154.0   23716.00
2  C-3PO                   75.0  150.0   22500.00
3  R2-D2                   32.0   64.0    4096.00
4  Darth Vader            136.0  272.0   73984.00
5  Leia Organa             49.0   98.0    9604.00
6  Owen Lars              120.0  240.0   57600.00
7  Beru Whitesun Lars      75.0  150.0   22500.00
8  R5-D4                   32.0   64.0    4096.00
9  Biggs Darklighter       84.0  168.0   28224.00
10 Obi-Wan Kenobi          77.0  154.0   23716.00
11 Anakin Skywalker        84.0  168.0   28224.00
12 Wilhuff Tarkin            NA     NA         NA
13 Chewbacca              112.0  224.0   50176.00
14 Han Solo                80.0  160.0   25600.00
15 Greedo                  74.0  148.0   21904.00
16 Jabba Desilijic Tiure 1358.0 2716.0 7376656.00
17 Wedge Antilles          77.0  154.0   23716.00
18 Jek Tono Porkins       110.0  220.0   48400.00
19 Yoda                    17.0   34.0    1156.00
20 Palpatine               75.0  150.0   22500.00
21 Boba Fett               78.2  156.4   24460.96
22 IG-88                  140.0  280.0   78400.00
23 Bossk                  113.0  226.0   51076.00
24 Lando Calrissian        79.0  158.0   24964.00
25 Lobot                   79.0  158.0   24964.00
26 Ackbar                  83.0  166.0   27556.00
27 Mon Mothma                NA     NA         NA
28 Arvel Crynyd              NA     NA         NA
29 Wicket Systri Warrick   20.0   40.0    1600.00
30 Nien Nunb               68.0  136.0   18496.00
⋮  ⋮                     ⋮      ⋮      ⋮
58 Mas Amedda               NA     NA         NA
59 Gregar Typho           85.0  170.0   28900.00
60 Cordé                    NA     NA         NA
61 Cliegg Lars              NA     NA         NA
62 Poggle the Lesser      80.0  160.0   25600.00
63 Luminara Unduli        56.2  112.4   12633.76
64 Barriss Offee          50.0  100.0   10000.00
65 Dormé                    NA     NA         NA
66 Dooku                  80.0  160.0   25600.00
67 Bail Prestor Organa      NA     NA         NA
68 Jango Fett             79.0  158.0   24964.00
69 Zam Wesell             55.0  110.0   12100.00
70 Dexter Jettster       102.0  204.0   41616.00
71 Lama Su                88.0  176.0   30976.00
72 Taun We                  NA     NA         NA
73 Jocasta Nu               NA     NA         NA
74 R4-P17                   NA     NA         NA
75 Wat Tambor             48.0   96.0    9216.00
76 San Hill                 NA     NA         NA
77 Shaak Ti               57.0  114.0   12996.00
78 Grievous              159.0  318.0  101124.00
79 Tarfful               136.0  272.0   73984.00
80 Raymus Antilles        79.0  158.0   24964.00
81 Sly Moore              48.0   96.0    9216.00
82 Tion Medon             80.0  160.0   25600.00
83 Finn                     NA     NA         NA
84 Rey                      NA     NA         NA
85 Poe Dameron              NA     NA         NA
86 BB8                      NA     NA         NA
87 Captain Phasma           NA     NA         NA

In [3]:
# As well as adding new variables, you can use mutate() to
# remove variables and modify existing variables.
starwars |>
  select(name, height, mass, homeworld) |>
  mutate(
    mass = NULL,
    height = height * 0.0328084 # convert to feet
  )

   name                  height   homeworld
1  Luke Skywalker        5.643045 Tatooine
2  C-3PO                 5.479003 Tatooine
3  R2-D2                 3.149606 Naboo
4  Darth Vader           6.627297 Tatooine
5  Leia Organa           4.921260 Alderaan
6  Owen Lars             5.839895 Tatooine
7  Beru Whitesun Lars    5.413386 Tatooine
8  R5-D4                 3.182415 Tatooine
9  Biggs Darklighter     6.003937 Tatooine
10 Obi-Wan Kenobi        5.971129 Stewjon
11 Anakin Skywalker      6.167979 Tatooine
12 Wilhuff Tarkin        5.905512 Eriadu
13 Chewbacca             7.480315 Kashyyyk
14 Han Solo              5.905512 Corellia
15 Greedo                5.675853 Rodia
16 Jabba Desilijic Tiure 5.741470 Nal Hutta
17 Wedge Antilles        5.577428 Corellia
18 Jek Tono Porkins      5.905512 Bestine IV
19 Yoda                  2.165354 NA
20 Palpatine             5.577428 Naboo
21 Boba Fett             6.003937 Kamino
22 IG-88                 6.561680 NA
23 Bossk                 6.233596 Trandosha
24 Lando Calrissian      5.807087 Socorro
25 Lobot                 5.741470 Bespin
26 Ackbar                5.905512 Mon Cala
27 Mon Mothma            4.921260 Chandrila
28 Arvel Crynyd                NA NA
29 Wicket Systri Warrick 2.887139 Endor
30 Nien Nunb             5.249344 Sullust
⋮  ⋮                     ⋮        ⋮
58 Mas Amedda            6.430446 Champala
59 Gregar Typho          6.069554 Naboo
60 Cordé                 5.150919 Naboo
61 Cliegg Lars           6.003937 Tatooine
62 Poggle the Lesser     6.003937 Geonosis
63 Luminara Unduli       5.577428 Mirial
64 Barriss Offee         5.446194 Mirial
65 Dormé                 5.413386 Naboo
66 Dooku                 6.332021 Serenno
67 Bail Prestor Organa   6.266404 Alderaan
68 Jango Fett            6.003937 Concord Dawn
69 Zam Wesell            5.511811 Zolan
70 Dexter Jettster       6.496063 Ojom
71 Lama Su               7.513124 Kamino
72 Taun We               6.988189 Kamino
73 Jocasta Nu            5.479003 Coruscant
74 R4-P17                3.149606 NA
75 Wat Tambor            6.332021 Skako
76 San Hill              6.266404 Muunilinst
77 Shaak Ti              5.839895 Shili
78 Grievous              7.086614 Kalee
79 Tarfful               7.677166 Kashyyyk
80 Raymus Antilles       6.167979 Alderaan
81 Sly Moore             5.839895 Umbara
82 Tion Medon            6.758530 Utapau
83 Finn                        NA NA
84 Rey                         NA NA
85 Poe Dameron                 NA NA
86 BB8                         NA NA
87 Captain Phasma              NA NA

In [4]:
# Use across() with mutate() to apply a transformation
# to multiple columns in a tibble.
starwars |>
  select(name, homeworld, species) |>
  mutate(across(!name, as.factor))

   name                  homeworld    species
1  Luke Skywalker        Tatooine     Human
2  C-3PO                 Tatooine     Droid
3  R2-D2                 Naboo        Droid
4  Darth Vader           Tatooine     Human
5  Leia Organa           Alderaan     Human
6  Owen Lars             Tatooine     Human
7  Beru Whitesun Lars    Tatooine     Human
8  R5-D4                 Tatooine     Droid
9  Biggs Darklighter     Tatooine     Human
10 Obi-Wan Kenobi        Stewjon      Human
11 Anakin Skywalker      Tatooine     Human
12 Wilhuff Tarkin        Eriadu       Human
13 Chewbacca             Kashyyyk     Wookiee
14 Han Solo              Corellia     Human
15 Greedo                Rodia        Rodian
16 Jabba Desilijic Tiure Nal Hutta    Hutt
17 Wedge Antilles        Corellia     Human
18 Jek Tono Porkins      Bestine IV   NA
19 Yoda                  NA           Yoda's species
20 Palpatine             Naboo        Human
21 Boba Fett             Kamino       Human
22 IG-88                 NA           Droid
23 Bossk                 Trandosha    Trandoshan
24 Lando Calrissian      Socorro      Human
25 Lobot                 Bespin       Human
26 Ackbar                Mon Cala     Mon Calamari
27 Mon Mothma            Chandrila    Human
28 Arvel Crynyd          NA           Human
29 Wicket Systri Warrick Endor        Ewok
30 Nien Nunb             Sullust      Sullustan
⋮  ⋮                     ⋮            ⋮
58 Mas Amedda            Champala     Chagrian
59 Gregar Typho          Naboo        NA
60 Cordé                 Naboo        NA
61 Cliegg Lars           Tatooine     Human
62 Poggle the Lesser     Geonosis     Geonosian
63 Luminara Unduli       Mirial       Mirialan
64 Barriss Offee         Mirial       Mirialan
65 Dormé                 Naboo        Human
66 Dooku                 Serenno      Human
67 Bail Prestor Organa   Alderaan     Human
68 Jango Fett            Concord Dawn Human
69 Zam Wesell            Zolan        Clawdite
70 Dexter Jettster       Ojom         Besalisk
71 Lama Su               Kamino       Kaminoan
72 Taun We               Kamino       Kaminoan
73 Jocasta Nu            Coruscant    Human
74 R4-P17                NA           Droid
75 Wat Tambor            Skako        Skakoan
76 San Hill              Muunilinst   Muun
77 Shaak Ti              Shili        Togruta
78 Grievous              Kalee        Kaleesh
79 Tarfful               Kashyyyk     Wookiee
80 Raymus Antilles       Alderaan     Human
81 Sly Moore             Umbara       NA
82 Tion Medon            Utapau       Pau'an
83 Finn                  NA           Human
84 Rey                   NA           Human
85 Poe Dameron           NA           Human
86 BB8                   NA           Droid
87 Captain Phasma        NA           Human

In [5]:
# Window functions are useful for grouped mutates:
starwars |>
  select(name, mass, homeworld) |>
  group_by(homeworld) |>
  mutate(rank = min_rank(desc(mass)))

   name                  mass   homeworld    rank
1  Luke Skywalker          77.0 Tatooine      5
2  C-3PO                   75.0 Tatooine      6
3  R2-D2                   32.0 Naboo         6
4  Darth Vader            136.0 Tatooine      1
5  Leia Organa             49.0 Alderaan      2
6  Owen Lars              120.0 Tatooine      2
7  Beru Whitesun Lars      75.0 Tatooine      6
8  R5-D4                   32.0 Tatooine      8
9  Biggs Darklighter       84.0 Tatooine      3
10 Obi-Wan Kenobi          77.0 Stewjon       1
11 Anakin Skywalker        84.0 Tatooine      3
12 Wilhuff Tarkin            NA Eriadu       NA
13 Chewbacca              112.0 Kashyyyk      2
14 Han Solo                80.0 Corellia      1
15 Greedo                  74.0 Rodia         1
16 Jabba Desilijic Tiure 1358.0 Nal Hutta     1
17 Wedge Antilles          77.0 Corellia      2
18 Jek Tono Porkins       110.0 Bestine IV    1
19 Yoda                    17.0 NA            3
20 Palpatine               75.0 Naboo         3
21 Boba Fett               78.2 Kamino        2
22 IG-88                  140.0 NA            1
23 Bossk                  113.0 Trandosha     1
24 Lando Calrissian        79.0 Socorro       1
25 Lobot                   79.0 Bespin        1
26 Ackbar                  83.0 Mon Cala      1
27 Mon Mothma                NA Chandrila    NA
28 Arvel Crynyd              NA NA           NA
29 Wicket Systri Warrick   20.0 Endor         1
30 Nien Nunb               68.0 Sullust       1
⋮  ⋮                     ⋮      ⋮            ⋮
58 Mas Amedda               NA  Champala     NA
59 Gregar Typho           85.0  Naboo         1
60 Cordé                    NA  Naboo        NA
61 Cliegg Lars              NA  Tatooine     NA
62 Poggle the Lesser      80.0  Geonosis      1
63 Luminara Unduli        56.2  Mirial        1
64 Barriss Offee          50.0  Mirial        2
65 Dormé                    NA  Naboo        NA
66 Dooku                  80.0  Serenno       1
67 Bail Prestor Organa      NA  Alderaan     NA
68 Jango Fett             79.0  Concord Dawn  1
69 Zam Wesell             55.0  Zolan         1
70 Dexter Jettster       102.0  Ojom          1
71 Lama Su                88.0  Kamino        1
72 Taun We                  NA  Kamino       NA
73 Jocasta Nu               NA  Coruscant    NA
74 R4-P17                   NA  NA           NA
75 Wat Tambor             48.0  Skako         1
76 San Hill                 NA  Muunilinst   NA
77 Shaak Ti               57.0  Shili         1
78 Grievous              159.0  Kalee         1
79 Tarfful               136.0  Kashyyyk      1
80 Raymus Antilles        79.0  Alderaan      1
81 Sly Moore              48.0  Umbara        1
82 Tion Medon             80.0  Utapau        1
83 Finn                     NA  NA           NA
84 Rey                      NA  NA           NA
85 Poe Dameron              NA  NA           NA
86 BB8                      NA  NA           NA
87 Captain Phasma           NA  NA           NA

In [6]:
# By default, new columns are placed on the far right.
df <- tibble(x = 1, y = 2)
df |> mutate(z = x + y)

  x y z
1 1 2 3

In [7]:
df |> mutate(z = x + y, .before = 1)

  z x y
1 3 1 2

In [8]:
df |> mutate(z = x + y, .after = x)

  x z y
1 1 3 2

In [9]:
# By default, mutate() keeps all columns from the input data.
df <- tibble(x = 1, y = 2, a = "a", b = "b")
df |> mutate(z = x + y, .keep = "all") # the default

  x y a b z
1 1 2 a b 3

In [10]:
df |> mutate(z = x + y, .keep = "used")

  x y z
1 1 2 3

In [11]:
df |> mutate(z = x + y, .keep = "unused")

  a b z
1 a b 3

In [12]:
df |> mutate(z = x + y, .keep = "none")

  z
1 3

In [13]:
# Grouping ----------------------------------------
# The mutate operation may yield different results on grouped
# tibbles because the expressions are computed within groups.
# The following normalises `mass` by the global average:
starwars |>
  select(name, mass, species) |>
  mutate(mass_norm = mass / mean(mass, na.rm = TRUE))

   name                  mass   species        mass_norm
1  Luke Skywalker          77.0 Human           0.7912704
2  C-3PO                   75.0 Droid           0.7707179
3  R2-D2                   32.0 Droid           0.3288397
4  Darth Vader            136.0 Human           1.3975685
5  Leia Organa             49.0 Human           0.5035357
6  Owen Lars              120.0 Human           1.2331487
7  Beru Whitesun Lars      75.0 Human           0.7707179
8  R5-D4                   32.0 Droid           0.3288397
9  Biggs Darklighter       84.0 Human           0.8632041
10 Obi-Wan Kenobi          77.0 Human           0.7912704
11 Anakin Skywalker        84.0 Human           0.8632041
12 Wilhuff Tarkin            NA Human                  NA
13 Chewbacca              112.0 Wookiee         1.1509388
14 Han Solo                80.0 Human           0.8220991
15 Greedo                  74.0 Rodian          0.7604417
16 Jabba Desilijic Tiure 1358.0 Hutt           13.9551329
17 Wedge Antilles          77.0 Human           0.7912704
18 Jek Tono Porkins       110.0 NA              1.1303863
19 Yoda                    17.0 Yoda's species  0.1746961
20 Palpatine               75.0 Human           0.7707179
21 Boba Fett               78.2 Human           0.8036019
22 IG-88                  140.0 Droid           1.4386735
23 Bossk                  113.0 Trandoshan      1.1612150
24 Lando Calrissian        79.0 Human           0.8118229
25 Lobot                   79.0 Human           0.8118229
26 Ackbar                  83.0 Mon Calamari    0.8529279
27 Mon Mothma                NA Human                  NA
28 Arvel Crynyd              NA Human                  NA
29 Wicket Systri Warrick   20.0 Ewok            0.2055248
30 Nien Nunb               68.0 Sullustan       0.6987843
⋮  ⋮                     ⋮      ⋮              ⋮
58 Mas Amedda               NA  Chagrian              NA
59 Gregar Typho           85.0  NA             0.8734803
60 Cordé                    NA  NA                    NA
61 Cliegg Lars              NA  Human                 NA
62 Poggle the Lesser      80.0  Geonosian      0.8220991
63 Luminara Unduli        56.2  Mirialan       0.5775246
64 Barriss Offee          50.0  Mirialan       0.5138120
65 Dormé                    NA  Human                 NA
66 Dooku                  80.0  Human          0.8220991
67 Bail Prestor Organa      NA  Human                 NA
68 Jango Fett             79.0  Human          0.8118229
69 Zam Wesell             55.0  Clawdite       0.5651932
70 Dexter Jettster       102.0  Besalisk       1.0481764
71 Lama Su                88.0  Kaminoan       0.9043091
72 Taun We                  NA  Kaminoan              NA
73 Jocasta Nu               NA  Human                 NA
74 R4-P17                   NA  Droid                 NA
75 Wat Tambor             48.0  Skakoan        0.4932595
76 San Hill                 NA  Muun                  NA
77 Shaak Ti               57.0  Togruta        0.5857456
78 Grievous              159.0  Kaleesh        1.6339220
79 Tarfful               136.0  Wookiee        1.3975685
80 Raymus Antilles        79.0  Human          0.8118229
81 Sly Moore              48.0  NA             0.4932595
82 Tion Medon             80.0  Pau'an         0.8220991
83 Finn                     NA  Human                 NA
84 Rey                      NA  Human                 NA
85 Poe Dameron              NA  Human                 NA
86 BB8                      NA  Droid                 NA
87 Captain Phasma           NA  Human                 NA

In [14]:
# Whereas this normalises `mass` by the averages within species
# levels:
starwars |>
  select(name, mass, species) |>
  group_by(species) |>
  mutate(mass_norm = mass / mean(mass, na.rm = TRUE))

   name                  mass   species        mass_norm
1  Luke Skywalker          77.0 Human          0.9469930
2  C-3PO                   75.0 Droid          1.0752688
3  R2-D2                   32.0 Droid          0.4587814
4  Darth Vader            136.0 Human          1.6726110
5  Leia Organa             49.0 Human          0.6026319
6  Owen Lars              120.0 Human          1.4758332
7  Beru Whitesun Lars      75.0 Human          0.9223958
8  R5-D4                   32.0 Droid          0.4587814
9  Biggs Darklighter       84.0 Human          1.0330833
10 Obi-Wan Kenobi          77.0 Human          0.9469930
11 Anakin Skywalker        84.0 Human          1.0330833
12 Wilhuff Tarkin            NA Human                 NA
13 Chewbacca              112.0 Wookiee        0.9032258
14 Han Solo                80.0 Human          0.9838888
15 Greedo                  74.0 Rodian         1.0000000
16 Jabba Desilijic Tiure 1358.0 Hutt           1.0000000
17 Wedge Antilles          77.0 Human          0.9469930
18 Jek Tono Porkins       110.0 NA             1.3580247
19 Yoda                    17.0 Yoda's species 1.0000000
20 Palpatine               75.0 Human          0.9223958
21 Boba Fett               78.2 Human          0.9617513
22 IG-88                  140.0 Droid          2.0071685
23 Bossk                  113.0 Trandoshan     1.0000000
24 Lando Calrissian        79.0 Human          0.9715902
25 Lobot                   79.0 Human          0.9715902
26 Ackbar                  83.0 Mon Calamari   1.0000000
27 Mon Mothma                NA Human                 NA
28 Arvel Crynyd              NA Human                 NA
29 Wicket Systri Warrick   20.0 Ewok           1.0000000
30 Nien Nunb               68.0 Sullustan      1.0000000
⋮  ⋮                     ⋮      ⋮              ⋮
58 Mas Amedda               NA  Chagrian              NA
59 Gregar Typho           85.0  NA             1.0493827
60 Cordé                    NA  NA                    NA
61 Cliegg Lars              NA  Human                 NA
62 Poggle the Lesser      80.0  Geonosian      1.0000000
63 Luminara Unduli        56.2  Mirialan       1.0583804
64 Barriss Offee          50.0  Mirialan       0.9416196
65 Dormé                    NA  Human                 NA
66 Dooku                  80.0  Human          0.9838888
67 Bail Prestor Organa      NA  Human                 NA
68 Jango Fett             79.0  Human          0.9715902
69 Zam Wesell             55.0  Clawdite       1.0000000
70 Dexter Jettster       102.0  Besalisk       1.0000000
71 Lama Su                88.0  Kaminoan       1.0000000
72 Taun We                  NA  Kaminoan              NA
73 Jocasta Nu               NA  Human                 NA
74 R4-P17                   NA  Droid                 NA
75 Wat Tambor             48.0  Skakoan        1.0000000
76 San Hill                 NA  Muun                  NA
77 Shaak Ti               57.0  Togruta        1.0000000
78 Grievous              159.0  Kaleesh        1.0000000
79 Tarfful               136.0  Wookiee        1.0967742
80 Raymus Antilles        79.0  Human          0.9715902
81 Sly Moore              48.0  NA             0.5925926
82 Tion Medon             80.0  Pau'an         1.0000000
83 Finn                     NA  Human                 NA
84 Rey                      NA  Human                 NA
85 Poe Dameron              NA  Human                 NA
86 BB8                      NA  Droid                 NA
87 Captain Phasma           NA  Human                 NA

<pre class="sourceCode r"><code>
# By default, new columns are placed on the far right.</span></span></span>
df</span> &lt;-</span> <a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span>(</span>x =</span> <span class="fl">1</span>, y =</span> <span class="fl">2</span>)</span></span></span>
df</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> mutate</span>(</span>z =</span> x</span> +</span> y</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 1 × 3</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       x     y     z</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">1</span>     1     2     3</span>
df</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> mutate</span>(</span>z =</span> x</span> +</span> y</span>, .before =</span> <span class="fl">1</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 1 × 3</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       z     x     y</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">1</span>     3     1     2</span>
df</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> mutate</span>(</span>z =</span> x</span> +</span> y</span>, .after =</span> x</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 1 × 3</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       x     z     y</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">1</span>     1     3     2</span>
</span></span>
# By default, mutate() keeps all columns from the input data.</span></span></span>
df</span> &lt;-</span> <a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span>(</span>x =</span> <span class="fl">1</span>, y =</span> <span class="fl">2</span>, a =</span> "a"</span>, b =</span> "b"</span>)</span></span></span>
df</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> mutate</span>(</span>z =</span> x</span> +</span> y</span>, .keep =</span> "all"</span>)</span> # the default</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 1 × 5</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       x     y a     b         z</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span> <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">1</span>     1     2 a     b         3</span>
df</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> mutate</span>(</span>z =</span> x</span> +</span> y</span>, .keep =</span> "used"</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 1 × 3</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       x     y     z</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">1</span>     1     2     3</span>
df</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> mutate</span>(</span>z =</span> x</span> +</span> y</span>, .keep =</span> "unused"</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 1 × 3</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   a     b         z</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span> <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">1</span> a     b         3</span>
df</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> mutate</span>(</span>z =</span> x</span> +</span> y</span>, .keep =</span> "none"</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 1 × 1</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       z</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">1</span>     3</span>
</span></span>
# Grouping ----------------------------------------</span></span></span>
# The mutate operation may yield different results on grouped</span></span></span>
# tibbles because the expressions are computed within groups.</span></span></span>
# The following normalises `mass` by the global average:</span></span></span>
starwars</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span></span>
  <a href="select.html">select</a></span>(</span>name</span>, mass</span>, species</span>)</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span></span>
  mutate</span>(</span>mass_norm =</span> mass</span> /</span> <a href="https://rdrr.io/r/base/mean.html">mean</a></span>(</span>mass</span>, na.rm =</span> TRUE</span>)</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 87 × 4</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    name                mass species mass_norm</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>              <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>       <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 1</span> Luke Skywalker        77 Human       0.791</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 2</span> C-3PO                 75 Droid       0.771</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 3</span> R2-D2                 32 Droid       0.329</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 4</span> Darth Vader          136 Human       1.40 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 5</span> Leia Organa           49 Human       0.504</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 6</span> Owen Lars            120 Human       1.23 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 7</span> Beru Whitesun Lars    75 Human       0.771</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 8</span> R5-D4                 32 Droid       0.329</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 9</span> Biggs Darklighter     84 Human       0.863</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">10</span> Obi-Wan Kenobi        77 Human       0.791</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># ℹ 77 more rows</span></span>
</span></span>
# Whereas this normalises `mass` by the averages within species</span></span></span>
# levels:</span></span></span>
starwars</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span></span>
  <a href="select.html">select</a></span>(</span>name</span>, mass</span>, species</span>)</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span></span>
  <a href="group_by.html">group_by</a></span>(</span>species</span>)</span> <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span></span>
  mutate</span>(</span>mass_norm =</span> mass</span> /</span> <a href="https://rdrr.io/r/base/mean.html">mean</a></span>(</span>mass</span>, na.rm =</span> TRUE</span>)</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 87 × 4</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># Groups:   species [38]</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    name                mass species mass_norm</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>              <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>       <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 1</span> Luke Skywalker        77 Human       0.947</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 2</span> C-3PO                 75 Droid       1.08 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 3</span> R2-D2                 32 Droid       0.459</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 4</span> Darth Vader          136 Human       1.67 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 5</span> Leia Organa           49 Human       0.603</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 6</span> Owen Lars            120 Human       1.48 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 7</span> Beru Whitesun Lars    75 Human       0.922</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 8</span> R5-D4                 32 Droid       0.459</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 9</span> Biggs Darklighter     84 Human       1.03 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">10</span> Obi-Wan Kenobi        77 Human       0.947</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># ℹ 77 more rows</span></span>
</span></span>
# Indirection ----------------------------------------</span></span></span>
# Refer to column names stored as strings with the `.data` pronoun:</span></span></span>
vars</span> &lt;-</span> <a href="https://rdrr.io/r/base/c.html">c</a></span>(</span>"mass"</span>, "height"</span>)</span></span></span>
mutate</span>(</span>starwars</span>, prod =</span> .data</span>[[</span>vars</span>[[</span><span class="fl">1</span>]</span>]</span>]</span>]</span> *</span> .data</span>[[</span>vars</span>[[</span><span class="fl">2</span>]</span>]</span>]</span>]</span>)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># A tibble: 87 × 15</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    name   height  mass hair_color skin_color eye_color birth_year sex  </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>   <span style="color: #949494; font-style: italic;">&lt;int&gt;</span> <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>      <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>      <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span>          <span style="color: #949494; font-style: italic;">&lt;dbl&gt;</span> <span style="color: #949494; font-style: italic;">&lt;chr&gt;</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 1</span> Luke …    172    77 blond      fair       blue            19   male </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 2</span> C-3PO     167    75 <span style="color: #BB0000;">NA</span>         gold       yellow         112   none </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 3</span> R2-D2      96    32 <span style="color: #BB0000;">NA</span>         white, bl… red             33   none </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 4</span> Darth…    202   136 none       white      yellow          41.9 male </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 5</span> Leia …    150    49 brown      light      brown           19   fema…</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 6</span> Owen …    178   120 brown, gr… light      blue            52   male </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 7</span> Beru …    165    75 brown      light      blue            47   fema…</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 8</span> R5-D4      97    32 <span style="color: #BB0000;">NA</span>         white, red red             <span style="color: #BB0000;">NA</span>   none </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;"> 9</span> Biggs…    183    84 black      light      brown           24   male </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #BCBCBC;">10</span> Obi-W…    182    77 auburn, w… fair       blue-gray       57   male </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># ℹ 77 more rows</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;"># ℹ 7 more variables: gender &lt;chr&gt;, homeworld &lt;chr&gt;, species &lt;chr&gt;,</span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> <span style="color: #949494;">#   films &lt;list&gt;, vehicles &lt;list&gt;, starships &lt;list&gt;, prod &lt;dbl&gt;</span></span>
# Learn more in ?rlang::args_data_masking</span></span></span>
</code></pre></div>