<h1>Introduction to dplyr</h1>

<small>Source: <a href="https://github.com/tidyverse/dplyr/blob/pkgdown-v1.1.4/vignettes/dplyr.Rmd"><code>vignettes/dplyr.Rmd</code></a></small>
<div><code>dplyr.Rmd</code></div>


<p>When working with data you must:</p>

<ul>
<li><p>Figure out what you want to do.</p></li>
<li><p>Describe those tasks in the form of a computer program.</p></li>
<li><p>Execute the program.</p></li>
</ul>

<p>The dplyr package makes these steps fast and easy:</p>

<ul>
<li><p>By constraining your options, it helps you think about your data manipulation challenges.</p></li>
<li><p>It provides simple “verbs”, functions that correspond to the most common data manipulation tasks, to help you translate your thoughts into
code.</p></li>
<li><p>It uses efficient backends, so you spend less time waiting for the computer.</p></li>
</ul>

<p>This document introduces you to dplyr’s basic set of tools, and shows you how to apply them to data frames. dplyr also supports databases via
the dbplyr package, once you’ve installed, read <code>vignette("dbplyr")</code> to learn more.</p>

# <h2 id="data-starwars">Data: starwars</h2>

<p>To explore the basic data manipulation verbs of dplyr, we’ll use the dataset <code>starwars</code>. This dataset contains 87 characters and
comes from the <a href="https://swapi.dev">Star Wars API</a>, and is documented in <code><a href="https://dplyr.tidyverse.org/reference/starwars.html">?starwars</a></code></p>

In [34]:
library(dplyr)

In [35]:
dim(starwars)

[1] 87 14

In [3]:
starwars

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Cordé                 157       NA  brown         light
59 Cliegg Lars           183       NA  brown         fair
60 Poggle the Lesser     183     80.0  none          green
61 Luminara Unduli       170     56.2  black         yellow
62 Barriss Offee         166     50.0  black         yellow
63 Dormé                 165       NA  brown         light
64 Dooku                 193     80.0  white         fair
65 Bail Prestor Organa   191       NA  black         tan
66 Jango Fett            183     79.0  black         tan
67 Zam Wesell            168     55.0  blonde        fair, green, yellow
68 Dexter Jettster       198    102.0  none          brown
69 Lama Su               229     88.0  none          grey
70 Taun We               213       NA  none          grey
71 Jocasta Nu            167       NA  white         fair
72 Ratts Tyerell          79     15.0  none          grey, blue
73 R4-P17                 96       NA  none          silver, red
74 Wat Tambor            193     48.0  none          green, grey
75 San Hill              191       NA  none          grey
76 Shaak Ti              178     57.0  none          red, blue, white
77 Grievous              216    159.0  none          brown, white
78 Tarfful               234    136.0  brown         brown
79 Raymus Antilles       188     79.0  brown         light
80 Sly Moore             178     48.0  none          pale
81 Tion Medon            206     80.0  none          grey
82 Finn                   NA       NA  black         dark
83 Rey                    NA       NA  brown         light
84 Poe Dameron            NA       NA  brown         light
85 BB8                    NA       NA  none          none
86 Captain Phasma         NA       NA  unknown       unknown
87 Padmé Amidala         165     45.0  brown         light
   eye_color     birth_year sex            gender    homeworld
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      male           masculine Bestine IV
19 brown         896.0      male           masculine NA
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine NA
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine NA
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 brown          NA        female         feminine  Naboo
59 blue           82        male           masculine Tatooine
60 yellow         NA        male           masculine Geonosis
61 blue           58        female         feminine  Mirial
62 blue           40        female         feminine  Mirial
63 brown          NA        female         feminine  Naboo
64 brown         102        male           masculine Serenno
65 brown          67        male           masculine Alderaan
66 brown          66        male           masculine Concord Dawn
67 yellow         NA        female         feminine  Zolan
68 yellow         NA        male           masculine Ojom
69 black          NA        male           masculine Kamino
70 black          NA        female         feminine  Kamino
71 blue           NA        female         feminine  Coruscant
72 unknown        NA        male           masculine Aleen Minor
73 red, blue      NA        none           feminine  NA
74 unknown        NA        male           masculine Skako
75 gold           NA        male           masculine Muunilinst
76 black          NA        female         feminine  Shili
77 green, yellow  NA        male           masculine Kalee
78 blue           NA        male           masculine Kashyyyk
79 brown          NA        male           masculine Alderaan
80 white          NA        NA             NA        Umbara
81 black          NA        male           masculine Utapau
82 dark           NA        male           masculine NA
83 hazel          NA        female         feminine  NA
84 brown          NA        male           masculine NA
85 black          NA        none           masculine NA
86 unknown        NA        NA             NA        NA
87 brown          46        female         feminine  Naboo
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 Human
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Human
59 Human
60 Geonosian
61 Mirialan
62 Mirialan
63 Human
64 Human
65 Human
66 Human
67 Clawdite
68 Besalisk
69 Kaminoan
70 Kaminoan
71 Human
72 Aleena
73 Droid
74 Skakoan
75 Muun
76 Togruta
77 Kaleesh
78 Wookiee
79 Human
80 NA
81 Pau'an
82 Human
83 Human
84 Human
85 Droid
86 NA
87 Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

<p>Note that <code>starwars</code> is a tibble, a modern reimagining of the data frame. It’s particularly useful for large datasets because it
only prints the first few rows. You can learn more about tibbles at <a href="https://tibble.tidyverse.org">https://tibble.tidyverse.org</a>; in particular you can convert data frames to tibbles with <code><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble()</a></code>.</p>


# <h2 id="single-table-verbs">Single table verbs</h2>

<p>dplyr aims to provide a function for each basic verb of data manipulation. These verbs can be organised into three categories based on the component of the dataset that they work with:</p>

<ul>
    
<li>Rows:
<ul>
<li><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> chooses rows based on column values.</li>
<li><code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code> chooses rows based on location.</li>
<li><code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> changes the order of the rows.</li>
</ul>
</li>

<li>Columns:
<ul>
<li><code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> changes whether or not a column is included.</li>
<li><code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename()</a></code> changes the name of columns.</li>
<li><code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> changes the values of columns and creates new columns.</li>
<li><code><a href="https://dplyr.tidyverse.org/reference/relocate.html">relocate()</a></code> changes the order of the columns.</li>
</ul>
</li>
                 
<li>Groups of rows:
<ul>
<li><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> collapses a group into a single row.</li>
</ul>
</li>
                 
</ul>


## <h3 id="the-pipe">The pipe</h3>

<p>All of the dplyr functions take a data frame (or tibble) as the first argument. Rather than forcing the user to either save intermediate
objects or nest functions, dplyr provides the <code>%&gt;%</code> operator from magrittr. <code>x %&gt;% f(y)</code> turns into <code>f(x, y)</code> so the result from one step is then “piped” into the next step. You can use the pipe to rewrite multiple operations that you can read left-to-right, top-to-bottom (reading the pipe operator as “then”).</p>


## <h3 id="filter-rows-with-filter">Filter rows with <code>filter()</code></h3>

<p><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> allows you to select a subset of rows in a data frame. Like all single verbs, the first argument is the tibble (or data frame). The second and subsequent arguments refer to variables within that data frame, selecting rows where the expression is <code>TRUE</code>.</p>
    
<p>For example, we can select all character with light skin color and brown eyes with:</p>

In [4]:
starwars |> filter(skin_color == "light", eye_color == "brown")

  name              height mass hair_color skin_color eye_color birth_year
1 Leia Organa       150    49   brown      light      brown     19
2 Biggs Darklighter 183    84   black      light      brown     24
3 Cordé             157    NA   brown      light      brown     NA
4 Dormé             165    NA   brown      light      brown     NA
5 Raymus Antilles   188    79   brown      light      brown     NA
6 Poe Dameron        NA    NA   brown      light      brown     NA
7 Padmé Amidala     165    45   brown      light      brown     46
  sex    gender    homeworld species
1 female feminine  Alderaan  Human
2 male   masculine Tatooine  Human
3 female feminine  Naboo     Human
4 female feminine  Naboo     Human
5 male   masculine Alderaan  Human
6 male   masculine NA        Human
7 female feminine  Naboo     Human
  films
1 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2 A New Hope
3 Attack of the Clones
4 Attack of the Clones
5 Revenge of the Sith, A New Hope
6 The Force Awakens
7 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
  vehicles
1 Imperial Speeder Bike
2
3
4
5
6
7
  starships
1
2 X-wing
3
4
5
6 T-70 X-wing fighter
7 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

<p>This is roughly equivalent to this base R code:</p>

<pre><code>starwars[starwars$skin_color == "light" & starwars$eye_color == "brown"]</code></pre>

## <h3 id="arrange-rows-with-arrange">Arrange rows with <code>arrange()</code></h3>

<p><code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> works similarly to <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> except that instead of filtering or selecting rows, it reorders them. It takes a data frame, and a set of column names (or more complicated expressions) to order by. If you provide more than one column name, each additional column will be used to break ties in the values of preceding columns:</p>

In [5]:
starwars |> arrange(height, mass)

   name                  height mass hair_color skin_color
1  Yoda                   66    17.0 white      green
2  Ratts Tyerell          79    15.0 none       grey, blue
3  Wicket Systri Warrick  88    20.0 brown      brown
4  Dud Bolt               94    45.0 none       blue, grey
5  R2-D2                  96    32.0 NA         white, blue
6  R4-P17                 96      NA none       silver, red
7  R5-D4                  97    32.0 NA         white, red
8  Sebulba               112    40.0 none       grey, red
9  Gasgano               122      NA none       white, blue
10 Watto                 137      NA black      blue, grey
11 Leia Organa           150    49.0 brown      light
12 Mon Mothma            150      NA auburn     fair
13 Cordé                 157      NA brown      light
14 Nien Nunb             160    68.0 none       grey
15 Ben Quadinaros        163    65.0 none       grey, green, yellow
16 Shmi Skywalker        163      NA black      fair
17 Padmé Amidala         165    45.0 brown      light
18 Beru Whitesun lars    165    75.0 brown      light
19 Dormé                 165      NA brown      light
20 Barriss Offee         166    50.0 black      yellow
21 C-3PO                 167    75.0 NA         gold
22 Jocasta Nu            167      NA white      fair
23 Zam Wesell            168    55.0 blonde     fair, green, yellow
24 Luminara Unduli       170    56.2 black      yellow
25 Palpatine             170    75.0 grey       pale
26 Wedge Antilles        170    77.0 brown      fair
27 Finis Valorum         170      NA blond      fair
28 Eeth Koth             171      NA black      brown
29 Luke Skywalker        172    77.0 blond      fair
30 Greedo                173    74.0 NA         green
⋮  ⋮                     ⋮      ⋮    ⋮          ⋮
58 Saesee Tiin           188     NA  none       pale
59 Bossk                 190    113  none       green
60 Nute Gunray           191     90  none       mottled green
61 Bail Prestor Organa   191     NA  black      tan
62 San Hill              191     NA  none       grey
63 Wat Tambor            193     48  none       green, grey
64 Dooku                 193     80  white      fair
65 Qui-Gon Jinn          193     89  brown      fair
66 Jar Jar Binks         196     66  none       orange
67 Kit Fisto             196     87  none       green
68 Mas Amedda            196     NA  none       blue
69 Ki-Adi-Mundi          198     82  white      pale
70 Dexter Jettster       198    102  none       brown
71 IG-88                 200    140  none       metal
72 Darth Vader           202    136  none       white
73 Tion Medon            206     80  none       grey
74 Rugor Nass            206     NA  none       green
75 Taun We               213     NA  none       grey
76 Grievous              216    159  none       brown, white
77 Roos Tarpals          224     82  none       grey
78 Chewbacca             228    112  brown      unknown
79 Lama Su               229     88  none       grey
80 Tarfful               234    136  brown      brown
81 Yarael Poof           264     NA  none       white
82 Arvel Crynyd           NA     NA  brown      fair
83 Finn                   NA     NA  black      dark
84 Rey                    NA     NA  brown      light
85 Poe Dameron            NA     NA  brown      light
86 BB8                    NA     NA  none       none
87 Captain Phasma         NA     NA  unknown    unknown
   eye_color     birth_year sex    gender    homeworld      species
1  brown         896        male   masculine NA             Yoda's species
2  unknown        NA        male   masculine Aleen Minor    Aleena
3  brown           8        male   masculine Endor          Ewok
4  yellow         NA        male   masculine Vulpter        Vulptereen
5  red            33        none   masculine Naboo          Droid
6  red, blue      NA        none   feminine  NA             Droid
7  red            NA        none   masculine Tatooine       Droid
8  orange         NA        male   masculine Malastare      Dug
9  black          NA        male   masculine Troiken        Xexto
10 yellow         NA        male   masculine Toydaria       Toydarian
11 brown          19        female feminine  Alderaan       Human
12 blue           48        female feminine  Chandrila      Human
13 brown          NA        female feminine  Naboo          Human
14 black          NA        male   masculine Sullust        Sullustan
15 orange         NA        male   masculine Tund           Toong
16 brown          72        female feminine  Tatooine       Human
17 brown          46        female feminine  Naboo          Human
18 blue           47        female feminine  Tatooine       Human
19 brown          NA        female feminine  Naboo          Human
20 blue           40        female feminine  Mirial         Mirialan
21 yellow        112        none   masculine Tatooine       Droid
22 blue           NA        female feminine  Coruscant      Human
23 yellow         NA        female feminine  Zolan          Clawdite
24 blue           58        female feminine  Mirial         Mirialan
25 yellow         82        male   masculine Naboo          Human
26 hazel          21        male   masculine Corellia       Human
27 blue           91        male   masculine Coruscant      Human
28 brown          NA        male   masculine Iridonia       Zabrak
29 blue           19        male   masculine Tatooine       Human
30 black          44        male   masculine Rodia          Rodian
⋮  ⋮             ⋮          ⋮      ⋮         ⋮              ⋮
58 orange           NA      male   masculine Iktotch        Iktotchi
59 red            53.0      male   masculine Trandosha      Trandoshan
60 red              NA      male   masculine Cato Neimoidia Neimodian
61 brown          67.0      male   masculine Alderaan       Human
62 gold             NA      male   masculine Muunilinst     Muun
63 unknown          NA      male   masculine Skako          Skakoan
64 brown         102.0      male   masculine Serenno        Human
65 blue           92.0      male   masculine NA             Human
66 orange         52.0      male   masculine Naboo          Gungan
67 black            NA      male   masculine Glee Anselm    Nautolan
68 blue             NA      male   masculine Champala       Chagrian
69 yellow         92.0      male   masculine Cerea          Cerean
70 yellow           NA      male   masculine Ojom           Besalisk
71 red            15.0      none   masculine NA             Droid
72 yellow         41.9      male   masculine Tatooine       Human
73 black            NA      male   masculine Utapau         Pau'an
74 orange           NA      male   masculine Naboo          Gungan
75 black            NA      female feminine  Kamino         Kaminoan
76 green, yellow    NA      male   masculine Kalee          Kaleesh
77 orange           NA      male   masculine Naboo          Gungan
78 blue          200.0      male   masculine Kashyyyk       Wookiee
79 black            NA      male   masculine Kamino         Kaminoan
80 blue             NA      male   masculine Kashyyyk       Wookiee
81 yellow           NA      male   masculine Quermia        Quermian
82 brown            NA      male   masculine NA             Human
83 dark             NA      male   masculine NA             Human
84 hazel            NA      female feminine  NA             Human
85 brown            NA      male   masculine NA             Human
86 black            NA      none   masculine NA             Droid
87 unknown          NA      NA     NA        NA             NA
   films
1  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
2  The Phantom Menace
3  Return of the Jedi
4  The Phantom Menace
5  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith
7  A New Hope
8  The Phantom Menace
9  The Phantom Menace
10 Attack of the Clones, The Phantom Menace
11 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
12 Return of the Jedi
13 Attack of the Clones
14 Return of the Jedi
15 The Phantom Menace
16 Attack of the Clones, The Phantom Menace
17 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
18 Attack of the Clones, Revenge of the Sith , A New Hope
19 Attack of the Clones
20 Attack of the Clones
21 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
22 Attack of the Clones
23 Attack of the Clones
24 Attack of the Clones, Revenge of the Sith
25 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
26 The Empire Strikes Back, Return of the Jedi     , A New Hope
27 The Phantom Menace
28 The Phantom Menace , Revenge of the Sith
29 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
30 A New Hope
⋮  ⋮
58 The Phantom Menace , Revenge of the Sith
59 The Empire Strikes Back
60 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 The Phantom Menace
66 Attack of the Clones, The Phantom Menace
67 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
68 Attack of the Clones, The Phantom Menace
69 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
70 Attack of the Clones
71 The Empire Strikes Back
72 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
73 Revenge of the Sith
74 The Phantom Menace
75 Attack of the Clones
76 Revenge of the Sith
77 The Phantom Menace
78 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
79 Attack of the Clones
80 Revenge of the Sith
81 The Phantom Menace
82 Return of the Jedi
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 The Force Awakens
   vehicles
1
2
3
4
5
6
7
8
9
10
11 Imperial Speeder Bike
12
13
14
15
16
17
18
19
20
21
22
23 Koro-2 Exodrive airspeeder
24
25
26 Snowspeeder
27
28
29 Snowspeeder          , Imperial Speeder Bike
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65 Tribubble bongo
66
67
68
69
70
71
72
73
74
75
76 Tsmeu-6 personal wheel bike
77
78 AT-ST
79
80
81
82
83
84
85
86
87
   starships
1
2
3
4
5
6
7
8
9
10
11
12
13
14 Millennium Falcon
15
16
17 H-type Nubian yacht, Naboo star skiff   , Naboo fighter
18
19
20
21
22
23
24
25
26 X-wing
27
28
29 X-wing          , Imperial shuttle
30
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72 TIE Advanced x1
73
74
75
76 Belbullab-22 starfighter
77
78 Millennium Falcon, Imperial shuttle
79
80
81
82 A-wing
83
84
85 T-70 X-wing fighter
86
87

<p>Use <code><a href="https://dplyr.tidyverse.org/reference/desc.html">desc()</a></code> to order a column in descending order:</p>

In [6]:
starwars |> arrange(desc(height))

   name                  height mass hair_color skin_color
1  Yarael Poof           264     NA  none       white
2  Tarfful               234    136  brown      brown
3  Lama Su               229     88  none       grey
4  Chewbacca             228    112  brown      unknown
5  Roos Tarpals          224     82  none       grey
6  Grievous              216    159  none       brown, white
7  Taun We               213     NA  none       grey
8  Rugor Nass            206     NA  none       green
9  Tion Medon            206     80  none       grey
10 Darth Vader           202    136  none       white
11 IG-88                 200    140  none       metal
12 Ki-Adi-Mundi          198     82  white      pale
13 Dexter Jettster       198    102  none       brown
14 Jar Jar Binks         196     66  none       orange
15 Kit Fisto             196     87  none       green
16 Mas Amedda            196     NA  none       blue
17 Qui-Gon Jinn          193     89  brown      fair
18 Dooku                 193     80  white      fair
19 Wat Tambor            193     48  none       green, grey
20 Nute Gunray           191     90  none       mottled green
21 Bail Prestor Organa   191     NA  black      tan
22 San Hill              191     NA  none       grey
23 Bossk                 190    113  none       green
24 Anakin Skywalker      188     84  blond      fair
25 Mace Windu            188     84  none       dark
26 Saesee Tiin           188     NA  none       pale
27 Plo Koon              188     80  none       orange
28 Raymus Antilles       188     79  brown      light
29 Gregar Typho          185     85  black      dark
30 Adi Gallia            184     50  none       dark
⋮  ⋮                     ⋮      ⋮    ⋮          ⋮
58 Luminara Unduli       170    56.2 black      yellow
59 Zam Wesell            168    55.0 blonde     fair, green, yellow
60 C-3PO                 167    75.0 NA         gold
61 Jocasta Nu            167      NA white      fair
62 Barriss Offee         166    50.0 black      yellow
63 Beru Whitesun lars    165    75.0 brown      light
64 Dormé                 165      NA brown      light
65 Padmé Amidala         165    45.0 brown      light
66 Shmi Skywalker        163      NA black      fair
67 Ben Quadinaros        163    65.0 none       grey, green, yellow
68 Nien Nunb             160    68.0 none       grey
69 Cordé                 157      NA brown      light
70 Leia Organa           150    49.0 brown      light
71 Mon Mothma            150      NA auburn     fair
72 Watto                 137      NA black      blue, grey
73 Gasgano               122      NA none       white, blue
74 Sebulba               112    40.0 none       grey, red
75 R5-D4                  97    32.0 NA         white, red
76 R2-D2                  96    32.0 NA         white, blue
77 R4-P17                 96      NA none       silver, red
78 Dud Bolt               94    45.0 none       blue, grey
79 Wicket Systri Warrick  88    20.0 brown      brown
80 Ratts Tyerell          79    15.0 none       grey, blue
81 Yoda                   66    17.0 white      green
82 Arvel Crynyd           NA      NA brown      fair
83 Finn                   NA      NA black      dark
84 Rey                    NA      NA brown      light
85 Poe Dameron            NA      NA brown      light
86 BB8                    NA      NA none       none
87 Captain Phasma         NA      NA unknown    unknown
   eye_color     birth_year sex    gender    homeworld      species
1  yellow           NA      male   masculine Quermia        Quermian
2  blue             NA      male   masculine Kashyyyk       Wookiee
3  black            NA      male   masculine Kamino         Kaminoan
4  blue          200.0      male   masculine Kashyyyk       Wookiee
5  orange           NA      male   masculine Naboo          Gungan
6  green, yellow    NA      male   masculine Kalee          Kaleesh
7  black            NA      female feminine  Kamino         Kaminoan
8  orange           NA      male   masculine Naboo          Gungan
9  black            NA      male   masculine Utapau         Pau'an
10 yellow         41.9      male   masculine Tatooine       Human
11 red            15.0      none   masculine NA             Droid
12 yellow         92.0      male   masculine Cerea          Cerean
13 yellow           NA      male   masculine Ojom           Besalisk
14 orange         52.0      male   masculine Naboo          Gungan
15 black            NA      male   masculine Glee Anselm    Nautolan
16 blue             NA      male   masculine Champala       Chagrian
17 blue           92.0      male   masculine NA             Human
18 brown         102.0      male   masculine Serenno        Human
19 unknown          NA      male   masculine Skako          Skakoan
20 red              NA      male   masculine Cato Neimoidia Neimodian
21 brown          67.0      male   masculine Alderaan       Human
22 gold             NA      male   masculine Muunilinst     Muun
23 red            53.0      male   masculine Trandosha      Trandoshan
24 blue           41.9      male   masculine Tatooine       Human
25 brown          72.0      male   masculine Haruun Kal     Human
26 orange           NA      male   masculine Iktotch        Iktotchi
27 black          22.0      male   masculine Dorin          Kel Dor
28 brown            NA      male   masculine Alderaan       Human
29 brown            NA      male   masculine Naboo          Human
30 blue             NA      female feminine  Coruscant      Tholothian
⋮  ⋮             ⋮          ⋮      ⋮         ⋮              ⋮
58 blue           58        female feminine  Mirial         Mirialan
59 yellow         NA        female feminine  Zolan          Clawdite
60 yellow        112        none   masculine Tatooine       Droid
61 blue           NA        female feminine  Coruscant      Human
62 blue           40        female feminine  Mirial         Mirialan
63 blue           47        female feminine  Tatooine       Human
64 brown          NA        female feminine  Naboo          Human
65 brown          46        female feminine  Naboo          Human
66 brown          72        female feminine  Tatooine       Human
67 orange         NA        male   masculine Tund           Toong
68 black          NA        male   masculine Sullust        Sullustan
69 brown          NA        female feminine  Naboo          Human
70 brown          19        female feminine  Alderaan       Human
71 blue           48        female feminine  Chandrila      Human
72 yellow         NA        male   masculine Toydaria       Toydarian
73 black          NA        male   masculine Troiken        Xexto
74 orange         NA        male   masculine Malastare      Dug
75 red            NA        none   masculine Tatooine       Droid
76 red            33        none   masculine Naboo          Droid
77 red, blue      NA        none   feminine  NA             Droid
78 yellow         NA        male   masculine Vulpter        Vulptereen
79 brown           8        male   masculine Endor          Ewok
80 unknown        NA        male   masculine Aleen Minor    Aleena
81 brown         896        male   masculine NA             Yoda's species
82 brown          NA        male   masculine NA             Human
83 dark           NA        male   masculine NA             Human
84 hazel          NA        female feminine  NA             Human
85 brown          NA        male   masculine NA             Human
86 black          NA        none   masculine NA             Droid
87 unknown        NA        NA     NA        NA             NA
   films
1  The Phantom Menace
2  Revenge of the Sith
3  Attack of the Clones
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
5  The Phantom Menace
6  Revenge of the Sith
7  Attack of the Clones
8  The Phantom Menace
9  Revenge of the Sith
10 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
11 The Empire Strikes Back
12 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
13 Attack of the Clones
14 Attack of the Clones, The Phantom Menace
15 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
16 Attack of the Clones, The Phantom Menace
17 The Phantom Menace
18 Attack of the Clones, Revenge of the Sith
19 Attack of the Clones
20 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
21 Attack of the Clones, Revenge of the Sith
22 Attack of the Clones
23 The Empire Strikes Back
24 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
25 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
26 The Phantom Menace , Revenge of the Sith
27 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
28 Revenge of the Sith, A New Hope
29 Attack of the Clones
30 The Phantom Menace , Revenge of the Sith
⋮  ⋮
58 Attack of the Clones, Revenge of the Sith
59 Attack of the Clones
60 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
61 Attack of the Clones
62 Attack of the Clones
63 Attack of the Clones, Revenge of the Sith , A New Hope
64 Attack of the Clones
65 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
66 Attack of the Clones, The Phantom Menace
67 The Phantom Menace
68 Return of the Jedi
69 Attack of the Clones
70 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
71 Return of the Jedi
72 Attack of the Clones, The Phantom Menace
73 The Phantom Menace
74 The Phantom Menace
75 A New Hope
76 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
77 Attack of the Clones, Revenge of the Sith
78 The Phantom Menace
79 Return of the Jedi
80 The Phantom Menace
81 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
82 Return of the Jedi
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 The Force Awakens
   vehicles
1
2
3
4  AT-ST
5
6  Tsmeu-6 personal wheel bike
7
8
9
10
11
12
13
14
15
16
17 Tribubble bongo
18 Flitknot speeder
19
20
21
22
23
24 Zephyr-G swoop bike, XJ-6 airspeeder
25
26
27
28
29
30
⋮  ⋮
58
59 Koro-2 Exodrive airspeeder
60
61
62
63
64
65
66
67
68
69
70 Imperial Speeder Bike
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
   starships
1
2
3
4  Millennium Falcon, Imperial shuttle
5
6  Belbullab-22 starfighter
7
8
9
10 TIE Advanced x1
11
12
13
14
15
16
17
18
19
20
21
22
23
24 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
25
26
27 Jedi starfighter
28
29 Naboo fighter
30
⋮  ⋮
58
59
60
61
62
63
64
65 H-type Nubian yacht, Naboo star skiff   , Naboo fighter
66
67
68 Millennium Falcon
69
70
71
72
73
74
75
76
77
78
79
80
81
82 A-wing
83
84
85 T-70 X-wing fighter
86
87

## <h3 id="choose-rows-using-their-position-with-slice">Choose rows using their position with <code>slice()</code></h3>

<p><code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code> lets you index rows by their (integer) locations. It allows you to select, remove, and duplicate rows.</p>

<p>We can get characters from row numbers 5 through 10.</p>

In [7]:
starwars |> slice(5:10)

  name               height mass hair_color    skin_color eye_color birth_year
1 Leia Organa        150     49  brown         light      brown     19
2 Owen Lars          178    120  brown, grey   light      blue      52
3 Beru Whitesun lars 165     75  brown         light      blue      47
4 R5-D4               97     32  NA            white, red red       NA
5 Biggs Darklighter  183     84  black         light      brown     24
6 Obi-Wan Kenobi     182     77  auburn, white fair       blue-gray 57
  sex    gender    homeworld species
1 female feminine  Alderaan  Human
2 male   masculine Tatooine  Human
3 female feminine  Tatooine  Human
4 none   masculine Tatooine  Droid
5 male   masculine Tatooine  Human
6 male   masculine Stewjon   Human
  films
1 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2 Attack of the Clones, Revenge of the Sith , A New Hope
3 Attack of the Clones, Revenge of the Sith , A New Hope
4 A New Hope
5 A New Hope
6 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
  vehicles
1 Imperial Speeder Bike
2
3
4
5
6 Tribubble bongo
  starships
1
2
3
4
5 X-wing
6 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter

<p>It is accompanied by a number of helpers for common use cases:</p>

<ul>
<li><code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_head()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_tail()</a></code> select the first or last rows.</li>
</ul>

In [8]:
starwars |> slice_head(n = 3)

  name           height mass hair_color skin_color  eye_color birth_year sex
1 Luke Skywalker 172    77   blond      fair        blue       19        male
2 C-3PO          167    75   NA         gold        yellow    112        none
3 R2-D2           96    32   NA         white, blue red        33        none
  gender    homeworld species
1 masculine Tatooine  Human
2 masculine Tatooine  Droid
3 masculine Naboo     Droid
  films
1 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
  vehicles
1 Snowspeeder          , Imperial Speeder Bike
2
3
  starships
1 X-wing          , Imperial shuttle
2
3

<ul>
<li><code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_sample()</a></code> randomly selects rows. Use the option prop to choose a certain proportion of the cases.</li>
</ul>

In [9]:
starwars |> slice_sample(n = 5)

  name            height mass hair_color skin_color eye_color birth_year sex
1 Rey              NA     NA  brown      light      hazel      NA        female
2 Chewbacca       228    112  brown      unknown    blue      200        male
3 Arvel Crynyd     NA     NA  brown      fair       brown      NA        male
4 Ayla Secura     178     55  none       blue       hazel      48        female
5 Raymus Antilles 188     79  brown      light      brown      NA        male
  gender    homeworld species
1 feminine  NA        Human
2 masculine Kashyyyk  Wookiee
3 masculine NA        Human
4 feminine  Ryloth    Twi'lek
5 masculine Alderaan  Human
  films
1 The Force Awakens
2 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
3 Return of the Jedi
4 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
5 Revenge of the Sith, A New Hope
  vehicles starships
1
2 AT-ST    Millennium Falcon, Imperial shuttle
3          A-wing
4
5

<p>Use <code>replace = TRUE</code> to perform a bootstrap sample. If needed, you can weight the sample with the <code>weight</code> argument.</p>

<ul>
<li><code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_min()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_max()</a></code> select rows with highest or lowest values of a variable. Note that we first must choose only the values which are not NA.</li>
</ul>

In [10]:
starwars |>
filter(!is.na(height)) |>
  slice_max(height, n = 3)

  name        height mass hair_color skin_color eye_color birth_year sex
1 Yarael Poof 264     NA  none       white      yellow    NA         male
2 Tarfful     234    136  brown      brown      blue      NA         male
3 Lama Su     229     88  none       grey       black     NA         male
  gender    homeworld species  films                vehicles starships
1 masculine Quermia   Quermian The Phantom Menace
2 masculine Kashyyyk  Wookiee  Revenge of the Sith
3 masculine Kamino    Kaminoan Attack of the Clones

## <h3 id="select-columns-with-select">Select columns with <code>select()</code></h3>

<p>Often you work with large datasets with many columns but only a few are actually of interest to you. <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> allows you to rapidly zoom in on a useful subset using operations that usually only work on numeric variable positions:</p>

In [11]:
# Select columns by name
starwars |> select(hair_color, skin_color, eye_color)

   hair_color    skin_color          eye_color
1  blond         fair                blue
2  NA            gold                yellow
3  NA            white, blue         red
4  none          white               yellow
5  brown         light               brown
6  brown, grey   light               blue
7  brown         light               blue
8  NA            white, red          red
9  black         light               brown
10 auburn, white fair                blue-gray
11 blond         fair                blue
12 auburn, grey  fair                blue
13 brown         unknown             blue
14 brown         fair                brown
15 NA            green               black
16 NA            green-tan, brown    orange
17 brown         fair                hazel
18 brown         fair                blue
19 white         green               brown
20 grey          pale                yellow
21 black         fair                brown
22 none          metal               red
23 none          green               red
24 black         dark                brown
25 none          light               blue
26 none          brown mottle        orange
27 auburn        fair                blue
28 brown         fair                brown
29 brown         brown               brown
30 none          grey                black
⋮  ⋮             ⋮                   ⋮
58 brown         light               brown
59 brown         fair                blue
60 none          green               yellow
61 black         yellow              blue
62 black         yellow              blue
63 brown         light               brown
64 white         fair                brown
65 black         tan                 brown
66 black         tan                 brown
67 blonde        fair, green, yellow yellow
68 none          brown               yellow
69 none          grey                black
70 none          grey                black
71 white         fair                blue
72 none          grey, blue          unknown
73 none          silver, red         red, blue
74 none          green, grey         unknown
75 none          grey                gold
76 none          red, blue, white    black
77 none          brown, white        green, yellow
78 brown         brown               blue
79 brown         light               brown
80 none          pale                white
81 none          grey                black
82 black         dark                dark
83 brown         light               hazel
84 brown         light               brown
85 none          none                black
86 unknown       unknown             unknown
87 brown         light               brown

In [12]:
# Select all columns between hair_color and eye_color (inclusive)
starwars |> select(hair_color:eye_color)

   hair_color    skin_color          eye_color
1  blond         fair                blue
2  NA            gold                yellow
3  NA            white, blue         red
4  none          white               yellow
5  brown         light               brown
6  brown, grey   light               blue
7  brown         light               blue
8  NA            white, red          red
9  black         light               brown
10 auburn, white fair                blue-gray
11 blond         fair                blue
12 auburn, grey  fair                blue
13 brown         unknown             blue
14 brown         fair                brown
15 NA            green               black
16 NA            green-tan, brown    orange
17 brown         fair                hazel
18 brown         fair                blue
19 white         green               brown
20 grey          pale                yellow
21 black         fair                brown
22 none          metal               red
23 none          green               red
24 black         dark                brown
25 none          light               blue
26 none          brown mottle        orange
27 auburn        fair                blue
28 brown         fair                brown
29 brown         brown               brown
30 none          grey                black
⋮  ⋮             ⋮                   ⋮
58 brown         light               brown
59 brown         fair                blue
60 none          green               yellow
61 black         yellow              blue
62 black         yellow              blue
63 brown         light               brown
64 white         fair                brown
65 black         tan                 brown
66 black         tan                 brown
67 blonde        fair, green, yellow yellow
68 none          brown               yellow
69 none          grey                black
70 none          grey                black
71 white         fair                blue
72 none          grey, blue          unknown
73 none          silver, red         red, blue
74 none          green, grey         unknown
75 none          grey                gold
76 none          red, blue, white    black
77 none          brown, white        green, yellow
78 brown         brown               blue
79 brown         light               brown
80 none          pale                white
81 none          grey                black
82 black         dark                dark
83 brown         light               hazel
84 brown         light               brown
85 none          none                black
86 unknown       unknown             unknown
87 brown         light               brown

In [13]:
# Select all columns except those from hair_color to eye_color (inclusive)
starwars %>% select(!(hair_color:eye_color))

   name                  height mass   birth_year sex            gender
1  Luke Skywalker        172      77.0  19.0      male           masculine
2  C-3PO                 167      75.0 112.0      none           masculine
3  R2-D2                  96      32.0  33.0      none           masculine
4  Darth Vader           202     136.0  41.9      male           masculine
5  Leia Organa           150      49.0  19.0      female         feminine
6  Owen Lars             178     120.0  52.0      male           masculine
7  Beru Whitesun lars    165      75.0  47.0      female         feminine
8  R5-D4                  97      32.0    NA      none           masculine
9  Biggs Darklighter     183      84.0  24.0      male           masculine
10 Obi-Wan Kenobi        182      77.0  57.0      male           masculine
11 Anakin Skywalker      188      84.0  41.9      male           masculine
12 Wilhuff Tarkin        180        NA  64.0      male           masculine
13 Chewbacca             228     112.0 200.0      male           masculine
14 Han Solo              180      80.0  29.0      male           masculine
15 Greedo                173      74.0  44.0      male           masculine
16 Jabba Desilijic Tiure 175    1358.0 600.0      hermaphroditic masculine
17 Wedge Antilles        170      77.0  21.0      male           masculine
18 Jek Tono Porkins      180     110.0    NA      male           masculine
19 Yoda                   66      17.0 896.0      male           masculine
20 Palpatine             170      75.0  82.0      male           masculine
21 Boba Fett             183      78.2  31.5      male           masculine
22 IG-88                 200     140.0  15.0      none           masculine
23 Bossk                 190     113.0  53.0      male           masculine
24 Lando Calrissian      177      79.0  31.0      male           masculine
25 Lobot                 175      79.0  37.0      male           masculine
26 Ackbar                180      83.0  41.0      male           masculine
27 Mon Mothma            150        NA  48.0      female         feminine
28 Arvel Crynyd           NA        NA    NA      male           masculine
29 Wicket Systri Warrick  88      20.0   8.0      male           masculine
30 Nien Nunb             160      68.0    NA      male           masculine
⋮  ⋮                     ⋮      ⋮      ⋮          ⋮              ⋮
58 Cordé                 157       NA   NA        female         feminine
59 Cliegg Lars           183       NA   82        male           masculine
60 Poggle the Lesser     183     80.0   NA        male           masculine
61 Luminara Unduli       170     56.2   58        female         feminine
62 Barriss Offee         166     50.0   40        female         feminine
63 Dormé                 165       NA   NA        female         feminine
64 Dooku                 193     80.0  102        male           masculine
65 Bail Prestor Organa   191       NA   67        male           masculine
66 Jango Fett            183     79.0   66        male           masculine
67 Zam Wesell            168     55.0   NA        female         feminine
68 Dexter Jettster       198    102.0   NA        male           masculine
69 Lama Su               229     88.0   NA        male           masculine
70 Taun We               213       NA   NA        female         feminine
71 Jocasta Nu            167       NA   NA        female         feminine
72 Ratts Tyerell          79     15.0   NA        male           masculine
73 R4-P17                 96       NA   NA        none           feminine
74 Wat Tambor            193     48.0   NA        male           masculine
75 San Hill              191       NA   NA        male           masculine
76 Shaak Ti              178     57.0   NA        female         feminine
77 Grievous              216    159.0   NA        male           masculine
78 Tarfful               234    136.0   NA        male           masculine
79 Raymus Antilles       188     79.0   NA        male           masculine
80 Sly Moore             178     48.0   NA        NA             NA
81 Tion Medon            206     80.0   NA        male           masculine
82 Finn                   NA       NA   NA        male           masculine
83 Rey                    NA       NA   NA        female         feminine
84 Poe Dameron            NA       NA   NA        male           masculine
85 BB8                    NA       NA   NA        none           masculine
86 Captain Phasma         NA       NA   NA        NA             NA
87 Padmé Amidala         165     45.0   46        female         feminine
   homeworld    species
1  Tatooine     Human
2  Tatooine     Droid
3  Naboo        Droid
4  Tatooine     Human
5  Alderaan     Human
6  Tatooine     Human
7  Tatooine     Human
8  Tatooine     Droid
9  Tatooine     Human
10 Stewjon      Human
11 Tatooine     Human
12 Eriadu       Human
13 Kashyyyk     Wookiee
14 Corellia     Human
15 Rodia        Rodian
16 Nal Hutta    Hutt
17 Corellia     Human
18 Bestine IV   Human
19 NA           Yoda's species
20 Naboo        Human
21 Kamino       Human
22 NA           Droid
23 Trandosha    Trandoshan
24 Socorro      Human
25 Bespin       Human
26 Mon Cala     Mon Calamari
27 Chandrila    Human
28 NA           Human
29 Endor        Ewok
30 Sullust      Sullustan
⋮  ⋮            ⋮
58 Naboo        Human
59 Tatooine     Human
60 Geonosis     Geonosian
61 Mirial       Mirialan
62 Mirial       Mirialan
63 Naboo        Human
64 Serenno      Human
65 Alderaan     Human
66 Concord Dawn Human
67 Zolan        Clawdite
68 Ojom         Besalisk
69 Kamino       Kaminoan
70 Kamino       Kaminoan
71 Coruscant    Human
72 Aleen Minor  Aleena
73 NA           Droid
74 Skako        Skakoan
75 Muunilinst   Muun
76 Shili        Togruta
77 Kalee        Kaleesh
78 Kashyyyk     Wookiee
79 Alderaan     Human
80 Umbara       NA
81 Utapau       Pau'an
82 NA           Human
83 NA           Human
84 NA           Human
85 NA           Droid
86 NA           NA
87 Naboo        Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

In [14]:
# Select all columns ending with color
starwars |> select(ends_with("color"))

   hair_color    skin_color          eye_color
1  blond         fair                blue
2  NA            gold                yellow
3  NA            white, blue         red
4  none          white               yellow
5  brown         light               brown
6  brown, grey   light               blue
7  brown         light               blue
8  NA            white, red          red
9  black         light               brown
10 auburn, white fair                blue-gray
11 blond         fair                blue
12 auburn, grey  fair                blue
13 brown         unknown             blue
14 brown         fair                brown
15 NA            green               black
16 NA            green-tan, brown    orange
17 brown         fair                hazel
18 brown         fair                blue
19 white         green               brown
20 grey          pale                yellow
21 black         fair                brown
22 none          metal               red
23 none          green               red
24 black         dark                brown
25 none          light               blue
26 none          brown mottle        orange
27 auburn        fair                blue
28 brown         fair                brown
29 brown         brown               brown
30 none          grey                black
⋮  ⋮             ⋮                   ⋮
58 brown         light               brown
59 brown         fair                blue
60 none          green               yellow
61 black         yellow              blue
62 black         yellow              blue
63 brown         light               brown
64 white         fair                brown
65 black         tan                 brown
66 black         tan                 brown
67 blonde        fair, green, yellow yellow
68 none          brown               yellow
69 none          grey                black
70 none          grey                black
71 white         fair                blue
72 none          grey, blue          unknown
73 none          silver, red         red, blue
74 none          green, grey         unknown
75 none          grey                gold
76 none          red, blue, white    black
77 none          brown, white        green, yellow
78 brown         brown               blue
79 brown         light               brown
80 none          pale                white
81 none          grey                black
82 black         dark                dark
83 brown         light               hazel
84 brown         light               brown
85 none          none                black
86 unknown       unknown             unknown
87 brown         light               brown

<p>There are a number of helper functions you can use within <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, like <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with()</a></code>, <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">ends_with()</a></code>, <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">matches()</a></code> and <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">contains()</a></code>. These let you quickly match larger blocks of variables that meet some criterion. See <code><a href="https://dplyr.tidyverse.org/reference/select.html">?select</a></code> for more details.</p>

<p>You can rename variables with <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> by using named arguments:</p>

In [15]:
starwars |> select(home_world = homeworld)

   home_world
1  Tatooine
2  Tatooine
3  Naboo
4  Tatooine
5  Alderaan
6  Tatooine
7  Tatooine
8  Tatooine
9  Tatooine
10 Stewjon
11 Tatooine
12 Eriadu
13 Kashyyyk
14 Corellia
15 Rodia
16 Nal Hutta
17 Corellia
18 Bestine IV
19 NA
20 Naboo
21 Kamino
22 NA
23 Trandosha
24 Socorro
25 Bespin
26 Mon Cala
27 Chandrila
28 NA
29 Endor
30 Sullust
⋮  ⋮
58 Naboo
59 Tatooine
60 Geonosis
61 Mirial
62 Mirial
63 Naboo
64 Serenno
65 Alderaan
66 Concord Dawn
67 Zolan
68 Ojom
69 Kamino
70 Kamino
71 Coruscant
72 Aleen Minor
73 NA
74 Skako
75 Muunilinst
76 Shili
77 Kalee
78 Kashyyyk
79 Alderaan
80 Umbara
81 Utapau
82 NA
83 NA
84 NA
85 NA
86 NA
87 Naboo

<p>But because <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> drops all the variables not explicitly mentioned, it’s not that useful. Instead, use <code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename()</a></code>:</p>

In [16]:
starwars |> rename(home_world = homeworld)

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Cordé                 157       NA  brown         light
59 Cliegg Lars           183       NA  brown         fair
60 Poggle the Lesser     183     80.0  none          green
61 Luminara Unduli       170     56.2  black         yellow
62 Barriss Offee         166     50.0  black         yellow
63 Dormé                 165       NA  brown         light
64 Dooku                 193     80.0  white         fair
65 Bail Prestor Organa   191       NA  black         tan
66 Jango Fett            183     79.0  black         tan
67 Zam Wesell            168     55.0  blonde        fair, green, yellow
68 Dexter Jettster       198    102.0  none          brown
69 Lama Su               229     88.0  none          grey
70 Taun We               213       NA  none          grey
71 Jocasta Nu            167       NA  white         fair
72 Ratts Tyerell          79     15.0  none          grey, blue
73 R4-P17                 96       NA  none          silver, red
74 Wat Tambor            193     48.0  none          green, grey
75 San Hill              191       NA  none          grey
76 Shaak Ti              178     57.0  none          red, blue, white
77 Grievous              216    159.0  none          brown, white
78 Tarfful               234    136.0  brown         brown
79 Raymus Antilles       188     79.0  brown         light
80 Sly Moore             178     48.0  none          pale
81 Tion Medon            206     80.0  none          grey
82 Finn                   NA       NA  black         dark
83 Rey                    NA       NA  brown         light
84 Poe Dameron            NA       NA  brown         light
85 BB8                    NA       NA  none          none
86 Captain Phasma         NA       NA  unknown       unknown
87 Padmé Amidala         165     45.0  brown         light
   eye_color     birth_year sex            gender    home_world
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      male           masculine Bestine IV
19 brown         896.0      male           masculine NA
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine NA
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine NA
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 brown          NA        female         feminine  Naboo
59 blue           82        male           masculine Tatooine
60 yellow         NA        male           masculine Geonosis
61 blue           58        female         feminine  Mirial
62 blue           40        female         feminine  Mirial
63 brown          NA        female         feminine  Naboo
64 brown         102        male           masculine Serenno
65 brown          67        male           masculine Alderaan
66 brown          66        male           masculine Concord Dawn
67 yellow         NA        female         feminine  Zolan
68 yellow         NA        male           masculine Ojom
69 black          NA        male           masculine Kamino
70 black          NA        female         feminine  Kamino
71 blue           NA        female         feminine  Coruscant
72 unknown        NA        male           masculine Aleen Minor
73 red, blue      NA        none           feminine  NA
74 unknown        NA        male           masculine Skako
75 gold           NA        male           masculine Muunilinst
76 black          NA        female         feminine  Shili
77 green, yellow  NA        male           masculine Kalee
78 blue           NA        male           masculine Kashyyyk
79 brown          NA        male           masculine Alderaan
80 white          NA        NA             NA        Umbara
81 black          NA        male           masculine Utapau
82 dark           NA        male           masculine NA
83 hazel          NA        female         feminine  NA
84 brown          NA        male           masculine NA
85 black          NA        none           masculine NA
86 unknown        NA        NA             NA        NA
87 brown          46        female         feminine  Naboo
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 Human
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Human
59 Human
60 Geonosian
61 Mirialan
62 Mirialan
63 Human
64 Human
65 Human
66 Human
67 Clawdite
68 Besalisk
69 Kaminoan
70 Kaminoan
71 Human
72 Aleena
73 Droid
74 Skakoan
75 Muun
76 Togruta
77 Kaleesh
78 Wookiee
79 Human
80 NA
81 Pau'an
82 Human
83 Human
84 Human
85 Droid
86 NA
87 Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

## <h3 id="add-new-columns-with-mutate">Add new columns with <code>mutate()</code></h3>

<p>Besides selecting sets of existing columns, it’s often useful to add new columns that are functions of existing columns. This is the job of
<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>:</p>

In [17]:
starwars |> mutate(height_m = height / 100)

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Cordé                 157       NA  brown         light
59 Cliegg Lars           183       NA  brown         fair
60 Poggle the Lesser     183     80.0  none          green
61 Luminara Unduli       170     56.2  black         yellow
62 Barriss Offee         166     50.0  black         yellow
63 Dormé                 165       NA  brown         light
64 Dooku                 193     80.0  white         fair
65 Bail Prestor Organa   191       NA  black         tan
66 Jango Fett            183     79.0  black         tan
67 Zam Wesell            168     55.0  blonde        fair, green, yellow
68 Dexter Jettster       198    102.0  none          brown
69 Lama Su               229     88.0  none          grey
70 Taun We               213       NA  none          grey
71 Jocasta Nu            167       NA  white         fair
72 Ratts Tyerell          79     15.0  none          grey, blue
73 R4-P17                 96       NA  none          silver, red
74 Wat Tambor            193     48.0  none          green, grey
75 San Hill              191       NA  none          grey
76 Shaak Ti              178     57.0  none          red, blue, white
77 Grievous              216    159.0  none          brown, white
78 Tarfful               234    136.0  brown         brown
79 Raymus Antilles       188     79.0  brown         light
80 Sly Moore             178     48.0  none          pale
81 Tion Medon            206     80.0  none          grey
82 Finn                   NA       NA  black         dark
83 Rey                    NA       NA  brown         light
84 Poe Dameron            NA       NA  brown         light
85 BB8                    NA       NA  none          none
86 Captain Phasma         NA       NA  unknown       unknown
87 Padmé Amidala         165     45.0  brown         light
   eye_color     birth_year sex            gender    homeworld
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      male           masculine Bestine IV
19 brown         896.0      male           masculine NA
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine NA
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine NA
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 brown          NA        female         feminine  Naboo
59 blue           82        male           masculine Tatooine
60 yellow         NA        male           masculine Geonosis
61 blue           58        female         feminine  Mirial
62 blue           40        female         feminine  Mirial
63 brown          NA        female         feminine  Naboo
64 brown         102        male           masculine Serenno
65 brown          67        male           masculine Alderaan
66 brown          66        male           masculine Concord Dawn
67 yellow         NA        female         feminine  Zolan
68 yellow         NA        male           masculine Ojom
69 black          NA        male           masculine Kamino
70 black          NA        female         feminine  Kamino
71 blue           NA        female         feminine  Coruscant
72 unknown        NA        male           masculine Aleen Minor
73 red, blue      NA        none           feminine  NA
74 unknown        NA        male           masculine Skako
75 gold           NA        male           masculine Muunilinst
76 black          NA        female         feminine  Shili
77 green, yellow  NA        male           masculine Kalee
78 blue           NA        male           masculine Kashyyyk
79 brown          NA        male           masculine Alderaan
80 white          NA        NA             NA        Umbara
81 black          NA        male           masculine Utapau
82 dark           NA        male           masculine NA
83 hazel          NA        female         feminine  NA
84 brown          NA        male           masculine NA
85 black          NA        none           masculine NA
86 unknown        NA        NA             NA        NA
87 brown          46        female         feminine  Naboo
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 Human
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Human
59 Human
60 Geonosian
61 Mirialan
62 Mirialan
63 Human
64 Human
65 Human
66 Human
67 Clawdite
68 Besalisk
69 Kaminoan
70 Kaminoan
71 Human
72 Aleena
73 Droid
74 Skakoan
75 Muun
76 Togruta
77 Kaleesh
78 Wookiee
79 Human
80 NA
81 Pau'an
82 Human
83 Human
84 Human
85 Droid
86 NA
87 Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter
   height_m
1  1.72
2  1.67
3  0.96
4  2.02
5  1.50
6  1.78
7  1.65
8  0.97
9  1.83
10 1.82
11 1.88
12 1.80
13 2.28
14 1.80
15 1.73
16 1.75
17 1.70
18 1.80
19 0.66
20 1.70
21 1.83
22 2.00
23 1.90
24 1.77
25 1.75
26 1.80
27 1.50
28   NA
29 0.88
30 1.60
⋮  ⋮
58 1.57
59 1.83
60 1.83
61 1.70
62 1.66
63 1.65
64 1.93
65 1.91
66 1.83
67 1.68
68 1.98
69 2.29
70 2.13
71 1.67
72 0.79
73 0.96
74 1.93
75 1.91
76 1.78
77 2.16
78 2.34
79 1.88
80 1.78
81 2.06
82   NA
83   NA
84   NA
85   NA
86   NA
87 1.65

<p>We can’t see the height in meters we just calculated, but we can fix that using a select command.</p>

In [18]:
starwars |>
  mutate(height_m = height / 100) |>
  select(height_m, height, everything())

   height_m height name                  mass   hair_color
1  1.72     172    Luke Skywalker          77.0 blond
2  1.67     167    C-3PO                   75.0 NA
3  0.96      96    R2-D2                   32.0 NA
4  2.02     202    Darth Vader            136.0 none
5  1.50     150    Leia Organa             49.0 brown
6  1.78     178    Owen Lars              120.0 brown, grey
7  1.65     165    Beru Whitesun lars      75.0 brown
8  0.97      97    R5-D4                   32.0 NA
9  1.83     183    Biggs Darklighter       84.0 black
10 1.82     182    Obi-Wan Kenobi          77.0 auburn, white
11 1.88     188    Anakin Skywalker        84.0 blond
12 1.80     180    Wilhuff Tarkin            NA auburn, grey
13 2.28     228    Chewbacca              112.0 brown
14 1.80     180    Han Solo                80.0 brown
15 1.73     173    Greedo                  74.0 NA
16 1.75     175    Jabba Desilijic Tiure 1358.0 NA
17 1.70     170    Wedge Antilles          77.0 brown
18 1.80     180    Jek Tono Porkins       110.0 brown
19 0.66      66    Yoda                    17.0 white
20 1.70     170    Palpatine               75.0 grey
21 1.83     183    Boba Fett               78.2 black
22 2.00     200    IG-88                  140.0 none
23 1.90     190    Bossk                  113.0 none
24 1.77     177    Lando Calrissian        79.0 black
25 1.75     175    Lobot                   79.0 none
26 1.80     180    Ackbar                  83.0 none
27 1.50     150    Mon Mothma                NA auburn
28   NA      NA    Arvel Crynyd              NA brown
29 0.88      88    Wicket Systri Warrick   20.0 brown
30 1.60     160    Nien Nunb               68.0 none
⋮  ⋮        ⋮      ⋮                     ⋮      ⋮
58 1.57     157    Cordé                    NA  brown
59 1.83     183    Cliegg Lars              NA  brown
60 1.83     183    Poggle the Lesser      80.0  none
61 1.70     170    Luminara Unduli        56.2  black
62 1.66     166    Barriss Offee          50.0  black
63 1.65     165    Dormé                    NA  brown
64 1.93     193    Dooku                  80.0  white
65 1.91     191    Bail Prestor Organa      NA  black
66 1.83     183    Jango Fett             79.0  black
67 1.68     168    Zam Wesell             55.0  blonde
68 1.98     198    Dexter Jettster       102.0  none
69 2.29     229    Lama Su                88.0  none
70 2.13     213    Taun We                  NA  none
71 1.67     167    Jocasta Nu               NA  white
72 0.79      79    Ratts Tyerell          15.0  none
73 0.96      96    R4-P17                   NA  none
74 1.93     193    Wat Tambor             48.0  none
75 1.91     191    San Hill                 NA  none
76 1.78     178    Shaak Ti               57.0  none
77 2.16     216    Grievous              159.0  none
78 2.34     234    Tarfful               136.0  brown
79 1.88     188    Raymus Antilles        79.0  brown
80 1.78     178    Sly Moore              48.0  none
81 2.06     206    Tion Medon             80.0  none
82   NA      NA    Finn                     NA  black
83   NA      NA    Rey                      NA  brown
84   NA      NA    Poe Dameron              NA  brown
85   NA      NA    BB8                      NA  none
86   NA      NA    Captain Phasma           NA  unknown
87 1.65     165    Padmé Amidala          45.0  brown
   skin_color          eye_color     birth_year sex            gender
1  fair                blue           19.0      male           masculine
2  gold                yellow        112.0      none           masculine
3  white, blue         red            33.0      none           masculine
4  white               yellow         41.9      male           masculine
5  light               brown          19.0      female         feminine
6  light               blue           52.0      male           masculine
7  light               blue           47.0      female         feminine
8  white, red          red              NA      none           masculine
9  light               brown          24.0      male           masculine
10 fair                blue-gray      57.0      male           masculine
11 fair                blue           41.9      male           masculine
12 fair                blue           64.0      male           masculine
13 unknown             blue          200.0      male           masculine
14 fair                brown          29.0      male           masculine
15 green               black          44.0      male           masculine
16 green-tan, brown    orange        600.0      hermaphroditic masculine
17 fair                hazel          21.0      male           masculine
18 fair                blue             NA      male           masculine
19 green               brown         896.0      male           masculine
20 pale                yellow         82.0      male           masculine
21 fair                brown          31.5      male           masculine
22 metal               red            15.0      none           masculine
23 green               red            53.0      male           masculine
24 dark                brown          31.0      male           masculine
25 light               blue           37.0      male           masculine
26 brown mottle        orange         41.0      male           masculine
27 fair                blue           48.0      female         feminine
28 fair                brown            NA      male           masculine
29 brown               brown           8.0      male           masculine
30 grey                black            NA      male           masculine
⋮  ⋮                   ⋮             ⋮          ⋮              ⋮
58 light               brown          NA        female         feminine
59 fair                blue           82        male           masculine
60 green               yellow         NA        male           masculine
61 yellow              blue           58        female         feminine
62 yellow              blue           40        female         feminine
63 light               brown          NA        female         feminine
64 fair                brown         102        male           masculine
65 tan                 brown          67        male           masculine
66 tan                 brown          66        male           masculine
67 fair, green, yellow yellow         NA        female         feminine
68 brown               yellow         NA        male           masculine
69 grey                black          NA        male           masculine
70 grey                black          NA        female         feminine
71 fair                blue           NA        female         feminine
72 grey, blue          unknown        NA        male           masculine
73 silver, red         red, blue      NA        none           feminine
74 green, grey         unknown        NA        male           masculine
75 grey                gold           NA        male           masculine
76 red, blue, white    black          NA        female         feminine
77 brown, white        green, yellow  NA        male           masculine
78 brown               blue           NA        male           masculine
79 light               brown          NA        male           masculine
80 pale                white          NA        NA             NA
81 grey                black          NA        male           masculine
82 dark                dark           NA        male           masculine
83 light               hazel          NA        female         feminine
84 light               brown          NA        male           masculine
85 none                black          NA        none           masculine
86 unknown             unknown        NA        NA             NA
87 light               brown          46        female         feminine
   homeworld    species
1  Tatooine     Human
2  Tatooine     Droid
3  Naboo        Droid
4  Tatooine     Human
5  Alderaan     Human
6  Tatooine     Human
7  Tatooine     Human
8  Tatooine     Droid
9  Tatooine     Human
10 Stewjon      Human
11 Tatooine     Human
12 Eriadu       Human
13 Kashyyyk     Wookiee
14 Corellia     Human
15 Rodia        Rodian
16 Nal Hutta    Hutt
17 Corellia     Human
18 Bestine IV   Human
19 NA           Yoda's species
20 Naboo        Human
21 Kamino       Human
22 NA           Droid
23 Trandosha    Trandoshan
24 Socorro      Human
25 Bespin       Human
26 Mon Cala     Mon Calamari
27 Chandrila    Human
28 NA           Human
29 Endor        Ewok
30 Sullust      Sullustan
⋮  ⋮            ⋮
58 Naboo        Human
59 Tatooine     Human
60 Geonosis     Geonosian
61 Mirial       Mirialan
62 Mirial       Mirialan
63 Naboo        Human
64 Serenno      Human
65 Alderaan     Human
66 Concord Dawn Human
67 Zolan        Clawdite
68 Ojom         Besalisk
69 Kamino       Kaminoan
70 Kamino       Kaminoan
71 Coruscant    Human
72 Aleen Minor  Aleena
73 NA           Droid
74 Skako        Skakoan
75 Muunilinst   Muun
76 Shili        Togruta
77 Kalee        Kaleesh
78 Kashyyyk     Wookiee
79 Alderaan     Human
80 Umbara       NA
81 Utapau       Pau'an
82 NA           Human
83 NA           Human
84 NA           Human
85 NA           Droid
86 NA           NA
87 Naboo        Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

<p><code><a href="https://dplyr.tidyverse.org/reference/mutate.html">dplyr::mutate()</a></code> is similar to the base <code><a href="https://rdrr.io/r/base/transform.html">transform()</a></code>, but allows you to refer to columns that you’ve just created:</p>

In [19]:
starwars |>
  mutate(
    height_m = height / 100,
    BMI = mass / (height_m^2)
  ) |>
  select(everything())

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Cordé                 157       NA  brown         light
59 Cliegg Lars           183       NA  brown         fair
60 Poggle the Lesser     183     80.0  none          green
61 Luminara Unduli       170     56.2  black         yellow
62 Barriss Offee         166     50.0  black         yellow
63 Dormé                 165       NA  brown         light
64 Dooku                 193     80.0  white         fair
65 Bail Prestor Organa   191       NA  black         tan
66 Jango Fett            183     79.0  black         tan
67 Zam Wesell            168     55.0  blonde        fair, green, yellow
68 Dexter Jettster       198    102.0  none          brown
69 Lama Su               229     88.0  none          grey
70 Taun We               213       NA  none          grey
71 Jocasta Nu            167       NA  white         fair
72 Ratts Tyerell          79     15.0  none          grey, blue
73 R4-P17                 96       NA  none          silver, red
74 Wat Tambor            193     48.0  none          green, grey
75 San Hill              191       NA  none          grey
76 Shaak Ti              178     57.0  none          red, blue, white
77 Grievous              216    159.0  none          brown, white
78 Tarfful               234    136.0  brown         brown
79 Raymus Antilles       188     79.0  brown         light
80 Sly Moore             178     48.0  none          pale
81 Tion Medon            206     80.0  none          grey
82 Finn                   NA       NA  black         dark
83 Rey                    NA       NA  brown         light
84 Poe Dameron            NA       NA  brown         light
85 BB8                    NA       NA  none          none
86 Captain Phasma         NA       NA  unknown       unknown
87 Padmé Amidala         165     45.0  brown         light
   eye_color     birth_year sex            gender    homeworld
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      male           masculine Bestine IV
19 brown         896.0      male           masculine NA
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine NA
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine NA
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 brown          NA        female         feminine  Naboo
59 blue           82        male           masculine Tatooine
60 yellow         NA        male           masculine Geonosis
61 blue           58        female         feminine  Mirial
62 blue           40        female         feminine  Mirial
63 brown          NA        female         feminine  Naboo
64 brown         102        male           masculine Serenno
65 brown          67        male           masculine Alderaan
66 brown          66        male           masculine Concord Dawn
67 yellow         NA        female         feminine  Zolan
68 yellow         NA        male           masculine Ojom
69 black          NA        male           masculine Kamino
70 black          NA        female         feminine  Kamino
71 blue           NA        female         feminine  Coruscant
72 unknown        NA        male           masculine Aleen Minor
73 red, blue      NA        none           feminine  NA
74 unknown        NA        male           masculine Skako
75 gold           NA        male           masculine Muunilinst
76 black          NA        female         feminine  Shili
77 green, yellow  NA        male           masculine Kalee
78 blue           NA        male           masculine Kashyyyk
79 brown          NA        male           masculine Alderaan
80 white          NA        NA             NA        Umbara
81 black          NA        male           masculine Utapau
82 dark           NA        male           masculine NA
83 hazel          NA        female         feminine  NA
84 brown          NA        male           masculine NA
85 black          NA        none           masculine NA
86 unknown        NA        NA             NA        NA
87 brown          46        female         feminine  Naboo
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 Human
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Human
59 Human
60 Geonosian
61 Mirialan
62 Mirialan
63 Human
64 Human
65 Human
66 Human
67 Clawdite
68 Besalisk
69 Kaminoan
70 Kaminoan
71 Human
72 Aleena
73 Droid
74 Skakoan
75 Muun
76 Togruta
77 Kaleesh
78 Wookiee
79 Human
80 NA
81 Pau'an
82 Human
83 Human
84 Human
85 Droid
86 NA
87 Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter
   height_m BMI
1  1.72      26.02758
2  1.67      26.89232
3  0.96      34.72222
4  2.02      33.33007
5  1.50      21.77778
6  1.78      37.87401
7  1.65      27.54821
8  0.97      34.00999
9  1.83      25.08286
10 1.82      23.24598
11 1.88      23.76641
12 1.80            NA
13 2.28      21.54509
14 1.80      24.69136
15 1.73      24.72518
16 1.75     443.42857
17 1.70      26.64360
18 1.80      33.95062
19 0.66      39.02663
20 1.70      25.95156
21 1.83      23.35095
22 2.00      35.00000
23 1.90      31.30194
24 1.77      25.21625
25 1.75      25.79592
26 1.80      25.61728
27 1.50            NA
28   NA            NA
29 0.88      25.82645
30 1.60      26.56250
⋮  ⋮        ⋮
58 1.57           NA
59 1.83           NA
60 1.83     23.88844
61 1.70     19.44637
62 1.66     18.14487
63 1.65           NA
64 1.93     21.47709
65 1.91           NA
66 1.83     23.58984
67 1.68     19.48696
68 1.98     26.01775
69 2.29     16.78076
70 2.13           NA
71 1.67           NA
72 0.79     24.03461
73 0.96           NA
74 1.93     12.88625
75 1.91           NA
76 1.78     17.99015
77 2.16     34.07922
78 2.34     24.83746
79 1.88     22.35174
80 1.78     15.14960
81 2.06     18.85192
82   NA           NA
83   NA           NA
84   NA           NA
85   NA           NA
86   NA           NA
87 1.65     16.52893

<p>If you only want to keep the new variables, use <code>.keep = "none"</code>:</p>

In [20]:
starwars |>
  mutate(
    height_m = height / 100,
    BMI = mass / (height_m^2),
    .keep = "none"
  )

   height_m BMI
1  1.72      26.02758
2  1.67      26.89232
3  0.96      34.72222
4  2.02      33.33007
5  1.50      21.77778
6  1.78      37.87401
7  1.65      27.54821
8  0.97      34.00999
9  1.83      25.08286
10 1.82      23.24598
11 1.88      23.76641
12 1.80            NA
13 2.28      21.54509
14 1.80      24.69136
15 1.73      24.72518
16 1.75     443.42857
17 1.70      26.64360
18 1.80      33.95062
19 0.66      39.02663
20 1.70      25.95156
21 1.83      23.35095
22 2.00      35.00000
23 1.90      31.30194
24 1.77      25.21625
25 1.75      25.79592
26 1.80      25.61728
27 1.50            NA
28   NA            NA
29 0.88      25.82645
30 1.60      26.56250
⋮  ⋮        ⋮
58 1.57           NA
59 1.83           NA
60 1.83     23.88844
61 1.70     19.44637
62 1.66     18.14487
63 1.65           NA
64 1.93     21.47709
65 1.91           NA
66 1.83     23.58984
67 1.68     19.48696
68 1.98     26.01775
69 2.29     16.78076
70 2.13           NA
71 1.67           NA
72 0.79     24.03461
73 0.96           NA
74 1.93     12.88625
75 1.91           NA
76 1.78     17.99015
77 2.16     34.07922
78 2.34     24.83746
79 1.88     22.35174
80 1.78     15.14960
81 2.06     18.85192
82   NA           NA
83   NA           NA
84   NA           NA
85   NA           NA
86   NA           NA
87 1.65     16.52893

## <h3 id="change-column-order-with-relocate">Change column order with <code>relocate()</code></h3>

<p>Use a similar syntax as <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> to move blocks of columns at once</p>

In [21]:
starwars |> relocate(sex:homeworld, .before = height)

   name                  sex            gender    homeworld    height mass
1  Luke Skywalker        male           masculine Tatooine     172      77.0
2  C-3PO                 none           masculine Tatooine     167      75.0
3  R2-D2                 none           masculine Naboo         96      32.0
4  Darth Vader           male           masculine Tatooine     202     136.0
5  Leia Organa           female         feminine  Alderaan     150      49.0
6  Owen Lars             male           masculine Tatooine     178     120.0
7  Beru Whitesun lars    female         feminine  Tatooine     165      75.0
8  R5-D4                 none           masculine Tatooine      97      32.0
9  Biggs Darklighter     male           masculine Tatooine     183      84.0
10 Obi-Wan Kenobi        male           masculine Stewjon      182      77.0
11 Anakin Skywalker      male           masculine Tatooine     188      84.0
12 Wilhuff Tarkin        male           masculine Eriadu       180        NA
13 Chewbacca             male           masculine Kashyyyk     228     112.0
14 Han Solo              male           masculine Corellia     180      80.0
15 Greedo                male           masculine Rodia        173      74.0
16 Jabba Desilijic Tiure hermaphroditic masculine Nal Hutta    175    1358.0
17 Wedge Antilles        male           masculine Corellia     170      77.0
18 Jek Tono Porkins      male           masculine Bestine IV   180     110.0
19 Yoda                  male           masculine NA            66      17.0
20 Palpatine             male           masculine Naboo        170      75.0
21 Boba Fett             male           masculine Kamino       183      78.2
22 IG-88                 none           masculine NA           200     140.0
23 Bossk                 male           masculine Trandosha    190     113.0
24 Lando Calrissian      male           masculine Socorro      177      79.0
25 Lobot                 male           masculine Bespin       175      79.0
26 Ackbar                male           masculine Mon Cala     180      83.0
27 Mon Mothma            female         feminine  Chandrila    150        NA
28 Arvel Crynyd          male           masculine NA            NA        NA
29 Wicket Systri Warrick male           masculine Endor         88      20.0
30 Nien Nunb             male           masculine Sullust      160      68.0
⋮  ⋮                     ⋮              ⋮         ⋮            ⋮      ⋮
58 Cordé                 female         feminine  Naboo        157       NA
59 Cliegg Lars           male           masculine Tatooine     183       NA
60 Poggle the Lesser     male           masculine Geonosis     183     80.0
61 Luminara Unduli       female         feminine  Mirial       170     56.2
62 Barriss Offee         female         feminine  Mirial       166     50.0
63 Dormé                 female         feminine  Naboo        165       NA
64 Dooku                 male           masculine Serenno      193     80.0
65 Bail Prestor Organa   male           masculine Alderaan     191       NA
66 Jango Fett            male           masculine Concord Dawn 183     79.0
67 Zam Wesell            female         feminine  Zolan        168     55.0
68 Dexter Jettster       male           masculine Ojom         198    102.0
69 Lama Su               male           masculine Kamino       229     88.0
70 Taun We               female         feminine  Kamino       213       NA
71 Jocasta Nu            female         feminine  Coruscant    167       NA
72 Ratts Tyerell         male           masculine Aleen Minor   79     15.0
73 R4-P17                none           feminine  NA            96       NA
74 Wat Tambor            male           masculine Skako        193     48.0
75 San Hill              male           masculine Muunilinst   191       NA
76 Shaak Ti              female         feminine  Shili        178     57.0
77 Grievous              male           masculine Kalee        216    159.0
78 Tarfful               male           masculine Kashyyyk     234    136.0
79 Raymus Antilles       male           masculine Alderaan     188     79.0
80 Sly Moore             NA             NA        Umbara       178     48.0
81 Tion Medon            male           masculine Utapau       206     80.0
82 Finn                  male           masculine NA            NA       NA
83 Rey                   female         feminine  NA            NA       NA
84 Poe Dameron           male           masculine NA            NA       NA
85 BB8                   none           masculine NA            NA       NA
86 Captain Phasma        NA             NA        NA            NA       NA
87 Padmé Amidala         female         feminine  Naboo        165     45.0
   hair_color    skin_color          eye_color     birth_year species
1  blond         fair                blue           19.0      Human
2  NA            gold                yellow        112.0      Droid
3  NA            white, blue         red            33.0      Droid
4  none          white               yellow         41.9      Human
5  brown         light               brown          19.0      Human
6  brown, grey   light               blue           52.0      Human
7  brown         light               blue           47.0      Human
8  NA            white, red          red              NA      Droid
9  black         light               brown          24.0      Human
10 auburn, white fair                blue-gray      57.0      Human
11 blond         fair                blue           41.9      Human
12 auburn, grey  fair                blue           64.0      Human
13 brown         unknown             blue          200.0      Wookiee
14 brown         fair                brown          29.0      Human
15 NA            green               black          44.0      Rodian
16 NA            green-tan, brown    orange        600.0      Hutt
17 brown         fair                hazel          21.0      Human
18 brown         fair                blue             NA      Human
19 white         green               brown         896.0      Yoda's species
20 grey          pale                yellow         82.0      Human
21 black         fair                brown          31.5      Human
22 none          metal               red            15.0      Droid
23 none          green               red            53.0      Trandoshan
24 black         dark                brown          31.0      Human
25 none          light               blue           37.0      Human
26 none          brown mottle        orange         41.0      Mon Calamari
27 auburn        fair                blue           48.0      Human
28 brown         fair                brown            NA      Human
29 brown         brown               brown           8.0      Ewok
30 none          grey                black            NA      Sullustan
⋮  ⋮             ⋮                   ⋮             ⋮          ⋮
58 brown         light               brown          NA        Human
59 brown         fair                blue           82        Human
60 none          green               yellow         NA        Geonosian
61 black         yellow              blue           58        Mirialan
62 black         yellow              blue           40        Mirialan
63 brown         light               brown          NA        Human
64 white         fair                brown         102        Human
65 black         tan                 brown          67        Human
66 black         tan                 brown          66        Human
67 blonde        fair, green, yellow yellow         NA        Clawdite
68 none          brown               yellow         NA        Besalisk
69 none          grey                black          NA        Kaminoan
70 none          grey                black          NA        Kaminoan
71 white         fair                blue           NA        Human
72 none          grey, blue          unknown        NA        Aleena
73 none          silver, red         red, blue      NA        Droid
74 none          green, grey         unknown        NA        Skakoan
75 none          grey                gold           NA        Muun
76 none          red, blue, white    black          NA        Togruta
77 none          brown, white        green, yellow  NA        Kaleesh
78 brown         brown               blue           NA        Wookiee
79 brown         light               brown          NA        Human
80 none          pale                white          NA        NA
81 none          grey                black          NA        Pau'an
82 black         dark                dark           NA        Human
83 brown         light               hazel          NA        Human
84 brown         light               brown          NA        Human
85 none          none                black          NA        Droid
86 unknown       unknown             unknown        NA        NA
87 brown         light               brown          46        Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

## <h3 id="summarise-values-with-summarise">Summarise values with <code>summarise()</code></h3>

<p>The last verb is <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>. It collapses a data frame to a single row.</p>

In [22]:
starwars |> summarise(height = mean(height, na.rm = TRUE))

  height
1 174.358

<p>It’s not that useful until we learn the <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> verb below.</p>

## <h3 id="commonalities">Commonalities</h3>

<p>You may have noticed that the syntax and function of all these verbs are very similar:</p>

<ul>
<li><p>The first argument is a data frame.</p></li>
<li><p>The subsequent arguments describe what to do with the data frame. You can refer to columns in the data frame directly without using <code>$</code>.</p></li>
<li><p>The result is a new data frame</p></li>
</ul>

<p>Together these properties make it easy to chain together multiple simple steps to achieve a complex result.</p>

<p>These five functions provide the basis of a language of data manipulation. At the most basic level, you can only alter a tidy data frame in five useful ways: you can reorder the rows (<code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code>), pick observations and variables of interest (<code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>), add new variables that are functions of existing variables (<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>), or collapse many values to a summary (<code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>).</p>

## <h2 id="combining-functions-with">Combining functions with <code>%&gt;%</code></h2>

<p>The dplyr API is functional in the sense that function calls don’t have side-effects. You must always save their results. This doesn’t lead
to particularly elegant code, especially if you want to do many operations at once. You either have to do it step-by-step:</p>

<pre><code>a1 <- <a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a>(starwars, species, sex)
a2 <- <a href="https://dplyr.tidyverse.org/reference/select.html">select</a>(a1, height, mass)
a3 <- <a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a>(a2,
  height = <a href="https://rdrr.io/r/base/mean.html">mean</a>(height, na.rm = TRUE),
  mass = <a href="https://rdrr.io/r/base/mean.html">mean</a>(mass, na.rm = TRUE)
)</code></pre>

<p>Or if you don’t want to name the intermediate results, you need to wrap the function calls inside each other:</p>

In [23]:
summarise(
  select(
    group_by(starwars, species, sex),
    height, mass
  ),
  height = mean(height, na.rm = TRUE),
  mass = mean(mass, na.rm = TRUE)
)

Adding missing grouping variables: `species`, `sex`
`summarise()` has grouped output by 'species'. You can override using the `.groups` argument.

   species        sex            height   mass
1  Aleena         male            79.0000   15.00000
2  Besalisk       male           198.0000  102.00000
3  Cerean         male           198.0000   82.00000
4  Chagrian       male           196.0000        NaN
5  Clawdite       female         168.0000   55.00000
6  Droid          none           131.2000   69.75000
7  Dug            male           112.0000   40.00000
8  Ewok           male            88.0000   20.00000
9  Geonosian      male           183.0000   80.00000
10 Gungan         male           208.6667   74.00000
11 Human          female         160.2500   56.33333
12 Human          male           182.3478   86.95789
13 Hutt           hermaphroditic 175.0000 1358.00000
14 Iktotchi       male           188.0000        NaN
15 Kaleesh        male           216.0000  159.00000
16 Kaminoan       female         213.0000        NaN
17 Kaminoan       male           229.0000   88.00000
18 Kel Dor        male           188.0000   80.00000
19 Mirialan       female         168.0000   53.10000
20 Mon Calamari   male           180.0000   83.00000
21 Muun           male           191.0000        NaN
22 Nautolan       male           196.0000   87.00000
23 Neimodian      male           191.0000   90.00000
24 Pau'an         male           206.0000   80.00000
25 Quermian       male           264.0000        NaN
26 Rodian         male           173.0000   74.00000
27 Skakoan        male           193.0000   48.00000
28 Sullustan      male           160.0000   68.00000
29 Tholothian     female         184.0000   50.00000
30 Togruta        female         178.0000   57.00000
31 Toong          male           163.0000   65.00000
32 Toydarian      male           137.0000        NaN
33 Trandoshan     male           190.0000  113.00000
34 Twi'lek        female         178.0000   55.00000
35 Twi'lek        male           180.0000        NaN
36 Vulptereen     male            94.0000   45.00000
37 Wookiee        male           231.0000  124.00000
38 Xexto          male           122.0000        NaN
39 Yoda's species male            66.0000   17.00000
40 Zabrak         male           173.0000   80.00000
41 NA             NA             181.3333   48.00000

<p>This is difficult to read because the order of the operations is from inside to out. Thus, the arguments are a long way away from the
function. To get around this problem, dplyr provides the <code>%&gt;%</code> operator from magrittr. <code>x %&gt;% f(y)</code> turns into <code>f(x, y)</code> so you can use it to rewrite multiple operations that you can read left-to-right, top-to-bottom (reading the pipe operator as “then”):</p>

<pre><code>starwars <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a>
  <a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a>(<species, sex) <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a>
  <a href="https://dplyr.tidyverse.org/reference/select.html">select</a>(height, mass) <a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a>
  <a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a>(
    height = <a href="https://rdrr.io/r/base/mean.html">mean</a>(height, na.rm = TRUE),
    mass = <a href="https://rdrr.io/r/base/mean.html">mean</a>(mass, na.rm = TRUE)
  )</code></pre>

# <h2 id="patterns-of-operations">Patterns of operations</h2>

<p>The dplyr verbs can be classified by the type of operations they accomplish (we sometimes speak of their <strong>semantics</strong>, i.e., their meaning). It’s helpful to have a good grasp of the difference between select and mutate operations.</p>

## <h3 id="selecting-operations">Selecting operations</h3>

<p>One of the appealing features of dplyr is that you can refer to columns from the tibble as if they were regular variables. However, the syntactic uniformity of referring to bare column names hides semantical differences across the verbs. A column symbol supplied to <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> does not have the same meaning as the same symbol supplied to <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>.</p>

<p>Selecting operations expect column names and positions. Hence, when you call <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> with bare variable names, they actually represent their own positions in the tibble. The following calls are completely equivalent from dplyr’s point of view:</p>

In [24]:
# `name` represents the integer 1
select(starwars, name)

   name
1  Luke Skywalker
2  C-3PO
3  R2-D2
4  Darth Vader
5  Leia Organa
6  Owen Lars
7  Beru Whitesun lars
8  R5-D4
9  Biggs Darklighter
10 Obi-Wan Kenobi
11 Anakin Skywalker
12 Wilhuff Tarkin
13 Chewbacca
14 Han Solo
15 Greedo
16 Jabba Desilijic Tiure
17 Wedge Antilles
18 Jek Tono Porkins
19 Yoda
20 Palpatine
21 Boba Fett
22 IG-88
23 Bossk
24 Lando Calrissian
25 Lobot
26 Ackbar
27 Mon Mothma
28 Arvel Crynyd
29 Wicket Systri Warrick
30 Nien Nunb
⋮  ⋮
58 Cordé
59 Cliegg Lars
60 Poggle the Lesser
61 Luminara Unduli
62 Barriss Offee
63 Dormé
64 Dooku
65 Bail Prestor Organa
66 Jango Fett
67 Zam Wesell
68 Dexter Jettster
69 Lama Su
70 Taun We
71 Jocasta Nu
72 Ratts Tyerell
73 R4-P17
74 Wat Tambor
75 San Hill
76 Shaak Ti
77 Grievous
78 Tarfful
79 Raymus Antilles
80 Sly Moore
81 Tion Medon
82 Finn
83 Rey
84 Poe Dameron
85 BB8
86 Captain Phasma
87 Padmé Amidala

In [25]:
select(starwars, 1)

   name
1  Luke Skywalker
2  C-3PO
3  R2-D2
4  Darth Vader
5  Leia Organa
6  Owen Lars
7  Beru Whitesun lars
8  R5-D4
9  Biggs Darklighter
10 Obi-Wan Kenobi
11 Anakin Skywalker
12 Wilhuff Tarkin
13 Chewbacca
14 Han Solo
15 Greedo
16 Jabba Desilijic Tiure
17 Wedge Antilles
18 Jek Tono Porkins
19 Yoda
20 Palpatine
21 Boba Fett
22 IG-88
23 Bossk
24 Lando Calrissian
25 Lobot
26 Ackbar
27 Mon Mothma
28 Arvel Crynyd
29 Wicket Systri Warrick
30 Nien Nunb
⋮  ⋮
58 Cordé
59 Cliegg Lars
60 Poggle the Lesser
61 Luminara Unduli
62 Barriss Offee
63 Dormé
64 Dooku
65 Bail Prestor Organa
66 Jango Fett
67 Zam Wesell
68 Dexter Jettster
69 Lama Su
70 Taun We
71 Jocasta Nu
72 Ratts Tyerell
73 R4-P17
74 Wat Tambor
75 San Hill
76 Shaak Ti
77 Grievous
78 Tarfful
79 Raymus Antilles
80 Sly Moore
81 Tion Medon
82 Finn
83 Rey
84 Poe Dameron
85 BB8
86 Captain Phasma
87 Padmé Amidala

<p>By the same token, this means that you cannot refer to variables from the surrounding context if they have the same name as one of the columns. In the following example, <code>height</code> still represents 2, not 5:</p>

In [26]:
height <- 5
select(starwars, height)

   height
1  172
2  167
3   96
4  202
5  150
6  178
7  165
8   97
9  183
10 182
11 188
12 180
13 228
14 180
15 173
16 175
17 170
18 180
19  66
20 170
21 183
22 200
23 190
24 177
25 175
26 180
27 150
28  NA
29  88
30 160
⋮  ⋮
58 157
59 183
60 183
61 170
62 166
63 165
64 193
65 191
66 183
67 168
68 198
69 229
70 213
71 167
72  79
73  96
74 193
75 191
76 178
77 216
78 234
79 188
80 178
81 206
82  NA
83  NA
84  NA
85  NA
86  NA
87 165

<p>One useful subtlety is that this only applies to bare names and to selecting calls like <code>c(height, mass)</code> or <code>height:mass</code>. In all other cases, the columns of the data frame are not put in scope. This allows you to refer to contextual variables in selection helpers:</p>

In [27]:
name <- "color"
select(starwars, ends_with(name))

   hair_color    skin_color          eye_color
1  blond         fair                blue
2  NA            gold                yellow
3  NA            white, blue         red
4  none          white               yellow
5  brown         light               brown
6  brown, grey   light               blue
7  brown         light               blue
8  NA            white, red          red
9  black         light               brown
10 auburn, white fair                blue-gray
11 blond         fair                blue
12 auburn, grey  fair                blue
13 brown         unknown             blue
14 brown         fair                brown
15 NA            green               black
16 NA            green-tan, brown    orange
17 brown         fair                hazel
18 brown         fair                blue
19 white         green               brown
20 grey          pale                yellow
21 black         fair                brown
22 none          metal               red
23 none          green               red
24 black         dark                brown
25 none          light               blue
26 none          brown mottle        orange
27 auburn        fair                blue
28 brown         fair                brown
29 brown         brown               brown
30 none          grey                black
⋮  ⋮             ⋮                   ⋮
58 brown         light               brown
59 brown         fair                blue
60 none          green               yellow
61 black         yellow              blue
62 black         yellow              blue
63 brown         light               brown
64 white         fair                brown
65 black         tan                 brown
66 black         tan                 brown
67 blonde        fair, green, yellow yellow
68 none          brown               yellow
69 none          grey                black
70 none          grey                black
71 white         fair                blue
72 none          grey, blue          unknown
73 none          silver, red         red, blue
74 none          green, grey         unknown
75 none          grey                gold
76 none          red, blue, white    black
77 none          brown, white        green, yellow
78 brown         brown               blue
79 brown         light               brown
80 none          pale                white
81 none          grey                black
82 black         dark                dark
83 brown         light               hazel
84 brown         light               brown
85 none          none                black
86 unknown       unknown             unknown
87 brown         light               brown

<p>These semantics are usually intuitive. But note the subtle difference:</p>

In [28]:
name <- 5
select(starwars, name, identity(name))

   name                  skin_color
1  Luke Skywalker        fair
2  C-3PO                 gold
3  R2-D2                 white, blue
4  Darth Vader           white
5  Leia Organa           light
6  Owen Lars             light
7  Beru Whitesun lars    light
8  R5-D4                 white, red
9  Biggs Darklighter     light
10 Obi-Wan Kenobi        fair
11 Anakin Skywalker      fair
12 Wilhuff Tarkin        fair
13 Chewbacca             unknown
14 Han Solo              fair
15 Greedo                green
16 Jabba Desilijic Tiure green-tan, brown
17 Wedge Antilles        fair
18 Jek Tono Porkins      fair
19 Yoda                  green
20 Palpatine             pale
21 Boba Fett             fair
22 IG-88                 metal
23 Bossk                 green
24 Lando Calrissian      dark
25 Lobot                 light
26 Ackbar                brown mottle
27 Mon Mothma            fair
28 Arvel Crynyd          fair
29 Wicket Systri Warrick brown
30 Nien Nunb             grey
⋮  ⋮                     ⋮
58 Cordé                 light
59 Cliegg Lars           fair
60 Poggle the Lesser     green
61 Luminara Unduli       yellow
62 Barriss Offee         yellow
63 Dormé                 light
64 Dooku                 fair
65 Bail Prestor Organa   tan
66 Jango Fett            tan
67 Zam Wesell            fair, green, yellow
68 Dexter Jettster       brown
69 Lama Su               grey
70 Taun We               grey
71 Jocasta Nu            fair
72 Ratts Tyerell         grey, blue
73 R4-P17                silver, red
74 Wat Tambor            green, grey
75 San Hill              grey
76 Shaak Ti              red, blue, white
77 Grievous              brown, white
78 Tarfful               brown
79 Raymus Antilles       light
80 Sly Moore             pale
81 Tion Medon            grey
82 Finn                  dark
83 Rey                   light
84 Poe Dameron           light
85 BB8                   none
86 Captain Phasma        unknown
87 Padmé Amidala         light

<p>In the first argument, <code>name</code> represents its own position <code>1</code>. In the second argument, <code>name</code> is evaluated in the surrounding context and represents the fifth column.</p>

<p>For a long time, <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> used to only understand column positions. Counting from dplyr 0.6, it now understands column names as well. This makes it a bit easier to program with <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>:</p>

In [29]:
vars <- c("name", "height")
select(starwars, all_of(vars), "mass")

   name                  height mass
1  Luke Skywalker        172      77.0
2  C-3PO                 167      75.0
3  R2-D2                  96      32.0
4  Darth Vader           202     136.0
5  Leia Organa           150      49.0
6  Owen Lars             178     120.0
7  Beru Whitesun lars    165      75.0
8  R5-D4                  97      32.0
9  Biggs Darklighter     183      84.0
10 Obi-Wan Kenobi        182      77.0
11 Anakin Skywalker      188      84.0
12 Wilhuff Tarkin        180        NA
13 Chewbacca             228     112.0
14 Han Solo              180      80.0
15 Greedo                173      74.0
16 Jabba Desilijic Tiure 175    1358.0
17 Wedge Antilles        170      77.0
18 Jek Tono Porkins      180     110.0
19 Yoda                   66      17.0
20 Palpatine             170      75.0
21 Boba Fett             183      78.2
22 IG-88                 200     140.0
23 Bossk                 190     113.0
24 Lando Calrissian      177      79.0
25 Lobot                 175      79.0
26 Ackbar                180      83.0
27 Mon Mothma            150        NA
28 Arvel Crynyd           NA        NA
29 Wicket Systri Warrick  88      20.0
30 Nien Nunb             160      68.0
⋮  ⋮                     ⋮      ⋮
58 Cordé                 157       NA
59 Cliegg Lars           183       NA
60 Poggle the Lesser     183     80.0
61 Luminara Unduli       170     56.2
62 Barriss Offee         166     50.0
63 Dormé                 165       NA
64 Dooku                 193     80.0
65 Bail Prestor Organa   191       NA
66 Jango Fett            183     79.0
67 Zam Wesell            168     55.0
68 Dexter Jettster       198    102.0
69 Lama Su               229     88.0
70 Taun We               213       NA
71 Jocasta Nu            167       NA
72 Ratts Tyerell          79     15.0
73 R4-P17                 96       NA
74 Wat Tambor            193     48.0
75 San Hill              191       NA
76 Shaak Ti              178     57.0
77 Grievous              216    159.0
78 Tarfful               234    136.0
79 Raymus Antilles       188     79.0
80 Sly Moore             178     48.0
81 Tion Medon            206     80.0
82 Finn                   NA       NA
83 Rey                    NA       NA
84 Poe Dameron            NA       NA
85 BB8                    NA       NA
86 Captain Phasma         NA       NA
87 Padmé Amidala         165     45.0

## <h3 id="mutating-operations">Mutating operations</h3>

<p>Mutate semantics are quite different from selection semantics.
Whereas <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> expects column names or positions, <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> expects <em>column vectors</em>. We will set up a smaller tibble to use for our examples.</p>

In [30]:
df <- starwars |> select(name, height, mass)

<p>When we use <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, the bare column names stand for their own positions in the tibble. For <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> on the other hand, column symbols represent the actual column vectors stored in the tibble. Consider what happens if we give a string or a number to <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>:</p>

In [31]:
mutate(df, "height", 2)

   name                  height mass   "height" 2
1  Luke Skywalker        172      77.0 height   2
2  C-3PO                 167      75.0 height   2
3  R2-D2                  96      32.0 height   2
4  Darth Vader           202     136.0 height   2
5  Leia Organa           150      49.0 height   2
6  Owen Lars             178     120.0 height   2
7  Beru Whitesun lars    165      75.0 height   2
8  R5-D4                  97      32.0 height   2
9  Biggs Darklighter     183      84.0 height   2
10 Obi-Wan Kenobi        182      77.0 height   2
11 Anakin Skywalker      188      84.0 height   2
12 Wilhuff Tarkin        180        NA height   2
13 Chewbacca             228     112.0 height   2
14 Han Solo              180      80.0 height   2
15 Greedo                173      74.0 height   2
16 Jabba Desilijic Tiure 175    1358.0 height   2
17 Wedge Antilles        170      77.0 height   2
18 Jek Tono Porkins      180     110.0 height   2
19 Yoda                   66      17.0 height   2
20 Palpatine             170      75.0 height   2
21 Boba Fett             183      78.2 height   2
22 IG-88                 200     140.0 height   2
23 Bossk                 190     113.0 height   2
24 Lando Calrissian      177      79.0 height   2
25 Lobot                 175      79.0 height   2
26 Ackbar                180      83.0 height   2
27 Mon Mothma            150        NA height   2
28 Arvel Crynyd           NA        NA height   2
29 Wicket Systri Warrick  88      20.0 height   2
30 Nien Nunb             160      68.0 height   2
⋮  ⋮                     ⋮      ⋮      ⋮        ⋮
58 Cordé                 157       NA  height   2
59 Cliegg Lars           183       NA  height   2
60 Poggle the Lesser     183     80.0  height   2
61 Luminara Unduli       170     56.2  height   2
62 Barriss Offee         166     50.0  height   2
63 Dormé                 165       NA  height   2
64 Dooku                 193     80.0  height   2
65 Bail Prestor Organa   191       NA  height   2
66 Jango Fett            183     79.0  height   2
67 Zam Wesell            168     55.0  height   2
68 Dexter Jettster       198    102.0  height   2
69 Lama Su               229     88.0  height   2
70 Taun We               213       NA  height   2
71 Jocasta Nu            167       NA  height   2
72 Ratts Tyerell          79     15.0  height   2
73 R4-P17                 96       NA  height   2
74 Wat Tambor            193     48.0  height   2
75 San Hill              191       NA  height   2
76 Shaak Ti              178     57.0  height   2
77 Grievous              216    159.0  height   2
78 Tarfful               234    136.0  height   2
79 Raymus Antilles       188     79.0  height   2
80 Sly Moore             178     48.0  height   2
81 Tion Medon            206     80.0  height   2
82 Finn                   NA       NA  height   2
83 Rey                    NA       NA  height   2
84 Poe Dameron            NA       NA  height   2
85 BB8                    NA       NA  height   2
86 Captain Phasma         NA       NA  height   2
87 Padmé Amidala         165     45.0  height   2

<p><code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> gets length-1 vectors that it interprets as new columns in the data frame. These vectors are recycled so they match the number of rows. That’s why it doesn’t make sense to supply expressions like <code>"height" + 10</code> to <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>. This amounts to adding 10 to a string! The correct expression is:</p>

In [32]:
mutate(df, height + 10)

   name                  height mass   height + 10
1  Luke Skywalker        172      77.0 182
2  C-3PO                 167      75.0 177
3  R2-D2                  96      32.0 106
4  Darth Vader           202     136.0 212
5  Leia Organa           150      49.0 160
6  Owen Lars             178     120.0 188
7  Beru Whitesun lars    165      75.0 175
8  R5-D4                  97      32.0 107
9  Biggs Darklighter     183      84.0 193
10 Obi-Wan Kenobi        182      77.0 192
11 Anakin Skywalker      188      84.0 198
12 Wilhuff Tarkin        180        NA 190
13 Chewbacca             228     112.0 238
14 Han Solo              180      80.0 190
15 Greedo                173      74.0 183
16 Jabba Desilijic Tiure 175    1358.0 185
17 Wedge Antilles        170      77.0 180
18 Jek Tono Porkins      180     110.0 190
19 Yoda                   66      17.0  76
20 Palpatine             170      75.0 180
21 Boba Fett             183      78.2 193
22 IG-88                 200     140.0 210
23 Bossk                 190     113.0 200
24 Lando Calrissian      177      79.0 187
25 Lobot                 175      79.0 185
26 Ackbar                180      83.0 190
27 Mon Mothma            150        NA 160
28 Arvel Crynyd           NA        NA  NA
29 Wicket Systri Warrick  88      20.0  98
30 Nien Nunb             160      68.0 170
⋮  ⋮                     ⋮      ⋮      ⋮
58 Cordé                 157       NA  167
59 Cliegg Lars           183       NA  193
60 Poggle the Lesser     183     80.0  193
61 Luminara Unduli       170     56.2  180
62 Barriss Offee         166     50.0  176
63 Dormé                 165       NA  175
64 Dooku                 193     80.0  203
65 Bail Prestor Organa   191       NA  201
66 Jango Fett            183     79.0  193
67 Zam Wesell            168     55.0  178
68 Dexter Jettster       198    102.0  208
69 Lama Su               229     88.0  239
70 Taun We               213       NA  223
71 Jocasta Nu            167       NA  177
72 Ratts Tyerell          79     15.0   89
73 R4-P17                 96       NA  106
74 Wat Tambor            193     48.0  203
75 San Hill              191       NA  201
76 Shaak Ti              178     57.0  188
77 Grievous              216    159.0  226
78 Tarfful               234    136.0  244
79 Raymus Antilles       188     79.0  198
80 Sly Moore             178     48.0  188
81 Tion Medon            206     80.0  216
82 Finn                   NA       NA   NA
83 Rey                    NA       NA   NA
84 Poe Dameron            NA       NA   NA
85 BB8                    NA       NA   NA
86 Captain Phasma         NA       NA   NA
87 Padmé Amidala         165     45.0  175

<p>In the same way, you can unquote values from the context if these values represent a valid column. They must be either length 1 (they then get recycled) or have the same length as the number of rows. In the following example we create a new vector that we add to the data frame:</p>

In [33]:
var <- seq(1, nrow(df))
mutate(df, new = var)

   name                  height mass   new
1  Luke Skywalker        172      77.0  1
2  C-3PO                 167      75.0  2
3  R2-D2                  96      32.0  3
4  Darth Vader           202     136.0  4
5  Leia Organa           150      49.0  5
6  Owen Lars             178     120.0  6
7  Beru Whitesun lars    165      75.0  7
8  R5-D4                  97      32.0  8
9  Biggs Darklighter     183      84.0  9
10 Obi-Wan Kenobi        182      77.0 10
11 Anakin Skywalker      188      84.0 11
12 Wilhuff Tarkin        180        NA 12
13 Chewbacca             228     112.0 13
14 Han Solo              180      80.0 14
15 Greedo                173      74.0 15
16 Jabba Desilijic Tiure 175    1358.0 16
17 Wedge Antilles        170      77.0 17
18 Jek Tono Porkins      180     110.0 18
19 Yoda                   66      17.0 19
20 Palpatine             170      75.0 20
21 Boba Fett             183      78.2 21
22 IG-88                 200     140.0 22
23 Bossk                 190     113.0 23
24 Lando Calrissian      177      79.0 24
25 Lobot                 175      79.0 25
26 Ackbar                180      83.0 26
27 Mon Mothma            150        NA 27
28 Arvel Crynyd           NA        NA 28
29 Wicket Systri Warrick  88      20.0 29
30 Nien Nunb             160      68.0 30
⋮  ⋮                     ⋮      ⋮      ⋮
58 Cordé                 157       NA  58
59 Cliegg Lars           183       NA  59
60 Poggle the Lesser     183     80.0  60
61 Luminara Unduli       170     56.2  61
62 Barriss Offee         166     50.0  62
63 Dormé                 165       NA  63
64 Dooku                 193     80.0  64
65 Bail Prestor Organa   191       NA  65
66 Jango Fett            183     79.0  66
67 Zam Wesell            168     55.0  67
68 Dexter Jettster       198    102.0  68
69 Lama Su               229     88.0  69
70 Taun We               213       NA  70
71 Jocasta Nu            167       NA  71
72 Ratts Tyerell          79     15.0  72
73 R4-P17                 96       NA  73
74 Wat Tambor            193     48.0  74
75 San Hill              191       NA  75
76 Shaak Ti              178     57.0  76
77 Grievous              216    159.0  77
78 Tarfful               234    136.0  78
79 Raymus Antilles       188     79.0  79
80 Sly Moore             178     48.0  80
81 Tion Medon            206     80.0  81
82 Finn                   NA       NA  82
83 Rey                    NA       NA  83
84 Poe Dameron            NA       NA  84
85 BB8                    NA       NA  85
86 Captain Phasma         NA       NA  86
87 Padmé Amidala         165     45.0  87

<p>A case in point is <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code>. While you might think it has select semantics, it actually has mutate semantics. This is quite handy as it allows to group by a modified column:</p>

In [36]:
group_by(starwars, sex)

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Cordé                 157       NA  brown         light
59 Cliegg Lars           183       NA  brown         fair
60 Poggle the Lesser     183     80.0  none          green
61 Luminara Unduli       170     56.2  black         yellow
62 Barriss Offee         166     50.0  black         yellow
63 Dormé                 165       NA  brown         light
64 Dooku                 193     80.0  white         fair
65 Bail Prestor Organa   191       NA  black         tan
66 Jango Fett            183     79.0  black         tan
67 Zam Wesell            168     55.0  blonde        fair, green, yellow
68 Dexter Jettster       198    102.0  none          brown
69 Lama Su               229     88.0  none          grey
70 Taun We               213       NA  none          grey
71 Jocasta Nu            167       NA  white         fair
72 Ratts Tyerell          79     15.0  none          grey, blue
73 R4-P17                 96       NA  none          silver, red
74 Wat Tambor            193     48.0  none          green, grey
75 San Hill              191       NA  none          grey
76 Shaak Ti              178     57.0  none          red, blue, white
77 Grievous              216    159.0  none          brown, white
78 Tarfful               234    136.0  brown         brown
79 Raymus Antilles       188     79.0  brown         light
80 Sly Moore             178     48.0  none          pale
81 Tion Medon            206     80.0  none          grey
82 Finn                   NA       NA  black         dark
83 Rey                    NA       NA  brown         light
84 Poe Dameron            NA       NA  brown         light
85 BB8                    NA       NA  none          none
86 Captain Phasma         NA       NA  unknown       unknown
87 Padmé Amidala         165     45.0  brown         light
   eye_color     birth_year sex            gender    homeworld
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      male           masculine Bestine IV
19 brown         896.0      male           masculine NA
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine NA
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine NA
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 brown          NA        female         feminine  Naboo
59 blue           82        male           masculine Tatooine
60 yellow         NA        male           masculine Geonosis
61 blue           58        female         feminine  Mirial
62 blue           40        female         feminine  Mirial
63 brown          NA        female         feminine  Naboo
64 brown         102        male           masculine Serenno
65 brown          67        male           masculine Alderaan
66 brown          66        male           masculine Concord Dawn
67 yellow         NA        female         feminine  Zolan
68 yellow         NA        male           masculine Ojom
69 black          NA        male           masculine Kamino
70 black          NA        female         feminine  Kamino
71 blue           NA        female         feminine  Coruscant
72 unknown        NA        male           masculine Aleen Minor
73 red, blue      NA        none           feminine  NA
74 unknown        NA        male           masculine Skako
75 gold           NA        male           masculine Muunilinst
76 black          NA        female         feminine  Shili
77 green, yellow  NA        male           masculine Kalee
78 blue           NA        male           masculine Kashyyyk
79 brown          NA        male           masculine Alderaan
80 white          NA        NA             NA        Umbara
81 black          NA        male           masculine Utapau
82 dark           NA        male           masculine NA
83 hazel          NA        female         feminine  NA
84 brown          NA        male           masculine NA
85 black          NA        none           masculine NA
86 unknown        NA        NA             NA        NA
87 brown          46        female         feminine  Naboo
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 Human
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Human
59 Human
60 Geonosian
61 Mirialan
62 Mirialan
63 Human
64 Human
65 Human
66 Human
67 Clawdite
68 Besalisk
69 Kaminoan
70 Kaminoan
71 Human
72 Aleena
73 Droid
74 Skakoan
75 Muun
76 Togruta
77 Kaleesh
78 Wookiee
79 Human
80 NA
81 Pau'an
82 Human
83 Human
84 Human
85 Droid
86 NA
87 Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

In [37]:
group_by(starwars, sex = as.factor(sex))

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Cordé                 157       NA  brown         light
59 Cliegg Lars           183       NA  brown         fair
60 Poggle the Lesser     183     80.0  none          green
61 Luminara Unduli       170     56.2  black         yellow
62 Barriss Offee         166     50.0  black         yellow
63 Dormé                 165       NA  brown         light
64 Dooku                 193     80.0  white         fair
65 Bail Prestor Organa   191       NA  black         tan
66 Jango Fett            183     79.0  black         tan
67 Zam Wesell            168     55.0  blonde        fair, green, yellow
68 Dexter Jettster       198    102.0  none          brown
69 Lama Su               229     88.0  none          grey
70 Taun We               213       NA  none          grey
71 Jocasta Nu            167       NA  white         fair
72 Ratts Tyerell          79     15.0  none          grey, blue
73 R4-P17                 96       NA  none          silver, red
74 Wat Tambor            193     48.0  none          green, grey
75 San Hill              191       NA  none          grey
76 Shaak Ti              178     57.0  none          red, blue, white
77 Grievous              216    159.0  none          brown, white
78 Tarfful               234    136.0  brown         brown
79 Raymus Antilles       188     79.0  brown         light
80 Sly Moore             178     48.0  none          pale
81 Tion Medon            206     80.0  none          grey
82 Finn                   NA       NA  black         dark
83 Rey                    NA       NA  brown         light
84 Poe Dameron            NA       NA  brown         light
85 BB8                    NA       NA  none          none
86 Captain Phasma         NA       NA  unknown       unknown
87 Padmé Amidala         165     45.0  brown         light
   eye_color     birth_year sex            gender    homeworld
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      male           masculine Bestine IV
19 brown         896.0      male           masculine NA
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine NA
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine NA
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 brown          NA        female         feminine  Naboo
59 blue           82        male           masculine Tatooine
60 yellow         NA        male           masculine Geonosis
61 blue           58        female         feminine  Mirial
62 blue           40        female         feminine  Mirial
63 brown          NA        female         feminine  Naboo
64 brown         102        male           masculine Serenno
65 brown          67        male           masculine Alderaan
66 brown          66        male           masculine Concord Dawn
67 yellow         NA        female         feminine  Zolan
68 yellow         NA        male           masculine Ojom
69 black          NA        male           masculine Kamino
70 black          NA        female         feminine  Kamino
71 blue           NA        female         feminine  Coruscant
72 unknown        NA        male           masculine Aleen Minor
73 red, blue      NA        none           feminine  NA
74 unknown        NA        male           masculine Skako
75 gold           NA        male           masculine Muunilinst
76 black          NA        female         feminine  Shili
77 green, yellow  NA        male           masculine Kalee
78 blue           NA        male           masculine Kashyyyk
79 brown          NA        male           masculine Alderaan
80 white          NA        NA             NA        Umbara
81 black          NA        male           masculine Utapau
82 dark           NA        male           masculine NA
83 hazel          NA        female         feminine  NA
84 brown          NA        male           masculine NA
85 black          NA        none           masculine NA
86 unknown        NA        NA             NA        NA
87 brown          46        female         feminine  Naboo
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 Human
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Human
59 Human
60 Geonosian
61 Mirialan
62 Mirialan
63 Human
64 Human
65 Human
66 Human
67 Clawdite
68 Besalisk
69 Kaminoan
70 Kaminoan
71 Human
72 Aleena
73 Droid
74 Skakoan
75 Muun
76 Togruta
77 Kaleesh
78 Wookiee
79 Human
80 NA
81 Pau'an
82 Human
83 Human
84 Human
85 Droid
86 NA
87 Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

In [38]:
group_by(starwars, height_binned = cut(height, 3))

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Cordé                 157       NA  brown         light
59 Cliegg Lars           183       NA  brown         fair
60 Poggle the Lesser     183     80.0  none          green
61 Luminara Unduli       170     56.2  black         yellow
62 Barriss Offee         166     50.0  black         yellow
63 Dormé                 165       NA  brown         light
64 Dooku                 193     80.0  white         fair
65 Bail Prestor Organa   191       NA  black         tan
66 Jango Fett            183     79.0  black         tan
67 Zam Wesell            168     55.0  blonde        fair, green, yellow
68 Dexter Jettster       198    102.0  none          brown
69 Lama Su               229     88.0  none          grey
70 Taun We               213       NA  none          grey
71 Jocasta Nu            167       NA  white         fair
72 Ratts Tyerell          79     15.0  none          grey, blue
73 R4-P17                 96       NA  none          silver, red
74 Wat Tambor            193     48.0  none          green, grey
75 San Hill              191       NA  none          grey
76 Shaak Ti              178     57.0  none          red, blue, white
77 Grievous              216    159.0  none          brown, white
78 Tarfful               234    136.0  brown         brown
79 Raymus Antilles       188     79.0  brown         light
80 Sly Moore             178     48.0  none          pale
81 Tion Medon            206     80.0  none          grey
82 Finn                   NA       NA  black         dark
83 Rey                    NA       NA  brown         light
84 Poe Dameron            NA       NA  brown         light
85 BB8                    NA       NA  none          none
86 Captain Phasma         NA       NA  unknown       unknown
87 Padmé Amidala         165     45.0  brown         light
   eye_color     birth_year sex            gender    homeworld
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      male           masculine Bestine IV
19 brown         896.0      male           masculine NA
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine NA
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine NA
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 brown          NA        female         feminine  Naboo
59 blue           82        male           masculine Tatooine
60 yellow         NA        male           masculine Geonosis
61 blue           58        female         feminine  Mirial
62 blue           40        female         feminine  Mirial
63 brown          NA        female         feminine  Naboo
64 brown         102        male           masculine Serenno
65 brown          67        male           masculine Alderaan
66 brown          66        male           masculine Concord Dawn
67 yellow         NA        female         feminine  Zolan
68 yellow         NA        male           masculine Ojom
69 black          NA        male           masculine Kamino
70 black          NA        female         feminine  Kamino
71 blue           NA        female         feminine  Coruscant
72 unknown        NA        male           masculine Aleen Minor
73 red, blue      NA        none           feminine  NA
74 unknown        NA        male           masculine Skako
75 gold           NA        male           masculine Muunilinst
76 black          NA        female         feminine  Shili
77 green, yellow  NA        male           masculine Kalee
78 blue           NA        male           masculine Kashyyyk
79 brown          NA        male           masculine Alderaan
80 white          NA        NA             NA        Umbara
81 black          NA        male           masculine Utapau
82 dark           NA        male           masculine NA
83 hazel          NA        female         feminine  NA
84 brown          NA        male           masculine NA
85 black          NA        none           masculine NA
86 unknown        NA        NA             NA        NA
87 brown          46        female         feminine  Naboo
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 Human
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Human
59 Human
60 Geonosian
61 Mirialan
62 Mirialan
63 Human
64 Human
65 Human
66 Human
67 Clawdite
68 Besalisk
69 Kaminoan
70 Kaminoan
71 Human
72 Aleena
73 Droid
74 Skakoan
75 Muun
76 Togruta
77 Kaleesh
78 Wookiee
79 Human
80 NA
81 Pau'an
82 Human
83 Human
84 Human
85 Droid
86 NA
87 Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter
   height_binned
1  (132,198]
2  (132,198]
3  (65.8,132]
4  (198,264]
5  (132,198]
6  (132,198]
7  (132,198]
8  (65.8,132]
9  (132,198]
10 (132,198]
11 (132,198]
12 (132,198]
13 (198,264]
14 (132,198]
15 (132,198]
16 (132,198]
17 (132,198]
18 (132,198]
19 (65.8,132]
20 (132,198]
21 (132,198]
22 (198,264]
23 (132,198]
24 (132,198]
25 (132,198]
26 (132,198]
27 (132,198]
28 NA
29 (65.8,132]
30 (132,198]
⋮  ⋮
58 (132,198]
59 (132,198]
60 (132,198]
61 (132,198]
62 (132,198]
63 (132,198]
64 (132,198]
65 (132,198]
66 (132,198]
67 (132,198]
68 (132,198]
69 (198,264]
70 (198,264]
71 (132,198]
72 (65.8,132]
73 (65.8,132]
74 (132,198]
75 (132,198]
76 (132,198]
77 (198,264]
78 (198,264]
79 (132,198]
80 (132,198]
81 (198,264]
82 NA
83 NA
84 NA
85 NA
86 NA
87 (132,198]

<p>This is why you can’t supply a column name to <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code>. This amounts to creating a new column containing the string recycled to the number of rows:</p>

In [39]:
group_by(df, "month")

   name                  height mass   "month"
1  Luke Skywalker        172      77.0 month
2  C-3PO                 167      75.0 month
3  R2-D2                  96      32.0 month
4  Darth Vader           202     136.0 month
5  Leia Organa           150      49.0 month
6  Owen Lars             178     120.0 month
7  Beru Whitesun lars    165      75.0 month
8  R5-D4                  97      32.0 month
9  Biggs Darklighter     183      84.0 month
10 Obi-Wan Kenobi        182      77.0 month
11 Anakin Skywalker      188      84.0 month
12 Wilhuff Tarkin        180        NA month
13 Chewbacca             228     112.0 month
14 Han Solo              180      80.0 month
15 Greedo                173      74.0 month
16 Jabba Desilijic Tiure 175    1358.0 month
17 Wedge Antilles        170      77.0 month
18 Jek Tono Porkins      180     110.0 month
19 Yoda                   66      17.0 month
20 Palpatine             170      75.0 month
21 Boba Fett             183      78.2 month
22 IG-88                 200     140.0 month
23 Bossk                 190     113.0 month
24 Lando Calrissian      177      79.0 month
25 Lobot                 175      79.0 month
26 Ackbar                180      83.0 month
27 Mon Mothma            150        NA month
28 Arvel Crynyd           NA        NA month
29 Wicket Systri Warrick  88      20.0 month
30 Nien Nunb             160      68.0 month
⋮  ⋮                     ⋮      ⋮      ⋮
58 Cordé                 157       NA  month
59 Cliegg Lars           183       NA  month
60 Poggle the Lesser     183     80.0  month
61 Luminara Unduli       170     56.2  month
62 Barriss Offee         166     50.0  month
63 Dormé                 165       NA  month
64 Dooku                 193     80.0  month
65 Bail Prestor Organa   191       NA  month
66 Jango Fett            183     79.0  month
67 Zam Wesell            168     55.0  month
68 Dexter Jettster       198    102.0  month
69 Lama Su               229     88.0  month
70 Taun We               213       NA  month
71 Jocasta Nu            167       NA  month
72 Ratts Tyerell          79     15.0  month
73 R4-P17                 96       NA  month
74 Wat Tambor            193     48.0  month
75 San Hill              191       NA  month
76 Shaak Ti              178     57.0  month
77 Grievous              216    159.0  month
78 Tarfful               234    136.0  month
79 Raymus Antilles       188     79.0  month
80 Sly Moore             178     48.0  month
81 Tion Medon            206     80.0  month
82 Finn                   NA       NA  month
83 Rey                    NA       NA  month
84 Poe Dameron            NA       NA  month
85 BB8                    NA       NA  month
86 Captain Phasma         NA       NA  month
87 Padmé Amidala         165     45.0  month