<h1>Keep or drop columns using their names and types</h1>

<small>Source: <a href="https://github.com/tidyverse/dplyr/blob/pkgdown-v1.1.4/R/select.R"><code>R/select.R</code></a></small>
<div><code>select.Rd</code></div>

<p>Select (and optionally rename) variables in a data frame, using a concise mini-language that makes it easy to refer to variables based on their name (e.g. <code>a:f</code> selects all columns from <code>a</code> on the left to <code>f</code> on the right) or type (e.g. <code>where(is.numeric)</code> selects all numeric columns).</p>

## <h3 id="overview-of-selection-features">Overview of selection features</h3>

<p>Tidyverse selections implement a dialect of R where operators make
it easy to select variables:</p>

<ul>
<li><p><code>:</code> for selecting a range of consecutive variables.</p></li>
<li><p><code>!</code> for taking the complement of a set of variables.</p></li>
<li><p><code>&amp;</code> and <code>|</code> for selecting the intersection or the union of two sets of variables.</p></li>
<li><p><code><a href="https://rdrr.io/r/base/c.html">c()</a></code> for combining selections.</p></li>
</ul>

<p>In addition, you can use <strong>selection helpers</strong>. Some helpers select specific columns:</p>

<ul>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/everything.html">everything()</a></code>: Matches all variables.</p></li>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/everything.html">last_col()</a></code>: Select last variable, possibly with an offset.</p></li>
<li><p><code><a href="group_cols.html">group_cols()</a></code>: Select all grouping columns.</p></li>
</ul>

<p>Other helpers select variables by matching patterns in their names:</p>

<ul>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with()</a></code>: Starts with a prefix.</p></li>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">ends_with()</a></code>: Ends with a suffix.</p></li>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">contains()</a></code>: Contains a literal string.</p></li>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">matches()</a></code>: Matches a regular expression.</p></li>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">num_range()</a></code>: Matches a numerical range like x01, x02, x03.</p></li>
</ul><p>Or from variables stored in a character vector:</p><ul><li><p><code><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of()</a></code>: Matches variable names in a character vector. All names must be present, otherwise an out-of-bounds error is thrown.</p></li>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/all_of.html">any_of()</a></code>: Same as <code><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of()</a></code>, except that no error is thrown for names that don't exist.</p></li>
</ul>

<p>Or using a predicate function:</p>

<ul>
<li><p><code><a href="https://tidyselect.r-lib.org/reference/where.html">where()</a></code>: Applies a function to all variables and selects those for which the function returns <code>TRUE</code>.</p></li>
</ul>

# <h2 id="ref-usage">Usage</h2>

<pre class="sourceCode r"><code>select(.data, ...)</code></pre>

# <h2 id="arguments">Arguments</h2>

<dl>

<dt id="arg--data">.data</dt>
<dd><p>A data frame, data frame extension (e.g. a tibble), or a lazy data frame (e.g. from dbplyr or dtplyr). See <em>Methods</em>, below, for more details.</p></dd>

<dt id="arg--">...</dt>
<dd><p>&lt;<code><a href="dplyr_tidy_select.html">tidy-select</a></code>&gt; One or more unquoted expressions separated by commas. Variable names can be used as if they were positions in the data frame, so expressions like <code>x:y</code> can be used to select a range of variables.</p></dd>

</dl>

# <h2 id="value">Value</h2>

<p>An object of the same type as <code>.data</code>. The output has the following properties:</p>

<ul>
<li><p>Rows are not affected.</p></li>
<li><p>Output columns are a subset of input columns, potentially with a different order. Columns will be renamed if <code>new_name = old_name</code> form is used.</p></li>
<li><p>Data frame attributes are preserved.</p></li>
<li><p>Groups are maintained; you can't select off grouping variables.</p></li>
</ul>

# <h2 id="methods">Methods</h2>

<p>This function is a <strong>generic</strong>, which means that packages can provide implementations (methods) for other classes.
See the documentation of individual methods for extra arguments and differences in behaviour.</p>

<p>The following methods are currently available in loaded packages:
dbplyr (<code><a href="https://dbplyr.tidyverse.org/reference/select.tbl_lazy.html">tbl_lazy</a></code>), dplyr (<code>data.frame</code>)
.</p>

# <h2 id="examples">Examples</h2>

<p>Here we show the usage for the basic selection operators. See the
specific help pages to learn about helpers like <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with()</a></code>.</p>

<p>The selection language can be used in functions like
<code>dplyr::select()</code> or <code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">tidyr::pivot_longer()</a></code>. Let's first attach the tidyverse:</p>

In [1]:
library(tidyverse)

# For better printing
iris <- as_tibble(iris)

── Attaching packages ────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   1.1.0
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ───────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

<p>Select variables by name:</p>

In [2]:
starwars |> select(height)

   height
1  172
2  167
3   96
4  202
5  150
6  178
7  165
8   97
9  183
10 182
11 188
12 180
13 228
14 180
15 173
16 175
17 170
18 180
19  66
20 170
21 183
22 200
23 190
24 177
25 175
26 180
27 150
28  NA
29  88
30 160
⋮  ⋮
58 157
59 183
60 183
61 170
62 166
63 165
64 193
65 191
66 183
67 168
68 198
69 229
70 213
71 167
72  79
73  96
74 193
75 191
76 178
77 216
78 234
79 188
80 178
81 206
82  NA
83  NA
84  NA
85  NA
86  NA
87 165

In [3]:
iris |> pivot_longer(Sepal.Length)

    Sepal.Width Petal.Length Petal.Width Species   name         value
1   3.5         1.4          0.2         setosa    Sepal.Length 5.1
2   3.0         1.4          0.2         setosa    Sepal.Length 4.9
3   3.2         1.3          0.2         setosa    Sepal.Length 4.7
4   3.1         1.5          0.2         setosa    Sepal.Length 4.6
5   3.6         1.4          0.2         setosa    Sepal.Length 5.0
6   3.9         1.7          0.4         setosa    Sepal.Length 5.4
7   3.4         1.4          0.3         setosa    Sepal.Length 4.6
8   3.4         1.5          0.2         setosa    Sepal.Length 5.0
9   2.9         1.4          0.2         setosa    Sepal.Length 4.4
10  3.1         1.5          0.1         setosa    Sepal.Length 4.9
11  3.7         1.5          0.2         setosa    Sepal.Length 5.4
12  3.4         1.6          0.2         setosa    Sepal.Length 4.8
13  3.0         1.4          0.1         setosa    Sepal.Length 4.8
14  3.0         1.1          0.1         setosa    Sepal.Length 4.3
15  4.0         1.2          0.2         setosa    Sepal.Length 5.8
16  4.4         1.5          0.4         setosa    Sepal.Length 5.7
17  3.9         1.3          0.4         setosa    Sepal.Length 5.4
18  3.5         1.4          0.3         setosa    Sepal.Length 5.1
19  3.8         1.7          0.3         setosa    Sepal.Length 5.7
20  3.8         1.5          0.3         setosa    Sepal.Length 5.1
21  3.4         1.7          0.2         setosa    Sepal.Length 5.4
22  3.7         1.5          0.4         setosa    Sepal.Length 5.1
23  3.6         1.0          0.2         setosa    Sepal.Length 4.6
24  3.3         1.7          0.5         setosa    Sepal.Length 5.1
25  3.4         1.9          0.2         setosa    Sepal.Length 4.8
26  3.0         1.6          0.2         setosa    Sepal.Length 5.0
27  3.4         1.6          0.4         setosa    Sepal.Length 5.0
28  3.5         1.5          0.2         setosa    Sepal.Length 5.2
29  3.4         1.4          0.2         setosa    Sepal.Length 5.2
30  3.2         1.6          0.2         setosa    Sepal.Length 4.7
⋮   ⋮           ⋮            ⋮           ⋮         ⋮            ⋮
121 3.2         5.7          2.3         virginica Sepal.Length 6.9
122 2.8         4.9          2.0         virginica Sepal.Length 5.6
123 2.8         6.7          2.0         virginica Sepal.Length 7.7
124 2.7         4.9          1.8         virginica Sepal.Length 6.3
125 3.3         5.7          2.1         virginica Sepal.Length 6.7
126 3.2         6.0          1.8         virginica Sepal.Length 7.2
127 2.8         4.8          1.8         virginica Sepal.Length 6.2
128 3.0         4.9          1.8         virginica Sepal.Length 6.1
129 2.8         5.6          2.1         virginica Sepal.Length 6.4
130 3.0         5.8          1.6         virginica Sepal.Length 7.2
131 2.8         6.1          1.9         virginica Sepal.Length 7.4
132 3.8         6.4          2.0         virginica Sepal.Length 7.9
133 2.8         5.6          2.2         virginica Sepal.Length 6.4
134 2.8         5.1          1.5         virginica Sepal.Length 6.3
135 2.6         5.6          1.4         virginica Sepal.Length 6.1
136 3.0         6.1          2.3         virginica Sepal.Length 7.7
137 3.4         5.6          2.4         virginica Sepal.Length 6.3
138 3.1         5.5          1.8         virginica Sepal.Length 6.4
139 3.0         4.8          1.8         virginica Sepal.Length 6.0
140 3.1         5.4          2.1         virginica Sepal.Length 6.9
141 3.1         5.6          2.4         virginica Sepal.Length 6.7
142 3.1         5.1          2.3         virginica Sepal.Length 6.9
143 2.7         5.1          1.9         virginica Sepal.Length 5.8
144 3.2         5.9          2.3         virginica Sepal.Length 6.8
145 3.3         5.7          2.5         virginica Sepal.Length 6.7
146 3.0         5.2          2.3         virginica Sepal.Length 6.7
147 2.5         5.0          1.9         virginica Sepal.Length 6.3
148 3.0         5.2          2.0         virginica Sepal.Length 6.5
149 3.4         5.4          2.3         virginica Sepal.Length 6.2
150 3.0         5.1          1.8         virginica Sepal.Length 5.9

<p>Select multiple variables by separating them with commas. Note how
the order of columns is determined by the order of inputs:</p>

In [4]:
starwars |> select(homeworld, height, mass)

   homeworld    height mass
1  Tatooine     172      77.0
2  Tatooine     167      75.0
3  Naboo         96      32.0
4  Tatooine     202     136.0
5  Alderaan     150      49.0
6  Tatooine     178     120.0
7  Tatooine     165      75.0
8  Tatooine      97      32.0
9  Tatooine     183      84.0
10 Stewjon      182      77.0
11 Tatooine     188      84.0
12 Eriadu       180        NA
13 Kashyyyk     228     112.0
14 Corellia     180      80.0
15 Rodia        173      74.0
16 Nal Hutta    175    1358.0
17 Corellia     170      77.0
18 Bestine IV   180     110.0
19 NA            66      17.0
20 Naboo        170      75.0
21 Kamino       183      78.2
22 NA           200     140.0
23 Trandosha    190     113.0
24 Socorro      177      79.0
25 Bespin       175      79.0
26 Mon Cala     180      83.0
27 Chandrila    150        NA
28 NA            NA        NA
29 Endor         88      20.0
30 Sullust      160      68.0
⋮  ⋮            ⋮      ⋮
58 Naboo        157       NA
59 Tatooine     183       NA
60 Geonosis     183     80.0
61 Mirial       170     56.2
62 Mirial       166     50.0
63 Naboo        165       NA
64 Serenno      193     80.0
65 Alderaan     191       NA
66 Concord Dawn 183     79.0
67 Zolan        168     55.0
68 Ojom         198    102.0
69 Kamino       229     88.0
70 Kamino       213       NA
71 Coruscant    167       NA
72 Aleen Minor   79     15.0
73 NA            96       NA
74 Skako        193     48.0
75 Muunilinst   191       NA
76 Shili        178     57.0
77 Kalee        216    159.0
78 Kashyyyk     234    136.0
79 Alderaan     188     79.0
80 Umbara       178     48.0
81 Utapau       206     80.0
82 NA            NA       NA
83 NA            NA       NA
84 NA            NA       NA
85 NA            NA       NA
86 NA            NA       NA
87 Naboo        165     45.0

<p>Functions like <code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">tidyr::pivot_longer()</a></code> don't take variables with dots. In this case use <code><a href="https://rdrr.io/r/base/c.html">c()</a></code> to select multiple variables:</p>

In [5]:
iris |> pivot_longer(c(Sepal.Length, Petal.Length))

    Sepal.Width Petal.Width Species   name         value
1   3.5         0.2         setosa    Sepal.Length 5.1
2   3.5         0.2         setosa    Petal.Length 1.4
3   3.0         0.2         setosa    Sepal.Length 4.9
4   3.0         0.2         setosa    Petal.Length 1.4
5   3.2         0.2         setosa    Sepal.Length 4.7
6   3.2         0.2         setosa    Petal.Length 1.3
7   3.1         0.2         setosa    Sepal.Length 4.6
8   3.1         0.2         setosa    Petal.Length 1.5
9   3.6         0.2         setosa    Sepal.Length 5.0
10  3.6         0.2         setosa    Petal.Length 1.4
11  3.9         0.4         setosa    Sepal.Length 5.4
12  3.9         0.4         setosa    Petal.Length 1.7
13  3.4         0.3         setosa    Sepal.Length 4.6
14  3.4         0.3         setosa    Petal.Length 1.4
15  3.4         0.2         setosa    Sepal.Length 5.0
16  3.4         0.2         setosa    Petal.Length 1.5
17  2.9         0.2         setosa    Sepal.Length 4.4
18  2.9         0.2         setosa    Petal.Length 1.4
19  3.1         0.1         setosa    Sepal.Length 4.9
20  3.1         0.1         setosa    Petal.Length 1.5
21  3.7         0.2         setosa    Sepal.Length 5.4
22  3.7         0.2         setosa    Petal.Length 1.5
23  3.4         0.2         setosa    Sepal.Length 4.8
24  3.4         0.2         setosa    Petal.Length 1.6
25  3.0         0.1         setosa    Sepal.Length 4.8
26  3.0         0.1         setosa    Petal.Length 1.4
27  3.0         0.1         setosa    Sepal.Length 4.3
28  3.0         0.1         setosa    Petal.Length 1.1
29  4.0         0.2         setosa    Sepal.Length 5.8
30  4.0         0.2         setosa    Petal.Length 1.2
⋮   ⋮           ⋮           ⋮         ⋮            ⋮
271 3.0         2.3         virginica Sepal.Length 7.7
272 3.0         2.3         virginica Petal.Length 6.1
273 3.4         2.4         virginica Sepal.Length 6.3
274 3.4         2.4         virginica Petal.Length 5.6
275 3.1         1.8         virginica Sepal.Length 6.4
276 3.1         1.8         virginica Petal.Length 5.5
277 3.0         1.8         virginica Sepal.Length 6.0
278 3.0         1.8         virginica Petal.Length 4.8
279 3.1         2.1         virginica Sepal.Length 6.9
280 3.1         2.1         virginica Petal.Length 5.4
281 3.1         2.4         virginica Sepal.Length 6.7
282 3.1         2.4         virginica Petal.Length 5.6
283 3.1         2.3         virginica Sepal.Length 6.9
284 3.1         2.3         virginica Petal.Length 5.1
285 2.7         1.9         virginica Sepal.Length 5.8
286 2.7         1.9         virginica Petal.Length 5.1
287 3.2         2.3         virginica Sepal.Length 6.8
288 3.2         2.3         virginica Petal.Length 5.9
289 3.3         2.5         virginica Sepal.Length 6.7
290 3.3         2.5         virginica Petal.Length 5.7
291 3.0         2.3         virginica Sepal.Length 6.7
292 3.0         2.3         virginica Petal.Length 5.2
293 2.5         1.9         virginica Sepal.Length 6.3
294 2.5         1.9         virginica Petal.Length 5.0
295 3.0         2.0         virginica Sepal.Length 6.5
296 3.0         2.0         virginica Petal.Length 5.2
297 3.4         2.3         virginica Sepal.Length 6.2
298 3.4         2.3         virginica Petal.Length 5.4
299 3.0         1.8         virginica Sepal.Length 5.9
300 3.0         1.8         virginica Petal.Length 5.1

## <h3 id="operators-">Operators:</h3>

<p>The <code>:</code> operator selects a range of consecutive variables:</p>

In [6]:
starwars |> select(name:mass)

   name                  height mass
1  Luke Skywalker        172      77.0
2  C-3PO                 167      75.0
3  R2-D2                  96      32.0
4  Darth Vader           202     136.0
5  Leia Organa           150      49.0
6  Owen Lars             178     120.0
7  Beru Whitesun lars    165      75.0
8  R5-D4                  97      32.0
9  Biggs Darklighter     183      84.0
10 Obi-Wan Kenobi        182      77.0
11 Anakin Skywalker      188      84.0
12 Wilhuff Tarkin        180        NA
13 Chewbacca             228     112.0
14 Han Solo              180      80.0
15 Greedo                173      74.0
16 Jabba Desilijic Tiure 175    1358.0
17 Wedge Antilles        170      77.0
18 Jek Tono Porkins      180     110.0
19 Yoda                   66      17.0
20 Palpatine             170      75.0
21 Boba Fett             183      78.2
22 IG-88                 200     140.0
23 Bossk                 190     113.0
24 Lando Calrissian      177      79.0
25 Lobot                 175      79.0
26 Ackbar                180      83.0
27 Mon Mothma            150        NA
28 Arvel Crynyd           NA        NA
29 Wicket Systri Warrick  88      20.0
30 Nien Nunb             160      68.0
⋮  ⋮                     ⋮      ⋮
58 Cordé                 157       NA
59 Cliegg Lars           183       NA
60 Poggle the Lesser     183     80.0
61 Luminara Unduli       170     56.2
62 Barriss Offee         166     50.0
63 Dormé                 165       NA
64 Dooku                 193     80.0
65 Bail Prestor Organa   191       NA
66 Jango Fett            183     79.0
67 Zam Wesell            168     55.0
68 Dexter Jettster       198    102.0
69 Lama Su               229     88.0
70 Taun We               213       NA
71 Jocasta Nu            167       NA
72 Ratts Tyerell          79     15.0
73 R4-P17                 96       NA
74 Wat Tambor            193     48.0
75 San Hill              191       NA
76 Shaak Ti              178     57.0
77 Grievous              216    159.0
78 Tarfful               234    136.0
79 Raymus Antilles       188     79.0
80 Sly Moore             178     48.0
81 Tion Medon            206     80.0
82 Finn                   NA       NA
83 Rey                    NA       NA
84 Poe Dameron            NA       NA
85 BB8                    NA       NA
86 Captain Phasma         NA       NA
87 Padmé Amidala         165     45.0

<p>The <code>!</code> operator negates a selection:</p>

In [7]:
starwars |> select(!(name:mass))

   hair_color    skin_color          eye_color     birth_year sex
1  blond         fair                blue           19.0      male
2  NA            gold                yellow        112.0      none
3  NA            white, blue         red            33.0      none
4  none          white               yellow         41.9      male
5  brown         light               brown          19.0      female
6  brown, grey   light               blue           52.0      male
7  brown         light               blue           47.0      female
8  NA            white, red          red              NA      none
9  black         light               brown          24.0      male
10 auburn, white fair                blue-gray      57.0      male
11 blond         fair                blue           41.9      male
12 auburn, grey  fair                blue           64.0      male
13 brown         unknown             blue          200.0      male
14 brown         fair                brown          29.0      male
15 NA            green               black          44.0      male
16 NA            green-tan, brown    orange        600.0      hermaphroditic
17 brown         fair                hazel          21.0      male
18 brown         fair                blue             NA      male
19 white         green               brown         896.0      male
20 grey          pale                yellow         82.0      male
21 black         fair                brown          31.5      male
22 none          metal               red            15.0      none
23 none          green               red            53.0      male
24 black         dark                brown          31.0      male
25 none          light               blue           37.0      male
26 none          brown mottle        orange         41.0      male
27 auburn        fair                blue           48.0      female
28 brown         fair                brown            NA      male
29 brown         brown               brown           8.0      male
30 none          grey                black            NA      male
⋮  ⋮             ⋮                   ⋮             ⋮          ⋮
58 brown         light               brown          NA        female
59 brown         fair                blue           82        male
60 none          green               yellow         NA        male
61 black         yellow              blue           58        female
62 black         yellow              blue           40        female
63 brown         light               brown          NA        female
64 white         fair                brown         102        male
65 black         tan                 brown          67        male
66 black         tan                 brown          66        male
67 blonde        fair, green, yellow yellow         NA        female
68 none          brown               yellow         NA        male
69 none          grey                black          NA        male
70 none          grey                black          NA        female
71 white         fair                blue           NA        female
72 none          grey, blue          unknown        NA        male
73 none          silver, red         red, blue      NA        none
74 none          green, grey         unknown        NA        male
75 none          grey                gold           NA        male
76 none          red, blue, white    black          NA        female
77 none          brown, white        green, yellow  NA        male
78 brown         brown               blue           NA        male
79 brown         light               brown          NA        male
80 none          pale                white          NA        NA
81 none          grey                black          NA        male
82 black         dark                dark           NA        male
83 brown         light               hazel          NA        female
84 brown         light               brown          NA        male
85 none          none                black          NA        none
86 unknown       unknown             unknown        NA        NA
87 brown         light               brown          46        female
   gender    homeworld    species
1  masculine Tatooine     Human
2  masculine Tatooine     Droid
3  masculine Naboo        Droid
4  masculine Tatooine     Human
5  feminine  Alderaan     Human
6  masculine Tatooine     Human
7  feminine  Tatooine     Human
8  masculine Tatooine     Droid
9  masculine Tatooine     Human
10 masculine Stewjon      Human
11 masculine Tatooine     Human
12 masculine Eriadu       Human
13 masculine Kashyyyk     Wookiee
14 masculine Corellia     Human
15 masculine Rodia        Rodian
16 masculine Nal Hutta    Hutt
17 masculine Corellia     Human
18 masculine Bestine IV   Human
19 masculine NA           Yoda's species
20 masculine Naboo        Human
21 masculine Kamino       Human
22 masculine NA           Droid
23 masculine Trandosha    Trandoshan
24 masculine Socorro      Human
25 masculine Bespin       Human
26 masculine Mon Cala     Mon Calamari
27 feminine  Chandrila    Human
28 masculine NA           Human
29 masculine Endor        Ewok
30 masculine Sullust      Sullustan
⋮  ⋮         ⋮            ⋮
58 feminine  Naboo        Human
59 masculine Tatooine     Human
60 masculine Geonosis     Geonosian
61 feminine  Mirial       Mirialan
62 feminine  Mirial       Mirialan
63 feminine  Naboo        Human
64 masculine Serenno      Human
65 masculine Alderaan     Human
66 masculine Concord Dawn Human
67 feminine  Zolan        Clawdite
68 masculine Ojom         Besalisk
69 masculine Kamino       Kaminoan
70 feminine  Kamino       Kaminoan
71 feminine  Coruscant    Human
72 masculine Aleen Minor  Aleena
73 feminine  NA           Droid
74 masculine Skako        Skakoan
75 masculine Muunilinst   Muun
76 feminine  Shili        Togruta
77 masculine Kalee        Kaleesh
78 masculine Kashyyyk     Wookiee
79 masculine Alderaan     Human
80 NA        Umbara       NA
81 masculine Utapau       Pau'an
82 masculine NA           Human
83 feminine  NA           Human
84 masculine NA           Human
85 masculine NA           Droid
86 NA        NA           NA
87 feminine  Naboo        Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
5  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
6  Attack of the Clones, Revenge of the Sith , A New Hope
7  Attack of the Clones, Revenge of the Sith , A New Hope
8  A New Hope
9  A New Hope
10 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
11 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
12 Revenge of the Sith, A New Hope
13 The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
14 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
15 A New Hope
16 The Phantom Menace, Return of the Jedi, A New Hope
17 The Empire Strikes Back, Return of the Jedi     , A New Hope
18 A New Hope
19 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
20 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
21 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones, Revenge of the Sith
61 Attack of the Clones, Revenge of the Sith
62 Attack of the Clones
63 Attack of the Clones
64 Attack of the Clones, Revenge of the Sith
65 Attack of the Clones, Revenge of the Sith
66 Attack of the Clones
67 Attack of the Clones
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 The Phantom Menace
73 Attack of the Clones, Revenge of the Sith
74 Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones, Revenge of the Sith
77 Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith, A New Hope
80 Attack of the Clones, Revenge of the Sith
81 Revenge of the Sith
82 The Force Awakens
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64 Flitknot speeder
65
66
67 Koro-2 Exodrive airspeeder
68
69
70
71
72
73
74
75
76
77 Tsmeu-6 personal wheel bike
78
79
80
81
82
83
84
85
86
87
   starships
1  X-wing          , Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
11 Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77 Belbullab-22 starfighter
78
79
80
81
82
83
84 T-70 X-wing fighter
85
86
87 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

In [8]:
iris |> select(!c(Sepal.Length, Petal.Length))

    Sepal.Width Petal.Width Species
1   3.5         0.2         setosa
2   3.0         0.2         setosa
3   3.2         0.2         setosa
4   3.1         0.2         setosa
5   3.6         0.2         setosa
6   3.9         0.4         setosa
7   3.4         0.3         setosa
8   3.4         0.2         setosa
9   2.9         0.2         setosa
10  3.1         0.1         setosa
11  3.7         0.2         setosa
12  3.4         0.2         setosa
13  3.0         0.1         setosa
14  3.0         0.1         setosa
15  4.0         0.2         setosa
16  4.4         0.4         setosa
17  3.9         0.4         setosa
18  3.5         0.3         setosa
19  3.8         0.3         setosa
20  3.8         0.3         setosa
21  3.4         0.2         setosa
22  3.7         0.4         setosa
23  3.6         0.2         setosa
24  3.3         0.5         setosa
25  3.4         0.2         setosa
26  3.0         0.2         setosa
27  3.4         0.4         setosa
28  3.5         0.2         setosa
29  3.4         0.2         setosa
30  3.2         0.2         setosa
⋮   ⋮           ⋮           ⋮
121 3.2         2.3         virginica
122 2.8         2.0         virginica
123 2.8         2.0         virginica
124 2.7         1.8         virginica
125 3.3         2.1         virginica
126 3.2         1.8         virginica
127 2.8         1.8         virginica
128 3.0         1.8         virginica
129 2.8         2.1         virginica
130 3.0         1.6         virginica
131 2.8         1.9         virginica
132 3.8         2.0         virginica
133 2.8         2.2         virginica
134 2.8         1.5         virginica
135 2.6         1.4         virginica
136 3.0         2.3         virginica
137 3.4         2.4         virginica
138 3.1         1.8         virginica
139 3.0         1.8         virginica
140 3.1         2.1         virginica
141 3.1         2.4         virginica
142 3.1         2.3         virginica
143 2.7         1.9         virginica
144 3.2         2.3         virginica
145 3.3         2.5         virginica
146 3.0         2.3         virginica
147 2.5         1.9         virginica
148 3.0         2.0         virginica
149 3.4         2.3         virginica
150 3.0         1.8         virginica

In [9]:
iris |> select(!ends_with("Width"))

    Sepal.Length Petal.Length Species
1   5.1          1.4          setosa
2   4.9          1.4          setosa
3   4.7          1.3          setosa
4   4.6          1.5          setosa
5   5.0          1.4          setosa
6   5.4          1.7          setosa
7   4.6          1.4          setosa
8   5.0          1.5          setosa
9   4.4          1.4          setosa
10  4.9          1.5          setosa
11  5.4          1.5          setosa
12  4.8          1.6          setosa
13  4.8          1.4          setosa
14  4.3          1.1          setosa
15  5.8          1.2          setosa
16  5.7          1.5          setosa
17  5.4          1.3          setosa
18  5.1          1.4          setosa
19  5.7          1.7          setosa
20  5.1          1.5          setosa
21  5.4          1.7          setosa
22  5.1          1.5          setosa
23  4.6          1.0          setosa
24  5.1          1.7          setosa
25  4.8          1.9          setosa
26  5.0          1.6          setosa
27  5.0          1.6          setosa
28  5.2          1.5          setosa
29  5.2          1.4          setosa
30  4.7          1.6          setosa
⋮   ⋮            ⋮            ⋮
121 6.9          5.7          virginica
122 5.6          4.9          virginica
123 7.7          6.7          virginica
124 6.3          4.9          virginica
125 6.7          5.7          virginica
126 7.2          6.0          virginica
127 6.2          4.8          virginica
128 6.1          4.9          virginica
129 6.4          5.6          virginica
130 7.2          5.8          virginica
131 7.4          6.1          virginica
132 7.9          6.4          virginica
133 6.4          5.6          virginica
134 6.3          5.1          virginica
135 6.1          5.6          virginica
136 7.7          6.1          virginica
137 6.3          5.6          virginica
138 6.4          5.5          virginica
139 6.0          4.8          virginica
140 6.9          5.4          virginica
141 6.7          5.6          virginica
142 6.9          5.1          virginica
143 5.8          5.1          virginica
144 6.8          5.9          virginica
145 6.7          5.7          virginica
146 6.7          5.2          virginica
147 6.3          5.0          virginica
148 6.5          5.2          virginica
149 6.2          5.4          virginica
150 5.9          5.1          virginica

<p><code>&amp;</code> and <code>|</code> take the intersection or the union of two selections:</p>

In [10]:
iris |> select(starts_with("Petal") & ends_with("Width"))

    Petal.Width
1   0.2
2   0.2
3   0.2
4   0.2
5   0.2
6   0.4
7   0.3
8   0.2
9   0.2
10  0.1
11  0.2
12  0.2
13  0.1
14  0.1
15  0.2
16  0.4
17  0.4
18  0.3
19  0.3
20  0.3
21  0.2
22  0.4
23  0.2
24  0.5
25  0.2
26  0.2
27  0.4
28  0.2
29  0.2
30  0.2
⋮   ⋮
121 2.3
122 2.0
123 2.0
124 1.8
125 2.1
126 1.8
127 1.8
128 1.8
129 2.1
130 1.6
131 1.9
132 2.0
133 2.2
134 1.5
135 1.4
136 2.3
137 2.4
138 1.8
139 1.8
140 2.1
141 2.4
142 2.3
143 1.9
144 2.3
145 2.5
146 2.3
147 1.9
148 2.0
149 2.3
150 1.8

In [11]:
iris |> select(starts_with("Petal") | ends_with("Width"))

    Petal.Length Petal.Width Sepal.Width
1   1.4          0.2         3.5
2   1.4          0.2         3.0
3   1.3          0.2         3.2
4   1.5          0.2         3.1
5   1.4          0.2         3.6
6   1.7          0.4         3.9
7   1.4          0.3         3.4
8   1.5          0.2         3.4
9   1.4          0.2         2.9
10  1.5          0.1         3.1
11  1.5          0.2         3.7
12  1.6          0.2         3.4
13  1.4          0.1         3.0
14  1.1          0.1         3.0
15  1.2          0.2         4.0
16  1.5          0.4         4.4
17  1.3          0.4         3.9
18  1.4          0.3         3.5
19  1.7          0.3         3.8
20  1.5          0.3         3.8
21  1.7          0.2         3.4
22  1.5          0.4         3.7
23  1.0          0.2         3.6
24  1.7          0.5         3.3
25  1.9          0.2         3.4
26  1.6          0.2         3.0
27  1.6          0.4         3.4
28  1.5          0.2         3.5
29  1.4          0.2         3.4
30  1.6          0.2         3.2
⋮   ⋮            ⋮           ⋮
121 5.7          2.3         3.2
122 4.9          2.0         2.8
123 6.7          2.0         2.8
124 4.9          1.8         2.7
125 5.7          2.1         3.3
126 6.0          1.8         3.2
127 4.8          1.8         2.8
128 4.9          1.8         3.0
129 5.6          2.1         2.8
130 5.8          1.6         3.0
131 6.1          1.9         2.8
132 6.4          2.0         3.8
133 5.6          2.2         2.8
134 5.1          1.5         2.8
135 5.6          1.4         2.6
136 6.1          2.3         3.0
137 5.6          2.4         3.4
138 5.5          1.8         3.1
139 4.8          1.8         3.0
140 5.4          2.1         3.1
141 5.6          2.4         3.1
142 5.1          2.3         3.1
143 5.1          1.9         2.7
144 5.9          2.3         3.2
145 5.7          2.5         3.3
146 5.2          2.3         3.0
147 5.0          1.9         2.5
148 5.2          2.0         3.0
149 5.4          2.3         3.4
150 5.1          1.8         3.0

<p>To take the difference between two selections, combine the <code>&amp;</code> and <code>!</code> operators:</p>

In [12]:
iris |> select(starts_with("Petal") & !ends_with("Width"))

    Petal.Length
1   1.4
2   1.4
3   1.3
4   1.5
5   1.4
6   1.7
7   1.4
8   1.5
9   1.4
10  1.5
11  1.5
12  1.6
13  1.4
14  1.1
15  1.2
16  1.5
17  1.3
18  1.4
19  1.7
20  1.5
21  1.7
22  1.5
23  1.0
24  1.7
25  1.9
26  1.6
27  1.6
28  1.5
29  1.4
30  1.6
⋮   ⋮
121 5.7
122 4.9
123 6.7
124 4.9
125 5.7
126 6.0
127 4.8
128 4.9
129 5.6
130 5.8
131 6.1
132 6.4
133 5.6
134 5.1
135 5.6
136 6.1
137 5.6
138 5.5
139 4.8
140 5.4
141 5.6
142 5.1
143 5.1
144 5.9
145 5.7
146 5.2
147 5.0
148 5.2
149 5.4
150 5.1

# <h2 id="see-also">See also<a href="#see-also"></a></h2>

<p>Other single table verbs:
<code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/reframe.html">reframe</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a>()</code></p>