<h1>Keep rows that match a condition</h1>

<small>Source: <a href="https://github.com/tidyverse/dplyr/blob/pkgdown-v1.1.4/R/filter.R"><code>R/filter.R</code></a></small>
<div><code>filter.Rd</code></div>

<p>The <code>filter()</code> function is used to subset a data frame,
retaining all rows that satisfy your conditions.
To be retained, the row must produce a value of <code>TRUE</code> for all conditions.
Note that when a condition evaluates to <code>NA</code> the row will be dropped, unlike base subsetting with <code>[</code>.</p>

# <h2 id="ref-usage">Usage</h2>

<pre><code>filter(.data, ..., .by = NULL, .preserve = FALSE)</code></pre>

# <h2 id="arguments">Arguments</h2>

<dl>

<dt id="arg--data">.data</dt>
<dd><p>A data frame, data frame extension (e.g. a tibble), or a
lazy data frame (e.g. from dbplyr or dtplyr). See <em>Methods</em>, below, for more details.</p></dd>

<dt id="arg--">...</dt>
<dd><p>&lt;<code><a href="https://rlang.r-lib.org/reference/args_data_masking.html">data-masking</a></code>&gt; Expressions that
return a logical value, and are defined in terms of the variables in
<code>.data</code>. If multiple expressions are included, they are combined with the <code>&amp;</code> operator. Only rows for which all conditions evaluate to <code>TRUE</code> are kept.</p></dd>

<dt id="arg--by">.by</dt>
<dd><p>&lt;<code><a href="dplyr_tidy_select.html">tidy-select</a></code>&gt; Optionally, a selection of columns to group by for just this operation, functioning as an alternative to <code><a href="group_by.html">group_by()</a></code>. For details and examples, see <a href="dplyr_by.html">?dplyr_by</a>.</p></dd>

<dt id="arg--preserve">.preserve</dt>
<dd><p>Relevant when the <code>.data</code> input is grouped.
If <code>.preserve = FALSE</code> (the default), the grouping structure is recalculated based on the resulting data, otherwise the grouping is kept as is.</p></dd>

# <h2 id="value">Value</h2>

<p>An object of the same type as <code>.data</code>. The output has the following properties:</p>

<ul>
<li><p>Rows are a subset of the input, but appear in the same order.</p></li>
<li><p>Columns are not modified.</p></li>
<li><p>The number of groups may be reduced (if <code>.preserve</code> is not <code>TRUE</code>).</p></li>
<li><p>Data frame attributes are preserved.</p></li>
</ul>

# <h2 id="details">Details</h2>
    
<p>The <code>filter()</code> function is used to subset the rows of
<code>.data</code>, applying the expressions in <code>...</code> to the column values to determine which rows should be retained. It can be applied to both grouped and ungrouped data (see <code><a href="group_by.html">group_by()</a></code> and <code><a href="group_by.html">ungroup()</a></code>). However, dplyr is not yet smart enough to optimise the filtering operation on grouped datasets that do not need grouped calculations. For this reason, filtering is often considerably faster on ungrouped data.</p>

# <h2 id="useful-filter-functions">Useful filter functions</h2>

<p>There are many functions and operators that are useful when constructing the expressions used to filter the data:</p>

<ul>
<li><p><code><a href="https://rdrr.io/r/base/Comparison.html">==</a></code>, <code>&gt;</code>, <code>&gt;=</code> etc</p></li>
<li><p><code>&amp;</code>, <code><a href="https://rdrr.io/r/base/Logic.html">|</a></code>, <code><a href="https://rdrr.io/r/base/Logic.html">!</a></code>, <code><a href="https://rdrr.io/r/base/Logic.html">xor()</a></code></p></li>
<li><p><code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/between.html">between()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/near.html">near()</a></code></p></li>
</ul>

# <h2 id="grouped-tibbles">Grouped tibbles</h2>

<p>Because filtering expressions are computed within groups, they may
yield different results on grouped tibbles. This will be the case
as soon as an aggregating, lagging, or ranking function is involved. Compare this ungrouped filtering:</p>

<pre><code></a>starwars %&gt;% filter(mass &gt; mean(mass, >na.rm = TRUE))</code></pre>

<p>With the grouped equivalent:</p>

<pre><code></a>starwars %&gt;% group_by(gender) %&gt;% filter(mass &gt; mean(mass, >na.rm = TRUE))</code></pre>

<p>In the ungrouped version, <code>filter()</code> compares the value of <code>mass</code> in each row to the global average (taken over the whole data set), keeping only the rows with <code>mass</code> greater than this global average. In contrast, the grouped version calculates the average mass separately for each <code>gender</code> group, and keeps rows with <code>mass</code> greater than the relevant within-gender average.</p>

# <h2 id="methods">Methods</h2>

<p>This function is a <strong>generic</strong>, which means that packages can provide implementations (methods) for other classes. See the documentation of individual methods for extra arguments and differences in behaviour.</p>

<p>The following methods are currently available in loaded packages:
dbplyr (<code><a href="https://dbplyr.tidyverse.org/reference/filter.tbl_lazy.html">tbl_lazy</a></code>), dplyr (<code>data.frame</code>, <code>ts</code>).</p>

# <h2 id="see-also">See also</h2>

<p>Other single table verbs:
<code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/reframe.html">reframe</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/select.html">select</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a>()</code></p></div>

# <h2 id="ref-examples">Examples</h2>

In [1]:
library(tidyverse)

# Filtering by one criterion
filter(starwars, species == "Human")

── Attaching packages ────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   1.1.0
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ───────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

   name                height mass  hair_color    skin_color eye_color
1  Luke Skywalker      172     77.0 blond         fair       blue
2  Darth Vader         202    136.0 none          white      yellow
3  Leia Organa         150     49.0 brown         light      brown
4  Owen Lars           178    120.0 brown, grey   light      blue
5  Beru Whitesun lars  165     75.0 brown         light      blue
6  Biggs Darklighter   183     84.0 black         light      brown
7  Obi-Wan Kenobi      182     77.0 auburn, white fair       blue-gray
8  Anakin Skywalker    188     84.0 blond         fair       blue
9  Wilhuff Tarkin      180       NA auburn, grey  fair       blue
10 Han Solo            180     80.0 brown         fair       brown
11 Wedge Antilles      170     77.0 brown         fair       hazel
12 Jek Tono Porkins    180    110.0 brown         fair       blue
13 Palpatine           170     75.0 grey          pale       yellow
14 Boba Fett           183     78.2 black         fair       brown
15 Lando Calrissian    177     79.0 black         dark       brown
16 Lobot               175     79.0 none          light      blue
17 Mon Mothma          150       NA auburn        fair       blue
18 Arvel Crynyd         NA       NA brown         fair       brown
19 Qui-Gon Jinn        193     89.0 brown         fair       blue
20 Finis Valorum       170       NA blond         fair       blue
21 Shmi Skywalker      163       NA black         fair       brown
22 Mace Windu          188     84.0 none          dark       brown
23 Gregar Typho        185     85.0 black         dark       brown
24 Cordé               157       NA brown         light      brown
25 Cliegg Lars         183       NA brown         fair       blue
26 Dormé               165       NA brown         light      brown
27 Dooku               193     80.0 white         fair       brown
28 Bail Prestor Organa 191       NA black         tan        brown
29 Jango Fett          183     79.0 black         tan        brown
30 Jocasta Nu          167       NA white         fair       blue
31 Raymus Antilles     188     79.0 brown         light      brown
32 Finn                 NA       NA black         dark       dark
33 Rey                  NA       NA brown         light      hazel
34 Poe Dameron          NA       NA brown         light      brown
35 Padmé Amidala       165     45.0 brown         light      brown
   birth_year sex    gender    homeworld    species
1   19.0      male   masculine Tatooine     Human
2   41.9      male   masculine Tatooine     Human
3   19.0      female feminine  Alderaan     Human
4   52.0      male   masculine Tatooine     Human
5   47.0      female feminine  Tatooine     Human
6   24.0      male   masculine Tatooine     Human
7   57.0      male   masculine Stewjon      Human
8   41.9      male   masculine Tatooine     Human
9   64.0      male   masculine Eriadu       Human
10  29.0      male   masculine Corellia     Human
11  21.0      male   masculine Corellia     Human
12    NA      male   masculine Bestine IV   Human
13  82.0      male   masculine Naboo        Human
14  31.5      male   masculine Kamino       Human
15  31.0      male   masculine Socorro      Human
16  37.0      male   masculine Bespin       Human
17  48.0      female feminine  Chandrila    Human
18    NA      male   masculine NA           Human
19  92.0      male   masculine NA           Human
20  91.0      male   masculine Coruscant    Human
21  72.0      female feminine  Tatooine     Human
22  72.0      male   masculine Haruun Kal   Human
23    NA      male   masculine Naboo        Human
24    NA      female feminine  Naboo        Human
25  82.0      male   masculine Tatooine     Human
26    NA      female feminine  Naboo        Human
27 102.0      male   masculine Serenno      Human
28  67.0      male   masculine Alderaan     Human
29  66.0      male   masculine Concord Dawn Human
30    NA      female feminine  Coruscant    Human
31    NA      male   masculine Alderaan     Human
32    NA      male   masculine NA           Human
33    NA      female feminine  NA           Human
34    NA      male   masculine NA           Human
35  46.0      female feminine  Naboo        Human
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
2  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
3  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  Attack of the Clones, Revenge of the Sith , A New Hope
5  Attack of the Clones, Revenge of the Sith , A New Hope
6  A New Hope
7  The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi     , A New Hope
8  Attack of the Clones, The Phantom Menace  , Revenge of the Sith
9  Revenge of the Sith, A New Hope
10 The Empire Strikes Back, Return of the Jedi     , A New Hope             , The Force Awakens
11 The Empire Strikes Back, Return of the Jedi     , A New Hope
12 A New Hope
13 The Empire Strikes Back, Attack of the Clones   , The Phantom Menace     , Revenge of the Sith    , Return of the Jedi
14 The Empire Strikes Back, Attack of the Clones   , Return of the Jedi
15 The Empire Strikes Back, Return of the Jedi
16 The Empire Strikes Back
17 Return of the Jedi
18 Return of the Jedi
19 The Phantom Menace
20 The Phantom Menace
21 Attack of the Clones, The Phantom Menace
22 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
23 Attack of the Clones
24 Attack of the Clones
25 Attack of the Clones
26 Attack of the Clones
27 Attack of the Clones, Revenge of the Sith
28 Attack of the Clones, Revenge of the Sith
29 Attack of the Clones
30 Attack of the Clones
31 Revenge of the Sith, A New Hope
32 The Force Awakens
33 The Force Awakens
34 The Force Awakens
35 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
   vehicles
1  Snowspeeder          , Imperial Speeder Bike
2
3  Imperial Speeder Bike
4
5
6
7  Tribubble bongo
8  Zephyr-G swoop bike, XJ-6 airspeeder
9
10
11 Snowspeeder
12
13
14
15
16
17
18
19 Tribubble bongo
20
21
22
23
24
25
26
27 Flitknot speeder
28
29
30
31
32
33
34
35
   starships
1  X-wing          , Imperial shuttle
2  TIE Advanced x1
3
4
5
6  X-wing
7  Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
8  Trade Federation cruiser, Jedi Interceptor        , Naboo fighter
9
10 Millennium Falcon, Imperial shuttle
11 X-wing
12 X-wing
13
14 Slave 1
15 Millennium Falcon
16
17
18 A-wing
19
20
21
22
23 Naboo fighter
24
25
26
27
28
29
30
31
32
33
34 T-70 X-wing fighter
35 H-type Nubian yacht, Naboo star skiff   , Naboo fighter

In [2]:
filter(starwars, mass > 1000)

  name                  height mass hair_color skin_color       eye_color
1 Jabba Desilijic Tiure 175    1358 NA         green-tan, brown orange
  birth_year sex            gender    homeworld species
1 600        hermaphroditic masculine Nal Hutta Hutt
  films                                                      vehicles starships
1 The Phantom Menace, Return of the Jedi, A New Hope

In [3]:
# Filtering by multiple criteria within a single logical expression
filter(starwars, hair_color == "none" & eye_color == "black")

  name       height mass hair_color skin_color       eye_color birth_year
1 Nien Nunb  160    68   none       grey             black     NA
2 Gasgano    122    NA   none       white, blue      black     NA
3 Kit Fisto  196    87   none       green            black     NA
4 Plo Koon   188    80   none       orange           black     22
5 Lama Su    229    88   none       grey             black     NA
6 Taun We    213    NA   none       grey             black     NA
7 Shaak Ti   178    57   none       red, blue, white black     NA
8 Tion Medon 206    80   none       grey             black     NA
9 BB8         NA    NA   none       none             black     NA
  sex    gender    homeworld   species
1 male   masculine Sullust     Sullustan
2 male   masculine Troiken     Xexto
3 male   masculine Glee Anselm Nautolan
4 male   masculine Dorin       Kel Dor
5 male   masculine Kamino      Kaminoan
6 female feminine  Kamino      Kaminoan
7 female feminine  Shili       Togruta
8 male   masculine Utapau      Pau'an
9 none   masculine NA          Droid
  films                                                            vehicles
1 Return of the Jedi
2 The Phantom Menace
3 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
4 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
5 Attack of the Clones
6 Attack of the Clones
7 Attack of the Clones, Revenge of the Sith
8 Revenge of the Sith
9 The Force Awakens
  starships
1 Millennium Falcon
2
3
4 Jedi starfighter
5
6
7
8
9

In [4]:
filter(starwars, hair_color == "none" | eye_color == "black")

   name              height mass hair_color skin_color          eye_color
1  Darth Vader       202    136  none       white               yellow
2  Greedo            173     74  NA         green               black
3  IG-88             200    140  none       metal               red
4  Bossk             190    113  none       green               red
5  Lobot             175     79  none       light               blue
6  Ackbar            180     83  none       brown mottle        orange
7  Nien Nunb         160     68  none       grey                black
8  Nute Gunray       191     90  none       mottled green       red
9  Jar Jar Binks     196     66  none       orange              orange
10 Roos Tarpals      224     82  none       grey                orange
11 Rugor Nass        206     NA  none       green               orange
12 Sebulba           112     40  none       grey, red           orange
13 Darth Maul        175     80  none       red                 yellow
14 Bib Fortuna       180     NA  none       pale                pink
15 Ayla Secura       178     55  none       blue                hazel
16 Dud Bolt           94     45  none       blue, grey          yellow
17 Gasgano           122     NA  none       white, blue         black
18 Ben Quadinaros    163     65  none       grey, green, yellow orange
19 Mace Windu        188     84  none       dark                brown
20 Kit Fisto         196     87  none       green               black
21 Adi Gallia        184     50  none       dark                blue
22 Saesee Tiin       188     NA  none       pale                orange
23 Yarael Poof       264     NA  none       white               yellow
24 Plo Koon          188     80  none       orange              black
25 Mas Amedda        196     NA  none       blue                blue
26 Poggle the Lesser 183     80  none       green               yellow
27 Dexter Jettster   198    102  none       brown               yellow
28 Lama Su           229     88  none       grey                black
29 Taun We           213     NA  none       grey                black
30 Ratts Tyerell      79     15  none       grey, blue          unknown
31 R4-P17             96     NA  none       silver, red         red, blue
32 Wat Tambor        193     48  none       green, grey         unknown
33 San Hill          191     NA  none       grey                gold
34 Shaak Ti          178     57  none       red, blue, white    black
35 Grievous          216    159  none       brown, white        green, yellow
36 Sly Moore         178     48  none       pale                white
37 Tion Medon        206     80  none       grey                black
38 BB8                NA     NA  none       none                black
   birth_year sex    gender    homeworld      species
1  41.9       male   masculine Tatooine       Human
2  44.0       male   masculine Rodia          Rodian
3  15.0       none   masculine NA             Droid
4  53.0       male   masculine Trandosha      Trandoshan
5  37.0       male   masculine Bespin         Human
6  41.0       male   masculine Mon Cala       Mon Calamari
7    NA       male   masculine Sullust        Sullustan
8    NA       male   masculine Cato Neimoidia Neimodian
9  52.0       male   masculine Naboo          Gungan
10   NA       male   masculine Naboo          Gungan
11   NA       male   masculine Naboo          Gungan
12   NA       male   masculine Malastare      Dug
13 54.0       male   masculine Dathomir       Zabrak
14   NA       male   masculine Ryloth         Twi'lek
15 48.0       female feminine  Ryloth         Twi'lek
16   NA       male   masculine Vulpter        Vulptereen
17   NA       male   masculine Troiken        Xexto
18   NA       male   masculine Tund           Toong
19 72.0       male   masculine Haruun Kal     Human
20   NA       male   masculine Glee Anselm    Nautolan
21   NA       female feminine  Coruscant      Tholothian
22   NA       male   masculine Iktotch        Iktotchi
23   NA       male   masculine Quermia        Quermian
24 22.0       male   masculine Dorin          Kel Dor
25   NA       male   masculine Champala       Chagrian
26   NA       male   masculine Geonosis       Geonosian
27   NA       male   masculine Ojom           Besalisk
28   NA       male   masculine Kamino         Kaminoan
29   NA       female feminine  Kamino         Kaminoan
30   NA       male   masculine Aleen Minor    Aleena
31   NA       none   feminine  NA             Droid
32   NA       male   masculine Skako          Skakoan
33   NA       male   masculine Muunilinst     Muun
34   NA       female feminine  Shili          Togruta
35   NA       male   masculine Kalee          Kaleesh
36   NA       NA     NA        Umbara         NA
37   NA       male   masculine Utapau         Pau'an
38   NA       none   masculine NA             Droid
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
2  A New Hope
3  The Empire Strikes Back
4  The Empire Strikes Back
5  The Empire Strikes Back
6  Return of the Jedi, The Force Awakens
7  Return of the Jedi
8  Attack of the Clones, The Phantom Menace  , Revenge of the Sith
9  Attack of the Clones, The Phantom Menace
10 The Phantom Menace
11 The Phantom Menace
12 The Phantom Menace
13 The Phantom Menace
14 Return of the Jedi
15 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
16 The Phantom Menace
17 The Phantom Menace
18 The Phantom Menace
19 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
20 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
21 The Phantom Menace , Revenge of the Sith
22 The Phantom Menace , Revenge of the Sith
23 The Phantom Menace
24 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
25 Attack of the Clones, The Phantom Menace
26 Attack of the Clones, Revenge of the Sith
27 Attack of the Clones
28 Attack of the Clones
29 Attack of the Clones
30 The Phantom Menace
31 Attack of the Clones, Revenge of the Sith
32 Attack of the Clones
33 Attack of the Clones
34 Attack of the Clones, Revenge of the Sith
35 Revenge of the Sith
36 Attack of the Clones, Revenge of the Sith
37 Revenge of the Sith
38 The Force Awakens
   vehicles                    starships
1                              TIE Advanced x1
2
3
4
5
6
7                              Millennium Falcon
8
9
10
11
12
13 Sith speeder                Scimitar
14
15
16
17
18
19
20
21
22
23
24                             Jedi starfighter
25
26
27
28
29
30
31
32
33
34
35 Tsmeu-6 personal wheel bike Belbullab-22 starfighter
36
37
38

In [5]:
# When multiple expressions are used, they are combined using &
filter(starwars, hair_color == "none", eye_color == "black")

  name       height mass hair_color skin_color       eye_color birth_year
1 Nien Nunb  160    68   none       grey             black     NA
2 Gasgano    122    NA   none       white, blue      black     NA
3 Kit Fisto  196    87   none       green            black     NA
4 Plo Koon   188    80   none       orange           black     22
5 Lama Su    229    88   none       grey             black     NA
6 Taun We    213    NA   none       grey             black     NA
7 Shaak Ti   178    57   none       red, blue, white black     NA
8 Tion Medon 206    80   none       grey             black     NA
9 BB8         NA    NA   none       none             black     NA
  sex    gender    homeworld   species
1 male   masculine Sullust     Sullustan
2 male   masculine Troiken     Xexto
3 male   masculine Glee Anselm Nautolan
4 male   masculine Dorin       Kel Dor
5 male   masculine Kamino      Kaminoan
6 female feminine  Kamino      Kaminoan
7 female feminine  Shili       Togruta
8 male   masculine Utapau      Pau'an
9 none   masculine NA          Droid
  films                                                            vehicles
1 Return of the Jedi
2 The Phantom Menace
3 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
4 Attack of the Clones, The Phantom Menace  , Revenge of the Sith
5 Attack of the Clones
6 Attack of the Clones
7 Attack of the Clones, Revenge of the Sith
8 Revenge of the Sith
9 The Force Awakens
  starships
1 Millennium Falcon
2
3
4 Jedi starfighter
5
6
7
8
9

In [6]:
# The filtering operation may yield different results on grouped
# tibbles because the expressions are computed within groups.
#
# The following filters rows where `mass` is greater than the
# global average:
starwars |> filter(mass > mean(mass, na.rm = TRUE))

   name                  height mass hair_color  skin_color       eye_color
1  Darth Vader           202     136 none        white            yellow
2  Owen Lars             178     120 brown, grey light            blue
3  Chewbacca             228     112 brown       unknown          blue
4  Jabba Desilijic Tiure 175    1358 NA          green-tan, brown orange
5  Jek Tono Porkins      180     110 brown       fair             blue
6  IG-88                 200     140 none        metal            red
7  Bossk                 190     113 none        green            red
8  Dexter Jettster       198     102 none        brown            yellow
9  Grievous              216     159 none        brown, white     green, yellow
10 Tarfful               234     136 brown       brown            blue
   birth_year sex            gender    homeworld  species
1   41.9      male           masculine Tatooine   Human
2   52.0      male           masculine Tatooine   Human
3  200.0      male           masculine Kashyyyk   Wookiee
4  600.0      hermaphroditic masculine Nal Hutta  Hutt
5     NA      male           masculine Bestine IV Human
6   15.0      none           masculine NA         Droid
7   53.0      male           masculine Trandosha  Trandoshan
8     NA      male           masculine Ojom       Besalisk
9     NA      male           masculine Kalee      Kaleesh
10    NA      male           masculine Kashyyyk   Wookiee
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
2  Attack of the Clones, Revenge of the Sith , A New Hope
3  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
4  The Phantom Menace, Return of the Jedi, A New Hope
5  A New Hope
6  The Empire Strikes Back
7  The Empire Strikes Back
8  Attack of the Clones
9  Revenge of the Sith
10 Revenge of the Sith
   vehicles                    starships
1                              TIE Advanced x1
2
3  AT-ST                       Millennium Falcon, Imperial shuttle
4
5                              X-wing
6
7
8
9  Tsmeu-6 personal wheel bike Belbullab-22 starfighter
10

In [7]:
# Whereas this keeps rows with `mass` greater than the gender
# average:
starwars |> group_by(gender) |> filter(mass > mean(mass, na.rm = TRUE))

   name                  height mass   hair_color  skin_color
1  Darth Vader           202     136.0 none        white
2  Owen Lars             178     120.0 brown, grey light
3  Beru Whitesun lars    165      75.0 brown       light
4  Chewbacca             228     112.0 brown       unknown
5  Jabba Desilijic Tiure 175    1358.0 NA          green-tan, brown
6  Jek Tono Porkins      180     110.0 brown       fair
7  IG-88                 200     140.0 none        metal
8  Bossk                 190     113.0 none        green
9  Ayla Secura           178      55.0 none        blue
10 Luminara Unduli       170      56.2 black       yellow
11 Zam Wesell            168      55.0 blonde      fair, green, yellow
12 Shaak Ti              178      57.0 none        red, blue, white
13 Grievous              216     159.0 none        brown, white
14 Tarfful               234     136.0 brown       brown
   eye_color     birth_year sex            gender    homeworld  species
1  yellow         41.9      male           masculine Tatooine   Human
2  blue           52.0      male           masculine Tatooine   Human
3  blue           47.0      female         feminine  Tatooine   Human
4  blue          200.0      male           masculine Kashyyyk   Wookiee
5  orange        600.0      hermaphroditic masculine Nal Hutta  Hutt
6  blue             NA      male           masculine Bestine IV Human
7  red            15.0      none           masculine NA         Droid
8  red            53.0      male           masculine Trandosha  Trandoshan
9  hazel          48.0      female         feminine  Ryloth     Twi'lek
10 blue           58.0      female         feminine  Mirial     Mirialan
11 yellow           NA      female         feminine  Zolan      Clawdite
12 black            NA      female         feminine  Shili      Togruta
13 green, yellow    NA      male           masculine Kalee      Kaleesh
14 blue             NA      male           masculine Kashyyyk   Wookiee
   films
1  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope
2  Attack of the Clones, Revenge of the Sith , A New Hope
3  Attack of the Clones, Revenge of the Sith , A New Hope
4  The Empire Strikes Back, Revenge of the Sith    , Return of the Jedi     , A New Hope             , The Force Awakens
5  The Phantom Menace, Return of the Jedi, A New Hope
6  A New Hope
7  The Empire Strikes Back
8  The Empire Strikes Back
9  Attack of the Clones, The Phantom Menace  , Revenge of the Sith
10 Attack of the Clones, Revenge of the Sith
11 Attack of the Clones
12 Attack of the Clones, Revenge of the Sith
13 Revenge of the Sith
14 Revenge of the Sith
   vehicles                    starships
1                              TIE Advanced x1
2
3
4  AT-ST                       Millennium Falcon, Imperial shuttle
5
6                              X-wing
7
8
9
10
11 Koro-2 Exodrive airspeeder
12
13 Tsmeu-6 personal wheel bike Belbullab-22 starfighter
14