<h1>Bar Charts in Python</h1>
How to make Bar Charts in Python with Plotly.

## <h3 id="bar-chart-with-plotly-express">Bar chart with Plotly Express</h3>

<p><a href="https://plotly.com/python/plotly-express/">Plotly Express</a> is the easy-to-use, high-level interface to Plotly, which <a href="https://plotly.com/python/px-arguments/">operates on a variety of types of data</a> and produces <a href="https://plotly.com/python/styling-plotly-express/">easy-to-style figures</a>.</p>

<p>With <code>px.bar</code>, <strong>each row of the DataFrame is represented as a rectangular mark</strong>. To aggregate multiple data points into the same rectangular mark, please refer to the <a href="https://plotly.com/python/histograms">histogram documentation</a>.</p>

<p>In the example below, there is only a single row of data per year, so a single bar is displayed per year.</p>

In [1]:
import plotly.express as px
data_canada = px.data.gapminder().query("country == 'Canada'")
fig = px.bar(data_canada, x='year', y='pop')
fig.show()

### <h4 id="bar-charts-with-long-format-data">Bar charts with Long Format Data</h4>

<p>Long-form data has one row per observation, and one column per variable. This is suitable for storing and displaying multivariate data i.e. with dimension greater than 2. This format is sometimes called "tidy".</p>

<p>To learn more about how to provide a specific form of column-oriented data to 2D-Cartesian Plotly Express functions such as <code>px.bar</code>, see the <a href="https://plotly.com/python/wide-form/">Plotly Express Wide-Form Support in Python
documentation</a>.</p>

<p>For  detailed column-input-format documentation, see the <a href="https://plotly.com/python/px-arguments/">Plotly Express Arguments documentation</a>.</p>

In [5]:
import plotly.express as px

long_df = px.data.medals_long()

long_df

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [6]:
fig = px.bar(long_df, x="nation", y="count", color="medal", title="Long-Form Input")
fig.show()

### <h4 id="bar-charts-with-wide-format-data">Bar charts with Wide Format Data</h4>

<p>Wide-form data has one row per value of one of the first variable, and one column per value of the second variable. This is suitable for storing and displaying 2-dimensional data.</p>

In [7]:
import plotly.express as px

wide_df = px.data.medals_wide()

wide_df

        nation  gold  silver  bronze
0  South Korea    24      13      11
1        China    10      15       8
2       Canada     9      12      12

In [8]:
fig = px.bar(wide_df, x="nation", y=["gold", "silver", "bronze"], title="Wide-Form Input")
fig.show()

## <h3 id="colored-bars">Colored Bars</h3>

<p>The bar plot can be customized using keyword arguments, for example to use <a href="https://plotly.com/python/colorscales/">continuous color</a>, as below, or <a href="https://plotly.com/python/discrete-color/">discrete color</a>, as above.</p>

In [35]:
import plotly.express as px

df = px.data.gapminder().query("country == 'Canada'")
fig = px.bar(df, x='year', y='pop',
             hover_data=['lifeExp', 'gdpPercap'], color='lifeExp', color_continuous_scale=['#FFA15A', '#EF553B', '#AB63FA', '#636EFA', '#00CC96'],
             labels={'pop':'population of Canada'}, height=400)
fig.show()

In [14]:
import plotly.express as px

df = px.data.gapminder().query("continent == 'Oceania'")
fig = px.bar(df, x='year', y='pop',
             hover_data=['lifeExp', 'gdpPercap'], color='country',
             labels={'pop':'population of Oceania'}, height=400)
fig.show()

## <h3 id="stacked-vs-grouped-bars">Stacked vs Grouped Bars</h3>

<p>When several rows share the same value of <code>x</code> (here Female or Male), the rectangles are stacked on top of one another by default.</p>

In [15]:
import plotly.express as px
df = px.data.tips()
fig = px.bar(df, x="sex", y="total_bill", color='time')
fig.show()

<p>The default stacked bar chart behavior can be changed to grouped (also known as clustered) using the <code>barmode</code> argument:</p>

In [18]:
import plotly.express as px
df = px.data.tips()
fig = px.bar(df, x="sex", y="total_bill",
             color='smoker', barmode='group',
             height=400)
fig.show()

## <h3 id="aggregating-into-single-colored-bars">Aggregating into Single Colored Bars</h3>

<p>As noted above <code>px.bar()</code> will result in <strong>one rectangle drawn per row of input</strong>. This can sometimes result in a striped look as in the examples above. To combine these rectangles into one per color per position, you can use <code>px.histogram()</code>, which has <a href="https://plotly.com/python/histogram">its own detailed documentation page</a>.</p>

<blockquote><p><code>px.bar</code> and <code>px.histogram</code> are designed  to be nearly interchangeable in their call signatures, so as to be able to switch between aggregated and disaggregated bar representations.</p>
</blockquote>

In [19]:
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="sex", y="total_bill",
             color='smoker', barmode='group',
             height=400)
fig.show()

<p><code>px.histogram()</code> will aggregate <code>y</code> values by summing them by default, but the <code>histfunc</code> argument can be used to set this to <code>avg</code> to create what is sometimes called a "barplot" which summarizes the central tendency of a dataset, rather than visually representing the totality of the dataset.</p>

<blockquote><p>Warning: when using <code>histfunc</code>s other than <code>"sum"</code> or <code>"count"</code> it can be very misleading to use a <code>barmode</code> other than <code>"group"</code>, as stacked bars in effect represent the sum of the bar heights, and summing averages is rarely a reasonable thing to visualize.</p>
</blockquote>

In [20]:
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="sex", y="total_bill",
             color='smoker', barmode='group',
             histfunc='avg',
             height=400)
fig.show()

## <h3 id="bar-charts-with-text">Bar Charts with Text</h3>

<p><em>New in v5.5</em></p>
<p>You can add text to bars using the <code>text_auto</code> argument. Setting it to <code>True</code> will display the values on the bars, and setting it to a <code>d3-format</code> formatting string will control the output format.</p>

In [21]:
import plotly.express as px
df = px.data.medals_long()

fig = px.bar(df, x="medal", y="count", color="nation", text_auto=True)
fig.show()

<p>The <code>text</code> argument can be used to display arbitrary text on the bars:</p>

In [22]:
import plotly.express as px
df = px.data.medals_long()

fig = px.bar(df, x="medal", y="count", color="nation", text="nation")
fig.show()

<p>By default, Plotly will scale and rotate text labels to maximize the number of visible labels, which can result in a variety of text angles and sizes and positions in the same figure. The <code>textfont</code>, <code>textposition</code> and <code>textangle</code> trace attributes can be used to control these.</p>

<p>Here is an example of the default behavior:</p>

In [23]:
import plotly.express as px

df = px.data.gapminder().query("continent == 'Europe' and year == 2007 and pop > 2.e6")
fig = px.bar(df, y='pop', x='country', text_auto='.2s',
            title="Default: various text sizes, positions and angles")
fig.show()

<p>Here is the same data with less variation in text formatting. Note that <code>textfont_size</code> will set the <em>maximum</em> size. The <code>layout.uniformtext</code> attribute can be used to guarantee that all text labels are the same size. See the <a href="https://plotly.com/python/text-and-annotations/">documentation on text and annotations</a> for details.</p>

<p>The <code>cliponaxis</code> attribute is set to <code>False</code> in the example below to ensure that the outside text on the tallest bar is allowed to render outside of the plotting area.</p>

In [24]:
import plotly.express as px

df = px.data.gapminder().query("continent == 'Europe' and year == 2007 and pop > 2.e6")
fig = px.bar(df, y='pop', x='country', text_auto='.2s',
            title="Controlled text sizes, positions and angles")
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.show()

## <h3 id="basic-bar-charts-with-plotlygraphobjects">Basic Bar Charts with plotly.graph_objects</h4>

<p>If Plotly Express does not provide a good starting point, it is also possible to use <a href="https://plotly.com/python/graph-objects/">the more generic <code>go.Bar</code> class from <code>plotly.graph_objects</code></a>.</p>

In [40]:
import plotly.graph_objects as go
animals=['giraffes', 'orangutans', 'monkeys']

fig = go.Figure([go.Bar(x=animals, y=[20, 14, 23], marker_color=px.colors.qualitative.D3[0])])
fig.show()

### <h4 id="grouped-bar-chart">Grouped Bar Chart</h4>

<p>Customize the figure using <code>fig.update</code>.</p>

In [44]:
import plotly.graph_objects as go
animals=['giraffes', 'orangutans', 'monkeys']

fig = go.Figure(data=[
    go.Bar(name='SF Zoo', x=animals, y=[20, 14, 23], marker_color=px.colors.qualitative.D3[0]),
    go.Bar(name='LA Zoo', x=animals, y=[12, 18, 29], marker_color=px.colors.qualitative.D3[1])
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()

## <h3 id="stacked-bar-chart">Stacked Bar Chart</h3>

In [46]:
import plotly.graph_objects as go
animals=['giraffes', 'orangutans', 'monkeys']

fig = go.Figure(data=[
    go.Bar(name='SF Zoo', x=animals, y=[20, 14, 23], marker_color=px.colors.qualitative.D3[0]),
    go.Bar(name='LA Zoo', x=animals, y=[12, 18, 29], marker_color=px.colors.qualitative.D3[1])
])
# Change the bar mode
fig.update_layout(barmode='stack')
fig.show()