<h1>Essential basic functionality</h1>

<p>Here we discuss a lot of the essential functionality common to the pandas data structures. To begin, let’s create some example objects like we did in the <a href="https://pandas.pydata.org/docs/user_guide/10min.html#min">10 minutes to pandas</a> section:</p>

In [526]:
import pandas as pd
import numpy as np

In [527]:
index = pd.date_range("1/1/2000", periods=8)

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

# <h2>Head and tail</h2>

<p>To view a small sample of a Series or DataFrame object, use the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html#pandas.DataFrame.head" title="pandas.DataFrame.head"><code>head()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail" title="pandas.DataFrame.tail"><code>tail()</code></a> methods. The default number of elements to display is five, but you may pass a custom number.</p>

In [528]:
long_series = pd.Series(np.random.randn(1000))

long_series.head()

0   -0.432656
1   -0.016351
2   -1.076961
3   -0.582527
4   -0.277326
dtype: float64

In [529]:
long_series.tail(3)

997    1.127144
998    1.549734
999   -0.696459
dtype: float64

# <h2>Attributes and underlying data</h2>

<p>pandas objects have a number of attributes enabling you to access the metadata</p>

<ul>

<li><p><strong>shape</strong>: gives the axis dimensions of the object, consistent with ndarray</p></li>

<li><dl>
<dt>Axis labels</dt><dd><ul>
<li><p><strong>Series</strong>: <em>index</em> (only axis)</p></li>
<li><p><strong>DataFrame</strong>: <em>index</em> (rows) and <em>columns</em></p></li></ul></dd>
</dl>
</li>

</ul>

<p>Note, <strong>these attributes can be safely assigned to</strong>!</p>

In [530]:
df[:2]

                   A         B         C
2000-01-01 -0.886674  0.426368  0.199364
2000-01-02 -1.486222  0.410934 -0.759902

In [531]:
df.columns = [x.lower() for x in df.columns]

In [532]:
df

                   a         b         c
2000-01-01 -0.886674  0.426368  0.199364
2000-01-02 -1.486222  0.410934 -0.759902
2000-01-03 -3.082106  0.351744  0.229585
2000-01-04 -0.963699 -1.316993 -1.118402
2000-01-05 -0.110169 -0.145872  0.539191
2000-01-06  1.248167  1.146345 -2.314208
2000-01-07 -0.707156 -0.823781 -0.687537
2000-01-08  0.141206  0.460871  0.321472

<p>pandas objects (<a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>) can be thought of as containers for arrays, which hold the actual data and do the actual computation. For many types, the underlying array is a <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a>. However, pandas and 3rd party libraries may <em>extend</em>
NumPy’s type system to add support for custom arrays (see <a href="https://pandas.pydata.org/docs/user_guide/basics.htmlhttps://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</a>).</p>

<p>To get the actual data inside a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>, use the <code>.array</code> property</p>

In [533]:
s.array

<NumpyExtensionArray>
[  1.1738537636948132,  -1.1276758551721011,  -0.3627040309578394,
 -0.20542237508313874,  -0.1398440283806816]
Length: 5, dtype: float64

In [534]:
s.index.array

<NumpyExtensionArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.array.html#pandas.Series.array" title="pandas.Series.array"><code>array</code></a> will always be an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a>.
The exact details of what an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a> is and why pandas uses them are a bit beyond the scope of this introduction. See <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</a> for more.</p>
<p>If you know you need a NumPy array, use <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</code></a> or <code>numpy.asarray()</code>.</p>

In [535]:
s.to_numpy()

array([ 1.17385376, -1.12767586, -0.36270403, -0.20542238, -0.13984403])

In [536]:
np.asarray(s)

array([ 1.17385376, -1.12767586, -0.36270403, -0.20542238, -0.13984403])

<p>When the Series or Index is backed by an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</code></a> may involve copying data and coercing values.
See <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</a> for more.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</code></a> gives some control over the <code>dtype</code> of the resulting <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a>.
For example, consider datetimes with timezones.
NumPy doesn’t have a dtype to represent timezone-aware datetimes, so there are two possibly useful representations:</p>

<ol>
<li><p>An object-dtype <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a> with <a href="https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html#pandas.Timestamp" title="pandas.Timestamp"><code>Timestamp</code></a> objects, each
with the correct <code>tz</code></p></li>
<li><p>A <code>datetime64[ns]</code> -dtype <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a>, where the values have been converted to UTC and the timezone discarded</p></li>
</ol>

<p>Timezones may be preserved with <code>dtype=object</code></p>

In [537]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))

ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET')], dtype=object)

<p>Or thrown away with <code>dtype='datetime64[ns]'</code></p>

In [538]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

<p>Getting the “raw data” inside a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> is possibly a bit more complex. When your <code>DataFrame</code> only has a single data type for all the columns, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</code></a> will return the underlying data:</p>

In [539]:
df.to_numpy()

array([[-0.88667369,  0.42636826,  0.19936378],
       [-1.4862222 ,  0.41093393, -0.75990232],
       [-3.08210575,  0.35174405,  0.22958519],
       [-0.96369856, -1.31699319, -1.11840241],
       [-0.11016868, -0.14587243,  0.5391912 ],
       [ 1.24816738,  1.14634513, -2.31420838],
       [-0.70715571, -0.82378125, -0.68753685],
       [ 0.14120552,  0.46087085,  0.32147221]])

<p>If a DataFrame contains homogeneously-typed data, the ndarray can
actually be modified in-place, and the changes will be reflected in the data structure. For heterogeneous data (e.g. some of the DataFrame’s columns are not all the same dtype), this will not be the case. The values attribute itself, unlike the axis labels, cannot be assigned to.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>When working with heterogeneous data, the dtype of the resulting ndarray will be chosen to accommodate all of the data involved. For example, if strings are involved, the result will be of object dtype. If there are only floats and integers, the resulting array will be of float dtype.</p>
</div>

<p>In the past, pandas recommended <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html#pandas.Series.values" title="pandas.Series.values"><code>Series.values</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values" title="pandas.DataFrame.values"><code>DataFrame.values</code></a> for extracting the data from a Series or DataFrame. You’ll still find references to these in old code bases and online. Going forward, we recommend avoiding <code>.values</code> and using <code>.array</code> or <code>.to_numpy()</code>. <code>.values</code> has the following drawbacks:</p>

<ol>

<li><p>When your Series contains an <a href="https://pandas.pydata.org/docs/development/extending.html#extending-extension-types">extension type</a>, it’s
unclear whether <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html#pandas.Series.values" title="pandas.Series.values"><code>Series.values</code></a> returns a NumPy array or the extension array.
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.array.html#pandas.Series.array" title="pandas.Series.array"><code>Series.array</code></a> will always return an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a>, and will never copy data.
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>Series.to_numpy()</code></a> will always return a NumPy array, potentially at the cost of copying / coercing values.</p></li>

<li><p>When your DataFrame contains a mixture of data types, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values" title="pandas.DataFrame.values"><code>DataFrame.values</code></a> may involve copying data and coercing values to a common dtype, a relatively expensive operation. <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</code></a>, being a method, makes it clearer that the returned NumPy array may not be a view on the same data in the DataFrame.</p></li>

</ol>

# <h2>Accelerated operations</h2>

<p>Pandas has support for accelerating certain types of binary numerical and boolean operations using the <code>numexpr</code> library and the <code>bottleneck</code> libraries.</p>

<p>These libraries are especially useful when dealing with large data sets, and provide large speedups. <code>numexpr</code> uses smart chunking, caching, and multiple cores. <code>bottleneck</code> is a set of specialized cython routines that are especially fast when dealing with arrays that have <code>nans</code>.</p>

<p>Here is a sample (using 100 column x 100,000 row <code>DataFrames</code>):</p>

<table class="table">
<colgroup>
<col style="width: 25.0%">
<col style="width: 25.0%">
<col style="width: 25.0%">
<col style="width: 25.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Operation</p></th>
<th class="head"><p>0.11.0 (ms)</p></th>
<th class="head"><p>Prior Version (ms)</p></th>
<th class="head"><p>Ratio to Prior</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code>df1 &gt; df2</code></p></td>
<td><p>13.32</p></td>
<td><p>125.35</p></td>
<td><p>0.1063</p></td>
</tr>
<tr class="row-odd"><td><p><code>df1 * df2</code></p></td>
<td><p>21.71</p></td>
<td><p>36.63</p></td>
<td><p>0.5928</p></td>
</tr>
<tr class="row-even"><td><p><code>df1 + df2</code></p></td>
<td><p>22.04</p></td>
<td><p>36.50</p></td>
<td><p>0.6039</p></td>
</tr>
</tbody>
</table>

<p>You are highly encouraged to install both libraries. See the section
<a href="https://pandas.pydata.org/docs/getting_started/install.html#install-recommended-dependencies">Recommended Dependencies</a> for more installation info.</p>

<p>These are both enabled to be used by default, you can control this by setting the options:</p>

In [540]:
pd.set_option("compute.use_bottleneck", False)
pd.set_option("compute.use_numexpr", False)

# <h2>Flexible binary operations</h2>

<p>With binary operations between pandas data structures, there are two key points of interest:</p>

<ul>
<li><p>Broadcasting behavior between higher- (e.g. DataFrame) and
lower-dimensional (e.g. Series) objects.</p></li>
<li><p>Missing data in computations.</p></li>
</ul>

<p>We will demonstrate how to manage these issues independently, though they can be handled simultaneously.</p>

## <h3>Matching / broadcasting behavior</h3>

<p>DataFrame has the methods <a href=".https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.add.html#pandas.DataFrame.add" title="pandas.DataFrame.add"><code>add()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sub.html#pandas.DataFrame.sub" title="pandas.DataFrame.sub"><code>sub()</code></a>,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mul.html#pandas.DataFrame.mul" title="pandas.DataFrame.mul"><code>mul()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.div.html#pandas.DataFrame.div" title="pandas.DataFrame.div"><code>div()</code></a> and related functions
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.radd.html#pandas.DataFrame.radd" title="pandas.DataFrame.radd"><code>radd()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rsub.html#pandas.DataFrame.rsub" title="pandas.DataFrame.rsub"><code>rsub()</code></a>, …
for carrying out binary operations. For broadcasting behavior,
Series input is of primary interest. Using these functions, you can use to either match on the <em>index</em> or <em>columns</em> via the <strong>axis</strong> keyword:</p>

In [541]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

In [542]:
df

        one       two     three
a  0.406755  0.429601       NaN
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028
d       NaN  1.194943 -0.433825

In [543]:
row = df.iloc[1]

column = df["two"]

df.sub(row, axis="columns")

        one       two     three
a  0.829021  0.299701       NaN
b  0.000000  0.000000  0.000000
c -0.152200 -1.725303 -1.253565
d       NaN  1.065044 -1.477362

In [544]:
df.sub(row, axis=1)

        one       two     three
a  0.829021  0.299701       NaN
b  0.000000  0.000000  0.000000
c -0.152200 -1.725303 -1.253565
d       NaN  1.065044 -1.477362

In [545]:
df.sub(column, axis="index")

        one  two     three
a -0.022846  0.0       NaN
b -0.552166  0.0  0.913638
c  1.020938  0.0  1.385376
d       NaN  0.0 -1.628768

In [546]:
df.sub(column, axis=0)

        one  two     three
a -0.022846  0.0       NaN
b -0.552166  0.0  0.913638
c  1.020938  0.0  1.385376
d       NaN  0.0 -1.628768

<p>Furthermore you can align a level of a MultiIndexed DataFrame with a Series.</p>

In [547]:
dfmi = df.copy()

dfmi.index = pd.MultiIndex.from_tuples(
    [(1, "a"), (1, "b"), (1, "c"), (2, "a")], names=["first", "second"]
)

dfmi.sub(column, axis=0, level="second")

                   one       two     three
first second
1     a      -0.022846  0.000000       NaN
      b      -0.552166  0.000000  0.913638
      c       1.020938  0.000000  1.385376
2     a            NaN  0.765342 -0.863426

<p>Series and Index also support the <a href="https://docs.python.org/3/library/functions.html#divmod" title="(in Python v3.13)"><code>divmod()</code></a> builtin. This function takes the floor division and modulo operation at the same time returning a two-tuple of the same type as the left hand side. For example:</p>

In [548]:
s = pd.Series(np.arange(10))

In [549]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [550]:
div, rem = divmod(s, 3)

In [551]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int64

In [552]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int64

In [553]:
idx = pd.Index(np.arange(10))

In [554]:
idx

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [555]:
div, rem = divmod(idx, 3)

In [556]:
div

Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64')

In [557]:
rem

Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64')

<p>We can also do elementwise <a href="https://docs.python.org/3/library/functions.html#divmod" title="(in Python v3.13)"><code>divmod()</code></a>:</p>

In [558]:
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [559]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64

In [560]:
rem

0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int64

## <h3>Missing data / operations with fill values</h3>

<p>In Series and DataFrame, the arithmetic functions have the option of inputting a <em>fill_value</em>, namely a value to substitute when at most one of the values at a location are missing. For example, when adding two DataFrame objects, you may wish to treat NaN as 0 unless both DataFrames are missing that value, in which case the result will be NaN (you can later replace NaN with some other value using <code>fillna</code> if you wish).</p>

In [561]:
df2 = df.copy()

df2.loc["a", "three"] = 1.0

In [562]:
df

        one       two     three
a  0.406755  0.429601       NaN
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028
d       NaN  1.194943 -0.433825

In [563]:
df2

        one       two     three
a  0.406755  0.429601  1.000000
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028
d       NaN  1.194943 -0.433825

In [564]:
df + df2

        one       two     three
a  0.813510  0.859202       NaN
b -0.844532  0.259799  2.087074
c -1.148932 -3.190807 -0.420056
d       NaN  2.389887 -0.867649

In [565]:
df.add(df2, fill_value=0)

        one       two     three
a  0.813510  0.859202  1.000000
b -0.844532  0.259799  2.087074
c -1.148932 -3.190807 -0.420056
d       NaN  2.389887 -0.867649

## <h3>Flexible comparisons</h3>

<p>Series and DataFrame have the binary comparison methods <code>eq</code>, <code>ne</code>, <code>lt</code>, <code>gt</code>, <code>le</code>, and <code>ge</code> whose behavior is analogous to the binary arithmetic operations described above:</p>

In [566]:
df.gt(df2)

     one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [567]:
df2.ne(df)

     one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

<p>These operations produce a pandas object of the same type as the left-hand-side input that is of dtype <code>bool</code>. These <code>boolean</code> objects can be used in indexing operations, see the section on <a href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-boolean">Boolean indexing</a>.</p>

## <h3>Boolean reductions</h3>

<p>You can apply the reductions: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.empty.html#pandas.DataFrame.empty" title="pandas.DataFrame.empty"><code>empty</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.any.html#pandas.DataFrame.any" title="pandas.DataFrame.any"><code>any()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html#pandas.DataFrame.all" title="pandas.DataFrame.all"><code>all()</code></a>, and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.bool.html#pandas.DataFrame.bool" title="pandas.DataFrame.bool"><code>bool()</code></a> to provide a way to summarize a boolean result.</p>

In [568]:
(df > 0).all()

one      False
two      False
three    False
dtype: bool

In [569]:
(df > 0).any()

one      True
two      True
three    True
dtype: bool

<p>You can reduce to a final boolean value.</p>

In [570]:
(df > 0).any().any()

True

<p>You can test if a pandas object is empty, via the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.empty.html#pandas.DataFrame.empty" title="pandas.DataFrame.empty"><code>empty</code></a> property.</p>

In [571]:
df.empty

False

In [572]:
pd.DataFrame(columns=list("ABC")).empty

True

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Asserting the truthiness of a pandas object will raise an error, as the testing of the emptiness
or values is ambiguous.</p>

In [573]:
if df:
    print(True)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
df and df2

<p>See <a href="https://pandas.pydata.org/docs/user_guide/gotchas.html#gotchas-truth">gotchas</a> for a more detailed discussion.</p>

## <h3>Comparing if objects are equivalent</h3>

<p>Often you may find that there is more than one way to compute the same result.  As a simple example, consider <code>df + df</code> and <code>df * 2</code>. To test
that these two computations produce the same result, given the tools
shown above, you might imagine using <code>(df + df == df * 2).all()</code>. But in
fact, this expression is False:</p>

In [ ]:
df + df == df * 2

In [ ]:
(df + df == df * 2).all()

<p>Notice that the boolean DataFrame <code>df + df == df * 2</code> contains some False values!
This is because NaNs do not compare as equals:</p>

In [ ]:
np.nan == np.nan

<p>So, NDFrames (such as Series and DataFrames)
have an <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html#pandas.DataFrame.equals" title="pandas.DataFrame.equals"><code>equals()</code></a> method for testing equality, with NaNs in corresponding locations treated as equal.</p>

In [ ]:
(df + df).equals(df * 2)

<p>Note that the Series or DataFrame index needs to be in the same order for equality to be True:</p>

In [ ]:
df1 = pd.DataFrame({"col": ["foo", 0, np.nan]})

df2 = pd.DataFrame({"col": [np.nan, 0, "foo"]}, index=[2, 1, 0])

In [ ]:
df1.equals(df2)

In [ ]:
df1.equals(df2.sort_index())

## <h3>Comparing array-like objects</h3>

<p>You can conveniently perform element-wise comparisons when comparing a pandas data structure with a scalar value:</p>

In [ ]:
pd.Series(["foo", "bar", "baz"]) == "foo"

In [ ]:
pd.Index(["foo", "bar", "baz"]) == "foo"

<p>pandas also handles element-wise comparisons between different array-like objects of the same length:</p>

In [ ]:
pd.Series(["foo", "bar", "baz"]) == pd.Index(["foo", "bar", "qux"])

In [ ]:
pd.Series(["foo", "bar", "baz"]) == np.array(["foo", "bar", "qux"])

<p>Trying to compare <code>Index</code> or <code>Series</code> objects of different lengths will raise a ValueError:</p>

In [ ]:
pd.Series(['foo', 'bar', 'baz']) == pd.Series(['foo', 'bar'])

## <h3>Combining overlapping data sets</h3>

<p>A problem occasionally arising is the combination of two similar data sets where values in one are preferred over the other. An example would be two data series representing a particular economic indicator where one is considered to be of “higher quality”.
However, the lower quality series might extend further back in history or have more complete data coverage. As such, we would like to combine two DataFrame objects where missing values in one DataFrame are conditionally filled with like-labeled values from the other DataFrame.
The function implementing this operation is <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</code></a>, which we illustrate:</p>

In [ ]:
df1 = pd.DataFrame(
    {"A": [1.0, np.nan, 3.0, 5.0, np.nan], "B": [np.nan, 2.0, 3.0, np.nan, 6.0]}
)

In [ ]:
df2 = pd.DataFrame(
    {
        "A": [5.0, 2.0, 4.0, np.nan, 3.0, 7.0],
        "B": [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0],
    }
)

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1.combine_first(df2)

## <h3>General DataFrame combine</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</code></a> method above calls the more general <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine.html#pandas.DataFrame.combine" title="pandas.DataFrame.combine"><code>DataFrame.combine()</code></a>.
This method takes another DataFrame and a combiner function, aligns the input DataFrame and then passes the combiner function pairs of Series (i.e., columns whose names are the same).</p>

<p>So, for instance, to reproduce <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</code></a> as above:</p>

In [ ]:
def combiner(x, y):
  return np.where(pd.isna(x), y, x)

df1.combine(df2, combiner)

# <h2>Descriptive statistics</h2>

<p>There exists a large number of methods for computing descriptive statistics and other related operations on <a href="https://pandas.pydata.org/docs/reference/series.html#api-series-stats">Series</a>, <a href="https://pandas.pydata.org/docs/reference/frame.html#api-dataframe-stats">DataFrame</a>.
Most of these are aggregations (hence producing a lower-dimensional result) like <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html#pandas.DataFrame.sum" title="pandas.DataFrame.sum"><code>sum()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html#pandas.DataFrame.mean" title="pandas.DataFrame.mean"><code>mean()</code></a>, and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html#pandas.DataFrame.quantile" title="pandas.DataFrame.quantile"><code>quantile()</code></a>, but some of them, like <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumsum.html#pandas.DataFrame.cumsum" title="pandas.DataFrame.cumsum"><code>cumsum()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumprod.html#pandas.DataFrame.cumprod" title="pandas.DataFrame.cumprod"><code>cumprod()</code></a>, produce an object of the same size.
Generally speaking, these methods take an <strong>axis</strong> argument, just like <em>ndarray.{sum, std, …}</em>, but the axis can be specified by name or integer:</p>

<ul>
<li><p><strong>Series</strong>: no axis argument needed</p></li>
<li><p><strong>DataFrame</strong>: “index” (axis=0, default), “columns” (axis=1)</p></li>
</ul>

<p>For example:</p>

In [ ]:
df

In [ ]:
df.mean(0)

In [ ]:
df.mean(1)

<p>All such methods have a <code>skipna</code> option signaling whether to exclude missing data (<code>True</code> by default):</p>

In [ ]:
df.sum(0, skipna=False)

In [ ]:
df.sum(axis=1, skipna=True)

<p>Combined with the broadcasting / arithmetic behavior, one can describe various statistical procedures, like standardization (rendering data zero mean and standard deviation of 1), very concisely:</p>

In [ ]:
ts_stand = (df - df.mean()) / df.std()

ts_stand.std()

In [ ]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

xs_stand.std(1)

<p>Note that methods like <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumsum.html#pandas.DataFrame.cumsum" title="pandas.DataFrame.cumsum"><code>cumsum()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumprod.html#pandas.DataFrame.cumprod" title="pandas.DataFrame.cumprod"><code>cumprod()</code></a> preserve the location of <code>NaN</code> values. This is somewhat different from <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.expanding.html#pandas.DataFrame.expanding" title="pandas.DataFrame.expanding"><code>expanding()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html#pandas.DataFrame.rolling" title="pandas.DataFrame.rolling"><code>rolling()</code></a> since <code>NaN</code> behavior is furthermore dictated by a <code>min_periods</code> parameter.</p>

In [ ]:
df.cumsum()

<p>Here is a quick reference summary table of common functions. Each also takes an optional <code>level</code> parameter which applies only if the object has a <a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-hierarchical">hierarchical index</a>.</p>

<table class="table">
<colgroup>
<col style="width: 20.0%">
<col style="width: 80.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Function</p></th>
<th class="head"><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code>count</code></p></td>
<td><p>Number of non-NA observations</p></td>
</tr>
<tr class="row-odd"><td><p><code>sum</code></p></td>
<td><p>Sum of values</p></td>
</tr>
<tr class="row-even"><td><p><code>mean</code></p></td>
<td><p>Mean of values</p></td>
</tr>
<tr class="row-odd"><td><p><code>median</code></p></td>
<td><p>Arithmetic median of values</p></td>
</tr>
<tr class="row-even"><td><p><code>min</code></p></td>
<td><p>Minimum</p></td>
</tr>
<tr class="row-odd"><td><p><code>max</code></p></td>
<td><p>Maximum</p></td>
</tr>
<tr class="row-even"><td><p><code>mode</code></p></td>
<td><p>Mode</p></td>
</tr>
<tr class="row-odd"><td><p><code>abs</code></p></td>
<td><p>Absolute Value</p></td>
</tr>
<tr class="row-even"><td><p><code>prod</code></p></td>
<td><p>Product of values</p></td>
</tr>
<tr class="row-odd"><td><p><code>std</code></p></td>
<td><p>Bessel-corrected sample standard deviation</p></td>
</tr>
<tr class="row-even"><td><p><code>var</code></p></td>
<td><p>Unbiased variance</p></td>
</tr>
<tr class="row-odd"><td><p><code>sem</code></p></td>
<td><p>Standard error of the mean</p></td>
</tr>
<tr class="row-even"><td><p><code>skew</code></p></td>
<td><p>Sample skewness (3rd moment)</p></td>
</tr>
<tr class="row-odd"><td><p><code>kurt</code></p></td>
<td><p>Sample kurtosis (4th moment)</p></td>
</tr>
<tr class="row-even"><td><p><code>quantile</code></p></td>
<td><p>Sample quantile (value at %)</p></td>
</tr>
<tr class="row-odd"><td><p><code>cumsum</code></p></td>
<td><p>Cumulative sum</p></td>
</tr>
<tr class="row-even"><td><p><code>cumprod</code></p></td>
<td><p>Cumulative product</p></td>
</tr>
<tr class="row-odd"><td><p><code>cummax</code></p></td>
<td><p>Cumulative maximum</p></td>
</tr>
<tr class="row-even"><td><p><code>cummin</code></p></td>
<td><p>Cumulative minimum</p></td>
</tr>
</tbody>
</table>

<p>Note that by chance some NumPy methods, like <code>mean</code>, <code>std</code>, and <code>sum</code>,
will exclude NAs on Series input by default:</p>

In [ ]:
np.mean(df["one"])

In [ ]:
np.mean(df["one"].to_numpy())

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.nunique.html#pandas.Series.nunique" title="pandas.Series.nunique"><code>Series.nunique()</code></a> will return the number of unique non-NA values in a Series:</p>

In [ ]:
series = pd.Series(np.random.randn(500))

series[20:500] = np.nan

series[10:20] = 5

series.nunique()

## <h3>Summarizing data: describe</h3>

<p>There is a convenient <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</code></a> function which computes a variety of summary statistics about a Series or the columns of a DataFrame (excluding NAs of course):</p>

In [ ]:
series = pd.Series(np.random.randn(1000))

series[::2] = np.nan

series.describe()

In [ ]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=["a", "b", "c", "d", "e"])

frame.iloc[::2] = np.nan

frame.describe()

<p>You can select specific percentiles to include in the output:</p>

In [ ]:
series.describe(percentiles=[0.05, 0.25, 0.75, 0.95])

<p>By default, the median is always included.</p>
<p>For a non-numerical Series object, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.Series.describe"><code>describe()</code></a> will give a simple summary of the number of unique values and most frequently occurring values:</p>

In [ ]:
s = pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])

s.describe()

<p>Note that on a mixed-type DataFrame object, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</code></a> will restrict the summary to include only numerical columns or, if none are, only categorical columns:</p>

In [ ]:
frame = pd.DataFrame({"a": ["Yes", "Yes", "No", "No"], "b": range(4)})

frame.describe()

<p>This behavior can be controlled by providing a list of types as <code>include</code>/<code>exclude</code>
arguments. The special value <code>all</code> can also be used:</p>

In [ ]:
frame.describe(include=["object"])

In [ ]:
frame.describe(include=["number"])

In [ ]:
frame.describe(include="all")

<p>That feature relies on <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes">select_dtypes</a>. Refer to there for details about accepted inputs.</p>

## <h3>Index of min/max values</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmin.html#pandas.DataFrame.idxmin" title="pandas.DataFrame.idxmin"><code>idxmin()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmax.html#pandas.DataFrame.idxmax" title="pandas.DataFrame.idxmax"><code>idxmax()</code></a> functions on Series and DataFrame compute the index labels with the minimum and maximum corresponding values:</p>

In [ ]:
s1 = pd.Series(np.random.randn(5))

In [ ]:
s1

In [ ]:
s1.idxmin(), s1.idxmax()

In [ ]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])

In [ ]:
df1

In [ ]:
df1.idxmin(axis=0)

In [ ]:
df1.idxmin(axis=0)

In [ ]:
df1.idxmax(axis=1)

<p>When there are multiple rows (or columns) matching the minimum or maximum value, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmin.html#pandas.DataFrame.idxmin" title="pandas.DataFrame.idxmin"><code>idxmin()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmax.html#pandas.DataFrame.idxmax" title="pandas.DataFrame.idxmax"><code>idxmax()</code></a> return the first
matching index:</p>

In [ ]:
df3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=["A"], index=list("edcba"))

In [ ]:
df3

In [ ]:
df3["A"].idxmin()

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>idxmin</code> and <code>idxmax</code> are called <code>argmin</code> and <code>argmax</code> in NumPy.</p>
</div>

## <h3>Value counts (histogramming) / mode</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts" title="pandas.Series.value_counts"><code>value_counts()</code></a> Series method computes a histogram of a 1D array of values. It can also be used as a function on regular arrays:</p>

In [574]:
data = np.random.randint(0, 7, size=50)

In [575]:
data

array([6, 6, 1, 1, 4, 0, 1, 4, 1, 4, 4, 3, 1, 2, 5, 1, 4, 4, 4, 6, 1, 2,
       1, 0, 6, 6, 0, 4, 1, 0, 6, 4, 6, 4, 4, 4, 3, 4, 0, 1, 4, 2, 5, 3,
       4, 5, 5, 3, 1, 2])

In [576]:
s = pd.Series(data)

In [577]:
s.value_counts()

4    15
1    11
6     7
0     5
3     4
2     4
5     4
Name: count, dtype: int64

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts" title="pandas.DataFrame.value_counts"><code>value_counts()</code></a> method can be used to count combinations across multiple columns.
By default all columns are used but a subset can be selected using the <code>subset</code> argument.</p>

In [578]:
data = {"a": [1, 2, 3, 4], "b": ["x", "x", "y", "y"]}

frame = pd.DataFrame(data)

In [579]:
frame.value_counts()

a  b
1  x    1
2  x    1
3  y    1
4  y    1
Name: count, dtype: int64

<p>Similarly, you can get the most frequently occurring value(s), i.e. the mode, of the values in a Series or DataFrame:</p>

In [580]:
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7])

s5.mode()

0    3
1    7
dtype: int64

In [581]:
df5 = pd.DataFrame(
       {
           "A": np.random.randint(0, 7, size=50),
           "B": np.random.randint(-10, 15, size=50),
       }
   )

df5.mode()

   A   B
0  0 -10

## <h3>Discretization and quantiling</h3>

<p>Continuous values can be discretized using the <a href="https://pandas.pydata.org/docs/reference/api/pandas.cut.html#pandas.cut" title="pandas.cut"><code>cut()</code></a> (bins based on values) and <a href="https://pandas.pydata.org/docs/reference/api/pandas.qcut.html#pandas.qcut" title="pandas.qcut"><code>qcut()</code></a> (bins based on sample quantiles) functions:</p>

In [582]:
arr = np.random.randn(20)

factor = pd.cut(arr, 4)

In [583]:
factor

[(-0.0339, 0.942], (0.942, 1.918], (-1.989, -1.01], (-1.989, -1.01], (-1.01, -0.0339], ..., (-1.01, -0.0339], (-1.01, -0.0339], (0.942, 1.918], (0.942, 1.918], (-0.0339, 0.942]]
Length: 20
Categories (4, interval[float64, right]): [(-1.989, -1.01] < (-1.01, -0.0339] < (-0.0339, 0.942] < (0.942, 1.918]]

In [584]:
factor = pd.cut(arr, [-5, -1, 0, 1, 5])

In [585]:
factor

[(0, 1], (1, 5], (-5, -1], (-5, -1], (-1, 0], ..., (-1, 0], (-1, 0], (1, 5], (1, 5], (0, 1]]
Length: 20
Categories (4, interval[int64, right]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.qcut.html#pandas.qcut" title="pandas.qcut"><code>qcut()</code></a> computes sample quantiles. For example, we could slice up some normally distributed data into equal-size quartiles like so:</p>

In [586]:
arr = np.random.randn(30)

factor = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])

In [587]:
factor

[(-2.28, -0.673], (0.148, 0.728], (-0.673, 0.148], (-2.28, -0.673], (-2.28, -0.673], ..., (0.148, 0.728], (0.148, 0.728], (0.148, 0.728], (0.148, 0.728], (0.728, 1.522]]
Length: 30
Categories (4, interval[float64, right]): [(-2.28, -0.673] < (-0.673, 0.148] < (0.148, 0.728] < (0.728, 1.522]]

<p>We can also pass infinite values to define the bins:</p>

In [588]:
arr = np.random.randn(20)

factor = pd.cut(arr, [-np.inf, 0, np.inf])

In [589]:
factor

[(-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (0.0, inf], (0.0, inf], ..., (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (-inf, 0.0]]
Length: 20
Categories (2, interval[float64, right]): [(-inf, 0.0] < (0.0, inf]]

# <h2>Function application</h2>

<p>To apply your own or another library’s functions to pandas objects,
you should be aware of the three methods below. The appropriate
method to use depends on whether your function expects to operate
on an entire <code>DataFrame</code> or <code>Series</code>, row- or column-wise, or elementwise.</p>
<ol>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#tablewise-function-application">Tablewise Function Application</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</code></a></p></li>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#row-or-column-wise-function-application">Row or Column-wise Function Application</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a></p></li>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#aggregation-api">Aggregation API</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html#pandas.DataFrame.agg" title="pandas.DataFrame.agg"><code>agg()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</code></a></p></li>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#applying-elementwise-functions">Applying Elementwise Functions</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.DataFrame.map"><code>map()</code></a></p></li>
</ol>

## <h3>Tablewise function application</h3>

<p><code>DataFrames</code> and <code>Series</code> can be passed into functions.
However, if the function needs to be called in a chain, consider using the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</code></a> method.</p>

<p>First some setup:</p>

In [590]:
def extract_city_name(df):
       """
       Chicago, IL -> Chicago for city_name column
       """
       df["city_name"] = df["city_and_code"].str.split(",").str.get(0)
       return df

In [591]:
def add_country_name(df, country_name=None):
       """
       Chicago -> Chicago-US for city_name column
       """
       col = "city_name"
       df["city_and_country"] = df[col] + country_name
       return df

In [592]:
df_p = pd.DataFrame({"city_and_code": ["Chicago, IL"]})

<p><code>extract_city_name</code> and <code>add_country_name</code> are functions taking and returning <code>DataFrames</code>.</p>

<p>Now compare the following:</p>

In [593]:
add_country_name(extract_city_name(df_p), country_name="US")

  city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

<p>Is equivalent to:</p>

In [594]:
df_p.pipe(extract_city_name).pipe(add_country_name, country_name="US")

  city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

<p>pandas encourages the second style, which is known as method chaining.
<code>pipe</code> makes it easy to use your own or another library’s functions
in method chains, alongside pandas’ methods.</p>
<p>In the example above, the functions <code>extract_city_name</code> and <code>add_country_name</code> each expected a <code>DataFrame</code> as the first positional argument.
What if the function you wish to apply takes its data as, say, the second argument?
In this case, provide <code>pipe</code> with a tuple of <code>(callable, data_keyword)</code>.
<code>.pipe</code> will route the <code>DataFrame</code> to the argument specified in the tuple.</p>
<p>For example, we can fit a regression using statsmodels. Their API expects a formula first and a <code>DataFrame</code> as the second argument, <code>data</code>. We pass in the function, keyword pair <code>(sm.ols, 'data')</code> to <code>pipe</code>:</p>

In [595]:
import statsmodels.formula.api as sm

bb = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/refs/heads/main/doc/data/baseball.csv", index_col="id")

(
       bb.query("h > 0")
       .assign(ln_h=lambda df: np.log(df.h))
       .pipe((sm.ols, "data"), "hr ~ ln_h + year + g + C(lg)")
       .fit()
       .summary()
   )

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.685
Model:                            OLS   Adj. R-squared:                  0.665
Method:                 Least Squares   F-statistic:                     34.28
Date:                Thu, 16 Oct 2025   Prob (F-statistic):           3.48e-15
Time:                        21:14:46   Log-Likelihood:                -205.92
No. Observations:                  68   AIC:                             421.8
Df Residuals:                      63   BIC:                             432.9
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -8484.7720   4664.146     -1.819      0.074   -1.78e+04     835.780
C(lg)[T.NL]    -2.2736      1.325     -1.716      0.091      -4.922       0.375
ln_h           -1.3542      0.875     -1.547      0.127      -3.103       0.395
year            4.2277      2.324      1.819      0.074      -0.417       8.872
g               0.1841      0.029      6.258      0.000       0.125       0.243
==============================================================================
Omnibus:                       10.875   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               17.298
Skew:                           0.537   Prob(JB):                     0.000175
Kurtosis:                       5.225   Cond. No.                     1.49e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

<p>The pipe method is inspired by unix pipes and more recently <a href="https://github.com/tidyverse/dplyr">dplyr</a> and <a href="https://github.com/tidyverse/magrittr">magrittr</a>, which
have introduced the popular <code>(%&gt;%)</code> (read pipe) operator for <a href="https://www.r-project.org">R</a>.
The implementation of <code>pipe</code> here is quite clean and feels right at home in Python.
We encourage you to view the source code of <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</code></a>.</p>

## <h3>Row or column-wise function application</h3>

<p>Arbitrary functions can be applied along the axes of a DataFrame
using the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> method, which, like the descriptive
statistics methods, takes an optional <code>axis</code> argument:</p>

In [596]:
df.apply(lambda x: np.mean(x))

one     -0.196659
two      0.039760
three    0.133228
dtype: float64

In [597]:
df.apply(lambda x: np.mean(x), axis=1)

a    0.418178
b    0.250390
c   -0.793299
d    0.380559
dtype: float64

In [598]:
df.apply(lambda x: x.max() - x.min())

one      0.981221
two      2.790347
three    1.477362
dtype: float64

In [599]:
df.apply(np.cumsum)

        one       two     three
a  0.406755  0.429601       NaN
b -0.015511  0.559500  1.043537
c -0.589977 -1.035903  0.833509
d       NaN  0.159040  0.399684

In [600]:
df.apply(np.exp)

        one       two     three
a  1.501936  1.536644       NaN
b  0.655560  1.138714  2.839242
c  0.563006  0.202827  0.810562
d       NaN  3.303370  0.648026

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> method will also dispatch on a string method name.</p>

In [601]:
df.apply("mean")

one     -0.196659
two      0.039760
three    0.133228
dtype: float64

In [602]:
df.apply("mean", axis=1)

a    0.418178
b    0.250390
c   -0.793299
d    0.380559
dtype: float64

<p>The return type of the function passed to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> affects the
type of the final output from <code>DataFrame.apply</code> for the default behaviour:</p>
<ul>
<li><p>If the applied function returns a <code>Series</code>, the final output is a <code>DataFrame</code>.
The columns match the index of the <code>Series</code> returned by the applied function.</p></li>
<li><p>If the applied function returns any other type, the final output is a <code>Series</code>.</p></li>
</ul>
<p>This default behaviour can be overridden using the <code>result_type</code>, which
accepts three options: <code>reduce</code>, <code>broadcast</code>, and <code>expand</code>.
These will determine how list-likes return values expand (or not) to a <code>DataFrame</code>.</p>
<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> combined with some cleverness can be used to answer many questions
about a data set. For example, suppose we wanted to extract the date where the
maximum value for each column occurred:</p>

In [603]:
tsdf = pd.DataFrame(
       np.random.randn(1000, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=1000),
   )

tsdf.apply(lambda x: x.idxmax())

A   2000-02-08
B   2002-02-27
C   2001-10-31
dtype: datetime64[ns]

<p>You may also pass additional arguments and keyword arguments to the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> method.</p>

In [604]:
def subtract_and_divide(x, sub, divide=1):
       return (x - sub) / divide

df_udf = pd.DataFrame(np.ones((2, 2)))

df_udf.apply(subtract_and_divide, sub=5, divide=3)

          0         1
0 -1.333333 -1.333333
1 -1.333333 -1.333333

<p>Another useful feature is the ability to pass Series methods to carry out some Series operation on each column or row:</p>

In [605]:
tsdf = pd.DataFrame(
       np.random.randn(10, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=10),
   )

tsdf.iloc[3:7] = np.nan

In [606]:
tsdf

                   A         B         C
2000-01-01 -0.182530  0.645620  1.164624
2000-01-02  0.987911 -1.201611 -1.521885
2000-01-03  0.642810  0.399127 -1.321171
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.754490  0.173075 -0.928362
2000-01-09  0.117125 -1.596917 -1.217406
2000-01-10  0.018397 -0.183965  1.183302

In [607]:
tsdf.apply(pd.Series.interpolate)

                   A         B         C
2000-01-01 -0.182530  0.645620  1.164624
2000-01-02  0.987911 -1.201611 -1.521885
2000-01-03  0.642810  0.399127 -1.321171
2000-01-04  0.665146  0.353916 -1.242609
2000-01-05  0.687482  0.308706 -1.164047
2000-01-06  0.709818  0.263495 -1.085486
2000-01-07  0.732154  0.218285 -1.006924
2000-01-08  0.754490  0.173075 -0.928362
2000-01-09  0.117125 -1.596917 -1.217406
2000-01-10  0.018397 -0.183965  1.183302

<p>Finally, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> takes an argument <code>raw</code> which is False by default, which converts each row or column into a Series before applying the function. When set to True, the passed function will instead receive an ndarray object, which has positive performance implications if you do not need the indexing functionality.</p>

## <h3>Aggregation API</h3>

<p>The aggregation API allows one to express possibly multiple aggregation operations in a single concise way.
This API is similar across pandas objects, see <a href="https://pandas.pydata.org/docs/user_guide/groupby.html#groupby-aggregate">groupby API</a>, the <a href="https://pandas.pydata.org/docs/user_guide/window.html#window-overview">window API</a>, and the <a href="https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-aggregate">resample API</a>.
The entry point for aggregation is <a href=".https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.aggregate.html#pandas.DataFrame.aggregate" title="pandas.DataFrame.aggregate"><code>DataFrame.aggregate()</code></a>, or the alias <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html#pandas.DataFrame.agg" title="pandas.DataFrame.agg"><code>DataFrame.agg()</code></a>.</p>

<p>We will use a similar starting frame from above:</p>

In [608]:
tsdf = pd.DataFrame(
       np.random.randn(10, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=10),
   )

tsdf.iloc[3:7] = np.nan

In [609]:
tsdf

                   A         B         C
2000-01-01  0.754317 -0.475227  0.626876
2000-01-02  1.423681 -0.531267 -0.841428
2000-01-03  0.782393  0.841003  0.884397
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -0.209709  0.693251 -0.431127
2000-01-09 -1.430312 -1.298136  0.070468
2000-01-10 -2.231735  0.809699 -2.067184

<p>Using a single function is equivalent to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a>. You can also pass named methods as strings. These will return a <code>Series</code> of the aggregated output:</p>

In [610]:
tsdf.agg(lambda x: np.sum(x))

A   -0.911365
B    0.039323
C   -1.757997
dtype: float64

In [611]:
tsdf.agg("sum")

A   -0.911365
B    0.039323
C   -1.757997
dtype: float64

In [612]:
# these are equivalent to a .sum() because we are aggregating
# on a single function
tsdf.sum()

A   -0.911365
B    0.039323
C   -1.757997
dtype: float64

<p>Single aggregations on a <code>Series</code> this will return a scalar value:</p>

In [613]:
tsdf["A"].agg("sum")

-0.911364862010072

### <h4>Aggregating with multiple functions</h4>

<p>You can pass multiple aggregation arguments as a list.
The results of each of the passed functions will be a row in the resulting <code>DataFrame</code>.
These are naturally named from the aggregation function.</p>

In [614]:
tsdf.agg(["sum"])

            A         B         C
sum -0.911365  0.039323 -1.757997

<p>Multiple functions yield multiple rows:</p>

In [615]:
tsdf.agg(["sum", "mean"])

             A         B         C
sum  -0.911365  0.039323 -1.757997
mean -0.151894  0.006554 -0.293000

<p>On a <code>Series</code>, multiple functions return a <code>Series</code>, indexed by the function names:</p>

In [616]:
tsdf["A"].agg(["sum", "mean"])

sum    -0.911365
mean   -0.151894
Name: A, dtype: float64

<p>Passing a <code>lambda</code> function will yield a <code>&lt;lambda&gt;</code> named row:</p>

In [617]:
tsdf["A"].agg(["sum", lambda x: x.mean()])

sum        -0.911365
<lambda>   -0.151894
Name: A, dtype: float64

<p>Passing a named function will yield that name for the row:</p>

In [618]:
def mymean(x):
       return x.mean()

tsdf["A"].agg(["sum", mymean])

sum      -0.911365
mymean   -0.151894
Name: A, dtype: float64

### <h4>Aggregating with a dict</h4>

<p>Passing a dictionary of column names to a scalar or a list of scalars, to <code>DataFrame.agg</code>
allows you to customize which functions are applied to which columns. Note that the results are not in any particular order, you can use an <code>OrderedDict</code> instead to guarantee ordering.</p>

In [619]:
tsdf.agg({"A": "mean", "B": "sum"})

A   -0.151894
B    0.039323
dtype: float64

<p>Passing a list-like will generate a <code>DataFrame</code> output. You will get a matrix-like output of all of the aggregators. The output will consist of all unique functions. Those that are not noted for a particular column will be <code>NaN</code>:</p>

In [620]:
tsdf.agg({"A": ["mean", "min"], "B": "sum"})

             A         B
mean -0.151894       NaN
min  -2.231735       NaN
sum        NaN  0.039323

### <h4>Custom describe</h4>

<p>With <code>.agg()</code> it is possible to easily create a custom describe function, similar to the built in <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-describe">describe function</a>.</p>

In [621]:
from functools import partial

q_25 = partial(pd.Series.quantile, q=0.25)

q_25.name = "25%"

q_75 = partial(pd.Series.quantile, q=0.75)

q_75.name = "75%"

tsdf.agg(["count", "mean", "std", "min", q_25, "median", q_75, "max"])

                 A         B         C
count     6.000000  6.000000  6.000000
mean     -0.151894  0.006554 -0.293000
std       1.424078  0.898496  1.080012
min      -2.231735 -1.298136 -2.067184
quantile -1.125162 -0.517257 -0.738853
median    0.272304  0.109012 -0.180329
quantile  0.775374  0.780587  0.487774
max       1.423681  0.841003  0.884397

## <h3>Transform API</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</code></a> method returns an object that is indexed the same (same size) as the original. This API allows you to provide <em>multiple</em> operations at the same time rather than one-by-one. Its API is quite similar to the <code>.agg</code> API.</p>

<p>We create a frame similar to the one used in the above sections.</p>

In [622]:
tsdf = pd.DataFrame(
       np.random.randn(10, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=10),
   )

tsdf.iloc[3:7] = np.nan

In [623]:
tsdf

                   A         B         C
2000-01-01  0.428391 -1.082854 -0.550772
2000-01-02  0.313701 -0.215504 -0.912640
2000-01-03 -0.099864  1.232196 -0.041247
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -1.269058  0.261355 -1.516779
2000-01-09 -0.172503  2.071841  0.218694
2000-01-10  0.777147  0.339124  1.124102

<p>Transform the entire frame. <code>.transform()</code> allows input functions as: a NumPy function, a string function name or a user defined function.</p>

In [624]:
tsdf.transform(np.abs)

                   A         B         C
2000-01-01  0.428391  1.082854  0.550772
2000-01-02  0.313701  0.215504  0.912640
2000-01-03  0.099864  1.232196  0.041247
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.269058  0.261355  1.516779
2000-01-09  0.172503  2.071841  0.218694
2000-01-10  0.777147  0.339124  1.124102

In [625]:
tsdf.transform("abs")

                   A         B         C
2000-01-01  0.428391  1.082854  0.550772
2000-01-02  0.313701  0.215504  0.912640
2000-01-03  0.099864  1.232196  0.041247
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.269058  0.261355  1.516779
2000-01-09  0.172503  2.071841  0.218694
2000-01-10  0.777147  0.339124  1.124102

In [626]:
tsdf.transform(lambda x: x.abs())

                   A         B         C
2000-01-01  0.428391  1.082854  0.550772
2000-01-02  0.313701  0.215504  0.912640
2000-01-03  0.099864  1.232196  0.041247
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.269058  0.261355  1.516779
2000-01-09  0.172503  2.071841  0.218694
2000-01-10  0.777147  0.339124  1.124102

<p>Here <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</code></a> received a single function; this is equivalent to a <a href="https://numpy.org/doc/stable/reference/ufuncs.html">ufunc</a> application.</p>

In [627]:
np.abs(tsdf)

                   A         B         C
2000-01-01  0.428391  1.082854  0.550772
2000-01-02  0.313701  0.215504  0.912640
2000-01-03  0.099864  1.232196  0.041247
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.269058  0.261355  1.516779
2000-01-09  0.172503  2.071841  0.218694
2000-01-10  0.777147  0.339124  1.124102

<p>Passing a single function to <code>.transform()</code> with a <code>Series</code> will yield a single <code>Series</code> in return.</p>

In [628]:
tsdf["A"].transform(np.abs)

2000-01-01    0.428391
2000-01-02    0.313701
2000-01-03    0.099864
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
2000-01-08    1.269058
2000-01-09    0.172503
2000-01-10    0.777147
Freq: D, Name: A, dtype: float64

### <h4>Transform with multiple functions</h4>

<p>Passing multiple functions will yield a column MultiIndexed DataFrame.
The first level will be the original frame column names; the second level will be the names of the transforming functions.</p>

In [629]:
tsdf.transform([np.abs, lambda x: x + 1])

                   A                   B                   C
            absolute  <lambda>  absolute  <lambda>  absolute  <lambda>
2000-01-01  0.428391  1.428391  1.082854 -0.082854  0.550772  0.449228
2000-01-02  0.313701  1.313701  0.215504  0.784496  0.912640  0.087360
2000-01-03  0.099864  0.900136  1.232196  2.232196  0.041247  0.958753
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-08  1.269058 -0.269058  0.261355  1.261355  1.516779 -0.516779
2000-01-09  0.172503  0.827497  2.071841  3.071841  0.218694  1.218694
2000-01-10  0.777147  1.777147  0.339124  1.339124  1.124102  2.124102

<p>Passing multiple functions to a Series will yield a DataFrame. The
resulting column names will be the transforming functions.</p>

In [630]:
tsdf["A"].transform([np.abs, lambda x: x + 1])

            absolute  <lambda>
2000-01-01  0.428391  1.428391
2000-01-02  0.313701  1.313701
2000-01-03  0.099864  0.900136
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  1.269058 -0.269058
2000-01-09  0.172503  0.827497
2000-01-10  0.777147  1.777147

### <h4>Transforming with a dict</h4>

<p>Passing a dict of functions will allow selective transforming per column.</p>

In [631]:
tsdf.transform({"A": np.abs, "B": lambda x: x + 1})

                   A         B
2000-01-01  0.428391 -0.082854
2000-01-02  0.313701  0.784496
2000-01-03  0.099864  2.232196
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  1.269058  1.261355
2000-01-09  0.172503  3.071841
2000-01-10  0.777147  1.339124

<p>Passing a dict of lists will generate a MultiIndexed DataFrame with these selective transforms.</p>

In [632]:
tsdf.transform({"A": np.abs, "B": [lambda x: x + 1, "sqrt"]})

/usr/local/Caskroom/miniconda/base/envs/data-science/lib/python3.9/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

                   A         B
            absolute  <lambda>      sqrt
2000-01-01  0.428391 -0.082854       NaN
2000-01-02  0.313701  0.784496       NaN
2000-01-03  0.099864  2.232196  1.110043
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.269058  1.261355  0.511229
2000-01-09  0.172503  3.071841  1.439389
2000-01-10  0.777147  1.339124  0.582344

## <h3>Applying elementwise functions</h3>

<p>Since not all functions can be vectorized (accept NumPy arrays and return another array or value), the methods <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.DataFrame.map"><code>map()</code></a> on DataFrame and analogously <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.Series.map"><code>map()</code></a> on Series accept any Python function taking a single value and returning a single value.
For example:</p>

In [633]:
df4 = df.copy()

In [634]:
df4

        one       two     three
a  0.406755  0.429601       NaN
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028
d       NaN  1.194943 -0.433825

In [635]:
def f(x):
    return len(str(x))

In [636]:
df4["one"].map(f)

a    18
b    19
c    19
d     3
Name: one, dtype: int64

In [637]:
df4.map(f)

   one  two  three
a   18   17      3
b   19   19     18
c   19   19     20
d    3   18     19

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html#pandas.Series.map"><code>Series.map()</code></a> has an additional feature; it can be used to easily “link” or “map” values defined by a secondary series. This is closely related to <a href="https://pandas.pydata.org/docs/user_guide/merging.html#merging">merging/joining functionality</a>:</p>

In [638]:
s = pd.Series(
    ["six", "seven", "six", "seven", "six"], index=["a", "b", "c", "d", "e"]
)

In [639]:
t = pd.Series({"six": 6.0, "seven": 7.0})

In [640]:
s

a      six
b    seven
c      six
d    seven
e      six
dtype: object

In [641]:
s.map(t)

a    6.0
b    7.0
c    6.0
d    7.0
e    6.0
dtype: float64

# <h2>Reindexing and altering labels</h2>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</code></a> is the fundamental data alignment method in pandas.
It is used to implement nearly all other features relying on label-alignment functionality. To <em>reindex</em> means to conform the data to match a given set of labels along a particular axis. This accomplishes several things:</p>

<ul>
<li><p>Reorders the existing data to match a new set of labels</p></li>
<li><p>Inserts missing value (NA) markers in label locations where no data for
that label existed</p></li>
<li><p>If specified, <strong>fill</strong> data for missing labels using logic (highly relevant
to working with time series data)</p></li>
</ul>

<p>Here is a simple example:</p>

In [642]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

In [643]:
s

a    2.091783
b    1.037907
c   -1.603432
d    1.694660
e    0.690982
dtype: float64

In [644]:
s.reindex(["e", "b", "f", "d"])

e    0.690982
b    1.037907
f         NaN
d    1.694660
dtype: float64

<p>Here, the <code>f</code> label was not contained in the Series and hence appears as <code>NaN</code> in the result.</p>

<p>With a DataFrame, you can simultaneously reindex the index and columns:</p>

In [645]:
df

        one       two     three
a  0.406755  0.429601       NaN
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028
d       NaN  1.194943 -0.433825

In [646]:
df.reindex(index=["c", "f", "b"], columns=["three", "two", "one"])

      three       two       one
c -0.210028 -1.595403 -0.574466
f       NaN       NaN       NaN
b  1.043537  0.129899 -0.422266

<p>Note that the <code>Index</code> objects containing the actual axis labels can be <strong>shared</strong> between objects. So if we have a Series and a DataFrame, the following can be done:</p>

In [647]:
rs = s.reindex(df.index)

In [648]:
rs

a    2.091783
b    1.037907
c   -1.603432
d    1.694660
dtype: float64

In [649]:
rs.index is df.index

True

<p>This means that the reindexed Series’s index is the same Python object as the DataFrame’s index.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html#pandas.DataFrame.reindex" title="pandas.DataFrame.reindex"><code>DataFrame.reindex()</code></a> also supports an “axis-style” calling convention, where you specify a single <code>labels</code> argument and the <code>axis</code> it applies to.</p>

In [650]:
df.reindex(["c", "f", "b"], axis="index")

        one       two     three
c -0.574466 -1.595403 -0.210028
f       NaN       NaN       NaN
b -0.422266  0.129899  1.043537

In [651]:
df.reindex(["three", "two", "one"], axis="columns")

      three       two       one
a       NaN  0.429601  0.406755
b  1.043537  0.129899 -0.422266
c -0.210028 -1.595403 -0.574466
d -0.433825  1.194943       NaN

<div class="alert alert-block alert-success">
<p>See also</p>
<p><a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced">MultiIndex / Advanced Indexing</a> is an even more concise way of doing reindexing.</p>
</div>

<div class="alert alert-block alert-info">
<p>Note</p>
<p>When writing performance-sensitive code, there is a good reason to spend some time becoming a reindexing ninja: <strong>many operations are faster on pre-aligned data</strong>. Adding two unaligned DataFrames internally triggers a reindexing step. For exploratory analysis you will hardly notice the difference (because <code>reindex</code> has been heavily optimized), but when CPU cycles matter sprinkling a few explicit <code>reindex</code> calls here and there can have an impact.</p>
</div>

## <h3>Reindexing to align with another object</h3>

<p>You may wish to take an object and reindex its axes to be labeled the same as another object. While the syntax for this is straightforward albeit verbose, it is a common enough operation that the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex_like.html#pandas.DataFrame.reindex_like" title="pandas.DataFrame.reindex_like"><code>reindex_like()</code></a> method is available to make this simpler:</p>

In [652]:
df2 = df.reindex(["a", "b", "c"], columns=["one", "two"])

In [653]:
df3 = df2 - df2.mean()

In [654]:
df2

        one       two
a  0.406755  0.429601
b -0.422266  0.129899
c -0.574466 -1.595403

In [655]:
df3

        one       two
a  0.603414  0.774902
b -0.225607  0.475201
c -0.377807 -1.250102

In [656]:
df.reindex_like(df2)

        one       two
a  0.406755  0.429601
b -0.422266  0.129899
c -0.574466 -1.595403

## <h3>Aligning objects with each other with <code>align</code></h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.align.html#pandas.Series.align" title="pandas.Series.align"><code>align()</code></a> method is the fastest way to simultaneously align two objects. It
supports a <code>join</code> argument (related to <a href="https://pandas.pydata.org/docs/user_guide/merging.html#merging">joining and merging</a>):</p>

<blockquote>
<div><ul>
<li><p><code>join='outer'</code>: take the union of the indexes (default)</p></li>
<li><p><code>join='left'</code>: use the calling object’s index</p></li>
<li><p><code>join='right'</code>: use the passed object’s index</p></li>
<li><p><code>join='inner'</code>: intersect the indexes</p></li>
</ul>
</div></blockquote>

<p>It returns a tuple with both of the reindexed Series:</p>

In [657]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

In [658]:
s1 = s[:4]

In [659]:
s2 = s[1:]

In [660]:
s1.align(s2)

(a   -0.792381
 b   -2.028916
 c   -1.557008
 d   -0.829204
 e         NaN
 dtype: float64,
 a         NaN
 b   -2.028916
 c   -1.557008
 d   -0.829204
 e    1.285756
 dtype: float64)

In [661]:
s1.align(s2, join="inner")

(b   -2.028916
 c   -1.557008
 d   -0.829204
 dtype: float64,
 b   -2.028916
 c   -1.557008
 d   -0.829204
 dtype: float64)

In [662]:
s1.align(s2, join="left")

(a   -0.792381
 b   -2.028916
 c   -1.557008
 d   -0.829204
 dtype: float64,
 a         NaN
 b   -2.028916
 c   -1.557008
 d   -0.829204
 dtype: float64)

<p>For DataFrames, the join method will be applied to both the index and the columns by default:</p>

In [663]:
df.align(df2, join="inner")

(        one       two
 a  0.406755  0.429601
 b -0.422266  0.129899
 c -0.574466 -1.595403,
         one       two
 a  0.406755  0.429601
 b -0.422266  0.129899
 c -0.574466 -1.595403)

<p>You can also pass an <code>axis</code> option to only align on the specified axis:</p>

In [664]:
df.align(df2, join="inner", axis=0)

(        one       two     three
 a  0.406755  0.429601       NaN
 b -0.422266  0.129899  1.043537
 c -0.574466 -1.595403 -0.210028,
         one       two
 a  0.406755  0.429601
 b -0.422266  0.129899
 c -0.574466 -1.595403)

<p>If you pass a Series to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.align.html#pandas.DataFrame.align" title="pandas.DataFrame.align"><code>DataFrame.align()</code></a>, you can choose to align both objects either on the DataFrame’s index or columns using the <code>axis</code> argument:</p>

In [665]:
df.align(df2.iloc[0], axis=1)

(        one     three       two
 a  0.406755       NaN  0.429601
 b -0.422266  1.043537  0.129899
 c -0.574466 -0.210028 -1.595403
 d       NaN -0.433825  1.194943,
 one      0.406755
 three         NaN
 two      0.429601
 Name: a, dtype: float64)

## <h3>Filling while reindexing</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</code></a> takes an optional parameter <code>method</code> which is a filling method chosen from the following table:</p>

<table class="table">
<colgroup>
<col style="width: 37.5%">
<col style="width: 62.5%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Method</p></th>
<th class="head"><p>Action</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>pad / ffill</p></td>
<td><p>Fill values forward</p></td>
</tr>
<tr class="row-odd"><td><p>bfill / backfill</p></td>
<td><p>Fill values backward</p></td>
</tr>
<tr class="row-even"><td><p>nearest</p></td>
<td><p>Fill from the nearest index value</p></td>
</tr>
</tbody>
</table>

<p>We illustrate these fill methods on a simple Series:</p>

In [666]:
rng = pd.date_range("1/3/2000", periods=8)

In [667]:
ts = pd.Series(np.random.randn(8), index=rng)

In [668]:
ts2 = ts.iloc[[0, 3, 6]]

In [669]:
ts

2000-01-03    0.144683
2000-01-04   -0.872957
2000-01-05    1.470476
2000-01-06   -0.114758
2000-01-07   -0.298444
2000-01-08   -0.793208
2000-01-09    0.267582
2000-01-10    0.057230
Freq: D, dtype: float64

In [670]:
ts2

2000-01-03    0.144683
2000-01-06   -0.114758
2000-01-09    0.267582
Freq: 3D, dtype: float64

In [671]:
ts2.reindex(ts.index)

2000-01-03    0.144683
2000-01-04         NaN
2000-01-05         NaN
2000-01-06   -0.114758
2000-01-07         NaN
2000-01-08         NaN
2000-01-09    0.267582
2000-01-10         NaN
Freq: D, dtype: float64

In [672]:
ts2.reindex(ts.index, method="ffill")

2000-01-03    0.144683
2000-01-04    0.144683
2000-01-05    0.144683
2000-01-06   -0.114758
2000-01-07   -0.114758
2000-01-08   -0.114758
2000-01-09    0.267582
2000-01-10    0.267582
Freq: D, dtype: float64

In [673]:
ts2.reindex(ts.index, method="bfill")

2000-01-03    0.144683
2000-01-04   -0.114758
2000-01-05   -0.114758
2000-01-06   -0.114758
2000-01-07    0.267582
2000-01-08    0.267582
2000-01-09    0.267582
2000-01-10         NaN
Freq: D, dtype: float64

In [674]:
ts2.reindex(ts.index, method="nearest")

2000-01-03    0.144683
2000-01-04    0.144683
2000-01-05   -0.114758
2000-01-06   -0.114758
2000-01-07   -0.114758
2000-01-08    0.267582
2000-01-09    0.267582
2000-01-10    0.267582
Freq: D, dtype: float64

<p>These methods require that the indexes are <strong>ordered</strong> increasing or decreasing.</p>

<p>Note that the same result could have been achieved using
<a href="https://pandas.pydata.org/docs/user_guide/missing_data.html#missing-data-fillna">ffill</a> (except for <code>method='nearest'</code>) or <a href="https://pandas.pydata.org/docs/user_guide/missing_data.html#missing-data-interpolate">interpolate</a>:</p>

In [675]:
ts2.reindex(ts.index).ffill()

2000-01-03    0.144683
2000-01-04    0.144683
2000-01-05    0.144683
2000-01-06   -0.114758
2000-01-07   -0.114758
2000-01-08   -0.114758
2000-01-09    0.267582
2000-01-10    0.267582
Freq: D, dtype: float64

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</code></a> will raise a ValueError if the index is not monotonically increasing or decreasing. <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.fillna.html#pandas.Series.fillna" title="pandas.Series.fillna"><code>fillna()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.interpolate.html#pandas.Series.interpolate" title="pandas.Series.interpolate"><code>interpolate()</code></a> will not perform any checks on the order of the index.</p>

## <h3>Limits on filling while reindexing</h3>

<p>The <code>limit</code> and <code>tolerance</code> arguments provide additional control over filling while reindexing. Limit specifies the maximum count of consecutive matches:</p>

In [676]:
ts2.reindex(ts.index, method="ffill", limit=1)

2000-01-03    0.144683
2000-01-04    0.144683
2000-01-05         NaN
2000-01-06   -0.114758
2000-01-07   -0.114758
2000-01-08         NaN
2000-01-09    0.267582
2000-01-10    0.267582
Freq: D, dtype: float64

<p>In contrast, tolerance specifies the maximum distance between the index and indexer values:</p>

In [677]:
ts2.reindex(ts.index, method="ffill", tolerance="1 day")

2000-01-03    0.144683
2000-01-04    0.144683
2000-01-05         NaN
2000-01-06   -0.114758
2000-01-07   -0.114758
2000-01-08         NaN
2000-01-09    0.267582
2000-01-10    0.267582
Freq: D, dtype: float64

<p>Notice that when used on a <code>DatetimeIndex</code>, <code>TimedeltaIndex</code> or <code>PeriodIndex</code>, <code>tolerance</code> will coerced into a <code>Timedelta</code> if possible.
This allows you to specify tolerance with appropriate strings.</p>

## <h3>Dropping labels from an axis</h3>

<p>A method closely related to <code>reindex</code> is the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html#pandas.DataFrame.drop" title="pandas.DataFrame.drop"><code>drop()</code></a> function.
It removes a set of labels from an axis:</p>

In [678]:
df

        one       two     three
a  0.406755  0.429601       NaN
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028
d       NaN  1.194943 -0.433825

In [679]:
df.drop(["a", "d"], axis=0)

        one       two     three
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028

In [680]:
df.drop(["one"], axis=1)

        two     three
a  0.429601       NaN
b  0.129899  1.043537
c -1.595403 -0.210028
d  1.194943 -0.433825

<p>Note that the following also works, but is a bit less obvious / clean:</p>

In [681]:
df.reindex(df.index.difference(["a", "d"]))

        one       two     three
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028

## <h3>Renaming / mapping labels</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename" title="pandas.DataFrame.rename"><code>rename()</code></a> method allows you to relabel an axis based on some mapping (a dict or Series) or an arbitrary function.</p>

In [682]:
s

a   -0.792381
b   -2.028916
c   -1.557008
d   -0.829204
e    1.285756
dtype: float64

In [683]:
s.rename(str.upper)

A   -0.792381
B   -2.028916
C   -1.557008
D   -0.829204
E    1.285756
dtype: float64

<p>If you pass a function, it must return a value when called with any of the labels (and must produce a set of unique values). A dict or
Series can also be used:</p>

In [684]:
df.rename(
       columns={"one": "foo", "two": "bar"},
       index={"a": "apple", "b": "banana", "d": "durian"},
   )

             foo       bar     three
apple   0.406755  0.429601       NaN
banana -0.422266  0.129899  1.043537
c      -0.574466 -1.595403 -0.210028
durian       NaN  1.194943 -0.433825

<p>If the mapping doesn’t include a column/index label, it isn’t renamed. Note that extra labels in the mapping don’t throw an error.</p>
<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename" title="pandas.DataFrame.rename"><code>DataFrame.rename()</code></a> also supports an “axis-style” calling convention, where you specify a single <code>mapper</code> and the <code>axis</code> to apply that mapping to.</p>

In [685]:
df.rename({"one": "foo", "two": "bar"}, axis="columns")

        foo       bar     three
a  0.406755  0.429601       NaN
b -0.422266  0.129899  1.043537
c -0.574466 -1.595403 -0.210028
d       NaN  1.194943 -0.433825

In [686]:
df.rename({"a": "apple", "b": "banana", "d": "durian"}, axis="index")

             one       two     three
apple   0.406755  0.429601       NaN
banana -0.422266  0.129899  1.043537
c      -0.574466 -1.595403 -0.210028
durian       NaN  1.194943 -0.433825

<p>Finally, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.rename.html#pandas.Series.rename" title="pandas.Series.rename"><code>rename()</code></a> also accepts a scalar or list-like for altering the <code>Series.name</code> attribute.</p>

In [687]:
s.rename("scalar-name")

a   -0.792381
b   -2.028916
c   -1.557008
d   -0.829204
e    1.285756
Name: scalar-name, dtype: float64

<p>The methods <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename_axis.html#pandas.DataFrame.rename_axis" title="pandas.DataFrame.rename_axis"><code>DataFrame.rename_axis()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.rename_axis.html#pandas.Series.rename_axis" title="pandas.Series.rename_axis"><code>Series.rename_axis()</code></a> allow specific names of a <code>MultiIndex</code> to be changed (as opposed to the labels).</p>

In [688]:
 df = pd.DataFrame(
       {"x": [1, 2, 3, 4, 5, 6], "y": [10, 20, 30, 40, 50, 60]},
       index=pd.MultiIndex.from_product(
           [["a", "b", "c"], [1, 2]], names=["let", "num"]
       ),
   )

In [689]:
df

         x   y
let num
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [690]:
df.rename_axis(index={"let": "abc"})

         x   y
abc num
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [691]:
df.rename_axis(index=str.upper)

         x   y
LET NUM
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

# <h2>Iteration</h2>

<p>The behavior of basic iteration over pandas objects depends on the type. When iterating over a Series, it is regarded as array-like, and basic iteration produces the values. DataFrames follow the dict-like convention of iterating over the “keys” of the objects.</p>

<p>In short, basic iteration (<code>for i in object</code>) produces:</p>

<ul>
<li><p><strong>Series</strong>: values</p></li>
<li><p><strong>DataFrame</strong>: column labels</p></li>
</ul>

<p>Thus, for example, iterating over a DataFrame gives you the column names:</p>

In [692]:
df = pd.DataFrame(
       {"col1": np.random.randn(3), "col2": np.random.randn(3)}, index=["a", "b", "c"]
   )

In [693]:
for col in df:
    print(col)

col1
col2

<p>pandas objects also have the dict-like <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.items.html" title="pandas.DataFrame.items"><code>items()</code></a> method to iterate over the (key, value) pairs.</p>

<p>To iterate over the rows of a DataFrame, you can use the following methods:</p>

<ul>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a>: Iterate over the rows of a DataFrame as (index, Series) pairs.
This converts the rows to Series objects, which can change the dtypes and has some performance implications.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html" title="pandas.DataFrame.itertuples"><code>itertuples()</code></a>: Iterate over the rows of a DataFrame as namedtuples of the values.  This is a lot faster than <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a>, and is in most cases preferable to use to iterate over the values of a DataFrame.</p></li>
</ul>

<div class="alert alert-block alert-warning">
<p>Warning</p>

<p>Iterating through pandas objects is generally <strong>slow</strong>. In many cases, iterating manually over the rows is not needed and can be avoided with one of the following approaches:</p>

<ul>
<li><p>Look for a <em>vectorized</em> solution: many operations can be performed using built-in methods or NumPy functions, (boolean) indexing, …</p></li>
<li><p>When you have a function that cannot work on the full DataFrame/Series at once, it is better to use <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> instead of iterating over the values. See the docs on <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-apply">function application</a>.</p></li>
<li><p>If you need to do iterative manipulations on the values but performance is important, consider writing the inner loop with cython or numba. See the <a href="https://pandas.pydata.org/docs/user_guide/enhancingperf.html#enhancingperf">enhancing performance</a> section for some examples of this approach.</p></li>
</ul>
</div>

<div class="alert alert-block alert-warning">
<p>Warning</p>
<p>You should <strong>never modify</strong> something you are iterating over. This is not guaranteed to work in all cases. Depending on the
data types, the iterator returns a copy and not a view, and writing to it will have no effect!</p>

<p>For example, in the following case setting the value has no effect:</p>

In [694]:
df = pd.DataFrame({"a": [1, 2, 3], "b": ["a", "b", "c"]})

In [695]:
for index, row in df.iterrows():
    row["a"] = 10

In [696]:
df

   a  b
0  1  a
1  2  b
2  3  c

## <h3>items</h3>

<p>Consistent with the dict-like interface, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.items.html#pandas.DataFrame.items" title="pandas.DataFrame.items"><code>items()</code></a> iterates through key-value pairs:</p>

<ul>
<li><p><strong>Series</strong>: (index, scalar value) pairs</p></li>
<li><p><strong>DataFrame</strong>: (column, Series) pairs</p></li>
</ul>

<p>For example:</p>

In [697]:
for label, ser in df.items():
    print(label)
    print(ser)

a
0    1
1    2
2    3
Name: a, dtype: int64
b
0    a
1    b
2    c
Name: b, dtype: object

## <h3>iterrows</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a> allows you to iterate through the rows of a DataFrame as Series objects. It returns an iterator yielding each index value along with a Series containing the data in each row:</p>

In [698]:
for row_index, row in df.iterrows():
    print(row_index, row, sep="\n")

0
a    1
b    a
Name: 0, dtype: object
1
a    2
b    b
Name: 1, dtype: object
2
a    3
b    c
Name: 2, dtype: object

<div class="alert alert-block alert-info">
<p>Note</p>
<p>Because <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a> returns a Series for each row, it does <strong>not</strong> preserve dtypes across the rows (dtypes are preserved across columns for DataFrames). For example,</p>

In [699]:
df_orig = pd.DataFrame([[1, 1.5]], columns=["int", "float"])

In [700]:
df_orig.dtypes

int        int64
float    float64
dtype: object

In [701]:
row = next(df_orig.iterrows())[1]

In [702]:
row

int      1.0
float    1.5
Name: 0, dtype: float64

<p>All values in <code>row</code>, returned as a Series, are now upcasted to floats, also the original integer value in column <code>x</code>:</p>

In [703]:
row["int"].dtype

dtype('float64')

In [704]:
df_orig["int"].dtype

dtype('int64')

<p>To preserve dtypes while iterating over the rows, it is better to use <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html" title="pandas.DataFrame.itertuples"><code>itertuples()</code></a> which returns namedtuples of the values and which is generally much faster than <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a>.</p>

<p>For instance, a contrived way to transpose the DataFrame would be:</p>

In [705]:
df2 = pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})

In [706]:
print(df2)

   x  y
0  1  4
1  2  5
2  3  6

In [707]:
print(df2.T)

   0  1  2
x  1  2  3
y  4  5  6

In [708]:
df2_t = pd.DataFrame({idx: values for idx, values in df2.iterrows()})

In [709]:
print(df2_t)

   0  1  2
x  1  2  3
y  4  5  6

## <h3>itertuples</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</code></a> method will return an iterator yielding a namedtuple for each row in the DataFrame. The first element of the tuple will be the row’s corresponding index value, while the remaining values are the row values.</p>

<p>For instance:</p>

In [710]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, a=1, b='a')
Pandas(Index=1, a=2, b='b')
Pandas(Index=2, a=3, b='c')

<p>This method does not convert the row to a Series object; it merely returns the values inside a namedtuple. Therefore,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html" title="pandas.DataFrame.itertuples"><code>itertuples()</code></a> preserves the data type of the values and is generally faster as <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a>.</p>

<div class="alert alert-block alert-info">
<p>Note</p>
<p>The column names will be renamed to positional names if they are invalid Python identifiers, repeated, or start with an underscore.
With a large number of columns (&gt;255), regular tuples are returned.</p>
</div>

# <h2>.dt accessor</h2>

<p><code>Series</code> has an accessor to succinctly return datetime like properties for the <em>values</em> of the Series, if it is a datetime/period like Series.
This will return a Series, indexed like the existing Series.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell106"># datetime
In [272]: s = pd.Series(pd.date_range("20130101 09:10:12", periods=4))

In [273]: s
Out[273]: 
0   2013-01-01 09:10:12
1   2013-01-02 09:10:12
2   2013-01-03 09:10:12
3   2013-01-04 09:10:12
dtype: datetime64[ns]

In [274]: s.dt.hour
Out[274]: 
0    9
1    9
2    9
3    9
dtype: int32

In [275]: s.dt.second
Out[275]: 
0    12
1    12
2    12
3    12
dtype: int32

In [276]: s.dt.day
Out[276]: 
0    1
1    2
2    3
3    4
dtype: int32
</pre>
</div>
</div>

<p>This enables nice expressions like this:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell107">In [277]: s[s.dt.day == 2]
Out[277]: 
1   2013-01-02 09:10:12
dtype: datetime64[ns]
</pre>
</div>
</div>

<p>You can easily produces tz aware transformations:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell108">In [278]: stz = s.dt.tz_localize("US/Eastern")

In [279]: stz
Out[279]: 
0   2013-01-01 09:10:12-05:00
1   2013-01-02 09:10:12-05:00
2   2013-01-03 09:10:12-05:00
3   2013-01-04 09:10:12-05:00
dtype: datetime64[ns, US/Eastern]

In [280]: stz.dt.tz
Out[280]: &lt;DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD&gt;
</pre>
</div>
</div>

<p>You can also chain these types of operations:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell109">In [281]: s.dt.tz_localize("UTC").dt.tz_convert("US/Eastern")
Out[281]: 
0   2013-01-01 04:10:12-05:00
1   2013-01-02 04:10:12-05:00
2   2013-01-03 04:10:12-05:00
3   2013-01-04 04:10:12-05:00
dtype: datetime64[ns, US/Eastern]
</pre>
</div>
</div>

<p>You can also format datetime values as strings with <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.strftime.html#pandas.Series.dt.strftime" title="pandas.Series.dt.strftime"><code>Series.dt.strftime()</code></a> which supports the same format as the standard <a href="https://docs.python.org/3/library/datetime.html#datetime.datetime.strftime" title="(in Python v3.13)"><code>strftime()</code></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell110"># DatetimeIndex
In [282]: s = pd.Series(pd.date_range("20130101", periods=4))

In [283]: s
Out[283]: 
0   2013-01-01
1   2013-01-02
2   2013-01-03
3   2013-01-04
dtype: datetime64[ns]

In [284]: s.dt.strftime("%Y/%m/<span class="si">%d")
Out[284]: 
0    2013/01/01
1    2013/01/02
2    2013/01/03
3    2013/01/04
dtype: object
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell111"># PeriodIndex
In [285]: s = pd.Series(pd.period_range("20130101", periods=4))

In [286]: s
Out[286]: 
0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [287]: s.dt.strftime("%Y/%m/<span class="si">%d")
Out[287]: 
0    2013/01/01
1    2013/01/02
2    2013/01/03
3    2013/01/04
dtype: object
</pre>
</div>
</div>

<p>The <code>.dt</code> accessor works for period and timedelta dtypes.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell112"># period
In [288]: s = pd.Series(pd.period_range("20130101", periods=4, freq="D"))

In [289]: s
Out[289]: 
0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [290]: s.dt.year
Out[290]: 
0    2013
1    2013
2    2013
3    2013
dtype: int64

In [291]: s.dt.day
Out[291]: 
0    1
1    2
2    3
3    4
dtype: int64
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell113"># timedelta
In [292]: s = pd.Series(pd.timedelta_range("1 day 00:00:05", periods=4, freq="s"))

In [293]: s
Out[293]: 
0   1 days 00:00:05
1   1 days 00:00:06
2   1 days 00:00:07
3   1 days 00:00:08
dtype: timedelta64[ns]

In [294]: s.dt.days
Out[294]: 
0    1
1    1
2    1
3    1
dtype: int64

In [295]: s.dt.seconds
Out[295]: 
0    5
1    6
2    7
3    8
dtype: int32

In [296]: s.dt.components
Out[296]: 
   days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0     1      0        0        5             0             0            0
1     1      0        0        6             0             0            0
2     1      0        0        7             0             0            0
3     1      0        0        8             0             0            0
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>Series.dt</code> will raise a <code>TypeError</code> if you access with a non-datetime-like values.</p>
</div>

# <h2>Vectorized string methods</h2>

<p>Series is equipped with a set of string processing methods that make it easy to operate on each element of the array. Perhaps most importantly, these methods exclude missing/NA values automatically. These are accessed via the Series’s <code>str</code> attribute and generally have names matching the equivalent (scalar) built-in string methods. For example:</p>
<blockquote>

In [711]:
s = pd.Series(
    ["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"], dtype="string"
)

s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5    <NA>
6    caba
7     dog
8     cat
dtype: string

<p>Powerful pattern-matching methods are provided as well, but note that pattern-matching generally uses <a href="https://docs.python.org/3/library/re.html">regular expressions</a> by default (and in some cases always uses them).</p>

<div class="alert alert-block alert-info">
<p>Note</p>
<p>Prior to pandas 1.0, string methods were only available on <code>object</code> -dtype <code>Series</code>. Pandas 1.0 added the <a href="https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html" title="pandas.StringDtype"><code>StringDtype</code></a> which is dedicated to strings. See <a href="text.html#text-types">Text data types</a> for more.</p>
</div>

<p>Please see <a href="https://pandas.pydata.org/docs/user_guide/text.html#text-string-methods">Vectorized String Methods</a> for a complete
description.</p>

# <h2>Sorting</h2>

<p>pandas supports three kinds of sorting: sorting by index labels,
sorting by column values, and sorting by a combination of both.</p>

## <h3>By index</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.sort_index.html" title="pandas.Series.sort_index"><code>Series.sort_index()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html" title="pandas.DataFrame.sort_index"><code>DataFrame.sort_index()</code></a> methods are used to sort a pandas object by its index levels.</p>

In [712]:
df = pd.DataFrame(
       {
           "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
           "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
           "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
       }
   )

In [713]:
unsorted_df = df.reindex(
       index=["a", "d", "c", "b"], columns=["three", "two", "one"]
   )

unsorted_df

      three       two       one
a       NaN -1.209628 -0.571197
d  0.843047  2.135376       NaN
c -0.644879 -0.084409  0.086390
b -0.881096 -0.128502  0.071322

In [714]:
# DataFrame
unsorted_df.sort_index()

      three       two       one
a       NaN -1.209628 -0.571197
b -0.881096 -0.128502  0.071322
c -0.644879 -0.084409  0.086390
d  0.843047  2.135376       NaN

In [715]:
unsorted_df.sort_index(ascending=False)

      three       two       one
d  0.843047  2.135376       NaN
c -0.644879 -0.084409  0.086390
b -0.881096 -0.128502  0.071322
a       NaN -1.209628 -0.571197

In [716]:
unsorted_df.sort_index(axis=1)

        one     three       two
a -0.571197       NaN -1.209628
d       NaN  0.843047  2.135376
c  0.086390 -0.644879 -0.084409
b  0.071322 -0.881096 -0.128502

In [717]:
# Series
unsorted_df["three"].sort_index()

a         NaN
b   -0.881096
c   -0.644879
d    0.843047
Name: three, dtype: float64

<p id="basics-sort-index-key">Sorting by index also supports a <code>key</code> parameter that takes a callable
function to apply to the index being sorted. For <code>MultiIndex</code> objects, the key is applied per-level to the levels specified by <code>level</code>.</p>

In [718]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
       list("ab")
   )

s1

     c
a b
B 1  2
a 2  3
C 3  4

In [719]:
s1.sort_index(level="a")

     c
a b
B 1  2
C 3  4
a 2  3

In [720]:
s1.sort_index(level="a", key=lambda idx: idx.str.lower())

     c
a b
a 2  3
B 1  2
C 3  4

<p>For information on key sorting by value, see <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-sort-value-key">value sorting</a>.</p>

## <h3>By values</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.sort_values.html#pandas.Series.sort_values" title="pandas.Series.sort_values"><code>Series.sort_values()</code></a> method is used to sort a <code>Series</code> by its values. The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</code></a> method is used to sort a <code>DataFrame</code> by its column or row values.
The optional <code>by</code> parameter to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</code></a> may used to specify one or more columns to use to determine the sorted order.</p>

In [721]:
df1 = pd.DataFrame(
       {"one": [2, 1, 1, 1], "two": [1, 3, 2, 4], "three": [5, 4, 3, 2]}
   )

df1.sort_values(by="two")

   one  two  three
0    2    1      5
2    1    2      3
1    1    3      4
3    1    4      2

<p>The <code>by</code> parameter can take a list of column names, e.g.:</p>

In [722]:
df1[["one", "two", "three"]].sort_values(by=["one", "two"])

   one  two  three
2    1    2      3
1    1    3      4
3    1    4      2
0    2    1      5

<p>These methods have special treatment of NA values via the <code>na_position</code> argument:</p>

In [723]:
s[2] = np.nan

In [724]:
s.sort_values()

0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
2    <NA>
5    <NA>
dtype: string

In [725]:
s.sort_values(na_position="first")

2    <NA>
5    <NA>
0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
dtype: string

<p>Sorting also supports a <code>key</code> parameter that takes a callable function to apply to the values being sorted.</p>

In [726]:
s1 = pd.Series(["B", "a", "C"])

s1.sort_values()

0    B
2    C
1    a
dtype: object

In [727]:
s1.sort_values(key=lambda x: x.str.lower())

1    a
0    B
2    C
dtype: object

<p><code>key</code> will be given the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> of values and should return a <code>Series</code> or array of the same shape with the transformed values. For <code>DataFrame</code> objects,
the key is applied per column, so the key should still expect a Series and return a Series, e.g.</p>

In [728]:
df = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3]})

df.sort_values(by="a")

   a  b
0  B  1
2  C  3
1  a  2

In [729]:
df.sort_values(by="a", key=lambda col: col.str.lower())

   a  b
1  a  2
0  B  1
2  C  3

<p>The name or type of each column can be used to apply different functions to different columns.</p>

## <h3>By indexes and values</h3>

<p>Strings passed as the <code>by</code> parameter to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</code></a> may
refer to either columns or index level names.</p>

In [730]:
# Build MultiIndex
idx = pd.MultiIndex.from_tuples(
       [("a", 1), ("a", 2), ("a", 2), ("b", 2), ("b", 1), ("b", 1)]
   )

idx.names = ["first", "second"]

In [731]:
# Build DataFrame
df_multi = pd.DataFrame({"A": np.arange(6, 0, -1)}, index=idx)

In [732]:
df_multi

              A
first second
a     1       6
      2       5
      2       4
b     2       3
      1       2
      1       1

<p>Sort by ‘second’ (index) and ‘A’ (column)</p>

In [733]:
df_multi.sort_values(by=["second", "A"])

              A
first second
b     1       1
      1       2
a     1       6
b     2       3
a     2       4
      2       5

<div class="alert alert-block alert-info">
<p>Note</p>
<p>If a string matches both a column name and an index level name then a
warning is issued and the column takes precedence. This will result in an ambiguity error in a future version.</p>
</div>

## <h3>searchsorted</h3>

<p>Series has the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.searchsorted.html" title="pandas.Series.searchsorted"><code>searchsorted()</code></a> method, which works similarly to <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.searchsorted.html" title="(in NumPy v2.3)"><code>numpy.ndarray.searchsorted()</code></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell127">In [327]: ser = pd.Series([1, 2, 3])

In [328]: ser.searchsorted([0, 3])
Out[328]: array([0, 2])

In [329]: ser.searchsorted([0, 4])
Out[329]: array([0, 3])

In [330]: ser.searchsorted([1, 3], side="right")
Out[330]: array([1, 3])

In [331]: ser.searchsorted([1, 3], side="left")
Out[331]: array([0, 2])

In [332]: ser = pd.Series([3, 1, 2])

In [333]: ser.searchsorted([0, 3], sorter=np.argsort(ser))
Out[333]: array([0, 2])
</pre>
</div>
</div>

## <h3>smallest / largest values</h3>

<p><code>Series</code> has the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.nsmallest.html" title="pandas.Series.nsmallest"><code>nsmallest()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.nlargest.html" title="pandas.Series.nlargest"><code>nlargest()</code></a> methods which return the smallest or largest n values. For a large <code>Series</code> this can be much faster than sorting the entire Series and calling <code>head(n)</code> on the result.</p>

In [734]:
s = pd.Series(np.random.permutation(10))

In [735]:
s

0    1
1    0
2    3
3    8
4    9
5    7
6    6
7    2
8    5
9    4
dtype: int64

In [736]:
s.sort_values()

1    0
0    1
7    2
2    3
9    4
8    5
6    6
5    7
3    8
4    9
dtype: int64

In [737]:
s.nsmallest(3)

1    0
0    1
7    2
dtype: int64

In [738]:
s.nlargest(3)

4    9
3    8
5    7
dtype: int64

<p><code>DataFrame</code> also has the <code>nlargest</code> and <code>nsmallest</code> methods.</p>

In [739]:
df = pd.DataFrame(
       {
           "a": [-2, -1, 1, 10, 8, 11, -1],
           "b": list("abdceff"),
           "c": [1.0, 2.0, 4.0, 3.2, np.nan, 3.0, 4.0],
       }
   )

In [740]:
df.nlargest(3, "a")

    a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN

In [741]:
df.nlargest(5, ["a", "c"])

    a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN
2   1  d  4.0
6  -1  f  4.0

In [742]:
df.nsmallest(3, "a")

   a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0

In [743]:
df.nsmallest(5, ["a", "c"])

   a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0
2  1  d  4.0
4  8  e  NaN

## <h3>Sorting by a MultiIndex column</h3>

<p>You must be explicit about sorting when the column is a MultiIndex, and fully specify
all levels to <code>by</code>.</p>

In [744]:
df1.columns = pd.MultiIndex.from_tuples(
    [("a", "one"), ("a", "two"), ("b", "three")]
)

In [745]:
df1.sort_values(by=("a", "two"))

    a         b
  one two three
0   2   1     5
2   1   2     3
1   1   3     4
3   1   4     2

# <h2>Copying</h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html" title="pandas.DataFrame.copy"><code>copy()</code></a> method on pandas objects copies the underlying data (though not the axis indexes, since they are immutable) and returns a new object.
Note that <strong>it is seldom necessary to copy objects</strong>. For example, there are only a handful of ways to alter a DataFrame <em>in-place</em>:</p>

<ul>
<li><p>Inserting, deleting, or modifying a column.</p></li>
<li><p>Assigning to the <code>index</code> or <code>columns</code> attributes.</p></li>
<li><p>For homogeneous data, directly modifying the values via the <code>values</code> attribute or advanced indexing.</p></li>
</ul>

<p>To be clear, no pandas method has the side effect of modifying your data; almost every method returns a new object, leaving the original object untouched. If the data is modified, it is because you did so explicitly.</p>

# <h2>dtypes</h2>

<p>For the most part, pandas uses NumPy arrays and dtypes for Series or individual columns of a DataFrame. NumPy provides support for <code>float</code>, <code>int</code>, <code>bool</code>, <code>timedelta64[ns]</code> and <code>datetime64[ns]</code> (note that NumPy does not support timezone-aware datetimes).</p>

<p>pandas and third-party libraries <em>extend</em> NumPy’s type system in a few places.
This section describes the extensions pandas has made internally.
See <a href="https://pandas.pydata.org/docs/development/extending.html#extending-extension-types">Extension types</a> for how to write your own extension that works with pandas. See <a href="https://pandas.pydata.org/community/ecosystem.html">the ecosystem page</a> for a list of third-party libraries that have implemented an extension.</p>

<p>The following table lists all of pandas extension types. For methods requiring <code>dtype</code> arguments, strings can be specified as indicated. See the respective documentation sections for more on each type.</p>

<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>Kind of Data</p></th>
<th class="head" colspan="2"><p>Data Type</p></th>
<th class="head" colspan="2"><p>Scalar</p></th>
<th class="head"><p>Array</p></th>
<th class="head"><p>String Aliases</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><a href="https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-timezone">tz-aware datetime</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DatetimeTZDtype.html" title="pandas.DatetimeTZDtype"><code>DatetimeTZDtype</code></a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html" title="pandas.Timestamp"><code>Timestamp</code></a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.DatetimeArray.html" title="pandas.arrays.DatetimeArray"><code>arrays.DatetimeArray</code></a></p></td>
<td><p><code>'datetime64[ns, &lt;tz&gt;]'</code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="https://pandas.pydata.org/docs/user_guide/categorical.html">Categorical</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.CategoricalDtype.html" title="pandas.CategoricalDtype"><code>CategoricalDtype</code></a></p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Categorical.html" title="pandas.Categorical"><code>Categorical</code></a></p></td>
<td><p><code>'category'</code></p></td>
</tr>
<tr class="row-even"><td><p><a href="https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-periods">period (time spans)</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.PeriodDtype.html" title="pandas.PeriodDtype"><code>PeriodDtype</code></a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Period.html" title="pandas.Period"><code>Period</code></a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.PeriodArray.html" title="pandas.arrays.PeriodArray"><code>arrays.PeriodArray</code></a>
<code>'Period[&lt;freq&gt;]'</code></p></td>
<td><p><code>'period[&lt;freq&gt;]'</code>,</p></td>
</tr>
<tr class="row-odd"><td><p><a href="https://pandas.pydata.org/docs/user_guide/sparse.html">sparse</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.SparseDtype.html" title="pandas.SparseDtype"><code>SparseDtype</code></a></p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.SparseArray.html" title="pandas.arrays.SparseArray"><code>arrays.SparseArray</code></a></p></td>
<td><p><code>'Sparse'</code>, <code>'Sparse[int]'</code>,
<code>'Sparse[float]'</code></p></td>
</tr>
<tr class="row-even"><td><p><a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-intervalindex">intervals</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.IntervalDtype.html" title="pandas.IntervalDtype"><code>IntervalDtype</code></a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Interval.html" title="pandas.Interval"><code>Interval</code></a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.IntervalArray.html" title="pandas.arrays.IntervalArray"><code>arrays.IntervalArray</code></a></p></td>
<td><p><code>'interval'</code>, <code>'Interval'</code>,
<code>'Interval[&lt;numpy_dtype&gt;]'</code>,
<code>'Interval[datetime64[ns, &lt;tz&gt;]]'</code>,
<code>'Interval[timedelta64[&lt;freq&gt;]]'</code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="https://pandas.pydata.org/docs/user_guide/integer_na.html">nullable integer</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Int64Dtype.html" title="pandas.Int64Dtype"><code>Int64Dtype</code></a>, …</p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.IntegerArray.html" title="pandas.arrays.IntegerArray"><code>arrays.IntegerArray</code></a></p></td>
<td><p><code>'Int8'</code>, <code>'Int16'</code>, <code>'Int32'</code>,
<code>'Int64'</code>, <code>'UInt8'</code>, <code>'UInt16'</code>,
<code>'UInt32'</code>, <code>'UInt64'</code></p></td>
</tr>
<tr class="row-even"><td><p><a href="https://pandas.pydata.org/docs/reference/arrays.html#api-arrays-float-na">nullable float</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Float64Dtype.html" title="pandas.Float64Dtype"><code>Float64Dtype</code></a>, …</p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.FloatingArray.html" title="pandas.arrays.FloatingArray"><code>arrays.FloatingArray</code></a></p></td>
<td><p><code>'Float32'</code>, <code>'Float64'</code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="text.html#text">Strings</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/user_guide/text.html" title="pandas.StringDtype"><code>StringDtype</code></a></p></td>
<td colspan="2"><p><a href="https://docs.python.org/3/library/stdtypes.html#str" title="(in Python v3.13)"><code>str</code></a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.StringArray.html" title="pandas.arrays.StringArray"><code>arrays.StringArray</code></a></p></td>
<td><p><code>'string'</code></p></td>
</tr>
<tr class="row-even"><td><p><a href="https://pandas.pydata.org/docs/reference/arrays.html#api-arrays-bool">Boolean (with NA)</a></p></td>
<td colspan="2"><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.BooleanDtype.html" title="pandas.BooleanDtype"><code>BooleanDtype</code></a></p></td>
<td colspan="2"><p><a href="https://docs.python.org/3/library/functions.html#bool" title="(in Python v3.13)"><code>bool</code></a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.arrays.BooleanArray.html" title="pandas.arrays.BooleanArray"><code>arrays.BooleanArray</code></a></p></td>
<td><p><code>'boolean'</code></p></td>
</tr>
</tbody>
</table>

<p>pandas has two ways to store strings.</p>

<ol>
<li><p><code>object</code> dtype, which can hold any Python object, including strings.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html" title="pandas.StringDtype"><code>StringDtype</code></a>, which is dedicated to strings.</p></li>
</ol>

<p>Generally, we recommend using <a href="https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html" title="pandas.StringDtype"><code>StringDtype</code></a>. See <a href="https://pandas.pydata.org/docs/user_guide/text.html#text-types">Text data types</a> for more.</p>

<p>Finally, arbitrary objects may be stored using the <code>object</code> dtype, but should be avoided to the extent possible (for performance and interoperability with other libraries and methods. See <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-object-conversion">object conversion</a>).</p>

<p>A convenient <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html" title="pandas.DataFrame.dtypes"><code>dtypes</code></a> attribute for DataFrame returns a Series with the data type of each column.</p>

In [746]:
dft = pd.DataFrame(
       {
           "A": np.random.rand(3),
           "B": 1,
           "C": "foo",
           "D": pd.Timestamp("20010102"),
           "E": pd.Series([1.0] * 3).astype("float32"),
           "F": False,
           "G": pd.Series([1] * 3, dtype="int8"),
       }
   )

In [747]:
dft

          A  B    C          D    E      F  G
0  0.063588  1  foo 2001-01-02  1.0  False  1
1  0.500784  1  foo 2001-01-02  1.0  False  1
2  0.890190  1  foo 2001-01-02  1.0  False  1

In [748]:
dft.dtypes

A          float64
B            int64
C           object
D    datetime64[s]
E          float32
F             bool
G             int8
dtype: object

<p>On a <code>Series</code> object, use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.dtype.html" title="pandas.Series.dtype"><code>dtype</code></a> attribute.</p>

In [749]:
dft["A"].dtype

dtype('float64')

<p>If a pandas object contains data with multiple dtypes <em>in a single column</em>, the dtype of the column will be chosen to accommodate all of the data types (<code>object</code> is the most general).</p>

In [750]:
# these ints are coerced to floats
pd.Series([1, 2, 3, 4, 5, 6.0])

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [751]:
# string data forces an ``object`` dtype
pd.Series([1, 2, 3, 6.0, "foo"])

0      1
1      2
2      3
3    6.0
4    foo
dtype: object

<p>The number of columns of each type in a <code>DataFrame</code> can be found by calling <code>DataFrame.dtypes.value_counts()</code>.</p>

In [752]:
dft.dtypes.value_counts()

float64          1
int64            1
object           1
datetime64[s]    1
float32          1
bool             1
int8             1
Name: count, dtype: int64

<p>Numeric dtypes will propagate and can coexist in DataFrames.
If a dtype is passed (either directly via the <code>dtype</code> keyword, a passed <code>ndarray</code>, or a passed <code>Series</code>), then it will be preserved in DataFrame operations. Furthermore, different numeric dtypes will <strong>NOT</strong> be combined. The following example will give you a taste.</p>

In [753]:
df1 = pd.DataFrame(np.random.randn(8, 1), columns=["A"], dtype="float32")

In [754]:
df1

          A
0  0.092167
1 -0.422098
2 -0.430068
3  0.882588
4  1.310577
5  0.183565
6 -0.146818
7  1.617424

In [755]:
df1.dtypes

A    float32
dtype: object

In [756]:
df2 = pd.DataFrame(
       {
           "A": pd.Series(np.random.randn(8), dtype="float16"),
           "B": pd.Series(np.random.randn(8)),
           "C": pd.Series(np.random.randint(0, 255, size=8), dtype="uint8"),  # [0,255] (range of uint8)
       }
   )

In [757]:
df2

          A         B    C
0 -1.504883 -0.280484  214
1 -0.680176  0.759361  228
2 -0.082825  0.264951  139
3  1.071289  0.627193  163
4  1.104492 -1.084742   74
5  1.032227  0.342222    2
6  0.435303  0.889464   58
7  0.301025  2.088440   15

In [758]:
df2.dtypes

A    float16
B    float64
C      uint8
dtype: object

## <h3>defaults</h3>

<p>By default integer types are <code>int64</code> and float types are <code>float64</code>, <em>regardless</em> of platform (32-bit or 64-bit).
The following will all result in <code>int64</code> dtypes.</p>

In [759]:
pd.DataFrame([1, 2], columns=["a"]).dtypes

a    int64
dtype: object

In [760]:
pd.DataFrame({"a": [1, 2]}).dtypes

a    int64
dtype: object

In [761]:
pd.DataFrame({"a": 1}, index=list(range(2))).dtypes

a    int64
dtype: object

<p>Note that Numpy will choose <em>platform-dependent</em> types when creating arrays.
The following <strong>WILL</strong> result in <code>int32</code> on 32-bit platform.</p>

In [762]:
frame = pd.DataFrame(np.array([1, 2]))

## <h3>upcasting</h3>

<p>Types can potentially be <em>upcasted</em> when combined with other types, meaning they are promoted
from the current type (e.g. <code>int</code> to <code>float</code>).</p>

In [763]:
df3 = df1.reindex_like(df2).fillna(value=0.0) + df2

In [764]:
df3

          A         B      C
0 -1.412716 -0.280484  214.0
1 -1.102274  0.759361  228.0
2 -0.512892  0.264951  139.0
3  1.953877  0.627193  163.0
4  2.415069 -1.084742   74.0
5  1.215791  0.342222    2.0
6  0.288484  0.889464   58.0
7  1.918449  2.088440   15.0

In [765]:
df3.dtypes

A    float32
B    float64
C    float64
dtype: object

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</code></a> will return the <em>lower-common-denominator</em> of the dtypes, meaning
the dtype that can accommodate <strong>ALL</strong> of the types in the resulting homogeneous dtyped NumPy array. This can
force some <em>upcasting</em>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell139">In [366]: df3.to_numpy().dtype
Out[366]: dtype('float64')
</pre>
</div>
</div>

In [766]:
df3.to_numpy().dtype

dtype('float64')

## <h3>astype</h3>

<p id="basics-cast">You can use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</code></a> method to explicitly convert dtypes from one to another. These will by default return a copy, even if the dtype was unchanged (pass <code>copy=False</code> to change this behavior). In addition, they will raise an exception if the astype operation is invalid.</p>

<p>Upcasting is always according to the <strong>NumPy</strong> rules. If two different dtypes are involved in an operation,
then the more <em>general</em> one will be used as the result of the operation.</p>

In [767]:
df3

          A         B      C
0 -1.412716 -0.280484  214.0
1 -1.102274  0.759361  228.0
2 -0.512892  0.264951  139.0
3  1.953877  0.627193  163.0
4  2.415069 -1.084742   74.0
5  1.215791  0.342222    2.0
6  0.288484  0.889464   58.0
7  1.918449  2.088440   15.0

In [768]:
df3.dtypes

A    float32
B    float64
C    float64
dtype: object

In [769]:
# conversion of dtypes
df3.astype("float32").dtypes

A    float32
B    float32
C    float32
dtype: object

<p>Convert a subset of columns to a specified type using <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</code></a>.</p>

In [770]:
dft = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})

In [771]:
dft[["a", "b"]] = dft[["a", "b"]].astype(np.uint8)

In [772]:
dft

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [773]:
dft.dtypes

a    uint8
b    uint8
c    int64
dtype: object

<p>Convert certain columns to a specific dtype by passing a dict to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</code></a>.</p>

In [774]:
dft1 = pd.DataFrame({"a": [1, 0, 1], "b": [4, 5, 6], "c": [7, 8, 9]})

In [775]:
dft1 = dft1.astype({"a": np.bool_, "c": np.float64})

In [776]:
dft1

       a  b    c
0   True  4  7.0
1  False  5  8.0
2   True  6  9.0

In [777]:
dft1.dtypes

a       bool
b      int64
c    float64
dtype: object

<div class="alert alert-block alert-info">
<p>Note</p>

<p>When trying to convert a subset of columns to a specified type using <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html" title="pandas.DataFrame.astype"><code>astype()</code></a>  and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html" title="pandas.DataFrame.loc"><code>loc()</code></a>, upcasting occurs.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html" title="pandas.DataFrame.loc"><code>loc()</code></a> tries to fit in what we are assigning to the current dtypes, while <code>[]</code> will overwrite them taking the dtype from the right hand side. Therefore the following piece of code produces the unintended result.</p>
</div>

In [778]:
dft = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})

In [779]:
dft.loc[:, ["a", "b"]].astype(np.uint8).dtypes

a    uint8
b    uint8
dtype: object

In [780]:
dft.loc[:, ["a", "b"]] = dft.loc[:, ["a", "b"]].astype(np.uint8)

In [781]:
dft.dtypes

a    int64
b    int64
c    int64
dtype: object

## <h3>object conversion</h3>

<p>pandas offers various functions to try to force conversion of types from the <code>object</code> dtype to other types.
In cases where the data is already of the correct type, but stored in an <code>object</code> array, the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.infer_objects.html" title="pandas.DataFrame.infer_objects"><code>DataFrame.infer_objects()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.infer_objects.html" title="pandas.Series.infer_objects"><code>Series.infer_objects()</code></a> methods can be used to soft convert to the correct type.</p>

In [782]:
import datetime

In [783]:
df = pd.DataFrame(
       [
           [1, 2],
           ["a", "b"],
           [datetime.datetime(2016, 3, 2), datetime.datetime(2016, 3, 2)],
       ]
   )

In [784]:
df = df.T

In [785]:
df

   0  1                    2
0  1  a  2016-03-02 00:00:00
1  2  b  2016-03-02 00:00:00

In [786]:
df.dtypes

0    object
1    object
2    object
dtype: object

<p>Because the data was transposed the original inference stored all columns as object, which <code>infer_objects</code> will correct.</p>

In [787]:
df.infer_objects().dtypes

0             int64
1            object
2    datetime64[ns]
dtype: object

<p>The following functions are available for one dimensional object arrays or scalars to perform hard conversion of objects to a specified type:</p>

<ul>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html" title="pandas.to_numeric"><code>to_numeric()</code></a> (conversion to numeric dtypes)</p>

In [788]:
m = ["1.1", 2, 3]

pd.to_numeric(m)

array([1.1, 2. , 3. ])

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html" title="pandas.to_datetime"><code>to_datetime()</code></a> (conversion to datetime objects)</p>

In [789]:
import datetime

m = ["2016-07-09", datetime.datetime(2016, 3, 2)]

pd.to_datetime(m)

DatetimeIndex(['2016-07-09', '2016-03-02'], dtype='datetime64[ns]', freq=None)

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.to_timedelta.html" title="pandas.to_timedelta"><code>to_timedelta()</code></a> (conversion to timedelta objects)</p>

In [790]:
m = ["5us", pd.Timedelta("1day")]

pd.to_timedelta(m)

TimedeltaIndex(['0 days 00:00:00.000005', '1 days 00:00:00'], dtype='timedelta64[ns]', freq=None)

<p>To force a conversion, we can pass in an <code>errors</code> argument, which specifies how pandas should deal with elements that cannot be converted to desired dtype or object. By default, <code>errors='raise'</code>, meaning that any errors encountered
will be raised during the conversion process. However, if <code>errors='coerce'</code>, these errors will be ignored and pandas will convert problematic elements to <code>pd.NaT</code> (for datetime and timedelta) or <code>np.nan</code> (for numeric). This might be useful if you are reading in data which is mostly of the desired dtype (e.g. numeric, datetime), but occasionally has non-conforming elements intermixed that you want to represent as missing:</p>

In [791]:
import datetime

m = ["apple", datetime.datetime(2016, 3, 2)]

pd.to_datetime(m, errors="coerce")

/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_56298/2710552240.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(m, errors="coerce")

DatetimeIndex(['NaT', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [792]:
m = ["apple", 2, 3]

pd.to_numeric(m, errors="coerce")

array([nan,  2.,  3.])

In [793]:
m = ["apple", pd.Timedelta("1day")]

pd.to_timedelta(m, errors="coerce")

TimedeltaIndex([NaT, '1 days'], dtype='timedelta64[ns]', freq=None)

<p>In addition to object conversion, <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html" title="pandas.to_numeric"><code>to_numeric()</code></a> provides another argument <code>downcast</code>, which gives the option of downcasting the newly (or already) numeric data to a smaller dtype, which can conserve memory:</p>

In [794]:
m = ["1", 2, 3]

pd.to_numeric(m, downcast="integer")  # smallest signed int dtype

array([1, 2, 3], dtype=int8)

In [795]:
pd.to_numeric(m, downcast="signed")  # same as 'integer'

array([1, 2, 3], dtype=int8)

In [796]:
pd.to_numeric(m, downcast="unsigned")  # smallest unsigned int dtype

array([1, 2, 3], dtype=uint8)

In [797]:
pd.to_numeric(m, downcast="float")  # smallest float dtype

array([1., 2., 3.], dtype=float32)

<p>As these methods apply only to one-dimensional arrays, lists or scalars; they cannot be used directly on multi-dimensional objects such
as DataFrames. However, with <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html" title="pandas.DataFrame.apply"><code>apply()</code></a>, we can “apply” the function over each column efficiently:</p>

In [798]:
import datetime

df = pd.DataFrame([["2016-07-09", datetime.datetime(2016, 3, 2)]] * 2, dtype="O")

In [799]:
df

            0                    1
0  2016-07-09  2016-03-02 00:00:00
1  2016-07-09  2016-03-02 00:00:00

In [800]:
df.apply(pd.to_datetime)

           0          1
0 2016-07-09 2016-03-02
1 2016-07-09 2016-03-02

In [801]:
df = pd.DataFrame([["1.1", 2, 3]] * 2, dtype="O")

In [802]:
df

     0  1  2
0  1.1  2  3
1  1.1  2  3

In [803]:
df.apply(pd.to_numeric)

     0  1  2
0  1.1  2  3
1  1.1  2  3

In [804]:
df = pd.DataFrame([["5us", pd.Timedelta("1day")]] * 2, dtype="O")

In [805]:
df

     0                1
0  5us  1 days 00:00:00
1  5us  1 days 00:00:00

In [806]:
df.apply(pd.to_timedelta)

                       0      1
0 0 days 00:00:00.000005 1 days
1 0 days 00:00:00.000005 1 days

## <h3>gotchas</h3>

<p>Performing selection operations on <code>integer</code> type data can easily upcast the data to <code>floating</code>.
The dtype of the input data will be preserved in cases where <code>nans</code> are not introduced.
See also <a href="https://pandas.pydata.org/docs/user_guide/gotchas.html#gotchas-intna">Support for integer NA</a>.</p>

In [807]:
dfi = df3.astype("int32")

In [808]:
dfi["E"] = 1

In [809]:
dfi

   A  B    C  E
0 -1  0  214  1
1 -1  0  228  1
2  0  0  139  1
3  1  0  163  1
4  2 -1   74  1
5  1  0    2  1
6  0  0   58  1
7  1  2   15  1

In [810]:
dfi.dtypes

A    int32
B    int32
C    int32
E    int64
dtype: object

In [811]:
casted = dfi[dfi > 0]

In [812]:
casted

     A    B    C  E
0  NaN  NaN  214  1
1  NaN  NaN  228  1
2  NaN  NaN  139  1
3  1.0  NaN  163  1
4  2.0  NaN   74  1
5  1.0  NaN    2  1
6  NaN  NaN   58  1
7  1.0  2.0   15  1

In [813]:
casted.dtypes

A    float64
B    float64
C      int32
E      int64
dtype: object

<p>While float dtypes are unchanged.</p>

In [814]:
dfa = df3.copy()

In [815]:
dfa["A"] = dfa["A"].astype("float32")

In [816]:
dfa.dtypes

A    float32
B    float64
C    float64
dtype: object

In [817]:
casted = dfa[df2 > 0]

In [818]:
casted

          A         B      C
0       NaN       NaN  214.0
1       NaN  0.759361  228.0
2       NaN  0.264951  139.0
3  1.953877  0.627193  163.0
4  2.415069       NaN   74.0
5  1.215791  0.342222    2.0
6  0.288484  0.889464   58.0
7  1.918449  2.088440   15.0

In [819]:
casted.dtypes

A    float32
B    float64
C    float64
dtype: object

# <h2>Selecting columns based on <code>dtype</code></h2>

<p id="basics-selectdtypes">The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</code></a> method implements subsetting of columns based on their <code>dtype</code>.</p>

<p>First, let’s create a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> with a slew of different dtypes:</p>

In [820]:
df = pd.DataFrame(
       {
           "string": list("abc"),
           "int64": list(range(1, 4)),
           "uint8": np.arange(3, 6).astype("u1"),
           "float64": np.arange(4.0, 7.0),
           "bool1": [True, False, True],
           "bool2": [False, True, False],
           "dates": pd.date_range("now", periods=3),
           "category": pd.Series(list("ABC")).astype("category"),
       }
   )

In [821]:
df["tdeltas"] = df.dates.diff()

In [822]:
df["uint64"] = np.arange(3, 6).astype("u8")

In [823]:
df["other_dates"] = pd.date_range("20130101", periods=3)

In [824]:
df["tz_aware_dates"] = pd.date_range("20130101", periods=3, tz="US/Eastern")

In [825]:
df

,string,int64,uint8,float64,bool1,bool2,dates,category,tdeltas,uint64,other_dates,tz_aware_dates
0,a,1,3,4.0,True,False,2025-10-16 21:14:48.185379,A,NaT,3,2013-01-01,2013-01-01 00:00:00-05:00
1,b,2,4,5.0,False,True,2025-10-17 21:14:48.185379,B,1 days,4,2013-01-02,2013-01-02 00:00:00-05:00
2,c,3,5,6.0,True,False,2025-10-18 21:14:48.185379,C,1 days,5,2013-01-03,2013-01-03 00:00:00-05:00

<p>And the dtypes:</p>

In [826]:
df.dtypes

string                                object
int64                                  int64
uint8                                  uint8
float64                              float64
bool1                                   bool
bool2                                   bool
dates                         datetime64[ns]
category                            category
tdeltas                      timedelta64[ns]
uint64                                uint64
other_dates                   datetime64[ns]
tz_aware_dates    datetime64[ns, US/Eastern]
dtype: object

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</code></a> has two parameters <code>include</code> and <code>exclude</code> that allow you to say “give me the columns <em>with</em> these dtypes” (<code>include</code>) and/or “give the columns <em>without</em> these dtypes” (<code>exclude</code>).</p>

<p>For example, to select <code>bool</code> columns:</p>

In [827]:
df.select_dtypes(include=[bool])

   bool1  bool2
0   True  False
1  False   True
2   True  False

<p>You can also pass the name of a dtype in the <a href="https://numpy.org/doc/stable/reference/arrays.scalars.html">NumPy dtype hierarchy</a>:</p>

In [828]:
df.select_dtypes(include=["bool"])

   bool1  bool2
0   True  False
1  False   True
2   True  False

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</code></a> also works with generic dtypes as well.</p>

<p>For example, to select all numeric and boolean columns while excluding unsigned integers:</p>

In [829]:
df.select_dtypes(include=["number", "bool"], exclude=["unsignedinteger"])

   int64  float64  bool1  bool2 tdeltas
0      1      4.0   True  False     NaT
1      2      5.0  False   True  1 days
2      3      6.0   True  False  1 days

<p>To select string columns you must use the <code>object</code> dtype:</p>

In [830]:
df.select_dtypes(include=["object"])

  string
0      a
1      b
2      c

<p>To see all the child dtypes of a generic <code>dtype</code> like <code>numpy.number</code> you can define a function that returns a tree of child dtypes:</p>

In [831]:
def subdtypes(dtype):
    subs = dtype.__subclasses__()
    if not subs:
        return dtype
    return [dtype, [subdtypes(dt) for dt in subs]]

<p>All NumPy dtypes are subclasses of <code>numpy.generic</code>:</p>

In [832]:
subdtypes(np.generic)

[numpy.generic,
 [[numpy.number,
   [[numpy.integer,
     [[numpy.signedinteger,
       [numpy.int8,
        numpy.int16,
        numpy.int32,
        numpy.int64,
        numpy.longlong,
        numpy.timedelta64]],
      [numpy.unsignedinteger,
       [numpy.uint8,
        numpy.uint16,
        numpy.uint32,
        numpy.uint64,
        numpy.ulonglong]]]],
    [numpy.inexact,
     [[numpy.floating,
       [numpy.float16, numpy.float32, numpy.float64, numpy.longdouble]],
      [numpy.complexfloating,
       [numpy.complex64, numpy.complex128, numpy.clongdouble]]]]]],
  [numpy.flexible,
   [[numpy.character, [numpy.bytes_, numpy.str_]],
    [numpy.void, [numpy.record]]]],
  numpy.bool_,
  numpy.datetime64,
  numpy.object_]]