<h1>Essential basic functionality</h1>

<p>Here we discuss a lot of the essential functionality common to the pandas data structures. To begin, let’s create some example objects like we did in the <a href="https://pandas.pydata.org/docs/user_guide/10min.html#min">10 minutes to pandas</a> section:</p>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
index = pd.date_range("1/1/2000", periods=8)

In [ ]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

# <h2>Head and tail</h2>

<p>To view a small sample of a Series or DataFrame object, use the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html#pandas.DataFrame.head" title="pandas.DataFrame.head"><code>head()</span></code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail" title="pandas.DataFrame.tail"><code>tail()</span></code></a> methods. The default number of elements to display is five, but you may pass a custom number.</p>

In [ ]:
long_series = pd.Series(np.random.randn(1000))

In [ ]:
long_series.head()

0   -0.104536
1    0.658591
2   -0.386662
3    0.892256
4   -0.388905
dtype: float64

In [ ]:
long_series.tail(3)

997    0.806210
998    0.405328
999   -1.250269
dtype: float64

# <h2>Attributes and underlying data</h2>

<p>pandas objects have a number of attributes enabling you to access the metadata</p>

<ul>

<li><p><strong>shape</strong>: gives the axis dimensions of the object, consistent with ndarray</p></li>

<li><dl>
<dt>Axis labels</dt><dd><ul>
<li><p><strong>Series</strong>: <em>index</em> (only axis)</p></li>
<li><p><strong>DataFrame</strong>: <em>index</em> (rows) and <em>columns</em></p></li></ul></dd>
</dl>
</li>

</ul>

<p>Note, <strong>these attributes can be safely assigned to</strong>!</p>

In [ ]:
df[:2]

                   A         B         C
2000-01-01  0.043841 -0.822261 -1.077136
2000-01-02  0.423654 -0.289164  0.662691

In [ ]:
df.columns = [x.lower() for x in df.columns]

In [ ]:
df

                   a         b         c
2000-01-01  0.043841 -0.822261 -1.077136
2000-01-02  0.423654 -0.289164  0.662691
2000-01-03  0.820460 -1.901086 -1.128062
2000-01-04  1.435166 -1.460891  0.788760
2000-01-05  1.117427 -1.532363  0.284889
2000-01-06 -0.909828  0.030832  1.014516
2000-01-07 -0.024018 -0.250079 -0.542020
2000-01-08  0.057914  1.587020  0.611096

<p>pandas objects (<a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a>) can be thought of as containers for arrays, which hold the actual data and do the actual computation. For many types, the underlying array is a <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</span></code></a>. However, pandas and 3rd party libraries may <em>extend</em>
NumPy’s type system to add support for custom arrays (see <a href="https://pandas.pydata.org/docs/user_guide/basics.htmlhttps://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</span></a>).</p>

<p>To get the actual data inside a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</span></code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</span></code></a>, use the <code>.array</span></code> property</p>

In [ ]:
s.array

<NumpyExtensionArray>
[ np.float64(0.01689068411765619),  np.float64(-0.9269892725639515),
 np.float64(-0.08131708454153358),  np.float64(0.05178787769397035),
   np.float64(1.7530642860525267)]
Length: 5, dtype: float64

In [ ]:
s.index.array

<NumpyExtensionArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.array.html#pandas.Series.array" title="pandas.Series.array"><code>array</span></code></a> will always be an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</span></code></a>.
The exact details of what an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</span></code></a> is and why pandas uses them are a bit beyond the scope of this introduction. See <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</span></a> for more.</p>
<p>If you know you need a NumPy array, use <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</span></code></a> or <code>numpy.asarray()</span></code>.</p>

In [ ]:
s.to_numpy()

array([ 0.01689068, -0.92698927, -0.08131708,  0.05178788,  1.75306429])

In [ ]:
np.asarray(s)

array([ 0.01689068, -0.92698927, -0.08131708,  0.05178788,  1.75306429])

<p>When the Series or Index is backed by an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</span></code></a> may involve copying data and coercing values.
See <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</span></a> for more.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</span></code></a> gives some control over the <code>dtype</span></code> of the resulting <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</span></code></a>.
For example, consider datetimes with timezones.
NumPy doesn’t have a dtype to represent timezone-aware datetimes, so there are two possibly useful representations:</p>

<ol>
<li><p>An object-dtype <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</span></code></a> with <a href="https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html#pandas.Timestamp" title="pandas.Timestamp"><code>Timestamp</span></code></a> objects, each
with the correct <code>tz</span></code></p></li>
<li><p>A <code>datetime64[ns]</span></code> -dtype <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</span></code></a>, where the values have been converted to UTC and the timezone discarded</p></li>
</ol>

<p>Timezones may be preserved with <code>dtype=object</span></code></p>

In [ ]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))

In [ ]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET')], dtype=object)

<p>Or thrown away with <code>dtype='datetime64[ns]'</span></code></p>

In [ ]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

<p>Getting the “raw data” inside a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> is possibly a bit more complex. When your <code>DataFrame</span></code> only has a single data type for all the columns, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</span></code></a> will return the underlying data:</p>

In [ ]:
df.to_numpy()

array([[ 0.04384093, -0.82226071, -1.07713609],
       [ 0.42365359, -0.2891637 ,  0.66269134],
       [ 0.82045985, -1.90108573, -1.1280617 ],
       [ 1.43516604, -1.46089135,  0.78875993],
       [ 1.11742661, -1.53236278,  0.28488929],
       [-0.90982822,  0.03083173,  1.0145159 ],
       [-0.02401836, -0.25007905, -0.54201955],
       [ 0.05791434,  1.58701992,  0.61109581]])

<p>If a DataFrame contains homogeneously-typed data, the ndarray can
actually be modified in-place, and the changes will be reflected in the data structure. For heterogeneous data (e.g. some of the DataFrame’s columns are not all the same dtype), this will not be the case. The values attribute itself, unlike the axis labels, cannot be assigned to.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>When working with heterogeneous data, the dtype of the resulting ndarray will be chosen to accommodate all of the data involved. For example, if strings are involved, the result will be of object dtype. If there are only floats and integers, the resulting array will be of float dtype.</p>
</div>

<p>In the past, pandas recommended <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html#pandas.Series.values" title="pandas.Series.values"><code>Series.values</span></code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values" title="pandas.DataFrame.values"><code>DataFrame.values</span></code></a> for extracting the data from a Series or DataFrame. You’ll still find references to these in old code bases and online. Going forward, we recommend avoiding <code>.values</span></code> and using <code>.array</span></code> or <code>.to_numpy()</span></code>. <code>.values</span></code> has the following drawbacks:</p>

<ol>

<li><p>When your Series contains an <a href="https://pandas.pydata.org/docs/development/extending.html#extending-extension-types">extension type</span></a>, it’s
unclear whether <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html#pandas.Series.values" title="pandas.Series.values"><code>Series.values</span></code></a> returns a NumPy array or the extension array.
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.array.html#pandas.Series.array" title="pandas.Series.array"><code>Series.array</span></code></a> will always return an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</span></code></a>, and will never copy data.
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>Series.to_numpy()</span></code></a> will always return a NumPy array, potentially at the cost of copying / coercing values.</p></li>

<li><p>When your DataFrame contains a mixture of data types, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values" title="pandas.DataFrame.values"><code>DataFrame.values</span></code></a> may involve copying data and coercing values to a common dtype, a relatively expensive operation. <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</span></code></a>, being a method, makes it clearer that the returned NumPy array may not be a view on the same data in the DataFrame.</p></li>

</ol>

# <h2>Accelerated operations</h2>

<p>Pandas has support for accelerating certain types of binary numerical and boolean operations using the <code>numexpr</span></code> library and the <code>bottleneck</span></code> libraries.</p>

<p>These libraries are especially useful when dealing with large data sets, and provide large speedups. <code>numexpr</span></code> uses smart chunking, caching, and multiple cores. <code>bottleneck</span></code> is a set of specialized cython routines that are especially fast when dealing with arrays that have <code>nans</span></code>.</p>

<p>Here is a sample (using 100 column x 100,000 row <code>DataFrames</span></code>):</p>

<table class="table">
<colgroup>
<col style="width: 25.0%">
<col style="width: 25.0%">
<col style="width: 25.0%">
<col style="width: 25.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Operation</p></th>
<th class="head"><p>0.11.0 (ms)</p></th>
<th class="head"><p>Prior Version (ms)</p></th>
<th class="head"><p>Ratio to Prior</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code>df1</span> &gt;</span> df2</span></code></p></td>
<td><p>13.32</p></td>
<td><p>125.35</p></td>
<td><p>0.1063</p></td>
</tr>
<tr class="row-odd"><td><p><code>df1</span> *</span> df2</span></code></p></td>
<td><p>21.71</p></td>
<td><p>36.63</p></td>
<td><p>0.5928</p></td>
</tr>
<tr class="row-even"><td><p><code>df1</span> +</span> df2</span></code></p></td>
<td><p>22.04</p></td>
<td><p>36.50</p></td>
<td><p>0.6039</p></td>
</tr>
</tbody>
</table>

<p>You are highly encouraged to install both libraries. See the section
<a href="https://pandas.pydata.org/docs/getting_started/install.html#install-recommended-dependencies">Recommended Dependencies</span></a> for more installation info.</p>

<p>These are both enabled to be used by default, you can control this by setting the options:</p>

In [ ]:
pd.set_option("compute.use_bottleneck", False)
pd.set_option("compute.use_numexpr", False)

# <h2>Flexible binary operations</h2>

<p>With binary operations between pandas data structures, there are two key points of interest:</p>

<ul>
<li><p>Broadcasting behavior between higher- (e.g. DataFrame) and
lower-dimensional (e.g. Series) objects.</p></li>
<li><p>Missing data in computations.</p></li>
</ul>

<p>We will demonstrate how to manage these issues independently, though they can be handled simultaneously.</p>

## <h3>Matching / broadcasting behavior</h3>

<p>DataFrame has the methods <a href=".https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.add.html#pandas.DataFrame.add" title="pandas.DataFrame.add"><code>add()</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sub.html#pandas.DataFrame.sub" title="pandas.DataFrame.sub"><code>sub()</span></code></a>,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mul.html#pandas.DataFrame.mul" title="pandas.DataFrame.mul"><code>mul()</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.div.html#pandas.DataFrame.div" title="pandas.DataFrame.div"><code>div()</span></code></a> and related functions
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.radd.html#pandas.DataFrame.radd" title="pandas.DataFrame.radd"><code>radd()</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rsub.html#pandas.DataFrame.rsub" title="pandas.DataFrame.rsub"><code>rsub()</span></code></a>, …
for carrying out binary operations. For broadcasting behavior,
Series input is of primary interest. Using these functions, you can use to either match on the <em>index</em> or <em>columns</em> via the <strong>axis</strong> keyword:</p>

In [20]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

In [21]:
df

        one       two     three
a -0.285443 -1.440337       NaN
b  0.576492  0.421561 -0.662958
c  1.998998 -1.322394  0.230040
d       NaN  0.494468 -0.505513

In [22]:
row = df.iloc[1]

In [24]:
column = df["two"]

In [26]:
df.sub(row, axis="columns")

        one       two     three
a -0.861935 -1.861898       NaN
b  0.000000  0.000000  0.000000
c  1.422506 -1.743955  0.892998
d       NaN  0.072907  0.157445

In [27]:
df.sub(row, axis=1)

        one       two     three
a -0.861935 -1.861898       NaN
b  0.000000  0.000000  0.000000
c  1.422506 -1.743955  0.892998
d       NaN  0.072907  0.157445

In [28]:
df.sub(column, axis="index")

        one  two     three
a  1.154894  0.0       NaN
b  0.154931  0.0 -1.084519
c  3.321392  0.0  1.552434
d       NaN  0.0 -0.999981

In [29]:
df.sub(column, axis=0)

        one  two     three
a  1.154894  0.0       NaN
b  0.154931  0.0 -1.084519
c  3.321392  0.0  1.552434
d       NaN  0.0 -0.999981

<p>Furthermore you can align a level of a MultiIndexed DataFrame with a Series.</p>

In [30]:
dfmi = df.copy()

In [31]:
dfmi.index = pd.MultiIndex.from_tuples(
    [(1, "a"), (1, "b"), (1, "c"), (2, "a")], names=["first", "second"]
)

In [33]:
dfmi.sub(column, axis=0, level="second")

                   one       two     three
first second
1     a       1.154894  0.000000       NaN
      b       0.154931  0.000000 -1.084519
      c       3.321392  0.000000  1.552434
2     a            NaN  1.934805  0.934824

<p>Series and Index also support the <a href="https://docs.python.org/3/library/functions.html#divmod" title="(in Python v3.13)"><code>divmod()</span></code></a> builtin. This function takes the floor division and modulo operation at the same time returning a two-tuple of the same type as the left hand side. For example:</p>

In [34]:
s = pd.Series(np.arange(10))

In [35]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [36]:
div, rem = divmod(s, 3)

In [37]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int64

In [38]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int64

In [39]:
idx = pd.Index(np.arange(10))

In [40]:
idx

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [41]:
div, rem = divmod(idx, 3)

In [42]:
div

Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64')

In [43]:
rem

Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64')

<p>We can also do elementwise <a href="https://docs.python.org/3/library/functions.html#divmod" title="(in Python v3.13)"><code>divmod()</span></code></a>:</p>

In [44]:
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [45]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64

In [46]:
rem

0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int64

## <h3>Missing data / operations with fill values</h3>

<p>In Series and DataFrame, the arithmetic functions have the option of inputting a <em>fill_value</em>, namely a value to substitute when at most one of the values at a location are missing. For example, when adding two DataFrame objects, you may wish to treat NaN as 0 unless both DataFrames are missing that value, in which case the result will be NaN (you can later replace NaN with some other value using <code>fillna</span></code> if you wish).</p>

In [48]:
df2 = df.copy()

In [52]:
df2.loc["a", "three"] = 1.0

In [50]:
df

        one       two     three
a -0.285443 -1.440337       NaN
b  0.576492  0.421561 -0.662958
c  1.998998 -1.322394  0.230040
d       NaN  0.494468 -0.505513

In [53]:
df2

        one       two     three
a -0.285443 -1.440337  1.000000
b  0.576492  0.421561 -0.662958
c  1.998998 -1.322394  0.230040
d       NaN  0.494468 -0.505513

In [54]:
df + df2

        one       two     three
a -0.570886 -2.880675       NaN
b  1.152985  0.843122 -1.325916
c  3.997996 -2.644788  0.460080
d       NaN  0.988936 -1.011027

In [55]:
df.add(df2, fill_value=0)

        one       two     three
a -0.570886 -2.880675  1.000000
b  1.152985  0.843122 -1.325916
c  3.997996 -2.644788  0.460080
d       NaN  0.988936 -1.011027

## <h3>Flexible comparisons</h3>

<p>Series and DataFrame have the binary comparison methods <code>eq</span></code>, <code>ne</span></code>, <code>lt</span></code>, <code>gt</span></code>, <code>le</span></code>, and <code>ge</span></code> whose behavior is analogous to the binary arithmetic operations described above:</p>

In [56]:
df.gt(df2)

     one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [57]:
df2.ne(df)

     one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

<p>These operations produce a pandas object of the same type as the left-hand-side input that is of dtype <code>bool</span></code>. These <code>boolean</span></code> objects can be used in indexing operations, see the section on <a href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-boolean">Boolean indexing</span></a>.</p>

## <h3>Boolean reductions</h3>

<p>You can apply the reductions: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.empty.html#pandas.DataFrame.empty" title="pandas.DataFrame.empty"><code>empty</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.any.html#pandas.DataFrame.any" title="pandas.DataFrame.any"><code>any()</span></code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html#pandas.DataFrame.all" title="pandas.DataFrame.all"><code>all()</span></code></a>, and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.bool.html#pandas.DataFrame.bool" title="pandas.DataFrame.bool"><code>bool()</span></code></a> to provide a way to summarize a boolean result.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell15"><span></span><span class="gp">In [50]: </span><span class="p">(</span><span class="n">df</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">)</span><span class="o">.</span><span class="n">all</span><span class="p">()</span>
<span class="gh">Out[50]: </span>
<span class="go">one      False</span>
<span class="go">two       True</span>
<span class="go">three    False</span>
<span class="go">dtype: bool</span>

<span class="gp">In [51]: </span><span class="p">(</span><span class="n">df</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">)</span><span class="o">.</span><span class="n">any</span><span class="p">()</span>
<span class="gh">Out[51]: </span>
<span class="go">one      True</span>
<span class="go">two      True</span>
<span class="go">three    True</span>
<span class="go">dtype: bool</span>
</pre>
</div>
</div>
<p>You can reduce to a final boolean value.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell16"><span></span><span class="gp">In [52]: </span><span class="p">(</span><span class="n">df</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">)</span><span class="o">.</span><span class="n">any</span><span class="p">()</span><span class="o">.</span><span class="n">any</span><span class="p">()</span>
<span class="gh">Out[52]: </span><span class="go">True</span>
</pre>
</div>
</div>
<p>You can test if a pandas object is empty, via the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.empty.html#pandas.DataFrame.empty" title="pandas.DataFrame.empty"><code>empty</span></code></a> property.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell17"><span></span><span class="gp">In [53]: </span><span class="n">df</span><span class="o">.</span><span class="n">empty</span>
<span class="gh">Out[53]: </span><span class="go">False</span>

<span class="gp">In [54]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">columns</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="s2">"ABC"</span><span class="p">))</span><span class="o">.</span><span class="n">empty</span>
<span class="gh">Out[54]: </span><span class="go">True</span>
</pre>
</div>
</div>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Asserting the truthiness of a pandas object will raise an error, as the testing of the emptiness
or values is ambiguous.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell18"><span></span><span class="gp">In [55]: </span><span class="k">if</span> <span class="n">df</span><span class="p">:</span>
<span class="gp"></span>    <span class="nb">print</span><span class="p">(</span><span class="kc">True</span><span class="p">)</span>
<span class="gp"></span>
<span class="gt">---------------------------------------------------------------------------</span>
<span class="ne">ValueError</span><span class="g g-Whitespace">                                </span>Traceback (most recent call last)
<span class="nn">&lt;ipython-input-55-318d08b2571a&gt;</span> in <span class="ni">?</span><span class="nt">()</span>
<span class="ne">----&gt; </span><span class="mi">1</span> <span class="k">if</span> <span class="n">df</span><span class="p">:</span>
<span class="g g-Whitespace">      </span><span class="mi">2</span>     <span class="nb">print</span><span class="p">(</span><span class="kc">True</span><span class="p">)</span>

<span class="nn">~/work/pandas/pandas/pandas/core/generic.py</span> in <span class="ni">?</span><span class="nt">(self)</span>
<span class="g g-Whitespace">   </span><span class="mi">1575</span>     <span class="nd">@final</span>
<span class="g g-Whitespace">   </span><span class="mi">1576</span>     <span class="k">def</span><span class="w"> </span><span class="nf">__nonzero__</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">NoReturn</span><span class="p">:</span>
<span class="ne">-&gt; </span><span class="mi">1577</span>         <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span>
<span class="g g-Whitespace">   </span><span class="mi">1578</span>             <span class="sa">f</span><span class="s2">"The truth value of a </span><span class="si">{</span><span class="nb">type</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span><span class="o">.</span><span class="vm">__name__</span><span class="si">}</span><span class="s2"> is ambiguous. "</span>
<span class="g g-Whitespace">   </span><span class="mi">1579</span>             <span class="s2">"Use a.empty, a.bool(), a.item(), a.any() or a.all()."</span>
<span class="g g-Whitespace">   </span><span class="mi">1580</span>         <span class="p">)</span>

<span class="ne">ValueError</span>: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell19"><span></span><span class="gp">In [56]: </span><span class="n">df</span> <span class="ow">and</span> <span class="n">df2</span>
<span class="gt">---------------------------------------------------------------------------</span>
<span class="ne">ValueError</span><span class="g g-Whitespace">                                </span>Traceback (most recent call last)
<span class="nn">&lt;ipython-input-56-b241b64bb471&gt;</span> in <span class="ni">?</span><span class="nt">()</span>
<span class="ne">----&gt; </span><span class="mi">1</span> <span class="n">df</span> <span class="ow">and</span> <span class="n">df2</span>

<span class="nn">~/work/pandas/pandas/pandas/core/generic.py</span> in <span class="ni">?</span><span class="nt">(self)</span>
<span class="g g-Whitespace">   </span><span class="mi">1575</span>     <span class="nd">@final</span>
<span class="g g-Whitespace">   </span><span class="mi">1576</span>     <span class="k">def</span><span class="w"> </span><span class="nf">__nonzero__</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">NoReturn</span><span class="p">:</span>
<span class="ne">-&gt; </span><span class="mi">1577</span>         <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span>
<span class="g g-Whitespace">   </span><span class="mi">1578</span>             <span class="sa">f</span><span class="s2">"The truth value of a </span><span class="si">{</span><span class="nb">type</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span><span class="o">.</span><span class="vm">__name__</span><span class="si">}</span><span class="s2"> is ambiguous. "</span>
<span class="g g-Whitespace">   </span><span class="mi">1579</span>             <span class="s2">"Use a.empty, a.bool(), a.item(), a.any() or a.all()."</span>
<span class="g g-Whitespace">   </span><span class="mi">1580</span>         <span class="p">)</span>

<span class="ne">ValueError</span>: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
</pre>
</div>
</div>
<p>See <a href="gotchas.html#gotchas-truth">gotchas</span></a> for a more detailed discussion.</p>
</div>

## <h3>Comparing if objects are equivalent</h3>

<p>Often you may find that there is more than one way to compute the same result.  As a simple example, consider <code>df</span> +</span> df</span></code> and <code>df</span> *</span> 2</span></code>. To test
that these two computations produce the same result, given the tools
shown above, you might imagine using <code>(df</span> +</span> df</span> ==</span> df</span> *</span> 2).all()</span></code>. But in
fact, this expression is False:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell20"><span></span><span class="gp">In [57]: </span><span class="n">df</span> <span class="o">+</span> <span class="n">df</span> <span class="o">==</span> <span class="n">df</span> <span class="o">*</span> <span class="mi">2</span>
<span class="gh">Out[57]: </span>
<span class="go">     one   two  three</span>
<span class="go">a   True  True  False</span>
<span class="go">b   True  True   True</span>
<span class="go">c   True  True   True</span>
<span class="go">d  False  True   True</span>

<span class="gp">In [58]: </span><span class="p">(</span><span class="n">df</span> <span class="o">+</span> <span class="n">df</span> <span class="o">==</span> <span class="n">df</span> <span class="o">*</span> <span class="mi">2</span><span class="p">)</span><span class="o">.</span><span class="n">all</span><span class="p">()</span>
<span class="gh">Out[58]: </span>
<span class="go">one      False</span>
<span class="go">two       True</span>
<span class="go">three    False</span>
<span class="go">dtype: bool</span>
</pre>
</div>
</div>

<p>Notice that the boolean DataFrame <code>df</span> +</span> df</span> ==</span> df</span> *</span> 2</span></code> contains some False values!
This is because NaNs do not compare as equals:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell21"><span></span><span class="gp">In [59]: </span><span class="n">np</span><span class="o">.</span><span class="n">nan</span> <span class="o">==</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>
<span class="gh">Out[59]: </span><span class="go">False</span>
</pre>
</div>
</div>

<p>So, NDFrames (such as Series and DataFrames)
have an <a href="../reference/api/pandas.DataFrame.equals.html#pandas.DataFrame.equals" title="pandas.DataFrame.equals"><code>equals()</span></code></a> method for testing equality, with NaNs in
corresponding locations treated as equal.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell22"><span></span><span class="gp">In [60]: </span><span class="p">(</span><span class="n">df</span> <span class="o">+</span> <span class="n">df</span><span class="p">)</span><span class="o">.</span><span class="n">equals</span><span class="p">(</span><span class="n">df</span> <span class="o">*</span> <span class="mi">2</span><span class="p">)</span>
<span class="gh">Out[60]: </span><span class="go">True</span>
</pre>
</div>
</div>

<p>Note that the Series or DataFrame index needs to be in the same order for equality to be True:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell23"><span></span><span class="gp">In [61]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"col"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"foo"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">]})</span>

<span class="gp">In [62]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"col"</span><span class="p">:</span> <span class="p">[</span><span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="s2">"foo"</span><span class="p">]},</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="mi">2</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">])</span>

<span class="gp">In [63]: </span><span class="n">df1</span><span class="o">.</span><span class="n">equals</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>
<span class="gh">Out[63]: </span><span class="go">False</span>

<span class="gp">In [64]: </span><span class="n">df1</span><span class="o">.</span><span class="n">equals</span><span class="p">(</span><span class="n">df2</span><span class="o">.</span><span class="n">sort_index</span><span class="p">())</span>
<span class="gh">Out[64]: </span><span class="go">True</span>
</pre>
</div>
</div>

## <h3>Comparing array-like objects</h3>

<p>You can conveniently perform element-wise comparisons when comparing a pandas data structure with a scalar value:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell24"><span></span><span class="gp">In [65]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"baz"</span><span class="p">])</span> <span class="o">==</span> <span class="s2">"foo"</span>
<span class="gh">Out[65]: </span>
<span class="go">0     True</span>
<span class="go">1    False</span>
<span class="go">2    False</span>
<span class="go">dtype: bool</span>

<span class="gp">In [66]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Index</span><span class="p">([</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"baz"</span><span class="p">])</span> <span class="o">==</span> <span class="s2">"foo"</span>
<span class="gh">Out[66]: </span><span class="go">array([ True, False, False])</span>
</pre>
</div>
</div>

<p>pandas also handles element-wise comparisons between different array-like objects of the same length:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell25"><span></span><span class="gp">In [67]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"baz"</span><span class="p">])</span> <span class="o">==</span> <span class="n">pd</span><span class="o">.</span><span class="n">Index</span><span class="p">([</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"qux"</span><span class="p">])</span>
<span class="gh">Out[67]: </span>
<span class="go">0     True</span>
<span class="go">1     True</span>
<span class="go">2    False</span>
<span class="go">dtype: bool</span>

<span class="gp">In [68]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"baz"</span><span class="p">])</span> <span class="o">==</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"qux"</span><span class="p">])</span>
<span class="gh">Out[68]: </span>
<span class="go">0     True</span>
<span class="go">1     True</span>
<span class="go">2    False</span>
<span class="go">dtype: bool</span>
</pre>
</div>
</div>

<p>Trying to compare <code>Index</span></code> or <code>Series</span></code> objects of different lengths will
raise a ValueError:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell26"><span></span><span class="gp">In [69]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">,</span> <span class="s1">'bar'</span><span class="p">,</span> <span class="s1">'baz'</span><span class="p">])</span> <span class="o">==</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">,</span> <span class="s1">'bar'</span><span class="p">])</span>
<span class="gt">---------------------------------------------------------------------------</span>
<span class="ne">ValueError</span><span class="g g-Whitespace">                                </span>Traceback (most recent call last)
<span class="n">Cell</span> <span class="n">In</span><span class="p">[</span><span class="mi">69</span><span class="p">],</span> <span class="n">line</span> <span class="mi">1</span>
<span class="ne">----&gt; </span><span class="mi">1</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">,</span> <span class="s1">'bar'</span><span class="p">,</span> <span class="s1">'baz'</span><span class="p">])</span> <span class="o">==</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">,</span> <span class="s1">'bar'</span><span class="p">])</span>

<span class="nn">File ~/work/pandas/pandas/pandas/core/ops/common.py:76,</span> in <span class="ni">_unpack_zerodim_and_defer.&lt;locals&gt;.new_method</span><span class="nt">(self, other)</span>
<span class="g g-Whitespace">     </span><span class="mi">72</span>             <span class="k">return</span> <span class="bp">NotImplemented</span>
<span class="g g-Whitespace">     </span><span class="mi">74</span> <span class="n">other</span> <span class="o">=</span> <span class="n">item_from_zerodim</span><span class="p">(</span><span class="n">other</span><span class="p">)</span>
<span class="ne">---&gt; </span><span class="mi">76</span> <span class="k">return</span> <span class="n">method</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">other</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/core/arraylike.py:40,</span> in <span class="ni">OpsMixin.__eq__</span><span class="nt">(self, other)</span>
<span class="g g-Whitespace">     </span><span class="mi">38</span> <span class="nd">@unpack_zerodim_and_defer</span><span class="p">(</span><span class="s2">"__eq__"</span><span class="p">)</span>
<span class="g g-Whitespace">     </span><span class="mi">39</span> <span class="k">def</span><span class="w"> </span><span class="fm">__eq__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">other</span><span class="p">):</span>
<span class="ne">---&gt; </span><span class="mi">40</span>     <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_cmp_method</span><span class="p">(</span><span class="n">other</span><span class="p">,</span> <span class="n">operator</span><span class="o">.</span><span class="n">eq</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/core/series.py:6125,</span> in <span class="ni">Series._cmp_method</span><span class="nt">(self, other, op)</span>
<span class="g g-Whitespace">   </span><span class="mi">6122</span> <span class="n">res_name</span> <span class="o">=</span> <span class="n">ops</span><span class="o">.</span><span class="n">get_op_result_name</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">other</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">6124</span> <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">other</span><span class="p">,</span> <span class="n">Series</span><span class="p">)</span> <span class="ow">and</span> <span class="ow">not</span> <span class="bp">self</span><span class="o">.</span><span class="n">_indexed_same</span><span class="p">(</span><span class="n">other</span><span class="p">):</span>
<span class="ne">-&gt; </span><span class="mi">6125</span>     <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s2">"Can only compare identically-labeled Series objects"</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">6127</span> <span class="n">lvalues</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_values</span>
<span class="g g-Whitespace">   </span><span class="mi">6128</span> <span class="n">rvalues</span> <span class="o">=</span> <span class="n">extract_array</span><span class="p">(</span><span class="n">other</span><span class="p">,</span> <span class="n">extract_numpy</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">extract_range</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="ne">ValueError</span>: Can only compare identically-labeled Series objects

<span class="gp">In [70]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">,</span> <span class="s1">'bar'</span><span class="p">,</span> <span class="s1">'baz'</span><span class="p">])</span> <span class="o">==</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">])</span>
<span class="gt">---------------------------------------------------------------------------</span>
<span class="ne">ValueError</span><span class="g g-Whitespace">                                </span>Traceback (most recent call last)
<span class="n">Cell</span> <span class="n">In</span><span class="p">[</span><span class="mi">70</span><span class="p">],</span> <span class="n">line</span> <span class="mi">1</span>
<span class="ne">----&gt; </span><span class="mi">1</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">,</span> <span class="s1">'bar'</span><span class="p">,</span> <span class="s1">'baz'</span><span class="p">])</span> <span class="o">==</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s1">'foo'</span><span class="p">])</span>

<span class="nn">File ~/work/pandas/pandas/pandas/core/ops/common.py:76,</span> in <span class="ni">_unpack_zerodim_and_defer.&lt;locals&gt;.new_method</span><span class="nt">(self, other)</span>
<span class="g g-Whitespace">     </span><span class="mi">72</span>             <span class="k">return</span> <span class="bp">NotImplemented</span>
<span class="g g-Whitespace">     </span><span class="mi">74</span> <span class="n">other</span> <span class="o">=</span> <span class="n">item_from_zerodim</span><span class="p">(</span><span class="n">other</span><span class="p">)</span>
<span class="ne">---&gt; </span><span class="mi">76</span> <span class="k">return</span> <span class="n">method</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">other</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/core/arraylike.py:40,</span> in <span class="ni">OpsMixin.__eq__</span><span class="nt">(self, other)</span>
<span class="g g-Whitespace">     </span><span class="mi">38</span> <span class="nd">@unpack_zerodim_and_defer</span><span class="p">(</span><span class="s2">"__eq__"</span><span class="p">)</span>
<span class="g g-Whitespace">     </span><span class="mi">39</span> <span class="k">def</span><span class="w"> </span><span class="fm">__eq__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">other</span><span class="p">):</span>
<span class="ne">---&gt; </span><span class="mi">40</span>     <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_cmp_method</span><span class="p">(</span><span class="n">other</span><span class="p">,</span> <span class="n">operator</span><span class="o">.</span><span class="n">eq</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/core/series.py:6125,</span> in <span class="ni">Series._cmp_method</span><span class="nt">(self, other, op)</span>
<span class="g g-Whitespace">   </span><span class="mi">6122</span> <span class="n">res_name</span> <span class="o">=</span> <span class="n">ops</span><span class="o">.</span><span class="n">get_op_result_name</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">other</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">6124</span> <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">other</span><span class="p">,</span> <span class="n">Series</span><span class="p">)</span> <span class="ow">and</span> <span class="ow">not</span> <span class="bp">self</span><span class="o">.</span><span class="n">_indexed_same</span><span class="p">(</span><span class="n">other</span><span class="p">):</span>
<span class="ne">-&gt; </span><span class="mi">6125</span>     <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s2">"Can only compare identically-labeled Series objects"</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">6127</span> <span class="n">lvalues</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_values</span>
<span class="g g-Whitespace">   </span><span class="mi">6128</span> <span class="n">rvalues</span> <span class="o">=</span> <span class="n">extract_array</span><span class="p">(</span><span class="n">other</span><span class="p">,</span> <span class="n">extract_numpy</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">extract_range</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="ne">ValueError</span>: Can only compare identically-labeled Series objects
</pre>
</div>
</div>

## <h3>Combining overlapping data sets</h3>

<p>A problem occasionally arising is the combination of two similar data sets where values in one are preferred over the other. An example would be two data series representing a particular economic indicator where one is considered to be of “higher quality”.
However, the lower quality series might extend further back in history or have more complete data coverage. As such, we would like to combine two DataFrame objects where missing values in one DataFrame are conditionally filled with like-labeled values from the other DataFrame.
The function implementing this operation is <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</span></code></a>, which we illustrate:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell27"><span></span><span class="gp">In [71]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span><span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="mf">1.0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="mf">5.0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">],</span> <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">6.0</span><span class="p">]}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [72]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="mf">5.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">4.0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="mf">7.0</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="mf">4.0</span><span class="p">,</span> <span class="mf">6.0</span><span class="p">,</span> <span class="mf">8.0</span><span class="p">],</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [73]: </span><span class="n">df1</span>
<span class="gh">Out[73]: </span>
<span class="go">     A    B</span>
<span class="go">0  1.0  NaN</span>
<span class="go">1  NaN  2.0</span>
<span class="go">2  3.0  3.0</span>
<span class="go">3  5.0  NaN</span>
<span class="go">4  NaN  6.0</span>

<span class="gp">In [74]: </span><span class="n">df2</span>
<span class="gh">Out[74]: </span>
<span class="go">     A    B</span>
<span class="go">0  5.0  NaN</span>
<span class="go">1  2.0  NaN</span>
<span class="go">2  4.0  3.0</span>
<span class="go">3  NaN  4.0</span>
<span class="go">4  3.0  6.0</span>
<span class="go">5  7.0  8.0</span>

<span class="gp">In [75]: </span><span class="n">df1</span><span class="o">.</span><span class="n">combine_first</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>
<span class="gh">Out[75]: </span>
<span class="go">     A    B</span>
<span class="go">0  1.0  NaN</span>
<span class="go">1  2.0  2.0</span>
<span class="go">2  3.0  3.0</span>
<span class="go">3  5.0  4.0</span>
<span class="go">4  3.0  6.0</span>
<span class="go">5  7.0  8.0</span>
</pre>
</div>
</div>

## <h3>General DataFrame combine</h3>

<p>The <a href="../reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</span></code></a> method above calls the more general <a href="../reference/api/pandas.DataFrame.combine.html#pandas.DataFrame.combine" title="pandas.DataFrame.combine"><code>DataFrame.combine()</span></code></a>.
This method takes another DataFrame and a combiner function, aligns the input DataFrame and then passes the combiner function pairs of Series (i.e., columns whose names are the same).</p>

<p>So, for instance, to reproduce <a href="../reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</span></code></a> as above:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell28"><span></span><span class="gp">In [76]: </span><span class="k">def</span><span class="w"> </span><span class="nf">combiner</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
<span class="gp"></span>    <span class="k">return</span> <span class="n">np</span><span class="o">.</span><span class="n">where</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">isna</span><span class="p">(</span><span class="n">x</span><span class="p">),</span> <span class="n">y</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [77]: </span><span class="n">df1</span><span class="o">.</span><span class="n">combine</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">combiner</span><span class="p">)</span>
<span class="gh">Out[77]: </span>
<span class="go">     A    B</span>
<span class="go">0  1.0  NaN</span>
<span class="go">1  2.0  2.0</span>
<span class="go">2  3.0  3.0</span>
<span class="go">3  5.0  4.0</span>
<span class="go">4  3.0  6.0</span>
<span class="go">5  7.0  8.0</span>
</pre>
</div>
</div>

# <h2>Descriptive statistics</h2>

<p>There exists a large number of methods for computing descriptive statistics and other related operations on <a href="../reference/series.html#api-series-stats">Series</span></a>, <a href="../reference/frame.html#api-dataframe-stats">DataFrame</span></a>.
Most of these are aggregations (hence producing a lower-dimensional result) like <a href="../reference/api/pandas.DataFrame.sum.html#pandas.DataFrame.sum" title="pandas.DataFrame.sum"><code>sum()</span></code></a>, <a href="../reference/api/pandas.DataFrame.mean.html#pandas.DataFrame.mean" title="pandas.DataFrame.mean"><code>mean()</span></code></a>, and <a href="../reference/api/pandas.DataFrame.quantile.html#pandas.DataFrame.quantile" title="pandas.DataFrame.quantile"><code>quantile()</span></code></a>, but some of them, like <a href="../reference/api/pandas.DataFrame.cumsum.html#pandas.DataFrame.cumsum" title="pandas.DataFrame.cumsum"><code>cumsum()</span></code></a> and <a href="../reference/api/pandas.DataFrame.cumprod.html#pandas.DataFrame.cumprod" title="pandas.DataFrame.cumprod"><code>cumprod()</span></code></a>, produce an object of the same size.
Generally speaking, these methods take an <strong>axis</strong> argument, just like <em>ndarray.{sum, std, …}</em>, but the axis can be specified by name or integer:</p>

<ul>
<li><p><strong>Series</strong>: no axis argument needed</p></li>
<li><p><strong>DataFrame</strong>: “index” (axis=0, default), “columns” (axis=1)</p></li>
</ul>

<p>For example:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell29"><span></span><span class="gp">In [78]: </span><span class="n">df</span>
<span class="gh">Out[78]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [79]: </span><span class="n">df</span><span class="o">.</span><span class="n">mean</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
<span class="gh">Out[79]: </span>
<span class="go">one      0.811094</span>
<span class="go">two      1.360588</span>
<span class="go">three    0.187958</span>
<span class="go">dtype: float64</span>

<span class="gp">In [80]: </span><span class="n">df</span><span class="o">.</span><span class="n">mean</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[80]: </span>
<span class="go">a    1.583749</span>
<span class="go">b    0.734929</span>
<span class="go">c    1.133683</span>
<span class="go">d   -0.166914</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>

<p>All such methods have a <code>skipna</span></code> option signaling whether to exclude missing data (<code>True</span></code> by default):</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell30"><span></span><span class="gp">In [81]: </span><span class="n">df</span><span class="o">.</span><span class="n">sum</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="n">skipna</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
<span class="gh">Out[81]: </span>
<span class="go">one           NaN</span>
<span class="go">two      5.442353</span>
<span class="go">three         NaN</span>
<span class="go">dtype: float64</span>

<span class="gp">In [82]: </span><span class="n">df</span><span class="o">.</span><span class="n">sum</span><span class="p">(</span><span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">skipna</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
<span class="gh">Out[82]: </span>
<span class="go">a    3.167498</span>
<span class="go">b    2.204786</span>
<span class="go">c    3.401050</span>
<span class="go">d   -0.333828</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>

<p>Combined with the broadcasting / arithmetic behavior, one can describe various statistical procedures, like standardization (rendering data zero mean and standard deviation of 1), very concisely:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell31"><span></span><span class="gp">In [83]: </span><span class="n">ts_stand</span> <span class="o">=</span> <span class="p">(</span><span class="n">df</span> <span class="o">-</span> <span class="n">df</span><span class="o">.</span><span class="n">mean</span><span class="p">())</span> <span class="o">/</span> <span class="n">df</span><span class="o">.</span><span class="n">std</span><span class="p">()</span>

<span class="gp">In [84]: </span><span class="n">ts_stand</span><span class="o">.</span><span class="n">std</span><span class="p">()</span>
<span class="gh">Out[84]: </span>
<span class="go">one      1.0</span>
<span class="go">two      1.0</span>
<span class="go">three    1.0</span>
<span class="go">dtype: float64</span>

<span class="gp">In [85]: </span><span class="n">xs_stand</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">sub</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">mean</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span> <span class="n">axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span><span class="o">.</span><span class="n">div</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">std</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span> <span class="n">axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>

<span class="gp">In [86]: </span><span class="n">xs_stand</span><span class="o">.</span><span class="n">std</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[86]: </span>
<span class="go">a    1.0</span>
<span class="go">b    1.0</span>
<span class="go">c    1.0</span>
<span class="go">d    1.0</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>

<p>Note that methods like <a href="../reference/api/pandas.DataFrame.cumsum.html#pandas.DataFrame.cumsum" title="pandas.DataFrame.cumsum"><code>cumsum()</span></code></a> and <a href="../reference/api/pandas.DataFrame.cumprod.html#pandas.DataFrame.cumprod" title="pandas.DataFrame.cumprod"><code>cumprod()</span></code></a>
preserve the location of <code>NaN</span></code> values. This is somewhat different from
<a href="../reference/api/pandas.DataFrame.expanding.html#pandas.DataFrame.expanding" title="pandas.DataFrame.expanding"><code>expanding()</span></code></a> and <a href="../reference/api/pandas.DataFrame.rolling.html#pandas.DataFrame.rolling" title="pandas.DataFrame.rolling"><code>rolling()</span></code></a> since <code>NaN</span></code> behavior
is furthermore dictated by a <code>min_periods</span></code> parameter.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell32"><span></span><span class="gp">In [87]: </span><span class="n">df</span><span class="o">.</span><span class="n">cumsum</span><span class="p">()</span>
<span class="gh">Out[87]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  1.738035  3.684640 -0.050390</span>
<span class="go">c  2.433281  5.163008  1.177045</span>
<span class="go">d       NaN  5.442353  0.563873</span>
</pre>
</div>
</div>

<p>Here is a quick reference summary table of common functions. Each also takes an
optional <code>level</span></code> parameter which applies only if the object has a
<a href="advanced.html#advanced-hierarchical">hierarchical index</span></a>.</p>
<table class="table">
<colgroup>
<col style="width: 20.0%">
<col style="width: 80.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Function</p></th>
<th class="head"><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code>count</span></code></p></td>
<td><p>Number of non-NA observations</p></td>
</tr>
<tr class="row-odd"><td><p><code>sum</span></code></p></td>
<td><p>Sum of values</p></td>
</tr>
<tr class="row-even"><td><p><code>mean</span></code></p></td>
<td><p>Mean of values</p></td>
</tr>
<tr class="row-odd"><td><p><code>median</span></code></p></td>
<td><p>Arithmetic median of values</p></td>
</tr>
<tr class="row-even"><td><p><code>min</span></code></p></td>
<td><p>Minimum</p></td>
</tr>
<tr class="row-odd"><td><p><code>max</span></code></p></td>
<td><p>Maximum</p></td>
</tr>
<tr class="row-even"><td><p><code>mode</span></code></p></td>
<td><p>Mode</p></td>
</tr>
<tr class="row-odd"><td><p><code>abs</span></code></p></td>
<td><p>Absolute Value</p></td>
</tr>
<tr class="row-even"><td><p><code>prod</span></code></p></td>
<td><p>Product of values</p></td>
</tr>
<tr class="row-odd"><td><p><code>std</span></code></p></td>
<td><p>Bessel-corrected sample standard deviation</p></td>
</tr>
<tr class="row-even"><td><p><code>var</span></code></p></td>
<td><p>Unbiased variance</p></td>
</tr>
<tr class="row-odd"><td><p><code>sem</span></code></p></td>
<td><p>Standard error of the mean</p></td>
</tr>
<tr class="row-even"><td><p><code>skew</span></code></p></td>
<td><p>Sample skewness (3rd moment)</p></td>
</tr>
<tr class="row-odd"><td><p><code>kurt</span></code></p></td>
<td><p>Sample kurtosis (4th moment)</p></td>
</tr>
<tr class="row-even"><td><p><code>quantile</span></code></p></td>
<td><p>Sample quantile (value at %)</p></td>
</tr>
<tr class="row-odd"><td><p><code>cumsum</span></code></p></td>
<td><p>Cumulative sum</p></td>
</tr>
<tr class="row-even"><td><p><code>cumprod</span></code></p></td>
<td><p>Cumulative product</p></td>
</tr>
<tr class="row-odd"><td><p><code>cummax</span></code></p></td>
<td><p>Cumulative maximum</p></td>
</tr>
<tr class="row-even"><td><p><code>cummin</span></code></p></td>
<td><p>Cumulative minimum</p></td>
</tr>
</tbody>
</table>

<p>Note that by chance some NumPy methods, like <code>mean</span></code>, <code>std</span></code>, and <code>sum</span></code>,
will exclude NAs on Series input by default:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell33"><span></span><span class="gp">In [88]: </span><span class="n">np</span><span class="o">.</span><span class="n">mean</span><span class="p">(</span><span class="n">df</span><span class="p">[</span><span class="s2">"one"</span><span class="p">])</span>
<span class="gh">Out[88]: </span><span class="go">0.8110935116651192</span>

<span class="gp">In [89]: </span><span class="n">np</span><span class="o">.</span><span class="n">mean</span><span class="p">(</span><span class="n">df</span><span class="p">[</span><span class="s2">"one"</span><span class="p">]</span><span class="o">.</span><span class="n">to_numpy</span><span class="p">())</span>
<span class="gh">Out[89]: </span><span class="go">nan</span>
</pre>
</div>
</div>

<p><a href="../reference/api/pandas.Series.nunique.html#pandas.Series.nunique" title="pandas.Series.nunique"><code>Series.nunique()</span></code></a> will return the number of unique non-NA values in a
Series:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell34"><span></span><span class="gp">In [90]: </span><span class="n">series</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">500</span><span class="p">))</span>

<span class="gp">In [91]: </span><span class="n">series</span><span class="p">[</span><span class="mi">20</span><span class="p">:</span><span class="mi">500</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [92]: </span><span class="n">series</span><span class="p">[</span><span class="mi">10</span><span class="p">:</span><span class="mi">20</span><span class="p">]</span> <span class="o">=</span> <span class="mi">5</span>

<span class="gp">In [93]: </span><span class="n">series</span><span class="o">.</span><span class="n">nunique</span><span class="p">()</span>
<span class="gh">Out[93]: </span><span class="go">11</span>
</pre>
</div>
</div>

## <h3>Summarizing data: describe</h3>

<p>There is a convenient <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</span></code></a> function which computes a variety of summary
statistics about a Series or the columns of a DataFrame (excluding NAs of
course):</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell35"><span></span><span class="gp">In [94]: </span><span class="n">series</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">1000</span><span class="p">))</span>

<span class="gp">In [95]: </span><span class="n">series</span><span class="p">[::</span><span class="mi">2</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [96]: </span><span class="n">series</span><span class="o">.</span><span class="n">describe</span><span class="p">()</span>
<span class="gh">Out[96]: </span>
<span class="go">count    500.000000</span>
<span class="go">mean      -0.021292</span>
<span class="go">std        1.015906</span>
<span class="go">min       -2.683763</span>
<span class="go">25%       -0.699070</span>
<span class="go">50%       -0.069718</span>
<span class="go">75%        0.714483</span>
<span class="go">max        3.160915</span>
<span class="go">dtype: float64</span>

<span class="gp">In [97]: </span><span class="n">frame</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">1000</span><span class="p">,</span> <span class="mi">5</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">])</span>

<span class="gp">In [98]: </span><span class="n">frame</span><span class="o">.</span><span class="n">iloc</span><span class="p">[::</span><span class="mi">2</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [99]: </span><span class="n">frame</span><span class="o">.</span><span class="n">describe</span><span class="p">()</span>
<span class="gh">Out[99]: </span>
<span class="go">                a           b           c           d           e</span>
<span class="go">count  500.000000  500.000000  500.000000  500.000000  500.000000</span>
<span class="go">mean     0.033387    0.030045   -0.043719   -0.051686    0.005979</span>
<span class="go">std      1.017152    0.978743    1.025270    1.015988    1.006695</span>
<span class="go">min     -3.000951   -2.637901   -3.303099   -3.159200   -3.188821</span>
<span class="go">25%     -0.647623   -0.576449   -0.712369   -0.691338   -0.691115</span>
<span class="go">50%      0.047578   -0.021499   -0.023888   -0.032652   -0.025363</span>
<span class="go">75%      0.729907    0.775880    0.618896    0.670047    0.649748</span>
<span class="go">max      2.740139    2.752332    3.004229    2.728702    3.240991</span>
</pre>
</div>
</div>

<p>You can select specific percentiles to include in the output:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell36"><span></span><span class="gp">In [100]: </span><span class="n">series</span><span class="o">.</span><span class="n">describe</span><span class="p">(</span><span class="n">percentiles</span><span class="o">=</span><span class="p">[</span><span class="mf">0.05</span><span class="p">,</span> <span class="mf">0.25</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.95</span><span class="p">])</span>
<span class="gh">Out[100]: </span>
<span class="go">count    500.000000</span>
<span class="go">mean      -0.021292</span>
<span class="go">std        1.015906</span>
<span class="go">min       -2.683763</span>
<span class="go">5%        -1.645423</span>
<span class="go">25%       -0.699070</span>
<span class="go">50%       -0.069718</span>
<span class="go">75%        0.714483</span>
<span class="go">95%        1.711409</span>
<span class="go">max        3.160915</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>

<p>By default, the median is always included.</p>
<p>For a non-numerical Series object, <a href="../reference/api/pandas.Series.describe.html#pandas.Series.describe" title="pandas.Series.describe"><code>describe()</span></code></a> will give a simple
summary of the number of unique values and most frequently occurring values:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell37"><span></span><span class="gp">In [101]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">])</span>

<span class="gp">In [102]: </span><span class="n">s</span><span class="o">.</span><span class="n">describe</span><span class="p">()</span>
<span class="gh">Out[102]: </span>
<span class="go">count     9</span>
<span class="go">unique    4</span>
<span class="go">top       a</span>
<span class="go">freq      5</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p>Note that on a mixed-type DataFrame object, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</span></code></a> will restrict the summary to include only numerical columns or, if none are, only categorical columns:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell38"><span></span><span class="gp">In [103]: </span><span class="n">frame</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"Yes"</span><span class="p">,</span> <span class="s2">"Yes"</span><span class="p">,</span> <span class="s2">"No"</span><span class="p">,</span> <span class="s2">"No"</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="nb">range</span><span class="p">(</span><span class="mi">4</span><span class="p">)})</span>

<span class="gp">In [104]: </span><span class="n">frame</span><span class="o">.</span><span class="n">describe</span><span class="p">()</span>
<span class="gh">Out[104]: </span>
<span class="go">              b</span>
<span class="go">count  4.000000</span>
<span class="go">mean   1.500000</span>
<span class="go">std    1.290994</span>
<span class="go">min    0.000000</span>
<span class="go">25%    0.750000</span>
<span class="go">50%    1.500000</span>
<span class="go">75%    2.250000</span>
<span class="go">max    3.000000</span>
</pre>
</div>
</div>

<p>This behavior can be controlled by providing a list of types as <code>include</span></code>/<code>exclude</span></code>
arguments. The special value <code>all</span></code> can also be used:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell39"><span></span><span class="gp">In [105]: </span><span class="n">frame</span><span class="o">.</span><span class="n">describe</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"object"</span><span class="p">])</span>
<span class="gh">Out[105]: </span>
<span class="go">          a</span>
<span class="go">count     4</span>
<span class="go">unique    2</span>
<span class="go">top     Yes</span>
<span class="go">freq      2</span>

<span class="gp">In [106]: </span><span class="n">frame</span><span class="o">.</span><span class="n">describe</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"number"</span><span class="p">])</span>
<span class="gh">Out[106]: </span>
<span class="go">              b</span>
<span class="go">count  4.000000</span>
<span class="go">mean   1.500000</span>
<span class="go">std    1.290994</span>
<span class="go">min    0.000000</span>
<span class="go">25%    0.750000</span>
<span class="go">50%    1.500000</span>
<span class="go">75%    2.250000</span>
<span class="go">max    3.000000</span>

<span class="gp">In [107]: </span><span class="n">frame</span><span class="o">.</span><span class="n">describe</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="s2">"all"</span><span class="p">)</span>
<span class="gh">Out[107]: </span>
<span class="go">          a         b</span>
<span class="go">count     4  4.000000</span>
<span class="go">unique    2       NaN</span>
<span class="go">top     Yes       NaN</span>
<span class="go">freq      2       NaN</span>
<span class="go">mean    NaN  1.500000</span>
<span class="go">std     NaN  1.290994</span>
<span class="go">min     NaN  0.000000</span>
<span class="go">25%     NaN  0.750000</span>
<span class="go">50%     NaN  1.500000</span>
<span class="go">75%     NaN  2.250000</span>
<span class="go">max     NaN  3.000000</span>
</pre>
</div>
</div>

<p>That feature relies on <a href="#basics-selectdtypes">select_dtypes</span></a>. Refer to there for details about accepted inputs.</p>

## <h3>Index of min/max values</h3>

<p>The <a href="../reference/api/pandas.DataFrame.idxmin.html#pandas.DataFrame.idxmin" title="pandas.DataFrame.idxmin"><code>idxmin()</span></code></a> and <a href="../reference/api/pandas.DataFrame.idxmax.html#pandas.DataFrame.idxmax" title="pandas.DataFrame.idxmax"><code>idxmax()</span></code></a> functions on Series
and DataFrame compute the index labels with the minimum and maximum
corresponding values:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell40"><span></span><span class="gp">In [108]: </span><span class="n">s1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">))</span>

<span class="gp">In [109]: </span><span class="n">s1</span>
<span class="gh">Out[109]: </span>
<span class="go">0    1.118076</span>
<span class="go">1   -0.352051</span>
<span class="go">2   -1.242883</span>
<span class="go">3   -1.277155</span>
<span class="go">4   -0.641184</span>
<span class="go">dtype: float64</span>

<span class="gp">In [110]: </span><span class="n">s1</span><span class="o">.</span><span class="n">idxmin</span><span class="p">(),</span> <span class="n">s1</span><span class="o">.</span><span class="n">idxmax</span><span class="p">()</span>
<span class="gh">Out[110]: </span><span class="go">(3, 0)</span>

<span class="gp">In [111]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">])</span>

<span class="gp">In [112]: </span><span class="n">df1</span>
<span class="gh">Out[112]: </span>
<span class="go">          A         B         C</span>
<span class="go">0 -0.327863 -0.946180 -0.137570</span>
<span class="go">1 -0.186235 -0.257213 -0.486567</span>
<span class="go">2 -0.507027 -0.871259 -0.111110</span>
<span class="go">3  2.000339 -2.430505  0.089759</span>
<span class="go">4 -0.321434 -0.033695  0.096271</span>

<span class="gp">In [113]: </span><span class="n">df1</span><span class="o">.</span><span class="n">idxmin</span><span class="p">(</span><span class="n">axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="gh">Out[113]: </span>
<span class="go">A    2</span>
<span class="go">B    3</span>
<span class="go">C    1</span>
<span class="go">dtype: int64</span>

<span class="gp">In [114]: </span><span class="n">df1</span><span class="o">.</span><span class="n">idxmax</span><span class="p">(</span><span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[114]: </span>
<span class="go">0    C</span>
<span class="go">1    A</span>
<span class="go">2    C</span>
<span class="go">3    A</span>
<span class="go">4    C</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>When there are multiple rows (or columns) matching the minimum or maximum
value, <a href="../reference/api/pandas.DataFrame.idxmin.html#pandas.DataFrame.idxmin" title="pandas.DataFrame.idxmin"><code>idxmin()</span></code></a> and <a href="../reference/api/pandas.DataFrame.idxmax.html#pandas.DataFrame.idxmax" title="pandas.DataFrame.idxmax"><code>idxmax()</span></code></a> return the first
matching index:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell41"><span></span><span class="gp">In [115]: </span><span class="n">df3</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([</span><span class="mi">2</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">],</span> <span class="n">index</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="s2">"edcba"</span><span class="p">))</span>

<span class="gp">In [116]: </span><span class="n">df3</span>
<span class="gh">Out[116]: </span>
<span class="go">     A</span>
<span class="go">e  2.0</span>
<span class="go">d  1.0</span>
<span class="go">c  1.0</span>
<span class="go">b  3.0</span>
<span class="go">a  NaN</span>

<span class="gp">In [117]: </span><span class="n">df3</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">idxmin</span><span class="p">()</span>
<span class="gh">Out[117]: </span><span class="go">'d'</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>idxmin</span></code> and <code>idxmax</span></code> are called <code>argmin</span></code> and <code>argmax</span></code> in NumPy.</p>
</div>

## <h3>Value counts (histogramming) / mode</h3>

<p>The <a href="../reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts" title="pandas.Series.value_counts"><code>value_counts()</span></code></a> Series method computes a histogram
of a 1D array of values. It can also be used as a function on regular arrays:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell42"><span></span><span class="gp">In [118]: </span><span class="n">data</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randint</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="n">size</span><span class="o">=</span><span class="mi">50</span><span class="p">)</span>

<span class="gp">In [119]: </span><span class="n">data</span>
<span class="gh">Out[119]: </span>
<span class="go">array([6, 6, 2, 3, 5, 3, 2, 5, 4, 5, 4, 3, 4, 5, 0, 2, 0, 4, 2, 0, 3, 2,</span>
<span class="go">       2, 5, 6, 5, 3, 4, 6, 4, 3, 5, 6, 4, 3, 6, 2, 6, 6, 2, 3, 4, 2, 1,</span>
<span class="go">       6, 2, 6, 1, 5, 4])</span>

<span class="gp">In [120]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">data</span><span class="p">)</span>

<span class="gp">In [121]: </span><span class="n">s</span><span class="o">.</span><span class="n">value_counts</span><span class="p">()</span>
<span class="gh">Out[121]: </span>
<span class="go">6    10</span>
<span class="go">2    10</span>
<span class="go">4     9</span>
<span class="go">3     8</span>
<span class="go">5     8</span>
<span class="go">0     3</span>
<span class="go">1     2</span>
<span class="go">Name: count, dtype: int64</span>
</pre>
</div>
</div>

<p>The <a href="../reference/api/pandas.DataFrame.value_counts.html#pandas.DataFrame.value_counts" title="pandas.DataFrame.value_counts"><code>value_counts()</span></code></a> method can be used to count combinations across multiple columns.
By default all columns are used but a subset can be selected using the <code>subset</span></code> argument.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell43"><span></span><span class="gp">In [122]: </span><span class="n">data</span> <span class="o">=</span> <span class="p">{</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"x"</span><span class="p">,</span> <span class="s2">"x"</span><span class="p">,</span> <span class="s2">"y"</span><span class="p">,</span> <span class="s2">"y"</span><span class="p">]}</span>

<span class="gp">In [123]: </span><span class="n">frame</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">data</span><span class="p">)</span>

<span class="gp">In [124]: </span><span class="n">frame</span><span class="o">.</span><span class="n">value_counts</span><span class="p">()</span>
<span class="gh">Out[124]: </span>
<span class="go">a  b</span>
<span class="go">1  x    1</span>
<span class="go">2  x    1</span>
<span class="go">3  y    1</span>
<span class="go">4  y    1</span>
<span class="go">Name: count, dtype: int64</span>
</pre>
</div>
</div>

<p>Similarly, you can get the most frequently occurring value(s), i.e. the mode, of the values in a Series or DataFrame:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell44"><span></span><span class="gp">In [125]: </span><span class="n">s5</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">7</span><span class="p">])</span>

<span class="gp">In [126]: </span><span class="n">s5</span><span class="o">.</span><span class="n">mode</span><span class="p">()</span>
<span class="gh">Out[126]: </span>
<span class="go">0    3</span>
<span class="go">1    7</span>
<span class="go">dtype: int64</span>

<span class="gp">In [127]: </span><span class="n">df5</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randint</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="n">size</span><span class="o">=</span><span class="mi">50</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"B"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randint</span><span class="p">(</span><span class="o">-</span><span class="mi">10</span><span class="p">,</span> <span class="mi">15</span><span class="p">,</span> <span class="n">size</span><span class="o">=</span><span class="mi">50</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="p">}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [128]: </span><span class="n">df5</span><span class="o">.</span><span class="n">mode</span><span class="p">()</span>
<span class="gh">Out[128]: </span>
<span class="go">     A   B</span>
<span class="go">0  1.0  -9</span>
<span class="go">1  NaN  10</span>
<span class="go">2  NaN  13</span>
</pre>
</div>
</div>

## <h3>Discretization and quantiling</h3>

<p>Continuous values can be discretized using the <a href="../reference/api/pandas.cut.html#pandas.cut" title="pandas.cut"><code>cut()</span></code></a> (bins based on values)
and <a href="../reference/api/pandas.qcut.html#pandas.qcut" title="pandas.qcut"><code>qcut()</span></code></a> (bins based on sample quantiles) functions:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell45"><span></span><span class="gp">In [129]: </span><span class="n">arr</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">20</span><span class="p">)</span>

<span class="gp">In [130]: </span><span class="n">factor</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span><span class="n">arr</span><span class="p">,</span> <span class="mi">4</span><span class="p">)</span>

<span class="gp">In [131]: </span><span class="n">factor</span>
<span class="gh">Out[131]: </span>
<span class="go">[(-0.251, 0.464], (-0.968, -0.251], (0.464, 1.179], (-0.251, 0.464], (-0.968, -0.251], ..., (-0.251, 0.464], (-0.968, -0.251], (-0.968, -0.251], (-0.968, -0.251], (-0.968, -0.251]]</span>
<span class="go">Length: 20</span>
<span class="go">Categories (4, interval[float64, right]): [(-0.968, -0.251] &lt; (-0.251, 0.464] &lt; (0.464, 1.179] &lt;</span>
<span class="go">                                           (1.179, 1.893]]</span>

<span class="gp">In [132]: </span><span class="n">factor</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span><span class="n">arr</span><span class="p">,</span> <span class="p">[</span><span class="o">-</span><span class="mi">5</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">5</span><span class="p">])</span>

<span class="gp">In [133]: </span><span class="n">factor</span>
<span class="gh">Out[133]: </span>
<span class="go">[(0, 1], (-1, 0], (0, 1], (0, 1], (-1, 0], ..., (-1, 0], (-1, 0], (-1, 0], (-1, 0], (-1, 0]]</span>
<span class="go">Length: 20</span>
<span class="go">Categories (4, interval[int64, right]): [(-5, -1] &lt; (-1, 0] &lt; (0, 1] &lt; (1, 5]]</span>
</pre>
</div>
</div>

<p><a href="../reference/api/pandas.qcut.html#pandas.qcut" title="pandas.qcut"><code>qcut()</span></code></a> computes sample quantiles. For example, we could slice up some
normally distributed data into equal-size quartiles like so:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell46"><span></span><span class="gp">In [134]: </span><span class="n">arr</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">30</span><span class="p">)</span>

<span class="gp">In [135]: </span><span class="n">factor</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">qcut</span><span class="p">(</span><span class="n">arr</span><span class="p">,</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mf">0.25</span><span class="p">,</span> <span class="mf">0.5</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mi">1</span><span class="p">])</span>

<span class="gp">In [136]: </span><span class="n">factor</span>
<span class="gh">Out[136]: </span>
<span class="go">[(0.569, 1.184], (-2.278, -0.301], (-2.278, -0.301], (0.569, 1.184], (0.569, 1.184], ..., (-0.301, 0.569], (1.184, 2.346], (1.184, 2.346], (-0.301, 0.569], (-2.278, -0.301]]</span>
<span class="go">Length: 30</span>
<span class="go">Categories (4, interval[float64, right]): [(-2.278, -0.301] &lt; (-0.301, 0.569] &lt; (0.569, 1.184] &lt;</span>
<span class="go">                                           (1.184, 2.346]]</span>
</pre>
</div>
</div>

<p>We can also pass infinite values to define the bins:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell47"><span></span><span class="gp">In [137]: </span><span class="n">arr</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">20</span><span class="p">)</span>

<span class="gp">In [138]: </span><span class="n">factor</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span><span class="n">arr</span><span class="p">,</span> <span class="p">[</span><span class="o">-</span><span class="n">np</span><span class="o">.</span><span class="n">inf</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">inf</span><span class="p">])</span>

<span class="gp">In [139]: </span><span class="n">factor</span>
<span class="gh">Out[139]: </span>
<span class="go">[(-inf, 0.0], (0.0, inf], (0.0, inf], (-inf, 0.0], (-inf, 0.0], ..., (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (0.0, inf], (0.0, inf]]</span>
<span class="go">Length: 20</span>
<span class="go">Categories (2, interval[float64, right]): [(-inf, 0.0] &lt; (0.0, inf]]</span>
</pre>
</div>
</div>

# <h2>Function application</h2>

<p>To apply your own or another library’s functions to pandas objects,
you should be aware of the three methods below. The appropriate
method to use depends on whether your function expects to operate
on an entire <code>DataFrame</span></code> or <code>Series</span></code>, row- or column-wise, or elementwise.</p>
<ol>
<li><p><a href="#tablewise-function-application">Tablewise Function Application</a>: <a href="../reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</span></code></a></p></li>
<li><p><a href="#row-or-column-wise-function-application">Row or Column-wise Function Application</a>: <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a></p></li>
<li><p><a href="#aggregation-api">Aggregation API</a>: <a href="../reference/api/pandas.DataFrame.agg.html#pandas.DataFrame.agg" title="pandas.DataFrame.agg"><code>agg()</span></code></a> and <a href="../reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</span></code></a></p></li>
<li><p><a href="#applying-elementwise-functions">Applying Elementwise Functions</a>: <a href="../reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.DataFrame.map"><code>map()</span></code></a></p></li>
</ol>

## <h3>Tablewise function application</h3>

<p><code>DataFrames</span></code> and <code>Series</span></code> can be passed into functions.
However, if the function needs to be called in a chain, consider using the <a href="../reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</span></code></a> method.</p>
<p>First some setup:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell48"><span></span><span class="gp">In [140]: </span><span class="k">def</span><span class="w"> </span><span class="nf">extract_city_name</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
<span class="gp">   .....: </span><span class="w">    </span><span class="sd">"""</span>
<span class="gp">   .....: </span><span class="sd">    Chicago, IL -&gt; Chicago for city_name column</span>
<span class="gp">   .....: </span><span class="sd">    """</span>
<span class="gp">   .....: </span>    <span class="n">df</span><span class="p">[</span><span class="s2">"city_name"</span><span class="p">]</span> <span class="o">=</span> <span class="n">df</span><span class="p">[</span><span class="s2">"city_and_code"</span><span class="p">]</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="s2">","</span><span class="p">)</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
<span class="gp">   .....: </span>    <span class="k">return</span> <span class="n">df</span>
<span class="gp">   .....: </span>

<span class="gp">In [141]: </span><span class="k">def</span><span class="w"> </span><span class="nf">add_country_name</span><span class="p">(</span><span class="n">df</span><span class="p">,</span> <span class="n">country_name</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
<span class="gp">   .....: </span><span class="w">    </span><span class="sd">"""</span>
<span class="gp">   .....: </span><span class="sd">    Chicago -&gt; Chicago-US for city_name column</span>
<span class="gp">   .....: </span><span class="sd">    """</span>
<span class="gp">   .....: </span>    <span class="n">col</span> <span class="o">=</span> <span class="s2">"city_name"</span>
<span class="gp">   .....: </span>    <span class="n">df</span><span class="p">[</span><span class="s2">"city_and_country"</span><span class="p">]</span> <span class="o">=</span> <span class="n">df</span><span class="p">[</span><span class="n">col</span><span class="p">]</span> <span class="o">+</span> <span class="n">country_name</span>
<span class="gp">   .....: </span>    <span class="k">return</span> <span class="n">df</span>
<span class="gp">   .....: </span>

<span class="gp">In [142]: </span><span class="n">df_p</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"city_and_code"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"Chicago, IL"</span><span class="p">]})</span>
</pre>
</div>
</div>

<p><code>extract_city_name</span></code> and <code>add_country_name</span></code> are functions taking and returning <code>DataFrames</span></code>.</p>
<p>Now compare the following:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell49"><span></span><span class="gp">In [143]: </span><span class="n">add_country_name</span><span class="p">(</span><span class="n">extract_city_name</span><span class="p">(</span><span class="n">df_p</span><span class="p">),</span> <span class="n">country_name</span><span class="o">=</span><span class="s2">"US"</span><span class="p">)</span>
<span class="gh">Out[143]: </span>
<span class="go">  city_and_code city_name city_and_country</span>
<span class="go">0   Chicago, IL   Chicago        ChicagoUS</span>
</pre>
</div>
</div>
<p>Is equivalent to:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell50"><span></span><span class="gp">In [144]: </span><span class="n">df_p</span><span class="o">.</span><span class="n">pipe</span><span class="p">(</span><span class="n">extract_city_name</span><span class="p">)</span><span class="o">.</span><span class="n">pipe</span><span class="p">(</span><span class="n">add_country_name</span><span class="p">,</span> <span class="n">country_name</span><span class="o">=</span><span class="s2">"US"</span><span class="p">)</span>
<span class="gh">Out[144]: </span>
<span class="go">  city_and_code city_name city_and_country</span>
<span class="go">0   Chicago, IL   Chicago        ChicagoUS</span>
</pre>
</div>
</div>
<p>pandas encourages the second style, which is known as method chaining.
<code>pipe</span></code> makes it easy to use your own or another library’s functions
in method chains, alongside pandas’ methods.</p>
<p>In the example above, the functions <code>extract_city_name</span></code> and <code>add_country_name</span></code> each expected a <code>DataFrame</span></code> as the first positional argument.
What if the function you wish to apply takes its data as, say, the second argument?
In this case, provide <code>pipe</span></code> with a tuple of <code>(callable,</span> data_keyword)</span></code>.
<code>.pipe</span></code> will route the <code>DataFrame</span></code> to the argument specified in the tuple.</p>
<p>For example, we can fit a regression using statsmodels. Their API expects a formula first and a <code>DataFrame</span></code> as the second argument, <code>data</span></code>. We pass in the function, keyword pair <code>(sm.ols,</span> 'data')</span></code> to <code>pipe</span></code>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell51"><span></span><span class="gp">In [147]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">statsmodels.formula.api</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="nn">sm</span>

<span class="gp">In [148]: </span><span class="n">bb</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span><span class="s2">"data/baseball.csv"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="s2">"id"</span><span class="p">)</span>

<span class="gp">In [149]: </span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">bb</span><span class="o">.</span><span class="n">query</span><span class="p">(</span><span class="s2">"h &gt; 0"</span><span class="p">)</span>
<span class="gp">   .....: </span>    <span class="o">.</span><span class="n">assign</span><span class="p">(</span><span class="n">ln_h</span><span class="o">=</span><span class="k">lambda</span> <span class="n">df</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">log</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">h</span><span class="p">))</span>
<span class="gp">   .....: </span>    <span class="o">.</span><span class="n">pipe</span><span class="p">((</span><span class="n">sm</span><span class="o">.</span><span class="n">ols</span><span class="p">,</span> <span class="s2">"data"</span><span class="p">),</span> <span class="s2">"hr ~ ln_h + year + g + C(lg)"</span><span class="p">)</span>
<span class="gp">   .....: </span>    <span class="o">.</span><span class="n">fit</span><span class="p">()</span>
<span class="gp">   .....: </span>    <span class="o">.</span><span class="n">summary</span><span class="p">()</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....:</span>
<span class="gh">Out[149]:</span>
<span class="go">&lt;class 'statsmodels.iolib.summary.Summary'&gt;</span>
<span class="go">"""</span>
<span class="go">                           OLS Regression Results</span>
<span class="go">==============================================================================</span>
<span class="go">Dep. Variable:                     hr   R-squared:                       0.685</span>
<span class="go">Model:                            OLS   Adj. R-squared:                  0.665</span>
<span class="go">Method:                 Least Squares   F-statistic:                     34.28</span>
<span class="go">Date:                Tue, 22 Nov 2022   Prob (F-statistic):           3.48e-15</span>
<span class="go">Time:                        05:34:17   Log-Likelihood:                -205.92</span>
<span class="go">No. Observations:                  68   AIC:                             421.8</span>
<span class="go">Df Residuals:                      63   BIC:                             432.9</span>
<span class="go">Df Model:                           4</span>
<span class="go">Covariance Type:            nonrobust</span>
<span class="go">===============================================================================</span>
<span class="go">                  coef    std err          t      P&gt;|t|      [0.025      0.975]</span>
<span class="gt">-------------------------------------------------------------------------------</span>
<span class="n">Intercept</span>   <span class="o">-</span><span class="mf">8484.7720</span>   <span class="mf">4664.146</span>     <span class="o">-</span><span class="mf">1.819</span>      <span class="mf">0.074</span>   <span class="o">-</span><span class="mf">1.78e+04</span>     <span class="mf">835.780</span>
<span class="n">C</span><span class="p">(</span><span class="n">lg</span><span class="p">)[</span><span class="n">T</span><span class="o">.</span><span class="n">NL</span><span class="p">]</span>    <span class="o">-</span><span class="mf">2.2736</span>      <span class="mf">1.325</span>     <span class="o">-</span><span class="mf">1.716</span>      <span class="mf">0.091</span>      <span class="o">-</span><span class="mf">4.922</span>       <span class="mf">0.375</span>
<span class="n">ln_h</span>           <span class="o">-</span><span class="mf">1.3542</span>      <span class="mf">0.875</span>     <span class="o">-</span><span class="mf">1.547</span>      <span class="mf">0.127</span>      <span class="o">-</span><span class="mf">3.103</span>       <span class="mf">0.395</span>
<span class="n">year</span>            <span class="mf">4.2277</span>      <span class="mf">2.324</span>      <span class="mf">1.819</span>      <span class="mf">0.074</span>      <span class="o">-</span><span class="mf">0.417</span>       <span class="mf">8.872</span>
<span class="n">g</span>               <span class="mf">0.1841</span>      <span class="mf">0.029</span>      <span class="mf">6.258</span>      <span class="mf">0.000</span>       <span class="mf">0.125</span>       <span class="mf">0.243</span>
<span class="o">==============================================================================</span>
<span class="ne">Omnibus</span>:                       10.875   Durbin-Watson:                   1.999
<span class="n">Prob</span><span class="p">(</span><span class="n">Omnibus</span><span class="p">):</span>                  <span class="mf">0.004</span>   <span class="n">Jarque</span><span class="o">-</span><span class="n">Bera</span> <span class="p">(</span><span class="n">JB</span><span class="p">):</span>               <span class="mf">17.298</span>
<span class="ne">Skew</span>:                           0.537   Prob(JB):                     0.000175
<span class="ne">Kurtosis</span>:                       5.225   Cond. No.                     1.49e+07
<span class="o">==============================================================================</span>

<span class="ne">Notes</span>:
<span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="n">Standard</span> <span class="n">Errors</span> <span class="n">assume</span> <span class="n">that</span> <span class="n">the</span> <span class="n">covariance</span> <span class="n">matrix</span> <span class="n">of</span> <span class="n">the</span> <span class="n">errors</span> <span class="ow">is</span> <span class="n">correctly</span> <span class="n">specified</span><span class="o">.</span>
<span class="p">[</span><span class="mi">2</span><span class="p">]</span> <span class="n">The</span> <span class="n">condition</span> <span class="n">number</span> <span class="ow">is</span> <span class="n">large</span><span class="p">,</span> <span class="mf">1.49e+07</span><span class="o">.</span> <span class="n">This</span> <span class="n">might</span> <span class="n">indicate</span> <span class="n">that</span> <span class="n">there</span> <span class="n">are</span>
<span class="n">strong</span> <span class="n">multicollinearity</span> <span class="ow">or</span> <span class="n">other</span> <span class="n">numerical</span> <span class="n">problems</span><span class="o">.</span>
<span class="s2">"""</span>
</pre>
</div>
</div>
<p>The pipe method is inspired by unix pipes and more recently <a href="https://github.com/tidyverse/dplyr">dplyr</a> and <a href="https://github.com/tidyverse/magrittr">magrittr</a>, which
have introduced the popular <code>(%&gt;%)</span></code> (read pipe) operator for <a href="https://www.r-project.org">R</a>.
The implementation of <code>pipe</span></code> here is quite clean and feels right at home in Python.
We encourage you to view the source code of <a href="../reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</span></code></a>.</p>
</section>

## <h3>Row or column-wise function application</h3>

<p>Arbitrary functions can be applied along the axes of a DataFrame
using the <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a> method, which, like the descriptive
statistics methods, takes an optional <code>axis</span></code> argument:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell52"><span></span><span class="gp">In [145]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">mean</span><span class="p">(</span><span class="n">x</span><span class="p">))</span>
<span class="gh">Out[145]: </span>
<span class="go">one      0.811094</span>
<span class="go">two      1.360588</span>
<span class="go">three    0.187958</span>
<span class="go">dtype: float64</span>

<span class="gp">In [146]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">mean</span><span class="p">(</span><span class="n">x</span><span class="p">),</span> <span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[146]: </span>
<span class="go">a    1.583749</span>
<span class="go">b    0.734929</span>
<span class="go">c    1.133683</span>
<span class="go">d   -0.166914</span>
<span class="go">dtype: float64</span>

<span class="gp">In [147]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="o">.</span><span class="n">max</span><span class="p">()</span> <span class="o">-</span> <span class="n">x</span><span class="o">.</span><span class="n">min</span><span class="p">())</span>
<span class="gh">Out[147]: </span>
<span class="go">one      1.051928</span>
<span class="go">two      1.632779</span>
<span class="go">three    1.840607</span>
<span class="go">dtype: float64</span>

<span class="gp">In [148]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">cumsum</span><span class="p">)</span>
<span class="gh">Out[148]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  1.738035  3.684640 -0.050390</span>
<span class="go">c  2.433281  5.163008  1.177045</span>
<span class="go">d       NaN  5.442353  0.563873</span>

<span class="gp">In [149]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">exp</span><span class="p">)</span>
<span class="gh">Out[149]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  4.034899  5.885648       NaN</span>
<span class="go">b  1.409244  6.767440  0.950858</span>
<span class="go">c  2.004201  4.385785  3.412466</span>
<span class="go">d       NaN  1.322262  0.541630</span>
</pre>
</div>
</div>
<p>The <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a> method will also dispatch on a string method name.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell53"><span></span><span class="gp">In [150]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="s2">"mean"</span><span class="p">)</span>
<span class="gh">Out[150]: </span>
<span class="go">one      0.811094</span>
<span class="go">two      1.360588</span>
<span class="go">three    0.187958</span>
<span class="go">dtype: float64</span>

<span class="gp">In [151]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="s2">"mean"</span><span class="p">,</span> <span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[151]: </span>
<span class="go">a    1.583749</span>
<span class="go">b    0.734929</span>
<span class="go">c    1.133683</span>
<span class="go">d   -0.166914</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>
<p>The return type of the function passed to <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a> affects the
type of the final output from <code>DataFrame.apply</span></code> for the default behaviour:</p>
<ul>
<li><p>If the applied function returns a <code>Series</span></code>, the final output is a <code>DataFrame</span></code>.
The columns match the index of the <code>Series</span></code> returned by the applied function.</p></li>
<li><p>If the applied function returns any other type, the final output is a <code>Series</span></code>.</p></li>
</ul>
<p>This default behaviour can be overridden using the <code>result_type</span></code>, which
accepts three options: <code>reduce</span></code>, <code>broadcast</span></code>, and <code>expand</span></code>.
These will determine how list-likes return values expand (or not) to a <code>DataFrame</span></code>.</p>
<p><a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a> combined with some cleverness can be used to answer many questions
about a data set. For example, suppose we wanted to extract the date where the
maximum value for each column occurred:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell54"><span></span><span class="gp">In [152]: </span><span class="n">tsdf</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">1000</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/1/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">1000</span><span class="p">),</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [153]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="o">.</span><span class="n">idxmax</span><span class="p">())</span>
<span class="gh">Out[153]: </span>
<span class="go">A   2000-08-06</span>
<span class="go">B   2001-01-18</span>
<span class="go">C   2001-07-18</span>
<span class="go">dtype: datetime64[ns]</span>
</pre>
</div>
</div>
<p>You may also pass additional arguments and keyword arguments to the <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a>
method.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell55"><span></span><span class="gp">In [154]: </span><span class="k">def</span><span class="w"> </span><span class="nf">subtract_and_divide</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">sub</span><span class="p">,</span> <span class="n">divide</span><span class="o">=</span><span class="mi">1</span><span class="p">):</span>
<span class="gp">   .....: </span>    <span class="k">return</span> <span class="p">(</span><span class="n">x</span> <span class="o">-</span> <span class="n">sub</span><span class="p">)</span> <span class="o">/</span> <span class="n">divide</span>
<span class="gp">   .....: </span>

<span class="gp">In [155]: </span><span class="n">df_udf</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">ones</span><span class="p">((</span><span class="mi">2</span><span class="p">,</span> <span class="mi">2</span><span class="p">)))</span>

<span class="gp">In [156]: </span><span class="n">df_udf</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">subtract_and_divide</span><span class="p">,</span> <span class="n">args</span><span class="o">=</span><span class="p">(</span><span class="mi">5</span><span class="p">,),</span> <span class="n">divide</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>
<span class="gh">Out[156]: </span>
<span class="go">          0         1</span>
<span class="go">0 -1.333333 -1.333333</span>
<span class="go">1 -1.333333 -1.333333</span>
</pre>
</div>
</div>
<p>Another useful feature is the ability to pass Series methods to carry out some
Series operation on each column or row:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell56"><span></span><span class="gp">In [157]: </span><span class="n">tsdf</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/1/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">10</span><span class="p">),</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [158]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">iloc</span><span class="p">[</span><span class="mi">3</span><span class="p">:</span><span class="mi">7</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [159]: </span><span class="n">tsdf</span>
<span class="gh">Out[159]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01 -0.158131 -0.232466  0.321604</span>
<span class="go">2000-01-02 -1.810340 -3.105758  0.433834</span>
<span class="go">2000-01-03 -1.209847 -1.156793 -0.136794</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08 -0.653602  0.178875  1.008298</span>
<span class="go">2000-01-09  1.007996  0.462824  0.254472</span>
<span class="go">2000-01-10  0.307473  0.600337  1.643950</span>

<span class="gp">In [160]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="o">.</span><span class="n">interpolate</span><span class="p">)</span>
<span class="gh">Out[160]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01 -0.158131 -0.232466  0.321604</span>
<span class="go">2000-01-02 -1.810340 -3.105758  0.433834</span>
<span class="go">2000-01-03 -1.209847 -1.156793 -0.136794</span>
<span class="go">2000-01-04 -1.098598 -0.889659  0.092225</span>
<span class="go">2000-01-05 -0.987349 -0.622526  0.321243</span>
<span class="go">2000-01-06 -0.876100 -0.355392  0.550262</span>
<span class="go">2000-01-07 -0.764851 -0.088259  0.779280</span>
<span class="go">2000-01-08 -0.653602  0.178875  1.008298</span>
<span class="go">2000-01-09  1.007996  0.462824  0.254472</span>
<span class="go">2000-01-10  0.307473  0.600337  1.643950</span>
</pre>
</div>
</div>
<p>Finally, <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a> takes an argument <code>raw</span></code> which is False by default, which
converts each row or column into a Series before applying the function. When
set to True, the passed function will instead receive an ndarray object, which
has positive performance implications if you do not need the indexing
functionality.</p>

## <h3>Aggregation API</h3>

<p>The aggregation API allows one to express possibly multiple aggregation operations in a single concise way.
This API is similar across pandas objects, see <a href="groupby.html#groupby-aggregate">groupby API</span></a>, the
<a href="window.html#window-overview">window API</span></a>, and the <a href="timeseries.html#timeseries-aggregate">resample API</span></a>.
The entry point for aggregation is <a href="../reference/api/pandas.DataFrame.aggregate.html#pandas.DataFrame.aggregate" title="pandas.DataFrame.aggregate"><code>DataFrame.aggregate()</span></code></a>, or the alias
<a href="../reference/api/pandas.DataFrame.agg.html#pandas.DataFrame.agg" title="pandas.DataFrame.agg"><code>DataFrame.agg()</span></code></a>.</p>
<p>We will use a similar starting frame from above:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell57"><span></span><span class="gp">In [161]: </span><span class="n">tsdf</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/1/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">10</span><span class="p">),</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [162]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">iloc</span><span class="p">[</span><span class="mi">3</span><span class="p">:</span><span class="mi">7</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [163]: </span><span class="n">tsdf</span>
<span class="gh">Out[163]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  1.257606  1.004194  0.167574</span>
<span class="go">2000-01-02 -0.749892  0.288112 -0.757304</span>
<span class="go">2000-01-03 -0.207550 -0.298599  0.116018</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.814347 -0.257623  0.869226</span>
<span class="go">2000-01-09 -0.250663 -1.206601  0.896839</span>
<span class="go">2000-01-10  2.169758 -1.333363  0.283157</span>
</pre>
</div>
</div>
<p>Using a single function is equivalent to <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a>. You can also
pass named methods as strings. These will return a <code>Series</span></code> of the aggregated
output:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell58"><span></span><span class="gp">In [164]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">agg</span><span class="p">(</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">sum</span><span class="p">(</span><span class="n">x</span><span class="p">))</span>
<span class="gh">Out[164]: </span>
<span class="go">A    3.033606</span>
<span class="go">B   -1.803879</span>
<span class="go">C    1.575510</span>
<span class="go">dtype: float64</span>

<span class="gp">In [165]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">agg</span><span class="p">(</span><span class="s2">"sum"</span><span class="p">)</span>
<span class="gh">Out[165]: </span>
<span class="go">A    3.033606</span>
<span class="go">B   -1.803879</span>
<span class="go">C    1.575510</span>
<span class="go">dtype: float64</span>

<span class="go"># these are equivalent to a ``.sum()`` because we are aggregating</span>
<span class="go"># on a single function</span>
<span class="gp">In [166]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">sum</span><span class="p">()</span>
<span class="gh">Out[166]: </span>
<span class="go">A    3.033606</span>
<span class="go">B   -1.803879</span>
<span class="go">C    1.575510</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>
<p>Single aggregations on a <code>Series</span></code> this will return a scalar value:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell59"><span></span><span class="gp">In [167]: </span><span class="n">tsdf</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">agg</span><span class="p">(</span><span class="s2">"sum"</span><span class="p">)</span>
<span class="gh">Out[167]: </span><span class="go">3.033606102414146</span>
</pre>
</div>
</div>
<section id="aggregating-with-multiple-functions">
<h4>Aggregating with multiple functions<a class="headerlink" href="#aggregating-with-multiple-functions" title="Link to this heading">#</a></h4>
<p>You can pass multiple aggregation arguments as a list.
The results of each of the passed functions will be a row in the resulting <code>DataFrame</span></code>.
These are naturally named from the aggregation function.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell60"><span></span><span class="gp">In [168]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">agg</span><span class="p">([</span><span class="s2">"sum"</span><span class="p">])</span>
<span class="gh">Out[168]: </span>
<span class="go">            A         B        C</span>
<span class="go">sum  3.033606 -1.803879  1.57551</span>
</pre>
</div>
</div>
<p>Multiple functions yield multiple rows:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell61"><span></span><span class="gp">In [169]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">agg</span><span class="p">([</span><span class="s2">"sum"</span><span class="p">,</span> <span class="s2">"mean"</span><span class="p">])</span>
<span class="gh">Out[169]: </span>
<span class="go">             A         B         C</span>
<span class="go">sum   3.033606 -1.803879  1.575510</span>
<span class="go">mean  0.505601 -0.300647  0.262585</span>
</pre>
</div>
</div>
<p>On a <code>Series</span></code>, multiple functions return a <code>Series</span></code>, indexed by the function names:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell62"><span></span><span class="gp">In [170]: </span><span class="n">tsdf</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">agg</span><span class="p">([</span><span class="s2">"sum"</span><span class="p">,</span> <span class="s2">"mean"</span><span class="p">])</span>
<span class="gh">Out[170]: </span>
<span class="go">sum     3.033606</span>
<span class="go">mean    0.505601</span>
<span class="go">Name: A, dtype: float64</span>
</pre>
</div>
</div>
<p>Passing a <code>lambda</span></code> function will yield a <code>&lt;lambda&gt;</span></code> named row:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell63"><span></span><span class="gp">In [171]: </span><span class="n">tsdf</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">agg</span><span class="p">([</span><span class="s2">"sum"</span><span class="p">,</span> <span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="o">.</span><span class="n">mean</span><span class="p">()])</span>
<span class="gh">Out[171]: </span>
<span class="go">sum         3.033606</span>
<span class="go">&lt;lambda&gt;    0.505601</span>
<span class="go">Name: A, dtype: float64</span>
</pre>
</div>
</div>
<p>Passing a named function will yield that name for the row:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell64"><span></span><span class="gp">In [172]: </span><span class="k">def</span><span class="w"> </span><span class="nf">mymean</span><span class="p">(</span><span class="n">x</span><span class="p">):</span>
<span class="gp">   .....: </span>    <span class="k">return</span> <span class="n">x</span><span class="o">.</span><span class="n">mean</span><span class="p">()</span>
<span class="gp">   .....: </span>

<span class="gp">In [173]: </span><span class="n">tsdf</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">agg</span><span class="p">([</span><span class="s2">"sum"</span><span class="p">,</span> <span class="n">mymean</span><span class="p">])</span>
<span class="gh">Out[173]: </span>
<span class="go">sum       3.033606</span>
<span class="go">mymean    0.505601</span>
<span class="go">Name: A, dtype: float64</span>
</pre>
</div>
</div>
</section>
<section id="aggregating-with-a-dict">
<h4>Aggregating with a dict<a class="headerlink" href="#aggregating-with-a-dict" title="Link to this heading">#</a></h4>
<p>Passing a dictionary of column names to a scalar or a list of scalars, to <code>DataFrame.agg</span></code>
allows you to customize which functions are applied to which columns. Note that the results
are not in any particular order, you can use an <code>OrderedDict</span></code> instead to guarantee ordering.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell65"><span></span><span class="gp">In [174]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">agg</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="s2">"mean"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">:</span> <span class="s2">"sum"</span><span class="p">})</span>
<span class="gh">Out[174]: </span>
<span class="go">A    0.505601</span>
<span class="go">B   -1.803879</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>
<p>Passing a list-like will generate a <code>DataFrame</span></code> output. You will get a matrix-like output
of all of the aggregators. The output will consist of all unique functions. Those that are
not noted for a particular column will be <code>NaN</span></code>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell66"><span></span><span class="gp">In [175]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">agg</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"mean"</span><span class="p">,</span> <span class="s2">"min"</span><span class="p">],</span> <span class="s2">"B"</span><span class="p">:</span> <span class="s2">"sum"</span><span class="p">})</span>
<span class="gh">Out[175]: </span>
<span class="go">             A         B</span>
<span class="go">mean  0.505601       NaN</span>
<span class="go">min  -0.749892       NaN</span>
<span class="go">sum        NaN -1.803879</span>
</pre>
</div>
</div>
</section>
<section id="custom-describe">
<span id="basics-aggregation-custom-describe"></span><h4>Custom describe<a class="headerlink" href="#custom-describe" title="Link to this heading">#</a></h4>
<p>With <code>.agg()</span></code> it is possible to easily create a custom describe function, similar
to the built in <a href="#basics-describe">describe function</span></a>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell67"><span></span><span class="gp">In [176]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">functools</span><span class="w"> </span><span class="kn">import</span> <span class="n">partial</span>

<span class="gp">In [177]: </span><span class="n">q_25</span> <span class="o">=</span> <span class="n">partial</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="o">.</span><span class="n">quantile</span><span class="p">,</span> <span class="n">q</span><span class="o">=</span><span class="mf">0.25</span><span class="p">)</span>

<span class="gp">In [178]: </span><span class="n">q_25</span><span class="o">.</span><span class="vm">__name__</span> <span class="o">=</span> <span class="s2">"25%"</span>

<span class="gp">In [179]: </span><span class="n">q_75</span> <span class="o">=</span> <span class="n">partial</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="o">.</span><span class="n">quantile</span><span class="p">,</span> <span class="n">q</span><span class="o">=</span><span class="mf">0.75</span><span class="p">)</span>

<span class="gp">In [180]: </span><span class="n">q_75</span><span class="o">.</span><span class="vm">__name__</span> <span class="o">=</span> <span class="s2">"75%"</span>

<span class="gp">In [181]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">agg</span><span class="p">([</span><span class="s2">"count"</span><span class="p">,</span> <span class="s2">"mean"</span><span class="p">,</span> <span class="s2">"std"</span><span class="p">,</span> <span class="s2">"min"</span><span class="p">,</span> <span class="n">q_25</span><span class="p">,</span> <span class="s2">"median"</span><span class="p">,</span> <span class="n">q_75</span><span class="p">,</span> <span class="s2">"max"</span><span class="p">])</span>
<span class="gh">Out[181]: </span>
<span class="go">               A         B         C</span>
<span class="go">count   6.000000  6.000000  6.000000</span>
<span class="go">mean    0.505601 -0.300647  0.262585</span>
<span class="go">std     1.103362  0.887508  0.606860</span>
<span class="go">min    -0.749892 -1.333363 -0.757304</span>
<span class="go">25%    -0.239885 -0.979600  0.128907</span>
<span class="go">median  0.303398 -0.278111  0.225365</span>
<span class="go">75%     1.146791  0.151678  0.722709</span>
<span class="go">max     2.169758  1.004194  0.896839</span>
</pre>
</div>
</div>
</section>
</section>
<section id="transform-api">
<span id="basics-transform"></span><h3>Transform API<a class="headerlink" href="#transform-api" title="Link to this heading">#</a></h3>
<p>The <a href="../reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</span></code></a> method returns an object that is indexed the same (same size)
as the original. This API allows you to provide <em>multiple</em> operations at the same
time rather than one-by-one. Its API is quite similar to the <code>.agg</span></code> API.</p>
<p>We create a frame similar to the one used in the above sections.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell68"><span></span><span class="gp">In [182]: </span><span class="n">tsdf</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/1/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">10</span><span class="p">),</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [183]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">iloc</span><span class="p">[</span><span class="mi">3</span><span class="p">:</span><span class="mi">7</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [184]: </span><span class="n">tsdf</span>
<span class="gh">Out[184]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01 -0.428759 -0.864890 -0.675341</span>
<span class="go">2000-01-02 -0.168731  1.338144 -1.279321</span>
<span class="go">2000-01-03 -1.621034  0.438107  0.903794</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.254374 -1.240447 -0.201052</span>
<span class="go">2000-01-09 -0.157795  0.791197 -1.144209</span>
<span class="go">2000-01-10 -0.030876  0.371900  0.061932</span>
</pre>
</div>
</div>
<p>Transform the entire frame. <code>.transform()</span></code> allows input functions as: a NumPy function, a string
function name or a user defined function.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell69"><span></span><span class="gp">In [185]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">transform</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">abs</span><span class="p">)</span>
<span class="gh">Out[185]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.428759  0.864890  0.675341</span>
<span class="go">2000-01-02  0.168731  1.338144  1.279321</span>
<span class="go">2000-01-03  1.621034  0.438107  0.903794</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.254374  1.240447  0.201052</span>
<span class="go">2000-01-09  0.157795  0.791197  1.144209</span>
<span class="go">2000-01-10  0.030876  0.371900  0.061932</span>

<span class="gp">In [186]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">transform</span><span class="p">(</span><span class="s2">"abs"</span><span class="p">)</span>
<span class="gh">Out[186]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.428759  0.864890  0.675341</span>
<span class="go">2000-01-02  0.168731  1.338144  1.279321</span>
<span class="go">2000-01-03  1.621034  0.438107  0.903794</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.254374  1.240447  0.201052</span>
<span class="go">2000-01-09  0.157795  0.791197  1.144209</span>
<span class="go">2000-01-10  0.030876  0.371900  0.061932</span>

<span class="gp">In [187]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">transform</span><span class="p">(</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="o">.</span><span class="n">abs</span><span class="p">())</span>
<span class="gh">Out[187]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.428759  0.864890  0.675341</span>
<span class="go">2000-01-02  0.168731  1.338144  1.279321</span>
<span class="go">2000-01-03  1.621034  0.438107  0.903794</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.254374  1.240447  0.201052</span>
<span class="go">2000-01-09  0.157795  0.791197  1.144209</span>
<span class="go">2000-01-10  0.030876  0.371900  0.061932</span>
</pre>
</div>
</div>
<p>Here <a href="../reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</span></code></a> received a single function; this is equivalent to a <a href="https://numpy.org/doc/stable/reference/ufuncs.html">ufunc</a> application.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell70"><span></span><span class="gp">In [188]: </span><span class="n">np</span><span class="o">.</span><span class="n">abs</span><span class="p">(</span><span class="n">tsdf</span><span class="p">)</span>
<span class="gh">Out[188]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.428759  0.864890  0.675341</span>
<span class="go">2000-01-02  0.168731  1.338144  1.279321</span>
<span class="go">2000-01-03  1.621034  0.438107  0.903794</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.254374  1.240447  0.201052</span>
<span class="go">2000-01-09  0.157795  0.791197  1.144209</span>
<span class="go">2000-01-10  0.030876  0.371900  0.061932</span>
</pre>
</div>
</div>
<p>Passing a single function to <code>.transform()</span></code> with a <code>Series</span></code> will yield a single <code>Series</span></code> in return.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell71"><span></span><span class="gp">In [189]: </span><span class="n">tsdf</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">transform</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">abs</span><span class="p">)</span>
<span class="gh">Out[189]: </span>
<span class="go">2000-01-01    0.428759</span>
<span class="go">2000-01-02    0.168731</span>
<span class="go">2000-01-03    1.621034</span>
<span class="go">2000-01-04         NaN</span>
<span class="go">2000-01-05         NaN</span>
<span class="go">2000-01-06         NaN</span>
<span class="go">2000-01-07         NaN</span>
<span class="go">2000-01-08    0.254374</span>
<span class="go">2000-01-09    0.157795</span>
<span class="go">2000-01-10    0.030876</span>
<span class="go">Freq: D, Name: A, dtype: float64</span>
</pre>
</div>
</div>
<section id="transform-with-multiple-functions">
<h4>Transform with multiple functions<a class="headerlink" href="#transform-with-multiple-functions" title="Link to this heading">#</a></h4>
<p>Passing multiple functions will yield a column MultiIndexed DataFrame.
The first level will be the original frame column names; the second level
will be the names of the transforming functions.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell72"><span></span><span class="gp">In [190]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">transform</span><span class="p">([</span><span class="n">np</span><span class="o">.</span><span class="n">abs</span><span class="p">,</span> <span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span> <span class="o">+</span> <span class="mi">1</span><span class="p">])</span>
<span class="gh">Out[190]: </span>
<span class="go">                   A                   B                   C          </span>
<span class="go">            absolute  &lt;lambda&gt;  absolute  &lt;lambda&gt;  absolute  &lt;lambda&gt;</span>
<span class="go">2000-01-01  0.428759  0.571241  0.864890  0.135110  0.675341  0.324659</span>
<span class="go">2000-01-02  0.168731  0.831269  1.338144  2.338144  1.279321 -0.279321</span>
<span class="go">2000-01-03  1.621034 -0.621034  0.438107  1.438107  0.903794  1.903794</span>
<span class="go">2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.254374  1.254374  1.240447 -0.240447  0.201052  0.798948</span>
<span class="go">2000-01-09  0.157795  0.842205  0.791197  1.791197  1.144209 -0.144209</span>
<span class="go">2000-01-10  0.030876  0.969124  0.371900  1.371900  0.061932  1.061932</span>
</pre>
</div>
</div>
<p>Passing multiple functions to a Series will yield a DataFrame. The
resulting column names will be the transforming functions.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell73"><span></span><span class="gp">In [191]: </span><span class="n">tsdf</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">transform</span><span class="p">([</span><span class="n">np</span><span class="o">.</span><span class="n">abs</span><span class="p">,</span> <span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span> <span class="o">+</span> <span class="mi">1</span><span class="p">])</span>
<span class="gh">Out[191]: </span>
<span class="go">            absolute  &lt;lambda&gt;</span>
<span class="go">2000-01-01  0.428759  0.571241</span>
<span class="go">2000-01-02  0.168731  0.831269</span>
<span class="go">2000-01-03  1.621034 -0.621034</span>
<span class="go">2000-01-04       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN</span>
<span class="go">2000-01-08  0.254374  1.254374</span>
<span class="go">2000-01-09  0.157795  0.842205</span>
<span class="go">2000-01-10  0.030876  0.969124</span>
</pre>
</div>
</div>
</section>
<section id="transforming-with-a-dict">
<h4>Transforming with a dict<a class="headerlink" href="#transforming-with-a-dict" title="Link to this heading">#</a></h4>
<p>Passing a dict of functions will allow selective transforming per column.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell74"><span></span><span class="gp">In [192]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">transform</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">abs</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">:</span> <span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span> <span class="o">+</span> <span class="mi">1</span><span class="p">})</span>
<span class="gh">Out[192]: </span>
<span class="go">                   A         B</span>
<span class="go">2000-01-01  0.428759  0.135110</span>
<span class="go">2000-01-02  0.168731  2.338144</span>
<span class="go">2000-01-03  1.621034  1.438107</span>
<span class="go">2000-01-04       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN</span>
<span class="go">2000-01-08  0.254374 -0.240447</span>
<span class="go">2000-01-09  0.157795  1.791197</span>
<span class="go">2000-01-10  0.030876  1.371900</span>
</pre>
</div>
</div>
<p>Passing a dict of lists will generate a MultiIndexed DataFrame with these
selective transforms.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell75"><span></span><span class="gp">In [193]: </span><span class="n">tsdf</span><span class="o">.</span><span class="n">transform</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">abs</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span> <span class="o">+</span> <span class="mi">1</span><span class="p">,</span> <span class="s2">"sqrt"</span><span class="p">]})</span>
<span class="gh">Out[193]: </span>
<span class="go">                   A         B          </span>
<span class="go">            absolute  &lt;lambda&gt;      sqrt</span>
<span class="go">2000-01-01  0.428759  0.135110       NaN</span>
<span class="go">2000-01-02  0.168731  2.338144  1.156782</span>
<span class="go">2000-01-03  1.621034  1.438107  0.661897</span>
<span class="go">2000-01-04       NaN       NaN       NaN</span>
<span class="go">2000-01-05       NaN       NaN       NaN</span>
<span class="go">2000-01-06       NaN       NaN       NaN</span>
<span class="go">2000-01-07       NaN       NaN       NaN</span>
<span class="go">2000-01-08  0.254374 -0.240447       NaN</span>
<span class="go">2000-01-09  0.157795  1.791197  0.889493</span>
<span class="go">2000-01-10  0.030876  1.371900  0.609836</span>
</pre>
</div>
</div>
</section>
</section>
<section id="applying-elementwise-functions">
<span id="basics-elementwise"></span><h3>Applying elementwise functions<a class="headerlink" href="#applying-elementwise-functions" title="Link to this heading">#</a></h3>
<p>Since not all functions can be vectorized (accept NumPy arrays and return
another array or value), the methods <a href="../reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.DataFrame.map"><code>map()</span></code></a> on DataFrame
and analogously <a href="../reference/api/pandas.Series.map.html#pandas.Series.map" title="pandas.Series.map"><code>map()</span></code></a> on Series accept any Python function taking
a single value and returning a single value. For example:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell76"><span></span><span class="gp">In [194]: </span><span class="n">df4</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">copy</span><span class="p">()</span>

<span class="gp">In [195]: </span><span class="n">df4</span>
<span class="gh">Out[195]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [196]: </span><span class="k">def</span><span class="w"> </span><span class="nf">f</span><span class="p">(</span><span class="n">x</span><span class="p">):</span>
<span class="gp">   .....: </span>    <span class="k">return</span> <span class="nb">len</span><span class="p">(</span><span class="nb">str</span><span class="p">(</span><span class="n">x</span><span class="p">))</span>
<span class="gp">   .....: </span>

<span class="gp">In [197]: </span><span class="n">df4</span><span class="p">[</span><span class="s2">"one"</span><span class="p">]</span><span class="o">.</span><span class="n">map</span><span class="p">(</span><span class="n">f</span><span class="p">)</span>
<span class="gh">Out[197]: </span>
<span class="go">a    18</span>
<span class="go">b    19</span>
<span class="go">c    18</span>
<span class="go">d     3</span>
<span class="go">Name: one, dtype: int64</span>

<span class="gp">In [198]: </span><span class="n">df4</span><span class="o">.</span><span class="n">map</span><span class="p">(</span><span class="n">f</span><span class="p">)</span>
<span class="gh">Out[198]: </span>
<span class="go">   one  two  three</span>
<span class="go">a   18   17      3</span>
<span class="go">b   19   18     20</span>
<span class="go">c   18   18     16</span>
<span class="go">d    3   19     19</span>
</pre>
</div>
</div>
<p><a href="../reference/api/pandas.Series.map.html#pandas.Series.map" title="pandas.Series.map"><code>Series.map()</span></code></a> has an additional feature; it can be used to easily
“link” or “map” values defined by a secondary series. This is closely related
to <a href="merging.html#merging">merging/joining functionality</span></a>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell77"><span></span><span class="gp">In [199]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[</span><span class="s2">"six"</span><span class="p">,</span> <span class="s2">"seven"</span><span class="p">,</span> <span class="s2">"six"</span><span class="p">,</span> <span class="s2">"seven"</span><span class="p">,</span> <span class="s2">"six"</span><span class="p">],</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [200]: </span><span class="n">t</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">({</span><span class="s2">"six"</span><span class="p">:</span> <span class="mf">6.0</span><span class="p">,</span> <span class="s2">"seven"</span><span class="p">:</span> <span class="mf">7.0</span><span class="p">})</span>

<span class="gp">In [201]: </span><span class="n">s</span>
<span class="gh">Out[201]: </span>
<span class="go">a      six</span>
<span class="go">b    seven</span>
<span class="go">c      six</span>
<span class="go">d    seven</span>
<span class="go">e      six</span>
<span class="go">dtype: object</span>

<span class="gp">In [202]: </span><span class="n">s</span><span class="o">.</span><span class="n">map</span><span class="p">(</span><span class="n">t</span><span class="p">)</span>
<span class="gh">Out[202]: </span>
<span class="go">a    6.0</span>
<span class="go">b    7.0</span>
<span class="go">c    6.0</span>
<span class="go">d    7.0</span>
<span class="go">e    6.0</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>
</section>
</section>
<section id="reindexing-and-altering-labels">
<span id="basics-reindexing"></span><h2>Reindexing and altering labels<a class="headerlink" href="#reindexing-and-altering-labels" title="Link to this heading">#</a></h2>
<p><a href="../reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</span></code></a> is the fundamental data alignment method in pandas.
It is used to implement nearly all other features relying on label-alignment
functionality. To <em>reindex</em> means to conform the data to match a given set of
labels along a particular axis. This accomplishes several things:</p>
<ul>
<li><p>Reorders the existing data to match a new set of labels</p></li>
<li><p>Inserts missing value (NA) markers in label locations where no data for
that label existed</p></li>
<li><p>If specified, <strong>fill</strong> data for missing labels using logic (highly relevant
to working with time series data)</p></li>
</ul>
<p>Here is a simple example:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell78"><span></span><span class="gp">In [203]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">])</span>

<span class="gp">In [204]: </span><span class="n">s</span>
<span class="gh">Out[204]: </span>
<span class="go">a    1.695148</span>
<span class="go">b    1.328614</span>
<span class="go">c    1.234686</span>
<span class="go">d   -0.385845</span>
<span class="go">e   -1.326508</span>
<span class="go">dtype: float64</span>

<span class="gp">In [205]: </span><span class="n">s</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"e"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"f"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">])</span>
<span class="gh">Out[205]: </span>
<span class="go">e   -1.326508</span>
<span class="go">b    1.328614</span>
<span class="go">f         NaN</span>
<span class="go">d   -0.385845</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>
<p>Here, the <code>f</span></code> label was not contained in the Series and hence appears as
<code>NaN</span></code> in the result.</p>
<p>With a DataFrame, you can simultaneously reindex the index and columns:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell79"><span></span><span class="gp">In [206]: </span><span class="n">df</span>
<span class="gh">Out[206]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [207]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"c"</span><span class="p">,</span> <span class="s2">"f"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"three"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">])</span>
<span class="gh">Out[207]: </span>
<span class="go">      three       two       one</span>
<span class="go">c  1.227435  1.478369  0.695246</span>
<span class="go">f       NaN       NaN       NaN</span>
<span class="go">b -0.050390  1.912123  0.343054</span>
</pre></div>
</div>
<p>Note that the <code>Index</span></code> objects containing the actual axis labels can be
<strong>shared</strong> between objects. So if we have a Series and a DataFrame, the
following can be done:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell80"><span></span><span class="gp">In [208]: </span><span class="n">rs</span> <span class="o">=</span> <span class="n">s</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">index</span><span class="p">)</span>

<span class="gp">In [209]: </span><span class="n">rs</span>
<span class="gh">Out[209]: </span>
<span class="go">a    1.695148</span>
<span class="go">b    1.328614</span>
<span class="go">c    1.234686</span>
<span class="go">d   -0.385845</span>
<span class="go">dtype: float64</span>

<span class="gp">In [210]: </span><span class="n">rs</span><span class="o">.</span><span class="n">index</span> <span class="ow">is</span> <span class="n">df</span><span class="o">.</span><span class="n">index</span>
<span class="gh">Out[210]: </span><span class="go">True</span>
</pre>
</div>
</div>
<p>This means that the reindexed Series’s index is the same Python object as the
DataFrame’s index.</p>
<p><a href="../reference/api/pandas.DataFrame.reindex.html#pandas.DataFrame.reindex" title="pandas.DataFrame.reindex"><code>DataFrame.reindex()</span></code></a> also supports an “axis-style” calling convention,
where you specify a single <code>labels</span></code> argument and the <code>axis</span></code> it applies to.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell81"><span></span><span class="gp">In [211]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"c"</span><span class="p">,</span> <span class="s2">"f"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"index"</span><span class="p">)</span>
<span class="gh">Out[211]: </span>
<span class="go">        one       two     three</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">f       NaN       NaN       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>

<span class="gp">In [212]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"three"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"columns"</span><span class="p">)</span>
<span class="gh">Out[212]: </span>
<span class="go">      three       two       one</span>
<span class="go">a       NaN  1.772517  1.394981</span>
<span class="go">b -0.050390  1.912123  0.343054</span>
<span class="go">c  1.227435  1.478369  0.695246</span>
<span class="go">d -0.613172  0.279344       NaN</span>
</pre>
</div>
</div>
<div class="admonition seealso">
<p class="admonition-title">See also</p>
<p><a href="advanced.html#advanced">MultiIndex / Advanced Indexing</span></a> is an even more concise way of
doing reindexing.</p>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>When writing performance-sensitive code, there is a good reason to spend
some time becoming a reindexing ninja: <strong>many operations are faster on
pre-aligned data</strong>. Adding two unaligned DataFrames internally triggers a
reindexing step. For exploratory analysis you will hardly notice the
difference (because <code>reindex</span></code> has been heavily optimized), but when CPU
cycles matter sprinkling a few explicit <code>reindex</span></code> calls here and there can
have an impact.</p>
</div>

## <h3>Reindexing to align with another object</h3>

<p>You may wish to take an object and reindex its axes to be labeled the same as
another object. While the syntax for this is straightforward albeit verbose, it
is a common enough operation that the <a href="../reference/api/pandas.DataFrame.reindex_like.html#pandas.DataFrame.reindex_like" title="pandas.DataFrame.reindex_like"><code>reindex_like()</span></code></a> method is
available to make this simpler:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell82"><span></span><span class="gp">In [213]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">])</span>

<span class="gp">In [214]: </span><span class="n">df3</span> <span class="o">=</span> <span class="n">df2</span> <span class="o">-</span> <span class="n">df2</span><span class="o">.</span><span class="n">mean</span><span class="p">()</span>

<span class="gp">In [215]: </span><span class="n">df2</span>
<span class="gh">Out[215]: </span>
<span class="go">        one       two</span>
<span class="go">a  1.394981  1.772517</span>
<span class="go">b  0.343054  1.912123</span>
<span class="go">c  0.695246  1.478369</span>

<span class="gp">In [216]: </span><span class="n">df3</span>
<span class="gh">Out[216]: </span>
<span class="go">        one       two</span>
<span class="go">a  0.583888  0.051514</span>
<span class="go">b -0.468040  0.191120</span>
<span class="go">c -0.115848 -0.242634</span>

<span class="gp">In [217]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex_like</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>
<span class="gh">Out[217]: </span>
<span class="go">        one       two</span>
<span class="go">a  1.394981  1.772517</span>
<span class="go">b  0.343054  1.912123</span>
<span class="go">c  0.695246  1.478369</span>
</pre>
</div>
</div>
</section>
<section id="aligning-objects-with-each-other-with-align">
<span id="basics-align"></span><h3>Aligning objects with each other with <code>align</span></code><a class="headerlink" href="#aligning-objects-with-each-other-with-align" title="Link to this heading">#</a></h3>
<p>The <a href="../reference/api/pandas.Series.align.html#pandas.Series.align" title="pandas.Series.align"><code>align()</span></code></a> method is the fastest way to simultaneously align two objects. It
supports a <code>join</span></code> argument (related to <a href="merging.html#merging">joining and merging</span></a>):</p>
<blockquote>
<div><ul>
<li><p><code>join='outer'</span></code>: take the union of the indexes (default)</p></li>
<li><p><code>join='left'</span></code>: use the calling object’s index</p></li>
<li><p><code>join='right'</span></code>: use the passed object’s index</p></li>
<li><p><code>join='inner'</span></code>: intersect the indexes</p></li>
</ul>
</div></blockquote>
<p>It returns a tuple with both of the reindexed Series:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell83"><span></span><span class="gp">In [218]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">])</span>

<span class="gp">In [219]: </span><span class="n">s1</span> <span class="o">=</span> <span class="n">s</span><span class="p">[:</span><span class="mi">4</span><span class="p">]</span>

<span class="gp">In [220]: </span><span class="n">s2</span> <span class="o">=</span> <span class="n">s</span><span class="p">[</span><span class="mi">1</span><span class="p">:]</span>

<span class="gp">In [221]: </span><span class="n">s1</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">s2</span><span class="p">)</span>
<span class="gh">Out[221]: </span>
<span class="go">(a   -0.186646</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> e         NaN</span>
<span class="go"> dtype: float64,</span>
<span class="go"> a         NaN</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> e    1.114285</span>
<span class="go"> dtype: float64)</span>

<span class="gp">In [222]: </span><span class="n">s1</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">s2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">)</span>
<span class="gh">Out[222]: </span>
<span class="go">(b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64,</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64)</span>

<span class="gp">In [223]: </span><span class="n">s1</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">s2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"left"</span><span class="p">)</span>
<span class="gh">Out[223]: </span>
<span class="go">(a   -0.186646</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64,</span>
<span class="go"> a         NaN</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64)</span>
</pre>
</div>
</div>
<p id="basics-df-join">For DataFrames, the join method will be applied to both the index and the
columns by default:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell84"><span></span><span class="gp">In [224]: </span><span class="n">df</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">)</span>
<span class="gh">Out[224]: </span>
<span class="go">(        one       two</span>
<span class="go"> a  1.394981  1.772517</span>
<span class="go"> b  0.343054  1.912123</span>
<span class="go"> c  0.695246  1.478369,</span>
<span class="go">         one       two</span>
<span class="go"> a  1.394981  1.772517</span>
<span class="go"> b  0.343054  1.912123</span>
<span class="go"> c  0.695246  1.478369)</span>
</pre>
</div>
</div>
<p>You can also pass an <code>axis</span></code> option to only align on the specified axis:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell85"><span></span><span class="gp">In [225]: </span><span class="n">df</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">,</span> <span class="n">axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="gh">Out[225]: </span>
<span class="go">(        one       two     three</span>
<span class="go"> a  1.394981  1.772517       NaN</span>
<span class="go"> b  0.343054  1.912123 -0.050390</span>
<span class="go"> c  0.695246  1.478369  1.227435,</span>
<span class="go">         one       two</span>
<span class="go"> a  1.394981  1.772517</span>
<span class="go"> b  0.343054  1.912123</span>
<span class="go"> c  0.695246  1.478369)</span>
</pre>
</div>
</div>
<p id="basics-align-frame-series">If you pass a Series to <a href="../reference/api/pandas.DataFrame.align.html#pandas.DataFrame.align" title="pandas.DataFrame.align"><code>DataFrame.align()</span></code></a>, you can choose to align both
objects either on the DataFrame’s index or columns using the <code>axis</span></code> argument:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell86"><span></span><span class="gp">In [226]: </span><span class="n">df</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">df2</span><span class="o">.</span><span class="n">iloc</span><span class="p">[</span><span class="mi">0</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[226]: </span>
<span class="go">(        one     three       two</span>
<span class="go"> a  1.394981       NaN  1.772517</span>
<span class="go"> b  0.343054 -0.050390  1.912123</span>
<span class="go"> c  0.695246  1.227435  1.478369</span>
<span class="go"> d       NaN -0.613172  0.279344,</span>
<span class="go"> one      1.394981</span>
<span class="go"> three         NaN</span>
<span class="go"> two      1.772517</span>
<span class="go"> Name: a, dtype: float64)</span>
</pre>
</div>
</div>
</section>
<section id="filling-while-reindexing">
<span id="basics-reindex-fill"></span><h3>Filling while reindexing<a class="headerlink" href="#filling-while-reindexing" title="Link to this heading">#</a></h3>
<p><a href="../reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</span></code></a> takes an optional parameter <code>method</span></code> which is a
filling method chosen from the following table:</p>
<table class="table">
<colgroup>
<col style="width: 37.5%">
<col style="width: 62.5%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Method</p></th>
<th class="head"><p>Action</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>pad / ffill</p></td>
<td><p>Fill values forward</p></td>
</tr>
<tr class="row-odd"><td><p>bfill / backfill</p></td>
<td><p>Fill values backward</p></td>
</tr>
<tr class="row-even"><td><p>nearest</p></td>
<td><p>Fill from the nearest index value</p></td>
</tr>
</tbody>
</table>
<p>We illustrate these fill methods on a simple Series:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell87"><span></span><span class="gp">In [227]: </span><span class="n">rng</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/3/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">8</span><span class="p">)</span>

<span class="gp">In [228]: </span><span class="n">ts</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="n">rng</span><span class="p">)</span>

<span class="gp">In [229]: </span><span class="n">ts2</span> <span class="o">=</span> <span class="n">ts</span><span class="o">.</span><span class="n">iloc</span><span class="p">[[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">]]</span>

<span class="gp">In [230]: </span><span class="n">ts</span>
<span class="gh">Out[230]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.400528</span>
<span class="go">2000-01-05   -0.015083</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    1.414806</span>
<span class="go">2000-01-08    0.118428</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10   -0.936077</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [231]: </span><span class="n">ts2</span>
<span class="gh">Out[231]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">Freq: 3D, dtype: float64</span>

<span class="gp">In [232]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">)</span>
<span class="gh">Out[232]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04         NaN</span>
<span class="go">2000-01-05         NaN</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07         NaN</span>
<span class="go">2000-01-08         NaN</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10         NaN</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [233]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"ffill"</span><span class="p">)</span>
<span class="gh">Out[233]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05    0.183051</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08    2.395489</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [234]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"bfill"</span><span class="p">)</span>
<span class="gh">Out[234]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    2.395489</span>
<span class="go">2000-01-05    2.395489</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    0.733639</span>
<span class="go">2000-01-08    0.733639</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10         NaN</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [235]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"nearest"</span><span class="p">)</span>
<span class="gh">Out[235]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05    2.395489</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08    0.733639</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>
<p>These methods require that the indexes are <strong>ordered</strong> increasing or
decreasing.</p>
<p>Note that the same result could have been achieved using
<a href="missing_data.html#missing-data-fillna">ffill</span></a> (except for <code>method='nearest'</span></code>) or
<a href="missing_data.html#missing-data-interpolate">interpolate</span></a>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell88"><span></span><span class="gp">In [236]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">)</span><span class="o">.</span><span class="n">ffill</span><span class="p">()</span>
<span class="gh">Out[236]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05    0.183051</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08    2.395489</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>
<p><a href="../reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</span></code></a> will raise a ValueError if the index is not monotonically
increasing or decreasing. <a href="../reference/api/pandas.Series.fillna.html#pandas.Series.fillna" title="pandas.Series.fillna"><code>fillna()</span></code></a> and <a href="../reference/api/pandas.Series.interpolate.html#pandas.Series.interpolate" title="pandas.Series.interpolate"><code>interpolate()</span></code></a>
will not perform any checks on the order of the index.</p>

## <h3>Limits on filling while reindexing</h3>

<p>The <code>limit</span></code> and <code>tolerance</span></code> arguments provide additional control over
filling while reindexing. Limit specifies the maximum count of consecutive
matches:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell89"><span></span><span class="gp">In [237]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"ffill"</span><span class="p">,</span> <span class="n">limit</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[237]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05         NaN</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08         NaN</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>
<p>In contrast, tolerance specifies the maximum distance between the index and
indexer values:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell90"><span></span><span class="gp">In [238]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"ffill"</span><span class="p">,</span> <span class="n">tolerance</span><span class="o">=</span><span class="s2">"1 day"</span><span class="p">)</span>
<span class="gh">Out[238]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05         NaN</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08         NaN</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>
<p>Notice that when used on a <code>DatetimeIndex</span></code>, <code>TimedeltaIndex</span></code> or
<code>PeriodIndex</span></code>, <code>tolerance</span></code> will coerced into a <code>Timedelta</span></code> if possible.
This allows you to specify tolerance with appropriate strings.</p>
</section>
<section id="dropping-labels-from-an-axis">
<span id="basics-drop"></span><h3>Dropping labels from an axis<a class="headerlink" href="#dropping-labels-from-an-axis" title="Link to this heading">#</a></h3>
<p>A method closely related to <code>reindex</span></code> is the <a href="../reference/api/pandas.DataFrame.drop.html#pandas.DataFrame.drop" title="pandas.DataFrame.drop"><code>drop()</span></code></a> function.
It removes a set of labels from an axis:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell91"><span></span><span class="gp">In [239]: </span><span class="n">df</span>
<span class="gh">Out[239]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [240]: </span><span class="n">df</span><span class="o">.</span><span class="n">drop</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="gh">Out[240]: </span>
<span class="go">        one       two     three</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>

<span class="gp">In [241]: </span><span class="n">df</span><span class="o">.</span><span class="n">drop</span><span class="p">([</span><span class="s2">"one"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[241]: </span>
<span class="go">        two     three</span>
<span class="go">a  1.772517       NaN</span>
<span class="go">b  1.912123 -0.050390</span>
<span class="go">c  1.478369  1.227435</span>
<span class="go">d  0.279344 -0.613172</span>
</pre>
</div>
</div>
<p>Note that the following also works, but is a bit less obvious / clean:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell92"><span></span><span class="gp">In [242]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">difference</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]))</span>
<span class="gh">Out[242]: </span>
<span class="go">        one       two     three</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
</pre>
</div>
</div>
</section>

## <h3>Renaming / mapping labels</h3>

<p>The <a href="../reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename" title="pandas.DataFrame.rename"><code>rename()</span></code></a> method allows you to relabel an axis based on some
mapping (a dict or Series) or an arbitrary function.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell93"><span></span><span class="gp">In [243]: </span><span class="n">s</span>
<span class="gh">Out[243]: </span>
<span class="go">a   -0.186646</span>
<span class="go">b   -1.692424</span>
<span class="go">c   -0.303893</span>
<span class="go">d   -1.425662</span>
<span class="go">e    1.114285</span>
<span class="go">dtype: float64</span>

<span class="gp">In [244]: </span><span class="n">s</span><span class="o">.</span><span class="n">rename</span><span class="p">(</span><span class="nb">str</span><span class="o">.</span><span class="n">upper</span><span class="p">)</span>
<span class="gh">Out[244]: </span>
<span class="go">A   -0.186646</span>
<span class="go">B   -1.692424</span>
<span class="go">C   -0.303893</span>
<span class="go">D   -1.425662</span>
<span class="go">E    1.114285</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>
<p>If you pass a function, it must return a value when called with any of the
labels (and must produce a set of unique values). A dict or
Series can also be used:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell94"><span></span><span class="gp">In [245]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">{</span><span class="s2">"one"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">:</span> <span class="s2">"bar"</span><span class="p">},</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="p">{</span><span class="s2">"a"</span><span class="p">:</span> <span class="s2">"apple"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">:</span> <span class="s2">"banana"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">:</span> <span class="s2">"durian"</span><span class="p">},</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>
<span class="gh">Out[245]: </span>
<span class="go">             foo       bar     three</span>
<span class="go">apple   1.394981  1.772517       NaN</span>
<span class="go">banana  0.343054  1.912123 -0.050390</span>
<span class="go">c       0.695246  1.478369  1.227435</span>
<span class="go">durian       NaN  0.279344 -0.613172</span>
</pre>
</div>
</div>
<p>If the mapping doesn’t include a column/index label, it isn’t renamed. Note that
extra labels in the mapping don’t throw an error.</p>
<p><a href="../reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename" title="pandas.DataFrame.rename"><code>DataFrame.rename()</span></code></a> also supports an “axis-style” calling convention, where
you specify a single <code>mapper</span></code> and the <code>axis</span></code> to apply that mapping to.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell95"><span></span><span class="gp">In [246]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename</span><span class="p">({</span><span class="s2">"one"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">:</span> <span class="s2">"bar"</span><span class="p">},</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"columns"</span><span class="p">)</span>
<span class="gh">Out[246]: </span>
<span class="go">        foo       bar     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [247]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="s2">"apple"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">:</span> <span class="s2">"banana"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">:</span> <span class="s2">"durian"</span><span class="p">},</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"index"</span><span class="p">)</span>
<span class="gh">Out[247]: </span>
<span class="go">             one       two     three</span>
<span class="go">apple   1.394981  1.772517       NaN</span>
<span class="go">banana  0.343054  1.912123 -0.050390</span>
<span class="go">c       0.695246  1.478369  1.227435</span>
<span class="go">durian       NaN  0.279344 -0.613172</span>
</pre>
</div>
</div>
<p>Finally, <a href="../reference/api/pandas.Series.rename.html#pandas.Series.rename" title="pandas.Series.rename"><code>rename()</span></code></a> also accepts a scalar or list-like
for altering the <code>Series.name</span></code> attribute.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell96"><span></span><span class="gp">In [248]: </span><span class="n">s</span><span class="o">.</span><span class="n">rename</span><span class="p">(</span><span class="s2">"scalar-name"</span><span class="p">)</span>
<span class="gh">Out[248]: </span>
<span class="go">a   -0.186646</span>
<span class="go">b   -1.692424</span>
<span class="go">c   -0.303893</span>
<span class="go">d   -1.425662</span>
<span class="go">e    1.114285</span>
<span class="go">Name: scalar-name, dtype: float64</span>
</pre>
</div>
</div>
<p id="basics-rename-axis">The methods <a href="../reference/api/pandas.DataFrame.rename_axis.html#pandas.DataFrame.rename_axis" title="pandas.DataFrame.rename_axis"><code>DataFrame.rename_axis()</span></code></a> and <a href="../reference/api/pandas.Series.rename_axis.html#pandas.Series.rename_axis" title="pandas.Series.rename_axis"><code>Series.rename_axis()</span></code></a>
allow specific names of a <code>MultiIndex</span></code> to be changed (as opposed to the
labels).</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell97"><span></span><span class="gp">In [249]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"x"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"y"</span><span class="p">:</span> <span class="p">[</span><span class="mi">10</span><span class="p">,</span> <span class="mi">20</span><span class="p">,</span> <span class="mi">30</span><span class="p">,</span> <span class="mi">40</span><span class="p">,</span> <span class="mi">50</span><span class="p">,</span> <span class="mi">60</span><span class="p">]},</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_product</span><span class="p">(</span>
<span class="gp">   .....: </span>        <span class="p">[[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">],</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]],</span> <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"let"</span><span class="p">,</span> <span class="s2">"num"</span><span class="p">]</span>
<span class="gp">   .....: </span>    <span class="p">),</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [250]: </span><span class="n">df</span>
<span class="gh">Out[250]: </span>
<span class="go">         x   y</span>
<span class="go">let num       </span>
<span class="go">a   1    1  10</span>
<span class="go">    2    2  20</span>
<span class="go">b   1    3  30</span>
<span class="go">    2    4  40</span>
<span class="go">c   1    5  50</span>
<span class="go">    2    6  60</span>

<span class="gp">In [251]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename_axis</span><span class="p">(</span><span class="n">index</span><span class="o">=</span><span class="p">{</span><span class="s2">"let"</span><span class="p">:</span> <span class="s2">"abc"</span><span class="p">})</span>
<span class="gh">Out[251]: </span>
<span class="go">         x   y</span>
<span class="go">abc num       </span>
<span class="go">a   1    1  10</span>
<span class="go">    2    2  20</span>
<span class="go">b   1    3  30</span>
<span class="go">    2    4  40</span>
<span class="go">c   1    5  50</span>
<span class="go">    2    6  60</span>

<span class="gp">In [252]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename_axis</span><span class="p">(</span><span class="n">index</span><span class="o">=</span><span class="nb">str</span><span class="o">.</span><span class="n">upper</span><span class="p">)</span>
<span class="gh">Out[252]: </span>
<span class="go">         x   y</span>
<span class="go">LET NUM       </span>
<span class="go">a   1    1  10</span>
<span class="go">    2    2  20</span>
<span class="go">b   1    3  30</span>
<span class="go">    2    4  40</span>
<span class="go">c   1    5  50</span>
<span class="go">    2    6  60</span>
</pre>
</div>
</div>

# <h2>Iteration</h2>

<p>The behavior of basic iteration over pandas objects depends on the type. When iterating over a Series, it is regarded as array-like, and basic iteration produces the values. DataFrames follow the dict-like convention of iterating over the “keys” of the objects.</p>

<p>In short, basic iteration (<code>for</span> i</span> in</span> object</span></code>) produces:</p>

<ul>
<li><p><strong>Series</strong>: values</p></li>
<li><p><strong>DataFrame</strong>: column labels</p></li>
</ul>

<p>Thus, for example, iterating over a DataFrame gives you the column names:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell98"><span></span><span class="gp">In [253]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"col1"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="s2">"col2"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">)},</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [254]: </span><span class="k">for</span> <span class="n">col</span> <span class="ow">in</span> <span class="n">df</span><span class="p">:</span>
<span class="gp">   .....: </span>    <span class="nb">print</span><span class="p">(</span><span class="n">col</span><span class="p">)</span>
<span class="gp">   .....: </span>
<span class="go">col1</span>
<span class="go">col2</span>
</pre>
</div>
</div>
<p>pandas objects also have the dict-like <a href="../reference/api/pandas.DataFrame.items.html#pandas.DataFrame.items" title="pandas.DataFrame.items"><code>items()</span></code></a> method to
iterate over the (key, value) pairs.</p>
<p>To iterate over the rows of a DataFrame, you can use the following methods:</p>
<ul>
<li><p><a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a>: Iterate over the rows of a DataFrame as (index, Series) pairs.
This converts the rows to Series objects, which can change the dtypes and has some
performance implications.</p></li>
<li><p><a href="../reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a>: Iterate over the rows of a DataFrame
as namedtuples of the values.  This is a lot faster than
<a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a>, and is in most cases preferable to use
to iterate over the values of a DataFrame.</p></li>
</ul>
<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Iterating through pandas objects is generally <strong>slow</strong>. In many cases,
iterating manually over the rows is not needed and can be avoided with
one of the following approaches:</p>
<ul>
<li><p>Look for a <em>vectorized</em> solution: many operations can be performed using
built-in methods or NumPy functions, (boolean) indexing, …</p></li>
<li><p>When you have a function that cannot work on the full DataFrame/Series
at once, it is better to use <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a> instead of iterating
over the values. See the docs on <a href="#basics-apply">function application</span></a>.</p></li>
<li><p>If you need to do iterative manipulations on the values but performance is
important, consider writing the inner loop with cython or numba.
See the <a href="enhancingperf.html#enhancingperf">enhancing performance</span></a> section for some
examples of this approach.</p></li>
</ul>
</div>
<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>You should <strong>never modify</strong> something you are iterating over.
This is not guaranteed to work in all cases. Depending on the
data types, the iterator returns a copy and not a view, and writing
to it will have no effect!</p>
<p>For example, in the following case setting the value has no effect:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell99"><span></span><span class="gp">In [255]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">]})</span>

<span class="gp">In [256]: </span><span class="k">for</span> <span class="n">index</span><span class="p">,</span> <span class="n">row</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">iterrows</span><span class="p">():</span>
<span class="gp">   .....: </span>    <span class="n">row</span><span class="p">[</span><span class="s2">"a"</span><span class="p">]</span> <span class="o">=</span> <span class="mi">10</span>
<span class="gp">   .....: </span>

<span class="gp">In [257]: </span><span class="n">df</span>
<span class="gh">Out[257]: </span>
<span class="go">   a  b</span>
<span class="go">0  1  a</span>
<span class="go">1  2  b</span>
<span class="go">2  3  c</span>
</pre>
</div>
</div>
</div>
<section id="items">
<h3>items<a class="headerlink" href="#items" title="Link to this heading">#</a></h3>
<p>Consistent with the dict-like interface, <a href="../reference/api/pandas.DataFrame.items.html#pandas.DataFrame.items" title="pandas.DataFrame.items"><code>items()</span></code></a> iterates
through key-value pairs:</p>
<ul>
<li><p><strong>Series</strong>: (index, scalar value) pairs</p></li>
<li><p><strong>DataFrame</strong>: (column, Series) pairs</p></li>
</ul>
<p>For example:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell100"><span></span><span class="gp">In [258]: </span><span class="k">for</span> <span class="n">label</span><span class="p">,</span> <span class="n">ser</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">items</span><span class="p">():</span>
<span class="gp">   .....: </span>    <span class="nb">print</span><span class="p">(</span><span class="n">label</span><span class="p">)</span>
<span class="gp">   .....: </span>    <span class="nb">print</span><span class="p">(</span><span class="n">ser</span><span class="p">)</span>
<span class="gp">   .....: </span>
<span class="go">a</span>
<span class="go">0    1</span>
<span class="go">1    2</span>
<span class="go">2    3</span>
<span class="go">Name: a, dtype: int64</span>
<span class="go">b</span>
<span class="go">0    a</span>
<span class="go">1    b</span>
<span class="go">2    c</span>
<span class="go">Name: b, dtype: object</span>
</pre>
</div>
</div>
</section>
<section id="iterrows">
<span id="basics-iterrows"></span><h3>iterrows<a class="headerlink" href="#iterrows" title="Link to this heading">#</a></h3>
<p><a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a> allows you to iterate through the rows of a
DataFrame as Series objects. It returns an iterator yielding each
index value along with a Series containing the data in each row:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell101"><span></span><span class="gp">In [259]: </span><span class="k">for</span> <span class="n">row_index</span><span class="p">,</span> <span class="n">row</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">iterrows</span><span class="p">():</span>
<span class="gp">   .....: </span>    <span class="nb">print</span><span class="p">(</span><span class="n">row_index</span><span class="p">,</span> <span class="n">row</span><span class="p">,</span> <span class="n">sep</span><span class="o">=</span><span class="s2">"</span><span class="se">\n</span><span class="s2">"</span><span class="p">)</span>
<span class="gp">   .....: </span>
<span class="go">0</span>
<span class="go">a    1</span>
<span class="go">b    a</span>
<span class="go">Name: 0, dtype: object</span>
<span class="go">1</span>
<span class="go">a    2</span>
<span class="go">b    b</span>
<span class="go">Name: 1, dtype: object</span>
<span class="go">2</span>
<span class="go">a    3</span>
<span class="go">b    c</span>
<span class="go">Name: 2, dtype: object</span>
</pre>
</div>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Because <a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a> returns a Series for each row,
it does <strong>not</strong> preserve dtypes across the rows (dtypes are
preserved across columns for DataFrames). For example,</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell102"><span></span><span class="gp">In [260]: </span><span class="n">df_orig</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="mi">1</span><span class="p">,</span> <span class="mf">1.5</span><span class="p">]],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"int"</span><span class="p">,</span> <span class="s2">"float"</span><span class="p">])</span>

<span class="gp">In [261]: </span><span class="n">df_orig</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[261]: </span>
<span class="go">int        int64</span>
<span class="go">float    float64</span>
<span class="go">dtype: object</span>

<span class="gp">In [262]: </span><span class="n">row</span> <span class="o">=</span> <span class="nb">next</span><span class="p">(</span><span class="n">df_orig</span><span class="o">.</span><span class="n">iterrows</span><span class="p">())[</span><span class="mi">1</span><span class="p">]</span>

<span class="gp">In [263]: </span><span class="n">row</span>
<span class="gh">Out[263]: </span>
<span class="go">int      1.0</span>
<span class="go">float    1.5</span>
<span class="go">Name: 0, dtype: float64</span>
</pre>
</div>
</div>

<p>All values in <code>row</span></code>, returned as a Series, are now upcasted
to floats, also the original integer value in column <code>x</span></code>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell103"><span></span><span class="gp">In [264]: </span><span class="n">row</span><span class="p">[</span><span class="s2">"int"</span><span class="p">]</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[264]: </span><span class="go">dtype('float64')</span>

<span class="gp">In [265]: </span><span class="n">df_orig</span><span class="p">[</span><span class="s2">"int"</span><span class="p">]</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[265]: </span><span class="go">dtype('int64')</span>
</pre>
</div>
</div>
<p>To preserve dtypes while iterating over the rows, it is better
to use <a href="../reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a> which returns namedtuples of the values
and which is generally much faster than <a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a>.</p>
</div>
<p>For instance, a contrived way to transpose the DataFrame would be:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell104"><span></span><span class="gp">In [266]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"x"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"y"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">]})</span>

<span class="gp">In [267]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>
<span class="go">   x  y</span>
<span class="go">0  1  4</span>
<span class="go">1  2  5</span>
<span class="go">2  3  6</span>

<span class="gp">In [268]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df2</span><span class="o">.</span><span class="n">T</span><span class="p">)</span>
<span class="go">   0  1  2</span>
<span class="go">x  1  2  3</span>
<span class="go">y  4  5  6</span>

<span class="gp">In [269]: </span><span class="n">df2_t</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="n">idx</span><span class="p">:</span> <span class="n">values</span> <span class="k">for</span> <span class="n">idx</span><span class="p">,</span> <span class="n">values</span> <span class="ow">in</span> <span class="n">df2</span><span class="o">.</span><span class="n">iterrows</span><span class="p">()})</span>

<span class="gp">In [270]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df2_t</span><span class="p">)</span>
<span class="go">   0  1  2</span>
<span class="go">x  1  2  3</span>
<span class="go">y  4  5  6</span>
</pre>
</div>
</div>

## <h3>itertuples</h3>

<p>The <a href="../reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a> method will return an iterator
yielding a namedtuple for each row in the DataFrame. The first element
of the tuple will be the row’s corresponding index value, while the
remaining values are the row values.</p>
<p>For instance:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell105"><span></span><span class="gp">In [271]: </span><span class="k">for</span> <span class="n">row</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">itertuples</span><span class="p">():</span>
<span class="gp">   .....: </span>    <span class="nb">print</span><span class="p">(</span><span class="n">row</span><span class="p">)</span>
<span class="gp">   .....: </span>
<span class="go">Pandas(Index=0, a=1, b='a')</span>
<span class="go">Pandas(Index=1, a=2, b='b')</span>
<span class="go">Pandas(Index=2, a=3, b='c')</span>
</pre>
</div>
</div>
<p>This method does not convert the row to a Series object; it merely
returns the values inside a namedtuple. Therefore,
<a href="../reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a> preserves the data type of the values
and is generally faster as <a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a>.</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The column names will be renamed to positional names if they are
invalid Python identifiers, repeated, or start with an underscore.
With a large number of columns (&gt;255), regular tuples are returned.</p>
</div>
</section>
</section>
<section id="dt-accessor">
<span id="basics-dt-accessors"></span><h2>.dt accessor<a class="headerlink" href="#dt-accessor" title="Link to this heading">#</a></h2>
<p><code>Series</span></code> has an accessor to succinctly return datetime like properties for the
<em>values</em> of the Series, if it is a datetime/period like Series.
This will return a Series, indexed like the existing Series.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell106"><span></span><span class="go"># datetime</span>
<span class="gp">In [272]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101 09:10:12"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [273]: </span><span class="n">s</span>
<span class="gh">Out[273]: </span>
<span class="go">0   2013-01-01 09:10:12</span>
<span class="go">1   2013-01-02 09:10:12</span>
<span class="go">2   2013-01-03 09:10:12</span>
<span class="go">3   2013-01-04 09:10:12</span>
<span class="go">dtype: datetime64[ns]</span>

<span class="gp">In [274]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">hour</span>
<span class="gh">Out[274]: </span>
<span class="go">0    9</span>
<span class="go">1    9</span>
<span class="go">2    9</span>
<span class="go">3    9</span>
<span class="go">dtype: int32</span>

<span class="gp">In [275]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">second</span>
<span class="gh">Out[275]: </span>
<span class="go">0    12</span>
<span class="go">1    12</span>
<span class="go">2    12</span>
<span class="go">3    12</span>
<span class="go">dtype: int32</span>

<span class="gp">In [276]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">day</span>
<span class="gh">Out[276]: </span>
<span class="go">0    1</span>
<span class="go">1    2</span>
<span class="go">2    3</span>
<span class="go">3    4</span>
<span class="go">dtype: int32</span>
</pre>
</div>
</div>
<p>This enables nice expressions like this:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell107"><span></span><span class="gp">In [277]: </span><span class="n">s</span><span class="p">[</span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">day</span> <span class="o">==</span> <span class="mi">2</span><span class="p">]</span>
<span class="gh">Out[277]: </span>
<span class="go">1   2013-01-02 09:10:12</span>
<span class="go">dtype: datetime64[ns]</span>
</pre>
</div>
</div>
<p>You can easily produces tz aware transformations:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell108"><span></span><span class="gp">In [278]: </span><span class="n">stz</span> <span class="o">=</span> <span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz_localize</span><span class="p">(</span><span class="s2">"US/Eastern"</span><span class="p">)</span>

<span class="gp">In [279]: </span><span class="n">stz</span>
<span class="gh">Out[279]: </span>
<span class="go">0   2013-01-01 09:10:12-05:00</span>
<span class="go">1   2013-01-02 09:10:12-05:00</span>
<span class="go">2   2013-01-03 09:10:12-05:00</span>
<span class="go">3   2013-01-04 09:10:12-05:00</span>
<span class="go">dtype: datetime64[ns, US/Eastern]</span>

<span class="gp">In [280]: </span><span class="n">stz</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz</span>
<span class="gh">Out[280]: </span><span class="go">&lt;DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD&gt;</span>
</pre>
</div>
</div>
<p>You can also chain these types of operations:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell109"><span></span><span class="gp">In [281]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz_localize</span><span class="p">(</span><span class="s2">"UTC"</span><span class="p">)</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz_convert</span><span class="p">(</span><span class="s2">"US/Eastern"</span><span class="p">)</span>
<span class="gh">Out[281]: </span>
<span class="go">0   2013-01-01 04:10:12-05:00</span>
<span class="go">1   2013-01-02 04:10:12-05:00</span>
<span class="go">2   2013-01-03 04:10:12-05:00</span>
<span class="go">3   2013-01-04 04:10:12-05:00</span>
<span class="go">dtype: datetime64[ns, US/Eastern]</span>
</pre>
</div>
</div>
<p>You can also format datetime values as strings with <a href="../reference/api/pandas.Series.dt.strftime.html#pandas.Series.dt.strftime" title="pandas.Series.dt.strftime"><code>Series.dt.strftime()</span></code></a> which supports the same format as the standard <a href="https://docs.python.org/3/library/datetime.html#datetime.datetime.strftime" title="(in Python v3.13)"><code>strftime()</span></code></a>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell110"><span></span><span class="go"># DatetimeIndex</span>
<span class="gp">In [282]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [283]: </span><span class="n">s</span>
<span class="gh">Out[283]: </span>
<span class="go">0   2013-01-01</span>
<span class="go">1   2013-01-02</span>
<span class="go">2   2013-01-03</span>
<span class="go">3   2013-01-04</span>
<span class="go">dtype: datetime64[ns]</span>

<span class="gp">In [284]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">strftime</span><span class="p">(</span><span class="s2">"%Y/%m/</span><span class="si">%d</span><span class="s2">"</span><span class="p">)</span>
<span class="gh">Out[284]: </span>
<span class="go">0    2013/01/01</span>
<span class="go">1    2013/01/02</span>
<span class="go">2    2013/01/03</span>
<span class="go">3    2013/01/04</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell111"><span></span><span class="go"># PeriodIndex</span>
<span class="gp">In [285]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">period_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [286]: </span><span class="n">s</span>
<span class="gh">Out[286]: </span>
<span class="go">0    2013-01-01</span>
<span class="go">1    2013-01-02</span>
<span class="go">2    2013-01-03</span>
<span class="go">3    2013-01-04</span>
<span class="go">dtype: period[D]</span>

<span class="gp">In [287]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">strftime</span><span class="p">(</span><span class="s2">"%Y/%m/</span><span class="si">%d</span><span class="s2">"</span><span class="p">)</span>
<span class="gh">Out[287]: </span>
<span class="go">0    2013/01/01</span>
<span class="go">1    2013/01/02</span>
<span class="go">2    2013/01/03</span>
<span class="go">3    2013/01/04</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p>The <code>.dt</span></code> accessor works for period and timedelta dtypes.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell112"><span></span><span class="go"># period</span>
<span class="gp">In [288]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">period_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"D"</span><span class="p">))</span>

<span class="gp">In [289]: </span><span class="n">s</span>
<span class="gh">Out[289]: </span>
<span class="go">0    2013-01-01</span>
<span class="go">1    2013-01-02</span>
<span class="go">2    2013-01-03</span>
<span class="go">3    2013-01-04</span>
<span class="go">dtype: period[D]</span>

<span class="gp">In [290]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">year</span>
<span class="gh">Out[290]: </span>
<span class="go">0    2013</span>
<span class="go">1    2013</span>
<span class="go">2    2013</span>
<span class="go">3    2013</span>
<span class="go">dtype: int64</span>

<span class="gp">In [291]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">day</span>
<span class="gh">Out[291]: </span>
<span class="go">0    1</span>
<span class="go">1    2</span>
<span class="go">2    3</span>
<span class="go">3    4</span>
<span class="go">dtype: int64</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell113"><span></span><span class="go"># timedelta</span>
<span class="gp">In [292]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">timedelta_range</span><span class="p">(</span><span class="s2">"1 day 00:00:05"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"s"</span><span class="p">))</span>

<span class="gp">In [293]: </span><span class="n">s</span>
<span class="gh">Out[293]: </span>
<span class="go">0   1 days 00:00:05</span>
<span class="go">1   1 days 00:00:06</span>
<span class="go">2   1 days 00:00:07</span>
<span class="go">3   1 days 00:00:08</span>
<span class="go">dtype: timedelta64[ns]</span>

<span class="gp">In [294]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">days</span>
<span class="gh">Out[294]: </span>
<span class="go">0    1</span>
<span class="go">1    1</span>
<span class="go">2    1</span>
<span class="go">3    1</span>
<span class="go">dtype: int64</span>

<span class="gp">In [295]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">seconds</span>
<span class="gh">Out[295]: </span>
<span class="go">0    5</span>
<span class="go">1    6</span>
<span class="go">2    7</span>
<span class="go">3    8</span>
<span class="go">dtype: int32</span>

<span class="gp">In [296]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">components</span>
<span class="gh">Out[296]: </span>
<span class="go">   days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds</span>
<span class="go">0     1      0        0        5             0             0            0</span>
<span class="go">1     1      0        0        6             0             0            0</span>
<span class="go">2     1      0        0        7             0             0            0</span>
<span class="go">3     1      0        0        8             0             0            0</span>
</pre>
</div>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>Series.dt</span></code> will raise a <code>TypeError</span></code> if you access with a non-datetime-like values.</p>
</div>
</section>
<section id="vectorized-string-methods">
<h2>Vectorized string methods<a class="headerlink" href="#vectorized-string-methods" title="Link to this heading">#</a></h2>
<p>Series is equipped with a set of string processing methods that make it easy to
operate on each element of the array. Perhaps most importantly, these methods
exclude missing/NA values automatically. These are accessed via the Series’s
<code>str</span></code> attribute and generally have names matching the equivalent (scalar)
built-in string methods. For example:</p>
<blockquote>
<div><div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell114"><span></span><span class="gp">In [297]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">,</span> <span class="s2">"Aaba"</span><span class="p">,</span> <span class="s2">"Baca"</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="s2">"CABA"</span><span class="p">,</span> <span class="s2">"dog"</span><span class="p">,</span> <span class="s2">"cat"</span><span class="p">],</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"string"</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [298]: </span><span class="n">s</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">()</span>
<span class="gh">Out[298]: </span>
<span class="go">0       a</span>
<span class="go">1       b</span>
<span class="go">2       c</span>
<span class="go">3    aaba</span>
<span class="go">4    baca</span>
<span class="go">5    &lt;NA&gt;</span>
<span class="go">6    caba</span>
<span class="go">7     dog</span>
<span class="go">8     cat</span>
<span class="go">dtype: string</span>
</pre>
</div>
</div>
</div></blockquote>
<p>Powerful pattern-matching methods are provided as well, but note that
pattern-matching generally uses <a href="https://docs.python.org/3/library/re.html">regular expressions</a> by default (and in some cases
always uses them).</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Prior to pandas 1.0, string methods were only available on <code>object</span></code> -dtype
<code>Series</span></code>. pandas 1.0 added the <a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a> which is dedicated
to strings. See <a href="text.html#text-types">Text data types</span></a> for more.</p>
</div>
<p>Please see <a href="text.html#text-string-methods">Vectorized String Methods</span></a> for a complete
description.</p>
</section>
<section id="sorting">
<span id="basics-sorting"></span><h2>Sorting<a class="headerlink" href="#sorting" title="Link to this heading">#</a></h2>
<p>pandas supports three kinds of sorting: sorting by index labels,
sorting by column values, and sorting by a combination of both.</p>
<section id="by-index">
<span id="basics-sort-index"></span><h3>By index<a class="headerlink" href="#by-index" title="Link to this heading">#</a></h3>
<p>The <a href="../reference/api/pandas.Series.sort_index.html#pandas.Series.sort_index" title="pandas.Series.sort_index"><code>Series.sort_index()</span></code></a> and <a href="../reference/api/pandas.DataFrame.sort_index.html#pandas.DataFrame.sort_index" title="pandas.DataFrame.sort_index"><code>DataFrame.sort_index()</span></code></a> methods are
used to sort a pandas object by its index levels.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell115"><span></span><span class="gp">In [299]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"one"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">]),</span>
<span class="gp">   .....: </span>        <span class="s2">"two"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">4</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]),</span>
<span class="gp">   .....: </span>        <span class="s2">"three"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]),</span>
<span class="gp">   .....: </span>    <span class="p">}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [300]: </span><span class="n">unsorted_df</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"three"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [301]: </span><span class="n">unsorted_df</span>
<span class="gh">Out[301]: </span>
<span class="go">      three       two       one</span>
<span class="go">a       NaN -1.152244  0.562973</span>
<span class="go">d -0.252916 -0.109597       NaN</span>
<span class="go">c  1.273388 -0.167123  0.640382</span>
<span class="go">b -0.098217  0.009797 -1.299504</span>

<span class="go"># DataFrame</span>
<span class="gp">In [302]: </span><span class="n">unsorted_df</span><span class="o">.</span><span class="n">sort_index</span><span class="p">()</span>
<span class="gh">Out[302]: </span>
<span class="go">      three       two       one</span>
<span class="go">a       NaN -1.152244  0.562973</span>
<span class="go">b -0.098217  0.009797 -1.299504</span>
<span class="go">c  1.273388 -0.167123  0.640382</span>
<span class="go">d -0.252916 -0.109597       NaN</span>

<span class="gp">In [303]: </span><span class="n">unsorted_df</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">ascending</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
<span class="gh">Out[303]: </span>
<span class="go">      three       two       one</span>
<span class="go">d -0.252916 -0.109597       NaN</span>
<span class="go">c  1.273388 -0.167123  0.640382</span>
<span class="go">b -0.098217  0.009797 -1.299504</span>
<span class="go">a       NaN -1.152244  0.562973</span>

<span class="gp">In [304]: </span><span class="n">unsorted_df</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[304]: </span>
<span class="go">        one     three       two</span>
<span class="go">a  0.562973       NaN -1.152244</span>
<span class="go">d       NaN -0.252916 -0.109597</span>
<span class="go">c  0.640382  1.273388 -0.167123</span>
<span class="go">b -1.299504 -0.098217  0.009797</span>

<span class="go"># Series</span>
<span class="gp">In [305]: </span><span class="n">unsorted_df</span><span class="p">[</span><span class="s2">"three"</span><span class="p">]</span><span class="o">.</span><span class="n">sort_index</span><span class="p">()</span>
<span class="gh">Out[305]: </span>
<span class="go">a         NaN</span>
<span class="go">b   -0.098217</span>
<span class="go">c    1.273388</span>
<span class="go">d   -0.252916</span>
<span class="go">Name: three, dtype: float64</span>
</pre>
</div>
</div>
<p id="basics-sort-index-key">Sorting by index also supports a <code>key</span></code> parameter that takes a callable
function to apply to the index being sorted. For <code>MultiIndex</span></code> objects,
the key is applied per-level to the levels specified by <code>level</span></code>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell116"><span></span><span class="gp">In [306]: </span><span class="n">s1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]})</span><span class="o">.</span><span class="n">set_index</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="nb">list</span><span class="p">(</span><span class="s2">"ab"</span><span class="p">)</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [307]: </span><span class="n">s1</span>
<span class="gh">Out[307]: </span>
<span class="go">     c</span>
<span class="go">a b   </span>
<span class="go">B 1  2</span>
<span class="go">a 2  3</span>
<span class="go">C 3  4</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell117"><span></span><span class="gp">In [308]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">level</span><span class="o">=</span><span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[308]: </span>
<span class="go">     c</span>
<span class="go">a b   </span>
<span class="go">B 1  2</span>
<span class="go">C 3  4</span>
<span class="go">a 2  3</span>

<span class="gp">In [309]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">level</span><span class="o">=</span><span class="s2">"a"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="k">lambda</span> <span class="n">idx</span><span class="p">:</span> <span class="n">idx</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">())</span>
<span class="gh">Out[309]: </span>
<span class="go">     c</span>
<span class="go">a b   </span>
<span class="go">a 2  3</span>
<span class="go">B 1  2</span>
<span class="go">C 3  4</span>
</pre>
</div>
</div>
<p>For information on key sorting by value, see <a href="#basics-sort-value-key">value sorting</span></a>.</p>
</section>
<section id="by-values">
<span id="basics-sort-values"></span><h3>By values<a class="headerlink" href="#by-values" title="Link to this heading">#</a></h3>
<p>The <a href="../reference/api/pandas.Series.sort_values.html#pandas.Series.sort_values" title="pandas.Series.sort_values"><code>Series.sort_values()</span></code></a> method is used to sort a <code>Series</span></code> by its values. The
<a href="../reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</span></code></a> method is used to sort a <code>DataFrame</span></code> by its column or row values.
The optional <code>by</span></code> parameter to <a href="../reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</span></code></a> may used to specify one or more columns
to use to determine the sorted order.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell118"><span></span><span class="gp">In [310]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"one"</span><span class="p">:</span> <span class="p">[</span><span class="mi">2</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">],</span> <span class="s2">"two"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">4</span><span class="p">],</span> <span class="s2">"three"</span><span class="p">:</span> <span class="p">[</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">]}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [311]: </span><span class="n">df1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="s2">"two"</span><span class="p">)</span>
<span class="gh">Out[311]: </span>
<span class="go">   one  two  three</span>
<span class="go">0    2    1      5</span>
<span class="go">2    1    2      3</span>
<span class="go">1    1    3      4</span>
<span class="go">3    1    4      2</span>
</pre>
</div>
</div>
<p>The <code>by</span></code> parameter can take a list of column names, e.g.:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell119"><span></span><span class="gp">In [312]: </span><span class="n">df1</span><span class="p">[[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"three"</span><span class="p">]]</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="p">[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">])</span>
<span class="gh">Out[312]: </span>
<span class="go">   one  two  three</span>
<span class="go">2    1    2      3</span>
<span class="go">1    1    3      4</span>
<span class="go">3    1    4      2</span>
<span class="go">0    2    1      5</span>
</pre>
</div>
</div>
<p>These methods have special treatment of NA values via the <code>na_position</span></code>
argument:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell120"><span></span><span class="gp">In [313]: </span><span class="n">s</span><span class="p">[</span><span class="mi">2</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [314]: </span><span class="n">s</span><span class="o">.</span><span class="n">sort_values</span><span class="p">()</span>
<span class="gh">Out[314]: </span>
<span class="go">0       A</span>
<span class="go">3    Aaba</span>
<span class="go">1       B</span>
<span class="go">4    Baca</span>
<span class="go">6    CABA</span>
<span class="go">8     cat</span>
<span class="go">7     dog</span>
<span class="go">2    &lt;NA&gt;</span>
<span class="go">5    &lt;NA&gt;</span>
<span class="go">dtype: string</span>

<span class="gp">In [315]: </span><span class="n">s</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">na_position</span><span class="o">=</span><span class="s2">"first"</span><span class="p">)</span>
<span class="gh">Out[315]: </span>
<span class="go">2    &lt;NA&gt;</span>
<span class="go">5    &lt;NA&gt;</span>
<span class="go">0       A</span>
<span class="go">3    Aaba</span>
<span class="go">1       B</span>
<span class="go">4    Baca</span>
<span class="go">6    CABA</span>
<span class="go">8     cat</span>
<span class="go">7     dog</span>
<span class="go">dtype: string</span>
</pre>
</div>
</div>
<p id="basics-sort-value-key">Sorting also supports a <code>key</span></code> parameter that takes a callable function
to apply to the values being sorted.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell121"><span></span><span class="gp">In [316]: </span><span class="n">s1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">])</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell122"><span></span><span class="gp">In [317]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">()</span>
<span class="gh">Out[317]: </span>
<span class="go">0    B</span>
<span class="go">2    C</span>
<span class="go">1    a</span>
<span class="go">dtype: object</span>

<span class="gp">In [318]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">key</span><span class="o">=</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">())</span>
<span class="gh">Out[318]: </span>
<span class="go">1    a</span>
<span class="go">0    B</span>
<span class="go">2    C</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p><code>key</span></code> will be given the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</span></code></a> of values and should return a <code>Series</span></code>
or array of the same shape with the transformed values. For <code>DataFrame</span></code> objects,
the key is applied per column, so the key should still expect a Series and return
a Series, e.g.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell123"><span></span><span class="gp">In [319]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]})</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell124"><span></span><span class="gp">In [320]: </span><span class="n">df</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[320]: </span>
<span class="go">   a  b</span>
<span class="go">0  B  1</span>
<span class="go">2  C  3</span>
<span class="go">1  a  2</span>

<span class="gp">In [321]: </span><span class="n">df</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="s2">"a"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="k">lambda</span> <span class="n">col</span><span class="p">:</span> <span class="n">col</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">())</span>
<span class="gh">Out[321]: </span>
<span class="go">   a  b</span>
<span class="go">1  a  2</span>
<span class="go">0  B  1</span>
<span class="go">2  C  3</span>
</pre>
</div>
</div>
<p>The name or type of each column can be used to apply different functions to
different columns.</p>
</section>
<section id="by-indexes-and-values">
<span id="basics-sort-indexes-and-values"></span><h3>By indexes and values<a class="headerlink" href="#by-indexes-and-values" title="Link to this heading">#</a></h3>
<p>Strings passed as the <code>by</span></code> parameter to <a href="../reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</span></code></a> may
refer to either columns or index level names.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell125"><span></span><span class="go"># Build MultiIndex</span>
<span class="gp">In [322]: </span><span class="n">idx</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_tuples</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[(</span><span class="s2">"a"</span><span class="p">,</span> <span class="mi">1</span><span class="p">),</span> <span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="mi">1</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="mi">1</span><span class="p">)]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [323]: </span><span class="n">idx</span><span class="o">.</span><span class="n">names</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"first"</span><span class="p">,</span> <span class="s2">"second"</span><span class="p">]</span>

<span class="go"># Build DataFrame</span>
<span class="gp">In [324]: </span><span class="n">df_multi</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">6</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">)},</span> <span class="n">index</span><span class="o">=</span><span class="n">idx</span><span class="p">)</span>

<span class="gp">In [325]: </span><span class="n">df_multi</span>
<span class="gh">Out[325]: </span>
<span class="go">              A</span>
<span class="go">first second   </span>
<span class="go">a     1       6</span>
<span class="go">      2       5</span>
<span class="go">      2       4</span>
<span class="go">b     2       3</span>
<span class="go">      1       2</span>
<span class="go">      1       1</span>
</pre>
</div>
</div>
<p>Sort by ‘second’ (index) and ‘A’ (column)</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell126"><span></span><span class="gp">In [326]: </span><span class="n">df_multi</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="p">[</span><span class="s2">"second"</span><span class="p">,</span> <span class="s2">"A"</span><span class="p">])</span>
<span class="gh">Out[326]: </span>
<span class="go">              A</span>
<span class="go">first second   </span>
<span class="go">b     1       1</span>
<span class="go">      1       2</span>
<span class="go">a     1       6</span>
<span class="go">b     2       3</span>
<span class="go">a     2       4</span>
<span class="go">      2       5</span>
</pre>
</div>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If a string matches both a column name and an index level name then a
warning is issued and the column takes precedence. This will result in an
ambiguity error in a future version.</p>
</div>
</section>
<section id="searchsorted">
<span id="basics-searchsorted"></span><h3>searchsorted<a class="headerlink" href="#searchsorted" title="Link to this heading">#</a></h3>
<p>Series has the <a href="../reference/api/pandas.Series.searchsorted.html#pandas.Series.searchsorted" title="pandas.Series.searchsorted"><code>searchsorted()</span></code></a> method, which works similarly to
<a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.searchsorted.html#numpy.ndarray.searchsorted" title="(in NumPy v2.3)"><code>numpy.ndarray.searchsorted()</span></code></a>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell127"><span></span><span class="gp">In [327]: </span><span class="n">ser</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>

<span class="gp">In [328]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>
<span class="gh">Out[328]: </span><span class="go">array([0, 2])</span>

<span class="gp">In [329]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">4</span><span class="p">])</span>
<span class="gh">Out[329]: </span><span class="go">array([0, 3])</span>

<span class="gp">In [330]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="n">side</span><span class="o">=</span><span class="s2">"right"</span><span class="p">)</span>
<span class="gh">Out[330]: </span><span class="go">array([1, 3])</span>

<span class="gp">In [331]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="n">side</span><span class="o">=</span><span class="s2">"left"</span><span class="p">)</span>
<span class="gh">Out[331]: </span><span class="go">array([0, 2])</span>

<span class="gp">In [332]: </span><span class="n">ser</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">3</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">])</span>

<span class="gp">In [333]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="n">sorter</span><span class="o">=</span><span class="n">np</span><span class="o">.</span><span class="n">argsort</span><span class="p">(</span><span class="n">ser</span><span class="p">))</span>
<span class="gh">Out[333]: </span><span class="go">array([0, 2])</span>
</pre>
</div>
</div>
</section>
<section id="smallest-largest-values">
<span id="basics-nsorted"></span><h3>smallest / largest values<a class="headerlink" href="#smallest-largest-values" title="Link to this heading">#</a></h3>
<p><code>Series</span></code> has the <a href="../reference/api/pandas.Series.nsmallest.html#pandas.Series.nsmallest" title="pandas.Series.nsmallest"><code>nsmallest()</span></code></a> and <a href="../reference/api/pandas.Series.nlargest.html#pandas.Series.nlargest" title="pandas.Series.nlargest"><code>nlargest()</span></code></a> methods which return the
smallest or largest <span class="math notranslate nohighlight"><mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" tabindex="0" ctxtmenu_counter="0" style="font-size: 118.8%; position: relative;"><mjx-math class="MJX-TEX" aria-hidden="true"><mjx-mi class="mjx-i"><mjx-c class="mjx-c1D45B TEX-I"></mjx-c></mjx-mi></mjx-math><mjx-assistive-mml unselectable="on" display="inline"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>n</mi></math></mjx-assistive-mml></mjx-container></span> values. For a large <code>Series</span></code> this can be much
faster than sorting the entire Series and calling <code>head(n)</span></code> on the result.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell128"><span></span><span class="gp">In [334]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">permutation</span><span class="p">(</span><span class="mi">10</span><span class="p">))</span>

<span class="gp">In [335]: </span><span class="n">s</span>
<span class="gh">Out[335]: </span>
<span class="go">0    2</span>
<span class="go">1    0</span>
<span class="go">2    3</span>
<span class="go">3    7</span>
<span class="go">4    1</span>
<span class="go">5    5</span>
<span class="go">6    9</span>
<span class="go">7    6</span>
<span class="go">8    8</span>
<span class="go">9    4</span>
<span class="go">dtype: int64</span>

<span class="gp">In [336]: </span><span class="n">s</span><span class="o">.</span><span class="n">sort_values</span><span class="p">()</span>
<span class="gh">Out[336]: </span>
<span class="go">1    0</span>
<span class="go">4    1</span>
<span class="go">0    2</span>
<span class="go">2    3</span>
<span class="go">9    4</span>
<span class="go">5    5</span>
<span class="go">7    6</span>
<span class="go">3    7</span>
<span class="go">8    8</span>
<span class="go">6    9</span>
<span class="go">dtype: int64</span>

<span class="gp">In [337]: </span><span class="n">s</span><span class="o">.</span><span class="n">nsmallest</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
<span class="gh">Out[337]: </span>
<span class="go">1    0</span>
<span class="go">4    1</span>
<span class="go">0    2</span>
<span class="go">dtype: int64</span>

<span class="gp">In [338]: </span><span class="n">s</span><span class="o">.</span><span class="n">nlargest</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
<span class="gh">Out[338]: </span>
<span class="go">6    9</span>
<span class="go">8    8</span>
<span class="go">3    7</span>
<span class="go">dtype: int64</span>
</pre>
</div>
</div>
<p><code>DataFrame</span></code> also has the <code>nlargest</span></code> and <code>nsmallest</span></code> methods.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell129"><span></span><span class="gp">In [339]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="o">-</span><span class="mi">2</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"b"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"abdceff"</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">4.0</span><span class="p">,</span> <span class="mf">3.2</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="mf">4.0</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="p">}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [340]: </span><span class="n">df</span><span class="o">.</span><span class="n">nlargest</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[340]: </span>
<span class="go">    a  b    c</span>
<span class="go">5  11  f  3.0</span>
<span class="go">3  10  c  3.2</span>
<span class="go">4   8  e  NaN</span>

<span class="gp">In [341]: </span><span class="n">df</span><span class="o">.</span><span class="n">nlargest</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">])</span>
<span class="gh">Out[341]: </span>
<span class="go">    a  b    c</span>
<span class="go">5  11  f  3.0</span>
<span class="go">3  10  c  3.2</span>
<span class="go">4   8  e  NaN</span>
<span class="go">2   1  d  4.0</span>
<span class="go">6  -1  f  4.0</span>

<span class="gp">In [342]: </span><span class="n">df</span><span class="o">.</span><span class="n">nsmallest</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[342]: </span>
<span class="go">   a  b    c</span>
<span class="go">0 -2  a  1.0</span>
<span class="go">1 -1  b  2.0</span>
<span class="go">6 -1  f  4.0</span>

<span class="gp">In [343]: </span><span class="n">df</span><span class="o">.</span><span class="n">nsmallest</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">])</span>
<span class="gh">Out[343]: </span>
<span class="go">   a  b    c</span>
<span class="go">0 -2  a  1.0</span>
<span class="go">1 -1  b  2.0</span>
<span class="go">6 -1  f  4.0</span>
<span class="go">2  1  d  4.0</span>
<span class="go">4  8  e  NaN</span>
</pre>
</div>
</div>
</section>
<section id="sorting-by-a-multiindex-column">
<span id="basics-multiindex-sorting"></span><h3>Sorting by a MultiIndex column<a class="headerlink" href="#sorting-by-a-multiindex-column" title="Link to this heading">#</a></h3>
<p>You must be explicit about sorting when the column is a MultiIndex, and fully specify
all levels to <code>by</span></code>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell130"><span></span><span class="gp">In [344]: </span><span class="n">df1</span><span class="o">.</span><span class="n">columns</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_tuples</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="s2">"three"</span><span class="p">)]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [345]: </span><span class="n">df1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">))</span>
<span class="gh">Out[345]: </span>
<span class="go">    a         b</span>
<span class="go">  one two three</span>
<span class="go">0   2   1     5</span>
<span class="go">2   1   2     3</span>
<span class="go">1   1   3     4</span>
<span class="go">3   1   4     2</span>
</pre>
</div>
</div>

# <h2>Copying</h2>

<p>The <a href="../reference/api/pandas.DataFrame.copy.html#pandas.DataFrame.copy" title="pandas.DataFrame.copy"><code>copy()</span></code></a> method on pandas objects copies the underlying data (though not
the axis indexes, since they are immutable) and returns a new object. Note that
<strong>it is seldom necessary to copy objects</strong>. For example, there are only a
handful of ways to alter a DataFrame <em>in-place</em>:</p>
<ul>
<li><p>Inserting, deleting, or modifying a column.</p></li>
<li><p>Assigning to the <code>index</span></code> or <code>columns</span></code> attributes.</p></li>
<li><p>For homogeneous data, directly modifying the values via the <code>values</span></code>
attribute or advanced indexing.</p></li>
</ul>
<p>To be clear, no pandas method has the side effect of modifying your data;
almost every method returns a new object, leaving the original object
untouched. If the data is modified, it is because you did so explicitly.</p>

# <h2>dtypes</h2>

<p>For the most part, pandas uses NumPy arrays and dtypes for Series or individual columns of a DataFrame. NumPy provides support for <code>float</span></code>, <code>int</span></code>, <code>bool</span></code>, <code>timedelta64[ns]</span></code> and <code>datetime64[ns]</span></code> (note that NumPy does not support timezone-aware datetimes).</p>

<p>pandas and third-party libraries <em>extend</em> NumPy’s type system in a few places.
This section describes the extensions pandas has made internally.
See <a href="https://pandas.pydata.org/docs/development/extending.html#extending-extension-types">Extension types</span></a> for how to write your own extension that works with pandas. See <a href="https://pandas.pydata.org/community/ecosystem.html">the ecosystem page</a> for a list of third-party libraries that have implemented an extension.</p>
<p>The following table lists all of pandas extension types.
For methods requiring <code>dtype</span></code> arguments, strings can be specified as indicated. See the respective
documentation sections for more on each type.</p>

<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>Kind of Data</p></th>
<th class="head" colspan="2"><p>Data Type</p></th>
<th class="head" colspan="2"><p>Scalar</p></th>
<th class="head"><p>Array</p></th>
<th class="head"><p>String Aliases</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><a href="timeseries.html#timeseries-timezone">tz-aware datetime</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.DatetimeTZDtype.html#pandas.DatetimeTZDtype" title="pandas.DatetimeTZDtype"><code>DatetimeTZDtype</span></code></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Timestamp.html#pandas.Timestamp" title="pandas.Timestamp"><code>Timestamp</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.DatetimeArray.html#pandas.arrays.DatetimeArray" title="pandas.arrays.DatetimeArray"><code>arrays.DatetimeArray</span></code></a></p></td>
<td><p><code>'datetime64[ns,</span> &lt;tz&gt;]'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="categorical.html#categorical">Categorical</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.CategoricalDtype.html#pandas.CategoricalDtype" title="pandas.CategoricalDtype"><code>CategoricalDtype</span></code></a></p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.Categorical.html#pandas.Categorical" title="pandas.Categorical"><code>Categorical</span></code></a></p></td>
<td><p><code>'category'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="timeseries.html#timeseries-periods">period (time spans)</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.PeriodDtype.html#pandas.PeriodDtype" title="pandas.PeriodDtype"><code>PeriodDtype</span></code></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Period.html#pandas.Period" title="pandas.Period"><code>Period</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.PeriodArray.html#pandas.arrays.PeriodArray" title="pandas.arrays.PeriodArray"><code>arrays.PeriodArray</span></code></a>
<code>'Period[&lt;freq&gt;]'</span></code></p></td>
<td><p><code>'period[&lt;freq&gt;]'</span></code>,</p></td>
</tr>
<tr class="row-odd"><td><p><a href="sparse.html#sparse">sparse</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.SparseDtype.html#pandas.SparseDtype" title="pandas.SparseDtype"><code>SparseDtype</span></code></a></p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.arrays.SparseArray.html#pandas.arrays.SparseArray" title="pandas.arrays.SparseArray"><code>arrays.SparseArray</span></code></a></p></td>
<td><p><code>'Sparse'</span></code>, <code>'Sparse[int]'</span></code>,
<code>'Sparse[float]'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="advanced.html#advanced-intervalindex">intervals</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.IntervalDtype.html#pandas.IntervalDtype" title="pandas.IntervalDtype"><code>IntervalDtype</span></code></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Interval.html#pandas.Interval" title="pandas.Interval"><code>Interval</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.IntervalArray.html#pandas.arrays.IntervalArray" title="pandas.arrays.IntervalArray"><code>arrays.IntervalArray</span></code></a></p></td>
<td><p><code>'interval'</span></code>, <code>'Interval'</span></code>,
<code>'Interval[&lt;numpy_dtype&gt;]'</span></code>,
<code>'Interval[datetime64[ns,</span> &lt;tz&gt;]]'</span></code>,
<code>'Interval[timedelta64[&lt;freq&gt;]]'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="integer_na.html#integer-na">nullable integer</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Int64Dtype.html#pandas.Int64Dtype" title="pandas.Int64Dtype"><code>Int64Dtype</span></code></a>, …</p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.arrays.IntegerArray.html#pandas.arrays.IntegerArray" title="pandas.arrays.IntegerArray"><code>arrays.IntegerArray</span></code></a></p></td>
<td><p><code>'Int8'</span></code>, <code>'Int16'</span></code>, <code>'Int32'</span></code>,
<code>'Int64'</span></code>, <code>'UInt8'</span></code>, <code>'UInt16'</span></code>,
<code>'UInt32'</span></code>, <code>'UInt64'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="../reference/arrays.html#api-arrays-float-na">nullable float</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Float64Dtype.html#pandas.Float64Dtype" title="pandas.Float64Dtype"><code>Float64Dtype</span></code></a>, …</p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.arrays.FloatingArray.html#pandas.arrays.FloatingArray" title="pandas.arrays.FloatingArray"><code>arrays.FloatingArray</span></code></a></p></td>
<td><p><code>'Float32'</span></code>, <code>'Float64'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="text.html#text">Strings</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a></p></td>
<td colspan="2"><p><a href="https://docs.python.org/3/library/stdtypes.html#str" title="(in Python v3.13)"><code>str</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.StringArray.html#pandas.arrays.StringArray" title="pandas.arrays.StringArray"><code>arrays.StringArray</span></code></a></p></td>
<td><p><code>'string'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="../reference/arrays.html#api-arrays-bool">Boolean (with NA)</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.BooleanDtype.html#pandas.BooleanDtype" title="pandas.BooleanDtype"><code>BooleanDtype</span></code></a></p></td>
<td colspan="2"><p><a href="https://docs.python.org/3/library/functions.html#bool" title="(in Python v3.13)"><code>bool</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.BooleanArray.html#pandas.arrays.BooleanArray" title="pandas.arrays.BooleanArray"><code>arrays.BooleanArray</span></code></a></p></td>
<td><p><code>'boolean'</span></code></p></td>
</tr>
</tbody>
</table>
<p>pandas has two ways to store strings.</p>
<ol>
<li><p><code>object</span></code> dtype, which can hold any Python object, including strings.</p></li>
<li><p><a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a>, which is dedicated to strings.</p></li>
</ol>

<p>Generally, we recommend using <a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a>. See <a href="text.html#text-types">Text data types</span></a> for more.</p>
<p>Finally, arbitrary objects may be stored using the <code>object</span></code> dtype, but should be avoided to the extent possible (for performance and interoperability with other libraries and methods.
See <a href="#basics-object-conversion">object conversion</span></a>).</p>

<p>A convenient <a href="../reference/api/pandas.DataFrame.dtypes.html#pandas.DataFrame.dtypes" title="pandas.DataFrame.dtypes"><code>dtypes</span></code></a> attribute for DataFrame returns a Series with the data type of each column.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell131"><span></span><span class="gp">In [346]: </span><span class="n">dft</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">rand</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"B"</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span>
<span class="gp">   .....: </span>        <span class="s2">"C"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span>
<span class="gp">   .....: </span>        <span class="s2">"D"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timestamp</span><span class="p">(</span><span class="s2">"20010102"</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"E"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mf">1.0</span><span class="p">]</span> <span class="o">*</span> <span class="mi">3</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"float32"</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"F"</span><span class="p">:</span> <span class="kc">False</span><span class="p">,</span>
<span class="gp">   .....: </span>        <span class="s2">"G"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">]</span> <span class="o">*</span> <span class="mi">3</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"int8"</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="p">}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [347]: </span><span class="n">dft</span>
<span class="gh">Out[347]: </span>
<span class="go">          A  B    C          D    E      F  G</span>
<span class="go">0  0.035962  1  foo 2001-01-02  1.0  False  1</span>
<span class="go">1  0.701379  1  foo 2001-01-02  1.0  False  1</span>
<span class="go">2  0.281885  1  foo 2001-01-02  1.0  False  1</span>

<span class="gp">In [348]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[348]: </span>
<span class="go">A          float64</span>
<span class="go">B            int64</span>
<span class="go">C           object</span>
<span class="go">D    datetime64[s]</span>
<span class="go">E          float32</span>
<span class="go">F             bool</span>
<span class="go">G             int8</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p>On a <code>Series</span></code> object, use the <a href="../reference/api/pandas.Series.dtype.html#pandas.Series.dtype" title="pandas.Series.dtype"><code>dtype</span></code></a> attribute.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell132"><span></span><span class="gp">In [349]: </span><span class="n">dft</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[349]: </span><span class="go">dtype('float64')</span>
</pre>
</div>
</div>

<p>If a pandas object contains data with multiple dtypes <em>in a single column</em>, the
dtype of the column will be chosen to accommodate all of the data types
(<code>object</span></code> is the most general).</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell133"><span></span><span class="go"># these ints are coerced to floats</span>
<span class="gp">In [350]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mf">6.0</span><span class="p">])</span>
<span class="gh">Out[350]: </span>
<span class="go">0    1.0</span>
<span class="go">1    2.0</span>
<span class="go">2    3.0</span>
<span class="go">3    4.0</span>
<span class="go">4    5.0</span>
<span class="go">5    6.0</span>
<span class="go">dtype: float64</span>

<span class="go"># string data forces an ``object`` dtype</span>
<span class="gp">In [351]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mf">6.0</span><span class="p">,</span> <span class="s2">"foo"</span><span class="p">])</span>
<span class="gh">Out[351]: </span>
<span class="go">0      1</span>
<span class="go">1      2</span>
<span class="go">2      3</span>
<span class="go">3    6.0</span>
<span class="go">4    foo</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p>The number of columns of each type in a <code>DataFrame</span></code> can be found by calling
<code>DataFrame.dtypes.value_counts()</span></code>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell134"><span></span><span class="gp">In [352]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span><span class="o">.</span><span class="n">value_counts</span><span class="p">()</span>
<span class="gh">Out[352]: </span>
<span class="go">float64          1</span>
<span class="go">int64            1</span>
<span class="go">object           1</span>
<span class="go">datetime64[s]    1</span>
<span class="go">float32          1</span>
<span class="go">bool             1</span>
<span class="go">int8             1</span>
<span class="go">Name: count, dtype: int64</span>
</pre>
</div>
</div>

<p>Numeric dtypes will propagate and can coexist in DataFrames.
If a dtype is passed (either directly via the <code>dtype</span></code> keyword, a passed <code>ndarray</span></code>,
or a passed <code>Series</span></code>), then it will be preserved in DataFrame operations. Furthermore,
different numeric dtypes will <strong>NOT</strong> be combined. The following example will give you a taste.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell135"><span></span><span class="gp">In [353]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">,</span> <span class="mi">1</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">],</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float32"</span><span class="p">)</span>

<span class="gp">In [354]: </span><span class="n">df1</span>
<span class="gh">Out[354]: </span>
<span class="go">          A</span>
<span class="go">0  0.224364</span>
<span class="go">1  1.890546</span>
<span class="go">2  0.182879</span>
<span class="go">3  0.787847</span>
<span class="go">4 -0.188449</span>
<span class="go">5  0.667715</span>
<span class="go">6 -0.011736</span>
<span class="go">7 -0.399073</span>

<span class="gp">In [355]: </span><span class="n">df1</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[355]: </span>
<span class="go">A    float32</span>
<span class="go">dtype: object</span>

<span class="gp">In [356]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">),</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float16"</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"B"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">)),</span>
<span class="gp">   .....: </span>        <span class="s2">"C"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randint</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">255</span><span class="p">,</span> <span class="n">size</span><span class="o">=</span><span class="mi">8</span><span class="p">),</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"uint8"</span><span class="p">),</span>  <span class="c1"># [0,255] (range of uint8)</span>
<span class="gp">   .....: </span>    <span class="p">}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [357]: </span><span class="n">df2</span>
<span class="gh">Out[357]: </span>
<span class="go">          A         B    C</span>
<span class="go">0  0.823242  0.256090   26</span>
<span class="go">1  1.607422  1.426469   86</span>
<span class="go">2 -0.333740 -0.416203   46</span>
<span class="go">3 -0.063477  1.139976  212</span>
<span class="go">4 -1.014648 -1.193477   26</span>
<span class="go">5  0.678711  0.096706    7</span>
<span class="go">6 -0.040863 -1.956850  184</span>
<span class="go">7 -0.357422 -0.714337  206</span>

<span class="gp">In [358]: </span><span class="n">df2</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[358]: </span>
<span class="go">A    float16</span>
<span class="go">B    float64</span>
<span class="go">C      uint8</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

## <h3>defaults</h3>

<p>By default integer types are <code>int64</span></code> and float types are <code>float64</span></code>, <em>regardless</em> of platform (32-bit or 64-bit).
The following will all result in <code>int64</span></code> dtypes.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell136"><span></span><span class="gp">In [359]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">])</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[359]: </span>
<span class="go">a    int64</span>
<span class="go">dtype: object</span>

<span class="gp">In [360]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]})</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[360]: </span>
<span class="go">a    int64</span>
<span class="go">dtype: object</span>

<span class="gp">In [361]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="mi">1</span><span class="p">},</span> <span class="n">index</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">2</span><span class="p">)))</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[361]: </span>
<span class="go">a    int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Note that Numpy will choose <em>platform-dependent</em> types when creating arrays.
The following <strong>WILL</strong> result in <code>int32</span></code> on 32-bit platform.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell137"><span></span><span class="gp">In [362]: </span><span class="n">frame</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]))</span>
</pre>
</div>
</div>
</section>
<section id="upcasting">

## <h3>upcasting</h3>

<p>Types can potentially be <em>upcasted</em> when combined with other types, meaning they are promoted
from the current type (e.g. <code>int</span></code> to <code>float</span></code>).</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell138"><span></span><span class="gp">In [363]: </span><span class="n">df3</span> <span class="o">=</span> <span class="n">df1</span><span class="o">.</span><span class="n">reindex_like</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span><span class="o">.</span><span class="n">fillna</span><span class="p">(</span><span class="n">value</span><span class="o">=</span><span class="mf">0.0</span><span class="p">)</span> <span class="o">+</span> <span class="n">df2</span>

<span class="gp">In [364]: </span><span class="n">df3</span>
<span class="gh">Out[364]: </span>
<span class="go">          A         B      C</span>
<span class="go">0  1.047606  0.256090   26.0</span>
<span class="go">1  3.497968  1.426469   86.0</span>
<span class="go">2 -0.150862 -0.416203   46.0</span>
<span class="go">3  0.724370  1.139976  212.0</span>
<span class="go">4 -1.203098 -1.193477   26.0</span>
<span class="go">5  1.346426  0.096706    7.0</span>
<span class="go">6 -0.052599 -1.956850  184.0</span>
<span class="go">7 -0.756495 -0.714337  206.0</span>

<span class="gp">In [365]: </span><span class="n">df3</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[365]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</span></code></a> will return the <em>lower-common-denominator</em> of the dtypes, meaning
the dtype that can accommodate <strong>ALL</strong> of the types in the resulting homogeneous dtyped NumPy array. This can
force some <em>upcasting</em>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell139"><span></span><span class="gp">In [366]: </span><span class="n">df3</span><span class="o">.</span><span class="n">to_numpy</span><span class="p">()</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[366]: </span><span class="go">dtype('float64')</span>
</pre>
</div>
</div>

## <h3>astype</h3>

<p id="basics-cast">You can use the <a href="../reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a> method to explicitly convert dtypes from one to another. These will by default return a copy,
even if the dtype was unchanged (pass <code>copy=False</span></code> to change this behavior). In addition, they will raise an
exception if the astype operation is invalid.</p>
<p>Upcasting is always according to the <strong>NumPy</strong> rules. If two different dtypes are involved in an operation,
then the more <em>general</em> one will be used as the result of the operation.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell140"><span></span><span class="gp">In [367]: </span><span class="n">df3</span>
<span class="gh">Out[367]: </span>
<span class="go">          A         B      C</span>
<span class="go">0  1.047606  0.256090   26.0</span>
<span class="go">1  3.497968  1.426469   86.0</span>
<span class="go">2 -0.150862 -0.416203   46.0</span>
<span class="go">3  0.724370  1.139976  212.0</span>
<span class="go">4 -1.203098 -1.193477   26.0</span>
<span class="go">5  1.346426  0.096706    7.0</span>
<span class="go">6 -0.052599 -1.956850  184.0</span>
<span class="go">7 -0.756495 -0.714337  206.0</span>

<span class="gp">In [368]: </span><span class="n">df3</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[368]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>

<span class="go"># conversion of dtypes</span>
<span class="gp">In [369]: </span><span class="n">df3</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"float32"</span><span class="p">)</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[369]: </span>
<span class="go">A    float32</span>
<span class="go">B    float32</span>
<span class="go">C    float32</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Convert a subset of columns to a specified type using <a href="../reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell141"><span></span><span class="gp">In [370]: </span><span class="n">dft</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">]})</span>

<span class="gp">In [371]: </span><span class="n">dft</span><span class="p">[[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span> <span class="o">=</span> <span class="n">dft</span><span class="p">[[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">uint8</span><span class="p">)</span>

<span class="gp">In [372]: </span><span class="n">dft</span>
<span class="gh">Out[372]: </span>
<span class="go">   a  b  c</span>
<span class="go">0  1  4  7</span>
<span class="go">1  2  5  8</span>
<span class="go">2  3  6  9</span>

<span class="gp">In [373]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[373]: </span>
<span class="go">a    uint8</span>
<span class="go">b    uint8</span>
<span class="go">c    int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Convert certain columns to a specific dtype by passing a dict to <a href="../reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell142"><span></span><span class="gp">In [374]: </span><span class="n">dft1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">]})</span>

<span class="gp">In [375]: </span><span class="n">dft1</span> <span class="o">=</span> <span class="n">dft1</span><span class="o">.</span><span class="n">astype</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">bool_</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">float64</span><span class="p">})</span>

<span class="gp">In [376]: </span><span class="n">dft1</span>
<span class="gh">Out[376]: </span>
<span class="go">       a  b    c</span>
<span class="go">0   True  4  7.0</span>
<span class="go">1  False  5  8.0</span>
<span class="go">2   True  6  9.0</span>

<span class="gp">In [377]: </span><span class="n">dft1</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[377]: </span>
<span class="go">a       bool</span>
<span class="go">b      int64</span>
<span class="go">c    float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>When trying to convert a subset of columns to a specified type using <a href="../reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a>  and <a href="../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc" title="pandas.DataFrame.loc"><code>loc()</span></code></a>, upcasting occurs.</p>
<p><a href="../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc" title="pandas.DataFrame.loc"><code>loc()</span></code></a> tries to fit in what we are assigning to the current dtypes, while <code>[]</span></code> will overwrite them taking the dtype from the right hand side. Therefore the following piece of code produces the unintended result.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell143"><span></span><span class="gp">In [378]: </span><span class="n">dft</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">]})</span>

<span class="gp">In [379]: </span><span class="n">dft</span><span class="o">.</span><span class="n">loc</span><span class="p">[:,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">uint8</span><span class="p">)</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[379]: </span>
<span class="go">a    uint8</span>
<span class="go">b    uint8</span>
<span class="go">dtype: object</span>

<span class="gp">In [380]: </span><span class="n">dft</span><span class="o">.</span><span class="n">loc</span><span class="p">[:,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span> <span class="o">=</span> <span class="n">dft</span><span class="o">.</span><span class="n">loc</span><span class="p">[:,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">uint8</span><span class="p">)</span>

<span class="gp">In [381]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[381]: </span>
<span class="go">a    int64</span>
<span class="go">b    int64</span>
<span class="go">c    int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
</div>

## <h3>object conversion</h3>

<p>pandas offers various functions to try to force conversion of types from the <code>object</span></code> dtype to other types.
In cases where the data is already of the correct type, but stored in an <code>object</span></code> array, the
<a href="../reference/api/pandas.DataFrame.infer_objects.html#pandas.DataFrame.infer_objects" title="pandas.DataFrame.infer_objects"><code>DataFrame.infer_objects()</span></code></a> and <a href="../reference/api/pandas.Series.infer_objects.html#pandas.Series.infer_objects" title="pandas.Series.infer_objects"><code>Series.infer_objects()</span></code></a> methods can be used to soft convert
to the correct type.</p>
<blockquote>
<div><div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell144"><span></span><span class="gp">In [382]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [383]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[</span>
<span class="gp">   .....: </span>        <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="p">[</span><span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)],</span>
<span class="gp">   .....: </span>    <span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [384]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">T</span>

<span class="gp">In [385]: </span><span class="n">df</span>
<span class="gh">Out[385]: </span>
<span class="go">   0  1                    2</span>
<span class="go">0  1  a  2016-03-02 00:00:00</span>
<span class="go">1  2  b  2016-03-02 00:00:00</span>

<span class="gp">In [386]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[386]: </span>
<span class="go">0    object</span>
<span class="go">1    object</span>
<span class="go">2    object</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
</div></blockquote>
<p>Because the data was transposed the original inference stored all columns as object, which
<code>infer_objects</span></code> will correct.</p>
<blockquote>
<div><div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell145"><span></span><span class="gp">In [387]: </span><span class="n">df</span><span class="o">.</span><span class="n">infer_objects</span><span class="p">()</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[387]: </span>
<span class="go">0             int64</span>
<span class="go">1            object</span>
<span class="go">2    datetime64[ns]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
</div></blockquote>
<p>The following functions are available for one dimensional object arrays or scalars to perform
hard conversion of objects to a specified type:</p>
<ul>
<li><p><a href="../reference/api/pandas.to_numeric.html#pandas.to_numeric" title="pandas.to_numeric"><code>to_numeric()</span></code></a> (conversion to numeric dtypes)</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell146"><span></span><span class="gp">In [388]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"1.1"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>

<span class="gp">In [389]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">)</span>
<span class="gh">Out[389]: </span><span class="go">array([1.1, 2. , 3. ])</span>
</pre>
</div>
</div>
</li>
<li><p><a href="../reference/api/pandas.to_datetime.html#pandas.to_datetime" title="pandas.to_datetime"><code>to_datetime()</span></code></a> (conversion to datetime objects)</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell147"><span></span><span class="gp">In [390]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [391]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"2016-07-09"</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)]</span>

<span class="gp">In [392]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">(</span><span class="n">m</span><span class="p">)</span>
<span class="gh">Out[392]: </span><span class="go">DatetimeIndex(['2016-07-09', '2016-03-02'], dtype='datetime64[ns]', freq=None)</span>
</pre>
</div>
</div>
</li>
<li><p><a href="../reference/api/pandas.to_timedelta.html#pandas.to_timedelta" title="pandas.to_timedelta"><code>to_timedelta()</span></code></a> (conversion to timedelta objects)</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell148"><span></span><span class="gp">In [393]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"5us"</span><span class="p">,</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"1day"</span><span class="p">)]</span>

<span class="gp">In [394]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_timedelta</span><span class="p">(</span><span class="n">m</span><span class="p">)</span>
<span class="gh">Out[394]: </span><span class="go">TimedeltaIndex(['0 days 00:00:00.000005', '1 days 00:00:00'], dtype='timedelta64[ns]', freq=None)</span>
</pre>
</div>
</div>
</li>
</ul>

<p>To force a conversion, we can pass in an <code>errors</span></code> argument, which specifies how pandas should deal with elements
that cannot be converted to desired dtype or object. By default, <code>errors='raise'</span></code>, meaning that any errors encountered
will be raised during the conversion process. However, if <code>errors='coerce'</span></code>, these errors will be ignored and pandas
will convert problematic elements to <code>pd.NaT</span></code> (for datetime and timedelta) or <code>np.nan</span></code> (for numeric). This might be
useful if you are reading in data which is mostly of the desired dtype (e.g. numeric, datetime), but occasionally has
non-conforming elements intermixed that you want to represent as missing:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell149"><span></span><span class="gp">In [395]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [396]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"apple"</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)]</span>

<span class="gp">In [397]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">errors</span><span class="o">=</span><span class="s2">"coerce"</span><span class="p">)</span>
<span class="gh">Out[397]: </span><span class="go">DatetimeIndex(['NaT', '2016-03-02'], dtype='datetime64[ns]', freq=None)</span>

<span class="gp">In [398]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"apple"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>

<span class="gp">In [399]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">errors</span><span class="o">=</span><span class="s2">"coerce"</span><span class="p">)</span>
<span class="gh">Out[399]: </span><span class="go">array([nan,  2.,  3.])</span>

<span class="gp">In [400]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"apple"</span><span class="p">,</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"1day"</span><span class="p">)]</span>

<span class="gp">In [401]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_timedelta</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">errors</span><span class="o">=</span><span class="s2">"coerce"</span><span class="p">)</span>
<span class="gh">Out[401]: </span><span class="go">TimedeltaIndex([NaT, '1 days'], dtype='timedelta64[ns]', freq=None)</span>
</pre>
</div>
</div>
<p>In addition to object conversion, <a href="../reference/api/pandas.to_numeric.html#pandas.to_numeric" title="pandas.to_numeric"><code>to_numeric()</span></code></a> provides another argument <code>downcast</span></code>, which gives the
option of downcasting the newly (or already) numeric data to a smaller dtype, which can conserve memory:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell150"><span></span><span class="gp">In [402]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"1"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>

<span class="gp">In [403]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"integer"</span><span class="p">)</span>  <span class="c1"># smallest signed int dtype</span>
<span class="gh">Out[403]: </span><span class="go">array([1, 2, 3], dtype=int8)</span>

<span class="gp">In [404]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"signed"</span><span class="p">)</span>  <span class="c1"># same as 'integer'</span>
<span class="gh">Out[404]: </span><span class="go">array([1, 2, 3], dtype=int8)</span>

<span class="gp">In [405]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"unsigned"</span><span class="p">)</span>  <span class="c1"># smallest unsigned int dtype</span>
<span class="gh">Out[405]: </span><span class="go">array([1, 2, 3], dtype=uint8)</span>

<span class="gp">In [406]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"float"</span><span class="p">)</span>  <span class="c1"># smallest float dtype</span>
<span class="gh">Out[406]: </span><span class="go">array([1., 2., 3.], dtype=float32)</span>
</pre>
</div>
</div>
<p>As these methods apply only to one-dimensional arrays, lists or scalars; they cannot be used directly on multi-dimensional objects such
as DataFrames. However, with <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a>, we can “apply” the function over each column efficiently:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell151"><span></span><span class="gp">In [407]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [408]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="s2">"2016-07-09"</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)]]</span> <span class="o">*</span> <span class="mi">2</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"O"</span><span class="p">)</span>

<span class="gp">In [409]: </span><span class="n">df</span>
<span class="gh">Out[409]: </span>
<span class="go">            0                    1</span>
<span class="go">0  2016-07-09  2016-03-02 00:00:00</span>
<span class="go">1  2016-07-09  2016-03-02 00:00:00</span>

<span class="gp">In [410]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">)</span>
<span class="gh">Out[410]: </span>
<span class="go">           0          1</span>
<span class="go">0 2016-07-09 2016-03-02</span>
<span class="go">1 2016-07-09 2016-03-02</span>

<span class="gp">In [411]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="s2">"1.1"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]]</span> <span class="o">*</span> <span class="mi">2</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"O"</span><span class="p">)</span>

<span class="gp">In [412]: </span><span class="n">df</span>
<span class="gh">Out[412]: </span>
<span class="go">     0  1  2</span>
<span class="go">0  1.1  2  3</span>
<span class="go">1  1.1  2  3</span>

<span class="gp">In [413]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">)</span>
<span class="gh">Out[413]: </span>
<span class="go">     0  1  2</span>
<span class="go">0  1.1  2  3</span>
<span class="go">1  1.1  2  3</span>

<span class="gp">In [414]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="s2">"5us"</span><span class="p">,</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"1day"</span><span class="p">)]]</span> <span class="o">*</span> <span class="mi">2</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"O"</span><span class="p">)</span>

<span class="gp">In [415]: </span><span class="n">df</span>
<span class="gh">Out[415]: </span>
<span class="go">     0                1</span>
<span class="go">0  5us  1 days 00:00:00</span>
<span class="go">1  5us  1 days 00:00:00</span>

<span class="gp">In [416]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">to_timedelta</span><span class="p">)</span>
<span class="gh">Out[416]: </span>
<span class="go">                       0      1</span>
<span class="go">0 0 days 00:00:00.000005 1 days</span>
<span class="go">1 0 days 00:00:00.000005 1 days</span>
</pre>
</div>
</div>

## <h3>gotchas</h3>
<p>Performing selection operations on <code>integer</span></code> type data can easily upcast the data to <code>floating</span></code>.
The dtype of the input data will be preserved in cases where <code>nans</span></code> are not introduced.
See also <a href="gotchas.html#gotchas-intna">Support for integer NA</span></a>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell152"><span></span><span class="gp">In [417]: </span><span class="n">dfi</span> <span class="o">=</span> <span class="n">df3</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"int32"</span><span class="p">)</span>

<span class="gp">In [418]: </span><span class="n">dfi</span><span class="p">[</span><span class="s2">"E"</span><span class="p">]</span> <span class="o">=</span> <span class="mi">1</span>

<span class="gp">In [419]: </span><span class="n">dfi</span>
<span class="gh">Out[419]: </span>
<span class="go">   A  B    C  E</span>
<span class="go">0  1  0   26  1</span>
<span class="go">1  3  1   86  1</span>
<span class="go">2  0  0   46  1</span>
<span class="go">3  0  1  212  1</span>
<span class="go">4 -1 -1   26  1</span>
<span class="go">5  1  0    7  1</span>
<span class="go">6  0 -1  184  1</span>
<span class="go">7  0  0  206  1</span>

<span class="gp">In [420]: </span><span class="n">dfi</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[420]: </span>
<span class="go">A    int32</span>
<span class="go">B    int32</span>
<span class="go">C    int32</span>
<span class="go">E    int64</span>
<span class="go">dtype: object</span>

<span class="gp">In [421]: </span><span class="n">casted</span> <span class="o">=</span> <span class="n">dfi</span><span class="p">[</span><span class="n">dfi</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">]</span>

<span class="gp">In [422]: </span><span class="n">casted</span>
<span class="gh">Out[422]: </span>
<span class="go">     A    B    C  E</span>
<span class="go">0  1.0  NaN   26  1</span>
<span class="go">1  3.0  1.0   86  1</span>
<span class="go">2  NaN  NaN   46  1</span>
<span class="go">3  NaN  1.0  212  1</span>
<span class="go">4  NaN  NaN   26  1</span>
<span class="go">5  1.0  NaN    7  1</span>
<span class="go">6  NaN  NaN  184  1</span>
<span class="go">7  NaN  NaN  206  1</span>

<span class="gp">In [423]: </span><span class="n">casted</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[423]: </span>
<span class="go">A    float64</span>
<span class="go">B    float64</span>
<span class="go">C      int32</span>
<span class="go">E      int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p>While float dtypes are unchanged.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell153"><span></span><span class="gp">In [424]: </span><span class="n">dfa</span> <span class="o">=</span> <span class="n">df3</span><span class="o">.</span><span class="n">copy</span><span class="p">()</span>

<span class="gp">In [425]: </span><span class="n">dfa</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span> <span class="o">=</span> <span class="n">dfa</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"float32"</span><span class="p">)</span>

<span class="gp">In [426]: </span><span class="n">dfa</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[426]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>

<span class="gp">In [427]: </span><span class="n">casted</span> <span class="o">=</span> <span class="n">dfa</span><span class="p">[</span><span class="n">df2</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">]</span>

<span class="gp">In [428]: </span><span class="n">casted</span>
<span class="gh">Out[428]: </span>
<span class="go">          A         B      C</span>
<span class="go">0  1.047606  0.256090   26.0</span>
<span class="go">1  3.497968  1.426469   86.0</span>
<span class="go">2       NaN       NaN   46.0</span>
<span class="go">3       NaN  1.139976  212.0</span>
<span class="go">4       NaN       NaN   26.0</span>
<span class="go">5  1.346426  0.096706    7.0</span>
<span class="go">6       NaN       NaN  184.0</span>
<span class="go">7       NaN       NaN  206.0</span>

<span class="gp">In [429]: </span><span class="n">casted</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[429]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

# <h2>Selecting columns based on <code>dtype</code></h2>

<p id="basics-selectdtypes">The <a href="../reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</span></code></a> method implements subsetting of columns
based on their <code>dtype</span></code>.</p>
<p>First, let’s create a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> with a slew of different
dtypes:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell154"><span></span><span class="gp">In [430]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"string"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"int64"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">4</span><span class="p">)),</span>
<span class="gp">   .....: </span>        <span class="s2">"uint8"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"u1"</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"float64"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mf">4.0</span><span class="p">,</span> <span class="mf">7.0</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"bool1"</span><span class="p">:</span> <span class="p">[</span><span class="kc">True</span><span class="p">,</span> <span class="kc">False</span><span class="p">,</span> <span class="kc">True</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"bool2"</span><span class="p">:</span> <span class="p">[</span><span class="kc">False</span><span class="p">,</span> <span class="kc">True</span><span class="p">,</span> <span class="kc">False</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"dates"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"now"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"category"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="s2">"ABC"</span><span class="p">))</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"category"</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="p">}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [431]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"tdeltas"</span><span class="p">]</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">dates</span><span class="o">.</span><span class="n">diff</span><span class="p">()</span>

<span class="gp">In [432]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"uint64"</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"u8"</span><span class="p">)</span>

<span class="gp">In [433]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"other_dates"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>

<span class="gp">In [434]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"tz_aware_dates"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">,</span> <span class="n">tz</span><span class="o">=</span><span class="s2">"US/Eastern"</span><span class="p">)</span>

<span class="gp">In [435]: </span><span class="n">df</span>
<span class="gh">Out[435]: </span>
<span class="go">  string  int64  uint8  ...  uint64  other_dates            tz_aware_dates</span>
<span class="go">0      a      1      3  ...       3   2013-01-01 2013-01-01 00:00:00-05:00</span>
<span class="go">1      b      2      4  ...       4   2013-01-02 2013-01-02 00:00:00-05:00</span>
<span class="go">2      c      3      5  ...       5   2013-01-03 2013-01-03 00:00:00-05:00</span>

<span class="go">[3 rows x 12 columns]</span>
</pre>
</div>
</div>
<p>And the dtypes:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell155"><span></span><span class="gp">In [436]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[436]: </span>
<span class="go">string                                object</span>
<span class="go">int64                                  int64</span>
<span class="go">uint8                                  uint8</span>
<span class="go">float64                              float64</span>
<span class="go">bool1                                   bool</span>
<span class="go">bool2                                   bool</span>
<span class="go">dates                         datetime64[ns]</span>
<span class="go">category                            category</span>
<span class="go">tdeltas                      timedelta64[ns]</span>
<span class="go">uint64                                uint64</span>
<span class="go">other_dates                   datetime64[ns]</span>
<span class="go">tz_aware_dates    datetime64[ns, US/Eastern]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p><a href="../reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</span></code></a> has two parameters <code>include</span></code> and <code>exclude</span></code> that allow you to
say “give me the columns <em>with</em> these dtypes” (<code>include</span></code>) and/or “give the
columns <em>without</em> these dtypes” (<code>exclude</span></code>).</p>
<p>For example, to select <code>bool</span></code> columns:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell156"><span></span><span class="gp">In [437]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="nb">bool</span><span class="p">])</span>
<span class="gh">Out[437]: </span>
<span class="go">   bool1  bool2</span>
<span class="go">0   True  False</span>
<span class="go">1  False   True</span>
<span class="go">2   True  False</span>
</pre>
</div>
</div>
<p>You can also pass the name of a dtype in the <a href="https://numpy.org/doc/stable/reference/arrays.scalars.html">NumPy dtype hierarchy</a>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell157"><span></span><span class="gp">In [438]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"bool"</span><span class="p">])</span>
<span class="gh">Out[438]: </span>
<span class="go">   bool1  bool2</span>
<span class="go">0   True  False</span>
<span class="go">1  False   True</span>
<span class="go">2   True  False</span>
</pre>
</div>
</div>
<p><a href="../reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</span></code></a> also works with generic dtypes as well.</p>
<p>For example, to select all numeric and boolean columns while excluding unsigned
integers:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell158"><span></span><span class="gp">In [439]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"number"</span><span class="p">,</span> <span class="s2">"bool"</span><span class="p">],</span> <span class="n">exclude</span><span class="o">=</span><span class="p">[</span><span class="s2">"unsignedinteger"</span><span class="p">])</span>
<span class="gh">Out[439]: </span>
<span class="go">   int64  float64  bool1  bool2 tdeltas</span>
<span class="go">0      1      4.0   True  False     NaT</span>
<span class="go">1      2      5.0  False   True  1 days</span>
<span class="go">2      3      6.0   True  False  1 days</span>
</pre>
</div>
</div>
<p>To select string columns you must use the <code>object</span></code> dtype:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell159"><span></span><span class="gp">In [440]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"object"</span><span class="p">])</span>
<span class="gh">Out[440]: </span>
<span class="go">  string</span>
<span class="go">0      a</span>
<span class="go">1      b</span>
<span class="go">2      c</span>
</pre>
</div>
</div>
<p>To see all the child dtypes of a generic <code>dtype</span></code> like <code>numpy.number</span></code> you
can define a function that returns a tree of child dtypes:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell160"><span></span><span class="gp">In [441]: </span><span class="k">def</span><span class="w"> </span><span class="nf">subdtypes</span><span class="p">(</span><span class="n">dtype</span><span class="p">):</span>
<span class="gp">   .....: </span>    <span class="n">subs</span> <span class="o">=</span> <span class="n">dtype</span><span class="o">.</span><span class="n">__subclasses__</span><span class="p">()</span>
<span class="gp">   .....: </span>    <span class="k">if</span> <span class="ow">not</span> <span class="n">subs</span><span class="p">:</span>
<span class="gp">   .....: </span>        <span class="k">return</span> <span class="n">dtype</span>
<span class="gp">   .....: </span>    <span class="k">return</span> <span class="p">[</span><span class="n">dtype</span><span class="p">,</span> <span class="p">[</span><span class="n">subdtypes</span><span class="p">(</span><span class="n">dt</span><span class="p">)</span> <span class="k">for</span> <span class="n">dt</span> <span class="ow">in</span> <span class="n">subs</span><span class="p">]]</span>
<span class="gp">   .....: </span>
</pre>
</div>
</div>
<p>All NumPy dtypes are subclasses of <code>numpy.generic</span></code>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell161"><span></span><span class="gp">In [442]: </span><span class="n">subdtypes</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">generic</span><span class="p">)</span>
<span class="gh">Out[442]: </span>
<span class="go">[numpy.generic,</span>
<span class="go"> [[numpy.number,</span>
<span class="go">   [[numpy.integer,</span>
<span class="go">     [[numpy.signedinteger,</span>
<span class="go">       [numpy.int8,</span>
<span class="go">        numpy.int16,</span>
<span class="go">        numpy.int32,</span>
<span class="go">        numpy.int64,</span>
<span class="go">        numpy.longlong,</span>
<span class="go">        numpy.timedelta64]],</span>
<span class="go">      [numpy.unsignedinteger,</span>
<span class="go">       [numpy.uint8,</span>
<span class="go">        numpy.uint16,</span>
<span class="go">        numpy.uint32,</span>
<span class="go">        numpy.uint64,</span>
<span class="go">        numpy.ulonglong]]]],</span>
<span class="go">    [numpy.inexact,</span>
<span class="go">     [[numpy.floating,</span>
<span class="go">       [numpy.float16, numpy.float32, numpy.float64, numpy.longdouble]],</span>
<span class="go">      [numpy.complexfloating,</span>
<span class="go">       [numpy.complex64, numpy.complex128, numpy.clongdouble]]]]]],</span>
<span class="go">  [numpy.flexible,</span>
<span class="go">   [[numpy.character, [numpy.bytes_, numpy.str_]],</span>
<span class="go">    [numpy.void, [numpy.record]]]],</span>
<span class="go">  numpy.bool_,</span>
<span class="go">  numpy.datetime64,</span>
<span class="go">  numpy.object_]]</span>
</pre>
</div>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>pandas also defines the types <code>category</span></code>, and <code>datetime64[ns,</span> tz]</span></code>, which are not integrated into the normal
NumPy hierarchy and won’t show up with the above function.</p>
</div>
</section>
</section>