<h1>Essential basic functionality</h1>

<p>Here we discuss a lot of the essential functionality common to the pandas data structures. To begin, let’s create some example objects like we did in the <a href="https://pandas.pydata.org/docs/user_guide/10min.html#min">10 minutes to pandas</a> section:</p>

In [8]:
import pandas as pd
import numpy as np

In [9]:
index = pd.date_range("1/1/2000", periods=8)

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

# <h2>Head and tail</h2>

<p>To view a small sample of a Series or DataFrame object, use the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html#pandas.DataFrame.head" title="pandas.DataFrame.head"><code>head()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail" title="pandas.DataFrame.tail"><code>tail()</code></a> methods. The default number of elements to display is five, but you may pass a custom number.</p>

In [10]:
long_series = pd.Series(np.random.randn(1000))

long_series.head()

0    1.541338
1   -0.720021
2   -0.920055
3   -0.496370
4   -0.778015
dtype: float64

In [11]:
long_series.tail(3)

997   -0.816181
998    0.161604
999   -1.664846
dtype: float64

# <h2>Attributes and underlying data</h2>

<p>pandas objects have a number of attributes enabling you to access the metadata</p>

<ul>

<li><p><strong>shape</strong>: gives the axis dimensions of the object, consistent with ndarray</p></li>

<li><dl>
<dt>Axis labels</dt><dd><ul>
<li><p><strong>Series</strong>: <em>index</em> (only axis)</p></li>
<li><p><strong>DataFrame</strong>: <em>index</em> (rows) and <em>columns</em></p></li></ul></dd>
</dl>
</li>

</ul>

<p>Note, <strong>these attributes can be safely assigned to</strong>!</p>

In [12]:
df[:2]

                   A         B         C
2000-01-01  0.016193  0.498954 -0.830927
2000-01-02 -0.433108 -2.152330  0.762996

In [13]:
df.columns = [x.lower() for x in df.columns]

In [14]:
df

                   a         b         c
2000-01-01  0.016193  0.498954 -0.830927
2000-01-02 -0.433108 -2.152330  0.762996
2000-01-03 -1.338013 -0.751896  0.020189
2000-01-04  1.111962  0.469293  0.101698
2000-01-05  1.053162  0.187691 -0.952068
2000-01-06 -0.798245 -0.700480  0.277246
2000-01-07  0.708292  0.887409  1.313241
2000-01-08 -1.166187  0.648396 -0.651875

<p>pandas objects (<a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>) can be thought of as containers for arrays, which hold the actual data and do the actual computation. For many types, the underlying array is a <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a>. However, pandas and 3rd party libraries may <em>extend</em>
NumPy’s type system to add support for custom arrays (see <a href="https://pandas.pydata.org/docs/user_guide/basics.htmlhttps://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</a>).</p>

<p>To get the actual data inside a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>, use the <code>.array</code> property</p>

In [15]:
s.array

<NumpyExtensionArray>
[  np.float64(0.3564627276588047), np.float64(-0.36404868522653394),
  np.float64(-1.9551788510704622),   np.float64(0.4094379655006229),
    np.float64(-1.32117467883223)]
Length: 5, dtype: float64

In [16]:
s.index.array

<NumpyExtensionArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.array.html#pandas.Series.array" title="pandas.Series.array"><code>array</code></a> will always be an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a>.
The exact details of what an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a> is and why pandas uses them are a bit beyond the scope of this introduction. See <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</a> for more.</p>
<p>If you know you need a NumPy array, use <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</code></a> or <code>numpy.asarray()</code>.</p>

In [17]:
s.to_numpy()

array([ 0.35646273, -0.36404869, -1.95517885,  0.40943797, -1.32117468])

In [18]:
np.asarray(s)

array([ 0.35646273, -0.36404869, -1.95517885,  0.40943797, -1.32117468])

<p>When the Series or Index is backed by an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</code></a> may involve copying data and coercing values.
See <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">dtypes</a> for more.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>to_numpy()</code></a> gives some control over the <code>dtype</code> of the resulting <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a>.
For example, consider datetimes with timezones.
NumPy doesn’t have a dtype to represent timezone-aware datetimes, so there are two possibly useful representations:</p>

<ol>
<li><p>An object-dtype <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a> with <a href="https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html#pandas.Timestamp" title="pandas.Timestamp"><code>Timestamp</code></a> objects, each
with the correct <code>tz</code></p></li>
<li><p>A <code>datetime64[ns]</code> -dtype <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray" title="(in NumPy v2.3)"><code>numpy.ndarray</code></a>, where the values have been converted to UTC and the timezone discarded</p></li>
</ol>

<p>Timezones may be preserved with <code>dtype=object</code></p>

In [19]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))

ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET')], dtype=object)

<p>Or thrown away with <code>dtype='datetime64[ns]'</code></p>

In [20]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

<p>Getting the “raw data” inside a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> is possibly a bit more complex. When your <code>DataFrame</code> only has a single data type for all the columns, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</code></a> will return the underlying data:</p>

In [21]:
df.to_numpy()

array([[ 0.01619258,  0.49895445, -0.83092668],
       [-0.43310822, -2.15233029,  0.76299645],
       [-1.33801319, -0.75189562,  0.02018892],
       [ 1.11196246,  0.46929299,  0.10169806],
       [ 1.05316246,  0.1876914 , -0.95206806],
       [-0.79824474, -0.70047992,  0.27724623],
       [ 0.70829203,  0.88740892,  1.31324078],
       [-1.16618667,  0.64839572, -0.651875  ]])

<p>If a DataFrame contains homogeneously-typed data, the ndarray can
actually be modified in-place, and the changes will be reflected in the data structure. For heterogeneous data (e.g. some of the DataFrame’s columns are not all the same dtype), this will not be the case. The values attribute itself, unlike the axis labels, cannot be assigned to.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>When working with heterogeneous data, the dtype of the resulting ndarray will be chosen to accommodate all of the data involved. For example, if strings are involved, the result will be of object dtype. If there are only floats and integers, the resulting array will be of float dtype.</p>
</div>

<p>In the past, pandas recommended <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html#pandas.Series.values" title="pandas.Series.values"><code>Series.values</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values" title="pandas.DataFrame.values"><code>DataFrame.values</code></a> for extracting the data from a Series or DataFrame. You’ll still find references to these in old code bases and online. Going forward, we recommend avoiding <code>.values</code> and using <code>.array</code> or <code>.to_numpy()</code>. <code>.values</code> has the following drawbacks:</p>

<ol>

<li><p>When your Series contains an <a href="https://pandas.pydata.org/docs/development/extending.html#extending-extension-types">extension type</a>, it’s
unclear whether <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html#pandas.Series.values" title="pandas.Series.values"><code>Series.values</code></a> returns a NumPy array or the extension array.
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.array.html#pandas.Series.array" title="pandas.Series.array"><code>Series.array</code></a> will always return an <a href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray" title="pandas.api.extensions.ExtensionArray"><code>ExtensionArray</code></a>, and will never copy data.
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy" title="pandas.Series.to_numpy"><code>Series.to_numpy()</code></a> will always return a NumPy array, potentially at the cost of copying / coercing values.</p></li>

<li><p>When your DataFrame contains a mixture of data types, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values" title="pandas.DataFrame.values"><code>DataFrame.values</code></a> may involve copying data and coercing values to a common dtype, a relatively expensive operation. <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</code></a>, being a method, makes it clearer that the returned NumPy array may not be a view on the same data in the DataFrame.</p></li>

</ol>

# <h2>Accelerated operations</h2>

<p>Pandas has support for accelerating certain types of binary numerical and boolean operations using the <code>numexpr</code> library and the <code>bottleneck</code> libraries.</p>

<p>These libraries are especially useful when dealing with large data sets, and provide large speedups. <code>numexpr</code> uses smart chunking, caching, and multiple cores. <code>bottleneck</code> is a set of specialized cython routines that are especially fast when dealing with arrays that have <code>nans</code>.</p>

<p>Here is a sample (using 100 column x 100,000 row <code>DataFrames</code>):</p>

<table class="table">
<colgroup>
<col style="width: 25.0%">
<col style="width: 25.0%">
<col style="width: 25.0%">
<col style="width: 25.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Operation</p></th>
<th class="head"><p>0.11.0 (ms)</p></th>
<th class="head"><p>Prior Version (ms)</p></th>
<th class="head"><p>Ratio to Prior</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code>df1 &gt; df2</code></p></td>
<td><p>13.32</p></td>
<td><p>125.35</p></td>
<td><p>0.1063</p></td>
</tr>
<tr class="row-odd"><td><p><code>df1 * df2</code></p></td>
<td><p>21.71</p></td>
<td><p>36.63</p></td>
<td><p>0.5928</p></td>
</tr>
<tr class="row-even"><td><p><code>df1 + df2</code></p></td>
<td><p>22.04</p></td>
<td><p>36.50</p></td>
<td><p>0.6039</p></td>
</tr>
</tbody>
</table>

<p>You are highly encouraged to install both libraries. See the section
<a href="https://pandas.pydata.org/docs/getting_started/install.html#install-recommended-dependencies">Recommended Dependencies</a> for more installation info.</p>

<p>These are both enabled to be used by default, you can control this by setting the options:</p>

In [22]:
pd.set_option("compute.use_bottleneck", False)
pd.set_option("compute.use_numexpr", False)

# <h2>Flexible binary operations</h2>

<p>With binary operations between pandas data structures, there are two key points of interest:</p>

<ul>
<li><p>Broadcasting behavior between higher- (e.g. DataFrame) and
lower-dimensional (e.g. Series) objects.</p></li>
<li><p>Missing data in computations.</p></li>
</ul>

<p>We will demonstrate how to manage these issues independently, though they can be handled simultaneously.</p>

## <h3>Matching / broadcasting behavior</h3>

<p>DataFrame has the methods <a href=".https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.add.html#pandas.DataFrame.add" title="pandas.DataFrame.add"><code>add()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sub.html#pandas.DataFrame.sub" title="pandas.DataFrame.sub"><code>sub()</code></a>,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mul.html#pandas.DataFrame.mul" title="pandas.DataFrame.mul"><code>mul()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.div.html#pandas.DataFrame.div" title="pandas.DataFrame.div"><code>div()</code></a> and related functions
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.radd.html#pandas.DataFrame.radd" title="pandas.DataFrame.radd"><code>radd()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rsub.html#pandas.DataFrame.rsub" title="pandas.DataFrame.rsub"><code>rsub()</code></a>, …
for carrying out binary operations. For broadcasting behavior,
Series input is of primary interest. Using these functions, you can use to either match on the <em>index</em> or <em>columns</em> via the <strong>axis</strong> keyword:</p>

In [23]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

In [24]:
df

        one       two     three
a -1.813796  1.088772       NaN
b -1.123272  2.038565 -0.447015
c  0.824326  0.823589  0.363256
d       NaN -0.377139  1.771935

In [25]:
row = df.iloc[1]

column = df["two"]

df.sub(row, axis="columns")

        one       two     three
a -0.690523 -0.949793       NaN
b  0.000000  0.000000  0.000000
c  1.947599 -1.214976  0.810271
d       NaN -2.415704  2.218950

In [26]:
df.sub(row, axis=1)

        one       two     three
a -0.690523 -0.949793       NaN
b  0.000000  0.000000  0.000000
c  1.947599 -1.214976  0.810271
d       NaN -2.415704  2.218950

In [27]:
df.sub(column, axis="index")

        one  two     three
a -2.902568  0.0       NaN
b -3.161837  0.0 -2.485580
c  0.000737  0.0 -0.460333
d       NaN  0.0  2.149075

In [28]:
df.sub(column, axis=0)

        one  two     three
a -2.902568  0.0       NaN
b -3.161837  0.0 -2.485580
c  0.000737  0.0 -0.460333
d       NaN  0.0  2.149075

<p>Furthermore you can align a level of a MultiIndexed DataFrame with a Series.</p>

In [29]:
dfmi = df.copy()

dfmi.index = pd.MultiIndex.from_tuples(
    [(1, "a"), (1, "b"), (1, "c"), (2, "a")], names=["first", "second"]
)

dfmi.sub(column, axis=0, level="second")

                   one       two     three
first second
1     a      -2.902568  0.000000       NaN
      b      -3.161837  0.000000 -2.485580
      c       0.000737  0.000000 -0.460333
2     a            NaN -1.465912  0.683163

<p>Series and Index also support the <a href="https://docs.python.org/3/library/functions.html#divmod" title="(in Python v3.13)"><code>divmod()</code></a> builtin. This function takes the floor division and modulo operation at the same time returning a two-tuple of the same type as the left hand side. For example:</p>

In [30]:
s = pd.Series(np.arange(10))

In [31]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [32]:
div, rem = divmod(s, 3)

In [33]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int64

In [34]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int64

In [35]:
idx = pd.Index(np.arange(10))

In [36]:
idx

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [37]:
div, rem = divmod(idx, 3)

In [38]:
div

Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64')

In [39]:
rem

Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64')

<p>We can also do elementwise <a href="https://docs.python.org/3/library/functions.html#divmod" title="(in Python v3.13)"><code>divmod()</code></a>:</p>

In [40]:
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [41]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64

In [42]:
rem

0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int64

## <h3>Missing data / operations with fill values</h3>

<p>In Series and DataFrame, the arithmetic functions have the option of inputting a <em>fill_value</em>, namely a value to substitute when at most one of the values at a location are missing. For example, when adding two DataFrame objects, you may wish to treat NaN as 0 unless both DataFrames are missing that value, in which case the result will be NaN (you can later replace NaN with some other value using <code>fillna</code> if you wish).</p>

In [43]:
df2 = df.copy()

df2.loc["a", "three"] = 1.0

In [44]:
df

        one       two     three
a -1.813796  1.088772       NaN
b -1.123272  2.038565 -0.447015
c  0.824326  0.823589  0.363256
d       NaN -0.377139  1.771935

In [45]:
df2

        one       two     three
a -1.813796  1.088772  1.000000
b -1.123272  2.038565 -0.447015
c  0.824326  0.823589  0.363256
d       NaN -0.377139  1.771935

In [46]:
df + df2

        one       two     three
a -3.627592  2.177544       NaN
b -2.246545  4.077129 -0.894030
c  1.648652  1.647178  0.726512
d       NaN -0.754279  3.543871

In [47]:
df.add(df2, fill_value=0)

        one       two     three
a -3.627592  2.177544  1.000000
b -2.246545  4.077129 -0.894030
c  1.648652  1.647178  0.726512
d       NaN -0.754279  3.543871

## <h3>Flexible comparisons</h3>

<p>Series and DataFrame have the binary comparison methods <code>eq</code>, <code>ne</code>, <code>lt</code>, <code>gt</code>, <code>le</code>, and <code>ge</code> whose behavior is analogous to the binary arithmetic operations described above:</p>

In [48]:
df.gt(df2)

     one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [49]:
df2.ne(df)

     one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

<p>These operations produce a pandas object of the same type as the left-hand-side input that is of dtype <code>bool</code>. These <code>boolean</code> objects can be used in indexing operations, see the section on <a href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-boolean">Boolean indexing</a>.</p>

## <h3>Boolean reductions</h3>

<p>You can apply the reductions: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.empty.html#pandas.DataFrame.empty" title="pandas.DataFrame.empty"><code>empty</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.any.html#pandas.DataFrame.any" title="pandas.DataFrame.any"><code>any()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html#pandas.DataFrame.all" title="pandas.DataFrame.all"><code>all()</code></a>, and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.bool.html#pandas.DataFrame.bool" title="pandas.DataFrame.bool"><code>bool()</code></a> to provide a way to summarize a boolean result.</p>

In [50]:
(df > 0).all()

one      False
two      False
three    False
dtype: bool

In [51]:
(df > 0).any()

one      True
two      True
three    True
dtype: bool

<p>You can reduce to a final boolean value.</p>

In [52]:
(df > 0).any().any()

np.True_

<p>You can test if a pandas object is empty, via the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.empty.html#pandas.DataFrame.empty" title="pandas.DataFrame.empty"><code>empty</code></a> property.</p>

In [53]:
df.empty

False

In [54]:
pd.DataFrame(columns=list("ABC")).empty

True

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Asserting the truthiness of a pandas object will raise an error, as the testing of the emptiness
or values is ambiguous.</p>

In [55]:
if df:
    print(True)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [56]:
df and df2

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

<p>See <a href="https://pandas.pydata.org/docs/user_guide/gotchas.html#gotchas-truth">gotchas</a> for a more detailed discussion.</p>

## <h3>Comparing if objects are equivalent</h3>

<p>Often you may find that there is more than one way to compute the same result.  As a simple example, consider <code>df + df</code> and <code>df * 2</code>. To test
that these two computations produce the same result, given the tools
shown above, you might imagine using <code>(df + df == df * 2).all()</code>. But in
fact, this expression is False:</p>

In [57]:
df + df == df * 2

     one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [58]:
(df + df == df * 2).all()

one      False
two       True
three    False
dtype: bool

<p>Notice that the boolean DataFrame <code>df + df == df * 2</code> contains some False values!
This is because NaNs do not compare as equals:</p>

In [59]:
np.nan == np.nan

False

<p>So, NDFrames (such as Series and DataFrames)
have an <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html#pandas.DataFrame.equals" title="pandas.DataFrame.equals"><code>equals()</code></a> method for testing equality, with NaNs in corresponding locations treated as equal.</p>

In [60]:
(df + df).equals(df * 2)

True

<p>Note that the Series or DataFrame index needs to be in the same order for equality to be True:</p>

In [61]:
df1 = pd.DataFrame({"col": ["foo", 0, np.nan]})

df2 = pd.DataFrame({"col": [np.nan, 0, "foo"]}, index=[2, 1, 0])

In [62]:
df1.equals(df2)

False

In [63]:
df1.equals(df2.sort_index())

True

## <h3>Comparing array-like objects</h3>

<p>You can conveniently perform element-wise comparisons when comparing a pandas data structure with a scalar value:</p>

In [64]:
pd.Series(["foo", "bar", "baz"]) == "foo"

0     True
1    False
2    False
dtype: bool

In [65]:
pd.Index(["foo", "bar", "baz"]) == "foo"

array([ True, False, False])

<p>pandas also handles element-wise comparisons between different array-like objects of the same length:</p>

In [66]:
pd.Series(["foo", "bar", "baz"]) == pd.Index(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

In [67]:
pd.Series(["foo", "bar", "baz"]) == np.array(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

<p>Trying to compare <code>Index</code> or <code>Series</code> objects of different lengths will raise a ValueError:</p>

In [68]:
pd.Series(['foo', 'bar', 'baz']) == pd.Series(['foo', 'bar'])

ValueError: Can only compare identically-labeled Series objects

## <h3>Combining overlapping data sets</h3>

<p>A problem occasionally arising is the combination of two similar data sets where values in one are preferred over the other. An example would be two data series representing a particular economic indicator where one is considered to be of “higher quality”.
However, the lower quality series might extend further back in history or have more complete data coverage. As such, we would like to combine two DataFrame objects where missing values in one DataFrame are conditionally filled with like-labeled values from the other DataFrame.
The function implementing this operation is <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</code></a>, which we illustrate:</p>

In [151]:
df1 = pd.DataFrame(
    {"A": [1.0, np.nan, 3.0, 5.0, np.nan], "B": [np.nan, 2.0, 3.0, np.nan, 6.0]}
)

In [69]:
df2 = pd.DataFrame(
    {
        "A": [5.0, 2.0, 4.0, np.nan, 3.0, 7.0],
        "B": [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0],
    }
)

In [70]:
df1

   col
0  foo
1    0
2  NaN

In [71]:
df2

     A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [72]:
df1.combine_first(df2)

     A    B  col
0  5.0  NaN  foo
1  2.0  NaN    0
2  4.0  3.0  NaN
3  NaN  4.0  NaN
4  3.0  6.0  NaN
5  7.0  8.0  NaN

## <h3>General DataFrame combine</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</code></a> method above calls the more general <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine.html#pandas.DataFrame.combine" title="pandas.DataFrame.combine"><code>DataFrame.combine()</code></a>.
This method takes another DataFrame and a combiner function, aligns the input DataFrame and then passes the combiner function pairs of Series (i.e., columns whose names are the same).</p>

<p>So, for instance, to reproduce <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>combine_first()</code></a> as above:</p>

In [73]:
def combiner(x, y):
  return np.where(pd.isna(x), y, x)

df1.combine(df2, combiner)

     A    B  col
0  5.0  NaN  foo
1  2.0  NaN    0
2  4.0  3.0  NaN
3  NaN  4.0  NaN
4  3.0  6.0  NaN
5  7.0  8.0  NaN

# <h2>Descriptive statistics</h2>

<p>There exists a large number of methods for computing descriptive statistics and other related operations on <a href="https://pandas.pydata.org/docs/reference/series.html#api-series-stats">Series</a>, <a href="https://pandas.pydata.org/docs/reference/frame.html#api-dataframe-stats">DataFrame</a>.
Most of these are aggregations (hence producing a lower-dimensional result) like <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html#pandas.DataFrame.sum" title="pandas.DataFrame.sum"><code>sum()</code></a>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html#pandas.DataFrame.mean" title="pandas.DataFrame.mean"><code>mean()</code></a>, and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html#pandas.DataFrame.quantile" title="pandas.DataFrame.quantile"><code>quantile()</code></a>, but some of them, like <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumsum.html#pandas.DataFrame.cumsum" title="pandas.DataFrame.cumsum"><code>cumsum()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumprod.html#pandas.DataFrame.cumprod" title="pandas.DataFrame.cumprod"><code>cumprod()</code></a>, produce an object of the same size.
Generally speaking, these methods take an <strong>axis</strong> argument, just like <em>ndarray.{sum, std, …}</em>, but the axis can be specified by name or integer:</p>

<ul>
<li><p><strong>Series</strong>: no axis argument needed</p></li>
<li><p><strong>DataFrame</strong>: “index” (axis=0, default), “columns” (axis=1)</p></li>
</ul>

<p>For example:</p>

In [74]:
df

        one       two     three
a -1.813796  1.088772       NaN
b -1.123272  2.038565 -0.447015
c  0.824326  0.823589  0.363256
d       NaN -0.377139  1.771935

In [75]:
df.mean(0)

one     -0.704247
two      0.893447
three    0.562725
dtype: float64

In [76]:
df.mean(1)

a   -0.362512
b    0.156092
c    0.670390
d    0.697398
dtype: float64

<p>All such methods have a <code>skipna</code> option signaling whether to exclude missing data (<code>True</code> by default):</p>

In [77]:
df.sum(0, skipna=False)

one           NaN
two      3.573786
three         NaN
dtype: float64

In [78]:
df.sum(axis=1, skipna=True)

a   -0.725024
b    0.468277
c    2.011171
d    1.394796
dtype: float64

<p>Combined with the broadcasting / arithmetic behavior, one can describe various statistical procedures, like standardization (rendering data zero mean and standard deviation of 1), very concisely:</p>

In [79]:
ts_stand = (df - df.mean()) / df.std()

ts_stand.std()

one      1.0
two      1.0
three    1.0
dtype: float64

In [80]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

<p>Note that methods like <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumsum.html#pandas.DataFrame.cumsum" title="pandas.DataFrame.cumsum"><code>cumsum()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumprod.html#pandas.DataFrame.cumprod" title="pandas.DataFrame.cumprod"><code>cumprod()</code></a> preserve the location of <code>NaN</code> values. This is somewhat different from <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.expanding.html#pandas.DataFrame.expanding" title="pandas.DataFrame.expanding"><code>expanding()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html#pandas.DataFrame.rolling" title="pandas.DataFrame.rolling"><code>rolling()</code></a> since <code>NaN</code> behavior is furthermore dictated by a <code>min_periods</code> parameter.</p>

In [81]:
df.cumsum()

        one       two     three
a -1.813796  1.088772       NaN
b -2.937068  3.127337 -0.447015
c -2.112742  3.950926 -0.083759
d       NaN  3.573786  1.688176

<p>Here is a quick reference summary table of common functions. Each also takes an optional <code>level</code> parameter which applies only if the object has a <a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-hierarchical">hierarchical index</a>.</p>

<table class="table">
<colgroup>
<col style="width: 20.0%">
<col style="width: 80.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Function</p></th>
<th class="head"><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code>count</code></p></td>
<td><p>Number of non-NA observations</p></td>
</tr>
<tr class="row-odd"><td><p><code>sum</code></p></td>
<td><p>Sum of values</p></td>
</tr>
<tr class="row-even"><td><p><code>mean</code></p></td>
<td><p>Mean of values</p></td>
</tr>
<tr class="row-odd"><td><p><code>median</code></p></td>
<td><p>Arithmetic median of values</p></td>
</tr>
<tr class="row-even"><td><p><code>min</code></p></td>
<td><p>Minimum</p></td>
</tr>
<tr class="row-odd"><td><p><code>max</code></p></td>
<td><p>Maximum</p></td>
</tr>
<tr class="row-even"><td><p><code>mode</code></p></td>
<td><p>Mode</p></td>
</tr>
<tr class="row-odd"><td><p><code>abs</code></p></td>
<td><p>Absolute Value</p></td>
</tr>
<tr class="row-even"><td><p><code>prod</code></p></td>
<td><p>Product of values</p></td>
</tr>
<tr class="row-odd"><td><p><code>std</code></p></td>
<td><p>Bessel-corrected sample standard deviation</p></td>
</tr>
<tr class="row-even"><td><p><code>var</code></p></td>
<td><p>Unbiased variance</p></td>
</tr>
<tr class="row-odd"><td><p><code>sem</code></p></td>
<td><p>Standard error of the mean</p></td>
</tr>
<tr class="row-even"><td><p><code>skew</code></p></td>
<td><p>Sample skewness (3rd moment)</p></td>
</tr>
<tr class="row-odd"><td><p><code>kurt</code></p></td>
<td><p>Sample kurtosis (4th moment)</p></td>
</tr>
<tr class="row-even"><td><p><code>quantile</code></p></td>
<td><p>Sample quantile (value at %)</p></td>
</tr>
<tr class="row-odd"><td><p><code>cumsum</code></p></td>
<td><p>Cumulative sum</p></td>
</tr>
<tr class="row-even"><td><p><code>cumprod</code></p></td>
<td><p>Cumulative product</p></td>
</tr>
<tr class="row-odd"><td><p><code>cummax</code></p></td>
<td><p>Cumulative maximum</p></td>
</tr>
<tr class="row-even"><td><p><code>cummin</code></p></td>
<td><p>Cumulative minimum</p></td>
</tr>
</tbody>
</table>

<p>Note that by chance some NumPy methods, like <code>mean</code>, <code>std</code>, and <code>sum</code>,
will exclude NAs on Series input by default:</p>

In [82]:
np.mean(df["one"])

np.float64(-0.7042474270880673)

In [83]:
np.mean(df["one"].to_numpy())

np.float64(nan)

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.nunique.html#pandas.Series.nunique" title="pandas.Series.nunique"><code>Series.nunique()</code></a> will return the number of unique non-NA values in a Series:</p>

In [84]:
series = pd.Series(np.random.randn(500))

series[20:500] = np.nan

series[10:20] = 5

series.nunique()

11

## <h3>Summarizing data: describe</h3>

<p>There is a convenient <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</code></a> function which computes a variety of summary statistics about a Series or the columns of a DataFrame (excluding NAs of course):</p>

In [85]:
series = pd.Series(np.random.randn(1000))

series[::2] = np.nan

series.describe()

count    500.000000
mean       0.000569
std        1.031596
min       -3.421431
25%       -0.717785
50%       -0.005073
75%        0.701095
max        3.176877
dtype: float64

In [86]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=["a", "b", "c", "d", "e"])

frame.iloc[::2] = np.nan

frame.describe()

                a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean     0.005543   -0.073726   -0.049729   -0.021767    0.056783
std      1.010794    1.029125    0.968514    0.986400    0.963190
min     -3.115853   -3.176122   -3.397938   -3.113628   -2.528166
25%     -0.620157   -0.763822   -0.707869   -0.694484   -0.563499
50%      0.018145   -0.069534   -0.047174   -0.014567    0.061567
75%      0.703414    0.688518    0.587643    0.632871    0.701050
max      3.113018    2.912918    3.092332    2.874571    2.860173

<p>You can select specific percentiles to include in the output:</p>

In [87]:
series.describe(percentiles=[0.05, 0.25, 0.75, 0.95])

count    500.000000
mean       0.000569
std        1.031596
min       -3.421431
5%        -1.622167
25%       -0.717785
50%       -0.005073
75%        0.701095
95%        1.585984
max        3.176877
dtype: float64

<p>By default, the median is always included.</p>
<p>For a non-numerical Series object, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.Series.describe"><code>describe()</code></a> will give a simple summary of the number of unique values and most frequently occurring values:</p>

In [88]:
s = pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])

s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

<p>Note that on a mixed-type DataFrame object, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe" title="pandas.DataFrame.describe"><code>describe()</code></a> will restrict the summary to include only numerical columns or, if none are, only categorical columns:</p>

In [89]:
frame = pd.DataFrame({"a": ["Yes", "Yes", "No", "No"], "b": range(4)})

frame.describe()

              b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

<p>This behavior can be controlled by providing a list of types as <code>include</code>/<code>exclude</code>
arguments. The special value <code>all</code> can also be used:</p>

In [90]:
frame.describe(include=["object"])

          a
count     4
unique    2
top     Yes
freq      2

In [91]:
frame.describe(include=["number"])

              b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [92]:
frame.describe(include="all")

          a         b
count     4  4.000000
unique    2       NaN
top     Yes       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

<p>That feature relies on <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes">select_dtypes</a>. Refer to there for details about accepted inputs.</p>

## <h3>Index of min/max values</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmin.html#pandas.DataFrame.idxmin" title="pandas.DataFrame.idxmin"><code>idxmin()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmax.html#pandas.DataFrame.idxmax" title="pandas.DataFrame.idxmax"><code>idxmax()</code></a> functions on Series and DataFrame compute the index labels with the minimum and maximum corresponding values:</p>

In [93]:
s1 = pd.Series(np.random.randn(5))

In [94]:
s1

0   -1.037355
1   -1.042799
2    0.880263
3    0.675078
4   -0.226213
dtype: float64

In [95]:
s1.idxmin(), s1.idxmax()

(1, 2)

In [96]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])

In [97]:
df1

          A         B         C
0  0.983925  1.026221 -0.097172
1 -1.175273 -0.384910  0.808923
2  0.505216  0.433006  1.192291
3  0.025696 -0.765824  0.236578
4  0.173526  0.971374 -0.470923

In [98]:
df1.idxmin(axis=0)

A    1
B    3
C    4
dtype: int64

In [99]:
df1.idxmin(axis=0)

A    1
B    3
C    4
dtype: int64

In [100]:
df1.idxmax(axis=1)

0    B
1    C
2    C
3    C
4    B
dtype: object

<p>When there are multiple rows (or columns) matching the minimum or maximum value, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmin.html#pandas.DataFrame.idxmin" title="pandas.DataFrame.idxmin"><code>idxmin()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmax.html#pandas.DataFrame.idxmax" title="pandas.DataFrame.idxmax"><code>idxmax()</code></a> return the first
matching index:</p>

In [101]:
df3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=["A"], index=list("edcba"))

In [102]:
df3

     A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [103]:
df3["A"].idxmin()

'd'

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>idxmin</code> and <code>idxmax</code> are called <code>argmin</code> and <code>argmax</code> in NumPy.</p>
</div>

## <h3>Value counts (histogramming) / mode</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts" title="pandas.Series.value_counts"><code>value_counts()</code></a> Series method computes a histogram of a 1D array of values. It can also be used as a function on regular arrays:</p>

In [104]:
data = np.random.randint(0, 7, size=50)

In [105]:
data

array([5, 0, 1, 1, 5, 5, 1, 0, 2, 4, 2, 3, 0, 2, 1, 2, 5, 2, 0, 6, 4, 6,
       5, 6, 3, 6, 1, 3, 4, 6, 2, 3, 5, 0, 4, 1, 0, 3, 0, 1, 2, 3, 3, 2,
       6, 2, 5, 5, 3, 2])

In [106]:
s = pd.Series(data)

In [107]:
s.value_counts()

2    10
3     8
5     8
1     7
0     7
6     6
4     4
Name: count, dtype: int64

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts" title="pandas.DataFrame.value_counts"><code>value_counts()</code></a> method can be used to count combinations across multiple columns.
By default all columns are used but a subset can be selected using the <code>subset</code> argument.</p>

In [108]:
data = {"a": [1, 2, 3, 4], "b": ["x", "x", "y", "y"]}

frame = pd.DataFrame(data)

In [109]:
frame.value_counts()

a  b
1  x    1
2  x    1
3  y    1
4  y    1
Name: count, dtype: int64

<p>Similarly, you can get the most frequently occurring value(s), i.e. the mode, of the values in a Series or DataFrame:</p>

In [110]:
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7])

s5.mode()

0    3
1    7
dtype: int64

In [111]:
df5 = pd.DataFrame(
       {
           "A": np.random.randint(0, 7, size=50),
           "B": np.random.randint(-10, 15, size=50),
       }
   )

df5.mode()

     A  B
0  1.0 -7
1  NaN  0
2  NaN  4

## <h3>Discretization and quantiling</h3>

<p>Continuous values can be discretized using the <a href="https://pandas.pydata.org/docs/reference/api/pandas.cut.html#pandas.cut" title="pandas.cut"><code>cut()</code></a> (bins based on values) and <a href="https://pandas.pydata.org/docs/reference/api/pandas.qcut.html#pandas.qcut" title="pandas.qcut"><code>qcut()</code></a> (bins based on sample quantiles) functions:</p>

In [112]:
arr = np.random.randn(20)

factor = pd.cut(arr, 4)

In [113]:
factor

[(-1.161, -0.144], (0.868, 1.881], (-0.144, 0.868], (-0.144, 0.868], (-1.161, -0.144], ..., (0.868, 1.881], (1.881, 2.894], (-1.161, -0.144], (-0.144, 0.868], (-0.144, 0.868]]
Length: 20
Categories (4, interval[float64, right]): [(-1.161, -0.144] < (-0.144, 0.868] < (0.868, 1.881] <
                                           (1.881, 2.894]]

In [114]:
factor = pd.cut(arr, [-5, -1, 0, 1, 5])

In [115]:
factor

[(-1, 0], (1, 5], (0, 1], (0, 1], (-1, 0], ..., (0, 1], (1, 5], (-1, 0], (0, 1], (0, 1]]
Length: 20
Categories (4, interval[int64, right]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.qcut.html#pandas.qcut" title="pandas.qcut"><code>qcut()</code></a> computes sample quantiles. For example, we could slice up some normally distributed data into equal-size quartiles like so:</p>

In [116]:
arr = np.random.randn(30)

factor = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])

In [117]:
factor

[(-0.407, 0.0522], (-1.6569999999999998, -0.407], (0.0522, 0.503], (0.0522, 0.503], (0.0522, 0.503], ..., (0.503, 2.087], (-1.6569999999999998, -0.407], (0.0522, 0.503], (0.503, 2.087], (-0.407, 0.0522]]
Length: 30
Categories (4, interval[float64, right]): [(-1.6569999999999998, -0.407] < (-0.407, 0.0522] < (0.0522, 0.503] <
                                           (0.503, 2.087]]

<p>We can also pass infinite values to define the bins:</p>

In [118]:
arr = np.random.randn(20)

factor = pd.cut(arr, [-np.inf, 0, np.inf])

In [119]:
factor

[(-inf, 0.0], (0.0, inf], (-inf, 0.0], (0.0, inf], (0.0, inf], ..., (0.0, inf], (0.0, inf], (0.0, inf], (-inf, 0.0], (0.0, inf]]
Length: 20
Categories (2, interval[float64, right]): [(-inf, 0.0] < (0.0, inf]]

# <h2>Function application</h2>

<p>To apply your own or another library’s functions to pandas objects,
you should be aware of the three methods below. The appropriate
method to use depends on whether your function expects to operate
on an entire <code>DataFrame</code> or <code>Series</code>, row- or column-wise, or elementwise.</p>
<ol>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#tablewise-function-application">Tablewise Function Application</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</code></a></p></li>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#row-or-column-wise-function-application">Row or Column-wise Function Application</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a></p></li>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#aggregation-api">Aggregation API</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html#pandas.DataFrame.agg" title="pandas.DataFrame.agg"><code>agg()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</code></a></p></li>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/basics.html#applying-elementwise-functions">Applying Elementwise Functions</a>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.DataFrame.map"><code>map()</code></a></p></li>
</ol>

## <h3>Tablewise function application</h3>

<p><code>DataFrames</code> and <code>Series</code> can be passed into functions.
However, if the function needs to be called in a chain, consider using the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</code></a> method.</p>

<p>First some setup:</p>

In [120]:
def extract_city_name(df):
       """
       Chicago, IL -> Chicago for city_name column
       """
       df["city_name"] = df["city_and_code"].str.split(",").str.get(0)
       return df

In [121]:
def add_country_name(df, country_name=None):
       """
       Chicago -> Chicago-US for city_name column
       """
       col = "city_name"
       df["city_and_country"] = df[col] + country_name
       return df

In [122]:
df_p = pd.DataFrame({"city_and_code": ["Chicago, IL"]})

<p><code>extract_city_name</code> and <code>add_country_name</code> are functions taking and returning <code>DataFrames</code>.</p>

<p>Now compare the following:</p>

In [123]:
add_country_name(extract_city_name(df_p), country_name="US")

  city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

<p>Is equivalent to:</p>

In [124]:
df_p.pipe(extract_city_name).pipe(add_country_name, country_name="US")

  city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

<p>pandas encourages the second style, which is known as method chaining.
<code>pipe</code> makes it easy to use your own or another library’s functions
in method chains, alongside pandas’ methods.</p>
<p>In the example above, the functions <code>extract_city_name</code> and <code>add_country_name</code> each expected a <code>DataFrame</code> as the first positional argument.
What if the function you wish to apply takes its data as, say, the second argument?
In this case, provide <code>pipe</code> with a tuple of <code>(callable, data_keyword)</code>.
<code>.pipe</code> will route the <code>DataFrame</code> to the argument specified in the tuple.</p>
<p>For example, we can fit a regression using statsmodels. Their API expects a formula first and a <code>DataFrame</code> as the second argument, <code>data</code>. We pass in the function, keyword pair <code>(sm.ols, 'data')</code> to <code>pipe</code>:</p>

In [125]:
import statsmodels.formula.api as sm

bb = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/refs/heads/main/doc/data/baseball.csv", index_col="id")

(
       bb.query("h > 0")
       .assign(ln_h=lambda df: np.log(df.h))
       .pipe((sm.ols, "data"), "hr ~ ln_h + year + g + C(lg)")
       .fit()
       .summary()
   )

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.685
Model:                            OLS   Adj. R-squared:                  0.665
Method:                 Least Squares   F-statistic:                     34.28
Date:                Mon, 08 Sep 2025   Prob (F-statistic):           3.48e-15
Time:                        11:15:49   Log-Likelihood:                -205.92
No. Observations:                  68   AIC:                             421.8
Df Residuals:                      63   BIC:                             432.9
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -8484.7720   4664.146     -1.819      0.074   -1.78e+04     835.780
C(lg)[T.NL]    -2.2736      1.325     -1.716      0.091      -4.922       0.375
ln_h           -1.3542      0.875     -1.547      0.127      -3.103       0.395
year            4.2277      2.324      1.819      0.074      -0.417       8.872
g               0.1841      0.029      6.258      0.000       0.125       0.243
==============================================================================
Omnibus:                       10.875   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               17.298
Skew:                           0.537   Prob(JB):                     0.000175
Kurtosis:                       5.225   Cond. No.                     1.49e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

<p>The pipe method is inspired by unix pipes and more recently <a href="https://github.com/tidyverse/dplyr">dplyr</a> and <a href="https://github.com/tidyverse/magrittr">magrittr</a>, which
have introduced the popular <code>(%&gt;%)</code> (read pipe) operator for <a href="https://www.r-project.org">R</a>.
The implementation of <code>pipe</code> here is quite clean and feels right at home in Python.
We encourage you to view the source code of <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html#pandas.DataFrame.pipe" title="pandas.DataFrame.pipe"><code>pipe()</code></a>.</p>

## <h3>Row or column-wise function application</h3>

<p>Arbitrary functions can be applied along the axes of a DataFrame
using the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> method, which, like the descriptive
statistics methods, takes an optional <code>axis</code> argument:</p>

In [126]:
df.apply(lambda x: np.mean(x))

one     -0.704247
two      0.893447
three    0.562725
dtype: float64

In [127]:
df.apply(lambda x: np.mean(x), axis=1)

a   -0.362512
b    0.156092
c    0.670390
d    0.697398
dtype: float64

In [128]:
df.apply(lambda x: x.max() - x.min())

one      2.638122
two      2.415704
three    2.218950
dtype: float64

In [129]:
df.apply(np.cumsum)

        one       two     three
a -1.813796  1.088772       NaN
b -2.937068  3.127337 -0.447015
c -2.112742  3.950926 -0.083759
d       NaN  3.573786  1.688176

In [130]:
df.apply(np.exp)

        one       two     three
a  0.163034  2.970625       NaN
b  0.325214  7.679579  0.639534
c  2.280343  2.278663  1.438004
d       NaN  0.685820  5.882226

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> method will also dispatch on a string method name.</p>

In [131]:
df.apply("mean")

one     -0.704247
two      0.893447
three    0.562725
dtype: float64

In [132]:
df.apply("mean", axis=1)

a   -0.362512
b    0.156092
c    0.670390
d    0.697398
dtype: float64

<p>The return type of the function passed to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> affects the
type of the final output from <code>DataFrame.apply</code> for the default behaviour:</p>
<ul>
<li><p>If the applied function returns a <code>Series</code>, the final output is a <code>DataFrame</code>.
The columns match the index of the <code>Series</code> returned by the applied function.</p></li>
<li><p>If the applied function returns any other type, the final output is a <code>Series</code>.</p></li>
</ul>
<p>This default behaviour can be overridden using the <code>result_type</code>, which
accepts three options: <code>reduce</code>, <code>broadcast</code>, and <code>expand</code>.
These will determine how list-likes return values expand (or not) to a <code>DataFrame</code>.</p>
<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> combined with some cleverness can be used to answer many questions
about a data set. For example, suppose we wanted to extract the date where the
maximum value for each column occurred:</p>

In [133]:
tsdf = pd.DataFrame(
       np.random.randn(1000, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=1000),
   )

tsdf.apply(lambda x: x.idxmax())

A   2002-05-21
B   2000-05-15
C   2001-01-23
dtype: datetime64[ns]

<p>You may also pass additional arguments and keyword arguments to the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> method.</p>

In [134]:
def subtract_and_divide(x, sub, divide=1):
       return (x - sub) / divide

df_udf = pd.DataFrame(np.ones((2, 2)))

df_udf.apply(subtract_and_divide, sub=5, divide=3)

          0         1
0 -1.333333 -1.333333
1 -1.333333 -1.333333

<p>Another useful feature is the ability to pass Series methods to carry out some Series operation on each column or row:</p>

In [135]:
tsdf = pd.DataFrame(
       np.random.randn(10, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=10),
   )

tsdf.iloc[3:7] = np.nan

In [136]:
tsdf

                   A         B         C
2000-01-01  1.426273 -0.206039  0.080453
2000-01-02  0.158786  1.439023  2.035693
2000-01-03  0.750041 -0.959542  0.893543
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.409221  0.045618 -0.200287
2000-01-09 -1.415893  0.687857  1.635022
2000-01-10  0.359352 -1.274127 -0.932117

In [137]:
tsdf.apply(pd.Series.interpolate)

                   A         B         C
2000-01-01  1.426273 -0.206039  0.080453
2000-01-02  0.158786  1.439023  2.035693
2000-01-03  0.750041 -0.959542  0.893543
2000-01-04  0.681877 -0.758510  0.674777
2000-01-05  0.613713 -0.557478  0.456011
2000-01-06  0.545549 -0.356446  0.237245
2000-01-07  0.477385 -0.155414  0.018479
2000-01-08  0.409221  0.045618 -0.200287
2000-01-09 -1.415893  0.687857  1.635022
2000-01-10  0.359352 -1.274127 -0.932117

<p>Finally, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a> takes an argument <code>raw</code> which is False by default, which converts each row or column into a Series before applying the function. When set to True, the passed function will instead receive an ndarray object, which has positive performance implications if you do not need the indexing functionality.</p>

## <h3>Aggregation API</h3>

<p>The aggregation API allows one to express possibly multiple aggregation operations in a single concise way.
This API is similar across pandas objects, see <a href="https://pandas.pydata.org/docs/user_guide/groupby.html#groupby-aggregate">groupby API</a>, the <a href="https://pandas.pydata.org/docs/user_guide/window.html#window-overview">window API</a>, and the <a href="https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-aggregate">resample API</a>.
The entry point for aggregation is <a href=".https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.aggregate.html#pandas.DataFrame.aggregate" title="pandas.DataFrame.aggregate"><code>DataFrame.aggregate()</code></a>, or the alias <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html#pandas.DataFrame.agg" title="pandas.DataFrame.agg"><code>DataFrame.agg()</code></a>.</p>

<p>We will use a similar starting frame from above:</p>

In [138]:
tsdf = pd.DataFrame(
       np.random.randn(10, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=10),
   )

tsdf.iloc[3:7] = np.nan

In [139]:
tsdf

                   A         B         C
2000-01-01  0.958595  1.870095 -0.639732
2000-01-02  0.187393 -0.378828 -0.055044
2000-01-03  0.269685  1.330343  0.151374
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.296419  1.151465 -0.451277
2000-01-09 -0.128637  0.844461 -0.806990
2000-01-10  0.136394 -0.182206 -0.477770

<p>Using a single function is equivalent to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</code></a>. You can also pass named methods as strings. These will return a <code>Series</code> of the aggregated output:</p>

In [140]:
tsdf.agg(lambda x: np.sum(x))

A    1.719850
B    4.635330
C   -2.279439
dtype: float64

In [141]:
tsdf.agg("sum")

A    1.719850
B    4.635330
C   -2.279439
dtype: float64

In [142]:
# these are equivalent to a .sum() because we are aggregating
# on a single function
tsdf.sum()

A    1.719850
B    4.635330
C   -2.279439
dtype: float64

<p>Single aggregations on a <code>Series</code> this will return a scalar value:</p>

In [143]:
tsdf["A"].agg("sum")

np.float64(1.7198499393085014)

### <h4>Aggregating with multiple functions</h4>

<p>You can pass multiple aggregation arguments as a list.
The results of each of the passed functions will be a row in the resulting <code>DataFrame</code>.
These are naturally named from the aggregation function.</p>

In [144]:
tsdf.agg(["sum"])

           A        B         C
sum  1.71985  4.63533 -2.279439

<p>Multiple functions yield multiple rows:</p>

In [145]:
tsdf.agg(["sum", "mean"])

             A         B         C
sum   1.719850  4.635330 -2.279439
mean  0.286642  0.772555 -0.379906

<p>On a <code>Series</code>, multiple functions return a <code>Series</code>, indexed by the function names:</p>

In [146]:
tsdf["A"].agg(["sum", "mean"])

sum     1.719850
mean    0.286642
Name: A, dtype: float64

<p>Passing a <code>lambda</code> function will yield a <code>&lt;lambda&gt;</code> named row:</p>

In [147]:
tsdf["A"].agg(["sum", lambda x: x.mean()])

sum         1.719850
<lambda>    0.286642
Name: A, dtype: float64

<p>Passing a named function will yield that name for the row:</p>

In [148]:
def mymean(x):
       return x.mean()

tsdf["A"].agg(["sum", mymean])

sum       1.719850
mymean    0.286642
Name: A, dtype: float64

### <h4>Aggregating with a dict</h4>

<p>Passing a dictionary of column names to a scalar or a list of scalars, to <code>DataFrame.agg</code>
allows you to customize which functions are applied to which columns. Note that the results are not in any particular order, you can use an <code>OrderedDict</code> instead to guarantee ordering.</p>

In [149]:
tsdf.agg({"A": "mean", "B": "sum"})

A    0.286642
B    4.635330
dtype: float64

<p>Passing a list-like will generate a <code>DataFrame</code> output. You will get a matrix-like output of all of the aggregators. The output will consist of all unique functions. Those that are not noted for a particular column will be <code>NaN</code>:</p>

In [150]:
tsdf.agg({"A": ["mean", "min"], "B": "sum"})

             A        B
mean  0.286642      NaN
min  -0.128637      NaN
sum        NaN  4.63533

### <h4>Custom describe</h4>

<p>With <code>.agg()</code> it is possible to easily create a custom describe function, similar to the built in <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-describe">describe function</a>.</p>

In [155]:
from functools import partial

q_25 = partial(pd.Series.quantile, q=0.25)

q_25.name = "25%"

q_75 = partial(pd.Series.quantile, q=0.75)

q_75.name = "75%"

tsdf.agg(["count", "mean", "std", "min", q_25, "median", q_75, "max"])

                 A         B         C
count     6.000000  6.000000  6.000000
mean      0.286642  0.772555 -0.379906
std       0.362432  0.883370  0.361213
min      -0.128637 -0.378828 -0.806990
quantile  0.149144  0.074461 -0.599241
median    0.228539  0.997963 -0.464523
quantile  0.289736  1.285624 -0.154102
max       0.958595  1.870095  0.151374

## <h3>Transform API</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</code></a> method returns an object that is indexed the same (same size) as the original. This API allows you to provide <em>multiple</em> operations at the same time rather than one-by-one. Its API is quite similar to the <code>.agg</code> API.</p>

<p>We create a frame similar to the one used in the above sections.</p>

In [157]:
tsdf = pd.DataFrame(
       np.random.randn(10, 3),
       columns=["A", "B", "C"],
       index=pd.date_range("1/1/2000", periods=10),
   )

tsdf.iloc[3:7] = np.nan

In [158]:
tsdf

                   A         B         C
2000-01-01 -1.826451 -0.067806 -0.177085
2000-01-02 -0.388254  0.524310 -0.801464
2000-01-03 -0.508476  1.120902  0.671076
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -1.547034 -0.928419 -0.328293
2000-01-09 -1.095869 -0.873517  2.188246
2000-01-10 -0.630756 -1.074915 -0.305048

<p>Transform the entire frame. <code>.transform()</code> allows input functions as: a NumPy function, a string function name or a user defined function.</p>

In [159]:
tsdf.transform(np.abs)

                   A         B         C
2000-01-01  1.826451  0.067806  0.177085
2000-01-02  0.388254  0.524310  0.801464
2000-01-03  0.508476  1.120902  0.671076
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.547034  0.928419  0.328293
2000-01-09  1.095869  0.873517  2.188246
2000-01-10  0.630756  1.074915  0.305048

In [160]:
tsdf.transform("abs")

                   A         B         C
2000-01-01  1.826451  0.067806  0.177085
2000-01-02  0.388254  0.524310  0.801464
2000-01-03  0.508476  1.120902  0.671076
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.547034  0.928419  0.328293
2000-01-09  1.095869  0.873517  2.188246
2000-01-10  0.630756  1.074915  0.305048

In [161]:
tsdf.transform(lambda x: x.abs())

                   A         B         C
2000-01-01  1.826451  0.067806  0.177085
2000-01-02  0.388254  0.524310  0.801464
2000-01-03  0.508476  1.120902  0.671076
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.547034  0.928419  0.328293
2000-01-09  1.095869  0.873517  2.188246
2000-01-10  0.630756  1.074915  0.305048

<p>Here <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html#pandas.DataFrame.transform" title="pandas.DataFrame.transform"><code>transform()</code></a> received a single function; this is equivalent to a <a href="https://numpy.org/doc/stable/reference/ufuncs.html">ufunc</a> application.</p>

In [162]:
np.abs(tsdf)

                   A         B         C
2000-01-01  1.826451  0.067806  0.177085
2000-01-02  0.388254  0.524310  0.801464
2000-01-03  0.508476  1.120902  0.671076
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.547034  0.928419  0.328293
2000-01-09  1.095869  0.873517  2.188246
2000-01-10  0.630756  1.074915  0.305048

<p>Passing a single function to <code>.transform()</code> with a <code>Series</code> will yield a single <code>Series</code> in return.</p>

In [163]:
tsdf["A"].transform(np.abs)

2000-01-01    1.826451
2000-01-02    0.388254
2000-01-03    0.508476
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
2000-01-08    1.547034
2000-01-09    1.095869
2000-01-10    0.630756
Freq: D, Name: A, dtype: float64

### <h4>Transform with multiple functions</h4>

<p>Passing multiple functions will yield a column MultiIndexed DataFrame.
The first level will be the original frame column names; the second level will be the names of the transforming functions.</p>

In [164]:
tsdf.transform([np.abs, lambda x: x + 1])

                   A                   B                   C
            absolute  <lambda>  absolute  <lambda>  absolute  <lambda>
2000-01-01  1.826451 -0.826451  0.067806  0.932194  0.177085  0.822915
2000-01-02  0.388254  0.611746  0.524310  1.524310  0.801464  0.198536
2000-01-03  0.508476  0.491524  1.120902  2.120902  0.671076  1.671076
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-08  1.547034 -0.547034  0.928419  0.071581  0.328293  0.671707
2000-01-09  1.095869 -0.095869  0.873517  0.126483  2.188246  3.188246
2000-01-10  0.630756  0.369244  1.074915 -0.074915  0.305048  0.694952

<p>Passing multiple functions to a Series will yield a DataFrame. The
resulting column names will be the transforming functions.</p>

In [165]:
tsdf["A"].transform([np.abs, lambda x: x + 1])

            absolute  <lambda>
2000-01-01  1.826451 -0.826451
2000-01-02  0.388254  0.611746
2000-01-03  0.508476  0.491524
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  1.547034 -0.547034
2000-01-09  1.095869 -0.095869
2000-01-10  0.630756  0.369244

### <h4>Transforming with a dict</h4>

<p>Passing a dict of functions will allow selective transforming per column.</p>

In [166]:
tsdf.transform({"A": np.abs, "B": lambda x: x + 1})

                   A         B
2000-01-01  1.826451  0.932194
2000-01-02  0.388254  1.524310
2000-01-03  0.508476  2.120902
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  1.547034  0.071581
2000-01-09  1.095869  0.126483
2000-01-10  0.630756 -0.074915

<p>Passing a dict of lists will generate a MultiIndexed DataFrame with these selective transforms.</p>

In [167]:
tsdf.transform({"A": np.abs, "B": [lambda x: x + 1, "sqrt"]})

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

                   A         B
            absolute  <lambda>      sqrt
2000-01-01  1.826451  0.932194       NaN
2000-01-02  0.388254  1.524310  0.724092
2000-01-03  0.508476  2.120902  1.058727
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.547034  0.071581       NaN
2000-01-09  1.095869  0.126483       NaN
2000-01-10  0.630756 -0.074915       NaN

## <h3>Applying elementwise functions</h3>

<p>Since not all functions can be vectorized (accept NumPy arrays and return another array or value), the methods <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.DataFrame.map"><code>map()</code></a> on DataFrame and analogously <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map" title="pandas.Series.map"><code>map()</code></a> on Series accept any Python function taking a single value and returning a single value.
For example:</p>

In [168]:
df4 = df.copy()

In [169]:
df4

        one       two     three
a -1.813796  1.088772       NaN
b -1.123272  2.038565 -0.447015
c  0.824326  0.823589  0.363256
d       NaN -0.377139  1.771935

In [172]:
def f(x):
    return len(str(x))

In [173]:
df4["one"].map(f)

a    18
b    17
c    18
d     3
Name: one, dtype: int64

In [171]:
df4.map(f)

   one  two  three
a   18   18      3
b   17   17     19
c   18   18     19
d    3   19     18

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html#pandas.Series.map"><code>Series.map()</code></a> has an additional feature; it can be used to easily “link” or “map” values defined by a secondary series. This is closely related to <a href="https://pandas.pydata.org/docs/user_guide/merging.html#merging">merging/joining functionality</a>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell77"><span></span><span class="gp">In [199]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">[</span><span class="s2">"six"</span><span class="p">,</span> <span class="s2">"seven"</span><span class="p">,</span> <span class="s2">"six"</span><span class="p">,</span> <span class="s2">"seven"</span><span class="p">,</span> <span class="s2">"six"</span><span class="p">],</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">]</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [200]: </span><span class="n">t</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">({</span><span class="s2">"six"</span><span class="p">:</span> <span class="mf">6.0</span><span class="p">,</span> <span class="s2">"seven"</span><span class="p">:</span> <span class="mf">7.0</span><span class="p">})</span>

<span class="gp">In [201]: </span><span class="n">s</span>
<span class="gh">Out[201]: </span>
<span class="go">a      six</span>
<span class="go">b    seven</span>
<span class="go">c      six</span>
<span class="go">d    seven</span>
<span class="go">e      six</span>
<span class="go">dtype: object</span>

<span class="gp">In [202]: </span><span class="n">s</span><span class="o">.</span><span class="n">map</span><span class="p">(</span><span class="n">t</span><span class="p">)</span>
<span class="gh">Out[202]: </span>
<span class="go">a    6.0</span>
<span class="go">b    7.0</span>
<span class="go">c    6.0</span>
<span class="go">d    7.0</span>
<span class="go">e    6.0</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>

# <h2>Reindexing and altering labels</h2>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</code></a> is the fundamental data alignment method in pandas.
It is used to implement nearly all other features relying on label-alignment functionality. To <em>reindex</em> means to conform the data to match a given set of labels along a particular axis. This accomplishes several things:</p>

<ul>
<li><p>Reorders the existing data to match a new set of labels</p></li>
<li><p>Inserts missing value (NA) markers in label locations where no data for
that label existed</p></li>
<li><p>If specified, <strong>fill</strong> data for missing labels using logic (highly relevant
to working with time series data)</p></li>
</ul>

<p>Here is a simple example:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell78"><span></span><span class="gp">In [203]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">])</span>

<span class="gp">In [204]: </span><span class="n">s</span>
<span class="gh">Out[204]: </span>
<span class="go">a    1.695148</span>
<span class="go">b    1.328614</span>
<span class="go">c    1.234686</span>
<span class="go">d   -0.385845</span>
<span class="go">e   -1.326508</span>
<span class="go">dtype: float64</span>

<span class="gp">In [205]: </span><span class="n">s</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"e"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"f"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">])</span>
<span class="gh">Out[205]: </span>
<span class="go">e   -1.326508</span>
<span class="go">b    1.328614</span>
<span class="go">f         NaN</span>
<span class="go">d   -0.385845</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>

<p>Here, the <code>f</code> label was not contained in the Series and hence appears as <code>NaN</code> in the result.</p>

<p>With a DataFrame, you can simultaneously reindex the index and columns:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell79"><span></span><span class="gp">In [206]: </span><span class="n">df</span>
<span class="gh">Out[206]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [207]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"c"</span><span class="p">,</span> <span class="s2">"f"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"three"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">])</span>
<span class="gh">Out[207]: </span>
<span class="go">      three       two       one</span>
<span class="go">c  1.227435  1.478369  0.695246</span>
<span class="go">f       NaN       NaN       NaN</span>
<span class="go">b -0.050390  1.912123  0.343054</span>
</pre></div>
</div>

<p>Note that the <code>Index</code> objects containing the actual axis labels can be <strong>shared</strong> between objects. So if we have a Series and a DataFrame, the following can be done:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell80"><span></span><span class="gp">In [208]: </span><span class="n">rs</span> <span class="o">=</span> <span class="n">s</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">index</span><span class="p">)</span>

<span class="gp">In [209]: </span><span class="n">rs</span>
<span class="gh">Out[209]: </span>
<span class="go">a    1.695148</span>
<span class="go">b    1.328614</span>
<span class="go">c    1.234686</span>
<span class="go">d   -0.385845</span>
<span class="go">dtype: float64</span>

<span class="gp">In [210]: </span><span class="n">rs</span><span class="o">.</span><span class="n">index</span> <span class="ow">is</span> <span class="n">df</span><span class="o">.</span><span class="n">index</span>
<span class="gh">Out[210]: </span><span class="go">True</span>
</pre>
</div>
</div>

<p>This means that the reindexed Series’s index is the same Python object as the DataFrame’s index.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html#pandas.DataFrame.reindex" title="pandas.DataFrame.reindex"><code>DataFrame.reindex()</code></a> also supports an “axis-style” calling convention, where you specify a single <code>labels</code> argument and the <code>axis</code> it applies to.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell81"><span></span><span class="gp">In [211]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"c"</span><span class="p">,</span> <span class="s2">"f"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"index"</span><span class="p">)</span>
<span class="gh">Out[211]: </span>
<span class="go">        one       two     three</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">f       NaN       NaN       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>

<span class="gp">In [212]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"three"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"columns"</span><span class="p">)</span>
<span class="gh">Out[212]: </span>
<span class="go">      three       two       one</span>
<span class="go">a       NaN  1.772517  1.394981</span>
<span class="go">b -0.050390  1.912123  0.343054</span>
<span class="go">c  1.227435  1.478369  0.695246</span>
<span class="go">d -0.613172  0.279344       NaN</span>
</pre>
</div>
</div>

<div class="admonition seealso">
<p class="admonition-title">See also</p>
<p><a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced">MultiIndex / Advanced Indexing</a> is an even more concise way of doing reindexing.</p>

</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>When writing performance-sensitive code, there is a good reason to spend some time becoming a reindexing ninja: <strong>many operations are faster on pre-aligned data</strong>. Adding two unaligned DataFrames internally triggers a reindexing step. For exploratory analysis you will hardly notice the difference (because <code>reindex</code> has been heavily optimized), but when CPU cycles matter sprinkling a few explicit <code>reindex</code> calls here and there can have an impact.</p>
</div>

## <h3>Reindexing to align with another object</h3>

<p>You may wish to take an object and reindex its axes to be labeled the same as another object. While the syntax for this is straightforward albeit verbose, it is a common enough operation that the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex_like.html#pandas.DataFrame.reindex_like" title="pandas.DataFrame.reindex_like"><code>reindex_like()</code></a> method is available to make this simpler:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell82"><span></span><span class="gp">In [213]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">])</span>

<span class="gp">In [214]: </span><span class="n">df3</span> <span class="o">=</span> <span class="n">df2</span> <span class="o">-</span> <span class="n">df2</span><span class="o">.</span><span class="n">mean</span><span class="p">()</span>

<span class="gp">In [215]: </span><span class="n">df2</span>
<span class="gh">Out[215]: </span>
<span class="go">        one       two</span>
<span class="go">a  1.394981  1.772517</span>
<span class="go">b  0.343054  1.912123</span>
<span class="go">c  0.695246  1.478369</span>

<span class="gp">In [216]: </span><span class="n">df3</span>
<span class="gh">Out[216]: </span>
<span class="go">        one       two</span>
<span class="go">a  0.583888  0.051514</span>
<span class="go">b -0.468040  0.191120</span>
<span class="go">c -0.115848 -0.242634</span>

<span class="gp">In [217]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex_like</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>
<span class="gh">Out[217]: </span>
<span class="go">        one       two</span>
<span class="go">a  1.394981  1.772517</span>
<span class="go">b  0.343054  1.912123</span>
<span class="go">c  0.695246  1.478369</span>
</pre>
</div>
</div>

## <h3>Aligning objects with each other with <code>align</code></h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.align.html#pandas.Series.align" title="pandas.Series.align"><code>align()</span></code></a> method is the fastest way to simultaneously align two objects. It
supports a <code>join</span></code> argument (related to <a href="https://pandas.pydata.org/docs/user_guide/merging.html#merging">joining and merging</span></a>):</p>

<blockquote>
<div><ul>
<li><p><code>join='outer'</span></code>: take the union of the indexes (default)</p></li>
<li><p><code>join='left'</span></code>: use the calling object’s index</p></li>
<li><p><code>join='right'</span></code>: use the passed object’s index</p></li>
<li><p><code>join='inner'</span></code>: intersect the indexes</p></li>
</ul>
</div></blockquote>

<p>It returns a tuple with both of the reindexed Series:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell83"><span></span><span class="gp">In [218]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">])</span>

<span class="gp">In [219]: </span><span class="n">s1</span> <span class="o">=</span> <span class="n">s</span><span class="p">[:</span><span class="mi">4</span><span class="p">]</span>

<span class="gp">In [220]: </span><span class="n">s2</span> <span class="o">=</span> <span class="n">s</span><span class="p">[</span><span class="mi">1</span><span class="p">:]</span>

<span class="gp">In [221]: </span><span class="n">s1</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">s2</span><span class="p">)</span>
<span class="gh">Out[221]: </span>
<span class="go">(a   -0.186646</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> e         NaN</span>
<span class="go"> dtype: float64,</span>
<span class="go"> a         NaN</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> e    1.114285</span>
<span class="go"> dtype: float64)</span>

<span class="gp">In [222]: </span><span class="n">s1</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">s2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">)</span>
<span class="gh">Out[222]: </span>
<span class="go">(b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64,</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64)</span>

<span class="gp">In [223]: </span><span class="n">s1</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">s2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"left"</span><span class="p">)</span>
<span class="gh">Out[223]: </span>
<span class="go">(a   -0.186646</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64,</span>
<span class="go"> a         NaN</span>
<span class="go"> b   -1.692424</span>
<span class="go"> c   -0.303893</span>
<span class="go"> d   -1.425662</span>
<span class="go"> dtype: float64)</span>
</pre>
</div>
</div>

<p>For DataFrames, the join method will be applied to both the index and the columns by default:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell84"><span></span><span class="gp">In [224]: </span><span class="n">df</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">)</span>
<span class="gh">Out[224]: </span>
<span class="go">(        one       two</span>
<span class="go"> a  1.394981  1.772517</span>
<span class="go"> b  0.343054  1.912123</span>
<span class="go"> c  0.695246  1.478369,</span>
<span class="go">         one       two</span>
<span class="go"> a  1.394981  1.772517</span>
<span class="go"> b  0.343054  1.912123</span>
<span class="go"> c  0.695246  1.478369)</span>
</pre>
</div>
</div>

<p>You can also pass an <code>axis</code> option to only align on the specified axis:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell85"><span></span><span class="gp">In [225]: </span><span class="n">df</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">join</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">,</span> <span class="n">axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="gh">Out[225]: </span>
<span class="go">(        one       two     three</span>
<span class="go"> a  1.394981  1.772517       NaN</span>
<span class="go"> b  0.343054  1.912123 -0.050390</span>
<span class="go"> c  0.695246  1.478369  1.227435,</span>
<span class="go">         one       two</span>
<span class="go"> a  1.394981  1.772517</span>
<span class="go"> b  0.343054  1.912123</span>
<span class="go"> c  0.695246  1.478369)</span>
</pre>
</div>
</div>

<p>If you pass a Series to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.align.html#pandas.DataFrame.align" title="pandas.DataFrame.align"><code>DataFrame.align()</code></a>, you can choose to align both objects either on the DataFrame’s index or columns using the <code>axis</code> argument:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell86"><span></span><span class="gp">In [226]: </span><span class="n">df</span><span class="o">.</span><span class="n">align</span><span class="p">(</span><span class="n">df2</span><span class="o">.</span><span class="n">iloc</span><span class="p">[</span><span class="mi">0</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[226]: </span>
<span class="go">(        one     three       two</span>
<span class="go"> a  1.394981       NaN  1.772517</span>
<span class="go"> b  0.343054 -0.050390  1.912123</span>
<span class="go"> c  0.695246  1.227435  1.478369</span>
<span class="go"> d       NaN -0.613172  0.279344,</span>
<span class="go"> one      1.394981</span>
<span class="go"> three         NaN</span>
<span class="go"> two      1.772517</span>
<span class="go"> Name: a, dtype: float64)</span>
</pre>
</div>
</div>

## <h3>Filling while reindexing</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</code></a> takes an optional parameter <code>method</code> which is a filling method chosen from the following table:</p>

<table class="table">
<colgroup>
<col style="width: 37.5%">
<col style="width: 62.5%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Method</p></th>
<th class="head"><p>Action</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>pad / ffill</p></td>
<td><p>Fill values forward</p></td>
</tr>
<tr class="row-odd"><td><p>bfill / backfill</p></td>
<td><p>Fill values backward</p></td>
</tr>
<tr class="row-even"><td><p>nearest</p></td>
<td><p>Fill from the nearest index value</p></td>
</tr>
</tbody>
</table>

<p>We illustrate these fill methods on a simple Series:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell87"><span></span><span class="gp">In [227]: </span><span class="n">rng</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/3/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">8</span><span class="p">)</span>

<span class="gp">In [228]: </span><span class="n">ts</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="n">rng</span><span class="p">)</span>

<span class="gp">In [229]: </span><span class="n">ts2</span> <span class="o">=</span> <span class="n">ts</span><span class="o">.</span><span class="n">iloc</span><span class="p">[[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">]]</span>

<span class="gp">In [230]: </span><span class="n">ts</span>
<span class="gh">Out[230]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.400528</span>
<span class="go">2000-01-05   -0.015083</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    1.414806</span>
<span class="go">2000-01-08    0.118428</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10   -0.936077</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [231]: </span><span class="n">ts2</span>
<span class="gh">Out[231]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">Freq: 3D, dtype: float64</span>

<span class="gp">In [232]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">)</span>
<span class="gh">Out[232]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04         NaN</span>
<span class="go">2000-01-05         NaN</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07         NaN</span>
<span class="go">2000-01-08         NaN</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10         NaN</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [233]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"ffill"</span><span class="p">)</span>
<span class="gh">Out[233]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05    0.183051</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08    2.395489</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [234]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"bfill"</span><span class="p">)</span>
<span class="gh">Out[234]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    2.395489</span>
<span class="go">2000-01-05    2.395489</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    0.733639</span>
<span class="go">2000-01-08    0.733639</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10         NaN</span>
<span class="go">Freq: D, dtype: float64</span>

<span class="gp">In [235]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"nearest"</span><span class="p">)</span>
<span class="gh">Out[235]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05    2.395489</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08    0.733639</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>

<p>These methods require that the indexes are <strong>ordered</strong> increasing or decreasing.</p>

<p>Note that the same result could have been achieved using
<a href="https://pandas.pydata.org/docs/user_guide/missing_data.html#missing-data-fillna">ffill</a> (except for <code>method='nearest'</code>) or <a href="https://pandas.pydata.org/docs/user_guide/missing_data.html#missing-data-interpolate">interpolate</a>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell88"><span></span><span class="gp">In [236]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">)</span><span class="o">.</span><span class="n">ffill</span><span class="p">()</span>
<span class="gh">Out[236]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05    0.183051</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08    2.395489</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.reindex.html#pandas.Series.reindex" title="pandas.Series.reindex"><code>reindex()</code></a> will raise a ValueError if the index is not monotonically increasing or decreasing. <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.fillna.html#pandas.Series.fillna" title="pandas.Series.fillna"><code>fillna()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.interpolate.html#pandas.Series.interpolate" title="pandas.Series.interpolate"><code>interpolate()</code></a> will not perform any checks on the order of the index.</p>

## <h3>Limits on filling while reindexing</h3>

<p>The <code>limit</code> and <code>tolerance</code> arguments provide additional control over filling while reindexing. Limit specifies the maximum count of consecutive matches:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell89"><span></span><span class="gp">In [237]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"ffill"</span><span class="p">,</span> <span class="n">limit</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[237]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05         NaN</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08         NaN</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>

<p>In contrast, tolerance specifies the maximum distance between the index and indexer values:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell90"><span></span><span class="gp">In [238]: </span><span class="n">ts2</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">ts</span><span class="o">.</span><span class="n">index</span><span class="p">,</span> <span class="n">method</span><span class="o">=</span><span class="s2">"ffill"</span><span class="p">,</span> <span class="n">tolerance</span><span class="o">=</span><span class="s2">"1 day"</span><span class="p">)</span>
<span class="gh">Out[238]: </span>
<span class="go">2000-01-03    0.183051</span>
<span class="go">2000-01-04    0.183051</span>
<span class="go">2000-01-05         NaN</span>
<span class="go">2000-01-06    2.395489</span>
<span class="go">2000-01-07    2.395489</span>
<span class="go">2000-01-08         NaN</span>
<span class="go">2000-01-09    0.733639</span>
<span class="go">2000-01-10    0.733639</span>
<span class="go">Freq: D, dtype: float64</span>
</pre>
</div>
</div>

<p>Notice that when used on a <code>DatetimeIndex</span></code>, <code>TimedeltaIndex</span></code> or <code>PeriodIndex</span></code>, <code>tolerance</span></code> will coerced into a <code>Timedelta</span></code> if possible.
This allows you to specify tolerance with appropriate strings.</p>

## <h3>Dropping labels from an axis</h3>

<p>A method closely related to <code>reindex</span></code> is the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html#pandas.DataFrame.drop" title="pandas.DataFrame.drop"><code>drop()</span></code></a> function.
It removes a set of labels from an axis:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell91"><span></span><span class="gp">In [239]: </span><span class="n">df</span>
<span class="gh">Out[239]: </span>
<span class="go">        one       two     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [240]: </span><span class="n">df</span><span class="o">.</span><span class="n">drop</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="gh">Out[240]: </span>
<span class="go">        one       two     three</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>

<span class="gp">In [241]: </span><span class="n">df</span><span class="o">.</span><span class="n">drop</span><span class="p">([</span><span class="s2">"one"</span><span class="p">],</span> <span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[241]: </span>
<span class="go">        two     three</span>
<span class="go">a  1.772517       NaN</span>
<span class="go">b  1.912123 -0.050390</span>
<span class="go">c  1.478369  1.227435</span>
<span class="go">d  0.279344 -0.613172</span>
</pre>
</div>
</div>

<p>Note that the following also works, but is a bit less obvious / clean:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell92"><span></span><span class="gp">In [242]: </span><span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">difference</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]))</span>
<span class="gh">Out[242]: </span>
<span class="go">        one       two     three</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
</pre>
</div>
</div>
</section>

## <h3>Renaming / mapping labels</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename" title="pandas.DataFrame.rename"><code>rename()</span></code></a> method allows you to relabel an axis based on some mapping (a dict or Series) or an arbitrary function.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell93"><span></span><span class="gp">In [243]: </span><span class="n">s</span>
<span class="gh">Out[243]: </span>
<span class="go">a   -0.186646</span>
<span class="go">b   -1.692424</span>
<span class="go">c   -0.303893</span>
<span class="go">d   -1.425662</span>
<span class="go">e    1.114285</span>
<span class="go">dtype: float64</span>

<span class="gp">In [244]: </span><span class="n">s</span><span class="o">.</span><span class="n">rename</span><span class="p">(</span><span class="nb">str</span><span class="o">.</span><span class="n">upper</span><span class="p">)</span>
<span class="gh">Out[244]: </span>
<span class="go">A   -0.186646</span>
<span class="go">B   -1.692424</span>
<span class="go">C   -0.303893</span>
<span class="go">D   -1.425662</span>
<span class="go">E    1.114285</span>
<span class="go">dtype: float64</span>
</pre>
</div>
</div>

<p>If you pass a function, it must return a value when called with any of the labels (and must produce a set of unique values). A dict or
Series can also be used:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell94"><span></span><span class="gp">In [245]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename</span><span class="p">(</span>
<span class="gp">   </span>    <span class="n">columns</span><span class="o">=</span><span class="p">{</span><span class="s2">"one"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">:</span> <span class="s2">"bar"</span><span class="p">},</span>
<span class="gp">   </span>    <span class="n">index</span><span class="o">=</span><span class="p">{</span><span class="s2">"a"</span><span class="p">:</span> <span class="s2">"apple"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">:</span> <span class="s2">"banana"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">:</span> <span class="s2">"durian"</span><span class="p">},</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>
<span class="gh">Out[245]: </span>
<span class="go">             foo       bar     three</span>
<span class="go">apple   1.394981  1.772517       NaN</span>
<span class="go">banana  0.343054  1.912123 -0.050390</span>
<span class="go">c       0.695246  1.478369  1.227435</span>
<span class="go">durian       NaN  0.279344 -0.613172</span>
</pre>
</div>
</div>

<p>If the mapping doesn’t include a column/index label, it isn’t renamed. Note that extra labels in the mapping don’t throw an error.</p>
<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename" title="pandas.DataFrame.rename"><code>DataFrame.rename()</span></code></a> also supports an “axis-style” calling convention, where you specify a single <code>mapper</span></code> and the <code>axis</span></code> to apply that mapping to.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell95"><span></span><span class="gp">In [246]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename</span><span class="p">({</span><span class="s2">"one"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">:</span> <span class="s2">"bar"</span><span class="p">},</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"columns"</span><span class="p">)</span>
<span class="gh">Out[246]: </span>
<span class="go">        foo       bar     three</span>
<span class="go">a  1.394981  1.772517       NaN</span>
<span class="go">b  0.343054  1.912123 -0.050390</span>
<span class="go">c  0.695246  1.478369  1.227435</span>
<span class="go">d       NaN  0.279344 -0.613172</span>

<span class="gp">In [247]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="s2">"apple"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">:</span> <span class="s2">"banana"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">:</span> <span class="s2">"durian"</span><span class="p">},</span> <span class="n">axis</span><span class="o">=</span><span class="s2">"index"</span><span class="p">)</span>
<span class="gh">Out[247]: </span>
<span class="go">             one       two     three</span>
<span class="go">apple   1.394981  1.772517       NaN</span>
<span class="go">banana  0.343054  1.912123 -0.050390</span>
<span class="go">c       0.695246  1.478369  1.227435</span>
<span class="go">durian       NaN  0.279344 -0.613172</span>
</pre>
</div>
</div>

<p>Finally, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.rename.html#pandas.Series.rename" title="pandas.Series.rename"><code>rename()</span></code></a> also accepts a scalar or list-like for altering the <code>Series.name</span></code> attribute.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell96"><span></span><span class="gp">In [248]: </span><span class="n">s</span><span class="o">.</span><span class="n">rename</span><span class="p">(</span><span class="s2">"scalar-name"</span><span class="p">)</span>
<span class="gh">Out[248]: </span>
<span class="go">a   -0.186646</span>
<span class="go">b   -1.692424</span>
<span class="go">c   -0.303893</span>
<span class="go">d   -1.425662</span>
<span class="go">e    1.114285</span>
<span class="go">Name: scalar-name, dtype: float64</span>
</pre>
</div>
</div>

<p>The methods <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename_axis.html#pandas.DataFrame.rename_axis" title="pandas.DataFrame.rename_axis"><code>DataFrame.rename_axis()</span></code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.rename_axis.html#pandas.Series.rename_axis" title="pandas.Series.rename_axis"><code>Series.rename_axis()</span></code></a> allow specific names of a <code>MultiIndex</span></code> to be changed (as opposed to the labels).</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell97"><span></span><span class="gp">In [249]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span><span class="s2">"x"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"y"</span><span class="p">:</span> <span class="p">[</span><span class="mi">10</span><span class="p">,</span> <span class="mi">20</span><span class="p">,</span> <span class="mi">30</span><span class="p">,</span> <span class="mi">40</span><span class="p">,</span> <span class="mi">50</span><span class="p">,</span> <span class="mi">60</span><span class="p">]},</span>
<span class="gp">   </span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_product</span><span class="p">(</span>
<span class="gp">   </span>        <span class="p">[[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">],</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]],</span> <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"let"</span><span class="p">,</span> <span class="s2">"num"</span><span class="p">]</span>
<span class="gp">   </span>    <span class="p">),</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [250]: </span><span class="n">df</span>
<span class="gh">Out[250]: </span>
<span class="go">         x   y</span>
<span class="go">let num       </span>
<span class="go">a   1    1  10</span>
<span class="go">    2    2  20</span>
<span class="go">b   1    3  30</span>
<span class="go">    2    4  40</span>
<span class="go">c   1    5  50</span>
<span class="go">    2    6  60</span>

<span class="gp">In [251]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename_axis</span><span class="p">(</span><span class="n">index</span><span class="o">=</span><span class="p">{</span><span class="s2">"let"</span><span class="p">:</span> <span class="s2">"abc"</span><span class="p">})</span>
<span class="gh">Out[251]: </span>
<span class="go">         x   y</span>
<span class="go">abc num       </span>
<span class="go">a   1    1  10</span>
<span class="go">    2    2  20</span>
<span class="go">b   1    3  30</span>
<span class="go">    2    4  40</span>
<span class="go">c   1    5  50</span>
<span class="go">    2    6  60</span>

<span class="gp">In [252]: </span><span class="n">df</span><span class="o">.</span><span class="n">rename_axis</span><span class="p">(</span><span class="n">index</span><span class="o">=</span><span class="nb">str</span><span class="o">.</span><span class="n">upper</span><span class="p">)</span>
<span class="gh">Out[252]: </span>
<span class="go">         x   y</span>
<span class="go">LET NUM       </span>
<span class="go">a   1    1  10</span>
<span class="go">    2    2  20</span>
<span class="go">b   1    3  30</span>
<span class="go">    2    4  40</span>
<span class="go">c   1    5  50</span>
<span class="go">    2    6  60</span>
</pre>
</div>
</div>

# <h2>Iteration</h2>

<p>The behavior of basic iteration over pandas objects depends on the type. When iterating over a Series, it is regarded as array-like, and basic iteration produces the values. DataFrames follow the dict-like convention of iterating over the “keys” of the objects.</p>

<p>In short, basic iteration (<code>for</span> i</span> in</span> object</span></code>) produces:</p>

<ul>
<li><p><strong>Series</strong>: values</p></li>
<li><p><strong>DataFrame</strong>: column labels</p></li>
</ul>

<p>Thus, for example, iterating over a DataFrame gives you the column names:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell98"><span></span><span class="gp">In [253]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span><span class="s2">"col1"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="s2">"col2"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">)},</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">]</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [254]: </span><span class="k">for</span> <span class="n">col</span> <span class="ow">in</span> <span class="n">df</span><span class="p">:</span>
<span class="gp">   </span>    <span class="nb">print</span><span class="p">(</span><span class="n">col</span><span class="p">)</span>
<span class="gp">   </span>
<span class="go">col1</span>
<span class="go">col2</span>
</pre>
</div>
</div>

<p>pandas objects also have the dict-like <a href="../reference/api/pandas.DataFrame.items.html#pandas.DataFrame.items" title="pandas.DataFrame.items"><code>items()</span></code></a> method to
iterate over the (key, value) pairs.</p>

<p>To iterate over the rows of a DataFrame, you can use the following methods:</p>

<ul>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a>: Iterate over the rows of a DataFrame as (index, Series) pairs.
This converts the rows to Series objects, which can change the dtypes and has some performance implications.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a>: Iterate over the rows of a DataFrame as namedtuples of the values.  This is a lot faster than <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a>, and is in most cases preferable to use to iterate over the values of a DataFrame.</p></li>
</ul>

<div class="admonition warning">
<p class="admonition-title">Warning</p>

<p>Iterating through pandas objects is generally <strong>slow</strong>. In many cases,
iterating manually over the rows is not needed and can be avoided with
one of the following approaches:</p>

<ul>
<li><p>Look for a <em>vectorized</em> solution: many operations can be performed using built-in methods or NumPy functions, (boolean) indexing, …</p></li>
<li><p>When you have a function that cannot work on the full DataFrame/Series at once, it is better to use <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a> instead of iterating over the values. See the docs on <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-apply">function application</span></a>.</p></li>
<li><p>If you need to do iterative manipulations on the values but performance is important, consider writing the inner loop with cython or numba. See the <a href="https://pandas.pydata.org/docs/user_guide/enhancingperf.html#enhancingperf">enhancing performance</span></a> section for some examples of this approach.</p></li>
</ul>
</div>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>You should <strong>never modify</strong> something you are iterating over. This is not guaranteed to work in all cases. Depending on the
data types, the iterator returns a copy and not a view, and writing
to it will have no effect!</p>

<p>For example, in the following case setting the value has no effect:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell99"><span></span><span class="gp">In [255]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">]})</span>

<span class="gp">In [256]: </span><span class="k">for</span> <span class="n">index</span><span class="p">,</span> <span class="n">row</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">iterrows</span><span class="p">():</span>
<span class="gp">   </span>    <span class="n">row</span><span class="p">[</span><span class="s2">"a"</span><span class="p">]</span> <span class="o">=</span> <span class="mi">10</span>
<span class="gp">   </span>

<span class="gp">In [257]: </span><span class="n">df</span>
<span class="gh">Out[257]: </span>
<span class="go">   a  b</span>
<span class="go">0  1  a</span>
<span class="go">1  2  b</span>
<span class="go">2  3  c</span>
</pre>
</div>
</div>
</div>

## <h3>items</h3>

<p>Consistent with the dict-like interface, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.items.html#pandas.DataFrame.items" title="pandas.DataFrame.items"><code>items()</code></a> iterates through key-value pairs:</p>

<ul>
<li><p><strong>Series</strong>: (index, scalar value) pairs</p></li>
<li><p><strong>DataFrame</strong>: (column, Series) pairs</p></li>
</ul>

<p>For example:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell100"><span></span><span class="gp">In [258]: </span><span class="k">for</span> <span class="n">label</span><span class="p">,</span> <span class="n">ser</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">items</span><span class="p">():</span>
<span class="gp">   </span>    <span class="nb">print</span><span class="p">(</span><span class="n">label</span><span class="p">)</span>
<span class="gp">   </span>    <span class="nb">print</span><span class="p">(</span><span class="n">ser</span><span class="p">)</span>
<span class="gp">   </span>
<span class="go">a</span>
<span class="go">0    1</span>
<span class="go">1    2</span>
<span class="go">2    3</span>
<span class="go">Name: a, dtype: int64</span>
<span class="go">b</span>
<span class="go">0    a</span>
<span class="go">1    b</span>
<span class="go">2    c</span>
<span class="go">Name: b, dtype: object</span>
</pre>
</div>
</div>

## <h3>iterrows</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a> allows you to iterate through the rows of a DataFrame as Series objects. It returns an iterator yielding each index value along with a Series containing the data in each row:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell101"><span></span><span class="gp">In [259]: </span><span class="k">for</span> <span class="n">row_index</span><span class="p">,</span> <span class="n">row</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">iterrows</span><span class="p">():</span>
<span class="gp">   </span>    <span class="nb">print</span><span class="p">(</span><span class="n">row_index</span><span class="p">,</span> <span class="n">row</span><span class="p">,</span> <span class="n">sep</span><span class="o">=</span><span class="s2">"</span><span class="se">\n</span><span class="s2">"</span><span class="p">)</span>
<span class="gp">   </span>
<span class="go">0</span>
<span class="go">a    1</span>
<span class="go">b    a</span>
<span class="go">Name: 0, dtype: object</span>
<span class="go">1</span>
<span class="go">a    2</span>
<span class="go">b    b</span>
<span class="go">Name: 1, dtype: object</span>
<span class="go">2</span>
<span class="go">a    3</span>
<span class="go">b    c</span>
<span class="go">Name: 2, dtype: object</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Because <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</code></a> returns a Series for each row, it does <strong>not</strong> preserve dtypes across the rows (dtypes are preserved across columns for DataFrames). For example,</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell102"><span></span><span class="gp">In [260]: </span><span class="n">df_orig</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="mi">1</span><span class="p">,</span> <span class="mf">1.5</span><span class="p">]],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"int"</span><span class="p">,</span> <span class="s2">"float"</span><span class="p">])</span>

<span class="gp">In [261]: </span><span class="n">df_orig</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[261]: </span>
<span class="go">int        int64</span>
<span class="go">float    float64</span>
<span class="go">dtype: object</span>

<span class="gp">In [262]: </span><span class="n">row</span> <span class="o">=</span> <span class="nb">next</span><span class="p">(</span><span class="n">df_orig</span><span class="o">.</span><span class="n">iterrows</span><span class="p">())[</span><span class="mi">1</span><span class="p">]</span>

<span class="gp">In [263]: </span><span class="n">row</span>
<span class="gh">Out[263]: </span>
<span class="go">int      1.0</span>
<span class="go">float    1.5</span>
<span class="go">Name: 0, dtype: float64</span>
</pre>
</div>
</div>

<p>All values in <code>row</span></code>, returned as a Series, are now upcasted to floats, also the original integer value in column <code>x</span></code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell103"><span></span><span class="gp">In [264]: </span><span class="n">row</span><span class="p">[</span><span class="s2">"int"</span><span class="p">]</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[264]: </span><span class="go">dtype('float64')</span>

<span class="gp">In [265]: </span><span class="n">df_orig</span><span class="p">[</span><span class="s2">"int"</span><span class="p">]</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[265]: </span><span class="go">dtype('int64')</span>
</pre>
</div>
</div>
<p>To preserve dtypes while iterating over the rows, it is better
to use <a href="../reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a> which returns namedtuples of the values
and which is generally much faster than <a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a>.</p>
</div>
<p>For instance, a contrived way to transpose the DataFrame would be:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell104"><span></span><span class="gp">In [266]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"x"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"y"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">]})</span>

<span class="gp">In [267]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>
<span class="go">   x  y</span>
<span class="go">0  1  4</span>
<span class="go">1  2  5</span>
<span class="go">2  3  6</span>

<span class="gp">In [268]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df2</span><span class="o">.</span><span class="n">T</span><span class="p">)</span>
<span class="go">   0  1  2</span>
<span class="go">x  1  2  3</span>
<span class="go">y  4  5  6</span>

<span class="gp">In [269]: </span><span class="n">df2_t</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="n">idx</span><span class="p">:</span> <span class="n">values</span> <span class="k">for</span> <span class="n">idx</span><span class="p">,</span> <span class="n">values</span> <span class="ow">in</span> <span class="n">df2</span><span class="o">.</span><span class="n">iterrows</span><span class="p">()})</span>

<span class="gp">In [270]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df2_t</span><span class="p">)</span>
<span class="go">   0  1  2</span>
<span class="go">x  1  2  3</span>
<span class="go">y  4  5  6</span>
</pre>
</div>
</div>

## <h3>itertuples</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a> method will return an iterator yielding a namedtuple for each row in the DataFrame. The first element of the tuple will be the row’s corresponding index value, while the remaining values are the row values.</p>

<p>For instance:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell105"><span></span><span class="gp">In [271]: </span><span class="k">for</span> <span class="n">row</span> <span class="ow">in</span> <span class="n">df</span><span class="o">.</span><span class="n">itertuples</span><span class="p">():</span>
<span class="gp">   </span>    <span class="nb">print</span><span class="p">(</span><span class="n">row</span><span class="p">)</span>
<span class="gp">   </span>
<span class="go">Pandas(Index=0, a=1, b='a')</span>
<span class="go">Pandas(Index=1, a=2, b='b')</span>
<span class="go">Pandas(Index=2, a=3, b='c')</span>
</pre>
</div>
</div>

<p>This method does not convert the row to a Series object; it merely
returns the values inside a namedtuple. Therefore,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples" title="pandas.DataFrame.itertuples"><code>itertuples()</span></code></a> preserves the data type of the values and is generally faster as <a href="../reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows" title="pandas.DataFrame.iterrows"><code>iterrows()</span></code></a>.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The column names will be renamed to positional names if they are
invalid Python identifiers, repeated, or start with an underscore.
With a large number of columns (&gt;255), regular tuples are returned.</p>
</div>

# <h2>.dt accessor</h2>

<p><code>Series</span></code> has an accessor to succinctly return datetime like properties for the <em>values</em> of the Series, if it is a datetime/period like Series.
This will return a Series, indexed like the existing Series.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell106"><span></span><span class="go"># datetime</span>
<span class="gp">In [272]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101 09:10:12"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [273]: </span><span class="n">s</span>
<span class="gh">Out[273]: </span>
<span class="go">0   2013-01-01 09:10:12</span>
<span class="go">1   2013-01-02 09:10:12</span>
<span class="go">2   2013-01-03 09:10:12</span>
<span class="go">3   2013-01-04 09:10:12</span>
<span class="go">dtype: datetime64[ns]</span>

<span class="gp">In [274]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">hour</span>
<span class="gh">Out[274]: </span>
<span class="go">0    9</span>
<span class="go">1    9</span>
<span class="go">2    9</span>
<span class="go">3    9</span>
<span class="go">dtype: int32</span>

<span class="gp">In [275]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">second</span>
<span class="gh">Out[275]: </span>
<span class="go">0    12</span>
<span class="go">1    12</span>
<span class="go">2    12</span>
<span class="go">3    12</span>
<span class="go">dtype: int32</span>

<span class="gp">In [276]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">day</span>
<span class="gh">Out[276]: </span>
<span class="go">0    1</span>
<span class="go">1    2</span>
<span class="go">2    3</span>
<span class="go">3    4</span>
<span class="go">dtype: int32</span>
</pre>
</div>
</div>

<p>This enables nice expressions like this:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell107"><span></span><span class="gp">In [277]: </span><span class="n">s</span><span class="p">[</span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">day</span> <span class="o">==</span> <span class="mi">2</span><span class="p">]</span>
<span class="gh">Out[277]: </span>
<span class="go">1   2013-01-02 09:10:12</span>
<span class="go">dtype: datetime64[ns]</span>
</pre>
</div>
</div>

<p>You can easily produces tz aware transformations:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell108"><span></span><span class="gp">In [278]: </span><span class="n">stz</span> <span class="o">=</span> <span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz_localize</span><span class="p">(</span><span class="s2">"US/Eastern"</span><span class="p">)</span>

<span class="gp">In [279]: </span><span class="n">stz</span>
<span class="gh">Out[279]: </span>
<span class="go">0   2013-01-01 09:10:12-05:00</span>
<span class="go">1   2013-01-02 09:10:12-05:00</span>
<span class="go">2   2013-01-03 09:10:12-05:00</span>
<span class="go">3   2013-01-04 09:10:12-05:00</span>
<span class="go">dtype: datetime64[ns, US/Eastern]</span>

<span class="gp">In [280]: </span><span class="n">stz</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz</span>
<span class="gh">Out[280]: </span><span class="go">&lt;DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD&gt;</span>
</pre>
</div>
</div>

<p>You can also chain these types of operations:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell109"><span></span><span class="gp">In [281]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz_localize</span><span class="p">(</span><span class="s2">"UTC"</span><span class="p">)</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">tz_convert</span><span class="p">(</span><span class="s2">"US/Eastern"</span><span class="p">)</span>
<span class="gh">Out[281]: </span>
<span class="go">0   2013-01-01 04:10:12-05:00</span>
<span class="go">1   2013-01-02 04:10:12-05:00</span>
<span class="go">2   2013-01-03 04:10:12-05:00</span>
<span class="go">3   2013-01-04 04:10:12-05:00</span>
<span class="go">dtype: datetime64[ns, US/Eastern]</span>
</pre>
</div>
</div>

<p>You can also format datetime values as strings with <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.strftime.html#pandas.Series.dt.strftime" title="pandas.Series.dt.strftime"><code>Series.dt.strftime()</span></code></a> which supports the same format as the standard <a href="https://docs.python.org/3/library/datetime.html#datetime.datetime.strftime" title="(in Python v3.13)"><code>strftime()</span></code></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell110"><span></span><span class="go"># DatetimeIndex</span>
<span class="gp">In [282]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [283]: </span><span class="n">s</span>
<span class="gh">Out[283]: </span>
<span class="go">0   2013-01-01</span>
<span class="go">1   2013-01-02</span>
<span class="go">2   2013-01-03</span>
<span class="go">3   2013-01-04</span>
<span class="go">dtype: datetime64[ns]</span>

<span class="gp">In [284]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">strftime</span><span class="p">(</span><span class="s2">"%Y/%m/</span><span class="si">%d</span><span class="s2">"</span><span class="p">)</span>
<span class="gh">Out[284]: </span>
<span class="go">0    2013/01/01</span>
<span class="go">1    2013/01/02</span>
<span class="go">2    2013/01/03</span>
<span class="go">3    2013/01/04</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell111"><span></span><span class="go"># PeriodIndex</span>
<span class="gp">In [285]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">period_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [286]: </span><span class="n">s</span>
<span class="gh">Out[286]: </span>
<span class="go">0    2013-01-01</span>
<span class="go">1    2013-01-02</span>
<span class="go">2    2013-01-03</span>
<span class="go">3    2013-01-04</span>
<span class="go">dtype: period[D]</span>

<span class="gp">In [287]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">strftime</span><span class="p">(</span><span class="s2">"%Y/%m/</span><span class="si">%d</span><span class="s2">"</span><span class="p">)</span>
<span class="gh">Out[287]: </span>
<span class="go">0    2013/01/01</span>
<span class="go">1    2013/01/02</span>
<span class="go">2    2013/01/03</span>
<span class="go">3    2013/01/04</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>The <code>.dt</span></code> accessor works for period and timedelta dtypes.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell112"><span></span><span class="go"># period</span>
<span class="gp">In [288]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">period_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"D"</span><span class="p">))</span>

<span class="gp">In [289]: </span><span class="n">s</span>
<span class="gh">Out[289]: </span>
<span class="go">0    2013-01-01</span>
<span class="go">1    2013-01-02</span>
<span class="go">2    2013-01-03</span>
<span class="go">3    2013-01-04</span>
<span class="go">dtype: period[D]</span>

<span class="gp">In [290]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">year</span>
<span class="gh">Out[290]: </span>
<span class="go">0    2013</span>
<span class="go">1    2013</span>
<span class="go">2    2013</span>
<span class="go">3    2013</span>
<span class="go">dtype: int64</span>

<span class="gp">In [291]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">day</span>
<span class="gh">Out[291]: </span>
<span class="go">0    1</span>
<span class="go">1    2</span>
<span class="go">2    3</span>
<span class="go">3    4</span>
<span class="go">dtype: int64</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell113"><span></span><span class="go"># timedelta</span>
<span class="gp">In [292]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">timedelta_range</span><span class="p">(</span><span class="s2">"1 day 00:00:05"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"s"</span><span class="p">))</span>

<span class="gp">In [293]: </span><span class="n">s</span>
<span class="gh">Out[293]: </span>
<span class="go">0   1 days 00:00:05</span>
<span class="go">1   1 days 00:00:06</span>
<span class="go">2   1 days 00:00:07</span>
<span class="go">3   1 days 00:00:08</span>
<span class="go">dtype: timedelta64[ns]</span>

<span class="gp">In [294]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">days</span>
<span class="gh">Out[294]: </span>
<span class="go">0    1</span>
<span class="go">1    1</span>
<span class="go">2    1</span>
<span class="go">3    1</span>
<span class="go">dtype: int64</span>

<span class="gp">In [295]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">seconds</span>
<span class="gh">Out[295]: </span>
<span class="go">0    5</span>
<span class="go">1    6</span>
<span class="go">2    7</span>
<span class="go">3    8</span>
<span class="go">dtype: int32</span>

<span class="gp">In [296]: </span><span class="n">s</span><span class="o">.</span><span class="n">dt</span><span class="o">.</span><span class="n">components</span>
<span class="gh">Out[296]: </span>
<span class="go">   days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds</span>
<span class="go">0     1      0        0        5             0             0            0</span>
<span class="go">1     1      0        0        6             0             0            0</span>
<span class="go">2     1      0        0        7             0             0            0</span>
<span class="go">3     1      0        0        8             0             0            0</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>Series.dt</span></code> will raise a <code>TypeError</span></code> if you access with a non-datetime-like values.</p>
</div>

# <h2>Vectorized string methods</h2>

<p>Series is equipped with a set of string processing methods that make it easy to operate on each element of the array. Perhaps most importantly, these methods exclude missing/NA values automatically. These are accessed via the Series’s <code>str</span></code> attribute and generally have names matching the equivalent (scalar) built-in string methods. For example:</p>
<blockquote>

<div><div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell114"><span></span><span class="gp">In [297]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">,</span> <span class="s2">"Aaba"</span><span class="p">,</span> <span class="s2">"Baca"</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="s2">"CABA"</span><span class="p">,</span> <span class="s2">"dog"</span><span class="p">,</span> <span class="s2">"cat"</span><span class="p">],</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"string"</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [298]: </span><span class="n">s</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">()</span>
<span class="gh">Out[298]: </span>
<span class="go">0       a</span>
<span class="go">1       b</span>
<span class="go">2       c</span>
<span class="go">3    aaba</span>
<span class="go">4    baca</span>
<span class="go">5    &lt;NA&gt;</span>
<span class="go">6    caba</span>
<span class="go">7     dog</span>
<span class="go">8     cat</span>
<span class="go">dtype: string</span>
</pre>
</div>
</div>
</div></blockquote>

<p>Powerful pattern-matching methods are provided as well, but note that
pattern-matching generally uses <a href="https://docs.python.org/3/library/re.html">regular expressions</a> by default (and in some cases
always uses them).</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Prior to pandas 1.0, string methods were only available on <code>object</span></code> -dtype
<code>Series</span></code>. pandas 1.0 added the <a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a> which is dedicated
to strings. See <a href="text.html#text-types">Text data types</span></a> for more.</p>
</div>

<p>Please see <a href="text.html#text-string-methods">Vectorized String Methods</span></a> for a complete
description.</p>

# <h2>Sorting</h2>

<p>pandas supports three kinds of sorting: sorting by index labels,
sorting by column values, and sorting by a combination of both.</p>

## <h3>By index</h3>

<p>The <a href="../reference/api/pandas.Series.sort_index.html#pandas.Series.sort_index" title="pandas.Series.sort_index"><code>Series.sort_index()</span></code></a> and <a href="../reference/api/pandas.DataFrame.sort_index.html#pandas.DataFrame.sort_index" title="pandas.DataFrame.sort_index"><code>DataFrame.sort_index()</span></code></a> methods are used to sort a pandas object by its index levels.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell115"><span></span><span class="gp">In [299]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span>
<span class="gp">   </span>        <span class="s2">"one"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">]),</span>
<span class="gp">   </span>        <span class="s2">"two"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">4</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]),</span>
<span class="gp">   </span>        <span class="s2">"three"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]),</span>
<span class="gp">   </span>    <span class="p">}</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [300]: </span><span class="n">unsorted_df</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">reindex</span><span class="p">(</span>
<span class="gp">   </span>    <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"three"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">]</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [301]: </span><span class="n">unsorted_df</span>
<span class="gh">Out[301]: </span>
<span class="go">      three       two       one</span>
<span class="go">a       NaN -1.152244  0.562973</span>
<span class="go">d -0.252916 -0.109597       NaN</span>
<span class="go">c  1.273388 -0.167123  0.640382</span>
<span class="go">b -0.098217  0.009797 -1.299504</span>

<span class="go"># DataFrame</span>
<span class="gp">In [302]: </span><span class="n">unsorted_df</span><span class="o">.</span><span class="n">sort_index</span><span class="p">()</span>
<span class="gh">Out[302]: </span>
<span class="go">      three       two       one</span>
<span class="go">a       NaN -1.152244  0.562973</span>
<span class="go">b -0.098217  0.009797 -1.299504</span>
<span class="go">c  1.273388 -0.167123  0.640382</span>
<span class="go">d -0.252916 -0.109597       NaN</span>

<span class="gp">In [303]: </span><span class="n">unsorted_df</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">ascending</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
<span class="gh">Out[303]: </span>
<span class="go">      three       two       one</span>
<span class="go">d -0.252916 -0.109597       NaN</span>
<span class="go">c  1.273388 -0.167123  0.640382</span>
<span class="go">b -0.098217  0.009797 -1.299504</span>
<span class="go">a       NaN -1.152244  0.562973</span>

<span class="gp">In [304]: </span><span class="n">unsorted_df</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[304]: </span>
<span class="go">        one     three       two</span>
<span class="go">a  0.562973       NaN -1.152244</span>
<span class="go">d       NaN -0.252916 -0.109597</span>
<span class="go">c  0.640382  1.273388 -0.167123</span>
<span class="go">b -1.299504 -0.098217  0.009797</span>

<span class="go"># Series</span>
<span class="gp">In [305]: </span><span class="n">unsorted_df</span><span class="p">[</span><span class="s2">"three"</span><span class="p">]</span><span class="o">.</span><span class="n">sort_index</span><span class="p">()</span>
<span class="gh">Out[305]: </span>
<span class="go">a         NaN</span>
<span class="go">b   -0.098217</span>
<span class="go">c    1.273388</span>
<span class="go">d   -0.252916</span>
<span class="go">Name: three, dtype: float64</span>
</pre>
</div>
</div>

<p id="basics-sort-index-key">Sorting by index also supports a <code>key</span></code> parameter that takes a callable
function to apply to the index being sorted. For <code>MultiIndex</span></code> objects, the key is applied per-level to the levels specified by <code>level</span></code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell116"><span></span><span class="gp">In [306]: </span><span class="n">s1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]})</span><span class="o">.</span><span class="n">set_index</span><span class="p">(</span>
<span class="gp">   </span>    <span class="nb">list</span><span class="p">(</span><span class="s2">"ab"</span><span class="p">)</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [307]: </span><span class="n">s1</span>
<span class="gh">Out[307]: </span>
<span class="go">     c</span>
<span class="go">a b   </span>
<span class="go">B 1  2</span>
<span class="go">a 2  3</span>
<span class="go">C 3  4</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell117"><span></span><span class="gp">In [308]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">level</span><span class="o">=</span><span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[308]: </span>
<span class="go">     c</span>
<span class="go">a b   </span>
<span class="go">B 1  2</span>
<span class="go">C 3  4</span>
<span class="go">a 2  3</span>

<span class="gp">In [309]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">level</span><span class="o">=</span><span class="s2">"a"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="k">lambda</span> <span class="n">idx</span><span class="p">:</span> <span class="n">idx</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">())</span>
<span class="gh">Out[309]: </span>
<span class="go">     c</span>
<span class="go">a b   </span>
<span class="go">a 2  3</span>
<span class="go">B 1  2</span>
<span class="go">C 3  4</span>
</pre>
</div>
</div>

<p>For information on key sorting by value, see <a href="#basics-sort-value-key">value sorting</span></a>.</p>

## <h3>By values</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.sort_values.html#pandas.Series.sort_values" title="pandas.Series.sort_values"><code>Series.sort_values()</span></code></a> method is used to sort a <code>Series</span></code> by its values. The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</span></code></a> method is used to sort a <code>DataFrame</span></code> by its column or row values.
The optional <code>by</span></code> parameter to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</span></code></a> may used to specify one or more columns to use to determine the sorted order.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell118"><span></span><span class="gp">In [310]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span><span class="s2">"one"</span><span class="p">:</span> <span class="p">[</span><span class="mi">2</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">],</span> <span class="s2">"two"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">4</span><span class="p">],</span> <span class="s2">"three"</span><span class="p">:</span> <span class="p">[</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">]}</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [311]: </span><span class="n">df1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="s2">"two"</span><span class="p">)</span>
<span class="gh">Out[311]: </span>
<span class="go">   one  two  three</span>
<span class="go">0    2    1      5</span>
<span class="go">2    1    2      3</span>
<span class="go">1    1    3      4</span>
<span class="go">3    1    4      2</span>
</pre>
</div>
</div>

<p>The <code>by</span></code> parameter can take a list of column names, e.g.:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell119"><span></span><span class="gp">In [312]: </span><span class="n">df1</span><span class="p">[[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"three"</span><span class="p">]]</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="p">[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">])</span>
<span class="gh">Out[312]: </span>
<span class="go">   one  two  three</span>
<span class="go">2    1    2      3</span>
<span class="go">1    1    3      4</span>
<span class="go">3    1    4      2</span>
<span class="go">0    2    1      5</span>
</pre>
</div>
</div>

<p>These methods have special treatment of NA values via the <code>na_position</span></code> argument:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell120"><span></span><span class="gp">In [313]: </span><span class="n">s</span><span class="p">[</span><span class="mi">2</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [314]: </span><span class="n">s</span><span class="o">.</span><span class="n">sort_values</span><span class="p">()</span>
<span class="gh">Out[314]: </span>
<span class="go">0       A</span>
<span class="go">3    Aaba</span>
<span class="go">1       B</span>
<span class="go">4    Baca</span>
<span class="go">6    CABA</span>
<span class="go">8     cat</span>
<span class="go">7     dog</span>
<span class="go">2    &lt;NA&gt;</span>
<span class="go">5    &lt;NA&gt;</span>
<span class="go">dtype: string</span>

<span class="gp">In [315]: </span><span class="n">s</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">na_position</span><span class="o">=</span><span class="s2">"first"</span><span class="p">)</span>
<span class="gh">Out[315]: </span>
<span class="go">2    &lt;NA&gt;</span>
<span class="go">5    &lt;NA&gt;</span>
<span class="go">0       A</span>
<span class="go">3    Aaba</span>
<span class="go">1       B</span>
<span class="go">4    Baca</span>
<span class="go">6    CABA</span>
<span class="go">8     cat</span>
<span class="go">7     dog</span>
<span class="go">dtype: string</span>
</pre>
</div>
</div>

<p>Sorting also supports a <code>key</span></code> parameter that takes a callable function to apply to the values being sorted.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell121"><span></span><span class="gp">In [316]: </span><span class="n">s1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">])</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell122"><span></span><span class="gp">In [317]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">()</span>
<span class="gh">Out[317]: </span>
<span class="go">0    B</span>
<span class="go">2    C</span>
<span class="go">1    a</span>
<span class="go">dtype: object</span>

<span class="gp">In [318]: </span><span class="n">s1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">key</span><span class="o">=</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">())</span>
<span class="gh">Out[318]: </span>
<span class="go">1    a</span>
<span class="go">0    B</span>
<span class="go">2    C</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p><code>key</span></code> will be given the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</span></code></a> of values and should return a <code>Series</span></code> or array of the same shape with the transformed values. For <code>DataFrame</span></code> objects,
the key is applied per column, so the key should still expect a Series and return a Series, e.g.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell123"><span></span><span class="gp">In [319]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]})</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell124"><span></span><span class="gp">In [320]: </span><span class="n">df</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[320]: </span>
<span class="go">   a  b</span>
<span class="go">0  B  1</span>
<span class="go">2  C  3</span>
<span class="go">1  a  2</span>

<span class="gp">In [321]: </span><span class="n">df</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="s2">"a"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="k">lambda</span> <span class="n">col</span><span class="p">:</span> <span class="n">col</span><span class="o">.</span><span class="n">str</span><span class="o">.</span><span class="n">lower</span><span class="p">())</span>
<span class="gh">Out[321]: </span>
<span class="go">   a  b</span>
<span class="go">1  a  2</span>
<span class="go">0  B  1</span>
<span class="go">2  C  3</span>
</pre>
</div>
</div>

<p>The name or type of each column can be used to apply different functions to different columns.</p>

## <h3>By indexes and values</h3>

<p>Strings passed as the <code>by</span></code> parameter to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values" title="pandas.DataFrame.sort_values"><code>DataFrame.sort_values()</span></code></a> may
refer to either columns or index level names.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell125"><span></span><span class="go"># Build MultiIndex</span>
<span class="gp">In [322]: </span><span class="n">idx</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_tuples</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">[(</span><span class="s2">"a"</span><span class="p">,</span> <span class="mi">1</span><span class="p">),</span> <span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="mi">1</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="mi">1</span><span class="p">)]</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [323]: </span><span class="n">idx</span><span class="o">.</span><span class="n">names</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"first"</span><span class="p">,</span> <span class="s2">"second"</span><span class="p">]</span>

<span class="go"># Build DataFrame</span>
<span class="gp">In [324]: </span><span class="n">df_multi</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">6</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">)},</span> <span class="n">index</span><span class="o">=</span><span class="n">idx</span><span class="p">)</span>

<span class="gp">In [325]: </span><span class="n">df_multi</span>
<span class="gh">Out[325]: </span>
<span class="go">              A</span>
<span class="go">first second   </span>
<span class="go">a     1       6</span>
<span class="go">      2       5</span>
<span class="go">      2       4</span>
<span class="go">b     2       3</span>
<span class="go">      1       2</span>
<span class="go">      1       1</span>
</pre>
</div>
</div>

<p>Sort by ‘second’ (index) and ‘A’ (column)</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell126"><span></span><span class="gp">In [326]: </span><span class="n">df_multi</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="p">[</span><span class="s2">"second"</span><span class="p">,</span> <span class="s2">"A"</span><span class="p">])</span>
<span class="gh">Out[326]: </span>
<span class="go">              A</span>
<span class="go">first second   </span>
<span class="go">b     1       1</span>
<span class="go">      1       2</span>
<span class="go">a     1       6</span>
<span class="go">b     2       3</span>
<span class="go">a     2       4</span>
<span class="go">      2       5</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If a string matches both a column name and an index level name then a
warning is issued and the column takes precedence. This will result in an ambiguity error in a future version.</p>
</div>

## <h3>searchsorted</h3>

<p>Series has the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.searchsorted.html#pandas.Series.searchsorted" title="pandas.Series.searchsorted"><code>searchsorted()</span></code></a> method, which works similarly to <a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.searchsorted.html#numpy.ndarray.searchsorted" title="(in NumPy v2.3)"><code>numpy.ndarray.searchsorted()</span></code></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell127"><span></span><span class="gp">In [327]: </span><span class="n">ser</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>

<span class="gp">In [328]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>
<span class="gh">Out[328]: </span><span class="go">array([0, 2])</span>

<span class="gp">In [329]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">4</span><span class="p">])</span>
<span class="gh">Out[329]: </span><span class="go">array([0, 3])</span>

<span class="gp">In [330]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="n">side</span><span class="o">=</span><span class="s2">"right"</span><span class="p">)</span>
<span class="gh">Out[330]: </span><span class="go">array([1, 3])</span>

<span class="gp">In [331]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="n">side</span><span class="o">=</span><span class="s2">"left"</span><span class="p">)</span>
<span class="gh">Out[331]: </span><span class="go">array([0, 2])</span>

<span class="gp">In [332]: </span><span class="n">ser</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">3</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">])</span>

<span class="gp">In [333]: </span><span class="n">ser</span><span class="o">.</span><span class="n">searchsorted</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="n">sorter</span><span class="o">=</span><span class="n">np</span><span class="o">.</span><span class="n">argsort</span><span class="p">(</span><span class="n">ser</span><span class="p">))</span>
<span class="gh">Out[333]: </span><span class="go">array([0, 2])</span>
</pre>
</div>
</div>

## <h3>smallest / largest values</h3>

<p><code>Series</span></code> has the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.nsmallest.html#pandas.Series.nsmallest" title="pandas.Series.nsmallest"><code>nsmallest()</span></code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.nlargest.html#pandas.Series.nlargest" title="pandas.Series.nlargest"><code>nlargest()</span></code></a> methods which return the smallest or largest <span class="math notranslate nohighlight"><mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" tabindex="0" ctxtmenu_counter="0" style="font-size: 118.8%; position: relative;"><mjx-math class="MJX-TEX" aria-hidden="true"><mjx-mi class="mjx-i"><mjx-c class="mjx-c1D45B TEX-I"></mjx-c></mjx-mi></mjx-math><mjx-assistive-mml unselectable="on" display="inline"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>n</mi></math></mjx-assistive-mml></mjx-container></span> values. For a large <code>Series</span></code> this can be much
faster than sorting the entire Series and calling <code>head(n)</span></code> on the result.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell128"><span></span><span class="gp">In [334]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">permutation</span><span class="p">(</span><span class="mi">10</span><span class="p">))</span>

<span class="gp">In [335]: </span><span class="n">s</span>
<span class="gh">Out[335]: </span>
<span class="go">0    2</span>
<span class="go">1    0</span>
<span class="go">2    3</span>
<span class="go">3    7</span>
<span class="go">4    1</span>
<span class="go">5    5</span>
<span class="go">6    9</span>
<span class="go">7    6</span>
<span class="go">8    8</span>
<span class="go">9    4</span>
<span class="go">dtype: int64</span>

<span class="gp">In [336]: </span><span class="n">s</span><span class="o">.</span><span class="n">sort_values</span><span class="p">()</span>
<span class="gh">Out[336]: </span>
<span class="go">1    0</span>
<span class="go">4    1</span>
<span class="go">0    2</span>
<span class="go">2    3</span>
<span class="go">9    4</span>
<span class="go">5    5</span>
<span class="go">7    6</span>
<span class="go">3    7</span>
<span class="go">8    8</span>
<span class="go">6    9</span>
<span class="go">dtype: int64</span>

<span class="gp">In [337]: </span><span class="n">s</span><span class="o">.</span><span class="n">nsmallest</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
<span class="gh">Out[337]: </span>
<span class="go">1    0</span>
<span class="go">4    1</span>
<span class="go">0    2</span>
<span class="go">dtype: int64</span>

<span class="gp">In [338]: </span><span class="n">s</span><span class="o">.</span><span class="n">nlargest</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
<span class="gh">Out[338]: </span>
<span class="go">6    9</span>
<span class="go">8    8</span>
<span class="go">3    7</span>
<span class="go">dtype: int64</span>
</pre>
</div>
</div>

<p><code>DataFrame</span></code> also has the <code>nlargest</span></code> and <code>nsmallest</span></code> methods.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell129"><span></span><span class="gp">In [339]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span>
<span class="gp">   </span>        <span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="o">-</span><span class="mi">2</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">],</span>
<span class="gp">   </span>        <span class="s2">"b"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"abdceff"</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">4.0</span><span class="p">,</span> <span class="mf">3.2</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="mf">4.0</span><span class="p">],</span>
<span class="gp">   </span>    <span class="p">}</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [340]: </span><span class="n">df</span><span class="o">.</span><span class="n">nlargest</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[340]: </span>
<span class="go">    a  b    c</span>
<span class="go">5  11  f  3.0</span>
<span class="go">3  10  c  3.2</span>
<span class="go">4   8  e  NaN</span>

<span class="gp">In [341]: </span><span class="n">df</span><span class="o">.</span><span class="n">nlargest</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">])</span>
<span class="gh">Out[341]: </span>
<span class="go">    a  b    c</span>
<span class="go">5  11  f  3.0</span>
<span class="go">3  10  c  3.2</span>
<span class="go">4   8  e  NaN</span>
<span class="go">2   1  d  4.0</span>
<span class="go">6  -1  f  4.0</span>

<span class="gp">In [342]: </span><span class="n">df</span><span class="o">.</span><span class="n">nsmallest</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">)</span>
<span class="gh">Out[342]: </span>
<span class="go">   a  b    c</span>
<span class="go">0 -2  a  1.0</span>
<span class="go">1 -1  b  2.0</span>
<span class="go">6 -1  f  4.0</span>

<span class="gp">In [343]: </span><span class="n">df</span><span class="o">.</span><span class="n">nsmallest</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">])</span>
<span class="gh">Out[343]: </span>
<span class="go">   a  b    c</span>
<span class="go">0 -2  a  1.0</span>
<span class="go">1 -1  b  2.0</span>
<span class="go">6 -1  f  4.0</span>
<span class="go">2  1  d  4.0</span>
<span class="go">4  8  e  NaN</span>
</pre>
</div>
</div>

## <h3>Sorting by a MultiIndex column</h3>

<p>You must be explicit about sorting when the column is a MultiIndex, and fully specify
all levels to <code>by</span></code>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell130"><span></span><span class="gp">In [344]: </span><span class="n">df1</span><span class="o">.</span><span class="n">columns</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_tuples</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">[(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"one"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"b"</span><span class="p">,</span> <span class="s2">"three"</span><span class="p">)]</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [345]: </span><span class="n">df1</span><span class="o">.</span><span class="n">sort_values</span><span class="p">(</span><span class="n">by</span><span class="o">=</span><span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">))</span>
<span class="gh">Out[345]: </span>
<span class="go">    a         b</span>
<span class="go">  one two three</span>
<span class="go">0   2   1     5</span>
<span class="go">2   1   2     3</span>
<span class="go">1   1   3     4</span>
<span class="go">3   1   4     2</span>
</pre>
</div>
</div>

# <h2>Copying</h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html#pandas.DataFrame.copy" title="pandas.DataFrame.copy"><code>copy()</span></code></a> method on pandas objects copies the underlying data (though not the axis indexes, since they are immutable) and returns a new object. Note that <strong>it is seldom necessary to copy objects</strong>. For example, there are only a handful of ways to alter a DataFrame <em>in-place</em>:</p>

<ul>
<li><p>Inserting, deleting, or modifying a column.</p></li>
<li><p>Assigning to the <code>index</span></code> or <code>columns</span></code> attributes.</p></li>
<li><p>For homogeneous data, directly modifying the values via the <code>values</span></code>
attribute or advanced indexing.</p></li>
</ul>

<p>To be clear, no pandas method has the side effect of modifying your data; almost every method returns a new object, leaving the original object untouched. If the data is modified, it is because you did so explicitly.</p>

# <h2>dtypes</h2>

<p>For the most part, pandas uses NumPy arrays and dtypes for Series or individual columns of a DataFrame. NumPy provides support for <code>float</span></code>, <code>int</span></code>, <code>bool</span></code>, <code>timedelta64[ns]</span></code> and <code>datetime64[ns]</span></code> (note that NumPy does not support timezone-aware datetimes).</p>

<p>pandas and third-party libraries <em>extend</em> NumPy’s type system in a few places.
This section describes the extensions pandas has made internally.
See <a href="https://pandas.pydata.org/docs/development/extending.html#extending-extension-types">Extension types</span></a> for how to write your own extension that works with pandas. See <a href="https://pandas.pydata.org/community/ecosystem.html">the ecosystem page</a> for a list of third-party libraries that have implemented an extension.</p>
<p>The following table lists all of pandas extension types.
For methods requiring <code>dtype</span></code> arguments, strings can be specified as indicated. See the respective
documentation sections for more on each type.</p>

<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>Kind of Data</p></th>
<th class="head" colspan="2"><p>Data Type</p></th>
<th class="head" colspan="2"><p>Scalar</p></th>
<th class="head"><p>Array</p></th>
<th class="head"><p>String Aliases</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><a href="timeseries.html#timeseries-timezone">tz-aware datetime</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.DatetimeTZDtype.html#pandas.DatetimeTZDtype" title="pandas.DatetimeTZDtype"><code>DatetimeTZDtype</span></code></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Timestamp.html#pandas.Timestamp" title="pandas.Timestamp"><code>Timestamp</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.DatetimeArray.html#pandas.arrays.DatetimeArray" title="pandas.arrays.DatetimeArray"><code>arrays.DatetimeArray</span></code></a></p></td>
<td><p><code>'datetime64[ns,</span> &lt;tz&gt;]'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="categorical.html#categorical">Categorical</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.CategoricalDtype.html#pandas.CategoricalDtype" title="pandas.CategoricalDtype"><code>CategoricalDtype</span></code></a></p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.Categorical.html#pandas.Categorical" title="pandas.Categorical"><code>Categorical</span></code></a></p></td>
<td><p><code>'category'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="timeseries.html#timeseries-periods">period (time spans)</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.PeriodDtype.html#pandas.PeriodDtype" title="pandas.PeriodDtype"><code>PeriodDtype</span></code></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Period.html#pandas.Period" title="pandas.Period"><code>Period</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.PeriodArray.html#pandas.arrays.PeriodArray" title="pandas.arrays.PeriodArray"><code>arrays.PeriodArray</span></code></a>
<code>'Period[&lt;freq&gt;]'</span></code></p></td>
<td><p><code>'period[&lt;freq&gt;]'</span></code>,</p></td>
</tr>
<tr class="row-odd"><td><p><a href="sparse.html#sparse">sparse</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.SparseDtype.html#pandas.SparseDtype" title="pandas.SparseDtype"><code>SparseDtype</span></code></a></p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.arrays.SparseArray.html#pandas.arrays.SparseArray" title="pandas.arrays.SparseArray"><code>arrays.SparseArray</span></code></a></p></td>
<td><p><code>'Sparse'</span></code>, <code>'Sparse[int]'</span></code>,
<code>'Sparse[float]'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="advanced.html#advanced-intervalindex">intervals</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.IntervalDtype.html#pandas.IntervalDtype" title="pandas.IntervalDtype"><code>IntervalDtype</span></code></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Interval.html#pandas.Interval" title="pandas.Interval"><code>Interval</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.IntervalArray.html#pandas.arrays.IntervalArray" title="pandas.arrays.IntervalArray"><code>arrays.IntervalArray</span></code></a></p></td>
<td><p><code>'interval'</span></code>, <code>'Interval'</span></code>,
<code>'Interval[&lt;numpy_dtype&gt;]'</span></code>,
<code>'Interval[datetime64[ns,</span> &lt;tz&gt;]]'</span></code>,
<code>'Interval[timedelta64[&lt;freq&gt;]]'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="integer_na.html#integer-na">nullable integer</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Int64Dtype.html#pandas.Int64Dtype" title="pandas.Int64Dtype"><code>Int64Dtype</span></code></a>, …</p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.arrays.IntegerArray.html#pandas.arrays.IntegerArray" title="pandas.arrays.IntegerArray"><code>arrays.IntegerArray</span></code></a></p></td>
<td><p><code>'Int8'</span></code>, <code>'Int16'</span></code>, <code>'Int32'</span></code>,
<code>'Int64'</span></code>, <code>'UInt8'</span></code>, <code>'UInt16'</span></code>,
<code>'UInt32'</span></code>, <code>'UInt64'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="../reference/arrays.html#api-arrays-float-na">nullable float</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.Float64Dtype.html#pandas.Float64Dtype" title="pandas.Float64Dtype"><code>Float64Dtype</span></code></a>, …</p></td>
<td colspan="2"><p>(none)</p></td>
<td><p><a href="../reference/api/pandas.arrays.FloatingArray.html#pandas.arrays.FloatingArray" title="pandas.arrays.FloatingArray"><code>arrays.FloatingArray</span></code></a></p></td>
<td><p><code>'Float32'</span></code>, <code>'Float64'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><a href="text.html#text">Strings</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a></p></td>
<td colspan="2"><p><a href="https://docs.python.org/3/library/stdtypes.html#str" title="(in Python v3.13)"><code>str</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.StringArray.html#pandas.arrays.StringArray" title="pandas.arrays.StringArray"><code>arrays.StringArray</span></code></a></p></td>
<td><p><code>'string'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><a href="../reference/arrays.html#api-arrays-bool">Boolean (with NA)</span></a></p></td>
<td colspan="2"><p><a href="../reference/api/pandas.BooleanDtype.html#pandas.BooleanDtype" title="pandas.BooleanDtype"><code>BooleanDtype</span></code></a></p></td>
<td colspan="2"><p><a href="https://docs.python.org/3/library/functions.html#bool" title="(in Python v3.13)"><code>bool</span></code></a></p></td>
<td><p><a href="../reference/api/pandas.arrays.BooleanArray.html#pandas.arrays.BooleanArray" title="pandas.arrays.BooleanArray"><code>arrays.BooleanArray</span></code></a></p></td>
<td><p><code>'boolean'</span></code></p></td>
</tr>
</tbody>
</table>
<p>pandas has two ways to store strings.</p>
<ol>
<li><p><code>object</span></code> dtype, which can hold any Python object, including strings.</p></li>
<li><p><a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a>, which is dedicated to strings.</p></li>
</ol>

<p>Generally, we recommend using <a href="../reference/api/pandas.StringDtype.html#pandas.StringDtype" title="pandas.StringDtype"><code>StringDtype</span></code></a>. See <a href="text.html#text-types">Text data types</span></a> for more.</p>
<p>Finally, arbitrary objects may be stored using the <code>object</span></code> dtype, but should be avoided to the extent possible (for performance and interoperability with other libraries and methods.
See <a href="#basics-object-conversion">object conversion</span></a>).</p>

<p>A convenient <a href="../reference/api/pandas.DataFrame.dtypes.html#pandas.DataFrame.dtypes" title="pandas.DataFrame.dtypes"><code>dtypes</span></code></a> attribute for DataFrame returns a Series with the data type of each column.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell131"><span></span><span class="gp">In [346]: </span><span class="n">dft</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span>
<span class="gp">   </span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">rand</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"B"</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span>
<span class="gp">   </span>        <span class="s2">"C"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span>
<span class="gp">   </span>        <span class="s2">"D"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timestamp</span><span class="p">(</span><span class="s2">"20010102"</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"E"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mf">1.0</span><span class="p">]</span> <span class="o">*</span> <span class="mi">3</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"float32"</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"F"</span><span class="p">:</span> <span class="kc">False</span><span class="p">,</span>
<span class="gp">   </span>        <span class="s2">"G"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">]</span> <span class="o">*</span> <span class="mi">3</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"int8"</span><span class="p">),</span>
<span class="gp">   </span>    <span class="p">}</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [347]: </span><span class="n">dft</span>
<span class="gh">Out[347]: </span>
<span class="go">          A  B    C          D    E      F  G</span>
<span class="go">0  0.035962  1  foo 2001-01-02  1.0  False  1</span>
<span class="go">1  0.701379  1  foo 2001-01-02  1.0  False  1</span>
<span class="go">2  0.281885  1  foo 2001-01-02  1.0  False  1</span>

<span class="gp">In [348]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[348]: </span>
<span class="go">A          float64</span>
<span class="go">B            int64</span>
<span class="go">C           object</span>
<span class="go">D    datetime64[s]</span>
<span class="go">E          float32</span>
<span class="go">F             bool</span>
<span class="go">G             int8</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
<p>On a <code>Series</span></code> object, use the <a href="../reference/api/pandas.Series.dtype.html#pandas.Series.dtype" title="pandas.Series.dtype"><code>dtype</span></code></a> attribute.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell132"><span></span><span class="gp">In [349]: </span><span class="n">dft</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[349]: </span><span class="go">dtype('float64')</span>
</pre>
</div>
</div>

<p>If a pandas object contains data with multiple dtypes <em>in a single column</em>, the dtype of the column will be chosen to accommodate all of the data types (<code>object</span></code> is the most general).</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell133"><span></span><span class="go"># these ints are coerced to floats</span>
<span class="gp">In [350]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mf">6.0</span><span class="p">])</span>
<span class="gh">Out[350]: </span>
<span class="go">0    1.0</span>
<span class="go">1    2.0</span>
<span class="go">2    3.0</span>
<span class="go">3    4.0</span>
<span class="go">4    5.0</span>
<span class="go">5    6.0</span>
<span class="go">dtype: float64</span>

<span class="go"># string data forces an ``object`` dtype</span>
<span class="gp">In [351]: </span><span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mf">6.0</span><span class="p">,</span> <span class="s2">"foo"</span><span class="p">])</span>
<span class="gh">Out[351]: </span>
<span class="go">0      1</span>
<span class="go">1      2</span>
<span class="go">2      3</span>
<span class="go">3    6.0</span>
<span class="go">4    foo</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>The number of columns of each type in a <code>DataFrame</span></code> can be found by calling <code>DataFrame.dtypes.value_counts()</span></code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell134"><span></span><span class="gp">In [352]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span><span class="o">.</span><span class="n">value_counts</span><span class="p">()</span>
<span class="gh">Out[352]: </span>
<span class="go">float64          1</span>
<span class="go">int64            1</span>
<span class="go">object           1</span>
<span class="go">datetime64[s]    1</span>
<span class="go">float32          1</span>
<span class="go">bool             1</span>
<span class="go">int8             1</span>
<span class="go">Name: count, dtype: int64</span>
</pre>
</div>
</div>

<p>Numeric dtypes will propagate and can coexist in DataFrames.
If a dtype is passed (either directly via the <code>dtype</span></code> keyword, a passed <code>ndarray</span></code>, or a passed <code>Series</span></code>), then it will be preserved in DataFrame operations. Furthermore, different numeric dtypes will <strong>NOT</strong> be combined. The following example will give you a taste.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell135"><span></span><span class="gp">In [353]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">,</span> <span class="mi">1</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">],</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float32"</span><span class="p">)</span>

<span class="gp">In [354]: </span><span class="n">df1</span>
<span class="gh">Out[354]: </span>
<span class="go">          A</span>
<span class="go">0  0.224364</span>
<span class="go">1  1.890546</span>
<span class="go">2  0.182879</span>
<span class="go">3  0.787847</span>
<span class="go">4 -0.188449</span>
<span class="go">5  0.667715</span>
<span class="go">6 -0.011736</span>
<span class="go">7 -0.399073</span>

<span class="gp">In [355]: </span><span class="n">df1</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[355]: </span>
<span class="go">A    float32</span>
<span class="go">dtype: object</span>

<span class="gp">In [356]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span>
<span class="gp">   </span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">),</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float16"</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"B"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">)),</span>
<span class="gp">   </span>        <span class="s2">"C"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randint</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">255</span><span class="p">,</span> <span class="n">size</span><span class="o">=</span><span class="mi">8</span><span class="p">),</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"uint8"</span><span class="p">),</span>  <span class="c1"># [0,255] (range of uint8)</span>
<span class="gp">   </span>    <span class="p">}</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [357]: </span><span class="n">df2</span>
<span class="gh">Out[357]: </span>
<span class="go">          A         B    C</span>
<span class="go">0  0.823242  0.256090   26</span>
<span class="go">1  1.607422  1.426469   86</span>
<span class="go">2 -0.333740 -0.416203   46</span>
<span class="go">3 -0.063477  1.139976  212</span>
<span class="go">4 -1.014648 -1.193477   26</span>
<span class="go">5  0.678711  0.096706    7</span>
<span class="go">6 -0.040863 -1.956850  184</span>
<span class="go">7 -0.357422 -0.714337  206</span>

<span class="gp">In [358]: </span><span class="n">df2</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[358]: </span>
<span class="go">A    float16</span>
<span class="go">B    float64</span>
<span class="go">C      uint8</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

## <h3>defaults</h3>

<p>By default integer types are <code>int64</span></code> and float types are <code>float64</span></code>, <em>regardless</em> of platform (32-bit or 64-bit).
The following will all result in <code>int64</span></code> dtypes.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell136"><span></span><span class="gp">In [359]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">])</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[359]: </span>
<span class="go">a    int64</span>
<span class="go">dtype: object</span>

<span class="gp">In [360]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]})</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[360]: </span>
<span class="go">a    int64</span>
<span class="go">dtype: object</span>

<span class="gp">In [361]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="mi">1</span><span class="p">},</span> <span class="n">index</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">2</span><span class="p">)))</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[361]: </span>
<span class="go">a    int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Note that Numpy will choose <em>platform-dependent</em> types when creating arrays.
The following <strong>WILL</strong> result in <code>int32</span></code> on 32-bit platform.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell137"><span></span><span class="gp">In [362]: </span><span class="n">frame</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]))</span>
</pre>
</div>
</div>
</section>
<section id="upcasting">

## <h3>upcasting</h3>

<p>Types can potentially be <em>upcasted</em> when combined with other types, meaning they are promoted
from the current type (e.g. <code>int</span></code> to <code>float</span></code>).</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell138"><span></span><span class="gp">In [363]: </span><span class="n">df3</span> <span class="o">=</span> <span class="n">df1</span><span class="o">.</span><span class="n">reindex_like</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span><span class="o">.</span><span class="n">fillna</span><span class="p">(</span><span class="n">value</span><span class="o">=</span><span class="mf">0.0</span><span class="p">)</span> <span class="o">+</span> <span class="n">df2</span>

<span class="gp">In [364]: </span><span class="n">df3</span>
<span class="gh">Out[364]: </span>
<span class="go">          A         B      C</span>
<span class="go">0  1.047606  0.256090   26.0</span>
<span class="go">1  3.497968  1.426469   86.0</span>
<span class="go">2 -0.150862 -0.416203   46.0</span>
<span class="go">3  0.724370  1.139976  212.0</span>
<span class="go">4 -1.203098 -1.193477   26.0</span>
<span class="go">5  1.346426  0.096706    7.0</span>
<span class="go">6 -0.052599 -1.956850  184.0</span>
<span class="go">7 -0.756495 -0.714337  206.0</span>

<span class="gp">In [365]: </span><span class="n">df3</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[365]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy" title="pandas.DataFrame.to_numpy"><code>DataFrame.to_numpy()</span></code></a> will return the <em>lower-common-denominator</em> of the dtypes, meaning
the dtype that can accommodate <strong>ALL</strong> of the types in the resulting homogeneous dtyped NumPy array. This can
force some <em>upcasting</em>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell139"><span></span><span class="gp">In [366]: </span><span class="n">df3</span><span class="o">.</span><span class="n">to_numpy</span><span class="p">()</span><span class="o">.</span><span class="n">dtype</span>
<span class="gh">Out[366]: </span><span class="go">dtype('float64')</span>
</pre>
</div>
</div>

## <h3>astype</h3>

<p id="basics-cast">You can use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a> method to explicitly convert dtypes from one to another. These will by default return a copy, even if the dtype was unchanged (pass <code>copy=False</span></code> to change this behavior). In addition, they will raise an exception if the astype operation is invalid.</p>

<p>Upcasting is always according to the <strong>NumPy</strong> rules. If two different dtypes are involved in an operation,
then the more <em>general</em> one will be used as the result of the operation.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell140"><span></span><span class="gp">In [367]: </span><span class="n">df3</span>
<span class="gh">Out[367]: </span>
<span class="go">          A         B      C</span>
<span class="go">0  1.047606  0.256090   26.0</span>
<span class="go">1  3.497968  1.426469   86.0</span>
<span class="go">2 -0.150862 -0.416203   46.0</span>
<span class="go">3  0.724370  1.139976  212.0</span>
<span class="go">4 -1.203098 -1.193477   26.0</span>
<span class="go">5  1.346426  0.096706    7.0</span>
<span class="go">6 -0.052599 -1.956850  184.0</span>
<span class="go">7 -0.756495 -0.714337  206.0</span>

<span class="gp">In [368]: </span><span class="n">df3</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[368]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>

<span class="go"># conversion of dtypes</span>
<span class="gp">In [369]: </span><span class="n">df3</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"float32"</span><span class="p">)</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[369]: </span>
<span class="go">A    float32</span>
<span class="go">B    float32</span>
<span class="go">C    float32</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Convert a subset of columns to a specified type using <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell141"><span></span><span class="gp">In [370]: </span><span class="n">dft</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">]})</span>

<span class="gp">In [371]: </span><span class="n">dft</span><span class="p">[[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span> <span class="o">=</span> <span class="n">dft</span><span class="p">[[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">uint8</span><span class="p">)</span>

<span class="gp">In [372]: </span><span class="n">dft</span>
<span class="gh">Out[372]: </span>
<span class="go">   a  b  c</span>
<span class="go">0  1  4  7</span>
<span class="go">1  2  5  8</span>
<span class="go">2  3  6  9</span>

<span class="gp">In [373]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[373]: </span>
<span class="go">a    uint8</span>
<span class="go">b    uint8</span>
<span class="go">c    int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Convert certain columns to a specific dtype by passing a dict to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell142"><span></span><span class="gp">In [374]: </span><span class="n">dft1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">]})</span>

<span class="gp">In [375]: </span><span class="n">dft1</span> <span class="o">=</span> <span class="n">dft1</span><span class="o">.</span><span class="n">astype</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">bool_</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">float64</span><span class="p">})</span>

<span class="gp">In [376]: </span><span class="n">dft1</span>
<span class="gh">Out[376]: </span>
<span class="go">       a  b    c</span>
<span class="go">0   True  4  7.0</span>
<span class="go">1  False  5  8.0</span>
<span class="go">2   True  6  9.0</span>

<span class="gp">In [377]: </span><span class="n">dft1</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[377]: </span>
<span class="go">a       bool</span>
<span class="go">b      int64</span>
<span class="go">c    float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>

<p>When trying to convert a subset of columns to a specified type using <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html#pandas.DataFrame.astype" title="pandas.DataFrame.astype"><code>astype()</span></code></a>  and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc" title="pandas.DataFrame.loc"><code>loc()</span></code></a>, upcasting occurs.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc" title="pandas.DataFrame.loc"><code>loc()</span></code></a> tries to fit in what we are assigning to the current dtypes, while <code>[]</span></code> will overwrite them taking the dtype from the right hand side. Therefore the following piece of code produces the unintended result.</p>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell143"><span></span><span class="gp">In [378]: </span><span class="n">dft</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"c"</span><span class="p">:</span> <span class="p">[</span><span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">]})</span>

<span class="gp">In [379]: </span><span class="n">dft</span><span class="o">.</span><span class="n">loc</span><span class="p">[:,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">uint8</span><span class="p">)</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[379]: </span>
<span class="go">a    uint8</span>
<span class="go">b    uint8</span>
<span class="go">dtype: object</span>

<span class="gp">In [380]: </span><span class="n">dft</span><span class="o">.</span><span class="n">loc</span><span class="p">[:,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span> <span class="o">=</span> <span class="n">dft</span><span class="o">.</span><span class="n">loc</span><span class="p">[:,</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">]]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">uint8</span><span class="p">)</span>

<span class="gp">In [381]: </span><span class="n">dft</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[381]: </span>
<span class="go">a    int64</span>
<span class="go">b    int64</span>
<span class="go">c    int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

## <h3>object conversion</h3>

<p>pandas offers various functions to try to force conversion of types from the <code>object</span></code> dtype to other types.
In cases where the data is already of the correct type, but stored in an <code>object</span></code> array, the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.infer_objects.html#pandas.DataFrame.infer_objects" title="pandas.DataFrame.infer_objects"><code>DataFrame.infer_objects()</span></code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.infer_objects.html#pandas.Series.infer_objects" title="pandas.Series.infer_objects"><code>Series.infer_objects()</span></code></a> methods can be used to soft convert to the correct type.</p>

<blockquote>
<div><div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell144"><span></span><span class="gp">In [382]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [383]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">[</span>
<span class="gp">   </span>        <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span>
<span class="gp">   </span>        <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span>
<span class="gp">   </span>        <span class="p">[</span><span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)],</span>
<span class="gp">   </span>    <span class="p">]</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [384]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">T</span>

<span class="gp">In [385]: </span><span class="n">df</span>
<span class="gh">Out[385]: </span>
<span class="go">   0  1                    2</span>
<span class="go">0  1  a  2016-03-02 00:00:00</span>
<span class="go">1  2  b  2016-03-02 00:00:00</span>

<span class="gp">In [386]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[386]: </span>
<span class="go">0    object</span>
<span class="go">1    object</span>
<span class="go">2    object</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
</div></blockquote>

<p>Because the data was transposed the original inference stored all columns as object, which <code>infer_objects</span></code> will correct.</p>

<blockquote>
<div><div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell145"><span></span><span class="gp">In [387]: </span><span class="n">df</span><span class="o">.</span><span class="n">infer_objects</span><span class="p">()</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[387]: </span>
<span class="go">0             int64</span>
<span class="go">1            object</span>
<span class="go">2    datetime64[ns]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>
</div></blockquote>

<p>The following functions are available for one dimensional object arrays or scalars to perform hard conversion of objects to a specified type:</p>

<ul>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html#pandas.to_numeric" title="pandas.to_numeric"><code>to_numeric()</span></code></a> (conversion to numeric dtypes)</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell146"><span></span><span class="gp">In [388]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"1.1"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>

<span class="gp">In [389]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">)</span>
<span class="gh">Out[389]: </span><span class="go">array([1.1, 2. , 3. ])</span>
</pre>
</div>
</div>
</li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html#pandas.to_datetime" title="pandas.to_datetime"><code>to_datetime()</span></code></a> (conversion to datetime objects)</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell147"><span></span><span class="gp">In [390]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [391]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"2016-07-09"</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)]</span>

<span class="gp">In [392]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">(</span><span class="n">m</span><span class="p">)</span>
<span class="gh">Out[392]: </span><span class="go">DatetimeIndex(['2016-07-09', '2016-03-02'], dtype='datetime64[ns]', freq=None)</span>
</pre>
</div>
</div>
</li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.to_timedelta.html#pandas.to_timedelta" title="pandas.to_timedelta"><code>to_timedelta()</span></code></a> (conversion to timedelta objects)</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell148"><span></span><span class="gp">In [393]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"5us"</span><span class="p">,</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"1day"</span><span class="p">)]</span>

<span class="gp">In [394]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_timedelta</span><span class="p">(</span><span class="n">m</span><span class="p">)</span>
<span class="gh">Out[394]: </span><span class="go">TimedeltaIndex(['0 days 00:00:00.000005', '1 days 00:00:00'], dtype='timedelta64[ns]', freq=None)</span>
</pre>
</div>
</div>
</li>
</ul>

<p>To force a conversion, we can pass in an <code>errors</span></code> argument, which specifies how pandas should deal with elements that cannot be converted to desired dtype or object. By default, <code>errors='raise'</span></code>, meaning that any errors encountered
will be raised during the conversion process. However, if <code>errors='coerce'</span></code>, these errors will be ignored and pandas will convert problematic elements to <code>pd.NaT</span></code> (for datetime and timedelta) or <code>np.nan</span></code> (for numeric). This might be useful if you are reading in data which is mostly of the desired dtype (e.g. numeric, datetime), but occasionally has non-conforming elements intermixed that you want to represent as missing:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell149"><span></span><span class="gp">In [395]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [396]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"apple"</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)]</span>

<span class="gp">In [397]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">errors</span><span class="o">=</span><span class="s2">"coerce"</span><span class="p">)</span>
<span class="gh">Out[397]: </span><span class="go">DatetimeIndex(['NaT', '2016-03-02'], dtype='datetime64[ns]', freq=None)</span>

<span class="gp">In [398]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"apple"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>

<span class="gp">In [399]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">errors</span><span class="o">=</span><span class="s2">"coerce"</span><span class="p">)</span>
<span class="gh">Out[399]: </span><span class="go">array([nan,  2.,  3.])</span>

<span class="gp">In [400]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"apple"</span><span class="p">,</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"1day"</span><span class="p">)]</span>

<span class="gp">In [401]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_timedelta</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">errors</span><span class="o">=</span><span class="s2">"coerce"</span><span class="p">)</span>
<span class="gh">Out[401]: </span><span class="go">TimedeltaIndex([NaT, '1 days'], dtype='timedelta64[ns]', freq=None)</span>
</pre>
</div>
</div>

<p>In addition to object conversion, <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html#pandas.to_numeric" title="pandas.to_numeric"><code>to_numeric()</span></code></a> provides another argument <code>downcast</span></code>, which gives the
option of downcasting the newly (or already) numeric data to a smaller dtype, which can conserve memory:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell150"><span></span><span class="gp">In [402]: </span><span class="n">m</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"1"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>

<span class="gp">In [403]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"integer"</span><span class="p">)</span>  <span class="c1"># smallest signed int dtype</span>
<span class="gh">Out[403]: </span><span class="go">array([1, 2, 3], dtype=int8)</span>

<span class="gp">In [404]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"signed"</span><span class="p">)</span>  <span class="c1"># same as 'integer'</span>
<span class="gh">Out[404]: </span><span class="go">array([1, 2, 3], dtype=int8)</span>

<span class="gp">In [405]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"unsigned"</span><span class="p">)</span>  <span class="c1"># smallest unsigned int dtype</span>
<span class="gh">Out[405]: </span><span class="go">array([1, 2, 3], dtype=uint8)</span>

<span class="gp">In [406]: </span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">(</span><span class="n">m</span><span class="p">,</span> <span class="n">downcast</span><span class="o">=</span><span class="s2">"float"</span><span class="p">)</span>  <span class="c1"># smallest float dtype</span>
<span class="gh">Out[406]: </span><span class="go">array([1., 2., 3.], dtype=float32)</span>
</pre>
</div>
</div>
<p>As these methods apply only to one-dimensional arrays, lists or scalars; they cannot be used directly on multi-dimensional objects such
as DataFrames. However, with <a href="../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply" title="pandas.DataFrame.apply"><code>apply()</span></code></a>, we can “apply” the function over each column efficiently:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell151"><span></span><span class="gp">In [407]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [408]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="s2">"2016-07-09"</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2016</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">)]]</span> <span class="o">*</span> <span class="mi">2</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"O"</span><span class="p">)</span>

<span class="gp">In [409]: </span><span class="n">df</span>
<span class="gh">Out[409]: </span>
<span class="go">            0                    1</span>
<span class="go">0  2016-07-09  2016-03-02 00:00:00</span>
<span class="go">1  2016-07-09  2016-03-02 00:00:00</span>

<span class="gp">In [410]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">)</span>
<span class="gh">Out[410]: </span>
<span class="go">           0          1</span>
<span class="go">0 2016-07-09 2016-03-02</span>
<span class="go">1 2016-07-09 2016-03-02</span>

<span class="gp">In [411]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="s2">"1.1"</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]]</span> <span class="o">*</span> <span class="mi">2</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"O"</span><span class="p">)</span>

<span class="gp">In [412]: </span><span class="n">df</span>
<span class="gh">Out[412]: </span>
<span class="go">     0  1  2</span>
<span class="go">0  1.1  2  3</span>
<span class="go">1  1.1  2  3</span>

<span class="gp">In [413]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">to_numeric</span><span class="p">)</span>
<span class="gh">Out[413]: </span>
<span class="go">     0  1  2</span>
<span class="go">0  1.1  2  3</span>
<span class="go">1  1.1  2  3</span>

<span class="gp">In [414]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="s2">"5us"</span><span class="p">,</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"1day"</span><span class="p">)]]</span> <span class="o">*</span> <span class="mi">2</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"O"</span><span class="p">)</span>

<span class="gp">In [415]: </span><span class="n">df</span>
<span class="gh">Out[415]: </span>
<span class="go">     0                1</span>
<span class="go">0  5us  1 days 00:00:00</span>
<span class="go">1  5us  1 days 00:00:00</span>

<span class="gp">In [416]: </span><span class="n">df</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">to_timedelta</span><span class="p">)</span>
<span class="gh">Out[416]: </span>
<span class="go">                       0      1</span>
<span class="go">0 0 days 00:00:00.000005 1 days</span>
<span class="go">1 0 days 00:00:00.000005 1 days</span>
</pre>
</div>
</div>

## <h3>gotchas</h3>

<p>Performing selection operations on <code>integer</span></code> type data can easily upcast the data to <code>floating</span></code>.
The dtype of the input data will be preserved in cases where <code>nans</span></code> are not introduced.
See also <a href="gotchas.html#gotchas-intna">Support for integer NA</span></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell152"><span></span><span class="gp">In [417]: </span><span class="n">dfi</span> <span class="o">=</span> <span class="n">df3</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"int32"</span><span class="p">)</span>

<span class="gp">In [418]: </span><span class="n">dfi</span><span class="p">[</span><span class="s2">"E"</span><span class="p">]</span> <span class="o">=</span> <span class="mi">1</span>

<span class="gp">In [419]: </span><span class="n">dfi</span>
<span class="gh">Out[419]: </span>
<span class="go">   A  B    C  E</span>
<span class="go">0  1  0   26  1</span>
<span class="go">1  3  1   86  1</span>
<span class="go">2  0  0   46  1</span>
<span class="go">3  0  1  212  1</span>
<span class="go">4 -1 -1   26  1</span>
<span class="go">5  1  0    7  1</span>
<span class="go">6  0 -1  184  1</span>
<span class="go">7  0  0  206  1</span>

<span class="gp">In [420]: </span><span class="n">dfi</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[420]: </span>
<span class="go">A    int32</span>
<span class="go">B    int32</span>
<span class="go">C    int32</span>
<span class="go">E    int64</span>
<span class="go">dtype: object</span>

<span class="gp">In [421]: </span><span class="n">casted</span> <span class="o">=</span> <span class="n">dfi</span><span class="p">[</span><span class="n">dfi</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">]</span>

<span class="gp">In [422]: </span><span class="n">casted</span>
<span class="gh">Out[422]: </span>
<span class="go">     A    B    C  E</span>
<span class="go">0  1.0  NaN   26  1</span>
<span class="go">1  3.0  1.0   86  1</span>
<span class="go">2  NaN  NaN   46  1</span>
<span class="go">3  NaN  1.0  212  1</span>
<span class="go">4  NaN  NaN   26  1</span>
<span class="go">5  1.0  NaN    7  1</span>
<span class="go">6  NaN  NaN  184  1</span>
<span class="go">7  NaN  NaN  206  1</span>

<span class="gp">In [423]: </span><span class="n">casted</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[423]: </span>
<span class="go">A    float64</span>
<span class="go">B    float64</span>
<span class="go">C      int32</span>
<span class="go">E      int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>While float dtypes are unchanged.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell153"><span></span><span class="gp">In [424]: </span><span class="n">dfa</span> <span class="o">=</span> <span class="n">df3</span><span class="o">.</span><span class="n">copy</span><span class="p">()</span>

<span class="gp">In [425]: </span><span class="n">dfa</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span> <span class="o">=</span> <span class="n">dfa</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"float32"</span><span class="p">)</span>

<span class="gp">In [426]: </span><span class="n">dfa</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[426]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>

<span class="gp">In [427]: </span><span class="n">casted</span> <span class="o">=</span> <span class="n">dfa</span><span class="p">[</span><span class="n">df2</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">]</span>

<span class="gp">In [428]: </span><span class="n">casted</span>
<span class="gh">Out[428]: </span>
<span class="go">          A         B      C</span>
<span class="go">0  1.047606  0.256090   26.0</span>
<span class="go">1  3.497968  1.426469   86.0</span>
<span class="go">2       NaN       NaN   46.0</span>
<span class="go">3       NaN  1.139976  212.0</span>
<span class="go">4       NaN       NaN   26.0</span>
<span class="go">5  1.346426  0.096706    7.0</span>
<span class="go">6       NaN       NaN  184.0</span>
<span class="go">7       NaN       NaN  206.0</span>

<span class="gp">In [429]: </span><span class="n">casted</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[429]: </span>
<span class="go">A    float32</span>
<span class="go">B    float64</span>
<span class="go">C    float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

# <h2>Selecting columns based on <code>dtype</code></h2>

<p id="basics-selectdtypes">The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</span></code></a> method implements subsetting of columns based on their <code>dtype</span></code>.</p>

<p>First, let’s create a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> with a slew of different
dtypes:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell154"><span></span><span class="gp">In [430]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   </span>    <span class="p">{</span>
<span class="gp">   </span>        <span class="s2">"string"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"int64"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">4</span><span class="p">)),</span>
<span class="gp">   </span>        <span class="s2">"uint8"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"u1"</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"float64"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mf">4.0</span><span class="p">,</span> <span class="mf">7.0</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"bool1"</span><span class="p">:</span> <span class="p">[</span><span class="kc">True</span><span class="p">,</span> <span class="kc">False</span><span class="p">,</span> <span class="kc">True</span><span class="p">],</span>
<span class="gp">   </span>        <span class="s2">"bool2"</span><span class="p">:</span> <span class="p">[</span><span class="kc">False</span><span class="p">,</span> <span class="kc">True</span><span class="p">,</span> <span class="kc">False</span><span class="p">],</span>
<span class="gp">   </span>        <span class="s2">"dates"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"now"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">),</span>
<span class="gp">   </span>        <span class="s2">"category"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="s2">"ABC"</span><span class="p">))</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"category"</span><span class="p">),</span>
<span class="gp">   </span>    <span class="p">}</span>
<span class="gp">   </span><span class="p">)</span>
<span class="gp">   </span>

<span class="gp">In [431]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"tdeltas"</span><span class="p">]</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">dates</span><span class="o">.</span><span class="n">diff</span><span class="p">()</span>

<span class="gp">In [432]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"uint64"</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"u8"</span><span class="p">)</span>

<span class="gp">In [433]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"other_dates"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>

<span class="gp">In [434]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"tz_aware_dates"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">,</span> <span class="n">tz</span><span class="o">=</span><span class="s2">"US/Eastern"</span><span class="p">)</span>

<span class="gp">In [435]: </span><span class="n">df</span>
<span class="gh">Out[435]: </span>
<span class="go">  string  int64  uint8  ...  uint64  other_dates            tz_aware_dates</span>
<span class="go">0      a      1      3  ...       3   2013-01-01 2013-01-01 00:00:00-05:00</span>
<span class="go">1      b      2      4  ...       4   2013-01-02 2013-01-02 00:00:00-05:00</span>
<span class="go">2      c      3      5  ...       5   2013-01-03 2013-01-03 00:00:00-05:00</span>

<span class="go">[3 rows x 12 columns]</span>
</pre>
</div>
</div>

<p>And the dtypes:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell155"><span></span><span class="gp">In [436]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[436]: </span>
<span class="go">string                                object</span>
<span class="go">int64                                  int64</span>
<span class="go">uint8                                  uint8</span>
<span class="go">float64                              float64</span>
<span class="go">bool1                                   bool</span>
<span class="go">bool2                                   bool</span>
<span class="go">dates                         datetime64[ns]</span>
<span class="go">category                            category</span>
<span class="go">tdeltas                      timedelta64[ns]</span>
<span class="go">uint64                                uint64</span>
<span class="go">other_dates                   datetime64[ns]</span>
<span class="go">tz_aware_dates    datetime64[ns, US/Eastern]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</span></code></a> has two parameters <code>include</span></code> and <code>exclude</span></code> that allow you to say “give me the columns <em>with</em> these dtypes” (<code>include</span></code>) and/or “give the columns <em>without</em> these dtypes” (<code>exclude</span></code>).</p>

<p>For example, to select <code>bool</span></code> columns:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell156"><span></span><span class="gp">In [437]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="nb">bool</span><span class="p">])</span>
<span class="gh">Out[437]: </span>
<span class="go">   bool1  bool2</span>
<span class="go">0   True  False</span>
<span class="go">1  False   True</span>
<span class="go">2   True  False</span>
</pre>
</div>
</div>

<p>You can also pass the name of a dtype in the <a href="https://numpy.org/doc/stable/reference/arrays.scalars.html">NumPy dtype hierarchy</a>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell157"><span></span><span class="gp">In [438]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"bool"</span><span class="p">])</span>
<span class="gh">Out[438]: </span>
<span class="go">   bool1  bool2</span>
<span class="go">0   True  False</span>
<span class="go">1  False   True</span>
<span class="go">2   True  False</span>
</pre>
</div>
</div>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes" title="pandas.DataFrame.select_dtypes"><code>select_dtypes()</span></code></a> also works with generic dtypes as well.</p>

<p>For example, to select all numeric and boolean columns while excluding unsigned integers:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell158"><span></span><span class="gp">In [439]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"number"</span><span class="p">,</span> <span class="s2">"bool"</span><span class="p">],</span> <span class="n">exclude</span><span class="o">=</span><span class="p">[</span><span class="s2">"unsignedinteger"</span><span class="p">])</span>
<span class="gh">Out[439]: </span>
<span class="go">   int64  float64  bool1  bool2 tdeltas</span>
<span class="go">0      1      4.0   True  False     NaT</span>
<span class="go">1      2      5.0  False   True  1 days</span>
<span class="go">2      3      6.0   True  False  1 days</span>
</pre>
</div>
</div>

<p>To select string columns you must use the <code>object</span></code> dtype:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell159"><span></span><span class="gp">In [440]: </span><span class="n">df</span><span class="o">.</span><span class="n">select_dtypes</span><span class="p">(</span><span class="n">include</span><span class="o">=</span><span class="p">[</span><span class="s2">"object"</span><span class="p">])</span>
<span class="gh">Out[440]: </span>
<span class="go">  string</span>
<span class="go">0      a</span>
<span class="go">1      b</span>
<span class="go">2      c</span>
</pre>
</div>
</div>

<p>To see all the child dtypes of a generic <code>dtype</span></code> like <code>numpy.number</span></code> you can define a function that returns a tree of child dtypes:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell160"><span></span><span class="gp">In [441]: </span><span class="k">def</span><span class="w"> </span><span class="nf">subdtypes</span><span class="p">(</span><span class="n">dtype</span><span class="p">):</span>
<span class="gp">   </span>    <span class="n">subs</span> <span class="o">=</span> <span class="n">dtype</span><span class="o">.</span><span class="n">__subclasses__</span><span class="p">()</span>
<span class="gp">   </span>    <span class="k">if</span> <span class="ow">not</span> <span class="n">subs</span><span class="p">:</span>
<span class="gp">   </span>        <span class="k">return</span> <span class="n">dtype</span>
<span class="gp">   </span>    <span class="k">return</span> <span class="p">[</span><span class="n">dtype</span><span class="p">,</span> <span class="p">[</span><span class="n">subdtypes</span><span class="p">(</span><span class="n">dt</span><span class="p">)</span> <span class="k">for</span> <span class="n">dt</span> <span class="ow">in</span> <span class="n">subs</span><span class="p">]]</span>
<span class="gp">   </span>
</pre>
</div>
</div>

<p>All NumPy dtypes are subclasses of <code>numpy.generic</span></code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell161"><span></span><span class="gp">In [442]: </span><span class="n">subdtypes</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">generic</span><span class="p">)</span>
<span class="gh">Out[442]: </span>
<span class="go">[numpy.generic,</span>
<span class="go"> [[numpy.number,</span>
<span class="go">   [[numpy.integer,</span>
<span class="go">     [[numpy.signedinteger,</span>
<span class="go">       [numpy.int8,</span>
<span class="go">        numpy.int16,</span>
<span class="go">        numpy.int32,</span>
<span class="go">        numpy.int64,</span>
<span class="go">        numpy.longlong,</span>
<span class="go">        numpy.timedelta64]],</span>
<span class="go">      [numpy.unsignedinteger,</span>
<span class="go">       [numpy.uint8,</span>
<span class="go">        numpy.uint16,</span>
<span class="go">        numpy.uint32,</span>
<span class="go">        numpy.uint64,</span>
<span class="go">        numpy.ulonglong]]]],</span>
<span class="go">    [numpy.inexact,</span>
<span class="go">     [[numpy.floating,</span>
<span class="go">       [numpy.float16, numpy.float32, numpy.float64, numpy.longdouble]],</span>
<span class="go">      [numpy.complexfloating,</span>
<span class="go">       [numpy.complex64, numpy.complex128, numpy.clongdouble]]]]]],</span>
<span class="go">  [numpy.flexible,</span>
<span class="go">   [[numpy.character, [numpy.bytes_, numpy.str_]],</span>
<span class="go">    [numpy.void, [numpy.record]]]],</span>
<span class="go">  numpy.bool_,</span>
<span class="go">  numpy.datetime64,</span>
<span class="go">  numpy.object_]]</span>
</pre>
</div>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>pandas also defines the types <code>category</span></code>, and <code>datetime64[ns,</span> tz]</span></code>, which are not integrated into the normal
NumPy hierarchy and won’t show up with the above function.</p>
</div>
</section>
</section>