<h1>IO tools (text, CSV, HDF5, …)</h1>

<p>The pandas I/O API is a set of top level <code>reader</code> functions accessed like
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>pandas.read_csv()</code></a> that generally return a pandas object. The corresponding <code>writer</code> functions are object methods that are accessed like
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html" title="pandas.DataFrame.to_csv"><code>DataFrame.to_csv()</code></a>. Below is a table containing available <code>readers</code> and <code>writers</code>.</p>

<table class="table">
<colgroup>
<col style="width: 12.0%">
<col style="width: 40.0%">
<col style="width: 24.0%">
<col style="width: 24.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Format Type</p></th>
<th class="head"><p>Data Description</p></th>
<th class="head"><p>Reader</p></th>
<th class="head"><p>Writer</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>text</p></td>
<td><p><a href="https://en.wikipedia.org/wiki/Comma-separated_values">CSV</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-read-csv-table>read_csv</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-store-in-csv">to_csv</a></p></td>
</tr>
<tr class="row-odd"><td><p>text</p></td>
<td><p>Fixed-Width Text File</p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-fwf-reader">read_fwf</a></p></td>
<td><p>NA</p></td>
</tr>
<tr class="row-even"><td><p>text</p></td>
<td><p><a href="https://www.json.org/">JSON</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-json-reader">read_json</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-json-writer">to_json</a></p></td>
</tr>
<tr class="row-odd"><td><p>text</p></td>
<td><p><a href="https://en.wikipedia.org/wiki/HTML">HTML</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-read-html">read_html</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-html">to_html</a></p></td>
</tr>
<tr class="row-even"><td><p>text</p></td>
<td><p><a href="https://en.wikipedia.org/wiki/LaTeX">LaTeX</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-latex">Styler.to_latex</a></p></td>
<td><p>NA</p></td>
</tr>
<tr class="row-odd"><td><p>text</p></td>
<td><p><a href="https://www.w3.org/standards/xml/core">XML</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-read-xml">read_xml</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-xml">to_xml</a></p></td>
</tr>
<tr class="row-even"><td><p>text</p></td>
<td><p>Local clipboard</p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-clipboard">read_clipboard</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-clipboard">to_clipboard</a></p></td>
</tr>
<tr class="row-odd"><td><p>binary</p></td>
<td><p><a href="https://en.wikipedia.org/wiki/Microsoft_Excel">MS Excel</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-excel-reader">read_excel</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-excel-writer">to_excel</a></p></td>
</tr>
<tr class="row-even"><td><p>binary</p></td>
<td><p><a href="http://opendocumentformat.org">OpenDocument</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-ods">read_excel</a></p></td>
<td><p>NA</p></td>
</tr>
<tr class="row-odd"><td><p>binary</p></td>
<td><p><a href="https://support.hdfgroup.org/HDF5/whatishdf5.html">HDF5 Format</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-hdf5">read_hdf</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-hdf5">to_hdf</a></p></td>
</tr>
<tr class="row-even"><td><p>binary</p></td>
<td><p><a href="https://github.com/wesm/feather">Feather Format</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-feather">read_feather</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-feather">to_feather</a></p></td>
</tr>
<tr class="row-odd"><td><p>binary</p></td>
<td><p><a href="https://parquet.apache.org/">Parquet Format</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-parquet">read_parquet</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-parquet">to_parquet</a></p></td>
</tr>
<tr class="row-even"><td><p>binary</p></td>
<td><p><a href="https://orc.apache.org/">ORC Format</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-orc">read_orc</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-orc">to_orc</a></p></td>
</tr>
<tr class="row-even"><td><p>binary</p></td>
<td><p><a href="https://docs.python.org/3/library/pickle.html">Python Pickle Format</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-pickle">read_pickle</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-pickle">to_pickle</a></p></td>
</tr>
<tr class="row-odd"><td><p>SQL</p></td>
<td><p><a href="https://en.wikipedia.org/wiki/SQL">SQL</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-sql">read_sql</a></p></td>
<td><p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-sql">to_sql</a></p></td>
</tr>
<tr class="row-even"><td><p>SQL</p></td>
<td><p><a href="https://en.wikipedia.org/wiki/BigQuery">Google BigQuery</a></td>
<td><p>:ref:<cite>read_gbq&lt;io.bigquery&gt;</cite></p></td>
<td><p>:ref:<cite>to_gbq&lt;io.bigquery&gt;</cite></p></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>

<p><a href="https://pandas.pydata.org/docs/user_guide/io.html#io-perf">Here</a> is an informal performance comparison for some of these IO methods.</p>
                                                                     
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>For examples that use the <code>StringIO</code> class, make sure you import it with <code>from io import StringIO</code> for Python 3.</p>
</div>

# <h2>CSV &amp; text files</h2>

<p>The workhorse function for reading text files (a.k.a. flat files) is
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>read_csv()</code></a>.
See the <a href="https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-csv">cookbook</a> for some advanced strategies.</p>

## <h3>Parsing options</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>read_csv()</code></a> accepts the following common arguments:</p>

### <h4>Basic</h4>

<dl>
<dt>filepath_or_buffer: various</dt><dd><p>Either a path to a file (a
<a href="https://docs.python.org/3/library/stdtypes.html#str" title="(in Python v3.13)"><code>str</code></a>,
<a href="https://docs.python.org/3/library/pathlib.html#pathlib.Path" title="(in Python v3.13)"><code>pathlib.Path</code></a>, or <code>py:py._path.local.LocalPath</code>), URL (including http, ftp, and S3 locations), or any object with a <code>read()</code> method (such as an open file or <a href="https://docs.python.org/3/library/io.html#io.StringIO" title="(in Python v3.13)"><code>StringIO</code></a>).</p>
</dd>
<dt>sep: str, defaults to <code>','</code> for <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>read_csv()</code></a>, <code>\t</code> for <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_table.html" title="pandas.read_table"><code>read_table()</code></a></dt><dd><p>Delimiter to use. If sep is <code>None</code>, the C engine cannot automatically detect the separator, but the Python parsing engine can, meaning the latter will be used and automatically detect the separator by Python’s builtin sniffer tool, <a href="https://docs.python.org/3/library/csv.html#csv.Sniffer" title="(in Python v3.13)"><code>csv.Sniffer</code></a>.
In addition, separators longer than 1 character and different from <code>'\s+'</code> will be interpreted as regular expressions and will also force the use of the Python parsing engine. Note that regex delimiters are prone to ignoring quoted data. Regex example: <code>'\\r\\t'</code>.</p>
</dd>
<dt>delimiter: str, default <code>None</code></dt><dd><p>Alternative argument name for sep.</p>
</dd>
<dt>delim_whitespace: boolean, default False</dt><dd><p>Specifies whether or not whitespace (e.g. <code>' '</code> or <code>'\t'</code>) will be used as the delimiter. Equivalent to setting <code>sep='\s+'</code>.
If this option is set to <code>True</code>, nothing should be passed in for the <code>delimiter</code> parameter.</p>
</dd>
</dl>

### <h4>Column and index locations and names</h4>

<dl>
<dt>header: int or list of ints, default <code>'infer'</code></dt><dd><p>Row number(s) to use as the column names, and the start of the data. Default behavior is to infer the column names: if no names are passed the behavior is identical to <code>header=0</code> and column names are inferred from the first line of the file, if column names are passed explicitly then the behavior is identical to <code>header=None</code>. Explicitly pass <code>header=0</code> to be able to replace existing names.</p>

<p>The header can be a list of ints that specify row locations for a MultiIndex on the columns e.g. <code>[0,1,3]</code>. Intervening rows that are not specified will be skipped (e.g. 2 in this example is skipped). Note that this parameter ignores commented lines and empty lines if <code>skip_blank_lines=True</code>, so header=0 denotes the first line of data rather than the first line of the file.</p>
</dd>
<dt>names: array-like, default <code>None</code></dt><dd><p>List of column names to use. If file contains no header row, then you should explicitly pass <code>header=None</code>. Duplicates in this list are not allowed.</p>
</dd>
<dt>index_col: int, str, sequence of int / str, or False, optional, default <code>None</code></dt><dd><p>Column(s) to use as the row labels of the <code>DataFrame</code>, either given as string name or column index. If a sequence of int / str is given, a MultiIndex is used.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>index_col=False</code> can be used to force pandas to <em>not</em> use the first column as the index, e.g. when you have a malformed file with delimiters at the end of each line.</p>
</div>

<p>The default value of <code>None</code> instructs pandas to guess. If the number of fields in the column header row is equal to the number of fields in the body of the data file, then a default index is used.  If it is larger, then the first columns are used as index so that the remaining number of fields in the body are equal to the number of fields in the header.</p>

<p>The first row after the header is used to determine the number of columns, which will go into the index. If the subsequent rows contain less columns than the first row, they are filled with <code>NaN</code>.</p>

<p>This can be avoided through <code>usecols</code>. This ensures that the columns are taken as is and the trailing data are ignored.</p>
</dd>

<dt>usecols: list-like or callable, default <code>None</code></dt><dd><p>Return a subset of the columns. If list-like, all elements must either be positional (i.e. integer indices into the document columns) or strings that correspond to column names provided either by the user in <code>names</code> or inferred from the document header row(s). If <code>names</code> are given, the document header row(s) are not taken into account. For example, a valid list-like <code>usecols</code> parameter would be <code>[0, 1, 2]</code> or <code>['foo', 'bar', 'baz']</code>.</p>

<p>Element order is ignored, so <code>usecols=[0, 1]</code> is the same as <code>[1, 0]</code>. To instantiate a DataFrame from <code>data</code> with element order preserved use <code>pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]</code> for columns in <code>['foo', 'bar']</code> order or <code>pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]</code> for <code>['bar', 'foo']</code> order.</p>

<p>If callable, the callable function will be evaluated against the column names, returning names where the callable function evaluates to True:</p>

In [6]:
import pandas as pd

from io import StringIO

In [7]:
data = "col1,col2,col3\na,b,1\na,b,2\nc,d,3"

In [8]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    a    b     1
1    a    b     2
2    c    d     3

In [9]:
pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ["COL1", "COL3"])

  col1  col3
0    a     1
1    a     2
2    c     3

<p>Using this parameter results in much faster parsing time and lower memory usage when using the c engine. The Python engine loads the data first before deciding which columns to drop.</p>
</dd>
</dl>

### <h4>General parsing configuration</h4>

<dl>
<dt>dtype: Type name or dict of column -&gt; type, default <code>None</code></dt><dd><p>Data type for data or columns. E.g. <code>{'a': np.float64, 'b': np.int32, 'c': 'Int64'}</code>
Use <code>str</code> or <code>object</code> together with suitable <code>na_values</code> settings to preserve and not interpret dtype. If converters are specified, they will be applied INSTEAD of dtype conversion.</p>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.5.0: Support for defaultdict was added. Specify a defaultdict as input where
the default determines the dtype of the columns which are not explicitly listed.</p>
</div>
</dd>
<dt>dtype_backend: {“numpy_nullable”, “pyarrow”}, defaults to NumPy backed DataFrames</dt><dd><p>Which dtype_backend to use, e.g. whether a DataFrame should have NumPy arrays, nullable dtypes are used for all dtypes that have a nullable implementation when “numpy_nullable” is set, pyarrow is used for all dtypes if “pyarrow” is set.</p>

<p>The dtype_backends are still experimential.</p>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 2.0.</p>
</div>
</dd>
<dt>engine: {<code>'c'</code>, <code>'python'</code>, <code>'pyarrow'</code>}</dt><dd><p>Parser engine to use. The C and pyarrow engines are faster, while the python engine is currently more feature-complete. Multithreading is currently only supported by the pyarrow engine.</p>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.4.0: The “pyarrow” engine was added as an <em>experimental</em> engine, and some features are unsupported, or may not work correctly, with this engine.</p>
</div>
</dd>

<dt>converters: dict, default <code>None</code></dt><dd><p>Dict of functions for converting values in certain columns. Keys can either be integers or column labels.</p>
</dd>
<dt>true_values: list, default <code>None</code></dt><dd><p>Values to consider as <code>True</code>.</p>
</dd>
<dt>false_values: list, default <code>None</code></dt><dd><p>Values to consider as <code>False</code>.</p>
</dd>
<dt>skipinitialspace: boolean, default <code>False</code></dt><dd><p>Skip spaces after delimiter.</p>
</dd>
<dt>skiprows: list-like or integer, default <code>None</code></dt><dd><p>Line numbers to skip (0-indexed) or number of lines to skip (int) at the start of the file.</p>

<p>If callable, the callable function will be evaluated against the row indices, returning True if the row should be skipped and False otherwise:</p>

</dd>

In [10]:
data = "col1,col2,col3\na,b,1\na,b,2\nc,d,3"

In [11]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    a    b     1
1    a    b     2
2    c    d     3

In [12]:
pd.read_csv(StringIO(data), skiprows=lambda x: x % 2 != 0)

  col1 col2  col3
0    a    b     2

<dt>skipfooter: int, default <code>0</code></dt><dd><p>Number of lines at bottom of file to skip (unsupported with engine=’c’).</p>
</dd>
<dt>nrows: int, default <code>None</code></dt><dd><p>Number of rows of file to read. Useful for reading pieces of large files.</p>
</dd>
<dt>low_memory: boolean, default <code>True</code></dt><dd><p>Internally process the file in chunks, resulting in lower memory use
while parsing, but possibly mixed type inference.  To ensure no mixed types either set <code>False</code>, or specify the type with the <code>dtype</code> parameter.
Note that the entire file is read into a single <code>DataFrame</code> regardless, use the <code>chunksize</code> or <code>iterator</code> parameter to return the data in chunks. (Only valid with C parser)</p>
</dd>
<dt>memory_map: boolean, default False</dt><dd><p>If a filepath is provided for <code>filepath_or_buffer</code>, map the file object
directly onto memory and access the data directly from there. Using this option can improve performance because there is no longer any I/O overhead.</p>
</dd>
</dl>

### <h4>NA and missing data handling</h4>

<dl>
<dt>na_values: scalar, str, list-like, or dict, default <code>None</code></dt><dd><p>Additional strings to recognize as NA/NaN. If dict passed, specific per-column NA values. See <a href="#io-navaluesconst">na values const</a> below for a list of the values interpreted as NaN by default.</p>
</dd>
<dt>keep_default_na: boolean, default <code>True</code></dt><dd><p>Whether or not to include the default NaN values when parsing the data. Depending on whether <code>na_values</code> is passed in, the behavior is as follows:</p>
<ul class="simple">
<li><p>If <code>keep_default_na</code> is <code>True</code>, and <code>na_values</code> are specified, <code>na_values</code> is appended to the default NaN values used for parsing.</p></li>
<li><p>If <code>keep_default_na</code> is <code>True</code>, and <code>na_values</code> are not specified, only
the default NaN values are used for parsing.</p></li>
<li><p>If <code>keep_default_na</code> is <code>False</code>, and <code>na_values</code> are specified, only
the NaN values specified <code>na_values</code> are used for parsing.</p></li>
<li><p>If <code>keep_default_na</code> is <code>False</code>, and <code>na_values</code> are not specified, no
strings will be parsed as NaN.</p></li>
</ul>
<p>Note that if <code>na_filter</code> is passed in as <code>False</code>, the <code>keep_default_na</code> and
<code>na_values</code> parameters will be ignored.</p>
</dd>
<dt>na_filter: boolean, default <code>True</code></dt><dd><p>Detect missing value markers (empty strings and the value of na_values). In data without any NAs, passing <code>na_filter=False</code> can improve the performance of reading a large file.</p>
</dd>
<dt>verbose: boolean, default <code>False</code></dt><dd><p>Indicate number of NA values placed in non-numeric columns.</p>
</dd>
<dt>skip_blank_lines: boolean, default <code>True</code></dt><dd><p>If <code>True</code>, skip over blank lines rather than interpreting as NaN values.</p>
</dd>
</dl>

### <h4>Datetime handling</h4>

<dl>
<dt>parse_dates: boolean or list of ints or names or list of lists or dict, default <code>False</code>.</dt><dd><ul class="simple">
<li><p>If <code>True</code> -&gt; try parsing the index.</p></li>
<li><p>If <code>[1, 2, 3]</code> -&gt;  try parsing columns 1, 2, 3 each as a separate date
column.</p></li>
<li><p>If <code>[[1, 3]]</code> -&gt; combine columns 1 and 3 and parse as a single date
column.</p></li>
<li><p>If <code>{'foo': [1, 3]}</code> -&gt; parse columns 1, 3 as date and call result ‘foo’.</p></li>
</ul>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>A fast-path exists for iso8601-formatted dates.</p>
</div>
</dd>
<dt>infer_datetime_format: boolean, default <code>False</code></dt><dd><p>If <code>True</code> and parse_dates is enabled for a column, attempt to infer the datetime format to speed up the processing.</p>
<div class="deprecated">
<p><span class="versionmodified deprecated">Deprecated since version 2.0.0: A strict version of this argument is now the default, passing it has no effect.</p>
</div>
</dd>
<dt>keep_date_col: boolean, default <code>False</code></dt><dd><p>If <code>True</code> and parse_dates specifies combining multiple columns then keep the original columns.</p>
</dd>
<dt>date_parser: function, default <code>None</code></dt><dd><p>Function to use for converting a sequence of string columns to an array of datetime instances. The default uses <code>dateutil.parser.parser</code> to do the conversion. pandas will try to call date_parser in three different ways, advancing to the next if an exception occurs: 1) Pass one or more arrays (as defined by parse_dates) as arguments; 2) concatenate (row-wise) the string values from the columns defined by parse_dates into a single array and pass that; and 3) call date_parser once for each row using one or more strings (corresponding to the columns defined by parse_dates) as arguments.</p>
<div class="deprecated">
<p><span class="versionmodified deprecated">Deprecated since version 2.0.0: Use <code>date_format</code> instead, or read in as <code>object</code> and then apply
<a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html" title="pandas.to_datetime"><code>to_datetime()</code></a> as-needed.</p>
</div>
</dd>
<dt>date_format: str or dict of column -&gt; format, default <code>None</code></dt><dd><p>If used in conjunction with <code>parse_dates</code>, will parse dates according to this format. For anything more complex, please read in as <code>object</code> and then apply
<a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html" title="pandas.to_datetime"><code>to_datetime()</code></a> as-needed.</p>
<div class="versionadded">
<p><span class="versionmodified added">Added in version 2.0.0.</p>
</div>
</dd>
<dt>dayfirst: boolean, default <code>False</code></dt><dd><p>DD/MM format dates, international and European format.</p>
</dd>
<dt>cache_dates: boolean, default True</dt><dd><p>If True, use a cache of unique, converted dates to apply the datetime conversion.
May produce significant speed-up when parsing duplicate date strings, especially ones with timezone offsets.</p>
</dd>
</dl>

### <h4>Iteration</h4>

<dl>
<dt>iterator: boolean, default <code>False</code></dt><dd><p>Return <code>TextFileReader</code> object for iteration or getting chunks with <code>get_chunk()</code>.</p>
</dd>
<dt>chunksize: int, default <code>None</code></dt><dd><p>Return <code>TextFileReader</code> object for iteration.
See <a href="#io-chunking">iterating and chunking</a> below.</p>
</dd>
</dl>

### <h4>Quoting, compression, and file format</h4>

<dl>
<dt>compression: {<code>'infer'</code>, <code>'gzip'</code>, <code>'bz2'</code>, <code>'zip'</code>, <code>'xz'</code>, <code>'zstd'</code>, <code>None</code>, <code>dict</code>}, default <code>'infer'</code></dt><dd><p>For on-the-fly decompression of on-disk data. If ‘infer’, then use gzip, bz2, zip, xz, or zstandard if <code>filepath_or_buffer</code> is path-like ending in ‘.gz’, ‘.bz2’, ‘.zip’, ‘.xz’, ‘.zst’, respectively, and no decompression otherwise.
If using ‘zip’, the ZIP file must contain only one data file to be read in.
Set to <code>None</code> for no decompression. Can also be a dict with key <code>'method'</code> set to one of {<code>'zip'</code>, <code>'gzip'</code>, <code>'bz2'</code>, <code>'zstd'</code>} and other key-value pairs are forwarded to <code>zipfile.ZipFile</code>, <code>gzip.GzipFile</code>, <code>bz2.BZ2File</code>, or <code>zstandard.ZstdDecompressor</code>.
As an example, the following could be passed for faster compression and to create a reproducible gzip archive:
<code>compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}</code>.</p>
<div class="versionchanged">
<p>Changed in version 1.2.0: Previous versions forwarded dict entries for ‘gzip’ to <code>gzip.open</code>.</p>
</div>
</dd>
<dt>thousands: str, default <code>None</code></dt><dd><p>Thousands separator.</p>
</dd>
<dt>decimal: str, default <code>'.'</code></dt><dd><p>Character to recognize as decimal point. E.g. use <code>','</code> for European data.</p>
</dd>
<dt>float_precision: string, default None</dt><dd><p>Specifies which converter the C engine should use for floating-point values.
The options are <code>None</code> for the ordinary converter, <code>high</code> for the high-precision converter, and <code>round_trip</code> for the round-trip converter.</p>
</dd>
<dt>lineterminator: str (length 1), default <code>None</code></dt><dd><p>Character to break file into lines. Only valid with C parser.</p>
</dd>
<dt>quotechar: str (length 1)</dt><dd><p>The character used to denote the start and end of a quoted item. Quoted items
can include the delimiter and it will be ignored.</p>
</dd>
<dt>quoting: int or <code>csv.QUOTE_*</code> instance, default <code>0</code></dt><dd><p>Control field quoting behavior per <code>csv.QUOTE_*</code> constants. Use one of <code>QUOTE_MINIMAL</code> (0), <code>QUOTE_ALL</code> (1), <code>QUOTE_NONNUMERIC</code> (2) or <code>QUOTE_NONE</code> (3).</p>
</dd>
<dt>doublequote: boolean, default <code>True</code></dt><dd><p>When <code>quotechar</code> is specified and <code>quoting</code> is not <code>QUOTE_NONE</code>, indicate whether or not to interpret two consecutive <code>quotechar</code> elements <strong>inside</strong> a field as a single <code>quotechar</code> element.</p>
</dd>
<dt>escapechar: str (length 1), default <code>None</code></dt><dd><p>One-character string used to escape delimiter when quoting is <code>QUOTE_NONE</code>.</p>
</dd>
<dt>comment: str, default <code>None</code></dt><dd><p>Indicates remainder of line should not be parsed. If found at the beginning of a line, the line will be ignored altogether. This parameter must be a single character. Like empty lines (as long as <code>skip_blank_lines=True</code>), fully commented lines are ignored by the parameter <code>header</code> but not by <code>skiprows</code>.
For example, if <code>comment='#'</code>, parsing ‘#empty\na,b,c\n1,2,3’ with <code>header=0</code> will result in ‘a,b,c’ being treated as the header.</p>
</dd>
<dt>encoding: str, default <code>None</code></dt><dd><p>Encoding to use for UTF when reading/writing (e.g. <code>'utf-8'</code>). <a href="https://docs.python.org/3/library/codecs.html#standard-encodings">List of Python standard encodings</a>.</p>
</dd>
<dt>dialect: str or <a href="https://docs.python.org/3/library/csv.html#csv.Dialect" title="(in Python v3.13)"><code>csv.Dialect</code></a> instance, default <code>None</code></dt><dd><p>If provided, this parameter will override values (default or not) for the
following parameters: <code>delimiter</code>, <code>doublequote</code>, <code>escapechar</code>,
<code>skipinitialspace</code>, <code>quotechar</code>, and <code>quoting</code>. If it is necessary to
override values, a ParserWarning will be issued. See <a href="https://docs.python.org/3/library/csv.html#csv.Dialect" title="(in Python v3.13)"><code>csv.Dialect</code></a> documentation for more details.</p>
</dd>
</dl>

### <h4>Error handling</h4>

<dl>
<dt>on_bad_lines: (‘error’, ‘warn’, ‘skip’), default ‘error’</dt><dd><p>Specifies what to do upon encountering a bad line (a line with too many fields). Allowed values are :</p>
<ul class="simple">
<li><p>‘error’, raise an ParserError when a bad line is encountered.</p></li>
<li><p>‘warn’, print a warning when a bad line is encountered and skip that line.</p></li>
<li><p>‘skip’, skip bad lines without raising or warning when they are encountered.</p></li>
</ul>
<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.3.0.</p>
</div>
</dd>
</dl>

In [13]:
import numpy as np

In [14]:
data = "a,b,c,d\n1,2,3,4\n5,6,7,8\n9,10,11"

In [15]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [16]:
df = pd.read_csv(StringIO(data), dtype=object)

In [17]:
df

   a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [18]:
df["a"][0]

'1'

In [19]:
df = pd.read_csv(StringIO(data), dtype={"b": object, "c": np.float64, "d": "Int64"})

In [20]:
df.dtypes

a      int64
b     object
c    float64
d      Int64
dtype: object

<p>Fortunately, pandas offers more than one way to ensure that your column(s) contain only one <code>dtype</code>.
If you’re unfamiliar with these concepts, you can see <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">here</a> to learn more about dtypes, and <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-object-conversion">here</a> to learn more about <code>object</code> conversion in pandas.</p>

<p>For instance, you can use the <code>converters</code> argument of <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>read_csv()</code></a>:</p>

In [21]:
data = "col_1\n1\n2\n'A'\n4.22"

In [22]:
df = pd.read_csv(StringIO(data), converters={"col_1": str})

In [23]:
df

  col_1
0     1
1     2
2   'A'
3  4.22

In [24]:
df["col_1"].apply(type).value_counts()

col_1
<class 'str'>    4
Name: count, dtype: int64

<p>Or you can use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html" title="pandas.to_numeric"><code>to_numeric()</code></a> function to coerce the dtypes after reading in the data,</p>

In [25]:
df2 = pd.read_csv(StringIO(data))

In [26]:
df2["col_1"] = pd.to_numeric(df2["col_1"], errors="coerce")

In [27]:
df2

   col_1
0   1.00
1   2.00
2    NaN
3   4.22

In [28]:
df2["col_1"].apply(type).value_counts()

col_1
<class 'float'>    4
Name: count, dtype: int64

<p>which will convert all valid parsing to floats, leaving the invalid parsing as <code>NaN</code>.</p>

<p>Ultimately, how you deal with reading in columns containing mixed dtypes depends on your specific needs. In the case above, if you wanted to <code>NaN</code> out the data anomalies, then <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html" title="pandas.to_numeric"><code>to_numeric()</code></a> is probably your best option.
However, if you wanted for all the data to be coerced, no matter the type, then using the <code>converters</code> argument of
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>read_csv()</code></a> would certainly be worth trying.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>In some cases, reading in abnormal data with columns containing mixed dtypes will result in an inconsistent dataset. If you rely on pandas to infer the dtypes of your columns, the parsing engine will go and infer the dtypes for different chunks of the data, rather than the whole dataset at once. Consequently, you can end up with column(s) with mixed dtypes. For example,</p>

In [29]:
col_1 = list(range(500000)) + ["a", "b"] + list(range(500000))

In [30]:
df = pd.DataFrame({"col_1": col_1})

In [31]:
df.to_csv("foo.csv")

In [32]:
mixed_df = pd.read_csv("foo.csv")

/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_87177/1675282049.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  mixed_df = pd.read_csv("foo.csv")

In [33]:
mixed_df["col_1"].apply(type).value_counts()

col_1
<class 'int'>    737858
<class 'str'>    262144
Name: count, dtype: int64

In [34]:
mixed_df["col_1"].dtype

dtype('O')

<p>will result with <code>mixed_df</code> containing an <code>int</code> dtype for certain chunks of the column, and <code>str</code> for others due to the mixed dtypes from the data that was read in. It is important to note that the overall column will be marked with a <code>dtype</code> of <code>object</code>, which is used for columns with mixed dtypes.</p>
</div>

<p>Setting <code>dtype_backend="numpy_nullable"</code> will result in nullable dtypes for every column.</p>

In [35]:
data = """a,b,c,d,e,f,g,h,i,j
1,2.5,True,a,,,,,12-31-2019,
3,4.5,False,b,6,7.5,True,a,12-31-2019,
"""

In [36]:
df = pd.read_csv(StringIO(data), dtype_backend="numpy_nullable", parse_dates=["i"])

In [37]:
df

   a    b      c  d     e     f     g     h          i     j
0  1  2.5   True  a  <NA>  <NA>  <NA>  <NA> 2019-12-31  <NA>
1  3  4.5  False  b     6   7.5  True     a 2019-12-31  <NA>

In [38]:
df.dtypes

a             Int64
b           Float64
c           boolean
d    string[python]
e             Int64
f           Float64
g           boolean
h    string[python]
i    datetime64[ns]
j             Int64
dtype: object

## <h3>Specifying categorical dtype</h3>

<p><code>Categorical</code> columns can be parsed directly by specifying <code>dtype='category'</code> or <code>dtype=CategoricalDtype(categories, ordered)</code>.</p>

In [39]:
data = "col1,col2,col3\na,b,1\na,b,2\nc,d,3"

In [40]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    a    b     1
1    a    b     2
2    c    d     3

In [41]:
pd.read_csv(StringIO(data)).dtypes

col1    object
col2    object
col3     int64
dtype: object

In [42]:
pd.read_csv(StringIO(data), dtype="category").dtypes

col1    category
col2    category
col3    category
dtype: object

<p>Individual columns can be parsed as a <code>Categorical</code> using a dict specification:</p>

In [43]:
pd.read_csv(StringIO(data), dtype={"col1": "category"}).dtypes

col1    category
col2      object
col3       int64
dtype: object

<p>Specifying <code>dtype='category'</code> will result in an unordered <code>Categorical</code> whose <code>categories</code> are the unique values observed in the data. For more control on the categories and order, create a <code>CategoricalDtype</code> ahead of time, and pass that for that column’s <code>dtype</code>.</p>

In [44]:
from pandas.api.types import CategoricalDtype

In [45]:
dtype = CategoricalDtype(["d", "c", "b", "a"], ordered=True)

In [46]:
pd.read_csv(StringIO(data), dtype={"col1": dtype}).dtypes

col1    category
col2      object
col3       int64
dtype: object

<p>When using <code>dtype=CategoricalDtype</code>, “unexpected” values outside of <code>dtype.categories</code> are treated as missing values.</p>

In [47]:
dtype = CategoricalDtype(["a", "b", "d"])  # No 'c'

In [48]:
pd.read_csv(StringIO(data), dtype={"col1": dtype}).col1

0      a
1      a
2    NaN
Name: col1, dtype: category
Categories (3, object): ['a', 'b', 'd']

<p>This matches the behavior of <code>Categorical.set_categories()</code>.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>With <code>dtype='category'</code>, the resulting categories will always be parsed as strings (object dtype). If the categories are numeric they can be converted using the <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html" title="pandas.to_numeric"><code>to_numeric()</code></a> function, or as appropriate, another converter such as
<a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html" title="pandas.to_datetime"><code>to_datetime()</code></a>.</p>

<p>When <code>dtype</code> is a <code>CategoricalDtype</code> with homogeneous <code>categories</code> (all numeric, all datetimes, etc.), the conversion is done automatically.</p>

In [49]:
df = pd.read_csv(StringIO(data), dtype="category")

In [50]:
df.dtypes

col1    category
col2    category
col3    category
dtype: object

In [51]:
df["col3"]

0    1
1    2
2    3
Name: col3, dtype: category
Categories (3, object): ['1', '2', '3']

In [52]:
new_categories = pd.to_numeric(df["col3"].cat.categories)

In [53]:
df["col3"] = df["col3"].cat.rename_categories(new_categories)

In [54]:
df["col3"]

0    1
1    2
2    3
Name: col3, dtype: category
Categories (3, int64): [1, 2, 3]

## <h3>Naming and using columns</h3>

### <h4>Handling column names</h4>

<p>A file may or may not have a header row. pandas assumes the first row should be used as the column names:</p>

In [55]:
data = "a,b,c\n1,2,3\n4,5,6\n7,8,9"

In [56]:
print(data)

a,b,c
1,2,3
4,5,6
7,8,9

In [57]:
pd.read_csv(StringIO(data))

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

<p>By specifying the <code>names</code> argument in conjunction with <code>header</code> you can indicate other names to use and whether or not to throw away the header row (if any):</p>

In [58]:
print(data)

a,b,c
1,2,3
4,5,6
7,8,9

In [59]:
pd.read_csv(StringIO(data), names=["foo", "bar", "baz"], header=0)

   foo  bar  baz
0    1    2    3
1    4    5    6
2    7    8    9

In [60]:
pd.read_csv(StringIO(data), names=["foo", "bar", "baz"], header=None)

  foo bar baz
0   a   b   c
1   1   2   3
2   4   5   6
3   7   8   9

<p>If the header is in a row other than the first, pass the row number to <code>header</code>. This will skip the preceding rows:</p>

In [61]:
data = "skip this skip it\na,b,c\n1,2,3\n4,5,6\n7,8,9"

In [62]:
pd.read_csv(StringIO(data), header=1)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Default behavior is to infer the column names: if no names are passed the behavior is identical to <code>header=0</code> and column names are inferred from the first non-blank line of the file, if column names are passed explicitly then the behavior is identical to <code>header=None</code>.</p>
</div>

## <h3>Duplicate names parsing</h3>

<p>If the file or header contains duplicate names, pandas will by default distinguish between them so as to prevent overwriting data:</p>

In [63]:
data = "a,b,a\n0,1,2\n3,4,5"

In [64]:
pd.read_csv(StringIO(data))

   a  b  a.1
0  0  1    2
1  3  4    5

<p>There is no more duplicate data because duplicate columns ‘X’, …, ‘X’ become ‘X’, ‘X.1’, …, ‘X.N’.</p>

### <h4>Filtering columns (<code>usecols</code>)</h4>

<p>The <code>usecols</code> argument allows you to select any subset of the columns in a file, either using the column names, position numbers or a callable:</p>

In [65]:
data = "a,b,c,d\n1,2,3,foo\n4,5,6,bar\n7,8,9,baz"

In [66]:
pd.read_csv(StringIO(data))

   a  b  c    d
0  1  2  3  foo
1  4  5  6  bar
2  7  8  9  baz

In [67]:
pd.read_csv(StringIO(data), usecols=["b", "d"])

   b    d
0  2  foo
1  5  bar
2  8  baz

In [68]:
pd.read_csv(StringIO(data), usecols=[0, 2, 3])

   a  c    d
0  1  3  foo
1  4  6  bar
2  7  9  baz

In [69]:
pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ["A", "C"])

   a  c
0  1  3
1  4  6
2  7  9

<p>The <code>usecols</code> argument can also be used to specify which columns not to use in the final result:</p>

In [70]:
pd.read_csv(StringIO(data), usecols=lambda x: x not in ["a", "c"])

   b    d
0  2  foo
1  5  bar
2  8  baz

<p>In this case, the callable is specifying that we exclude the “a” and “c” columns from the output.</p>

## <h3>Comments and empty lines</h3>

### <h4>Ignoring line comments and empty lines</h4>

<p>If the <code>comment</code> parameter is specified, then completely commented lines will be ignored. By default, completely blank lines will be ignored as well.</p>

In [71]:
data = "\na,b,c\n  \n# commented line\n1,2,3\n\n4,5,6"

In [72]:
print(data)

a,b,c

# commented line
1,2,3

4,5,6

In [73]:
pd.read_csv(StringIO(data), comment='#')

   a  b  c
0  1  2  3
1  4  5  6

<p>If <code>skip_blank_lines=False</code>, then <code>read_csv</code> will not ignore blank lines:</p>

In [74]:
data = "a,b,c\n\n1,2,3\n\n\n4,5,6"

In [75]:
pd.read_csv(StringIO(data), skip_blank_lines=False)

     a    b    c
0  NaN  NaN  NaN
1  1.0  2.0  3.0
2  NaN  NaN  NaN
3  NaN  NaN  NaN
4  4.0  5.0  6.0

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>The presence of ignored lines might create ambiguities involving line numbers;
the parameter <code>header</code> uses row numbers (ignoring commented/empty
lines), while <code>skiprows</code> uses line numbers (including commented/empty lines):</p>

In [76]:
data = "#comment\na,b,c\nA,B,C\n1,2,3"

In [77]:
pd.read_csv(StringIO(data), comment='#', header=1)

   A  B  C
0  1  2  3

In [78]:
data = "A,B,C\n#comment\na,b,c\n1,2,3"

In [79]:
pd.read_csv(StringIO(data), comment="#", skiprows=2)

   a  b  c
0  1  2  3

<p>If both <code>header</code> and <code>skiprows</code> are specified, <code>header</code> will be
relative to the end of <code>skiprows</code>. For example:</p>
</div>

In [80]:
data = (
    "# empty\n"
    "# second empty line\n"
    "# third emptyline\n"
    "X,Y,Z\n"
    "1,2,3\n"
    "A,B,C\n"
    "1,2.,4.\n"
    "5.,NaN,10.0\n"
)

In [81]:
print(data)

# empty
# second empty line
# third emptyline
X,Y,Z
1,2,3
A,B,C
1,2.,4.
5.,NaN,10.0

In [82]:
pd.read_csv(StringIO(data), comment="#", skiprows=4, header=1)

     A    B     C
0  1.0  2.0   4.0
1  5.0  NaN  10.0

### <h4>Comments</h4>

<p>Sometimes comments or meta data may be included in a file:</p>

In [83]:
data = (
    "ID,level,category\n"
    "Patient1,123000,x # really unpleasant\n"
    "Patient2,23000,y # wouldn't take his medicine\n"
    "Patient3,1234018,z # awesome"
)

In [84]:
with open("tmp.csv", "w") as fh:
    fh.write(data)

In [85]:
print(open("tmp.csv").read())

ID,level,category
Patient1,123000,x # really unpleasant
Patient2,23000,y # wouldn't take his medicine
Patient3,1234018,z # awesome

<p>By default, the parser includes the comments in the output:</p>

In [86]:
df = pd.read_csv("tmp.csv")

In [87]:
df

         ID    level                        category
0  Patient1   123000           x # really unpleasant
1  Patient2    23000  y # wouldn't take his medicine
2  Patient3  1234018                     z # awesome

<p>We can suppress the comments using the <code>comment</code> keyword:</p>

In [88]:
df = pd.read_csv("tmp.csv", comment="#")

In [89]:
df

         ID    level category
0  Patient1   123000       x
1  Patient2    23000       y
2  Patient3  1234018       z

## <h3>Dealing with Unicode data</h3>

<p>The <code>encoding</code> argument should be used for encoded unicode data, which will result in byte strings being decoded to unicode in the result:</p>

In [90]:
from io import BytesIO

In [91]:
data = b"word,length\n" b"Tr\xc3\xa4umen,7\n" b"Gr\xc3\xbc\xc3\x9fe,5"

In [92]:
data = data.decode("utf8").encode("latin-1")

In [93]:
df = pd.read_csv(BytesIO(data), encoding="latin-1")

In [94]:
df

      word  length
0  Träumen       7
1    Grüße       5

In [95]:
df["word"][1]

'Grüße'

<p>Some formats which encode all characters as multiple bytes, like UTF-16, won’t parse correctly at all without specifying the encoding.
<a href="https://docs.python.org/3/library/codecs.html#standard-encodings">Full list of Python standard encodings</a>.</p>

## <h3>Index columns and trailing delimiters</h3>

<p>If a file has one more column of data than the number of column names, the first column will be used as the <code>DataFrame</code>’s row names:</p>

In [96]:
data = "a,b,c\n4,apple,bat,5.7\n8,orange,cow,10"

In [97]:
pd.read_csv(StringIO(data))

        a    b     c
4   apple  bat   5.7
8  orange  cow  10.0

In [98]:
data = "index,a,b,c\n4,apple,bat,5.7\n8,orange,cow,10"

In [99]:
pd.read_csv(StringIO(data), index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

<p>Ordinarily, you can achieve this behavior using the <code>index_col</code> option.</p>

<p>There are some exception cases when a file has been prepared with delimiters at the end of each data line, confusing the parser.
To explicitly disable the index column inference and discard the last column, pass <code>index_col=False</code>:</p>

In [100]:
data = "a,b,c\n4,apple,bat,\n8,orange,cow,"

In [101]:
print(data)

a,b,c
4,apple,bat,
8,orange,cow,

In [102]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [103]:
pd.read_csv(StringIO(data), index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

<p>If a subset of data is being parsed using the <code>usecols</code> option, the <code>index_col</code> specification is based on that subset, not the original data.</p>

In [104]:
data = "a,b,c\n4,apple,bat,\n8,orange,cow,"

In [105]:
print(data)

a,b,c
4,apple,bat,
8,orange,cow,

In [106]:
pd.read_csv(StringIO(data), usecols=["b", "c"])

     b   c
4  bat NaN
8  cow NaN

In [107]:
pd.read_csv(StringIO(data), usecols=["b", "c"], index_col=0)

     b   c
4  bat NaN
8  cow NaN

## <h3>Date Handling</h3>

### <h4>Specifying date columns</h4>

<p>To better facilitate working with datetime data, <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>read_csv()</code></a> uses the keyword arguments <code>parse_dates</code> and <code>date_format</code> to allow users to specify a variety of columns and date/time formats to turn the input text data into <code>datetime</code> objects.</p>

<p>The simplest case is to just pass in <code>parse_dates=True</code>:</p>

In [108]:
with open("foo.csv", mode="w") as f:
    f.write("date,A,B,C\n20090101,a,1,2\n20090102,b,3,4\n20090103,c,4,5")

In [109]:
# Use a column as an index, and parse it as dates.
df = pd.read_csv("foo.csv", index_col=0, parse_dates=True)

In [110]:
df

            A  B  C
date
2009-01-01  a  1  2
2009-01-02  b  3  4
2009-01-03  c  4  5

In [111]:
# These are Python datetime objects
df.index

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03'], dtype='datetime64[ns]', name='date', freq=None)

<p>It is often the case that we may want to store date and time data separately, or store various date fields separately. the <code>parse_dates</code> keyword can be used to specify a combination of columns to parse the dates and/or times from.</p>

<p>You can specify a list of column lists to <code>parse_dates</code>, the resulting date columns will be prepended to the output (so as to not affect the existing column order) and the new column names will be the concatenation of the component column names:</p>

In [112]:
data = (
    "KORD,19990127, 19:00:00, 18:56:00, 0.8100\n"
    "KORD,19990127, 20:00:00, 19:56:00, 0.0100\n"
    "KORD,19990127, 21:00:00, 20:56:00, -0.5900\n"
    "KORD,19990127, 21:00:00, 21:18:00, -0.9900\n"
    "KORD,19990127, 22:00:00, 21:56:00, -0.5900\n"
    "KORD,19990127, 23:00:00, 22:56:00, -0.5900"
)

In [113]:
with open("tmp.csv", "w") as fh:
    fh.write(data)

In [114]:
df = pd.read_csv("tmp.csv", header=None, parse_dates=[[1, 2], [1, 3]])

/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_87177/3378133469.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df = pd.read_csv("tmp.csv", header=None, parse_dates=[[1, 2], [1, 3]])

In [115]:
df

                  1_2                 1_3     0     4
0 1999-01-27 19:00:00 1999-01-27 18:56:00  KORD  0.81
1 1999-01-27 20:00:00 1999-01-27 19:56:00  KORD  0.01
2 1999-01-27 21:00:00 1999-01-27 20:56:00  KORD -0.59
3 1999-01-27 21:00:00 1999-01-27 21:18:00  KORD -0.99
4 1999-01-27 22:00:00 1999-01-27 21:56:00  KORD -0.59
5 1999-01-27 23:00:00 1999-01-27 22:56:00  KORD -0.59

<p>By default the parser removes the component date columns, but you can choose to retain them via the <code>keep_date_col</code> keyword:</p>

In [116]:
df = pd.read_csv(
    "tmp.csv", header=None, parse_dates=[[1, 2], [1, 3]], keep_date_col=True
)

/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_87177/4090359388.py:1: FutureWarning: The 'keep_date_col' keyword in pd.read_csv is deprecated and will be removed in a future version. Explicitly remove unwanted columns after parsing instead.
  df = pd.read_csv(
/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_87177/4090359388.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df = pd.read_csv(

In [117]:
df

,1_2,1_3,0,1,2,3,4
0,1999-01-27 19:00:00,1999-01-27 18:56:00,KORD,19990127,19:00:00,18:56:00,0.81
1,1999-01-27 20:00:00,1999-01-27 19:56:00,KORD,19990127,20:00:00,19:56:00,0.01
2,1999-01-27 21:00:00,1999-01-27 20:56:00,KORD,19990127,21:00:00,20:56:00,-0.59
3,1999-01-27 21:00:00,1999-01-27 21:18:00,KORD,19990127,21:00:00,21:18:00,-0.99
4,1999-01-27 22:00:00,1999-01-27 21:56:00,KORD,19990127,22:00:00,21:56:00,-0.59
5,1999-01-27 23:00:00,1999-01-27 22:56:00,KORD,19990127,23:00:00,22:56:00,-0.59

<p>Note that if you wish to combine multiple columns into a single date column, a nested list must be used. In other words, <code>parse_dates=[1, 2]</code> indicates that the second and third columns should each be parsed as separate date columns while <code>parse_dates=[[1, 2]]</code> means the two columns should be parsed into a single column.</p>

<p>You can also use a dict to specify custom name columns:</p>

In [118]:
date_spec = {"nominal": [1, 2], "actual": [1, 3]}

In [119]:
df = pd.read_csv("tmp.csv", header=None, parse_dates=date_spec)

/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_87177/3022266606.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df = pd.read_csv("tmp.csv", header=None, parse_dates=date_spec)

In [120]:
df

              nominal              actual     0     4
0 1999-01-27 19:00:00 1999-01-27 18:56:00  KORD  0.81
1 1999-01-27 20:00:00 1999-01-27 19:56:00  KORD  0.01
2 1999-01-27 21:00:00 1999-01-27 20:56:00  KORD -0.59
3 1999-01-27 21:00:00 1999-01-27 21:18:00  KORD -0.99
4 1999-01-27 22:00:00 1999-01-27 21:56:00  KORD -0.59
5 1999-01-27 23:00:00 1999-01-27 22:56:00  KORD -0.59

<p>It is important to remember that if multiple text columns are to be parsed into a single date column, then a new column is prepended to the data. The <code>index_col</code> specification is based off of this new set of columns rather than the original data columns:</p>

In [121]:
date_spec = {"nominal": [1, 2], "actual": [1, 3]}

In [122]:
df = pd.read_csv(
    "tmp.csv", header=None, parse_dates=date_spec, index_col=0
)  # index is the nominal column

/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_87177/4078987091.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df = pd.read_csv(

In [123]:
df

                                 actual     0     4
nominal
1999-01-27 19:00:00 1999-01-27 18:56:00  KORD  0.81
1999-01-27 20:00:00 1999-01-27 19:56:00  KORD  0.01
1999-01-27 21:00:00 1999-01-27 20:56:00  KORD -0.59
1999-01-27 21:00:00 1999-01-27 21:18:00  KORD -0.99
1999-01-27 22:00:00 1999-01-27 21:56:00  KORD -0.59
1999-01-27 23:00:00 1999-01-27 22:56:00  KORD -0.59

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If a column or index contains an unparsable date, the entire column or index will be returned unaltered as an object data type.
For non-standard datetime parsing, use <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html" title="pandas.to_datetime"><code>to_datetime()</code></a> after <code>pd.read_csv</code>.</p>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>read_csv has a fast_path for parsing datetime strings in iso8601 format, e.g “2000-01-01T00:01:02+00:00” and similar variations.
If you can arrange for your data to store datetimes in this format, load times will be significantly faster, ~20x has been observed.</p>
</div>

<div class="deprecated">
<p><span class="versionmodified deprecated">Deprecated since version 2.2.0: Combining date columns inside read_csv is deprecated.
Use <code>pd.to_datetime</code> on the relevant result columns instead.</p>
</div>

### <h4>Date parsing functions</h4>

<p>Finally, the parser allows you to specify a custom <code>date_format</code>.
Performance-wise, you should try these methods of parsing dates in order:</p>

<ol class="arabic simple">
<li><p>If you know the format, use <code>date_format</code>, e.g.: <code>date_format="%d/%m/%Y"</code> or <code>date_format={column_name: "%d/%m/%Y"}</code>.</p></li>
<li><p>If you different formats for different columns, or want to pass any extra options (such as <code>utc</code>) to <code>to_datetime</code>, then you should read in your data as <code>object</code> dtype, and then use <code>to_datetime</code>.</p></li>
</ol>

### <h4>Parsing a CSV with mixed timezones</h4>

<p>pandas cannot natively represent a column or index with mixed timezones. If your CSV file contains columns with a mixture of timezones, the default result will be an object-dtype column with strings, even with <code>parse_dates</code>.
To parse the mixed-timezone values as a datetime column, read in as <code>object</code> dtype and then call
<a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html" title="pandas.to_datetime"><code>to_datetime()</code></a> with <code>utc=True</code>.</p>

In [124]:
content = """\
a
2000-01-01T00:00:00+05:00
2000-01-01T00:00:00+06:00"""

In [125]:
df = pd.read_csv(StringIO(content))

In [126]:
df["a"] = pd.to_datetime(df["a"], utc=True)

In [127]:
df["a"]

0   1999-12-31 19:00:00+00:00
1   1999-12-31 18:00:00+00:00
Name: a, dtype: datetime64[ns, UTC]

### <h4>Inferring datetime format</h4>

<p>Here are some examples of datetime strings that can be guessed (all
representing December 30th, 2011 at 00:00:00):</p>
<ul class="simple">
<li><p>“20111230”</p></li>
<li><p>“2011/12/30”</p></li>
<li><p>“20111230 00:00:00”</p></li>
<li><p>“12/30/2011 00:00:00”</p></li>
<li><p>“30/Dec/2011 00:00:00”</p></li>
<li><p>“30/December/2011 00:00:00”</p></li>
</ul>
<p>Note that format inference is sensitive to <code>dayfirst</code>.  With <code>dayfirst=True</code>, it will guess “01/12/2011” to be December 1st. With <code>dayfirst=False</code> (default) it will guess “01/12/2011” to be January 12th.</p>

<p>If you try to parse a column of date strings, pandas will attempt to guess the format from the first non-NaN element, and will then parse the rest of the column with that format. If pandas fails to guess the format (for example if your first string is <code>'01 December US/Pacific 2000'</code>), then a warning will be raised and each row will be parsed individually by <code>dateutil.parser.parse</code>. The safest way to parse dates is to explicitly set <code>format=</code>.</p>

In [128]:
df = pd.read_csv(
    "foo.csv",
    index_col=0,
    parse_dates=True
)

In [129]:
df

            A  B  C
date
2009-01-01  a  1  2
2009-01-02  b  3  4
2009-01-03  c  4  5

<p>or, if your datetime formats are all ISO8601 (possibly not identically-formatted):</p>

In [130]:
data = StringIO("date\n12 Jan 2000\n2000-01-13\n")

In [131]:
df = pd.read_csv(data)

In [132]:
df['date'] = pd.to_datetime(df['date'], format='mixed')

In [133]:
df

        date
0 2000-01-12
1 2000-01-13

<p>In the case that you have mixed datetime formats within the same column, you can pass  <code>format='mixed'</code></p>

In [134]:
data = StringIO("date\n2020-01-01\n2020-01-01 03:00\n")

In [135]:
df = pd.read_csv(data)

In [136]:
df['date'] = pd.to_datetime(df['date'], format='ISO8601')

In [137]:
df

                 date
0 2020-01-01 00:00:00
1 2020-01-01 03:00:00

### <h4>International date formats</h4>

<p>While US date formats tend to be MM/DD/YYYY, many international formats use DD/MM/YYYY instead. For convenience, a <code>dayfirst</code> keyword is provided:</p>

In [138]:
data = "date,value,cat\n1/6/2000,5,a\n2/6/2000,10,b\n3/6/2000,15,c"

In [139]:
print(data)

date,value,cat
1/6/2000,5,a
2/6/2000,10,b
3/6/2000,15,c

In [140]:
with open("tmp.csv", "w") as fh:
    fh.write(data)

In [141]:
pd.read_csv("tmp.csv", parse_dates=[0])

        date  value cat
0 2000-01-06      5   a
1 2000-02-06     10   b
2 2000-03-06     15   c

In [142]:
pd.read_csv("tmp.csv", dayfirst=True, parse_dates=[0])

        date  value cat
0 2000-06-01      5   a
1 2000-06-02     10   b
2 2000-06-03     15   c

### <h4>Writing CSVs to binary file objects</h4>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.2.0.</p>
</div>

<p><code>df.to_csv(..., mode="wb")</code> allows writing a CSV to a file object opened binary mode. In most cases, it is not necessary to specify <code>mode</code> as Pandas will auto-detect whether the file object is opened in text or binary mode.</p>

In [143]:
import io

In [144]:
data = pd.DataFrame([0, 1, 2])

In [145]:
buffer = io.BytesIO()

In [146]:
data.to_csv(buffer, encoding="utf-8", compression="gzip")

## <h3>Specifying method for floating-point conversion</h3>

<p>The parameter <code>float_precision</code> can be specified in order to use a specific floating-point converter during parsing with the C engine. The options are the ordinary converter, the high-precision converter, and the round-trip converter (which is guaranteed to round-trip values after writing to a file). For example:</p>

In [208]:
val = "0.3066101993807095471566981359501369297504425048828125"

In [212]:
data = "a,b,c\n1,2,{0}".format(val)

In [213]:
print(data)

a,b,c
1,2,0.3066101993807095471566981359501369297504425048828125

In [222]:
abs(
    pd.read_csv(
        StringIO(data),
        engine='c',
        float_precision=None,
    )["c"][0] - float(val)
)

5.551115123125783e-17

In [223]:
abs(
    pd.read_csv(
        StringIO(data),
        engine='c',
        float_precision='high',
    )["c"][0] - float(val)
)

5.551115123125783e-17

In [224]:
abs(
    pd.read_csv(StringIO(data), engine="c", float_precision="round_trip")["c"][0]
    - float(val)
)

0.0

## <h3>Thousand separators</h3>

<p>For large numbers that have been written with a thousands separator, you can set the <code>thousands</code> keyword to a string of length 1 so that integers will be parsed correctly:</p>

<p>By default, numbers with a thousands separator will be parsed as strings:</p>

In [147]:
data = (
    "ID|level|category\n"
    "Patient1|123,000|x\n"
    "Patient2|23,000|y\n"
    "Patient3|1,234,018|z"
)

In [148]:
with open("tmp.csv", "w") as fh:
    fh.write(data)

In [149]:
df = pd.read_csv("tmp.csv", sep="|")

In [150]:
df

         ID      level category
0  Patient1    123,000        x
1  Patient2     23,000        y
2  Patient3  1,234,018        z

In [151]:
df.level.dtype

dtype('O')

<p>The <code>thousands</code> keyword allows integers to be parsed correctly:</p>

In [152]:
df = pd.read_csv("tmp.csv", sep="|", thousands=",")

In [153]:
df

         ID    level category
0  Patient1   123000        x
1  Patient2    23000        y
2  Patient3  1234018        z

In [154]:
df.level.dtype

dtype('int64')

## <h3>NA values</h3>

<p>To control which values are parsed as missing values (which are signified by <code>NaN</code>), specify a string in <code>na_values</code>. If you specify a list of strings, then all values in it are considered to be missing values.
If you specify a number (a <code>float</code>, like <code>5.0</code> or an <code>integer</code> like <code>5</code>), the corresponding equivalent values will also imply a missing value (in this case effectively <code>[5.0, 5]</code> are recognized as <code>NaN</code>).</p>

<p>To completely override the default values that are recognized as missing, specify <code>keep_default_na=False</code>.</p>

<p id="io-navaluesconst">The default <code>NaN</code> recognized values are <code>['-1.#IND', '1.#QNAN', '1.#IND', '-1.#QNAN', '#N/A N/A', '#N/A', 'N/A', 'n/a', 'NA', '&lt;NA&gt;', '#NA', 'NULL', 'null', 'NaN', '-NaN', 'nan', '-nan', 'None', '']</code>.</p>

<p>Let us consider some examples:</p>

In [155]:
pd.read_csv("path_to_file.csv", na_values=[5])

FileNotFoundError: [Errno 2] No such file or directory: 'path_to_file.csv'

<p>In the example above <code>5</code> and <code>5.0</code> will be recognized as <code>NaN</code>, in addition to the defaults.
A string will first be interpreted as a numerical <code>5</code>, then as a <code>NaN</code>.</p>

In [ ]:
pd.read_csv("path_to_file.csv", keep_default_na=False, na_values=[""])

<p>Above, only an empty field will be recognized as <code>NaN</code>.</p>

In [ ]:
pd.read_csv("path_to_file.csv", keep_default_na=False, na_values=["NA", "0"])

<p>Above, both <code>NA</code> and <code>0</code> as strings are <code>NaN</code>.</p>

In [ ]:
pd.read_csv("path_to_file.csv", na_values=["Nope"])

<p>The default values, in addition to the string <code>"Nope"</code> are recognized as <code>NaN</code>.</p>

## <h3>Infinity</h3>

<p><code>inf</code> like values will be parsed as <code>np.inf</code> (positive infinity), and <code>-inf</code> as <code>-np.inf</code> (negative infinity). These will ignore the case of the value, meaning <code>Inf</code>, will also be parsed as <code>np.inf</code>.</p>

## <h3>Boolean values</h3>

<p>The common values <code>True</code>, <code>False</code>, <code>TRUE</code>, and <code>FALSE</code> are all recognized as boolean. Occasionally you might want to recognize other values as being boolean. To do this, use the <code>true_values</code> and <code>false_values</code> options as follows:</p>

In [ ]:
data = "a,b,c\n1,Yes,2\n3,No,4"

In [ ]:
print(data)

In [ ]:
pd.read_csv(StringIO(data))

In [ ]:
pd.read_csv(StringIO(data), true_values=["Yes"], false_values=["No"])

## <h3>Handling “bad” lines</h3>

<p>Some files may have malformed lines with too few fields or too many. Lines with too few fields will have NA values filled in the trailing fields. Lines with too many fields will raise an error by default:</p>

In [ ]:
data = "a,b,c\n1,2,3\n4,5,6,7\n8,9,10"

In [ ]:
pd.read_csv(StringIO(data))

<p>You can elect to skip bad lines:</p>

In [ ]:
data = "a,b,c\n1,2,3\n4,5,6,7\n8,9,10"

In [ ]:
pd.read_csv(StringIO(data), on_bad_lines="skip")

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.4.0.</span></p>
</div>
<p>Or pass a callable function to handle the bad line if <code>engine="python"</code>.
The bad line will be a list of strings that was split by the <code>sep</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell51"><span></span><span class="gp">In [164]: </span><span class="n">external_list</span> <span class="o">=</span> <span class="p">[]</span>

<span class="gp">In [165]: </span><span class="k">def</span><span class="w"> </span><span class="nf">bad_lines_func</span><span class="p">(</span><span class="n">line</span><span class="p">):</span>
<span class="gp"></span>    <span class="n">external_list</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">line</span><span class="p">)</span>
<span class="gp"></span>    <span class="k">return</span> <span class="n">line</span><span class="p">[</span><span class="o">-</span><span class="mi">3</span><span class="p">:]</span>
<span class="gp"></span>

<span class="gp">In [166]: </span><span class="n">external_list</span>
<span class="gh">Out[166]: </span><span class="go">[]</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The callable function will handle only a line with too many fields. Bad lines caused by other errors will be silently skipped.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell52"><span></span><span class="gp">In [167]: </span><span class="n">bad_lines_func</span> <span class="o">=</span> <span class="k">lambda</span> <span class="n">line</span><span class="p">:</span> <span class="nb">print</span><span class="p">(</span><span class="n">line</span><span class="p">)</span>

<span class="gp">In [168]: </span><span class="n">data</span> <span class="o">=</span> <span class="s1">'name,type</span><span class="se">\n</span><span class="s1">name a,a is of type a</span><span class="se">\n</span><span class="s1">name b,"b</span><span class="se">\"</span><span class="s1"> is of type b"'</span>

<span class="gp">In [169]: </span><span class="n">data</span>
<span class="gh">Out[169]: </span><span class="go">'name,type\nname a,a is of type a\nname b,"b" is of type b"'</span>

<span class="gp">In [170]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">data</span><span class="p">),</span> <span class="n">on_bad_lines</span><span class="o">=</span><span class="n">bad_lines_func</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"python"</span><span class="p">)</span>
<span class="gh">Out[170]: </span>
<span class="go">     name            type</span>
<span class="go">0  name a  a is of type a</span>
</pre>
</div>
</div>

<p>The line was not processed in this case, as a “bad line” here is caused by an escape character.</p>
</div>
<p>You can also use the <code>usecols</code> parameter to eliminate extraneous column data that appear in some lines but not others:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell53"><span></span><span class="gp">In [171]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">data</span><span class="p">),</span> <span class="n">usecols</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">])</span>
<span class="gt">---------------------------------------------------------------------------</span>
<span class="ne">ValueError</span><span class="g g-Whitespace">                                </span>Traceback (most recent call last)
<span class="n">Cell</span> <span class="n">In</span><span class="p">[</span><span class="mi">171</span><span class="p">],</span> <span class="n">line</span> <span class="mi">1</span>
<span class="ne">----&gt; </span><span class="mi">1</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">data</span><span class="p">),</span> <span class="n">usecols</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">])</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/parsers/readers.py:1026,</span> in <span class="ni">read_csv</span><span class="nt">(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)</span>
<span class="g g-Whitespace">   </span><span class="mi">1013</span> <span class="n">kwds_defaults</span> <span class="o">=</span> <span class="n">_refine_defaults_read</span><span class="p">(</span>
<span class="g g-Whitespace">   </span><span class="mi">1014</span>     <span class="n">dialect</span><span class="p">,</span>
<span class="g g-Whitespace">   </span><span class="mi">1015</span>     <span class="n">delimiter</span><span class="p">,</span>
   <span class="p">(</span><span class="o">...</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">1022</span>     <span class="n">dtype_backend</span><span class="o">=</span><span class="n">dtype_backend</span><span class="p">,</span>
<span class="g g-Whitespace">   </span><span class="mi">1023</span> <span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">1024</span> <span class="n">kwds</span><span class="o">.</span><span class="n">update</span><span class="p">(</span><span class="n">kwds_defaults</span><span class="p">)</span>
<span class="ne">-&gt; </span><span class="mi">1026</span> <span class="k">return</span> <span class="n">_read</span><span class="p">(</span><span class="n">filepath_or_buffer</span><span class="p">,</span> <span class="n">kwds</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/parsers/readers.py:620,</span> in <span class="ni">_read</span><span class="nt">(filepath_or_buffer, kwds)</span>
<span class="g g-Whitespace">    </span><span class="mi">617</span> <span class="n">_validate_names</span><span class="p">(</span><span class="n">kwds</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="s2">"names"</span><span class="p">,</span> <span class="kc">None</span><span class="p">))</span>
<span class="g g-Whitespace">    </span><span class="mi">619</span> <span class="c1"># Create the parser.</span>
<span class="ne">--&gt; </span><span class="mi">620</span> <span class="n">parser</span> <span class="o">=</span> <span class="n">TextFileReader</span><span class="p">(</span><span class="n">filepath_or_buffer</span><span class="p">,</span> <span class="o">**</span><span class="n">kwds</span><span class="p">)</span>
<span class="g g-Whitespace">    </span><span class="mi">622</span> <span class="k">if</span> <span class="n">chunksize</span> <span class="ow">or</span> <span class="n">iterator</span><span class="p">:</span>
<span class="g g-Whitespace">    </span><span class="mi">623</span>     <span class="k">return</span> <span class="n">parser</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/parsers/readers.py:1620,</span> in <span class="ni">TextFileReader.__init__</span><span class="nt">(self, f, engine, **kwds)</span>
<span class="g g-Whitespace">   </span><span class="mi">1617</span>     <span class="bp">self</span><span class="o">.</span><span class="n">options</span><span class="p">[</span><span class="s2">"has_index_names"</span><span class="p">]</span> <span class="o">=</span> <span class="n">kwds</span><span class="p">[</span><span class="s2">"has_index_names"</span><span class="p">]</span>
<span class="g g-Whitespace">   </span><span class="mi">1619</span> <span class="bp">self</span><span class="o">.</span><span class="n">handles</span><span class="p">:</span> <span class="n">IOHandles</span> <span class="o">|</span> <span class="kc">None</span> <span class="o">=</span> <span class="kc">None</span>
<span class="ne">-&gt; </span><span class="mi">1620</span> <span class="bp">self</span><span class="o">.</span><span class="n">_engine</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_make_engine</span><span class="p">(</span><span class="n">f</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">engine</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/parsers/readers.py:1898,</span> in <span class="ni">TextFileReader._make_engine</span><span class="nt">(self, f, engine)</span>
<span class="g g-Whitespace">   </span><span class="mi">1895</span>     <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="n">msg</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">1897</span> <span class="k">try</span><span class="p">:</span>
<span class="ne">-&gt; </span><span class="mi">1898</span>     <span class="k">return</span> <span class="n">mapping</span><span class="p">[</span><span class="n">engine</span><span class="p">](</span><span class="n">f</span><span class="p">,</span> <span class="o">**</span><span class="bp">self</span><span class="o">.</span><span class="n">options</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">1899</span> <span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
<span class="g g-Whitespace">   </span><span class="mi">1900</span>     <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">handles</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/parsers/c_parser_wrapper.py:155,</span> in <span class="ni">CParserWrapper.__init__</span><span class="nt">(self, src, **kwds)</span>
<span class="g g-Whitespace">    </span><span class="mi">152</span>     <span class="c1"># error: Cannot determine type of 'names'</span>
<span class="g g-Whitespace">    </span><span class="mi">153</span>     <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">names</span><span class="p">)</span> <span class="o">&lt;</span> <span class="nb">len</span><span class="p">(</span><span class="n">usecols</span><span class="p">):</span>  <span class="c1"># type: ignore[has-type]</span>
<span class="g g-Whitespace">    </span><span class="mi">154</span>         <span class="c1"># error: Cannot determine type of 'names'</span>
<span class="ne">--&gt; </span><span class="mi">155</span>         <span class="bp">self</span><span class="o">.</span><span class="n">_validate_usecols_names</span><span class="p">(</span>
<span class="g g-Whitespace">    </span><span class="mi">156</span>             <span class="n">usecols</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">157</span>             <span class="bp">self</span><span class="o">.</span><span class="n">names</span><span class="p">,</span>  <span class="c1"># type: ignore[has-type]</span>
<span class="g g-Whitespace">    </span><span class="mi">158</span>         <span class="p">)</span>
<span class="g g-Whitespace">    </span><span class="mi">160</span> <span class="c1"># error: Cannot determine type of 'names'</span>
<span class="g g-Whitespace">    </span><span class="mi">161</span> <span class="bp">self</span><span class="o">.</span><span class="n">_validate_parse_dates_presence</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">names</span><span class="p">)</span>  <span class="c1"># type: ignore[has-type]</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/parsers/base_parser.py:988,</span> in <span class="ni">ParserBase._validate_usecols_names</span><span class="nt">(self, usecols, names)</span>
<span class="g g-Whitespace">    </span><span class="mi">986</span> <span class="n">missing</span> <span class="o">=</span> <span class="p">[</span><span class="n">c</span> <span class="k">for</span> <span class="n">c</span> <span class="ow">in</span> <span class="n">usecols</span> <span class="k">if</span> <span class="n">c</span> <span class="ow">not</span> <span class="ow">in</span> <span class="n">names</span><span class="p">]</span>
<span class="g g-Whitespace">    </span><span class="mi">987</span> <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">missing</span><span class="p">)</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">:</span>
<span class="ne">--&gt; </span><span class="mi">988</span>     <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span>
<span class="g g-Whitespace">    </span><span class="mi">989</span>         <span class="sa">f</span><span class="s2">"Usecols do not match columns, columns expected but not found: "</span>
<span class="g g-Whitespace">    </span><span class="mi">990</span>         <span class="sa">f</span><span class="s2">"</span><span class="si">{</span><span class="n">missing</span><span class="si">}</span><span class="s2">"</span>
<span class="g g-Whitespace">    </span><span class="mi">991</span>     <span class="p">)</span>
<span class="g g-Whitespace">    </span><span class="mi">993</span> <span class="k">return</span> <span class="n">usecols</span>

<span class="ne">ValueError</span>: Usecols do not match columns, columns expected but not found: [0, 1, 2]
</pre>
</div>
</div>

<p>In case you want to keep all data including the lines with too many fields, you can specify a sufficient number of <code>names</code>. This ensures that lines with not enough fields are filled with <code>NaN</code>.</p>

In [ ]:
pd.read_csv(StringIO(data), names=['a', 'b', 'c', 'd'])

## <h3>Dialect</h3>

<p>The <code>dialect</code> keyword gives greater flexibility in specifying the file format.
By default it uses the Excel dialect but you can specify either the dialect name or a
<a href="https://docs.python.org/3/library/csv.html#csv.Dialect" title="(in Python v3.13)"><code>csv.Dialect</code></a> instance.</p>

<p>Suppose you had data with unenclosed quotes:</p>

In [ ]:
data = "label1,label2,label3\n" 'index1,"a,c,e\n' "index2,b,d,f"

In [ ]:
print(data)

<p>By default, <code>read_csv</code> uses the Excel dialect and treats the double quote as the quote character, which causes it to fail when it finds a newline before it finds the closing double quote.</p>

<p>We can get around this using <code>dialect</code>:</p>

In [ ]:
import csv

In [ ]:
dia = csv.excel()

In [ ]:
dia.quoting = csv.QUOTE_NONE

In [ ]:
pd.read_csv(StringIO(data), dialect=dia)

<p>All of the dialect options can be specified separately by keyword arguments:</p>

In [ ]:
data = "a,b,c~1,2,3~4,5,6"

In [156]:
pd.read_csv(StringIO(data), lineterminator="~")

Empty DataFrame
Columns: [ID|level|category
Patient1|123, 000|x
Patient2|23, 000|y
Patient3|1, 234, 018|z]
Index: []

<p>Another common dialect option is <code>skipinitialspace</code>, to skip any whitespace after a delimiter:</p>

In [157]:
data = "a, b, c\n1, 2, 3\n4, 5, 6"

In [158]:
print(data)

a, b, c
1, 2, 3
4, 5, 6

In [159]:
pd.read_csv(StringIO(data), skipinitialspace=True)

   a  b  c
0  1  2  3
1  4  5  6

<p>The parsers make every attempt to “do the right thing” and not be fragile. Type inference is a pretty big deal. If a column can be coerced to integer dtype without altering the contents, the parser will do so. Any non-numeric columns will come through as object dtype as with the rest of pandas objects.</p>

## <h3>Quoting and Escape Characters</h3>

<p>Quotes (and other escape characters) in embedded fields can be handled in any number of ways. One way is to use backslashes; to properly parse this data, you should pass the <code>escapechar</code> option:</p>

In [160]:
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [161]:
print(data)

a,b
"hello, \"Bob\", nice to see you",5

In [162]:
pd.read_csv(StringIO(data), escapechar="\\")

                               a  b
0  hello, "Bob", nice to see you  5

## <h3>Files with fixed width columns</h3>

<p>While <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html" title="pandas.read_csv"><code>read_csv()</code></a> reads delimited data, the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html" title="pandas.read_fwf"><code>read_fwf()</code></a> function works with data files that have known and fixed column widths.
The function parameters to <code>read_fwf</code> are largely the same as <code>read_csv</code> with two extra parameters, and a different usage of the <code>delimiter</code> parameter:</p>

<ul class="simple">
<li><p><code>colspecs</code>: A list of pairs (tuples) giving the extents of the fixed-width fields of each line as half-open intervals (i.e.,  [from, to[ ). String value ‘infer’ can be used to instruct the parser to try detecting the column specifications from the first 100 rows of the data. Default behavior, if not specified, is to infer.</p></li>
<li><p><code>widths</code>: A list of field widths which can be used instead of ‘colspecs’ if the intervals are contiguous.</p></li>
<li><p><code>delimiter</code>: Characters to consider as filler characters in the fixed-width file.
Can be used to specify the filler character of the fields if it is not spaces (e.g., ‘~’).</p></li>
</ul>

<p>Consider a typical fixed-width data file:</p>

In [163]:
data1 = (
    "id8141    360.242940   149.910199   11950.7\n"
    "id1594    444.953632   166.985655   11788.4\n"
    "id1849    364.136849   183.628767   11806.2\n"
    "id1230    413.836124   184.375703   11916.8\n"
    "id1948    502.953953   173.237159   12468.3"
)

In [164]:
with open("bar.csv", "w") as f:
    f.write(data1)

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell60"><span></span><span class="gp">In [187]: </span><span class="n">data1</span> <span class="o">=</span> <span class="p">(</span>
<span class="gp"></span>    <span class="s2">"id8141    360.242940   149.910199   11950.7</span><span class="se">\n</span><span class="s2">"</span>
<span class="gp"></span>    <span class="s2">"id1594    444.953632   166.985655   11788.4</span><span class="se">\n</span><span class="s2">"</span>
<span class="gp"></span>    <span class="s2">"id1849    364.136849   183.628767   11806.2</span><span class="se">\n</span><span class="s2">"</span>
<span class="gp"></span>    <span class="s2">"id1230    413.836124   184.375703   11916.8</span><span class="se">\n</span><span class="s2">"</span>
<span class="gp"></span>    <span class="s2">"id1948    502.953953   173.237159   12468.3"</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [188]: </span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s2">"bar.csv"</span><span class="p">,</span> <span class="s2">"w"</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">f</span><span class="o">.</span><span class="n">write</span><span class="p">(</span><span class="n">data1</span><span class="p">)</span>
<span class="gp"></span>
</pre>
</div>
</div>

<p>In order to parse this file into a <code>DataFrame</code>, we simply need to supply the column specifications to the <code>read_fwf</code> function along with the file name:</p>

In [165]:
# Column specifications are a list of half-intervals

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell61"><span></span><span class="go"># Column specifications are a list of half-intervals</span>
<span class="gp">In [189]: </span><span class="n">colspecs</span> <span class="o">=</span> <span class="p">[(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">6</span><span class="p">),</span> <span class="p">(</span><span class="mi">8</span><span class="p">,</span> <span class="mi">20</span><span class="p">),</span> <span class="p">(</span><span class="mi">21</span><span class="p">,</span> <span class="mi">33</span><span class="p">),</span> <span class="p">(</span><span class="mi">34</span><span class="p">,</span> <span class="mi">43</span><span class="p">)]</span>

<span class="gp">In [190]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_fwf</span><span class="p">(</span><span class="s2">"bar.csv"</span><span class="p">,</span> <span class="n">colspecs</span><span class="o">=</span><span class="n">colspecs</span><span class="p">,</span> <span class="n">header</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>

<span class="gp">In [191]: </span><span class="n">df</span>
<span class="gh">Out[191]: </span>
<span class="go">                 1           2        3</span>
<span class="go">0                                      </span>
<span class="go">id8141  360.242940  149.910199  11950.7</span>
<span class="go">id1594  444.953632  166.985655  11788.4</span>
<span class="go">id1849  364.136849  183.628767  11806.2</span>
<span class="go">id1230  413.836124  184.375703  11916.8</span>
<span class="go">id1948  502.953953  173.237159  12468.3</span>
</pre>
</div>
</div>

<p>Note how the parser automatically picks column names X.&lt;column number&gt; when <code>header=None</code> argument is specified. Alternatively, you can supply just the column widths for contiguous columns:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell62"><span></span><span class="go"># Widths are a list of integers</span>
<span class="gp">In [192]: </span><span class="n">widths</span> <span class="o">=</span> <span class="p">[</span><span class="mi">6</span><span class="p">,</span> <span class="mi">14</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">10</span><span class="p">]</span>

<span class="gp">In [193]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_fwf</span><span class="p">(</span><span class="s2">"bar.csv"</span><span class="p">,</span> <span class="n">widths</span><span class="o">=</span><span class="n">widths</span><span class="p">,</span> <span class="n">header</span><span class="o">=</span><span class="kc">None</span><span class="p">)</span>

<span class="gp">In [194]: </span><span class="n">df</span>
<span class="gh">Out[194]: </span>
<span class="go">        0           1           2        3</span>
<span class="go">0  id8141  360.242940  149.910199  11950.7</span>
<span class="go">1  id1594  444.953632  166.985655  11788.4</span>
<span class="go">2  id1849  364.136849  183.628767  11806.2</span>
<span class="go">3  id1230  413.836124  184.375703  11916.8</span>
<span class="go">4  id1948  502.953953  173.237159  12468.3</span>
</pre>
</div>
</div>

<p>The parser will take care of extra white spaces around the columns so it’s ok to have extra separation between the columns in the file.</p>

<p>By default, <code>read_fwf</code> will try to infer the file’s <code>colspecs</code> by using the first 100 rows of the file. It can do it only in cases when the columns are aligned and correctly separated by the provided <code>delimiter</code> (default delimiter is whitespace).</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell63"><span></span><span class="gp">In [195]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_fwf</span><span class="p">(</span><span class="s2">"bar.csv"</span><span class="p">,</span> <span class="n">header</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>

<span class="gp">In [196]: </span><span class="n">df</span>
<span class="gh">Out[196]: </span>
<span class="go">                 1           2        3</span>
<span class="go">0                                      </span>
<span class="go">id8141  360.242940  149.910199  11950.7</span>
<span class="go">id1594  444.953632  166.985655  11788.4</span>
<span class="go">id1849  364.136849  183.628767  11806.2</span>
<span class="go">id1230  413.836124  184.375703  11916.8</span>
<span class="go">id1948  502.953953  173.237159  12468.3</span>
</pre>
</div>
</div>

<p><code>read_fwf</code> supports the <code>dtype</span></code> parameter for specifying the types of parsed columns to be different from the inferred type.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell64"><span></span><span class="gp">In [197]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_fwf</span><span class="p">(</span><span class="s2">"bar.csv"</span><span class="p">,</span> <span class="n">header</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[197]: </span>
<span class="go">1    float64</span>
<span class="go">2    float64</span>
<span class="go">3    float64</span>
<span class="go">dtype: object</span>

<span class="gp">In [198]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_fwf</span><span class="p">(</span><span class="s2">"bar.csv"</span><span class="p">,</span> <span class="n">header</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="p">{</span><span class="mi">2</span><span class="p">:</span> <span class="s2">"object"</span><span class="p">})</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[198]: </span>
<span class="go">0     object</span>
<span class="go">1    float64</span>
<span class="go">2     object</span>
<span class="go">3    float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

## <h3>Indexes</h3>

### <h4>Files with an “implicit” index column</h4>

<p>Consider a file with one less entry in the header than the number of data column:</p>

In [166]:
data = "A,B,C\n20090101,a,1,2\n20090102,b,3,4\n20090103,c,4,5"

In [167]:
print(data)

A,B,C
20090101,a,1,2
20090102,b,3,4
20090103,c,4,5

In [168]:
with open("foo.csv", "w") as f:
    f.write(data)

<p>In this special case, <code>read_csv</code> assumes that the first column is to be used as the index of the <code>DataFrame</code>:</p>

In [169]:
pd.read_csv("foo.csv")

          A  B  C
20090101  a  1  2
20090102  b  3  4
20090103  c  4  5

<p>Note that the dates weren’t automatically parsed. In that case you would need to do as before:</p>

In [170]:
df = pd.read_csv("foo.csv", parse_dates=True)

In [171]:
df.index

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03'], dtype='datetime64[ns]', freq=None)

### <h4>Reading an index with a <code>MultiIndex</code></h4>

<p id="io-csv-multiindex">Suppose you have data indexed by two columns:</p>

In [172]:
data = 'year,indiv,zit,xit\n1977,"A",1.2,.6\n1977,"B",1.5,.5'

In [173]:
print(data)

year,indiv,zit,xit
1977,"A",1.2,.6
1977,"B",1.5,.5

In [174]:
with open("mindex_ex.csv", mode="w") as f:
    f.write(data)

<p>The <code>index_col</code> argument to <code>read_csv</code> can take a list of column numbers to turn multiple columns into a <code>MultiIndex</code> for the index of the returned object:</p>

In [175]:
df = pd.read_csv("mindex_ex.csv", index_col=[0, 1])

In [176]:
df

            zit  xit
year indiv
1977 A      1.2  0.6
     B      1.5  0.5

In [177]:
df.loc[1977]

       zit  xit
indiv
A      1.2  0.6
B      1.5  0.5

### <h4>Reading columns with a <code>MultiIndex</code></h4>

<p>By specifying list of row locations for the <code>header</code> argument, you can read in a <code>MultiIndex</code> for the columns. Specifying non-consecutive rows will skip the intervening rows.</p>

In [178]:
mi_idx = pd.MultiIndex.from_arrays([[1, 2, 3, 4], list("abcd")], names=list("ab"))

In [179]:
mi_col = pd.MultiIndex.from_arrays([[1, 2], list("ab")], names=list("cd"))

In [182]:
df = pd.DataFrame(np.ones((4, 2)), index=mi_idx, columns=mi_col)

In [184]:
df.to_csv("mi.csv")

In [185]:
print(open("mi.csv").read())

c,,1,2
d,,a,b
a,b,,
1,a,1.0,1.0
2,b,1.0,1.0
3,c,1.0,1.0
4,d,1.0,1.0

In [190]:
pd.read_csv("mi.csv", header=[0, 1], index_col=[0, 1])

c      1    2
d      a    b
a b
1 a  1.0  1.0
2 b  1.0  1.0
3 c  1.0  1.0
4 d  1.0  1.0

<p><code>read_csv</code> is also able to interpret a more common format of multi-columns indices.</p>

In [192]:
data = ",a,a,a,b,c,c\n,q,r,s,t,u,v\none,1,2,3,4,5,6\ntwo,7,8,9,10,11,12"

In [193]:
print(data)

,a,a,a,b,c,c
,q,r,s,t,u,v
one,1,2,3,4,5,6
two,7,8,9,10,11,12

In [194]:
with open("mi2.csv", "w") as fh:
    fh.write(data)

In [195]:
pd.read_csv("mi2.csv", header=[0, 1], index_col=0)

     a         b   c
     q  r  s   t   u   v
one  1  2  3   4   5   6
two  7  8  9  10  11  12

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If an <code>index_col</code> is not specified (e.g. you don’t have an index, or wrote it with <code>df.to_csv(..., index=False)</code>, then any <code>names</code> on the columns index will be <em>lost</em>.</p>
</div>

## <h3>Automatically “sniffing” the delimiter</h3>

<p><code>read_csv</code> is capable of inferring delimited (not necessarily comma-separated) files, as pandas uses the
<a href="https://docs.python.org/3/library/csv.html#csv.Sniffer" title="(in Python v3.13)"><code>csv.Sniffer</code></a>
class of the csv module. For this, you have to specify <code>sep=None</code>.</p>

In [196]:
df = pd.DataFrame(np.random.randn(10, 4))

In [197]:
df.to_csv("tmp2.csv", sep=":", index=False)

In [198]:
pd.read_csv("tmp2.csv", sep=None, engine="python")

          0         1         2         3
0 -0.093891 -0.244431  0.320334  0.653058
1  0.131947 -1.939125  0.801211  0.787400
2  0.385827  0.106251  0.026817  0.766698
3  0.767070 -0.027245 -0.081091 -0.589929
4 -1.341561  0.497904  0.945239  0.216333
5 -0.191375 -1.571076 -2.062559  1.029346
6 -2.242638  0.175846 -1.046450 -0.468761
7 -1.471329  0.494932 -0.501807 -0.039943
8  0.090193 -1.603466  0.023050 -0.084687
9  0.563319 -0.502829 -0.490412  0.477442

## <h3>Reading multiple files to create a single DataFrame</h3>

<p>It’s best to use <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html" title="pandas.concat"><code>concat()</code></a> to combine multiple files. See the <a href="cookbook.html#cookbook-csv-multiple-files">cookbook</a> for an example.</p>

## <h3>Iterating through files chunk by chunk</h3>

<p>Suppose you wish to iterate through a (potentially very large) file lazily rather than reading the entire file into memory, such as the following:</p>

In [199]:
df = pd.DataFrame(np.random.randn(10, 4))

In [200]:
df.to_csv("tmp.csv", index=False)

In [201]:
table = pd.read_csv("tmp.csv")

In [202]:
table

          0         1         2         3
0 -0.409079 -1.001802 -1.604563 -0.746196
1  0.645220 -0.484783 -0.258055 -0.048784
2 -0.079875  1.077621 -1.909987 -1.375159
3 -0.098725  0.735927 -1.006878  0.046016
4 -1.457045 -2.398408  1.125994  0.563794
5  0.882572 -0.977353 -0.167917 -0.190714
6 -1.681271  1.934070  1.516589 -0.735237
7  0.013279 -0.971108 -0.382302  0.236761
8 -0.553534 -0.143275  2.321512 -1.160101
9  1.746495 -0.326085 -0.155900  0.217083

<p>By specifying a <code>chunksize</code> to <code>read_csv</code>, the return value will be an iterable object of type <code>TextFileReader</code>:</p>

In [203]:
with pd.read_csv("tmp.csv", chunksize=4) as reader:
    print(reader)
    for chunk in reader:
        print(chunk)

<pandas.io.parsers.readers.TextFileReader object at 0x18d9d5910>
          0         1         2         3
0 -0.409079 -1.001802 -1.604563 -0.746196
1  0.645220 -0.484783 -0.258055 -0.048784
2 -0.079875  1.077621 -1.909987 -1.375159
3 -0.098725  0.735927 -1.006878  0.046016
          0         1         2         3
4 -1.457045 -2.398408  1.125994  0.563794
5  0.882572 -0.977353 -0.167917 -0.190714
6 -1.681271  1.934070  1.516589 -0.735237
7  0.013279 -0.971108 -0.382302  0.236761
          0         1         2         3
8 -0.553534 -0.143275  2.321512 -1.160101
9  1.746495 -0.326085 -0.155900  0.217083

<div class="versionchanged">
<p>Changed in version 1.2: <code>read_csv/json/sas</code> return a context-manager when iterating through a file.</p>
</div>

<p>Specifying <code>iterator=True</code> will also return the <code>TextFileReader</code> object:</p>

In [207]:
with pd.read_csv("tmp.csv", iterator=True) as reader:
    print(reader.get_chunk(5))

          0         1         2         3
0 -0.409079 -1.001802 -1.604563 -0.746196
1  0.645220 -0.484783 -0.258055 -0.048784
2 -0.079875  1.077621 -1.909987 -1.375159
3 -0.098725  0.735927 -1.006878  0.046016
4 -1.457045 -2.398408  1.125994  0.563794

## <h3>Specifying the parser engine</h3>

<p>Pandas currently supports three engines, the C engine, the python engine, and an experimental pyarrow engine (requires the <code>pyarrow</code> package). In general, the pyarrow engine is fastest on larger workloads and is equivalent in speed to the C engine on most other workloads. The python engine tends to be slower than the pyarrow and C engines on most workloads. However, the pyarrow engine is much less robust than the C engine, which lacks a few features compared to the Python engine.</p>

<p>Where possible, pandas uses the C parser (specified as <code>engine='c'</code>), but it may fall back to Python if C-unsupported options are specified.</p>

<p>Currently, options unsupported by the C and pyarrow engines include:</p>

<ul class="simple">
<li><p><code>sep</code> other than a single character (e.g. regex separators)</p></li>
<li><p><code>skipfooter</code></p></li>
<li><p><code>sep=None</code> with <code>delim_whitespace=False</code></p></li>
</ul>

<p>Specifying any of the above options will produce a <code>ParserWarning</code> unless the python engine is selected explicitly using <code>engine='python'</code>.</p>

<p>Options that are unsupported by the pyarrow engine which are not covered by the list above include:</p>

<ul class="simple">
<li><p><code>float_precision</span></code></p></li>
<li><p><code>chunksize</span></code></p></li>
<li><p><code>comment</span></code></p></li>
<li><p><code>nrows</span></code></p></li>
<li><p><code>thousands</span></code></p></li>
<li><p><code>memory_map</span></code></p></li>
<li><p><code>dialect</span></code></p></li>
<li><p><code>on_bad_lines</span></code></p></li>
<li><p><code>delim_whitespace</span></code></p></li>
<li><p><code>quoting</span></code></p></li>
<li><p><code>lineterminator</span></code></p></li>
<li><p><code>converters</span></code></p></li>
<li><p><code>decimal</span></code></p></li>
<li><p><code>iterator</span></code></p></li>
<li><p><code>dayfirst</span></code></p></li>
<li><p><code>infer_datetime_format</span></code></p></li>
<li><p><code>verbose</span></code></p></li>
<li><p><code>skipinitialspace</span></code></p></li>
<li><p><code>low_memory</span></code></p></li>
</ul>

<p>Specifying these options with <code>engine='pyarrow'</code> will raise a <code>ValueError</code>.</p>

## <h3>Reading/writing remote files</h3>

<p>You can pass in a URL to read or write remote files to many of pandas’ IO functions - the following example shows reading a CSV file:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell76"><span></span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span><span class="s2">"https://download.bls.gov/pub/time.series/cu/cu.item"</span><span class="p">,</span> <span class="n">sep</span><span class="o">=</span><span class="s2">"</span><span class="se">\t</span><span class="s2">"</span><span class="p">)</span>
</pre>
</div>
</div>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.3.0.</span></p>
</div>

<p>A custom header can be sent alongside HTTP(s) requests by passing a dictionary of header key value mappings to the <code>storage_options</code> keyword argument as shown below:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell77"><span></span><span class="n">headers</span> <span class="o">=</span> <span class="p">{</span><span class="s2">"User-Agent"</span><span class="p">:</span> <span class="s2">"pandas"</span><span class="p">}</span>
<span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span>
    <span class="s2">"https://download.bls.gov/pub/time.series/cu/cu.item"</span><span class="p">,</span>
    <span class="n">sep</span><span class="o">=</span><span class="s2">"</span><span class="se">\t</span><span class="s2">"</span><span class="p">,</span>
    <span class="n">storage_options</span><span class="o">=</span><span class="n">headers</span>
<span class="p">)</span>
</pre>
</div>
</div>

<p>All URLs which are not local files or HTTP(s) are handled by <a href="https://filesystem-spec.readthedocs.io/en/latest/">fsspec</a>, if installed, and its various filesystem implementations (including Amazon S3, Google Cloud, SSH, FTP, webHDFS…).
Some of these implementations will require additional packages to be installed, for example S3 URLs require the
<a href="https://pypi.org/project/s3fs/">s3fs</a> library:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell78"><span></span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="s2">"s3://pandas-test/adatafile.json"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>When dealing with remote storage systems, you might need extra configuration with environment variables or config files in special locations. For example, to access data in your S3 bucket, you will need to define credentials in one of the several ways listed in
the <a href="https://s3fs.readthedocs.io/en/latest/#credentials">S3Fs documentation</a>. The same is true for several of the storage backends, and you should follow the links at <a href="https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations">fsimpl1</a> for implementations built into <code>fsspec</code> and <a href="https://filesystem-spec.readthedocs.io/en/latest/api.html#other-known-implementations">fsimpl2</a> for those not included in the main <code>fsspec</code> distribution.</p>

<p>You can also pass parameters directly to the backend driver. Since <code>fsspec</code> does not utilize the <code>AWS_S3_HOST</code> environment variable, we can directly define a dictionary containing the endpoint_url and pass the object into the storage option parameter:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell79"><span></span><span class="n">storage_options</span> <span class="o">=</span> <span class="p">{</span><span class="s2">"client_kwargs"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"endpoint_url"</span><span class="p">:</span> <span class="s2">"http://127.0.0.1:5555"</span><span class="p">}}}</span>
<span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="s2">"s3://pandas-test/test-1"</span><span class="p">,</span> <span class="n">storage_options</span><span class="o">=</span><span class="n">storage_options</span><span class="p">)</span>
</pre>
</div>
</div>

<p>More sample configurations and documentation can be found at <a href="https://s3fs.readthedocs.io/en/latest/index.html?highlight=host#s3-compatible-storage">S3Fs documentation</a>.</p>

<p>If you do <em>not</em> have S3 credentials, you can still access public data by specifying an anonymous connection, such as</p>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.2.0.</span></p>
</div>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell80"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span>
    <span class="s2">"s3://ncei-wcsd-archive/data/processed/SH1305/18kHz/SaKe2013"</span>
    <span class="s2">"-D20130523-T080854_to_SaKe2013-D20130523-T085643.csv"</span><span class="p">,</span>
    <span class="n">storage_options</span><span class="o">=</span><span class="p">{</span><span class="s2">"anon"</span><span class="p">:</span> <span class="kc">True</span><span class="p">},</span>
<span class="p">)</span>
</pre>
</div>
</div>

<p><code>fsspec</code> also allows complex URLs, for accessing data in compressed archives, local caching of files, and more.
To locally cache the above example, you would modify the call to</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell81"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span>
    <span class="s2">"simplecache::s3://ncei-wcsd-archive/data/processed/SH1305/18kHz/"</span>
    <span class="s2">"SaKe2013-D20130523-T080854_to_SaKe2013-D20130523-T085643.csv"</span><span class="p">,</span>
    <span class="n">storage_options</span><span class="o">=</span><span class="p">{</span><span class="s2">"s3"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"anon"</span><span class="p">:</span> <span class="kc">True</span><span class="p">}},</span>
<span class="p">)</span>
</pre>
</div>
</div>

<p>where we specify that the “anon” parameter is meant for the “s3” part of the implementation, not to the caching implementation.
Note that this caches to a temporary directory for the duration of the session only, but you can also specify a permanent store.</p>

## <h3>Writing out data</h3>

### <h4>Writing to CSV format</h4>

<p>The <code>Series</code> and <code>DataFrame</code> objects have an instance method <code>to_csv</code> which allows storing the contents of the object as a comma-separated-values file. The function takes a number of arguments. Only the first is required.</p>

<ul class="simple">
<li><p><code>path_or_buf</code>: A string path to the file to write or a file object.  If a file object it must be opened with <code>newline=''</code></p></li>
<li><p><code>sep</code> : Field delimiter for the output file (default “,”)</p></li>
<li><p><code>na_rep</code>: A string representation of a missing value (default ‘’)</p></li>
<li><p><code>float_format</code>: Format string for floating point numbers</p></li>
<li><p><code>columns</code>: Columns to write (default None)</p></li>
<li><p><code>header</code>: Whether to write out the column names (default True)</p></li>
<li><p><code>index</code>: whether to write row (index) names (default True)</p></li>
<li><p><code>index_label</code>: Column label(s) for index column(s) if desired. If None (default), and <code>header</code> and <code>index</code> are True, then the index names are used. (A sequence should be given if the <code>DataFrame</code> uses MultiIndex).</p></li>
<li><p><code>mode</code> : Python write mode, default ‘w’</p></li>
<li><p><code>encoding</code>: a string representing the encoding to use if the contents are non-ASCII, for Python versions prior to 3</p></li>
<li><p><code>lineterminator</code>: Character sequence denoting line end (default <code>os.linesep</code>)</p></li>
<li><p><code>quoting</code>: Set quoting rules as in csv module (default csv.QUOTE_MINIMAL). Note that if you have set a <code>float_format</code> then floats are converted to strings and csv.QUOTE_NONNUMERIC will treat them as non-numeric</p></li>
<li><p><code>quotechar</code>: Character used to quote fields (default ‘”’)</p></li>
<li><p><code>doublequote</code>: Control quoting of <code>quotechar</code> in fields (default True)</p></li>
<li><p><code>escapechar</code>: Character used to escape <code>sep</code> and <code>quotechar</code> when appropriate (default None)</p></li>
<li><p><code>chunksize</code>: Number of rows to write at a time</p></li>
<li><p><code>date_format</code>: Format string for datetime objects</p></li>
</ul>

### <h4>Writing a formatted string</h4>

<p id="io-formatting">The <code>DataFrame</code> object has an instance method <code>to_string</code> which allows control over the string representation of the object. All arguments are optional:</p>

<ul class="simple">
<li><p><code>buf</code> default None, for example a StringIO object</p></li>
<li><p><code>columns</code> default None, which columns to write</p></li>
<li><p><code>col_space</code> default None, minimum width of each column.</p></li>
<li><p><code>na_rep</code> default <code>NaN</code>, representation of NA value</p></li>
<li><p><code>formatters</code> default None, a dictionary (by column) of functions each of which takes a single argument and returns a formatted string</p></li>
<li><p><code>float_format</code> default None, a function which takes a single (float) argument and returns a formatted string; to be applied to floats in the <code>DataFrame</code>.</p></li>
<li><p><code>sparsify</code> default True, set to False for a <code>DataFrame</code> with a hierarchical index to print every MultiIndex key at each row.</p></li>
<li><p><code>index_names</code> default True, will print the names of the indices</p></li>
<li><p><code>index</code> default True, will print the index (ie, row labels)</p></li>
<li><p><code>header</code> default True, will print the column labels</p></li>
<li><p><code>justify</code> default <code>left</code>, will print column headers left- or right-justified</p></li>
</ul>

<p>The <code>Series</code> object also has a <code>to_string</code> method, but with only the <code>buf</code>, <code>na_rep</code>, <code>float_format</code> arguments. There is also a <code>length</code> argument which, if set to <code>True</code>, will additionally output the length of the Series.</p>

# <h2>JSON</h2>

<p>Read and write <code>JSON</code> format files and strings.</p>

## <h3>Writing JSON</h3>

<p>A <code>Series</code> or <code>DataFrame</code> can be converted to a valid JSON string.
Use <code>to_json</code> with optional parameters:</p>

<ul>
<li><p><code>path_or_buf</code> : the pathname or buffer to write the output.
This can be <code>None</code> in which case a JSON string is returned.</p></li>
<li><p><code>orient</code> :</p>
<dl class="simple">
<dt><code>Series</code>:</dt><dd><ul class="simple">
<li><p>default is <code>index</code></p></li>
<li><p>allowed values are {<code>split</code>, <code>records</code>, <code>index</code>}</p></li>
</ul>
</dd>
<dt><code>DataFrame</code>:</dt><dd><ul class="simple">
<li><p>default is <code>columns</code></p></li>
<li><p>allowed values are {<code>split</code>, <code>records</code>, <code>index</code>, <code>columns</code>, <code>values</code>, <code>table</code>}</p></li>
</ul>
</dd>
</dl>
<p>The format of the JSON string</p>
<table class="table">
<colgroup>
<col style="width: 11.8%">
<col style="width: 88.2%">
</colgroup>
<tbody>
<tr class="row-odd"><td><p><code>split</code></p></td>
<td><p>dict like {index -&gt; [index]; columns -&gt; [columns]; data -&gt; [values]}</p></td>
</tr>
<tr class="row-even"><td><p><code>records</code></p></td>
<td><p>list like [{column -&gt; value}; … ]</p></td>
</tr>
<tr class="row-odd"><td><p><code>index</code></p></td>
<td><p>dict like {index -&gt; {column -&gt; value}}</p></td>
</tr>
<tr class="row-even"><td><p><code>columns</code></p></td>
<td><p>dict like {column -&gt; {index -&gt; value}}</p></td>
</tr>
<tr class="row-odd"><td><p><code>values</code></p></td>
<td><p>just the values array</p></td>
</tr>
<tr class="row-even"><td><p><code>table</code></p></td>
<td><p>adhering to the JSON <a href="https://specs.frictionlessdata.io/table-schema/">Table Schema</a></p></td>
</tr>
</tbody>
</table>
</li>
<li><p><code>date_format</code> : string, type of date conversion, ‘epoch’ for timestamp, ‘iso’ for ISO8601.</p></li>
<li><p><code>double_precision</code> : The number of decimal places to use when encoding floating point values, default 10.</p></li>
<li><p><code>force_ascii</code> : force encoded string to be ASCII, default True.</p></li>
<li><p><code>date_unit</code> : The time unit to encode to, governs timestamp and ISO8601 precision. One of ‘s’, ‘ms’, ‘us’ or ‘ns’ for seconds, milliseconds, microseconds and nanoseconds respectively. Default ‘ms’.</p></li>
<li><p><code>default_handler</code> : The handler to call if an object cannot otherwise be converted to a suitable format for JSON. Takes a single argument, which is the object to convert, and returns a serializable object.</p></li>
<li><p><code>lines</code> : If <code>records</code> orient, then will write each record per line as json.</p></li>
<li><p><code>mode</code> : string, writer mode when writing to path. ‘w’ for write, ‘a’ for append. Default ‘w’</p></li>
</ul>

<p>Note <code>NaN</code>’s, <code>NaT</code>’s and <code>None</code> will be converted to <code>null</code> and <code>datetime</code> objects will be converted based on the <code>date_format</code> and <code>date_unit</code> parameters.</p>

In [225]:
dfj = pd.DataFrame(np.random.randn(5, 2), columns=list("AB"))

In [227]:
json = dfj.to_json()

In [228]:
json

'{"A":{"0":0.230361601,"1":-0.7075419094,"2":-1.2351020015,"3":-0.4919242986,"4":-0.315573622},"B":{"0":0.8956838974,"1":-1.0600397587,"2":0.5039836767,"3":0.5569086291,"4":0.9708851089}}'

### <h4>Orient options</h4>

<p>There are a number of different options for the format of the resulting JSON file / string. Consider the following <code>DataFrame</code> and <code>Series</code>:</p>

In [229]:
dfjo = pd.DataFrame(
    dict(A=range(1, 4), B=range(4, 7), C=range(7, 10)),
    columns=list("ABC"),
    index=list("xyz"),
)

In [230]:
dfjo

   A  B  C
x  1  4  7
y  2  5  8
z  3  6  9

In [231]:
sjo = pd.Series(dict(x=15, y=16, z=17), name="D")

In [232]:
sjo

x    15
y    16
z    17
Name: D, dtype: int64

<p><strong>Column oriented</strong> (the default for <code>DataFrame</code>) serializes the data as nested JSON objects with column labels acting as the primary index:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell84"><span></span><span class="gp">In [237]: </span><span class="n">dfjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"columns"</span><span class="p">)</span>
<span class="gh">Out[237]: </span><span class="go">'{"A":{"x":1,"y":2,"z":3},"B":{"x":4,"y":5,"z":6},"C":{"x":7,"y":8,"z":9}}'</span>

<span class="go"># Not available for Series</span>
</pre>
</div>
</div>

<p><strong>Index oriented</strong> (the default for <code>Series</code>) similar to column oriented but the index labels are now primary:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell85"><span></span><span class="gp">In [238]: </span><span class="n">dfjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"index"</span><span class="p">)</span>
<span class="gh">Out[238]: </span><span class="go">'{"x":{"A":1,"B":4,"C":7},"y":{"A":2,"B":5,"C":8},"z":{"A":3,"B":6,"C":9}}'</span>

<span class="gp">In [239]: </span><span class="n">sjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"index"</span><span class="p">)</span>
<span class="gh">Out[239]: </span><span class="go">'{"x":15,"y":16,"z":17}'</span>
</pre>
</div>
</div>
<p><strong>Record oriented</strong> serializes the data to a JSON array of column -&gt; value records,
index labels are not included. This is useful for passing <code>DataFrame</span></code> data to plotting
libraries, for example the JavaScript library <code>d3.js</span></code>:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell86"><span></span><span class="gp">In [240]: </span><span class="n">dfjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"records"</span><span class="p">)</span>
<span class="gh">Out[240]: </span><span class="go">'[{"A":1,"B":4,"C":7},{"A":2,"B":5,"C":8},{"A":3,"B":6,"C":9}]'</span>

<span class="gp">In [241]: </span><span class="n">sjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"records"</span><span class="p">)</span>
<span class="gh">Out[241]: </span><span class="go">'[15,16,17]'</span>
</pre>
</div>
</div>
<p><strong>Value oriented</strong> is a bare-bones option which serializes to nested JSON arrays of
values only, column and index labels are not included:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell87"><span></span><span class="gp">In [242]: </span><span class="n">dfjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"values"</span><span class="p">)</span>
<span class="gh">Out[242]: </span><span class="go">'[[1,4,7],[2,5,8],[3,6,9]]'</span>

<span class="go"># Not available for Series</span>
</pre>
</div>
</div>

<p><strong>Split oriented</strong> serializes to a JSON object containing separate entries for values, index and columns.
Name is also included for <code>Series</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell88"><span></span><span class="gp">In [243]: </span><span class="n">dfjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"split"</span><span class="p">)</span>
<span class="gh">Out[243]: </span><span class="go">'{"columns":["A","B","C"],"index":["x","y","z"],"data":[[1,4,7],[2,5,8],[3,6,9]]}'</span>

<span class="gp">In [244]: </span><span class="n">sjo</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"split"</span><span class="p">)</span>
<span class="gh">Out[244]: </span><span class="go">'{"name":"D","index":["x","y","z"],"data":[15,16,17]}'</span>
</pre>
</div>
</div>

<p><strong>Table oriented</strong> serializes to the JSON <a href="https://specs.frictionlessdata.io/table-schema/">Table Schema</a>, allowing for the preservation of metadata including but not limited to dtypes and index names.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Any orient option that encodes to a JSON object will not preserve the ordering of index and column labels during round-trip serialization. If you wish to preserve label ordering use the <code>split</span></code> option as it uses ordered containers.</p>
</div>

### <h4>Date handling</h4>

<p>Writing in ISO date format:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell89"><span></span><span class="gp">In [245]: </span><span class="n">dfd</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="s2">"AB"</span><span class="p">))</span>

<span class="gp">In [246]: </span><span class="n">dfd</span><span class="p">[</span><span class="s2">"date"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timestamp</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">)</span>

<span class="gp">In [247]: </span><span class="n">dfd</span> <span class="o">=</span> <span class="n">dfd</span><span class="o">.</span><span class="n">sort_index</span><span class="p">(</span><span class="n">axis</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">ascending</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>

<span class="gp">In [248]: </span><span class="n">json</span> <span class="o">=</span> <span class="n">dfd</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">date_format</span><span class="o">=</span><span class="s2">"iso"</span><span class="p">)</span>

<span class="gp">In [249]: </span><span class="n">json</span>
<span class="gh">Out[249]: </span><span class="go">'{"date":{"0":"2013-01-01T00:00:00.000","1":"2013-01-01T00:00:00.000","2":"2013-01-01T00:00:00.000","3":"2013-01-01T00:00:00.000","4":"2013-01-01T00:00:00.000"},"B":{"0":0.403309524,"1":0.3016244523,"2":-1.3698493577,"3":1.4626960492,"4":-0.8265909164},"A":{"0":0.1764443426,"1":-0.1549507744,"2":-2.1798606054,"3":-0.9542078401,"4":-1.7431609117}}'</span>
</pre>
</div>
</div>

<p>Writing in ISO date format, with microseconds:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell90"><span></span><span class="gp">In [250]: </span><span class="n">json</span> <span class="o">=</span> <span class="n">dfd</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">date_format</span><span class="o">=</span><span class="s2">"iso"</span><span class="p">,</span> <span class="n">date_unit</span><span class="o">=</span><span class="s2">"us"</span><span class="p">)</span>

<span class="gp">In [251]: </span><span class="n">json</span>
<span class="gh">Out[251]: </span><span class="go">'{"date":{"0":"2013-01-01T00:00:00.000000","1":"2013-01-01T00:00:00.000000","2":"2013-01-01T00:00:00.000000","3":"2013-01-01T00:00:00.000000","4":"2013-01-01T00:00:00.000000"},"B":{"0":0.403309524,"1":0.3016244523,"2":-1.3698493577,"3":1.4626960492,"4":-0.8265909164},"A":{"0":0.1764443426,"1":-0.1549507744,"2":-2.1798606054,"3":-0.9542078401,"4":-1.7431609117}}'</span>
</pre>
</div>
</div>

<p>Epoch timestamps, in seconds:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell91"><span></span><span class="gp">In [252]: </span><span class="n">json</span> <span class="o">=</span> <span class="n">dfd</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">date_format</span><span class="o">=</span><span class="s2">"epoch"</span><span class="p">,</span> <span class="n">date_unit</span><span class="o">=</span><span class="s2">"s"</span><span class="p">)</span>

<span class="gp">In [253]: </span><span class="n">json</span>
<span class="gh">Out[253]: </span><span class="go">'{"date":{"0":1,"1":1,"2":1,"3":1,"4":1},"B":{"0":0.403309524,"1":0.3016244523,"2":-1.3698493577,"3":1.4626960492,"4":-0.8265909164},"A":{"0":0.1764443426,"1":-0.1549507744,"2":-2.1798606054,"3":-0.9542078401,"4":-1.7431609117}}'</span>
</pre>
</div>
</div>

<p>Writing to a file, with a date index and a date column:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell92"><span></span><span class="gp">In [254]: </span><span class="n">dfj2</span> <span class="o">=</span> <span class="n">dfj</span><span class="o">.</span><span class="n">copy</span><span class="p">()</span>

<span class="gp">In [255]: </span><span class="n">dfj2</span><span class="p">[</span><span class="s2">"date"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timestamp</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">)</span>

<span class="gp">In [256]: </span><span class="n">dfj2</span><span class="p">[</span><span class="s2">"ints"</span><span class="p">]</span> <span class="o">=</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">5</span><span class="p">))</span>

<span class="gp">In [257]: </span><span class="n">dfj2</span><span class="p">[</span><span class="s2">"bools"</span><span class="p">]</span> <span class="o">=</span> <span class="kc">True</span>

<span class="gp">In [258]: </span><span class="n">dfj2</span><span class="o">.</span><span class="n">index</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">5</span><span class="p">)</span>

<span class="gp">In [259]: </span><span class="n">dfj2</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">)</span>

<span class="gp">In [260]: </span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">)</span> <span class="k">as</span> <span class="n">fh</span><span class="p">:</span>
<span class="gp"></span>    <span class="nb">print</span><span class="p">(</span><span class="n">fh</span><span class="o">.</span><span class="n">read</span><span class="p">())</span>
<span class="gp"></span>
<span class="go">{"A":{"1356998400000":-0.1213062281,"1357084800000":0.6957746499,"1357171200000":0.9597255933,"1357257600000":-0.6199759194,"1357344000000":-0.7323393705},"B":{"1356998400000":-0.0978826728,"1357084800000":0.3417343559,"1357171200000":-1.1103361029,"1357257600000":0.1497483186,"1357344000000":0.6877383895},"date":{"1356998400000":1356,"1357084800000":1356,"1357171200000":1356,"1357257600000":1356,"1357344000000":1356},"ints":{"1356998400000":0,"1357084800000":1,"1357171200000":2,"1357257600000":3,"1357344000000":4},"bools":{"1356998400000":true,"1357084800000":true,"1357171200000":true,"1357257600000":true,"1357344000000":true}}</span>
</pre>
</div>
</div>

### <h4>Fallback behavior</h4>

<p>If the JSON serializer cannot handle the container contents directly it will fall back in the following manner:</p>

<ul>
<li><p>if the dtype is unsupported (e.g. <code>np.complex_</code>) then the <code>default_handler</code>, if provided, will be called
for each value, otherwise an exception is raised.</p></li>
<li><p>if an object is unsupported it will attempt the following:</p>
<blockquote>
<div><ul class="simple">
<li><p>check if the object has defined a <code>toDict</span></code> method and call it.
A <code>toDict</span></code> method should return a <code>dict</span></code> which will then be JSON serialized.</p></li>
<li><p>invoke the <code>default_handler</span></code> if one was provided.</p></li>
<li><p>convert the object to a <code>dict</code> by traversing its contents. However this will often fail
with an <code>OverflowError</code> or give unexpected results.</p></li>
</ul>
</div></blockquote>
</li>
</ul>
    
<p>In general the best approach for unsupported objects or dtypes is to provide a <code>default_handler</code>. For example:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell93"><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">DataFrame</span><span class="p">([</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="nb">complex</span><span class="p">(</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">)])</span><span class="o">.</span><span class="n">to_json</span><span class="p">()</span>  <span class="c1"># raises</span>
<span class="go">RuntimeError: Unhandled numpy dtype 15</span>
</pre>
</div>
</div>

<p>can be dealt with by specifying a simple <code>default_handler</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell94"><span></span><span class="gp">In [261]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="nb">complex</span><span class="p">(</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">)])</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">default_handler</span><span class="o">=</span><span class="nb">str</span><span class="p">)</span>
<span class="gh">Out[261]: </span><span class="go">'{"0":{"0":"(1+0j)","1":"(2+0j)","2":"(1+2j)"}}'</span>
</pre>
</div>
</div>

## <h3>Reading JSON</h3>

<p>Reading a JSON string to pandas object can take a number of parameters. The parser will try to parse a <code>DataFrame</code> if <code>typ</code> is not supplied or is <code>None</code>. To explicitly force <code>Series</code> parsing, pass <code>typ=series</code></p>

<ul>
<li><p><code>filepath_or_buffer</span></code> : a <strong>VALID</strong> JSON string or file handle / StringIO. The string could be
a URL. Valid URL schemes include http, ftp, S3, and file. For file URLs, a host
is expected. For instance, a local file could be
file ://localhost/path/to/table.json</p></li>
<li><p><code>typ</span></code>    : type of object to recover (series or frame), default ‘frame’</p></li>
<li><p><code>orient</span></code> :</p>
<dl class="simple">
<dt>Series :</dt><dd><ul class="simple">
<li><p>default is <code>index</span></code></p></li>
<li><p>allowed values are {<code>split</span></code>, <code>records</span></code>, <code>index</span></code>}</p></li>
</ul>
</dd>
<dt>DataFrame</dt><dd><ul class="simple">
<li><p>default is <code>columns</span></code></p></li>
<li><p>allowed values are {<code>split</span></code>, <code>records</span></code>, <code>index</span></code>, <code>columns</span></code>, <code>values</span></code>, <code>table</span></code>}</p></li>
</ul>
</dd>
</dl>
<p>The format of the JSON string</p>
<table class="table">
<colgroup>
<col style="width: 11.8%">
<col style="width: 88.2%">
</colgroup>
<tbody>
<tr class="row-odd"><td><p><code>split</span></code></p></td>
<td><p>dict like {index -&gt; [index]; columns -&gt; [columns]; data -&gt; [values]}</p></td>
</tr>
<tr class="row-even"><td><p><code>records</span></code></p></td>
<td><p>list like [{column -&gt; value} …]</p></td>
</tr>
<tr class="row-odd"><td><p><code>index</span></code></p></td>
<td><p>dict like {index -&gt; {column -&gt; value}}</p></td>
</tr>
<tr class="row-even"><td><p><code>columns</span></code></p></td>
<td><p>dict like {column -&gt; {index -&gt; value}}</p></td>
</tr>
<tr class="row-odd"><td><p><code>values</span></code></p></td>
<td><p>just the values array</p></td>
</tr>
<tr class="row-even"><td><p><code>table</span></code></p></td>
<td><p>adhering to the JSON <a href="https://specs.frictionlessdata.io/table-schema/">Table Schema</a></p></td>
</tr>
</tbody>
</table>
</li>
<li><p><code>dtype</span></code> : if True, infer dtypes, if a dict of column to dtype, then use those, if <code>False</span></code>, then don’t infer dtypes at all, default is True, apply only to the data.</p></li>
<li><p><code>convert_axes</span></code> : boolean, try to convert the axes to the proper dtypes, default is <code>True</span></code></p></li>
<li><p><code>convert_dates</span></code> : a list of columns to parse for dates; If <code>True</span></code>, then try to parse date-like columns, default is <code>True</span></code>.</p></li>
<li><p><code>keep_default_dates</span></code> : boolean, default <code>True</span></code>. If parsing dates, then parse the default date-like columns.</p></li>
<li><p><code>precise_float</span></code> : boolean, default <code>False</span></code>. Set to enable usage of higher precision (strtod) function when decoding string to double values. Default (<code>False</span></code>) is to use fast but less precise builtin functionality.</p></li>
<li><p><code>date_unit</span></code> : string, the timestamp unit to detect if converting dates. Default None.
By default the timestamp precision will be detected, if this is not desired then pass one of ‘s’, ‘ms’, ‘us’ or ‘ns’ to force timestamp precision to seconds, milliseconds, microseconds or nanoseconds respectively.</p></li>
<li><p><code>lines</span></code> : reads file as one json object per line.</p></li>
<li><p><code>encoding</span></code> : The encoding to use to decode py3 bytes.</p></li>
<li><p><code>chunksize</span></code> : when used in combination with <code>lines=True</span></code>, return a <code>pandas.api.typing.JsonReader</span></code> which reads in <code>chunksize</span></code> lines per iteration.</p></li>
<li><p><code>engine</span></code>: Either <code>"ujson"</span></code>, the built-in JSON parser, or <code>"pyarrow"</span></code> which dispatches to pyarrow’s <code>pyarrow.json.read_json</span></code>.
The <code>"pyarrow"</span></code> is only available when <code>lines=True</span></code></p></li>
</ul>

<p>The parser will raise one of <code>ValueError/TypeError/AssertionError</code> if the JSON is not parseable.</p>

<p>If a non-default <code>orient</span></code> was used when encoding to JSON be sure to pass the same option here so that decoding produces sensible results, see <a href="#orient-options">Orient Options</a> for an overview.</p>

### <h4>Data conversion</h4>

<p>The default of <code>convert_axes=True</span></code>, <code>dtype=True</span></code>, and <code>convert_dates=True</span></code>
will try to parse the axes, and all of the data into appropriate types, including dates. If you need to override specific dtypes, pass a dict to <code>dtype</span></code>. <code>convert_axes</span></code> should only be set to <code>False</span></code> if you need to
preserve string-like numbers (e.g. ‘1’, ‘2’) in an axes.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Large integer values may be converted to dates if <code>convert_dates=True</span></code> and the data and / or column labels appear ‘date-like’. The exact threshold depends on the <code>date_unit</span></code> specified. ‘date-like’ means that the column label meets one of the following criteria:</p>
<ul class="simple">
<li><p>it ends with <code>'_at'</span></code></p></li>
<li><p>it ends with <code>'_time'</span></code></p></li>
<li><p>it begins with <code>'timestamp'</span></code></p></li>
<li><p>it is <code>'modified'</span></code></p></li>
<li><p>it is <code>'date'</span></code></p></li>
</ul>
</div>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>When reading JSON data, automatic coercing into dtypes has some quirks:</p>
<ul class="simple">
<li><p>an index can be reconstructed in a different order from serialization, that is, the returned order is not guaranteed to be the same as before serialization</p></li>
<li><p>a column that was <code>float</span></code> data will be converted to <code>integer</span></code> if it can be done safely, e.g. a column of <code>1.</span></code></p></li>
<li><p>bool columns will be converted to <code>integer</span></code> on reconstruction</p></li>
</ul>
<p>Thus there are times where you may want to specify specific dtypes via the <code>dtype</span></code> keyword argument.</p>
</div>

<p>Reading from a JSON string:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell95"><span></span><span class="gp">In [262]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">StringIO</span>

<span class="gp">In [263]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">json</span><span class="p">))</span>
<span class="gh">Out[263]: </span>
<span class="go">   date         B         A</span>
<span class="go">0     1  0.403310  0.176444</span>
<span class="go">1     1  0.301624 -0.154951</span>
<span class="go">2     1 -1.369849 -2.179861</span>
<span class="go">3     1  1.462696 -0.954208</span>
<span class="go">4     1 -0.826591 -1.743161</span>
</pre>
</div>
</div>

<p>Reading from a file:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell96"><span></span><span class="gp">In [264]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">)</span>
<span class="gh">Out[264]: </span>
<span class="go">                   A         B  date  ints  bools</span>
<span class="go">2013-01-01 -0.121306 -0.097883  1356     0   True</span>
<span class="go">2013-01-02  0.695775  0.341734  1356     1   True</span>
<span class="go">2013-01-03  0.959726 -1.110336  1356     2   True</span>
<span class="go">2013-01-04 -0.619976  0.149748  1356     3   True</span>
<span class="go">2013-01-05 -0.732339  0.687738  1356     4   True</span>
</pre>
</div>
</div>

<p>Don’t convert any data (but still convert axes and dates):</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell97"><span></span><span class="gp">In [265]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="nb">object</span><span class="p">)</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[265]: </span>
<span class="go">A        object</span>
<span class="go">B        object</span>
<span class="go">date     object</span>
<span class="go">ints     object</span>
<span class="go">bools    object</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Specify dtypes for conversion:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell98"><span></span><span class="gp">In [266]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="p">{</span><span class="s2">"A"</span><span class="p">:</span> <span class="s2">"float32"</span><span class="p">,</span> <span class="s2">"bools"</span><span class="p">:</span> <span class="s2">"int8"</span><span class="p">})</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[266]: </span>
<span class="go">A        float32</span>
<span class="go">B        float64</span>
<span class="go">date       int64</span>
<span class="go">ints       int64</span>
<span class="go">bools       int8</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Preserve string indices:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell99"><span></span><span class="gp">In [267]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">StringIO</span>

<span class="gp">In [268]: </span><span class="n">si</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">np</span><span class="o">.</span><span class="n">zeros</span><span class="p">((</span><span class="mi">4</span><span class="p">,</span> <span class="mi">4</span><span class="p">)),</span> <span class="n">columns</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">4</span><span class="p">)),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="nb">str</span><span class="p">(</span><span class="n">i</span><span class="p">)</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">4</span><span class="p">)]</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [269]: </span><span class="n">si</span>
<span class="gh">Out[269]: </span>
<span class="go">     0    1    2    3</span>
<span class="go">0  0.0  0.0  0.0  0.0</span>
<span class="go">1  0.0  0.0  0.0  0.0</span>
<span class="go">2  0.0  0.0  0.0  0.0</span>
<span class="go">3  0.0  0.0  0.0  0.0</span>

<span class="gp">In [270]: </span><span class="n">si</span><span class="o">.</span><span class="n">index</span>
<span class="gh">Out[270]: </span><span class="go">Index(['0', '1', '2', '3'], dtype='object')</span>

<span class="gp">In [271]: </span><span class="n">si</span><span class="o">.</span><span class="n">columns</span>
<span class="gh">Out[271]: </span><span class="go">Index([0, 1, 2, 3], dtype='int64')</span>

<span class="gp">In [272]: </span><span class="n">json</span> <span class="o">=</span> <span class="n">si</span><span class="o">.</span><span class="n">to_json</span><span class="p">()</span>

<span class="gp">In [273]: </span><span class="n">sij</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">json</span><span class="p">),</span> <span class="n">convert_axes</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>

<span class="gp">In [274]: </span><span class="n">sij</span>
<span class="gh">Out[274]: </span>
<span class="go">   0  1  2  3</span>
<span class="go">0  0  0  0  0</span>
<span class="go">1  0  0  0  0</span>
<span class="go">2  0  0  0  0</span>
<span class="go">3  0  0  0  0</span>

<span class="gp">In [275]: </span><span class="n">sij</span><span class="o">.</span><span class="n">index</span>
<span class="gh">Out[275]: </span><span class="go">Index(['0', '1', '2', '3'], dtype='object')</span>

<span class="gp">In [276]: </span><span class="n">sij</span><span class="o">.</span><span class="n">columns</span>
<span class="gh">Out[276]: </span><span class="go">Index(['0', '1', '2', '3'], dtype='object')</span>
</pre>
</div>
</div>

<p>Dates written in nanoseconds need to be read back in nanoseconds:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell100"><span></span><span class="gp">In [277]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">StringIO</span>

<span class="gp">In [278]: </span><span class="n">json</span> <span class="o">=</span> <span class="n">dfj2</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">date_unit</span><span class="o">=</span><span class="s2">"ns"</span><span class="p">)</span>

<span class="go"># Try to parse timestamps as milliseconds -&gt; Won't Work</span>
<span class="gp">In [279]: </span><span class="n">dfju</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">json</span><span class="p">),</span> <span class="n">date_unit</span><span class="o">=</span><span class="s2">"ms"</span><span class="p">)</span>

<span class="gp">In [280]: </span><span class="n">dfju</span>
<span class="gh">Out[280]: </span>
<span class="go">                            A         B        date  ints  bools</span>
<span class="go">1356998400000000000 -0.121306 -0.097883  1356998400     0   True</span>
<span class="go">1357084800000000000  0.695775  0.341734  1356998400     1   True</span>
<span class="go">1357171200000000000  0.959726 -1.110336  1356998400     2   True</span>
<span class="go">1357257600000000000 -0.619976  0.149748  1356998400     3   True</span>
<span class="go">1357344000000000000 -0.732339  0.687738  1356998400     4   True</span>

<span class="go"># Let pandas detect the correct precision</span>
<span class="gp">In [281]: </span><span class="n">dfju</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">json</span><span class="p">))</span>

<span class="gp">In [282]: </span><span class="n">dfju</span>
<span class="gh">Out[282]: </span>
<span class="go">                   A         B       date  ints  bools</span>
<span class="go">2013-01-01 -0.121306 -0.097883 2013-01-01     0   True</span>
<span class="go">2013-01-02  0.695775  0.341734 2013-01-01     1   True</span>
<span class="go">2013-01-03  0.959726 -1.110336 2013-01-01     2   True</span>
<span class="go">2013-01-04 -0.619976  0.149748 2013-01-01     3   True</span>
<span class="go">2013-01-05 -0.732339  0.687738 2013-01-01     4   True</span>

<span class="go"># Or specify that all timestamps are in nanoseconds</span>
<span class="gp">In [283]: </span><span class="n">dfju</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">json</span><span class="p">),</span> <span class="n">date_unit</span><span class="o">=</span><span class="s2">"ns"</span><span class="p">)</span>

<span class="gp">In [284]: </span><span class="n">dfju</span>
<span class="gh">Out[284]: </span>
<span class="go">                   A         B        date  ints  bools</span>
<span class="go">2013-01-01 -0.121306 -0.097883  1356998400     0   True</span>
<span class="go">2013-01-02  0.695775  0.341734  1356998400     1   True</span>
<span class="go">2013-01-03  0.959726 -1.110336  1356998400     2   True</span>
<span class="go">2013-01-04 -0.619976  0.149748  1356998400     3   True</span>
<span class="go">2013-01-05 -0.732339  0.687738  1356998400     4   True</span>
</pre>
</div>
</div>

<p>By setting the <code>dtype_backend</code> argument you can control the default dtypes used for the resulting DataFrame.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell101"><span></span><span class="gp">In [285]: </span><span class="n">data</span> <span class="o">=</span> <span class="p">(</span>
<span class="gp"></span> <span class="s1">'{"a":{"0":1,"1":3},"b":{"0":2.5,"1":4.5},"c":{"0":true,"1":false},"d":{"0":"a","1":"b"},'</span>
<span class="gp"></span> <span class="s1">'"e":{"0":null,"1":6.0},"f":{"0":null,"1":7.5},"g":{"0":null,"1":true},"h":{"0":null,"1":"a"},'</span>
<span class="gp"></span> <span class="s1">'"i":{"0":"12-31-2019","1":"12-31-2019"},"j":{"0":null,"1":null}}'</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [286]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">data</span><span class="p">),</span> <span class="n">dtype_backend</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>

<span class="gp">In [287]: </span><span class="n">df</span>
<span class="gh">Out[287]: </span>
<span class="go">   a    b      c  d     e     f     g     h           i     j</span>
<span class="go">0  1  2.5   True  a  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  12-31-2019  None</span>
<span class="go">1  3  4.5  False  b     6   7.5  True     a  12-31-2019  None</span>

<span class="gp">In [288]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[288]: </span>
<span class="go">a     int64[pyarrow]</span>
<span class="go">b    double[pyarrow]</span>
<span class="go">c      bool[pyarrow]</span>
<span class="go">d    string[pyarrow]</span>
<span class="go">e     int64[pyarrow]</span>
<span class="go">f    double[pyarrow]</span>
<span class="go">g      bool[pyarrow]</span>
<span class="go">h    string[pyarrow]</span>
<span class="go">i    string[pyarrow]</span>
<span class="go">j      null[pyarrow]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

## <h3>Normalization</h3>

<p>pandas provides a utility function to take a dict or list of dicts and <em>normalize</em> this semi-structured data into a flat table.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell102"><span></span><span class="gp">In [289]: </span><span class="n">data</span> <span class="o">=</span> <span class="p">[</span>
<span class="gp"></span>    <span class="p">{</span><span class="s2">"id"</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="s2">"name"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"first"</span><span class="p">:</span> <span class="s2">"Coleen"</span><span class="p">,</span> <span class="s2">"last"</span><span class="p">:</span> <span class="s2">"Volk"</span><span class="p">}},</span>
<span class="gp"></span>    <span class="p">{</span><span class="s2">"name"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"given"</span><span class="p">:</span> <span class="s2">"Mark"</span><span class="p">,</span> <span class="s2">"family"</span><span class="p">:</span> <span class="s2">"Regner"</span><span class="p">}},</span>
<span class="gp"></span>    <span class="p">{</span><span class="s2">"id"</span><span class="p">:</span> <span class="mi">2</span><span class="p">,</span> <span class="s2">"name"</span><span class="p">:</span> <span class="s2">"Faye Raker"</span><span class="p">},</span>
<span class="gp"></span><span class="p">]</span>
<span class="gp"></span>

<span class="gp">In [290]: </span><span class="n">pd</span><span class="o">.</span><span class="n">json_normalize</span><span class="p">(</span><span class="n">data</span><span class="p">)</span>
<span class="gh">Out[290]: </span>
<span class="go">    id name.first name.last name.given name.family        name</span>
<span class="go">0  1.0     Coleen      Volk        NaN         NaN         NaN</span>
<span class="go">1  NaN        NaN       NaN       Mark      Regner         NaN</span>
<span class="go">2  2.0        NaN       NaN        NaN         NaN  Faye Raker</span>
</pre>
</div>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell103"><span></span><span class="gp">In [291]: </span><span class="n">data</span> <span class="o">=</span> <span class="p">[</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"state"</span><span class="p">:</span> <span class="s2">"Florida"</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"shortname"</span><span class="p">:</span> <span class="s2">"FL"</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"info"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"governor"</span><span class="p">:</span> <span class="s2">"Rick Scott"</span><span class="p">},</span>
<span class="gp"></span>        <span class="s2">"county"</span><span class="p">:</span> <span class="p">[</span>
<span class="gp"></span>            <span class="p">{</span><span class="s2">"name"</span><span class="p">:</span> <span class="s2">"Dade"</span><span class="p">,</span> <span class="s2">"population"</span><span class="p">:</span> <span class="mi">12345</span><span class="p">},</span>
<span class="gp"></span>            <span class="p">{</span><span class="s2">"name"</span><span class="p">:</span> <span class="s2">"Broward"</span><span class="p">,</span> <span class="s2">"population"</span><span class="p">:</span> <span class="mi">40000</span><span class="p">},</span>
<span class="gp"></span>            <span class="p">{</span><span class="s2">"name"</span><span class="p">:</span> <span class="s2">"Palm Beach"</span><span class="p">,</span> <span class="s2">"population"</span><span class="p">:</span> <span class="mi">60000</span><span class="p">},</span>
<span class="gp"></span>        <span class="p">],</span>
<span class="gp"></span>    <span class="p">},</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"state"</span><span class="p">:</span> <span class="s2">"Ohio"</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"shortname"</span><span class="p">:</span> <span class="s2">"OH"</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"info"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"governor"</span><span class="p">:</span> <span class="s2">"John Kasich"</span><span class="p">},</span>
<span class="gp"></span>        <span class="s2">"county"</span><span class="p">:</span> <span class="p">[</span>
<span class="gp"></span>            <span class="p">{</span><span class="s2">"name"</span><span class="p">:</span> <span class="s2">"Summit"</span><span class="p">,</span> <span class="s2">"population"</span><span class="p">:</span> <span class="mi">1234</span><span class="p">},</span>
<span class="gp"></span>            <span class="p">{</span><span class="s2">"name"</span><span class="p">:</span> <span class="s2">"Cuyahoga"</span><span class="p">,</span> <span class="s2">"population"</span><span class="p">:</span> <span class="mi">1337</span><span class="p">},</span>
<span class="gp"></span>        <span class="p">],</span>
<span class="gp"></span>    <span class="p">},</span>
<span class="gp"></span><span class="p">]</span>
<span class="gp"></span>

<span class="gp">In [292]: </span><span class="n">pd</span><span class="o">.</span><span class="n">json_normalize</span><span class="p">(</span><span class="n">data</span><span class="p">,</span> <span class="s2">"county"</span><span class="p">,</span> <span class="p">[</span><span class="s2">"state"</span><span class="p">,</span> <span class="s2">"shortname"</span><span class="p">,</span> <span class="p">[</span><span class="s2">"info"</span><span class="p">,</span> <span class="s2">"governor"</span><span class="p">]])</span>
<span class="gh">Out[292]: </span>
<span class="go">         name  population    state shortname info.governor</span>
<span class="go">0        Dade       12345  Florida        FL    Rick Scott</span>
<span class="go">1     Broward       40000  Florida        FL    Rick Scott</span>
<span class="go">2  Palm Beach       60000  Florida        FL    Rick Scott</span>
<span class="go">3      Summit        1234     Ohio        OH   John Kasich</span>
<span class="go">4    Cuyahoga        1337     Ohio        OH   John Kasich</span>
</pre>
</div>
</div>

<p>The max_level parameter provides more control over which level to end normalization.
With max_level=1 the following snippet normalizes until 1st nesting level of the provided dict.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell104"><span></span><span class="gp">In [293]: </span><span class="n">data</span> <span class="o">=</span> <span class="p">[</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"CreatedBy"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"Name"</span><span class="p">:</span> <span class="s2">"User001"</span><span class="p">},</span>
<span class="gp"></span>        <span class="s2">"Lookup"</span><span class="p">:</span> <span class="p">{</span>
<span class="gp"></span>            <span class="s2">"TextField"</span><span class="p">:</span> <span class="s2">"Some text"</span><span class="p">,</span>
<span class="gp"></span>            <span class="s2">"UserField"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"Id"</span><span class="p">:</span> <span class="s2">"ID001"</span><span class="p">,</span> <span class="s2">"Name"</span><span class="p">:</span> <span class="s2">"Name001"</span><span class="p">},</span>
<span class="gp"></span>        <span class="p">},</span>
<span class="gp"></span>        <span class="s2">"Image"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"a"</span><span class="p">:</span> <span class="s2">"b"</span><span class="p">},</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">]</span>
<span class="gp"></span>

<span class="gp">In [294]: </span><span class="n">pd</span><span class="o">.</span><span class="n">json_normalize</span><span class="p">(</span><span class="n">data</span><span class="p">,</span> <span class="n">max_level</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="gh">Out[294]: </span>
<span class="go">  CreatedBy.Name Lookup.TextField                    Lookup.UserField Image.a</span>
<span class="go">0        User001        Some text  {'Id': 'ID001', 'Name': 'Name001'}       b</span>
</pre>
</div>
</div>

## <h3>Line delimited json</h3>

<p>pandas is able to read and write line-delimited json files that are common in data processing pipelines using Hadoop or Spark.</p>

<p>For line-delimited json files, pandas can also return an iterator which reads in <code>chunksize</code> lines at a time.
This can be useful for large files or to read from a stream.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell105"><span></span><span class="gp">In [295]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">StringIO</span>

<span class="gp">In [296]: </span><span class="n">jsonl</span> <span class="o">=</span> <span class="s2">"""</span>
<span class="gp"></span><span class="s2">    {"a": 1, "b": 2}</span>
<span class="gp"></span><span class="s2">    {"a": 3, "b": 4}</span>
<span class="gp"></span><span class="s2">"""</span>
<span class="gp"></span>

<span class="gp">In [297]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">jsonl</span><span class="p">),</span> <span class="n">lines</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="gp">In [298]: </span><span class="n">df</span>
<span class="gh">Out[298]: </span>
<span class="go">   a  b</span>
<span class="go">0  1  2</span>
<span class="go">1  3  4</span>

<span class="gp">In [299]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"records"</span><span class="p">,</span> <span class="n">lines</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
<span class="gh">Out[299]: </span><span class="go">'{"a":1,"b":2}\n{"a":3,"b":4}\n'</span>

<span class="go"># reader is an iterator that returns ``chunksize`` lines each iteration</span>
<span class="gp">In [300]: </span><span class="k">with</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">jsonl</span><span class="p">),</span> <span class="n">lines</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">chunksize</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span> <span class="k">as</span> <span class="n">reader</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">reader</span>
<span class="gp"></span>    <span class="k">for</span> <span class="n">chunk</span> <span class="ow">in</span> <span class="n">reader</span><span class="p">:</span>
<span class="gp"></span>        <span class="nb">print</span><span class="p">(</span><span class="n">chunk</span><span class="p">)</span>
<span class="gp"></span>
<span class="go">Empty DataFrame</span>
<span class="go">Columns: []</span>
<span class="go">Index: []</span>
<span class="go">   a  b</span>
<span class="go">0  1  2</span>
<span class="go">   a  b</span>
<span class="go">1  3  4</span>
</pre>
</div>
</div>

<p>Line-limited json can also be read using the pyarrow reader by specifying <code>engine="pyarrow"</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell106"><span></span><span class="gp">In [301]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">BytesIO</span>

<span class="gp">In [302]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="n">BytesIO</span><span class="p">(</span><span class="n">jsonl</span><span class="o">.</span><span class="n">encode</span><span class="p">()),</span> <span class="n">lines</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>

<span class="gp">In [303]: </span><span class="n">df</span>
<span class="gh">Out[303]: </span>
<span class="go">   a  b</span>
<span class="go">0  1  2</span>
<span class="go">1  3  4</span>
</pre>
</div>
</div>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 2.0.0.</span></p>
</div>

## <h3>Table schema</h3>

<p><a href="https://specs.frictionlessdata.io/table-schema/">Table Schema</a> is a spec for describing tabular datasets as a JSON
object. The JSON includes information on the field names, types, and other attributes. You can use the orient <code>table</code> to build a JSON string with two fields, <code>schema</code> and <code>data</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell107"><span></span><span class="gp">In [304]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"C"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"2016-01-01"</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"d"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">},</span>
<span class="gp"></span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">Index</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="n">name</span><span class="o">=</span><span class="s2">"idx"</span><span class="p">),</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [305]: </span><span class="n">df</span>
<span class="gh">Out[305]: </span>
<span class="go">     A  B          C</span>
<span class="go">idx                 </span>
<span class="go">0    1  a 2016-01-01</span>
<span class="go">1    2  b 2016-01-02</span>
<span class="go">2    3  c 2016-01-03</span>

<span class="gp">In [306]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="n">orient</span><span class="o">=</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">date_format</span><span class="o">=</span><span class="s2">"iso"</span><span class="p">)</span>
<span class="gh">Out[306]: </span><span class="go">'{"schema":{"fields":[{"name":"idx","type":"integer"},{"name":"A","type":"integer"},{"name":"B","type":"string"},{"name":"C","type":"datetime"}],"primaryKey":["idx"],"pandas_version":"1.4.0"},"data":[{"idx":0,"A":1,"B":"a","C":"2016-01-01T00:00:00.000"},{"idx":1,"A":2,"B":"b","C":"2016-01-02T00:00:00.000"},{"idx":2,"A":3,"B":"c","C":"2016-01-03T00:00:00.000"}]}'</span>
</pre>
</div>
</div>

<p>The <code>schema</code> field contains the <code>fields</code> key, which itself contains a list of column name to type pairs, including the <code>Index</span></code> or <code>MultiIndex</code> (see below for a list of types).
The <code>schema</code> field also contains a <code>primaryKey</code> field if the (Multi)index is unique.</p>

<p>The second field, <code>data</code>, contains the serialized data with the <code>records</code>
orient. The index is included, and any datetimes are ISO 8601 formatted, as required by the Table Schema spec.</p>

<p>The full list of types supported are described in the Table Schema spec. This table shows the mapping from pandas types:</p>

<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>pandas type</p></th>
<th class="head"><p>Table Schema type</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>int64</p></td>
<td><p>integer</p></td>
</tr>
<tr class="row-odd"><td><p>float64</p></td>
<td><p>number</p></td>
</tr>
<tr class="row-even"><td><p>bool</p></td>
<td><p>boolean</p></td>
</tr>
<tr class="row-odd"><td><p>datetime64[ns]</p></td>
<td><p>datetime</p></td>
</tr>
<tr class="row-even"><td><p>timedelta64[ns]</p></td>
<td><p>duration</p></td>
</tr>
<tr class="row-odd"><td><p>categorical</p></td>
<td><p>any</p></td>
</tr>
<tr class="row-even"><td><p>object</p></td>
<td><p>str</p></td>
</tr>
</tbody>
</table>

<p>A few notes on the generated table schema:</p>

<ul>
<li><p>The <code>schema</span></code> object contains a <code>pandas_version</span></code> field.
This contains the version of pandas’ dialect of the schema, and will be incremented with each revision.</p></li>
<li><p>All dates are converted to UTC when serializing. Even timezone naive values, which are treated as UTC with an offset of 0.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell108"><span></span><span class="gp">In [307]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">pandas.io.json</span><span class="w"> </span><span class="kn">import</span> <span class="n">build_table_schema</span>

<span class="gp">In [308]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"2016"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [309]: </span><span class="n">build_table_schema</span><span class="p">(</span><span class="n">s</span><span class="p">)</span>
<span class="gh">Out[309]: </span>
<span class="go">{'fields': [{'name': 'index', 'type': 'integer'},</span>
<span class="go">  {'name': 'values', 'type': 'datetime'}],</span>
<span class="go"> 'primaryKey': ['index'],</span>
<span class="go"> 'pandas_version': '1.4.0'}</span>
</pre>
</div>
</div>

</li>
<li><p>datetimes with a timezone (before serializing), include an additional field <code>tz</code> with the time zone name (e.g. <code>'US/Central'</code>).</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell109"><span></span><span class="gp">In [310]: </span><span class="n">s_tz</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"2016"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">12</span><span class="p">,</span> <span class="n">tz</span><span class="o">=</span><span class="s2">"US/Central"</span><span class="p">))</span>

<span class="gp">In [311]: </span><span class="n">build_table_schema</span><span class="p">(</span><span class="n">s_tz</span><span class="p">)</span>
<span class="gh">Out[311]: </span>
<span class="go">{'fields': [{'name': 'index', 'type': 'integer'},</span>
<span class="go">  {'name': 'values', 'type': 'datetime', 'tz': 'US/Central'}],</span>
<span class="go"> 'primaryKey': ['index'],</span>
<span class="go"> 'pandas_version': '1.4.0'}</span>
</pre>
</div>
</div>

</li>
<li><p>Periods are converted to timestamps before serialization, and so have the same behavior of being converted to UTC. In addition, periods will contain and additional field <code>freq</code> with the period’s frequency, e.g. <code>'A-DEC'</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell110"><span></span><span class="gp">In [312]: </span><span class="n">s_per</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">period_range</span><span class="p">(</span><span class="s2">"2016"</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"Y-DEC"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">))</span>

<span class="gp">In [313]: </span><span class="n">build_table_schema</span><span class="p">(</span><span class="n">s_per</span><span class="p">)</span>
<span class="gh">Out[313]: </span>
<span class="go">{'fields': [{'name': 'index', 'type': 'datetime', 'freq': 'YE-DEC'},</span>
<span class="go">  {'name': 'values', 'type': 'integer'}],</span>
<span class="go"> 'primaryKey': ['index'],</span>
<span class="go"> 'pandas_version': '1.4.0'}</span>
</pre>
</div>
</div>
</li>

<li><p>Categoricals use the <code>any</code> type and an <code>enum</code> constraint listing the set of possible values.
Additionally, an <code>ordered</code> field is included:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell111"><span></span><span class="gp">In [314]: </span><span class="n">s_cat</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">pd</span><span class="o">.</span><span class="n">Categorical</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">]))</span>

<span class="gp">In [315]: </span><span class="n">build_table_schema</span><span class="p">(</span><span class="n">s_cat</span><span class="p">)</span>
<span class="gh">Out[315]: </span>
<span class="go">{'fields': [{'name': 'index', 'type': 'integer'},</span>
<span class="go">  {'name': 'values',</span>
<span class="go">   'type': 'any',</span>
<span class="go">   'constraints': {'enum': ['a', 'b']},</span>
<span class="go">   'ordered': False}],</span>
<span class="go"> 'primaryKey': ['index'],</span>
<span class="go"> 'pandas_version': '1.4.0'}</span>
</pre>
</div>
</div>
</li>

<li><p>A <code>primaryKey</code> field, containing an array of labels, is included <em>if the index is unique</em>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell112"><span></span><span class="gp">In [316]: </span><span class="n">s_dupe</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">])</span>

<span class="gp">In [317]: </span><span class="n">build_table_schema</span><span class="p">(</span><span class="n">s_dupe</span><span class="p">)</span>
<span class="gh">Out[317]: </span>
<span class="go">{'fields': [{'name': 'index', 'type': 'integer'},</span>
<span class="go">  {'name': 'values', 'type': 'integer'}],</span>
<span class="go"> 'pandas_version': '1.4.0'}</span>
</pre>
</div>
</div>

</li>
<li><p>The <code>primaryKey</code> behavior is the same with MultiIndexes, but in this case the <code>primaryKey</code> is an array:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell113"><span></span><span class="gp">In [318]: </span><span class="n">s_multi</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_product</span><span class="p">([(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">),</span> <span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">)]))</span>

<span class="gp">In [319]: </span><span class="n">build_table_schema</span><span class="p">(</span><span class="n">s_multi</span><span class="p">)</span>
<span class="gh">Out[319]: </span>
<span class="go">{'fields': [{'name': 'level_0', 'type': 'string'},</span>
<span class="go">  {'name': 'level_1', 'type': 'integer'},</span>
<span class="go">  {'name': 'values', 'type': 'integer'}],</span>
<span class="go"> 'primaryKey': FrozenList(['level_0', 'level_1']),</span>
<span class="go"> 'pandas_version': '1.4.0'}</span>
</pre>
</div>
</div>

</li>
<li><p>The default naming roughly follows these rules:</p>
<blockquote>
<div><ul class="simple">
<li><p>For series, the <code>object.name</span></code> is used. If that’s none, then the
name is <code>values</span></code></p></li>
<li><p>For <code>DataFrames</span></code>, the stringified version of the column name is used</p></li>
<li><p>For <code>Index</span></code> (not <code>MultiIndex</span></code>), <code>index.name</span></code> is used, with a
fallback to <code>index</span></code> if that is None.</p></li>
<li><p>For <code>MultiIndex</span></code>, <code>mi.names</span></code> is used. If any level has no name,
then <code>level_&lt;i&gt;</span></code> is used.</p></li>
</ul>
</div></blockquote>
</li>
</ul>

<p><code>read_json</code> also accepts <code>orient='table'</code> as an argument. This allows for
the preservation of metadata such as dtypes and index names in a round-trippable manner.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell114"><span></span><span class="gp">In [320]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"foo"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"bar"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"baz"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"2018-01-01"</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"d"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">4</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"qux"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Categorical</span><span class="p">([</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">]),</span>
<span class="gp"></span>    <span class="p">},</span>
<span class="gp"></span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">Index</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">4</span><span class="p">),</span> <span class="n">name</span><span class="o">=</span><span class="s2">"idx"</span><span class="p">),</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [321]: </span><span class="n">df</span>
<span class="gh">Out[321]: </span>
<span class="go">     foo bar        baz qux</span>
<span class="go">idx                        </span>
<span class="go">0      1   a 2018-01-01   a</span>
<span class="go">1      2   b 2018-01-02   b</span>
<span class="go">2      3   c 2018-01-03   c</span>
<span class="go">3      4   d 2018-01-04   c</span>

<span class="gp">In [322]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[322]: </span>
<span class="go">foo             int64</span>
<span class="go">bar            object</span>
<span class="go">baz    datetime64[ns]</span>
<span class="go">qux          category</span>
<span class="go">dtype: object</span>

<span class="gp">In [323]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">,</span> <span class="n">orient</span><span class="o">=</span><span class="s2">"table"</span><span class="p">)</span>

<span class="gp">In [324]: </span><span class="n">new_df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">,</span> <span class="n">orient</span><span class="o">=</span><span class="s2">"table"</span><span class="p">)</span>

<span class="gp">In [325]: </span><span class="n">new_df</span>
<span class="gh">Out[325]: </span>
<span class="go">     foo bar        baz qux</span>
<span class="go">idx                        </span>
<span class="go">0      1   a 2018-01-01   a</span>
<span class="go">1      2   b 2018-01-02   b</span>
<span class="go">2      3   c 2018-01-03   c</span>
<span class="go">3      4   d 2018-01-04   c</span>

<span class="gp">In [326]: </span><span class="n">new_df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[326]: </span>
<span class="go">foo             int64</span>
<span class="go">bar            object</span>
<span class="go">baz    datetime64[ns]</span>
<span class="go">qux          category</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Please note that the literal string ‘index’ as the name of an <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html" title="pandas.Index"><code>Index</code></a> is not round-trippable, nor are any names beginning with <code>'level_'</code> within a
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a>.
These are used by default in <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html" title="pandas.DataFrame.to_json"><code>DataFrame.to_json()</code></a> to indicate missing values and the subsequent read cannot distinguish the intent.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell115"><span></span><span class="gp">In [327]: </span><span class="n">df</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">name</span> <span class="o">=</span> <span class="s2">"index"</span>

<span class="gp">In [328]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">,</span> <span class="n">orient</span><span class="o">=</span><span class="s2">"table"</span><span class="p">)</span>

<span class="gp">In [329]: </span><span class="n">new_df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_json</span><span class="p">(</span><span class="s2">"test.json"</span><span class="p">,</span> <span class="n">orient</span><span class="o">=</span><span class="s2">"table"</span><span class="p">)</span>

<span class="gp">In [330]: </span><span class="nb">print</span><span class="p">(</span><span class="n">new_df</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">name</span><span class="p">)</span>
<span class="go">None</span>
</pre>
</div>
</div>

<p>When using <code>orient='table'</code> along with user-defined <code>ExtensionArray</code>, the generated schema will contain an additional <code>extDtype</code> key in the respective <code>fields</code> element.
This extra key is not standard but does enable JSON roundtrips for extension types (e.g. <code>read_json(df.to_json(orient="table"), orient="table")</code>).</p>

<p>The <code>extDtype</code> key carries the name of the extension, if you have properly registered the <code>ExtensionDtype</code>, pandas will use said name to perform a lookup into the registry and re-convert the serialized data into your custom dtype.</p>

# <h2>HTML</h2>

## <h3>Reading HTML content</h3>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>We <strong>highly encourage</strong> you to read the <a href="https://pandas.pydata.org/docs/user_guide/io.html#io-html-gotchas">HTML Table Parsing gotchas</a> below regarding the issues surrounding the BeautifulSoup4/html5lib/lxml parsers.</p>
</div>

<p>The top-level <code>read_html()</code> function can accept an HTML string/file/URL and will parse HTML tables into list of pandas <code>DataFrames</code>. Let’s look at a few examples.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>read_html</code> returns a <code>list</code> of <code>DataFrame</code> objects, even if there is only a single table contained in the HTML content.</p>
</div>

<p>Read a URL with no options:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell116"><span></span><span class="gp">In [320]: </span><span class="n">url</span> <span class="o">=</span> <span class="s2">"https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list"</span>
<span class="gp">In [321]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">)</span>
<span class="gh">Out[321]:</span>
<span class="go">[                         Bank NameBank           CityCity StateSt  ...              Acquiring InstitutionAI Closing DateClosing FundFund</span>
<span class="go"> 0                    Almena State Bank             Almena      KS  ...                          Equity Bank    October 23, 2020    10538</span>
<span class="go"> 1           First City Bank of Florida  Fort Walton Beach      FL  ...            United Fidelity Bank, fsb    October 16, 2020    10537</span>
<span class="go"> 2                 The First State Bank      Barboursville      WV  ...                       MVB Bank, Inc.       April 3, 2020    10536</span>
<span class="go"> 3                   Ericson State Bank            Ericson      NE  ...           Farmers and Merchants Bank   February 14, 2020    10535</span>
<span class="go"> 4     City National Bank of New Jersey             Newark      NJ  ...                      Industrial Bank    November 1, 2019    10534</span>
<span class="go"> ..                                 ...                ...     ...  ...                                  ...                 ...      ...</span>
<span class="go"> 558                 Superior Bank, FSB           Hinsdale      IL  ...                Superior Federal, FSB       July 27, 2001     6004</span>
<span class="go"> 559                Malta National Bank              Malta      OH  ...                    North Valley Bank         May 3, 2001     4648</span>
<span class="go"> 560    First Alliance Bank &amp; Trust Co.         Manchester      NH  ...  Southern New Hampshire Bank &amp; Trust    February 2, 2001     4647</span>
<span class="go"> 561  National State Bank of Metropolis         Metropolis      IL  ...              Banterra Bank of Marion   December 14, 2000     4646</span>
<span class="go"> 562                   Bank of Honolulu           Honolulu      HI  ...                   Bank of the Orient    October 13, 2000     4645</span>

<span class="go"> [563 rows x 7 columns]]</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The data from the above URL changes every Monday so the resulting data above may be slightly different.</p>
</div>

<p>Read a URL while passing headers alongside the HTTP request:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell117"><span></span><span class="gp">In [322]: </span><span class="n">url</span> <span class="o">=</span> <span class="s1">'https://www.sump.org/notes/request/'</span> <span class="c1"># HTTP request reflector</span>
<span class="gp">In [323]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">)</span>
<span class="gh">Out[323]:</span>
<span class="go">[                   0                    1</span>
<span class="go"> 0     Remote Socket:  51.15.105.256:51760</span>
<span class="go"> 1  Protocol Version:             HTTP/1.1</span>
<span class="go"> 2    Request Method:                  GET</span>
<span class="go"> 3       Request URI:      /notes/request/</span>
<span class="go"> 4     Request Query:                  NaN,</span>
<span class="go"> 0   Accept-Encoding:             identity</span>
<span class="go"> 1              Host:         www.sump.org</span>
<span class="go"> 2        User-Agent:    Python-urllib/3.8</span>
<span class="go"> 3        Connection:                close]</span>
<span class="gp">In [324]: </span><span class="n">headers</span> <span class="o">=</span> <span class="p">{</span>
<span class="gp">In [325]: </span>   <span class="s1">'User-Agent'</span><span class="p">:</span><span class="s1">'Mozilla Firefox v14.0'</span><span class="p">,</span>
<span class="gp">In [326]: </span>   <span class="s1">'Accept'</span><span class="p">:</span><span class="s1">'application/json'</span><span class="p">,</span>
<span class="gp">In [327]: </span>   <span class="s1">'Connection'</span><span class="p">:</span><span class="s1">'keep-alive'</span><span class="p">,</span>
<span class="gp">In [328]: </span>   <span class="s1">'Auth'</span><span class="p">:</span><span class="s1">'Bearer 2*/f3+fe68df*4'</span>
<span class="gp">In [329]: </span><span class="p">}</span>
<span class="gp">In [340]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">storage_options</span><span class="o">=</span><span class="n">headers</span><span class="p">)</span>
<span class="gh">Out[340]:</span>
<span class="go">[                   0                    1</span>
<span class="go"> 0     Remote Socket:  51.15.105.256:51760</span>
<span class="go"> 1  Protocol Version:             HTTP/1.1</span>
<span class="go"> 2    Request Method:                  GET</span>
<span class="go"> 3       Request URI:      /notes/request/</span>
<span class="go"> 4     Request Query:                  NaN,</span>
<span class="go"> 0        User-Agent: Mozilla Firefox v14.0</span>
<span class="go"> 1    AcceptEncoding:   gzip,  deflate,  br</span>
<span class="go"> 2            Accept:      application/json</span>
<span class="go"> 3        Connection:             keep-alive</span>
<span class="go"> 4              Auth:  Bearer 2*/f3+fe68df*4]</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>We see above that the headers we passed are reflected in the HTTP request.</p>
</div>

<p>Read in the content of the file from the above URL and pass it to <code>read_html</code> as a string:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell118"><span></span><span class="gp">In [331]: </span><span class="n">html_str</span> <span class="o">=</span> <span class="s2">"""</span>
<span class="gp"></span><span class="s2">         &lt;table&gt;</span>
<span class="gp"></span><span class="s2">             &lt;tr&gt;</span>
<span class="gp"></span><span class="s2">                 &lt;th&gt;A&lt;/th&gt;</span>
<span class="gp"></span><span class="s2">                 &lt;th colspan="1"&gt;B&lt;/th&gt;</span>
<span class="gp"></span><span class="s2">                 &lt;th rowspan="1"&gt;C&lt;/th&gt;</span>
<span class="gp"></span><span class="s2">             &lt;/tr&gt;</span>
<span class="gp"></span><span class="s2">             &lt;tr&gt;</span>
<span class="gp"></span><span class="s2">                 &lt;td&gt;a&lt;/td&gt;</span>
<span class="gp"></span><span class="s2">                 &lt;td&gt;b&lt;/td&gt;</span>
<span class="gp"></span><span class="s2">                 &lt;td&gt;c&lt;/td&gt;</span>
<span class="gp"></span><span class="s2">             &lt;/tr&gt;</span>
<span class="gp"></span><span class="s2">         &lt;/table&gt;</span>
<span class="gp"></span><span class="s2">     """</span>
<span class="gp"></span>

<span class="gp">In [332]: </span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s2">"tmp.html"</span><span class="p">,</span> <span class="s2">"w"</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">f</span><span class="o">.</span><span class="n">write</span><span class="p">(</span><span class="n">html_str</span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [333]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="s2">"tmp.html"</span><span class="p">)</span>

<span class="gp">In [334]: </span><span class="n">df</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span>
<span class="gh">Out[334]: </span>
<span class="go">   A  B  C</span>
<span class="go">0  a  b  c</span>
</pre>
</div>
</div>

<p>You can even pass in an instance of <code>StringIO</code> if you so desire:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell119"><span></span><span class="gp">In [335]: </span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">html_str</span><span class="p">))</span>

<span class="gp">In [336]: </span><span class="n">dfs</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span>
<span class="gh">Out[336]: </span>
<span class="go">   A  B  C</span>
<span class="go">0  a  b  c</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The following examples are not run by the IPython evaluator due to the fact that having so many network-accessing functions slows down the documentation build. If you spot an error or an example that doesn’t run, please do not hesitate to report it over on
<a href="https://github.com/pandas-dev/pandas/issues">pandas GitHub issues page</a>.</p>
</div>

<p>Read a URL and match a table that contains specific text:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell120"><span></span><span class="n">match</span> <span class="o">=</span> <span class="s2">"Metcalf Bank"</span>
<span class="n">df_list</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">match</span><span class="o">=</span><span class="n">match</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Specify a header row (by default <code>&lt;th&gt;</code> or <code>&lt;td&gt;</code> elements located within a <code>&lt;thead&gt;</code> are used to form the column index, if multiple rows are contained within <code>&lt;thead&gt;</code> then a MultiIndex is created); if specified, the header row is taken from the data minus the parsed header elements (<code>&lt;th&gt;</span></code> elements).</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell121"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">header</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Specify an index column:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell122"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Specify a number of rows to skip:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell123"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">skiprows</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Specify a number of rows to skip using a list (<code>range</code> works as well):</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell124"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">skiprows</span><span class="o">=</span><span class="nb">range</span><span class="p">(</span><span class="mi">2</span><span class="p">))</span>
</pre>
</div>
</div>

<p>Specify an HTML attribute:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell125"><span></span><span class="n">dfs1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">attrs</span><span class="o">=</span><span class="p">{</span><span class="s2">"id"</span><span class="p">:</span> <span class="s2">"table"</span><span class="p">})</span>
<span class="n">dfs2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">attrs</span><span class="o">=</span><span class="p">{</span><span class="s2">"class"</span><span class="p">:</span> <span class="s2">"sortable"</span><span class="p">})</span>
<span class="nb">print</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">array_equal</span><span class="p">(</span><span class="n">dfs1</span><span class="p">[</span><span class="mi">0</span><span class="p">],</span> <span class="n">dfs2</span><span class="p">[</span><span class="mi">0</span><span class="p">]))</span>  <span class="c1"># Should be True</span>
</pre>
</div>
</div>

<p>Specify values that should be converted to NaN:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell126"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">na_values</span><span class="o">=</span><span class="p">[</span><span class="s2">"No Acquirer"</span><span class="p">])</span>
</pre>
</div>
</div>

<p>Specify whether to keep the default set of NaN values:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell127"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">keep_default_na</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Specify converters for columns. This is useful for numerical text data that has leading zeros.  By default columns that are numerical are cast to numeric types and the leading zeros are lost. To avoid this, we can convert these columns to strings.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell128"><span></span><span class="n">url_mcc</span> <span class="o">=</span> <span class="s2">"https://en.wikipedia.org/wiki/Mobile_country_code?oldid=899173761"</span>
<span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span>
    <span class="n">url_mcc</span><span class="p">,</span>
    <span class="n">match</span><span class="o">=</span><span class="s2">"Telekom Albania"</span><span class="p">,</span>
    <span class="n">header</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span>
    <span class="n">converters</span><span class="o">=</span><span class="p">{</span><span class="s2">"MNC"</span><span class="p">:</span> <span class="nb">str</span><span class="p">},</span>
<span class="p">)</span>
</pre>
</div>
</div>

<p>Use some combination of the above:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell129"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="n">match</span><span class="o">=</span><span class="s2">"Metcalf Bank"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Read in pandas <code>to_html</code> output (with some loss of floating point precision):</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell130"><span></span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">2</span><span class="p">))</span>
<span class="n">s</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">(</span><span class="n">float_format</span><span class="o">=</span><span class="s2">"</span><span class="si">{0:.40g}</span><span class="s2">"</span><span class="o">.</span><span class="n">format</span><span class="p">)</span>
<span class="n">dfin</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
</pre>
</div>
</div>

<p>The <code>lxml</code> backend will raise an error on a failed parse if that is the only parser you provide. If you only have a single parser you can provide just a string, but it is considered good practice to pass a list with one string if, for example, the function expects a sequence of strings. You may use:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell131"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="s2">"Metcalf Bank"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">flavor</span><span class="o">=</span><span class="p">[</span><span class="s2">"lxml"</span><span class="p">])</span>
</pre>
</div>
</div>

<p>Or you could pass <code>flavor='lxml'</code> without a list:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell132"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="s2">"Metcalf Bank"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">flavor</span><span class="o">=</span><span class="s2">"lxml"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>However, if you have bs4 and html5lib installed and pass <code>None</code> or <code>['lxml', 'bs4']</code> then the parse will most likely succeed. Note that <em>as soon as a parse succeeds, the function will return</em>.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell133"><span></span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span><span class="n">url</span><span class="p">,</span> <span class="s2">"Metcalf Bank"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">flavor</span><span class="o">=</span><span class="p">[</span><span class="s2">"lxml"</span><span class="p">,</span> <span class="s2">"bs4"</span><span class="p">])</span>
</pre>
</div>
</div>

<p>Links can be extracted from cells along with the text using <code>extract_links="all"</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell134"><span></span><span class="gp">In [337]: </span><span class="n">html_table</span> <span class="o">=</span> <span class="s2">"""</span>
<span class="gp"></span><span class="s2">&lt;table&gt;</span>
<span class="gp"></span><span class="s2">  &lt;tr&gt;</span>
<span class="gp"></span><span class="s2">    &lt;th&gt;GitHub&lt;/th&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/tr&gt;</span>
<span class="gp"></span><span class="s2">  &lt;tr&gt;</span>
<span class="gp"></span><span class="s2">    &lt;td&gt;&lt;a href="https://github.com/pandas-dev/pandas"&gt;pandas&lt;/a&gt;&lt;/td&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/tr&gt;</span>
<span class="gp"></span><span class="s2">&lt;/table&gt;</span>
<span class="gp"></span><span class="s2">"""</span>
<span class="gp"></span>

<span class="gp">In [338]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_html</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">StringIO</span><span class="p">(</span><span class="n">html_table</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">extract_links</span><span class="o">=</span><span class="s2">"all"</span>
<span class="gp"></span><span class="p">)[</span><span class="mi">0</span><span class="p">]</span>
<span class="gp"></span>

<span class="gp">In [339]: </span><span class="n">df</span>
<span class="gh">Out[339]: </span>
<span class="go">                                   (GitHub, None)</span>
<span class="go">0  (pandas, https://github.com/pandas-dev/pandas)</span>

<span class="gp">In [340]: </span><span class="n">df</span><span class="p">[(</span><span class="s2">"GitHub"</span><span class="p">,</span> <span class="kc">None</span><span class="p">)]</span>
<span class="gh">Out[340]: </span>
<span class="go">0    (pandas, https://github.com/pandas-dev/pandas)</span>
<span class="go">Name: (GitHub, None), dtype: object</span>

<span class="gp">In [341]: </span><span class="n">df</span><span class="p">[(</span><span class="s2">"GitHub"</span><span class="p">,</span> <span class="kc">None</span><span class="p">)]</span><span class="o">.</span><span class="n">str</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span>
<span class="gh">Out[341]: </span>
<span class="go">0    https://github.com/pandas-dev/pandas</span>
<span class="go">Name: (GitHub, None), dtype: object</span>
</pre>
</div>
</div>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.5.0.</span></p>
</div>

## <h3>Writing to HTML files</h3>

<p><code>DataFrame</code> objects have an instance method <code>to_html</code> which renders the contents of the <code>DataFrame</code> as an HTML table. The function arguments are as in the method <code>to_string</code> described above.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Not all of the possible options for <code>DataFrame.to_html</code> are shown here for
brevity’s sake. See <code>DataFrame.to_html()</code> for the full set of options.</p>
</div>
                                                            
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>In an HTML-rendering supported environment like a Jupyter Notebook, <code>display(HTML(...))</code> will render the raw HTML into the environment.</p>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell135"><span></span><span class="gp">In [342]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">IPython.display</span><span class="w"> </span><span class="kn">import</span> <span class="n">display</span><span class="p">,</span> <span class="n">HTML</span>

<span class="gp">In [343]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">2</span><span class="p">))</span>

<span class="gp">In [344]: </span><span class="n">df</span>
<span class="gh">Out[344]: </span>
<span class="go">          0         1</span>
<span class="go">0 -0.345352  1.314232</span>
<span class="go">1  0.690579  0.995761</span>

<span class="gp">In [345]: </span><span class="n">html</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">()</span>

<span class="gp">In [346]: </span><span class="nb">print</span><span class="p">(</span><span class="n">html</span><span class="p">)</span>  <span class="c1"># raw html</span>
<span class="go">&lt;table border="1" class="dataframe"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;-0.345352&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;1.314232&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;0.690579&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;0.995761&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>

<span class="gp">In [347]: </span><span class="n">display</span><span class="p">(</span><span class="n">HTML</span><span class="p">(</span><span class="n">html</span><span class="p">))</span>
<span class="go">&lt;IPython.core.display.HTML object&gt;</span>
</pre>
</div>
</div>

<p>The <code>columns</code> argument will limit the columns shown:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell136"><span></span><span class="gp">In [348]: </span><span class="n">html</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">(</span><span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>

<span class="gp">In [349]: </span><span class="nb">print</span><span class="p">(</span><span class="n">html</span><span class="p">)</span>
<span class="go">&lt;table border="1" class="dataframe"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;-0.345352&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;0.690579&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>

<span class="gp">In [350]: </span><span class="n">display</span><span class="p">(</span><span class="n">HTML</span><span class="p">(</span><span class="n">html</span><span class="p">))</span>
<span class="go">&lt;IPython.core.display.HTML object&gt;</span>
</pre>
</div>
</div>

<p><code>float_format</code> takes a Python callable to control the precision of floating point values:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell137"><span></span><span class="gp">In [351]: </span><span class="n">html</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">(</span><span class="n">float_format</span><span class="o">=</span><span class="s2">"</span><span class="si">{0:.10f}</span><span class="s2">"</span><span class="o">.</span><span class="n">format</span><span class="p">)</span>

<span class="gp">In [352]: </span><span class="nb">print</span><span class="p">(</span><span class="n">html</span><span class="p">)</span>
<span class="go">&lt;table border="1" class="dataframe"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;-0.3453521949&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;1.3142323796&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;0.6905793352&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;0.9957609037&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>

<span class="gp">In [353]: </span><span class="n">display</span><span class="p">(</span><span class="n">HTML</span><span class="p">(</span><span class="n">html</span><span class="p">))</span>
<span class="go">&lt;IPython.core.display.HTML object&gt;</span>
</pre>
</div>
</div>

<p><code>bold_rows</code> will make the row labels bold by default, but you can turn that off:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell138"><span></span><span class="gp">In [354]: </span><span class="n">html</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">(</span><span class="n">bold_rows</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>

<span class="gp">In [355]: </span><span class="nb">print</span><span class="p">(</span><span class="n">html</span><span class="p">)</span>
<span class="go">&lt;table border="1" class="dataframe"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;td&gt;0&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;-0.345352&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;1.314232&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;td&gt;1&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;0.690579&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;0.995761&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>

<span class="gp">In [356]: </span><span class="n">display</span><span class="p">(</span><span class="n">HTML</span><span class="p">(</span><span class="n">html</span><span class="p">))</span>
<span class="go">&lt;IPython.core.display.HTML object&gt;</span>
</pre>
</div>
</div>

<p>The <code>classes</code> argument provides the ability to give the resulting HTML table CSS classes. Note that these classes are <em>appended</em> to the existing <code>'dataframe'</code> class.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell139"><span></span><span class="gp">In [357]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">(</span><span class="n">classes</span><span class="o">=</span><span class="p">[</span><span class="s2">"awesome_table_class"</span><span class="p">,</span> <span class="s2">"even_more_awesome_class"</span><span class="p">]))</span>
<span class="go">&lt;table border="1" class="dataframe awesome_table_class even_more_awesome_class"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;-0.345352&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;1.314232&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;0.690579&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;0.995761&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>
</pre>
</div>
</div>

<p>The <code>render_links</code> argument provides the ability to add hyperlinks to cells that contain URLs.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell140"><span></span><span class="gp">In [358]: </span><span class="n">url_df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"name"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"Python"</span><span class="p">,</span> <span class="s2">"pandas"</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"url"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"https://www.python.org/"</span><span class="p">,</span> <span class="s2">"https://pandas.pydata.org"</span><span class="p">],</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [359]: </span><span class="n">html</span> <span class="o">=</span> <span class="n">url_df</span><span class="o">.</span><span class="n">to_html</span><span class="p">(</span><span class="n">render_links</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="gp">In [360]: </span><span class="nb">print</span><span class="p">(</span><span class="n">html</span><span class="p">)</span>
<span class="go">&lt;table border="1" class="dataframe"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;name&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;url&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;Python&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;&lt;a href="https://www.python.org/" target="_blank"&gt;https://www.python.org/&lt;/a&gt;&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;pandas&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;&lt;a href="https://pandas.pydata.org" target="_blank"&gt;https://pandas.pydata.org&lt;/a&gt;&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>

<span class="gp">In [361]: </span><span class="n">display</span><span class="p">(</span><span class="n">HTML</span><span class="p">(</span><span class="n">html</span><span class="p">))</span>
<span class="go">&lt;IPython.core.display.HTML object&gt;</span>
</pre>
</div>
</div>
<p>Finally, the <code>escape</span></code> argument allows you to control whether the
“&lt;”, “&gt;” and “&amp;” characters escaped in the resulting HTML (by default it is
<code>True</span></code>). So to get the HTML without escaped characters pass <code>escape=False</span></code></p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell141"><span></span><span class="gp">In [362]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"&amp;&lt;&gt;"</span><span class="p">),</span> <span class="s2">"b"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">3</span><span class="p">)})</span>
</pre>
</div>
</div>

<p>Escaped:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell142"><span></span><span class="gp">In [363]: </span><span class="n">html</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">()</span>

<span class="gp">In [364]: </span><span class="nb">print</span><span class="p">(</span><span class="n">html</span><span class="p">)</span>
<span class="go">&lt;table border="1" class="dataframe"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;a&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;b&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;&amp;amp;&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;2.396780&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;&amp;lt;&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;0.014871&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;2&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;&amp;gt;&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;3.357427&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>

<span class="gp">In [365]: </span><span class="n">display</span><span class="p">(</span><span class="n">HTML</span><span class="p">(</span><span class="n">html</span><span class="p">))</span>
<span class="go">&lt;IPython.core.display.HTML object&gt;</span>
</pre>
</div>
</div>

<p>Not escaped:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell143"><span></span><span class="gp">In [366]: </span><span class="n">html</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">to_html</span><span class="p">(</span><span class="n">escape</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>

<span class="gp">In [367]: </span><span class="nb">print</span><span class="p">(</span><span class="n">html</span><span class="p">)</span>
<span class="go">&lt;table border="1" class="dataframe"&gt;</span>
<span class="go">  &lt;thead&gt;</span>
<span class="go">    &lt;tr style="text-align: right;"&gt;</span>
<span class="go">      &lt;th&gt;&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;a&lt;/th&gt;</span>
<span class="go">      &lt;th&gt;b&lt;/th&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/thead&gt;</span>
<span class="go">  &lt;tbody&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;0&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;&amp;&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;2.396780&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;1&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;&lt;&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;0.014871&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">    &lt;tr&gt;</span>
<span class="go">      &lt;th&gt;2&lt;/th&gt;</span>
<span class="go">      &lt;td&gt;&gt;&lt;/td&gt;</span>
<span class="go">      &lt;td&gt;3.357427&lt;/td&gt;</span>
<span class="go">    &lt;/tr&gt;</span>
<span class="go">  &lt;/tbody&gt;</span>
<span class="go">&lt;/table&gt;</span>

<span class="gp">In [368]: </span><span class="n">display</span><span class="p">(</span><span class="n">HTML</span><span class="p">(</span><span class="n">html</span><span class="p">))</span>
<span class="go">&lt;IPython.core.display.HTML object&gt;</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Some browsers may not show a difference in the rendering of the previous two
HTML tables.</p>
</div>

## <h3>HTML Table Parsing Gotchas</h3>

<p>There are some versioning issues surrounding the libraries that are used to parse HTML tables in the top-level pandas io function <code>read_html</code>.</p>

<p><strong>Issues with</strong> <a href="https://lxml.de"><strong>lxml</strong></a></p>

<ul>
<li><p>Benefits</p>
<blockquote>
<div><ul class="simple">
<li><p><a href="https://lxml.de"><strong>lxml</strong></a> is very fast.</p></li>
<li><p><a href="https://lxml.de"><strong>lxml</strong></a> requires Cython to install correctly.</p></li>
</ul>
</div></blockquote>
</li>
<li><p>Drawbacks</p>
<blockquote>
<div><ul class="simple">
<li><p><a href="https://lxml.de"><strong>lxml</strong></a> does <em>not</em> make any guarantees about the results of its parse
<em>unless</em> it is given <a href="https://validator.w3.org/docs/help.html#validation_basics"><strong>strictly valid markup</strong></a>.</p></li>
<li><p>In light of the above, we have chosen to allow you, the user, to use the
<a href="https://lxml.de"><strong>lxml</strong></a> backend, but <strong>this backend will use</strong>
<a href="https://github.com/html5lib/html5lib-python"><strong>html5lib</strong></a> if <a href="https://lxml.de"><strong>lxml</strong></a>
fails to parse</p></li>
<li><p>It is therefore <em>highly recommended</em> that you install both
<a href="https://www.crummy.com/software/BeautifulSoup"><strong>BeautifulSoup4</strong></a> and
<a href="https://github.com/html5lib/html5lib-python"><strong>html5lib</strong></a>, so that you will still get a valid result (provided everything else is valid) even if <a href="https://lxml.de"><strong>lxml</strong></a> fails.</p></li>
</ul>
</div></blockquote>
</li>
</ul>

<p><strong>Issues with</strong> <a href="https://www.crummy.com/software/BeautifulSoup"><strong>BeautifulSoup4</strong></a> 
<strong>using</strong> <a href="https://lxml.de"><strong>lxml</strong></a> <strong>as a backend</strong></p>

<ul class="simple">
<li><p>The above issues hold here as well since <a href="https://www.crummy.com/software/BeautifulSoup"><strong>BeautifulSoup4</strong></a> is essentially
just a wrapper around a parser backend.</p></li>
</ul>

<p><strong>Issues with</strong> <a href="https://www.crummy.com/software/BeautifulSoup"><strong>BeautifulSoup4</strong></a> <strong>using</strong> <a href="https://github.com/html5lib/html5lib-python"><strong>html5lib</strong></a> <strong>as a backend</strong></p>

<ul>
<li><p>Benefits</p>
<blockquote>
<div><ul class="simple">
<li><p><a href="https://github.com/html5lib/html5lib-python"><strong>html5lib</strong></a> is far more lenient than <a href="https://lxml.de"><strong>lxml</strong></a> and consequently deals with <em>real-life markup</em> in a much saner way rather than just, e.g., dropping an element without notifying you.</p></li>
<li><p><a href="https://github.com/html5lib/html5lib-python"><strong>html5lib</strong></a> <em>generates valid HTML5 markup from invalid markup automatically</em>. This is extremely important for parsing HTML tables, since it guarantees a valid document. However, that does NOT mean that it is “correct”, since the process of fixing markup does not have a single definition.</p></li>
<li><p><a href="https://github.com/html5lib/html5lib-python"><strong>html5lib</strong></a> is pure Python and requires no additional build steps beyond its own installation.</p></li>
</ul>
</div></blockquote>
</li>
<li><p>Drawbacks</p>
<blockquote>
<div><ul class="simple">
<li><p>The biggest drawback to using <a href="https://github.com/html5lib/html5lib-python"><strong>html5lib</strong></a> is that it is slow as molasses.  However consider the fact that many tables on the web are not big enough for the parsing algorithm runtime to matter.
It is more likely that the bottleneck will be in the process of reading the raw text from the URL over the web, i.e., IO (input-output).
For very large tables, this might not be true.</p></li>
</ul>
</div></blockquote>
</li>
</ul>

# <h2>LaTeX</h2>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.3.0.</span></p>
</div>

<p>Currently there are no methods to read from LaTeX, only output methods.</p>

## <h3>Writing to LaTeX files</h3>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>DataFrame <em>and</em> Styler objects currently have a <code>to_latex</code> method. We recommend using the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_latex.html">Styler.to_latex()</a> method over
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_latex.html">DataFrame.to_latex()</a> due to the former’s greater flexibility with conditional styling, and the latter’s possible future deprecation.</p>
</div>

<p>Review the documentation for
<a href="https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_latex.html">Styler.to_latex</a>, which gives examples of conditional styling and explains the operation of its keyword arguments.</p>

<p>For simple application the following pattern is sufficient.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell144"><span></span><span class="gp">In [369]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]],</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">])</span>

<span class="gp">In [370]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">style</span><span class="o">.</span><span class="n">to_latex</span><span class="p">())</span>
<span class="go">\begin{tabular}{lrr}</span>
<span class="go"> &amp; c &amp; d \\</span>
<span class="go">a &amp; 1 &amp; 2 \\</span>
<span class="go">b &amp; 3 &amp; 4 \\</span>
<span class="go">\end{tabular}</span>
</pre>
</div>
</div>

<p>To format values before output, chain the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.format.html">Styler.format</a> method.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell145"><span></span><span class="gp">In [371]: </span><span class="nb">print</span><span class="p">(</span><span class="n">df</span><span class="o">.</span><span class="n">style</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="s2">"€ </span><span class="si">{}</span><span class="s2">"</span><span class="p">)</span><span class="o">.</span><span class="n">to_latex</span><span class="p">())</span>
<span class="go">\begin{tabular}{lrr}</span>
<span class="go"> &amp; c &amp; d \\</span>
<span class="go">a &amp; € 1 &amp; € 2 \\</span>
<span class="go">b &amp; € 3 &amp; € 4 \\</span>
<span class="go">\end{tabular}</span>
</pre>
</div>
</div>

# <h2>XML</h2>

## <h3>Reading XML</h3>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.3.0.</span></p>
</div>

<p>The top-level <code>read_xml()</code> function can accept an XML string/file/URL and will parse nodes and attributes into a pandas <code>DataFrame</code>.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Since there is no standard XML structure where design types can vary in many ways, <code>read_xml</code> works best with flatter, shallow versions. If an XML document is deeply nested, use the <code>stylesheet</code> feature to transform XML into a flatter version.</p>
</div>

<p>Let’s look at a few examples.</p>

<p>Read an XML string:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell146"><span></span><span class="gp">In [372]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">StringIO</span>

<span class="gp">In [373]: </span><span class="n">xml</span> <span class="o">=</span> <span class="s2">"""&lt;?xml version="1.0" encoding="UTF-8"?&gt;</span>
<span class="gp"></span><span class="s2">&lt;bookstore&gt;</span>
<span class="gp"></span><span class="s2">  &lt;book category="cooking"&gt;</span>
<span class="gp"></span><span class="s2">    &lt;title lang="en"&gt;Everyday Italian&lt;/title&gt;</span>
<span class="gp"></span><span class="s2">    &lt;author&gt;Giada De Laurentiis&lt;/author&gt;</span>
<span class="gp"></span><span class="s2">    &lt;year&gt;2005&lt;/year&gt;</span>
<span class="gp"></span><span class="s2">    &lt;price&gt;30.00&lt;/price&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/book&gt;</span>
<span class="gp"></span><span class="s2">  &lt;book category="children"&gt;</span>
<span class="gp"></span><span class="s2">    &lt;title lang="en"&gt;Harry Potter&lt;/title&gt;</span>
<span class="gp"></span><span class="s2">    &lt;author&gt;J K. Rowling&lt;/author&gt;</span>
<span class="gp"></span><span class="s2">    &lt;year&gt;2005&lt;/year&gt;</span>
<span class="gp"></span><span class="s2">    &lt;price&gt;29.99&lt;/price&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/book&gt;</span>
<span class="gp"></span><span class="s2">  &lt;book category="web"&gt;</span>
<span class="gp"></span><span class="s2">    &lt;title lang="en"&gt;Learning XML&lt;/title&gt;</span>
<span class="gp"></span><span class="s2">    &lt;author&gt;Erik T. Ray&lt;/author&gt;</span>
<span class="gp"></span><span class="s2">    &lt;year&gt;2003&lt;/year&gt;</span>
<span class="gp"></span><span class="s2">    &lt;price&gt;39.95&lt;/price&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/book&gt;</span>
<span class="gp"></span><span class="s2">&lt;/bookstore&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [374]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">xml</span><span class="p">))</span>

<span class="gp">In [375]: </span><span class="n">df</span>
<span class="gh">Out[375]: </span>
<span class="go">   category             title               author  year  price</span>
<span class="go">0   cooking  Everyday Italian  Giada De Laurentiis  2005  30.00</span>
<span class="go">1  children      Harry Potter         J K. Rowling  2005  29.99</span>
<span class="go">2       web      Learning XML          Erik T. Ray  2003  39.95</span>
</pre>
</div>
</div>

<p>Read a URL with no options:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell147"><span></span><span class="gp">In [376]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="s2">"https://www.w3schools.com/xml/books.xml"</span><span class="p">)</span>

<span class="gp">In [377]: </span><span class="n">df</span>
<span class="gh">Out[377]: </span>
<span class="go">   category              title                  author  year  price      cover</span>
<span class="go">0   cooking   Everyday Italian     Giada De Laurentiis  2005  30.00       None</span>
<span class="go">1  children       Harry Potter            J K. Rowling  2005  29.99       None</span>
<span class="go">2       web  XQuery Kick Start  Vaidyanathan Nagarajan  2003  49.99       None</span>
<span class="go">3       web       Learning XML             Erik T. Ray  2003  39.95  paperback</span>
</pre>
</div>
</div>

<p>Read in the content of the “books.xml” file and pass it to <code>read_xml</code> as a string:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell148"><span></span><span class="gp">In [378]: </span><span class="n">file_path</span> <span class="o">=</span> <span class="s2">"books.xml"</span>

<span class="gp">In [379]: </span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="n">file_path</span><span class="p">,</span> <span class="s2">"w"</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">f</span><span class="o">.</span><span class="n">write</span><span class="p">(</span><span class="n">xml</span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [380]: </span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="n">file_path</span><span class="p">,</span> <span class="s2">"r"</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">f</span><span class="o">.</span><span class="n">read</span><span class="p">()))</span>
<span class="gp"></span>

<span class="gp">In [381]: </span><span class="n">df</span>
<span class="gh">Out[381]: </span>
<span class="go">   category             title               author  year  price</span>
<span class="go">0   cooking  Everyday Italian  Giada De Laurentiis  2005  30.00</span>
<span class="go">1  children      Harry Potter         J K. Rowling  2005  29.99</span>
<span class="go">2       web      Learning XML          Erik T. Ray  2003  39.95</span>
</pre>
</div>
</div>

<p>Read in the content of the “books.xml” as instance of <code>StringIO</code> or <code>BytesIO</code> and pass it to <code>read_xml</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell149"><span></span><span class="gp">In [382]: </span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="n">file_path</span><span class="p">,</span> <span class="s2">"r"</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">sio</span> <span class="o">=</span> <span class="n">StringIO</span><span class="p">(</span><span class="n">f</span><span class="o">.</span><span class="n">read</span><span class="p">())</span>
<span class="gp"></span>

<span class="gp">In [383]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">sio</span><span class="p">)</span>

<span class="gp">In [384]: </span><span class="n">df</span>
<span class="gh">Out[384]: </span>
<span class="go">   category             title               author  year  price</span>
<span class="go">0   cooking  Everyday Italian  Giada De Laurentiis  2005  30.00</span>
<span class="go">1  children      Harry Potter         J K. Rowling  2005  29.99</span>
<span class="go">2       web      Learning XML          Erik T. Ray  2003  39.95</span>
</pre>
</div>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell150"><span></span><span class="gp">In [385]: </span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="n">file_path</span><span class="p">,</span> <span class="s2">"rb"</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">bio</span> <span class="o">=</span> <span class="n">BytesIO</span><span class="p">(</span><span class="n">f</span><span class="o">.</span><span class="n">read</span><span class="p">())</span>
<span class="gp"></span>

<span class="gp">In [386]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">bio</span><span class="p">)</span>

<span class="gp">In [387]: </span><span class="n">df</span>
<span class="gh">Out[387]: </span>
<span class="go">   category             title               author  year  price</span>
<span class="go">0   cooking  Everyday Italian  Giada De Laurentiis  2005  30.00</span>
<span class="go">1  children      Harry Potter         J K. Rowling  2005  29.99</span>
<span class="go">2       web      Learning XML          Erik T. Ray  2003  39.95</span>
</pre>
</div>
</div>

<p>Even read XML from AWS S3 buckets such as NIH NCBI PMC Article Datasets providing Biomedical and Life Science Jorurnals:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell151"><span></span><span class="gp">In [388]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span>
<span class="gp"></span>    <span class="s2">"s3://pmc-oa-opendata/oa_comm/xml/all/PMC1236943.xml"</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">xpath</span><span class="o">=</span><span class="s2">".//journal-meta"</span><span class="p">,</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [389]: </span><span class="n">df</span>
<span class="gh">Out[389]: </span>
<span class="go">              journal-id              journal-title       issn  publisher</span>
<span class="go">0  Cardiovasc Ultrasound  Cardiovascular Ultrasound  1476-7120        NaN</span>
</pre>
</div>
</div>

<p>With <a href="https://lxml.de">lxml</a> as default <code>parser</code>, you access the full-featured XML library that extends Python’s ElementTree API. One powerful tool is ability to query nodes selectively or conditionally with more expressive XPath:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell152"><span></span><span class="gp">In [390]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">file_path</span><span class="p">,</span> <span class="n">xpath</span><span class="o">=</span><span class="s2">"//book[year=2005]"</span><span class="p">)</span>

<span class="gp">In [391]: </span><span class="n">df</span>
<span class="gh">Out[391]: </span>
<span class="go">   category             title               author  year  price</span>
<span class="go">0   cooking  Everyday Italian  Giada De Laurentiis  2005  30.00</span>
<span class="go">1  children      Harry Potter         J K. Rowling  2005  29.99</span>
</pre>
</div>
</div>

<p>Specify only elements or only attributes to parse:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell153"><span></span><span class="gp">In [392]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">file_path</span><span class="p">,</span> <span class="n">elems_only</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="gp">In [393]: </span><span class="n">df</span>
<span class="gh">Out[393]: </span>
<span class="go">              title               author  year  price</span>
<span class="go">0  Everyday Italian  Giada De Laurentiis  2005  30.00</span>
<span class="go">1      Harry Potter         J K. Rowling  2005  29.99</span>
<span class="go">2      Learning XML          Erik T. Ray  2003  39.95</span>
</pre>
</div>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell154"><span></span><span class="gp">In [394]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">file_path</span><span class="p">,</span> <span class="n">attrs_only</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="gp">In [395]: </span><span class="n">df</span>
<span class="gh">Out[395]: </span>
<span class="go">   category</span>
<span class="go">0   cooking</span>
<span class="go">1  children</span>
<span class="go">2       web</span>
</pre>
</div>
</div>

<p>XML documents can have namespaces with prefixes and default namespaces without prefixes both of which are denoted with a special attribute <code>xmlns</code>. In order to parse by node under a namespace context, <code>xpath</code> must reference a prefix.</p>

<p>For example, below XML contains a namespace with prefix, <code>doc</code>, and URI at <code>https://example.com</code>.
In order to parse <code>doc:row</code> nodes, <code>namespaces</code> must be used.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell155"><span></span><span class="gp">In [396]: </span><span class="n">xml</span> <span class="o">=</span> <span class="s2">"""&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="gp"></span><span class="s2">&lt;doc:data xmlns:doc="https://example.com"&gt;</span>
<span class="gp"></span><span class="s2">  &lt;doc:row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:shape&gt;square&lt;/doc:shape&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:degrees&gt;360&lt;/doc:degrees&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:sides&gt;4.0&lt;/doc:sides&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/doc:row&gt;</span>
<span class="gp"></span><span class="s2">  &lt;doc:row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:shape&gt;circle&lt;/doc:shape&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:degrees&gt;360&lt;/doc:degrees&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:sides/&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/doc:row&gt;</span>
<span class="gp"></span><span class="s2">  &lt;doc:row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:shape&gt;triangle&lt;/doc:shape&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:degrees&gt;180&lt;/doc:degrees&gt;</span>
<span class="gp"></span><span class="s2">    &lt;doc:sides&gt;3.0&lt;/doc:sides&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/doc:row&gt;</span>
<span class="gp"></span><span class="s2">&lt;/doc:data&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [397]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">xml</span><span class="p">),</span>
<span class="gp"></span>                 <span class="n">xpath</span><span class="o">=</span><span class="s2">"//doc:row"</span><span class="p">,</span>
<span class="gp"></span>                 <span class="n">namespaces</span><span class="o">=</span><span class="p">{</span><span class="s2">"doc"</span><span class="p">:</span> <span class="s2">"https://example.com"</span><span class="p">})</span>
<span class="gp"></span>

<span class="gp">In [398]: </span><span class="n">df</span>
<span class="gh">Out[398]: </span>
<span class="go">      shape  degrees  sides</span>
<span class="go">0    square      360    4.0</span>
<span class="go">1    circle      360    NaN</span>
<span class="go">2  triangle      180    3.0</span>
</pre>
</div>
</div>

<p>Similarly, an XML document can have a default namespace without prefix. Failing to assign a temporary prefix will return no nodes and raise a <code>ValueError</code>. But assigning <em>any</em> temporary name to correct URI allows parsing by nodes.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell156"><span></span><span class="gp">In [399]: </span><span class="n">xml</span> <span class="o">=</span> <span class="s2">"""&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="gp"></span><span class="s2">&lt;data xmlns="https://example.com"&gt;</span>
<span class="gp"></span><span class="s2"> &lt;row&gt;</span>
<span class="gp"></span><span class="s2">   &lt;shape&gt;square&lt;/shape&gt;</span>
<span class="gp"></span><span class="s2">   &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="gp"></span><span class="s2">   &lt;sides&gt;4.0&lt;/sides&gt;</span>
<span class="gp"></span><span class="s2"> &lt;/row&gt;</span>
<span class="gp"></span><span class="s2"> &lt;row&gt;</span>
<span class="gp"></span><span class="s2">   &lt;shape&gt;circle&lt;/shape&gt;</span>
<span class="gp"></span><span class="s2">   &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="gp"></span><span class="s2">   &lt;sides/&gt;</span>
<span class="gp"></span><span class="s2"> &lt;/row&gt;</span>
<span class="gp"></span><span class="s2"> &lt;row&gt;</span>
<span class="gp"></span><span class="s2">   &lt;shape&gt;triangle&lt;/shape&gt;</span>
<span class="gp"></span><span class="s2">   &lt;degrees&gt;180&lt;/degrees&gt;</span>
<span class="gp"></span><span class="s2">   &lt;sides&gt;3.0&lt;/sides&gt;</span>
<span class="gp"></span><span class="s2"> &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">&lt;/data&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [400]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">xml</span><span class="p">),</span>
<span class="gp"></span>                 <span class="n">xpath</span><span class="o">=</span><span class="s2">"//pandas:row"</span><span class="p">,</span>
<span class="gp"></span>                 <span class="n">namespaces</span><span class="o">=</span><span class="p">{</span><span class="s2">"pandas"</span><span class="p">:</span> <span class="s2">"https://example.com"</span><span class="p">})</span>
<span class="gp"></span>

<span class="gp">In [401]: </span><span class="n">df</span>
<span class="gh">Out[401]: </span>
<span class="go">      shape  degrees  sides</span>
<span class="go">0    square      360    4.0</span>
<span class="go">1    circle      360    NaN</span>
<span class="go">2  triangle      180    3.0</span>
</pre>
</div>
</div>

<p>However, if XPath does not reference node names such as default, <code>/*</code>, then <code>namespaces</code> is not required.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Since <code>xpath</code> identifies the parent of content to be parsed, only immediate descendants which include child nodes or current attributes are parsed. Therefore, <code>read_xml</code> will not parse the text of grandchildren or other descendants and will not parse attributes of any descendant. To retrieve lower level content, adjust xpath to lower level. For example,</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell157"><span></span><span class="gp">In [402]: </span><span class="n">xml</span> <span class="o">=</span> <span class="s2">"""</span>
<span class="gp"></span><span class="s2">&lt;data&gt;</span>
<span class="gp"></span><span class="s2">  &lt;row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;shape sides="4"&gt;square&lt;/shape&gt;</span>
<span class="gp"></span><span class="s2">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">  &lt;row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;shape sides="0"&gt;circle&lt;/shape&gt;</span>
<span class="gp"></span><span class="s2">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">  &lt;row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;shape sides="3"&gt;triangle&lt;/shape&gt;</span>
<span class="gp"></span><span class="s2">    &lt;degrees&gt;180&lt;/degrees&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">&lt;/data&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [403]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">xml</span><span class="p">),</span> <span class="n">xpath</span><span class="o">=</span><span class="s2">"./row"</span><span class="p">)</span>

<span class="gp">In [404]: </span><span class="n">df</span>
<span class="gh">Out[404]: </span>
<span class="go">      shape  degrees</span>
<span class="go">0    square      360</span>
<span class="go">1    circle      360</span>
<span class="go">2  triangle      180</span>
</pre>
</div>
</div>

<p>shows the attribute <code>sides</code> on <code>shape</code> element was not parsed as expected since this attribute resides on the child of <code>row</code> element and not <code>row</code> element itself. In other words, <code>sides</code> attribute is a grandchild level descendant of <code>row</code> element. However, the <code>xpath</code> targets <code>row</code> element which covers only its children and attributes.</p>
</div>

<p>With <a href="https://lxml.de">lxml</a> as parser, you can flatten nested XML documents with an XSLT script which also can be string/file/URL types. As background, <a href="https://www.w3.org/TR/xslt/">XSLT</a> is a special-purpose language written in a special XML file that can transform original XML documents into other XML, HTML, even text (CSV, JSON, etc.) using an XSLT processor.</p>

<p>For example, consider this somewhat nested structure of Chicago “L” Rides where station and rides elements encapsulate data in their own sections. With below XSLT, <code>lxml</code> can transform original nested document into a flatter output (as shown below for demonstration) for easier parse into <code>DataFrame</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell158"><span></span><span class="gp">In [405]: </span><span class="n">xml</span> <span class="o">=</span> <span class="s2">"""&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="gp"></span><span class="s2"> &lt;response&gt;</span>
<span class="gp"></span><span class="s2">  &lt;row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;station id="40850" name="Library"/&gt;</span>
<span class="gp"></span><span class="s2">    &lt;month&gt;2020-09-01T00:00:00&lt;/month&gt;</span>
<span class="gp"></span><span class="s2">    &lt;rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_weekday_rides&gt;864.2&lt;/avg_weekday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_saturday_rides&gt;534&lt;/avg_saturday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_sunday_holiday_rides&gt;417.2&lt;/avg_sunday_holiday_rides&gt;</span>
<span class="gp"></span><span class="s2">    &lt;/rides&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">  &lt;row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;station id="41700" name="Washington/Wabash"/&gt;</span>
<span class="gp"></span><span class="s2">    &lt;month&gt;2020-09-01T00:00:00&lt;/month&gt;</span>
<span class="gp"></span><span class="s2">    &lt;rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_weekday_rides&gt;2707.4&lt;/avg_weekday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_saturday_rides&gt;1909.8&lt;/avg_saturday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_sunday_holiday_rides&gt;1438.6&lt;/avg_sunday_holiday_rides&gt;</span>
<span class="gp"></span><span class="s2">    &lt;/rides&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">  &lt;row&gt;</span>
<span class="gp"></span><span class="s2">    &lt;station id="40380" name="Clark/Lake"/&gt;</span>
<span class="gp"></span><span class="s2">    &lt;month&gt;2020-09-01T00:00:00&lt;/month&gt;</span>
<span class="gp"></span><span class="s2">    &lt;rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_weekday_rides&gt;2949.6&lt;/avg_weekday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_saturday_rides&gt;1657&lt;/avg_saturday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_sunday_holiday_rides&gt;1453.8&lt;/avg_sunday_holiday_rides&gt;</span>
<span class="gp"></span><span class="s2">    &lt;/rides&gt;</span>
<span class="gp"></span><span class="s2">  &lt;/row&gt;</span>
<span class="gp"></span><span class="s2"> &lt;/response&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [406]: </span><span class="n">xsl</span> <span class="o">=</span> <span class="s2">"""&lt;xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:output method="xml" omit-xml-declaration="no" indent="yes"/&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:strip-space elements="*"/&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:template match="/response"&gt;</span>
<span class="gp"></span><span class="s2">      &lt;xsl:copy&gt;</span>
<span class="gp"></span><span class="s2">        &lt;xsl:apply-templates select="row"/&gt;</span>
<span class="gp"></span><span class="s2">      &lt;/xsl:copy&gt;</span>
<span class="gp"></span><span class="s2">   &lt;/xsl:template&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:template match="row"&gt;</span>
<span class="gp"></span><span class="s2">      &lt;xsl:copy&gt;</span>
<span class="gp"></span><span class="s2">        &lt;station_id&gt;&lt;xsl:value-of select="station/@id"/&gt;&lt;/station_id&gt;</span>
<span class="gp"></span><span class="s2">        &lt;station_name&gt;&lt;xsl:value-of select="station/@name"/&gt;&lt;/station_name&gt;</span>
<span class="gp"></span><span class="s2">        &lt;xsl:copy-of select="month|rides/*"/&gt;</span>
<span class="gp"></span><span class="s2">      &lt;/xsl:copy&gt;</span>
<span class="gp"></span><span class="s2">   &lt;/xsl:template&gt;</span>
<span class="gp"></span><span class="s2"> &lt;/xsl:stylesheet&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [407]: </span><span class="n">output</span> <span class="o">=</span> <span class="s2">"""&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="gp"></span><span class="s2"> &lt;response&gt;</span>
<span class="gp"></span><span class="s2">   &lt;row&gt;</span>
<span class="gp"></span><span class="s2">      &lt;station_id&gt;40850&lt;/station_id&gt;</span>
<span class="gp"></span><span class="s2">      &lt;station_name&gt;Library&lt;/station_name&gt;</span>
<span class="gp"></span><span class="s2">      &lt;month&gt;2020-09-01T00:00:00&lt;/month&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_weekday_rides&gt;864.2&lt;/avg_weekday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_saturday_rides&gt;534&lt;/avg_saturday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_sunday_holiday_rides&gt;417.2&lt;/avg_sunday_holiday_rides&gt;</span>
<span class="gp"></span><span class="s2">   &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">   &lt;row&gt;</span>
<span class="gp"></span><span class="s2">      &lt;station_id&gt;41700&lt;/station_id&gt;</span>
<span class="gp"></span><span class="s2">      &lt;station_name&gt;Washington/Wabash&lt;/station_name&gt;</span>
<span class="gp"></span><span class="s2">      &lt;month&gt;2020-09-01T00:00:00&lt;/month&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_weekday_rides&gt;2707.4&lt;/avg_weekday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_saturday_rides&gt;1909.8&lt;/avg_saturday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_sunday_holiday_rides&gt;1438.6&lt;/avg_sunday_holiday_rides&gt;</span>
<span class="gp"></span><span class="s2">   &lt;/row&gt;</span>
<span class="gp"></span><span class="s2">   &lt;row&gt;</span>
<span class="gp"></span><span class="s2">      &lt;station_id&gt;40380&lt;/station_id&gt;</span>
<span class="gp"></span><span class="s2">      &lt;station_name&gt;Clark/Lake&lt;/station_name&gt;</span>
<span class="gp"></span><span class="s2">      &lt;month&gt;2020-09-01T00:00:00&lt;/month&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_weekday_rides&gt;2949.6&lt;/avg_weekday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_saturday_rides&gt;1657&lt;/avg_saturday_rides&gt;</span>
<span class="gp"></span><span class="s2">      &lt;avg_sunday_holiday_rides&gt;1453.8&lt;/avg_sunday_holiday_rides&gt;</span>
<span class="gp"></span><span class="s2">   &lt;/row&gt;</span>
<span class="gp"></span><span class="s2"> &lt;/response&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [408]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span><span class="n">StringIO</span><span class="p">(</span><span class="n">xml</span><span class="p">),</span> <span class="n">stylesheet</span><span class="o">=</span><span class="n">xsl</span><span class="p">)</span>

<span class="gp">In [409]: </span><span class="n">df</span>
<span class="gh">Out[409]: </span>
<span class="go">   station_id       station_name  ... avg_saturday_rides  avg_sunday_holiday_rides</span>
<span class="go">0       40850            Library  ...              534.0                     417.2</span>
<span class="go">1       41700  Washington/Wabash  ...             1909.8                    1438.6</span>
<span class="go">2       40380         Clark/Lake  ...             1657.0                    1453.8</span>

<span class="go">[3 rows x 6 columns]</span>
</pre>
</div>
</div>

<p>For very large XML files that can range in hundreds of megabytes to gigabytes,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html" title="pandas.read_xml"><code>pandas.read_xml()</code></a>
supports parsing such sizeable files using <a href="https://lxml.de/3.2/parsing.html#iterparse-and-iterwalk">lxml’s iterparse</a> and
<a href="https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.iterparse">etree’s iterparse</a> which are memory-efficient methods to iterate through an XML tree and extract specific elements and attributes. without holding entire tree in memory.</p>
    
<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.5.0.</span></p>
</div>

<p>To use this feature, you must pass a physical XML file path into <code>read_xml</code> and use the <code>iterparse</code> argument.
Files should not be compressed or point to online sources but stored on local disk. Also, <code>iterparse</code> should be a dictionary where the key is the repeating nodes in document (which become the rows) and the value is a list of any element or attribute that is a descendant (i.e., child, grandchild) of repeating node. Since XPath is not used in this method, descendants do not need to share same relationship with one another. Below shows example of reading in Wikipedia’s very large (12 GB+) latest article data dump.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell159"><span></span><span class="gp">In [1]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_xml</span><span class="p">(</span>
<span class="go">...         "/path/to/downloaded/enwikisource-latest-pages-articles.xml",</span>
<span class="go">...         iterparse = {"page": ["title", "ns", "id"]}</span>
<span class="go">...     )</span>
<span class="go">...     df</span>
<span class="gh">Out[2]:</span>
<span class="go">                                                     title   ns        id</span>
<span class="go">0                                       Gettysburg Address    0     21450</span>
<span class="go">1                                                Main Page    0     42950</span>
<span class="go">2                            Declaration by United Nations    0      8435</span>
<span class="go">3             Constitution of the United States of America    0      8435</span>
<span class="go">4                     Declaration of Independence (Israel)    0     17858</span>
<span class="go">...                                                    ...  ...       ...</span>
<span class="go">3578760               Page:Black cat 1897 07 v2 n10.pdf/17  104    219649</span>
<span class="go">3578761               Page:Black cat 1897 07 v2 n10.pdf/43  104    219649</span>
<span class="go">3578762               Page:Black cat 1897 07 v2 n10.pdf/44  104    219649</span>
<span class="go">3578763      The History of Tom Jones, a Foundling/Book IX    0  12084291</span>
<span class="go">3578764  Page:Shakespeare of Stratford (1926) Yale.djvu/91  104     21450</span>

<span class="go">[3578765 rows x 3 columns]</span>
</pre>
</div>
</div>

## <h3>Writing XML</h3>

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.3.0.</span></p>
</div>

<p><code>DataFrame</code> objects have an instance method <code>to_xml</code> which renders the contents of the <code>DataFrame</code> as an XML document.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>This method does not support special properties of XML including DTD, CData, XSD schemas, processing instructions, comments, and others.
Only namespaces at the root level is supported. However, <code>stylesheet</code> allows design changes after initial output.</p>
</div>

<p>Let’s look at a few examples.</p>

<p>Write an XML without options:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell160"><span></span><span class="gp">In [410]: </span><span class="n">geom_df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"shape"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"square"</span><span class="p">,</span> <span class="s2">"circle"</span><span class="p">,</span> <span class="s2">"triangle"</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"degrees"</span><span class="p">:</span> <span class="p">[</span><span class="mi">360</span><span class="p">,</span> <span class="mi">360</span><span class="p">,</span> <span class="mi">180</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"sides"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [411]: </span><span class="nb">print</span><span class="p">(</span><span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">())</span>
<span class="go">&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="go">&lt;data&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;index&gt;0&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;square&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;4.0&lt;/sides&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;index&gt;1&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;circle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides/&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;index&gt;2&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;triangle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;180&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;3.0&lt;/sides&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">&lt;/data&gt;</span>
</pre>
</div>
</div>

<p>Write an XML with new root and row name:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell161"><span></span><span class="gp">In [412]: </span><span class="nb">print</span><span class="p">(</span><span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">(</span><span class="n">root_name</span><span class="o">=</span><span class="s2">"geometry"</span><span class="p">,</span> <span class="n">row_name</span><span class="o">=</span><span class="s2">"objects"</span><span class="p">))</span>
<span class="go">&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="go">&lt;geometry&gt;</span>
<span class="go">  &lt;objects&gt;</span>
<span class="go">    &lt;index&gt;0&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;square&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;4.0&lt;/sides&gt;</span>
<span class="go">  &lt;/objects&gt;</span>
<span class="go">  &lt;objects&gt;</span>
<span class="go">    &lt;index&gt;1&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;circle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides/&gt;</span>
<span class="go">  &lt;/objects&gt;</span>
<span class="go">  &lt;objects&gt;</span>
<span class="go">    &lt;index&gt;2&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;triangle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;180&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;3.0&lt;/sides&gt;</span>
<span class="go">  &lt;/objects&gt;</span>
<span class="go">&lt;/geometry&gt;</span>
</pre>
</div>
</div>

<p>Write an attribute-centric XML:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell162"><span></span><span class="gp">In [413]: </span><span class="nb">print</span><span class="p">(</span><span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">(</span><span class="n">attr_cols</span><span class="o">=</span><span class="n">geom_df</span><span class="o">.</span><span class="n">columns</span><span class="o">.</span><span class="n">tolist</span><span class="p">()))</span>
<span class="go">&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="go">&lt;data&gt;</span>
<span class="go">  &lt;row index="0" shape="square" degrees="360" sides="4.0"/&gt;</span>
<span class="go">  &lt;row index="1" shape="circle" degrees="360"/&gt;</span>
<span class="go">  &lt;row index="2" shape="triangle" degrees="180" sides="3.0"/&gt;</span>
<span class="go">&lt;/data&gt;</span>
</pre>
</div>
</div>

<p>Write a mix of elements and attributes:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell163"><span></span><span class="gp">In [414]: </span><span class="nb">print</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">(</span>
<span class="gp"></span>        <span class="n">index</span><span class="o">=</span><span class="kc">False</span><span class="p">,</span>
<span class="gp"></span>        <span class="n">attr_cols</span><span class="o">=</span><span class="p">[</span><span class="s1">'shape'</span><span class="p">],</span>
<span class="gp"></span>        <span class="n">elem_cols</span><span class="o">=</span><span class="p">[</span><span class="s1">'degrees'</span><span class="p">,</span> <span class="s1">'sides'</span><span class="p">])</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>
<span class="go">&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="go">&lt;data&gt;</span>
<span class="go">  &lt;row shape="square"&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;4.0&lt;/sides&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row shape="circle"&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides/&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row shape="triangle"&gt;</span>
<span class="go">    &lt;degrees&gt;180&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;3.0&lt;/sides&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">&lt;/data&gt;</span>
</pre>
</div>
</div>

<p>Any <code>DataFrames</code> with hierarchical columns will be flattened for XML element names with levels delimited by underscores:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell164"><span></span><span class="gp">In [415]: </span><span class="n">ext_geom_df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"type"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"polygon"</span><span class="p">,</span> <span class="s2">"other"</span><span class="p">,</span> <span class="s2">"polygon"</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"shape"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"square"</span><span class="p">,</span> <span class="s2">"circle"</span><span class="p">,</span> <span class="s2">"triangle"</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"degrees"</span><span class="p">:</span> <span class="p">[</span><span class="mi">360</span><span class="p">,</span> <span class="mi">360</span><span class="p">,</span> <span class="mi">180</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"sides"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [416]: </span><span class="n">pvt_df</span> <span class="o">=</span> <span class="n">ext_geom_df</span><span class="o">.</span><span class="n">pivot_table</span><span class="p">(</span><span class="n">index</span><span class="o">=</span><span class="s1">'shape'</span><span class="p">,</span>
<span class="gp"></span>                                 <span class="n">columns</span><span class="o">=</span><span class="s1">'type'</span><span class="p">,</span>
<span class="gp"></span>                                 <span class="n">values</span><span class="o">=</span><span class="p">[</span><span class="s1">'degrees'</span><span class="p">,</span> <span class="s1">'sides'</span><span class="p">],</span>
<span class="gp"></span>                                 <span class="n">aggfunc</span><span class="o">=</span><span class="s1">'sum'</span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [417]: </span><span class="n">pvt_df</span>
<span class="gh">Out[417]: </span>
<span class="go">         degrees         sides        </span>
<span class="go">type       other polygon other polygon</span>
<span class="go">shape                                 </span>
<span class="go">circle     360.0     NaN   0.0     NaN</span>
<span class="go">square       NaN   360.0   NaN     4.0</span>
<span class="go">triangle     NaN   180.0   NaN     3.0</span>

<span class="gp">In [418]: </span><span class="nb">print</span><span class="p">(</span><span class="n">pvt_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">())</span>
<span class="go">&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="go">&lt;data&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;shape&gt;circle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees_other&gt;360.0&lt;/degrees_other&gt;</span>
<span class="go">    &lt;degrees_polygon/&gt;</span>
<span class="go">    &lt;sides_other&gt;0.0&lt;/sides_other&gt;</span>
<span class="go">    &lt;sides_polygon/&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;shape&gt;square&lt;/shape&gt;</span>
<span class="go">    &lt;degrees_other/&gt;</span>
<span class="go">    &lt;degrees_polygon&gt;360.0&lt;/degrees_polygon&gt;</span>
<span class="go">    &lt;sides_other/&gt;</span>
<span class="go">    &lt;sides_polygon&gt;4.0&lt;/sides_polygon&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;shape&gt;triangle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees_other/&gt;</span>
<span class="go">    &lt;degrees_polygon&gt;180.0&lt;/degrees_polygon&gt;</span>
<span class="go">    &lt;sides_other/&gt;</span>
<span class="go">    &lt;sides_polygon&gt;3.0&lt;/sides_polygon&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">&lt;/data&gt;</span>
</pre>
</div>
</div>

<p>Write an XML with default namespace:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell165"><span></span><span class="gp">In [419]: </span><span class="nb">print</span><span class="p">(</span><span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">(</span><span class="n">namespaces</span><span class="o">=</span><span class="p">{</span><span class="s2">""</span><span class="p">:</span> <span class="s2">"https://example.com"</span><span class="p">}))</span>
<span class="go">&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="go">&lt;data xmlns="https://example.com"&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;index&gt;0&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;square&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;4.0&lt;/sides&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;index&gt;1&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;circle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">    &lt;sides/&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">  &lt;row&gt;</span>
<span class="go">    &lt;index&gt;2&lt;/index&gt;</span>
<span class="go">    &lt;shape&gt;triangle&lt;/shape&gt;</span>
<span class="go">    &lt;degrees&gt;180&lt;/degrees&gt;</span>
<span class="go">    &lt;sides&gt;3.0&lt;/sides&gt;</span>
<span class="go">  &lt;/row&gt;</span>
<span class="go">&lt;/data&gt;</span>
</pre>
</div>
</div>

<p>Write an XML with namespace prefix:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell166"><span></span><span class="gp">In [420]: </span><span class="nb">print</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">(</span><span class="n">namespaces</span><span class="o">=</span><span class="p">{</span><span class="s2">"doc"</span><span class="p">:</span> <span class="s2">"https://example.com"</span><span class="p">},</span>
<span class="gp"></span>                   <span class="n">prefix</span><span class="o">=</span><span class="s2">"doc"</span><span class="p">)</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>
<span class="go">&lt;?xml version='1.0' encoding='utf-8'?&gt;</span>
<span class="go">&lt;doc:data xmlns:doc="https://example.com"&gt;</span>
<span class="go">  &lt;doc:row&gt;</span>
<span class="go">    &lt;doc:index&gt;0&lt;/doc:index&gt;</span>
<span class="go">    &lt;doc:shape&gt;square&lt;/doc:shape&gt;</span>
<span class="go">    &lt;doc:degrees&gt;360&lt;/doc:degrees&gt;</span>
<span class="go">    &lt;doc:sides&gt;4.0&lt;/doc:sides&gt;</span>
<span class="go">  &lt;/doc:row&gt;</span>
<span class="go">  &lt;doc:row&gt;</span>
<span class="go">    &lt;doc:index&gt;1&lt;/doc:index&gt;</span>
<span class="go">    &lt;doc:shape&gt;circle&lt;/doc:shape&gt;</span>
<span class="go">    &lt;doc:degrees&gt;360&lt;/doc:degrees&gt;</span>
<span class="go">    &lt;doc:sides/&gt;</span>
<span class="go">  &lt;/doc:row&gt;</span>
<span class="go">  &lt;doc:row&gt;</span>
<span class="go">    &lt;doc:index&gt;2&lt;/doc:index&gt;</span>
<span class="go">    &lt;doc:shape&gt;triangle&lt;/doc:shape&gt;</span>
<span class="go">    &lt;doc:degrees&gt;180&lt;/doc:degrees&gt;</span>
<span class="go">    &lt;doc:sides&gt;3.0&lt;/doc:sides&gt;</span>
<span class="go">  &lt;/doc:row&gt;</span>
<span class="go">&lt;/doc:data&gt;</span>
</pre>
</div>
</div>

<p>Write an XML without declaration or pretty print:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell167"><span></span><span class="gp">In [421]: </span><span class="nb">print</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">(</span><span class="n">xml_declaration</span><span class="o">=</span><span class="kc">False</span><span class="p">,</span>
<span class="gp"></span>                   <span class="n">pretty_print</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>
<span class="go">&lt;data&gt;&lt;row&gt;&lt;index&gt;0&lt;/index&gt;&lt;shape&gt;square&lt;/shape&gt;&lt;degrees&gt;360&lt;/degrees&gt;&lt;sides&gt;4.0&lt;/sides&gt;&lt;/row&gt;&lt;row&gt;&lt;index&gt;1&lt;/index&gt;&lt;shape&gt;circle&lt;/shape&gt;&lt;degrees&gt;360&lt;/degrees&gt;&lt;sides/&gt;&lt;/row&gt;&lt;row&gt;&lt;index&gt;2&lt;/index&gt;&lt;shape&gt;triangle&lt;/shape&gt;&lt;degrees&gt;180&lt;/degrees&gt;&lt;sides&gt;3.0&lt;/sides&gt;&lt;/row&gt;&lt;/data&gt;</span>
</pre>
</div>
</div>

<p>Write an XML and transform with stylesheet:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell168"><span></span><span class="gp">In [422]: </span><span class="n">xsl</span> <span class="o">=</span> <span class="s2">"""&lt;xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:output method="xml" omit-xml-declaration="no" indent="yes"/&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:strip-space elements="*"/&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:template match="/data"&gt;</span>
<span class="gp"></span><span class="s2">     &lt;geometry&gt;</span>
<span class="gp"></span><span class="s2">       &lt;xsl:apply-templates select="row"/&gt;</span>
<span class="gp"></span><span class="s2">     &lt;/geometry&gt;</span>
<span class="gp"></span><span class="s2">   &lt;/xsl:template&gt;</span>
<span class="gp"></span><span class="s2">   &lt;xsl:template match="row"&gt;</span>
<span class="gp"></span><span class="s2">     &lt;object index="</span><span class="si">{index}</span><span class="s2">"&gt;</span>
<span class="gp"></span><span class="s2">       &lt;xsl:if test="shape!='circle'"&gt;</span>
<span class="gp"></span><span class="s2">           &lt;xsl:attribute name="type"&gt;polygon&lt;/xsl:attribute&gt;</span>
<span class="gp"></span><span class="s2">       &lt;/xsl:if&gt;</span>
<span class="gp"></span><span class="s2">       &lt;xsl:copy-of select="shape"/&gt;</span>
<span class="gp"></span><span class="s2">       &lt;property&gt;</span>
<span class="gp"></span><span class="s2">           &lt;xsl:copy-of select="degrees|sides"/&gt;</span>
<span class="gp"></span><span class="s2">       &lt;/property&gt;</span>
<span class="gp"></span><span class="s2">     &lt;/object&gt;</span>
<span class="gp"></span><span class="s2">   &lt;/xsl:template&gt;</span>
<span class="gp"></span><span class="s2"> &lt;/xsl:stylesheet&gt;"""</span>
<span class="gp"></span>

<span class="gp">In [423]: </span><span class="nb">print</span><span class="p">(</span><span class="n">geom_df</span><span class="o">.</span><span class="n">to_xml</span><span class="p">(</span><span class="n">stylesheet</span><span class="o">=</span><span class="n">xsl</span><span class="p">))</span>
<span class="go">&lt;?xml version="1.0"?&gt;</span>
<span class="go">&lt;geometry&gt;</span>
<span class="go">  &lt;object index="0" type="polygon"&gt;</span>
<span class="go">    &lt;shape&gt;square&lt;/shape&gt;</span>
<span class="go">    &lt;property&gt;</span>
<span class="go">      &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">      &lt;sides&gt;4.0&lt;/sides&gt;</span>
<span class="go">    &lt;/property&gt;</span>
<span class="go">  &lt;/object&gt;</span>
<span class="go">  &lt;object index="1"&gt;</span>
<span class="go">    &lt;shape&gt;circle&lt;/shape&gt;</span>
<span class="go">    &lt;property&gt;</span>
<span class="go">      &lt;degrees&gt;360&lt;/degrees&gt;</span>
<span class="go">      &lt;sides/&gt;</span>
<span class="go">    &lt;/property&gt;</span>
<span class="go">  &lt;/object&gt;</span>
<span class="go">  &lt;object index="2" type="polygon"&gt;</span>
<span class="go">    &lt;shape&gt;triangle&lt;/shape&gt;</span>
<span class="go">    &lt;property&gt;</span>
<span class="go">      &lt;degrees&gt;180&lt;/degrees&gt;</span>
<span class="go">      &lt;sides&gt;3.0&lt;/sides&gt;</span>
<span class="go">    &lt;/property&gt;</span>
<span class="go">  &lt;/object&gt;</span>
<span class="go">&lt;/geometry&gt;</span>
</pre>
</div>
</div>

## <h3>XML Final Notes</h3>

<ul class="simple">
<li><p>All XML documents adhere to <a href="https://www.w3.org/TR/xml/">W3C specifications</a>. Both <code>etree</code> and <code>lxml</code> parsers will fail to parse any markup document that is not well-formed or follows XML syntax rules.
Do be aware HTML is not an XML document unless it follows XHTML specs. However, other popular markup types including KML, XAML, RSS, MusicML, MathML are compliant
<a href="https://en.wikipedia.org/wiki/List_of_types_of_XML_schemas">XML schemas</a>.</p></li>
<li><p>For above reason, if your application builds XML prior to pandas operations, use appropriate DOM libraries like <code>etree</code> and <code>lxml</code> to build the necessary document and not by string concatenation or regex adjustments. Always remember XML is a <em>special</em> text file with markup rules.</p></li>
<li><p>With very large XML files (several hundred MBs to GBs), XPath and XSLT can become memory-intensive operations.
Be sure to have enough available RAM for reading and writing to large XML files (roughly about 5 times the size of text).</p></li>
<li><p>Because XSLT is a programming language, use it with caution since such scripts can pose a security risk in your environment and can run large or infinite recursive operations. Always test scripts on small fragments before full run.</p></li>
<li><p>The <a href="https://docs.python.org/3/library/xml.etree.elementtree.html">etree</a> parser supports all functionality of both <code>read_xml</code> and <code>to_xml</code> except for complex XPath and any XSLT.
Though limited in features, <code>etree</code> is still a reliable and capable parser and tree builder. Its performance may trail <code>lxml</code> to a certain degree for larger files but relatively unnoticeable on small to medium size files.</p></li>
</ul>

# <h2>Excel files</h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html" title="pandas.read_excel"><code>read_excel()</code></a> method can read Excel 2007+ (<code>.xlsx</code>) files using the <code>openpyxl</code> Python module.
Excel 2003 (<code>.xls</code>) files can be read using <code>xlrd</code>. Binary Excel (<code>.xlsb</code>) files can be read using <code>pyxlsb</code>. All formats can be read using <a href="https://pandas.pydata.org/docs/user_guide/io.html#io-calamine">calamine</a> engine.

The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html" title="pandas.DataFrame.to_excel"><code>to_excel()</code></a> instance method is used for saving a <code>DataFrame</code> to Excel. Generally the semantics are similar to working with <a href="#io-read-csv-table">csv</a> data.
See the <a href="cookbook.html#cookbook-excel">cookbook</a> for some advanced strategies.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>When <code>engine=None</code>, the following logic will be used to determine the engine:</p>
<ul class="simple">
<li><p>If <code>path_or_buffer</code> is an OpenDocument format (.odf, .ods, .odt), then
<a href="https://pypi.org/project/odfpy/">odf</a> will be used.</p></li>
<li><p>Otherwise if <code>path_or_buffer</code> is an xls format, <code>xlrd</code> will be used.</p></li>
<li><p>Otherwise if <code>path_or_buffer</code> is in xlsb format, <code>pyxlsb</code> will be used.</p></li>
<li><p>Otherwise <code>openpyxl</code> will be used.</p></li>
</ul>
</div>

## <h3>Reading Excel files</h3>

<p>In the most basic use-case, <code>read_excel</code> takes a path to an Excel file, and the <code>sheet_name</code> indicating which sheet to parse.</p>

<p>When using the <code>engine_kwargs</code> parameter, pandas will pass these arguments to the engine. For this, it is important to know which function pandas is using internally.</p>

<ul class="simple">
<li><p>For the engine openpyxl, pandas is using <code>openpyxl.load_workbook()</code> to read in (<code>.xlsx</code>) and (<code>.xlsm</code>) files.</p></li>
<li><p>For the engine xlrd, pandas is using <code>xlrd.open_workbook()</code> to read in (<code>.xls</code>) files.</p></li>
<li><p>For the engine pyxlsb, pandas is using <code>pyxlsb.open_workbook()</code> to read in (<code>.xlsb</code>) files.</p></li>
<li><p>For the engine odf, pandas is using <code>odf.opendocument.load()</code> to read in (<code>.ods</code>) files.</p></li>
<li><p>For the engine calamine, pandas is using <code>python_calamine.load_workbook()</code>
to read in (<code>.xlsx</code>), (<code>.xlsm</code>), (<code>.xls</code>), (<code>.xlsb</code>), (<code>.ods</code>) files.</p></li>
</ul>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell169"><span></span><span class="c1"># Returns a DataFrame</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="s2">"Sheet1"</span><span class="p">)</span>
</pre>
</div>
</div>

### <h4><code>ExcelFile</code> class</h4>

<p>To facilitate working with multiple sheets from the same file, the <code>ExcelFile</code> class can be used to wrap the file and can be passed into <code>read_excel</code>
There will be a performance benefit for reading multiple sheets as the file is read into memory only once.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell170"><span></span><span class="n">xlsx</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelFile</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">)</span>
<span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xlsx</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>The <code>ExcelFile</span></code> class can also be used as a context manager.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell171"><span></span><span class="k">with</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelFile</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">)</span> <span class="k">as</span> <span class="n">xls</span><span class="p">:</span>
    <span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">)</span>
    <span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet2"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>The <code>sheet_names</code> property will generate a list of the sheet names in the file.</p>

<p>The primary use-case for an <code>ExcelFile</code> is parsing multiple sheets with different parameters:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell172"><span></span><span class="n">data</span> <span class="o">=</span> <span class="p">{}</span>
<span class="c1"># For when Sheet1's format differs from Sheet2</span>
<span class="k">with</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelFile</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">)</span> <span class="k">as</span> <span class="n">xls</span><span class="p">:</span>
    <span class="n">data</span><span class="p">[</span><span class="s2">"Sheet1"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">na_values</span><span class="o">=</span><span class="p">[</span><span class="s2">"NA"</span><span class="p">])</span>
    <span class="n">data</span><span class="p">[</span><span class="s2">"Sheet2"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet2"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Note that if the same parsing parameters are used for all sheets, a list of sheet names can simply be passed to <code>read_excel</code> with no loss in performance.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell173"><span></span><span class="c1"># using the ExcelFile class</span>
<span class="n">data</span> <span class="o">=</span> <span class="p">{}</span>
<span class="k">with</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelFile</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">)</span> <span class="k">as</span> <span class="n">xls</span><span class="p">:</span>
    <span class="n">data</span><span class="p">[</span><span class="s2">"Sheet1"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">na_values</span><span class="o">=</span><span class="p">[</span><span class="s2">"NA"</span><span class="p">])</span>
    <span class="n">data</span><span class="p">[</span><span class="s2">"Sheet2"</span><span class="p">]</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet2"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">na_values</span><span class="o">=</span><span class="p">[</span><span class="s2">"NA"</span><span class="p">])</span>

<span class="c1"># equivalent using the read_excel function</span>
<span class="n">data</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span>
    <span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="p">[</span><span class="s2">"Sheet1"</span><span class="p">,</span> <span class="s2">"Sheet2"</span><span class="p">],</span> <span class="n">index_col</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">na_values</span><span class="o">=</span><span class="p">[</span><span class="s2">"NA"</span><span class="p">]</span>
<span class="p">)</span>
</pre>
</div>
</div>

<p><code>ExcelFile</code> can also be called with a <code>xlrd.book.Book</code> object as a parameter.
This allows the user to control how the excel file is read. For example, sheets can be loaded on demand by calling <code>xlrd.open_workbook()</code> with <code>on_demand=True</code>.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell174"><span></span><span class="kn">import</span><span class="w"> </span><span class="nn">xlrd</span>

<span class="n">xlrd_book</span> <span class="o">=</span> <span class="n">xlrd</span><span class="o">.</span><span class="n">open_workbook</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="n">on_demand</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
<span class="k">with</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelFile</span><span class="p">(</span><span class="n">xlrd_book</span><span class="p">)</span> <span class="k">as</span> <span class="n">xls</span><span class="p">:</span>
    <span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">)</span>
    <span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="n">xls</span><span class="p">,</span> <span class="s2">"Sheet2"</span><span class="p">)</span>
</pre>
</div>
</div>

### <h4>Specifying sheets</h4>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The second argument is <code>sheet_name</code>, not to be confused with <code>ExcelFile.sheet_names</code>.</p>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>An ExcelFile’s attribute <code>sheet_names</code> provides access to a list of sheets.</p>
</div>

<ul class="simple">
<li><p>The arguments <code>sheet_name</code> allows specifying the sheet or sheets to read.</p></li>
<li><p>The default value for <code>sheet_name</code> is 0, indicating to read the first sheet</p></li>
<li><p>Pass a string to refer to the name of a particular sheet in the workbook.</p></li>
<li><p>Pass an integer to refer to the index of a sheet. Indices follow Python convention, beginning at 0.</p></li>
<li><p>Pass a list of either strings or integers, to return a dictionary of specified sheets.</p></li>
<li><p>Pass a <code>None</code> to return a dictionary of all available sheets.</p></li>
</ul>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell175"><span></span><span class="c1"># Returns a DataFrame</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">na_values</span><span class="o">=</span><span class="p">[</span><span class="s2">"NA"</span><span class="p">])</span>
</pre>
</div>
</div>

<p>Using the sheet index:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell176"><span></span><span class="c1"># Returns a DataFrame</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">na_values</span><span class="o">=</span><span class="p">[</span><span class="s2">"NA"</span><span class="p">])</span>
</pre>
</div>
</div>

<p>Using all default values:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell177"><span></span><span class="c1"># Returns a DataFrame</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Using None to get all sheets:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell178"><span></span><span class="c1"># Returns a dictionary of DataFrames</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="kc">None</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Using a list to get multiple sheets:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell179"><span></span><span class="c1"># Returns the 1st and 4th sheet, as a dictionary of DataFrames.</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="p">[</span><span class="s2">"Sheet1"</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>
</pre>
</div>
</div>

<p><code>read_excel</code> can read more than one sheet, by setting <code>sheet_name</code> to either a list of sheet names, a list of sheet positions, or <code>None</code> to read all sheets.
Sheets can be specified by sheet index or sheet name, using an integer or string, respectively.</p>

### <h4>Reading a <code>MultiIndex</code></h4>

<p><code>read_excel</code> can read a <code>MultiIndex</code> index, by passing a list of columns to <code>index_col</code> and a <code>MultiIndex</code> column by passing a list of rows to <code>header</code>.  If either the <code>index</code> or <code>columns</code> have serialized level names those will be read in as well by specifying the rows/columns that make up the levels.</p>

<p>For example, to read in a <code>MultiIndex</code> index without names:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell180"><span></span><span class="gp">In [424]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">]},</span>
<span class="gp"></span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_product</span><span class="p">([[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span> <span class="p">[</span><span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]]),</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [425]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">)</span>

<span class="gp">In [426]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">])</span>

<span class="gp">In [427]: </span><span class="n">df</span>
<span class="gh">Out[427]: </span>
<span class="go">     a  b</span>
<span class="go">a c  1  5</span>
<span class="go">  d  2  6</span>
<span class="go">b c  3  7</span>
<span class="go">  d  4  8</span>
</pre>
</div>
</div>

<p>If the index has level names, they will parsed as well, using the same parameters.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell181"><span></span><span class="gp">In [428]: </span><span class="n">df</span><span class="o">.</span><span class="n">index</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">set_names</span><span class="p">([</span><span class="s2">"lvl1"</span><span class="p">,</span> <span class="s2">"lvl2"</span><span class="p">])</span>

<span class="gp">In [429]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">)</span>

<span class="gp">In [430]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">])</span>

<span class="gp">In [431]: </span><span class="n">df</span>
<span class="gh">Out[431]: </span>
<span class="go">           a  b</span>
<span class="go">lvl1 lvl2      </span>
<span class="go">a    c     1  5</span>
<span class="go">     d     2  6</span>
<span class="go">b    c     3  7</span>
<span class="go">     d     4  8</span>
</pre>
</div>
</div>

<p>If the source file has both <code>MultiIndex</code> index and columns, lists specifying each should be passed to <code>index_col</code> and <code>header</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell182"><span></span><span class="gp">In [432]: </span><span class="n">df</span><span class="o">.</span><span class="n">columns</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_product</span><span class="p">([[</span><span class="s2">"a"</span><span class="p">],</span> <span class="p">[</span><span class="s2">"b"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]],</span> <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"c1"</span><span class="p">,</span> <span class="s2">"c2"</span><span class="p">])</span>

<span class="gp">In [433]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">)</span>

<span class="gp">In [434]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">],</span> <span class="n">header</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">])</span>

<span class="gp">In [435]: </span><span class="n">df</span>
<span class="gh">Out[435]: </span>
<span class="go">c1         a   </span>
<span class="go">c2         b  d</span>
<span class="go">lvl1 lvl2      </span>
<span class="go">a    c     1  5</span>
<span class="go">     d     2  6</span>
<span class="go">b    c     3  7</span>
<span class="go">     d     4  8</span>
</pre>
</div>
</div>

<p>Missing values in columns specified in <code>index_col</code> will be forward filled to allow roundtripping with <code>to_excel</code> for <code>merged_cells=True</code>.
To avoid forward filling the missing values use <code>set_index</code> after reading the data instead of <code>index_col</code>.</p>

### <h4>Parsing specific columns</h4>

<p>It is often the case that users will insert columns to do temporary computations in Excel and you may not want to read in those columns. <code>read_excel</code> takes a <code>usecols</code> keyword to allow you to specify a subset of columns to parse.</p>

<p>You can specify a comma-delimited set of Excel columns and ranges as a string:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell183"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">usecols</span><span class="o">=</span><span class="s2">"A,C:E"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>If <code>usecols</code> is a list of integers, then it is assumed to be the file column indices to be parsed.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell184"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">usecols</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>
</pre>
</div>
</div>

<p>Element order is ignored, so <code>usecols=[0, 1]</code> is the same as <code>[1, 0]</code>.</p>

<p>If <code>usecols</code> is a list of strings, it is assumed that each string corresponds to a column name provided either by the user in <code>names</code> or inferred from the document header row(s). Those strings define which columns will be parsed:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell185"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">usecols</span><span class="o">=</span><span class="p">[</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">])</span>
</pre>
</div>
</div>

<p>Element order is ignored, so <code>usecols=['baz', 'joe']</code> is the same as <code>['joe', 'baz']</code>.</p>

<p>If <code>usecols</code> is callable, the callable function will be evaluated against the column names, returning names where the callable function evaluates to <code>True</code>.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell186"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">usecols</span><span class="o">=</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="o">.</span><span class="n">isalpha</span><span class="p">())</span>
</pre>
</div>
</div>

### <h4>Parsing dates</h4>

<p>Datetime-like values are normally automatically converted to the appropriate dtype when reading the excel file.
But if you have a column of strings that <em>look</em> like dates (but are not actually formatted as dates in excel), you can use the <code>parse_dates</code> keyword to parse those strings to datetimes:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell187"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">parse_dates</span><span class="o">=</span><span class="p">[</span><span class="s2">"date_strings"</span><span class="p">])</span>
</pre>
</div>
</div>

### <h4>Cell converters</h4>

<p>It is possible to transform the contents of Excel cells via the <code>converters</code> option.
For instance, to convert a column to boolean:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell188"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">converters</span><span class="o">=</span><span class="p">{</span><span class="s2">"MyBools"</span><span class="p">:</span> <span class="nb">bool</span><span class="p">})</span>
</pre>
</div>
</div>

<p>This options handles missing values and treats exceptions in the converters as missing data. Transformations are applied cell by cell rather than to the column as a whole, so the array dtype is not guaranteed. For instance, a column of integers with missing values cannot be transformed to an array with integer dtype, because NaN is strictly a float. You can manually mask missing data to recover integer dtype:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell189"><span></span><span class="k">def</span><span class="w"> </span><span class="nf">cfun</span><span class="p">(</span><span class="n">x</span><span class="p">):</span>
    <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">x</span><span class="p">)</span> <span class="k">if</span> <span class="n">x</span> <span class="k">else</span> <span class="o">-</span><span class="mi">1</span>


<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">converters</span><span class="o">=</span><span class="p">{</span><span class="s2">"MyInts"</span><span class="p">:</span> <span class="n">cfun</span><span class="p">})</span>
</pre>
</div>
</div>

### <h4>Dtype specifications</h4>

<p>As an alternative to converters, the type for an entire column can be specified using the <code>dtype</code> keyword, which takes a dictionary mapping column names to types. To interpret data with no type inference, use the type <code>str</code> or <code>object</code>.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell190"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xls"</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="p">{</span><span class="s2">"MyInts"</span><span class="p">:</span> <span class="s2">"int64"</span><span class="p">,</span> <span class="s2">"MyText"</span><span class="p">:</span> <span class="nb">str</span><span class="p">})</span>
</pre>
</div>
</div>

## <h3>Writing Excel files</h3>

### <h4>Writing Excel files to disk</h4>

<p>To write a <code>DataFrame</code> object to a sheet of an Excel file, you can use the <code>to_excel</code> instance method. The arguments are largely the same as <code>to_csv</code> described above, the first argument being the name of the excel file, and the optional second argument the name of the sheet to which the <code>DataFrame</code> should be written.
For example:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell191"><span></span><span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="s2">"Sheet1"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Files with a <code>.xlsx</code> extension will be written using <code>xlsxwriter</code> (if available) or
<code>openpyxl</code>.</p>

<p>The <code>DataFrame</code> will be written in a way that tries to mimic the REPL output. The <code>index_label</code> will be placed in the second row instead of the first. You can place it in the first row by setting the <code>merge_cells</code> option in <code>to_excel()</code> to <code>False</code>:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell192"><span></span><span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">index_label</span><span class="o">=</span><span class="s2">"label"</span><span class="p">,</span> <span class="n">merge_cells</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
</pre>
</div>
</div>

<p>In order to write separate <code>DataFrames</code> to separate sheets in a single Excel file, one can pass an <code>ExcelWriter</code>.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell193"><span></span><span class="k">with</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelWriter</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">)</span> <span class="k">as</span> <span class="n">writer</span><span class="p">:</span>
    <span class="n">df1</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="n">writer</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="s2">"Sheet1"</span><span class="p">)</span>
    <span class="n">df2</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="n">writer</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="s2">"Sheet2"</span><span class="p">)</span>
</pre>
</div>
</div>

<p id="io-excel-writing-buffer">When using the <code>engine_kwargs</code> parameter, pandas will pass these arguments to the engine. For this, it is important to know which function pandas is using internally.</p>

<ul class="simple">
<li><p>For the engine openpyxl, pandas is using <code>openpyxl.Workbook()</code> to create a new sheet and <code>openpyxl.load_workbook()</code> to append data to an existing sheet. The openpyxl engine writes to (<code>.xlsx</code>) and (<code>.xlsm</code>) files.</p></li>
<li><p>For the engine xlsxwriter, pandas is using <code>xlsxwriter.Workbook()</code> to write to (<code>.xlsx</code>) files.</p></li>
<li><p>For the engine odf, pandas is using <code>odf.opendocument.OpenDocumentSpreadsheet()</code> to write to (<code>.ods</code>) files.</p></li>
</ul>

### <h4>Writing Excel files to memory</h4>

<p>pandas supports writing Excel files to buffer-like objects such as <code>StringIO</code> or <code>BytesIO</code> using <code>ExcelWriter</code>.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell194"><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">BytesIO</span>

<span class="n">bio</span> <span class="o">=</span> <span class="n">BytesIO</span><span class="p">()</span>

<span class="c1"># By setting the 'engine' in the ExcelWriter constructor.</span>
<span class="n">writer</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelWriter</span><span class="p">(</span><span class="n">bio</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"xlsxwriter"</span><span class="p">)</span>
<span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="n">writer</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="s2">"Sheet1"</span><span class="p">)</span>

<span class="c1"># Save the workbook</span>
<span class="n">writer</span><span class="o">.</span><span class="n">save</span><span class="p">()</span>

<span class="c1"># Seek to the beginning and read to copy the workbook to a variable in memory</span>
<span class="n">bio</span><span class="o">.</span><span class="n">seek</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
<span class="n">workbook</span> <span class="o">=</span> <span class="n">bio</span><span class="o">.</span><span class="n">read</span><span class="p">()</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>engine</code> is optional but recommended. Setting the engine determines the version of workbook produced.
Setting <code>engine='xlrd'</code> will produce an Excel 2003-format workbook (xls). Using either <code>'openpyxl'</code> or <code>'xlsxwriter'</code> will produce an Excel 2007-format workbook (xlsx). If omitted, an Excel 2007-formatted workbook is produced.</p>
</div>

## <h3>Excel writer engines</h3>

<p>pandas chooses an Excel writer via two methods:</p>

<ol class="arabic simple">
<li><p>the <code>engine</code> keyword argument</p></li>
<li><p>the filename extension (via the default specified in config options)</p></li>
</ol>

<p>By default, pandas uses the <a href="https://xlsxwriter.readthedocs.io">XlsxWriter</a>  for <code>.xlsx</code>,
<a href="https://openpyxl.readthedocs.io/">openpyxl</a> for <code>.xlsm</code>.
If you have multiple engines installed, you can set the default engine through <a href="options.html#options">setting the config options</a> <code>io.excel.xlsx.writer</code> and <code>io.excel.xls.writer</code>.
pandas will fall back on <a href="https://openpyxl.readthedocs.io/">openpyxl</a> for <code>.xlsx</code> files if
<a href="https://xlsxwriter.readthedocs.io">Xlsxwriter</a> is not available.</p>

<p>To specify which writer you want to use, you can pass an engine keyword argument to <code>to_excel</code> and to <code>ExcelWriter</code>. The built-in engines are:</p>

<ul class="simple">
<li><p><code>openpyxl</code>: version 2.4 or higher is required</p></li>
<li><p><code>xlsxwriter</code></p></li>
</ul>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell195"><span></span><span class="c1"># By setting the 'engine' in the DataFrame 'to_excel()' methods.</span>
<span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="s2">"Sheet1"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"xlsxwriter"</span><span class="p">)</span>

<span class="c1"># By setting the 'engine' in the ExcelWriter constructor.</span>
<span class="n">writer</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">ExcelWriter</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"xlsxwriter"</span><span class="p">)</span>

<span class="c1"># Or via pandas configuration.</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">pandas</span><span class="w"> </span><span class="kn">import</span> <span class="n">options</span>  <span class="c1"># noqa: E402</span>

<span class="n">options</span><span class="o">.</span><span class="n">io</span><span class="o">.</span><span class="n">excel</span><span class="o">.</span><span class="n">xlsx</span><span class="o">.</span><span class="n">writer</span> <span class="o">=</span> <span class="s2">"xlsxwriter"</span>

<span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsx"</span><span class="p">,</span> <span class="n">sheet_name</span><span class="o">=</span><span class="s2">"Sheet1"</span><span class="p">)</span>
</pre>
</div>
</div>

## <h3>Style and formatting</h3>

<p>The look and feel of Excel worksheets created from pandas can be modified using the following parameters on the <code>DataFrame</code>’s <code>to_excel</code> method.</p>

<ul class="simple">
<li><p><code>float_format</code> : Format string for floating point numbers (default <code>None</code>).</p></li>
<li><p><code>freeze_panes</code> : A tuple of two integers representing the bottommost row and rightmost column to freeze. Each of these parameters is one-based, so (1, 1) will freeze the first row and first column (default <code>None</code>).</p></li>
</ul>

<p>Using the <a href="https://xlsxwriter.readthedocs.io">Xlsxwriter</a> engine provides many options for controlling the
format of an Excel worksheet created with the <code>to_excel</code> method.  Excellent examples can be found in the
<a href="https://xlsxwriter.readthedocs.io">Xlsxwriter</a> documentation here: <a href="https://xlsxwriter.readthedocs.io/working_with_pandas.html">https://xlsxwriter.readthedocs.io/working_with_pandas.html</a></p>

# <h2>OpenDocument Spreadsheets</h2>

<p>The io methods for <a href="#excel-files">Excel files</a> also support reading and writing OpenDocument spreadsheets
using the <a href="https://pypi.org/project/odfpy/">odfpy</a> module. The semantics and features for reading and writing
OpenDocument spreadsheets match what can be done for <a href="#excel-files">Excel files</a> using
<code>engine='odf'</code>. The optional dependency ‘odfpy’ needs to be installed.</p>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html" title="pandas.read_excel"><code>read_excel()</code></a> method can read OpenDocument spreadsheets</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell196"><span></span><span class="c1"># Returns a DataFrame</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.ods"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"odf"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Similarly, the <code>to_excel()</span></code> method can write OpenDocument spreadsheets</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell197"><span></span><span class="c1"># Writes DataFrame to a .ods file</span>
<span class="n">df</span><span class="o">.</span><span class="n">to_excel</span><span class="p">(</span><span class="s2">"path_to_file.ods"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"odf"</span><span class="p">)</span>
</pre>
</div>
</div>

# <h2>Binary Excel (.xlsb) files</h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html" title="pandas.read_excel"><code>read_excel()</code></a> method can also read binary Excel files using the <code>pyxlsb</code> module.
The semantics and features for reading binary Excel files mostly match what can be done for
<a href="https://pandas.pydata.org/docs/user_guide/io.html#excel-files">Excel files</a> using <code>engine='pyxlsb'</code>. <code>pyxlsb</code> does not recognize datetime types in files and will return floats instead (you can use
<a href="https://pandas.pydata.org/docs/user_guide/io.html#io-calamine">calamine</a> if you need recognize datetime types).</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell198"><span></span><span class="c1"># Returns a DataFrame</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsb"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyxlsb"</span><span class="p">)</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Currently pandas only supports <em>reading</em> binary Excel files. Writing is not implemented.</p>
</div>

# <h2>Calamine (Excel and ODS files)</h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html" title="pandas.read_excel"><code>read_excel()</code></a> method can read Excel file (<code>.xlsx</code>, <code>.xlsm</code>, <code>.xls</code>, <code>.xlsb</code>) and OpenDocument spreadsheets (<code>.ods</code>) using the <code>python-calamine</code> module.
This module is a binding for Rust library <a href="https://crates.io/crates/calamine">calamine</a>
and is faster than other engines in most cases. The optional dependency ‘python-calamine’ needs to be installed.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell199"><span></span><span class="c1"># Returns a DataFrame</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_excel</span><span class="p">(</span><span class="s2">"path_to_file.xlsb"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"calamine"</span><span class="p">)</span>
</pre>
</div>
</div>

# <h2>Clipboard</h2>

<p>A handy way to grab data is to use the <code>read_clipboard()</code> method, which takes the contents of the clipboard buffer and passes them to the <code>read_csv</code> method. For instance, you can copy the following text to the
clipboard (CTRL-C on many operating systems):</p>

<div class="highlight-console notranslate"><div class="highlight"><pre id="codecell200"><span></span><span class="go">  A B C</span>
<span class="go">x 1 4 p</span>
<span class="go">y 2 5 q</span>
<span class="go">z 3 6 r</span>
</pre>
</div>
</div>

<p>And then import the data directly to a <code>DataFrame</code> by calling:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell201"><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">clipdf</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_clipboard</span><span class="p">()</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">clipdf</span>
<span class="go">  A B C</span>
<span class="go">x 1 4 p</span>
<span class="go">y 2 5 q</span>
<span class="go">z 3 6 r</span>
</pre>
</div>
</div>

<p>The <code>to_clipboard</code> method can be used to write the contents of a <code>DataFrame</code> to the clipboard. Following which you can paste the clipboard contents into other applications (CTRL-V on many operating systems).
Here we illustrate writing a <code>DataFrame</code> into clipboard and reading it back.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell202"><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">... </span>    <span class="p">{</span><span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">],</span> <span class="s2">"C"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"p"</span><span class="p">,</span> <span class="s2">"q"</span><span class="p">,</span> <span class="s2">"r"</span><span class="p">]},</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"x"</span><span class="p">,</span> <span class="s2">"y"</span><span class="p">,</span> <span class="s2">"z"</span><span class="p">]</span>
<span class="gp">... </span><span class="p">)</span>

<span class="gp">&gt;&gt;&gt; </span><span class="n">df</span>
<span class="go">  A B C</span>
<span class="go">x 1 4 p</span>
<span class="go">y 2 5 q</span>
<span class="go">z 3 6 r</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">df</span><span class="o">.</span><span class="n">to_clipboard</span><span class="p">()</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">pd</span><span class="o">.</span><span class="n">read_clipboard</span><span class="p">()</span>
<span class="go">  A B C</span>
<span class="go">x 1 4 p</span>
<span class="go">y 2 5 q</span>
<span class="go">z 3 6 r</span>
</pre>
</div>
</div>

<p>We can see that we got the same content back, which we had earlier written to the clipboard.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>You may need to install xclip or xsel (with PyQt5, PyQt4 or qtpy) on Linux to use these methods.</p>
</div>

# <h2>Pickling</h2>

<p>All pandas objects are equipped with <code>to_pickle</code> methods which use Python’s <code>cPickle</code> module to save data structures to disk using the pickle format.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell203"><span></span><span class="gp">In [436]: </span><span class="n">df</span>
<span class="gh">Out[436]: </span>
<span class="go">c1         a   </span>
<span class="go">c2         b  d</span>
<span class="go">lvl1 lvl2      </span>
<span class="go">a    c     1  5</span>
<span class="go">     d     2  6</span>
<span class="go">b    c     3  7</span>
<span class="go">     d     4  8</span>

<span class="gp">In [437]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"foo.pkl"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>The <code>read_pickle</code> function in the <code>pandas</code> namespace can be used to load any pickled pandas object (or any other pickled object) from file:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell204"><span></span><span class="gp">In [438]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_pickle</span><span class="p">(</span><span class="s2">"foo.pkl"</span><span class="p">)</span>
<span class="gh">Out[438]: </span>
<span class="go">c1         a   </span>
<span class="go">c2         b  d</span>
<span class="go">lvl1 lvl2      </span>
<span class="go">a    c     1  5</span>
<span class="go">     d     2  6</span>
<span class="go">b    c     3  7</span>
<span class="go">     d     4  8</span>
</pre>
</div>
</div>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Loading pickled data received from untrusted sources can be unsafe.</p>
<p>See: <a href="https://docs.python.org/3/library/pickle.html">https://docs.python.org/3/library/pickle.html</a></p>
</div>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_pickle.html" title="pandas.read_pickle"><code>read_pickle()</code></a> is only guaranteed backwards compatible back to a few minor release.</p>
</div>

## <h3>Compressed pickle files</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_pickle.html" title="pandas.read_pickle"><code>read_pickle()</code></a>,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_pickle.html" title="pandas.DataFrame.to_pickle"><code>DataFrame.to_pickle()</code></a> and
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.to_pickle.html" title="pandas.Series.to_pickle"><code>Series.to_pickle()</code></a> can read and write compressed pickle files. The compression types of <code>gzip</code>, <code>bz2</code>, <code>xz</code>, <code>zstd</code> are supported for reading and writing.
The <code>zip</code> file format only supports reading and must contain only one data file to be read.</p>

<p>The compression type can be an explicit parameter or be inferred from the file extension.
If ‘infer’, then use <code>gzip</code>, <code>bz2</code>, <code>zip</code>, <code>xz</code>, <code>zstd</code> if filename ends in <code>'.gz'</code>, <code>'.bz2'</code>, <code>'.zip'</code>, <code>'.xz'</code>, or <code>'.zst'</code>, respectively.</p>

<p>The compression parameter can also be a <code>dict</code> in order to pass options to the
compression protocol. It must have a <code>'method'</code> key set to the name of the compression protocol, which must be one of {<code>'zip'</code>, <code>'gzip'</code>, <code>'bz2'</code>, <code>'xz'</code>, <code>'zstd'</code>}. All other key-value pairs are passed to
the underlying compression library.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell205"><span></span><span class="gp">In [439]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">1000</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"B"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"C"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">1000</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"s"</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [440]: </span><span class="n">df</span>
<span class="gh">Out[440]: </span>
<span class="go">            A    B                   C</span>
<span class="go">0   -0.317441  foo 2013-01-01 00:00:00</span>
<span class="go">1   -1.236269  foo 2013-01-01 00:00:01</span>
<span class="go">2    0.896171  foo 2013-01-01 00:00:02</span>
<span class="go">3   -0.487602  foo 2013-01-01 00:00:03</span>
<span class="go">4   -0.082240  foo 2013-01-01 00:00:04</span>
<span class="go">..        ...  ...                 ...</span>
<span class="go">995 -0.171092  foo 2013-01-01 00:16:35</span>
<span class="go">996  1.786173  foo 2013-01-01 00:16:36</span>
<span class="go">997 -0.575189  foo 2013-01-01 00:16:37</span>
<span class="go">998  0.820750  foo 2013-01-01 00:16:38</span>
<span class="go">999 -1.256530  foo 2013-01-01 00:16:39</span>

<span class="go">[1000 rows x 3 columns]</span>
</pre>
</div>
</div>

<p>Using an explicit compression type:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell206"><span></span><span class="gp">In [441]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"data.pkl.compress"</span><span class="p">,</span> <span class="n">compression</span><span class="o">=</span><span class="s2">"gzip"</span><span class="p">)</span>

<span class="gp">In [442]: </span><span class="n">rt</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_pickle</span><span class="p">(</span><span class="s2">"data.pkl.compress"</span><span class="p">,</span> <span class="n">compression</span><span class="o">=</span><span class="s2">"gzip"</span><span class="p">)</span>

<span class="gp">In [443]: </span><span class="n">rt</span>
<span class="gh">Out[443]: </span>
<span class="go">            A    B                   C</span>
<span class="go">0   -0.317441  foo 2013-01-01 00:00:00</span>
<span class="go">1   -1.236269  foo 2013-01-01 00:00:01</span>
<span class="go">2    0.896171  foo 2013-01-01 00:00:02</span>
<span class="go">3   -0.487602  foo 2013-01-01 00:00:03</span>
<span class="go">4   -0.082240  foo 2013-01-01 00:00:04</span>
<span class="go">..        ...  ...                 ...</span>
<span class="go">995 -0.171092  foo 2013-01-01 00:16:35</span>
<span class="go">996  1.786173  foo 2013-01-01 00:16:36</span>
<span class="go">997 -0.575189  foo 2013-01-01 00:16:37</span>
<span class="go">998  0.820750  foo 2013-01-01 00:16:38</span>
<span class="go">999 -1.256530  foo 2013-01-01 00:16:39</span>

<span class="go">[1000 rows x 3 columns]</span>
</pre>
</div>
</div>

<p>Inferring compression type from the extension:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell207"><span></span><span class="gp">In [444]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"data.pkl.xz"</span><span class="p">,</span> <span class="n">compression</span><span class="o">=</span><span class="s2">"infer"</span><span class="p">)</span>

<span class="gp">In [445]: </span><span class="n">rt</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_pickle</span><span class="p">(</span><span class="s2">"data.pkl.xz"</span><span class="p">,</span> <span class="n">compression</span><span class="o">=</span><span class="s2">"infer"</span><span class="p">)</span>

<span class="gp">In [446]: </span><span class="n">rt</span>
<span class="gh">Out[446]: </span>
<span class="go">            A    B                   C</span>
<span class="go">0   -0.317441  foo 2013-01-01 00:00:00</span>
<span class="go">1   -1.236269  foo 2013-01-01 00:00:01</span>
<span class="go">2    0.896171  foo 2013-01-01 00:00:02</span>
<span class="go">3   -0.487602  foo 2013-01-01 00:00:03</span>
<span class="go">4   -0.082240  foo 2013-01-01 00:00:04</span>
<span class="go">..        ...  ...                 ...</span>
<span class="go">995 -0.171092  foo 2013-01-01 00:16:35</span>
<span class="go">996  1.786173  foo 2013-01-01 00:16:36</span>
<span class="go">997 -0.575189  foo 2013-01-01 00:16:37</span>
<span class="go">998  0.820750  foo 2013-01-01 00:16:38</span>
<span class="go">999 -1.256530  foo 2013-01-01 00:16:39</span>

<span class="go">[1000 rows x 3 columns]</span>
</pre>
</div>
</div>

<p>The default is to ‘infer’:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell208"><span></span><span class="gp">In [447]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"data.pkl.gz"</span><span class="p">)</span>

<span class="gp">In [448]: </span><span class="n">rt</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_pickle</span><span class="p">(</span><span class="s2">"data.pkl.gz"</span><span class="p">)</span>

<span class="gp">In [449]: </span><span class="n">rt</span>
<span class="gh">Out[449]: </span>
<span class="go">            A    B                   C</span>
<span class="go">0   -0.317441  foo 2013-01-01 00:00:00</span>
<span class="go">1   -1.236269  foo 2013-01-01 00:00:01</span>
<span class="go">2    0.896171  foo 2013-01-01 00:00:02</span>
<span class="go">3   -0.487602  foo 2013-01-01 00:00:03</span>
<span class="go">4   -0.082240  foo 2013-01-01 00:00:04</span>
<span class="go">..        ...  ...                 ...</span>
<span class="go">995 -0.171092  foo 2013-01-01 00:16:35</span>
<span class="go">996  1.786173  foo 2013-01-01 00:16:36</span>
<span class="go">997 -0.575189  foo 2013-01-01 00:16:37</span>
<span class="go">998  0.820750  foo 2013-01-01 00:16:38</span>
<span class="go">999 -1.256530  foo 2013-01-01 00:16:39</span>

<span class="go">[1000 rows x 3 columns]</span>

<span class="gp">In [450]: </span><span class="n">df</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"s1.pkl.bz2"</span><span class="p">)</span>

<span class="gp">In [451]: </span><span class="n">rt</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_pickle</span><span class="p">(</span><span class="s2">"s1.pkl.bz2"</span><span class="p">)</span>

<span class="gp">In [452]: </span><span class="n">rt</span>
<span class="gh">Out[452]: </span>
<span class="go">0     -0.317441</span>
<span class="go">1     -1.236269</span>
<span class="go">2      0.896171</span>
<span class="go">3     -0.487602</span>
<span class="go">4     -0.082240</span>
<span class="go">         ...   </span>
<span class="go">995   -0.171092</span>
<span class="go">996    1.786173</span>
<span class="go">997   -0.575189</span>
<span class="go">998    0.820750</span>
<span class="go">999   -1.256530</span>
<span class="go">Name: A, Length: 1000, dtype: float64</span>
</pre>
</div>
</div>

<p>Passing options to the compression protocol in order to speed up compression:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell209"><span></span><span class="gp">In [453]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"data.pkl.gz"</span><span class="p">,</span> <span class="n">compression</span><span class="o">=</span><span class="p">{</span><span class="s2">"method"</span><span class="p">:</span> <span class="s2">"gzip"</span><span class="p">,</span> <span class="s2">"compresslevel"</span><span class="p">:</span> <span class="mi">1</span><span class="p">})</span>
</pre>
</div>
</div>

# <h2>HDF5 (PyTables)</h2>

<p><code>HDFStore</code> is a dict-like object which reads and writes pandas using the high performance HDF5 format using the excellent
<a href="https://www.pytables.org/">PyTables</a> library.
See the <a href="https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-hdf">cookbook</a> for some advanced strategies</p>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>pandas uses PyTables for reading and writing HDF5 files, which allows serializing object-dtype data with pickle. Loading pickled data received from untrusted sources can be unsafe.</p>
<p>See: <a href="https://docs.python.org/3/library/pickle.html">https://docs.python.org/3/library/pickle.html</a> for more.</p>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell210"><span></span><span class="gp">In [454]: </span><span class="n">store</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">HDFStore</span><span class="p">(</span><span class="s2">"store.h5"</span><span class="p">)</span>

<span class="gp">In [455]: </span><span class="nb">print</span><span class="p">(</span><span class="n">store</span><span class="p">)</span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>
</pre>
</div>
</div>
<p>Objects can be written to the file just like adding key-value pairs to a
dict:</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell211"><span></span><span class="gp">In [456]: </span><span class="n">index</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/1/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">8</span><span class="p">)</span>

<span class="gp">In [457]: </span><span class="n">s</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">5</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">,</span> <span class="s2">"e"</span><span class="p">])</span>

<span class="gp">In [458]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="n">index</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">])</span>

<span class="go"># store.put('s', s) is an equivalent method</span>
<span class="gp">In [459]: </span><span class="n">store</span><span class="p">[</span><span class="s2">"s"</span><span class="p">]</span> <span class="o">=</span> <span class="n">s</span>

<span class="gp">In [460]: </span><span class="n">store</span><span class="p">[</span><span class="s2">"df"</span><span class="p">]</span> <span class="o">=</span> <span class="n">df</span>

<span class="gp">In [461]: </span><span class="n">store</span>
<span class="gh">Out[461]: </span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>
</pre>
</div>
</div>

<p>In a current or later Python session, you can retrieve stored objects:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell212"><span></span><span class="go"># store.get('df') is an equivalent method</span>
<span class="gp">In [462]: </span><span class="n">store</span><span class="p">[</span><span class="s2">"df"</span><span class="p">]</span>
<span class="gh">Out[462]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006</span>
<span class="go">2000-01-02 -0.080372 -1.268121  1.561967</span>
<span class="go">2000-01-03  0.816983  1.965656 -1.169408</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517</span>

<span class="go"># dotted (attribute) access provides get as well</span>
<span class="gp">In [463]: </span><span class="n">store</span><span class="o">.</span><span class="n">df</span>
<span class="gh">Out[463]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006</span>
<span class="go">2000-01-02 -0.080372 -1.268121  1.561967</span>
<span class="go">2000-01-03  0.816983  1.965656 -1.169408</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517</span>
</pre>
</div>
</div>

<p>Deletion of the object specified by the key:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell213"><span></span><span class="go"># store.remove('df') is an equivalent method</span>
<span class="gp">In [464]: </span><span class="k">del</span> <span class="n">store</span><span class="p">[</span><span class="s2">"df"</span><span class="p">]</span>

<span class="gp">In [465]: </span><span class="n">store</span>
<span class="gh">Out[465]: </span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>
</pre>
</div>
</div>

<p>Closing a Store and using a context manager:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell214"><span></span><span class="gp">In [466]: </span><span class="n">store</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>

<span class="gp">In [467]: </span><span class="n">store</span>
<span class="gh">Out[467]: </span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>

<span class="gp">In [468]: </span><span class="n">store</span><span class="o">.</span><span class="n">is_open</span>
<span class="gh">Out[468]: </span><span class="go">False</span>

<span class="go"># Working with, and automatically closing the store using a context manager</span>
<span class="gp">In [469]: </span><span class="k">with</span> <span class="n">pd</span><span class="o">.</span><span class="n">HDFStore</span><span class="p">(</span><span class="s2">"store.h5"</span><span class="p">)</span> <span class="k">as</span> <span class="n">store</span><span class="p">:</span>
<span class="gp"></span>    <span class="n">store</span><span class="o">.</span><span class="n">keys</span><span class="p">()</span>
<span class="gp"></span>
</pre>
</div>
</div>

## <h3>Read/write API</h3>

<p><code>HDFStore</code> supports a top-level API using  <code>read_hdf</code> for reading and <code>to_hdf</code> for writing, similar to how <code>read_csv</code> and <code>to_csv</code> work.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell215"><span></span><span class="gp">In [470]: </span><span class="n">df_tl</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">5</span><span class="p">)),</span> <span class="s2">"B"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">5</span><span class="p">))})</span>

<span class="gp">In [471]: </span><span class="n">df_tl</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span><span class="s2">"store_tl.h5"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">append</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="gp">In [472]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"store_tl.h5"</span><span class="p">,</span> <span class="s2">"table"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="p">[</span><span class="s2">"index&gt;2"</span><span class="p">])</span>
<span class="gh">Out[472]: </span>
<span class="go">   A  B</span>
<span class="go">3  3  3</span>
<span class="go">4  4  4</span>
</pre>
</div>
</div>

<p>HDFStore will by default not drop rows that are all missing. This behavior can be changed by setting <code>dropna=True</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell216"><span></span><span class="gp">In [473]: </span><span class="n">df_with_missing</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"col1"</span><span class="p">:</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"col2"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">],</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [474]: </span><span class="n">df_with_missing</span>
<span class="gh">Out[474]: </span>
<span class="go">   col1  col2</span>
<span class="go">0   0.0   1.0</span>
<span class="go">1   NaN   NaN</span>
<span class="go">2   2.0   NaN</span>

<span class="gp">In [475]: </span><span class="n">df_with_missing</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span><span class="s2">"file.h5"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"df_with_missing"</span><span class="p">,</span> <span class="nb">format</span><span class="o">=</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">)</span>

<span class="gp">In [476]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"file.h5"</span><span class="p">,</span> <span class="s2">"df_with_missing"</span><span class="p">)</span>
<span class="gh">Out[476]: </span>
<span class="go">   col1  col2</span>
<span class="go">0   0.0   1.0</span>
<span class="go">1   NaN   NaN</span>
<span class="go">2   2.0   NaN</span>

<span class="gp">In [477]: </span><span class="n">df_with_missing</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span>
<span class="gp"></span>    <span class="s2">"file.h5"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"df_with_missing"</span><span class="p">,</span> <span class="nb">format</span><span class="o">=</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">,</span> <span class="n">dropna</span><span class="o">=</span><span class="kc">True</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [478]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"file.h5"</span><span class="p">,</span> <span class="s2">"df_with_missing"</span><span class="p">)</span>
<span class="gh">Out[478]: </span>
<span class="go">   col1  col2</span>
<span class="go">0   0.0   1.0</span>
<span class="go">2   2.0   NaN</span>
</pre>
</div>
</div>

## <h3>Fixed format</h3>

<p>The examples above show storing using <code>put</code>, which write the HDF5 to <code>PyTables</code> in a fixed array format, called the <code>fixed</code> format. These types of stores are <strong>not</strong> appendable once written (though you can simply remove them and rewrite). Nor are they <strong>queryable</strong>; they must be retrieved in their entirety. They also do not support dataframes with non-unique column names.
The <code>fixed</code> format stores offer very fast writing and slightly faster reading than <code>table</code> stores.
This format is specified by default when using <code>put</code> or <code>to_hdf</code> or by <code>format='fixed'</code> or <code>format='f'</code>.</p>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>A <code>fixed</code> format will raise a <code>TypeError</code> if you try to retrieve using a <code>where</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell217"><span></span><span class="gp">In [479]: </span><span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">2</span><span class="p">))</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span><span class="s2">"test_fixed.h5"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"df"</span><span class="p">)</span>

<span class="gp">In [480]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"test_fixed.h5"</span><span class="p">,</span> <span class="s2">"df"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="s2">"index&gt;5"</span><span class="p">)</span>
<span class="gt">---------------------------------------------------------------------------</span>
<span class="ne">TypeError</span><span class="g g-Whitespace">                                 </span>Traceback (most recent call last)
<span class="n">Cell</span> <span class="n">In</span><span class="p">[</span><span class="mi">480</span><span class="p">],</span> <span class="n">line</span> <span class="mi">1</span>
<span class="ne">----&gt; </span><span class="mi">1</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"test_fixed.h5"</span><span class="p">,</span> <span class="s2">"df"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="s2">"index&gt;5"</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:465,</span> in <span class="ni">read_hdf</span><span class="nt">(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)</span>
<span class="g g-Whitespace">    </span><span class="mi">460</span>                 <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span>
<span class="g g-Whitespace">    </span><span class="mi">461</span>                     <span class="s2">"key must be provided when HDF5 "</span>
<span class="g g-Whitespace">    </span><span class="mi">462</span>                     <span class="s2">"file contains multiple datasets."</span>
<span class="g g-Whitespace">    </span><span class="mi">463</span>                 <span class="p">)</span>
<span class="g g-Whitespace">    </span><span class="mi">464</span>         <span class="n">key</span> <span class="o">=</span> <span class="n">candidate_only_group</span><span class="o">.</span><span class="n">_v_pathname</span>
<span class="ne">--&gt; </span><span class="mi">465</span>     <span class="k">return</span> <span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span>
<span class="g g-Whitespace">    </span><span class="mi">466</span>         <span class="n">key</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">467</span>         <span class="n">where</span><span class="o">=</span><span class="n">where</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">468</span>         <span class="n">start</span><span class="o">=</span><span class="n">start</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">469</span>         <span class="n">stop</span><span class="o">=</span><span class="n">stop</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">470</span>         <span class="n">columns</span><span class="o">=</span><span class="n">columns</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">471</span>         <span class="n">iterator</span><span class="o">=</span><span class="n">iterator</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">472</span>         <span class="n">chunksize</span><span class="o">=</span><span class="n">chunksize</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">473</span>         <span class="n">auto_close</span><span class="o">=</span><span class="n">auto_close</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">474</span>     <span class="p">)</span>
<span class="g g-Whitespace">    </span><span class="mi">475</span> <span class="k">except</span> <span class="p">(</span><span class="ne">ValueError</span><span class="p">,</span> <span class="ne">TypeError</span><span class="p">,</span> <span class="ne">LookupError</span><span class="p">):</span>
<span class="g g-Whitespace">    </span><span class="mi">476</span>     <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">path_or_buf</span><span class="p">,</span> <span class="n">HDFStore</span><span class="p">):</span>
<span class="g g-Whitespace">    </span><span class="mi">477</span>         <span class="c1"># if there is an error, close the store if we opened it.</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:919,</span> in <span class="ni">HDFStore.select</span><span class="nt">(self, key, where, start, stop, columns, iterator, chunksize, auto_close)</span>
<span class="g g-Whitespace">    </span><span class="mi">905</span> <span class="c1"># create the iterator</span>
<span class="g g-Whitespace">    </span><span class="mi">906</span> <span class="n">it</span> <span class="o">=</span> <span class="n">TableIterator</span><span class="p">(</span>
<span class="g g-Whitespace">    </span><span class="mi">907</span>     <span class="bp">self</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">908</span>     <span class="n">s</span><span class="p">,</span>
   <span class="p">(</span><span class="o">...</span><span class="p">)</span>
<span class="g g-Whitespace">    </span><span class="mi">916</span>     <span class="n">auto_close</span><span class="o">=</span><span class="n">auto_close</span><span class="p">,</span>
<span class="g g-Whitespace">    </span><span class="mi">917</span> <span class="p">)</span>
<span class="ne">--&gt; </span><span class="mi">919</span> <span class="k">return</span> <span class="n">it</span><span class="o">.</span><span class="n">get_result</span><span class="p">()</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:2042,</span> in <span class="ni">TableIterator.get_result</span><span class="nt">(self, coordinates)</span>
<span class="g g-Whitespace">   </span><span class="mi">2039</span>     <span class="n">where</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">where</span>
<span class="g g-Whitespace">   </span><span class="mi">2041</span> <span class="c1"># directly return the result</span>
<span class="ne">-&gt; </span><span class="mi">2042</span> <span class="n">results</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">func</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">start</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">stop</span><span class="p">,</span> <span class="n">where</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">2043</span> <span class="bp">self</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>
<span class="g g-Whitespace">   </span><span class="mi">2044</span> <span class="k">return</span> <span class="n">results</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:903,</span> in <span class="ni">HDFStore.select.&lt;locals&gt;.func</span><span class="nt">(_start, _stop, _where)</span>
<span class="g g-Whitespace">    </span><span class="mi">902</span> <span class="k">def</span><span class="w"> </span><span class="nf">func</span><span class="p">(</span><span class="n">_start</span><span class="p">,</span> <span class="n">_stop</span><span class="p">,</span> <span class="n">_where</span><span class="p">):</span>
<span class="ne">--&gt; </span><span class="mi">903</span>     <span class="k">return</span> <span class="n">s</span><span class="o">.</span><span class="n">read</span><span class="p">(</span><span class="n">start</span><span class="o">=</span><span class="n">_start</span><span class="p">,</span> <span class="n">stop</span><span class="o">=</span><span class="n">_stop</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="n">_where</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="n">columns</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:3345,</span> in <span class="ni">BlockManagerFixed.read</span><span class="nt">(self, where, columns, start, stop)</span>
<span class="g g-Whitespace">   </span><span class="mi">3337</span> <span class="k">def</span><span class="w"> </span><span class="nf">read</span><span class="p">(</span>
<span class="g g-Whitespace">   </span><span class="mi">3338</span>     <span class="bp">self</span><span class="p">,</span>
<span class="g g-Whitespace">   </span><span class="mi">3339</span>     <span class="n">where</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span>
   <span class="p">(</span><span class="o">...</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">3343</span> <span class="p">)</span> <span class="o">-&gt;</span> <span class="n">DataFrame</span><span class="p">:</span>
<span class="g g-Whitespace">   </span><span class="mi">3344</span>     <span class="c1"># start, stop applied to rows, so 0th axis only</span>
<span class="ne">-&gt; </span><span class="mi">3345</span>     <span class="bp">self</span><span class="o">.</span><span class="n">validate_read</span><span class="p">(</span><span class="n">columns</span><span class="p">,</span> <span class="n">where</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">3346</span>     <span class="n">select_axis</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">obj_type</span><span class="p">()</span><span class="o">.</span><span class="n">_get_block_manager_axis</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">3348</span>     <span class="n">axes</span> <span class="o">=</span> <span class="p">[]</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:2949,</span> in <span class="ni">GenericFixed.validate_read</span><span class="nt">(self, columns, where)</span>
<span class="g g-Whitespace">   </span><span class="mi">2944</span>     <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span>
<span class="g g-Whitespace">   </span><span class="mi">2945</span>         <span class="s2">"cannot pass a column specification when reading "</span>
<span class="g g-Whitespace">   </span><span class="mi">2946</span>         <span class="s2">"a Fixed format store. this store must be selected in its entirety"</span>
<span class="g g-Whitespace">   </span><span class="mi">2947</span>     <span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">2948</span> <span class="k">if</span> <span class="n">where</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span>
<span class="ne">-&gt; </span><span class="mi">2949</span>     <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span>
<span class="g g-Whitespace">   </span><span class="mi">2950</span>         <span class="s2">"cannot pass a where specification when reading "</span>
<span class="g g-Whitespace">   </span><span class="mi">2951</span>         <span class="s2">"from a Fixed format store. this store must be selected in its entirety"</span>
<span class="g g-Whitespace">   </span><span class="mi">2952</span>     <span class="p">)</span>

<span class="ne">TypeError</span>: cannot pass a where specification when reading from a Fixed format store. this store must be selected in its entirety
</pre>
</div>
</div>
</div>

## <h3>Table format</h3>

<p><code>HDFStore</code> supports another <code>PyTables</code> format on disk, the <code>table</code> format. Conceptually a <code>table</code> is shaped very much like a DataFrame, with rows and columns. A <code>table</code> may be appended to in the same or other sessions.  In addition, delete and query type operations are supported. This format is specified by <code>format='table'</code> or <code>format='t'</code>
to <code>append</code> or <code>put</code> or <code>to_hdf</code>.</p>

<p>This format can be set as an option as well <code>pd.set_option('io.hdf.default_format','table')</code> to
enable <code>put/append/to_hdf</code> to by default store in the <code>table</code> format.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell218"><span></span><span class="gp">In [481]: </span><span class="n">store</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">HDFStore</span><span class="p">(</span><span class="s2">"store.h5"</span><span class="p">)</span>

<span class="gp">In [482]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">df</span><span class="p">[</span><span class="mi">0</span><span class="p">:</span><span class="mi">4</span><span class="p">]</span>

<span class="gp">In [483]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">df</span><span class="p">[</span><span class="mi">4</span><span class="p">:]</span>

<span class="go"># append data (creates a table automatically)</span>
<span class="gp">In [484]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">df1</span><span class="p">)</span>

<span class="gp">In [485]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">df2</span><span class="p">)</span>

<span class="gp">In [486]: </span><span class="n">store</span>
<span class="gh">Out[486]: </span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>

<span class="go"># select the entire object</span>
<span class="gp">In [487]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df"</span><span class="p">)</span>
<span class="gh">Out[487]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006</span>
<span class="go">2000-01-02 -0.080372 -1.268121  1.561967</span>
<span class="go">2000-01-03  0.816983  1.965656 -1.169408</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517</span>

<span class="go"># the type of stored data</span>
<span class="gp">In [488]: </span><span class="n">store</span><span class="o">.</span><span class="n">root</span><span class="o">.</span><span class="n">df</span><span class="o">.</span><span class="n">_v_attrs</span><span class="o">.</span><span class="n">pandas_type</span>
<span class="gh">Out[488]: </span><span class="go">'frame_table'</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>You can also create a <code>table</code> by passing <code>format='table'</code> or <code>format='t'</code> to a <code>put</code> operation.</p>
</div>

## <h3>Hierarchical keys</h3>

<p>Keys to a store can be specified as a string. These can be in a hierarchical path-name like format (e.g. <code>foo/bar/bah</code>), which will generate a hierarchy of sub-stores (or <code>Groups</code> in PyTables parlance). Keys can be specified without the leading ‘/’ and are <strong>always</strong> absolute (e.g. ‘foo’ refers to ‘/foo’). Removal operations can remove everything in the sub-store and <strong>below</strong>, so be <em>careful</em>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell219"><span></span><span class="gp">In [489]: </span><span class="n">store</span><span class="o">.</span><span class="n">put</span><span class="p">(</span><span class="s2">"foo/bar/bah"</span><span class="p">,</span> <span class="n">df</span><span class="p">)</span>

<span class="gp">In [490]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"food/orange"</span><span class="p">,</span> <span class="n">df</span><span class="p">)</span>

<span class="gp">In [491]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"food/apple"</span><span class="p">,</span> <span class="n">df</span><span class="p">)</span>

<span class="gp">In [492]: </span><span class="n">store</span>
<span class="gh">Out[492]: </span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>

<span class="go"># a list of keys are returned</span>
<span class="gp">In [493]: </span><span class="n">store</span><span class="o">.</span><span class="n">keys</span><span class="p">()</span>
<span class="gh">Out[493]: </span><span class="go">['/df', '/food/apple', '/food/orange', '/foo/bar/bah']</span>

<span class="go"># remove all nodes under this level</span>
<span class="gp">In [494]: </span><span class="n">store</span><span class="o">.</span><span class="n">remove</span><span class="p">(</span><span class="s2">"food"</span><span class="p">)</span>

<span class="gp">In [495]: </span><span class="n">store</span>
<span class="gh">Out[495]: </span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>
</pre>
</div>
</div>

<p>You can walk through the group hierarchy using the <code>walk</code> method which will yield a tuple for each group key along with the relative keys of its contents.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell220"><span></span><span class="gp">In [496]: </span><span class="k">for</span> <span class="p">(</span><span class="n">path</span><span class="p">,</span> <span class="n">subgroups</span><span class="p">,</span> <span class="n">subkeys</span><span class="p">)</span> <span class="ow">in</span> <span class="n">store</span><span class="o">.</span><span class="n">walk</span><span class="p">():</span>
<span class="gp"></span>    <span class="k">for</span> <span class="n">subgroup</span> <span class="ow">in</span> <span class="n">subgroups</span><span class="p">:</span>
<span class="gp"></span>        <span class="nb">print</span><span class="p">(</span><span class="s2">"GROUP: </span><span class="si">{}</span><span class="s2">/</span><span class="si">{}</span><span class="s2">"</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">path</span><span class="p">,</span> <span class="n">subgroup</span><span class="p">))</span>
<span class="gp"></span>    <span class="k">for</span> <span class="n">subkey</span> <span class="ow">in</span> <span class="n">subkeys</span><span class="p">:</span>
<span class="gp"></span>        <span class="n">key</span> <span class="o">=</span> <span class="s2">"/"</span><span class="o">.</span><span class="n">join</span><span class="p">([</span><span class="n">path</span><span class="p">,</span> <span class="n">subkey</span><span class="p">])</span>
<span class="gp"></span>        <span class="nb">print</span><span class="p">(</span><span class="s2">"KEY: </span><span class="si">{}</span><span class="s2">"</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">key</span><span class="p">))</span>
<span class="gp"></span>        <span class="nb">print</span><span class="p">(</span><span class="n">store</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="n">key</span><span class="p">))</span>
<span class="gp"></span>
<span class="go">GROUP: /foo</span>
<span class="go">KEY: /df</span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006</span>
<span class="go">2000-01-02 -0.080372 -1.268121  1.561967</span>
<span class="go">2000-01-03  0.816983  1.965656 -1.169408</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517</span>
<span class="go">GROUP: /foo/bar</span>
<span class="go">KEY: /foo/bar/bah</span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006</span>
<span class="go">2000-01-02 -0.080372 -1.268121  1.561967</span>
<span class="go">2000-01-03  0.816983  1.965656 -1.169408</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517</span>
</pre>
</div>
</div>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Hierarchical keys cannot be retrieved as dotted (attribute) access as described above for items stored under the root node.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell221"><span></span><span class="gp">In [497]: </span><span class="n">store</span><span class="o">.</span><span class="n">foo</span><span class="o">.</span><span class="n">bar</span><span class="o">.</span><span class="n">bah</span>
<span class="gt">---------------------------------------------------------------------------</span>
<span class="ne">TypeError</span><span class="g g-Whitespace">                                 </span>Traceback (most recent call last)
<span class="n">Cell</span> <span class="n">In</span><span class="p">[</span><span class="mi">497</span><span class="p">],</span> <span class="n">line</span> <span class="mi">1</span>
<span class="ne">----&gt; </span><span class="mi">1</span> <span class="n">store</span><span class="o">.</span><span class="n">foo</span><span class="o">.</span><span class="n">bar</span><span class="o">.</span><span class="n">bah</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:626,</span> in <span class="ni">HDFStore.__getattr__</span><span class="nt">(self, name)</span>
<span class="g g-Whitespace">    </span><span class="mi">624</span><span class="w"> </span><span class="sd">"""allow attribute access to get stores"""</span>
<span class="g g-Whitespace">    </span><span class="mi">625</span> <span class="k">try</span><span class="p">:</span>
<span class="ne">--&gt; </span><span class="mi">626</span>     <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="n">name</span><span class="p">)</span>
<span class="g g-Whitespace">    </span><span class="mi">627</span> <span class="k">except</span> <span class="p">(</span><span class="ne">KeyError</span><span class="p">,</span> <span class="n">ClosedFileError</span><span class="p">):</span>
<span class="g g-Whitespace">    </span><span class="mi">628</span>     <span class="k">pass</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:826,</span> in <span class="ni">HDFStore.get</span><span class="nt">(self, key)</span>
<span class="g g-Whitespace">    </span><span class="mi">824</span> <span class="k">if</span> <span class="n">group</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span>
<span class="g g-Whitespace">    </span><span class="mi">825</span>     <span class="k">raise</span> <span class="ne">KeyError</span><span class="p">(</span><span class="sa">f</span><span class="s2">"No object named </span><span class="si">{</span><span class="n">key</span><span class="si">}</span><span class="s2"> in the file"</span><span class="p">)</span>
<span class="ne">--&gt; </span><span class="mi">826</span> <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_read_group</span><span class="p">(</span><span class="n">group</span><span class="p">)</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:1891,</span> in <span class="ni">HDFStore._read_group</span><span class="nt">(self, group)</span>
<span class="g g-Whitespace">   </span><span class="mi">1890</span> <span class="k">def</span><span class="w"> </span><span class="nf">_read_group</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">group</span><span class="p">:</span> <span class="n">Node</span><span class="p">):</span>
<span class="ne">-&gt; </span><span class="mi">1891</span>     <span class="n">s</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_create_storer</span><span class="p">(</span><span class="n">group</span><span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">1892</span>     <span class="n">s</span><span class="o">.</span><span class="n">infer_axes</span><span class="p">()</span>
<span class="g g-Whitespace">   </span><span class="mi">1893</span>     <span class="k">return</span> <span class="n">s</span><span class="o">.</span><span class="n">read</span><span class="p">()</span>

<span class="nn">File ~/work/pandas/pandas/pandas/io/pytables.py:1765,</span> in <span class="ni">HDFStore._create_storer</span><span class="nt">(self, group, format, value, encoding, errors)</span>
<span class="g g-Whitespace">   </span><span class="mi">1763</span>         <span class="n">tt</span> <span class="o">=</span> <span class="s2">"generic_table"</span>
<span class="g g-Whitespace">   </span><span class="mi">1764</span>     <span class="k">else</span><span class="p">:</span>
<span class="ne">-&gt; </span><span class="mi">1765</span>         <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span>
<span class="g g-Whitespace">   </span><span class="mi">1766</span>             <span class="s2">"cannot create a storer if the object is not existing "</span>
<span class="g g-Whitespace">   </span><span class="mi">1767</span>             <span class="s2">"nor a value are passed"</span>
<span class="g g-Whitespace">   </span><span class="mi">1768</span>         <span class="p">)</span>
<span class="g g-Whitespace">   </span><span class="mi">1769</span> <span class="k">else</span><span class="p">:</span>
<span class="g g-Whitespace">   </span><span class="mi">1770</span>     <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">value</span><span class="p">,</span> <span class="n">Series</span><span class="p">):</span>

<span class="ne">TypeError</span>: cannot create a storer if the object is not existing nor a value are passed
</pre>
</div>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell222"><span></span><span class="go"># you can directly access the actual PyTables node but using the root node</span>
<span class="gp">In [498]: </span><span class="n">store</span><span class="o">.</span><span class="n">root</span><span class="o">.</span><span class="n">foo</span><span class="o">.</span><span class="n">bar</span><span class="o">.</span><span class="n">bah</span>
<span class="gh">Out[498]: </span>
<span class="go">/foo/bar/bah (Group) ''</span>
<span class="go">  children := ['axis0' (Array), 'axis1' (Array), 'block0_items' (Array), 'block0_values' (Array)]</span>
</pre>
</div>
</div>

<p>Instead, use explicit string based keys:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell223"><span></span><span class="gp">In [499]: </span><span class="n">store</span><span class="p">[</span><span class="s2">"foo/bar/bah"</span><span class="p">]</span>
<span class="gh">Out[499]: </span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006</span>
<span class="go">2000-01-02 -0.080372 -1.268121  1.561967</span>
<span class="go">2000-01-03  0.816983  1.965656 -1.169408</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517</span>
</pre>
</div>
</div>
</div>

## <h3>Storing types</h3>

### <h4>Storing mixed types in a table</h4>

<p>Storing mixed-dtype data is supported. Strings are stored as a fixed-width using the maximum size of the appended column. Subsequent attempts at appending longer strings will raise a <code>ValueError</code>.</p>

<p>Passing <code>min_itemsize={`values`: size}</code> as a parameter to append will set a larger minimum for the string columns. Storing <code>floats, strings, ints, bools, datetime64</code> are currently supported. For string
columns, passing <code>nan_rep = 'nan'</code> to append will change the default nan representation on disk (which converts to/from <code>np.nan</code>), this defaults to <code>nan</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell224"><span></span><span class="gp">In [500]: </span><span class="n">df_mixed</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"B"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"C"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">),</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float32"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"string"</span><span class="p">:</span> <span class="s2">"string"</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"int"</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"bool"</span><span class="p">:</span> <span class="kc">True</span><span class="p">,</span>
<span class="gp"></span>        <span class="s2">"datetime64"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timestamp</span><span class="p">(</span><span class="s2">"20010102"</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">},</span>
<span class="gp"></span>    <span class="n">index</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">8</span><span class="p">)),</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [501]: </span><span class="n">df_mixed</span><span class="o">.</span><span class="n">loc</span><span class="p">[</span><span class="n">df_mixed</span><span class="o">.</span><span class="n">index</span><span class="p">[</span><span class="mi">3</span><span class="p">:</span><span class="mi">5</span><span class="p">],</span> <span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"string"</span><span class="p">,</span> <span class="s2">"datetime64"</span><span class="p">]]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [502]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df_mixed"</span><span class="p">,</span> <span class="n">df_mixed</span><span class="p">,</span> <span class="n">min_itemsize</span><span class="o">=</span><span class="p">{</span><span class="s2">"values"</span><span class="p">:</span> <span class="mi">50</span><span class="p">})</span>

<span class="gp">In [503]: </span><span class="n">df_mixed1</span> <span class="o">=</span> <span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_mixed"</span><span class="p">)</span>

<span class="gp">In [504]: </span><span class="n">df_mixed1</span>
<span class="gh">Out[504]: </span>
<span class="go">          A         B         C  ... int  bool                    datetime64</span>
<span class="go">0  0.013747 -1.166078 -1.292080  ...   1  True 1970-01-01 00:00:00.978393600</span>
<span class="go">1 -0.712009  0.247572  1.526911  ...   1  True 1970-01-01 00:00:00.978393600</span>
<span class="go">2 -0.645096  1.687406  0.288504  ...   1  True 1970-01-01 00:00:00.978393600</span>
<span class="go">3       NaN       NaN  0.097771  ...   1  True                           NaT</span>
<span class="go">4       NaN       NaN  1.536408  ...   1  True                           NaT</span>
<span class="go">5 -0.023202  0.043702  0.926790  ...   1  True 1970-01-01 00:00:00.978393600</span>
<span class="go">6  2.359782  0.088224 -0.676448  ...   1  True 1970-01-01 00:00:00.978393600</span>
<span class="go">7 -0.143428 -0.813360 -0.179724  ...   1  True 1970-01-01 00:00:00.978393600</span>

<span class="go">[8 rows x 7 columns]</span>

<span class="gp">In [505]: </span><span class="n">df_mixed1</span><span class="o">.</span><span class="n">dtypes</span><span class="o">.</span><span class="n">value_counts</span><span class="p">()</span>
<span class="gh">Out[505]: </span>
<span class="go">float64           2</span>
<span class="go">float32           1</span>
<span class="go">object            1</span>
<span class="go">int64             1</span>
<span class="go">bool              1</span>
<span class="go">datetime64[ns]    1</span>
<span class="go">Name: count, dtype: int64</span>

<span class="go"># we have provided a minimum string column size</span>
<span class="gp">In [506]: </span><span class="n">store</span><span class="o">.</span><span class="n">root</span><span class="o">.</span><span class="n">df_mixed</span><span class="o">.</span><span class="n">table</span>
<span class="gh">Out[506]: </span>
<span class="go">/df_mixed/table (Table(8,)) ''</span>
<span class="go">  description := {</span>
<span class="go">  "index": Int64Col(shape=(), dflt=0, pos=0),</span>
<span class="go">  "values_block_0": Float64Col(shape=(2,), dflt=0.0, pos=1),</span>
<span class="go">  "values_block_1": Float32Col(shape=(1,), dflt=0.0, pos=2),</span>
<span class="go">  "values_block_2": StringCol(itemsize=50, shape=(1,), dflt=b'', pos=3),</span>
<span class="go">  "values_block_3": Int64Col(shape=(1,), dflt=0, pos=4),</span>
<span class="go">  "values_block_4": BoolCol(shape=(1,), dflt=False, pos=5),</span>
<span class="go">  "values_block_5": Int64Col(shape=(1,), dflt=0, pos=6)}</span>
<span class="go">  byteorder := 'little'</span>
<span class="go">  chunkshape := (689,)</span>
<span class="go">  autoindex := True</span>
<span class="go">  colindexes := {</span>
<span class="go">    "index": Index(6, mediumshuffle, zlib(1)).is_csi=False}</span>
</pre>
</div>
</div>

### <h4>Storing MultiIndex DataFrames</h4>

<p>Storing MultiIndex <code>DataFrames</code> as tables is very similar to storing/selecting from homogeneous index <code>DataFrames</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell225"><span></span><span class="gp">In [507]: </span><span class="n">index</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="p">(</span>
<span class="gp"></span>   <span class="n">levels</span><span class="o">=</span><span class="p">[[</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"baz"</span><span class="p">,</span> <span class="s2">"qux"</span><span class="p">],</span> <span class="p">[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"three"</span><span class="p">]],</span>
<span class="gp"></span>   <span class="n">codes</span><span class="o">=</span><span class="p">[[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]],</span>
<span class="gp"></span>   <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">],</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [508]: </span><span class="n">df_mi</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="n">index</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">])</span>

<span class="gp">In [509]: </span><span class="n">df_mi</span>
<span class="gh">Out[509]: </span>
<span class="go">                  A         B         C</span>
<span class="go">foo bar                                </span>
<span class="go">foo one   -1.303456 -0.642994 -0.649456</span>
<span class="go">    two    1.012694  0.414147  1.950460</span>
<span class="go">    three  1.094544 -0.802899 -0.583343</span>
<span class="go">bar one    0.410395  0.618321  0.560398</span>
<span class="go">    two    1.434027 -0.033270  0.343197</span>
<span class="go">baz two   -1.646063 -0.695847 -0.429156</span>
<span class="go">    three -0.244688 -1.428229 -0.138691</span>
<span class="go">qux one    1.866184 -1.446617  0.036660</span>
<span class="go">    two   -1.660522  0.929553 -1.298649</span>
<span class="go">    three  3.565769  0.682402  1.041927</span>

<span class="gp">In [510]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df_mi"</span><span class="p">,</span> <span class="n">df_mi</span><span class="p">)</span>

<span class="gp">In [511]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_mi"</span><span class="p">)</span>
<span class="gh">Out[511]: </span>
<span class="go">                  A         B         C</span>
<span class="go">foo bar                                </span>
<span class="go">foo one   -1.303456 -0.642994 -0.649456</span>
<span class="go">    two    1.012694  0.414147  1.950460</span>
<span class="go">    three  1.094544 -0.802899 -0.583343</span>
<span class="go">bar one    0.410395  0.618321  0.560398</span>
<span class="go">    two    1.434027 -0.033270  0.343197</span>
<span class="go">baz two   -1.646063 -0.695847 -0.429156</span>
<span class="go">    three -0.244688 -1.428229 -0.138691</span>
<span class="go">qux one    1.866184 -1.446617  0.036660</span>
<span class="go">    two   -1.660522  0.929553 -1.298649</span>
<span class="go">    three  3.565769  0.682402  1.041927</span>

<span class="go"># the levels are automatically included as data columns</span>
<span class="gp">In [512]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_mi"</span><span class="p">,</span> <span class="s2">"foo=bar"</span><span class="p">)</span>
<span class="gh">Out[512]: </span>
<span class="go">                A         B         C</span>
<span class="go">foo bar                              </span>
<span class="go">bar one  0.410395  0.618321  0.560398</span>
<span class="go">    two  1.434027 -0.033270  0.343197</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The <code>index</code> keyword is reserved and cannot be use as a level name.</p>
</div>

## <h3>Querying</h3>

### <h4>Querying a table</h4>

<p><code>select</code> and <code>delete</code> operations have an optional criterion that can be specified to select/delete only a subset of the data. This allows one to have a very large on-disk table and retrieve only a portion of the data.</p>

<p>A query is specified using the <code>Term</code> class under the hood, as a boolean expression.</p>

<ul class="simple">
<li><p><code>index</code> and <code>columns</code> are supported indexers of <code>DataFrames</code>.</p></li>
<li><p>if <code>data_columns</code> are specified, these can be used as additional indexers.</p></li>
<li><p>level name in a MultiIndex, with default name  <code>level_0</code>, <code>level_1</code>, … if not provided.</p></li>
</ul>

<p>Valid comparison operators are:</p>

<p><code>=, ==, !=, &gt;, &gt;=, &lt;, &lt;=</code></p>

<p>Valid boolean expressions are combined with:</p>

<ul class="simple">
<li><p><code>|</code> : or</p></li>
<li><p><code>&amp;</code> : and</p></li>
<li><p><code>(</code> and <code>)</code> : for grouping</p></li>
</ul>

<p>These rules are similar to how boolean expressions are used in pandas for indexing.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<ul class="simple">
<li><p><code>=</code> will be automatically expanded to the comparison operator <code>==</code></p></li>
<li><p><code>~</code> is the not operator, but can only be used in very limited circumstances</p></li>
<li><p>If a list/tuple of expressions is passed they will be combined via <code>&amp;</code></p></li>
</ul>
</div>

<p>The following are valid expressions:</p>

<ul class="simple">
<li><p><code>'index &gt;= date'</code></p></li>
<li><p><code>"columns = ['A', 'D']"</code></p></li>
<li><p><code>"columns in ['A', 'D']"</code></p></li>
<li><p><code>'columns = A'</code></p></li>
<li><p><code>'columns == A'</code></p></li>
<li><p><code>"~(columns = ['A', 'B'])"</code></p></li>
<li><p><code>'index &gt; df.index[3] &amp; string = "bar"'</code></p></li>
<li><p><code>'(index &gt; df.index[3] &amp; index &lt;= df.index[6]) | string = "bar"'</code></p></li>
<li><p><code>"ts &gt;= Timestamp('2012-02-01')"</code></p></li>
<li><p><code>"major_axis&gt;=20130101"</code></p></li>
</ul>

<p>The <code>indexers</code> are on the left-hand side of the sub-expression:</p>

<p><code>columns</code>, <code>major_axis</code>, <code>ts</code></p>

<p>The right-hand side of the sub-expression (after a comparison operator) can be:</p>

<ul class="simple">
<li><p>functions that will be evaluated, e.g. <code>Timestamp('2012-02-01')</code></p></li>
<li><p>strings, e.g. <code>"bar"</code></p></li>
<li><p>date-like, e.g. <code>20130101</code>, or <code>"20130101"</code></p></li>
<li><p>lists, e.g. <code>"['A', 'B']"</code></p></li>
<li><p>variables that are defined in the local names space, e.g. <code>date</code></p></li>
</ul>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Passing a string to a query by interpolating it into the query expression is not recommended. Simply assign the string of interest to a variable and use that variable in an expression. For example, do this</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell226"><span></span><span class="n">string</span> <span class="o">=</span> <span class="s2">"HolyMoly'"</span>
<span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="s2">"index == string"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>instead of this</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell227"><span></span><span class="n">string</span> <span class="o">=</span> <span class="s2">"HolyMoly'"</span>
<span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s1">'df'</span><span class="p">,</span> <span class="sa">f</span><span class="s1">'index == </span><span class="si">{</span><span class="n">string</span><span class="si">}</span><span class="s1">'</span><span class="p">)</span>
</pre>
</div>
</div>

<p>The latter will <strong>not</strong> work and will raise a <code>SyntaxError</code>.
Note that there’s a single quote followed by a double quote in the <code>string</code> variable.</p>

<p>If you <em>must</em> interpolate, use the <code>'%r'</span></code> format specifier</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell228"><span></span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="s2">"index == </span><span class="si">%r</span><span class="s2">"</span> <span class="o">%</span> <span class="n">string</span><span class="p">)</span>
</pre>
</div>
</div>

<p>which will quote <code>string</code>.</p>
</div>

<p>Here are some examples:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell229"><span></span><span class="gp">In [513]: </span><span class="n">dfq</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">4</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">columns</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="s2">"ABCD"</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">10</span><span class="p">),</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [514]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dfq"</span><span class="p">,</span> <span class="n">dfq</span><span class="p">,</span> <span class="nb">format</span><span class="o">=</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">data_columns</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Use boolean expressions, with in-line function evaluation.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell230"><span></span><span class="gp">In [515]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"dfq"</span><span class="p">,</span> <span class="s2">"index&gt;pd.Timestamp('20130104') &amp; columns=['A', 'B']"</span><span class="p">)</span>
<span class="gh">Out[515]: </span>
<span class="go">                   A         B</span>
<span class="go">2013-01-05 -0.830545 -0.457071</span>
<span class="go">2013-01-06  0.431186  1.049421</span>
<span class="go">2013-01-07  0.617509 -0.811230</span>
<span class="go">2013-01-08  0.947422 -0.671233</span>
<span class="go">2013-01-09 -0.183798 -1.211230</span>
<span class="go">2013-01-10  0.361428  0.887304</span>
</pre>
</div>
</div>

<p>Use inline column reference.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell231"><span></span><span class="gp">In [516]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"dfq"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="s2">"A&gt;0 or C&gt;0"</span><span class="p">)</span>
<span class="gh">Out[516]: </span>
<span class="go">                   A         B         C         D</span>
<span class="go">2013-01-02  0.658179  0.362814 -0.917897  0.010165</span>
<span class="go">2013-01-03  0.905122  1.848731 -1.184241  0.932053</span>
<span class="go">2013-01-05 -0.830545 -0.457071  1.565581  1.148032</span>
<span class="go">2013-01-06  0.431186  1.049421  0.383309  0.595013</span>
<span class="go">2013-01-07  0.617509 -0.811230 -2.088563 -1.393500</span>
<span class="go">2013-01-08  0.947422 -0.671233 -0.847097 -1.187785</span>
<span class="go">2013-01-10  0.361428  0.887304  0.266457 -0.399641</span>
</pre>
</div>
</div>

<p>The <code>columns</code> keyword can be supplied to select a list of columns to be returned, this is equivalent to passing a <code>'columns=list_of_columns_to_filter'</code>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell232"><span></span><span class="gp">In [517]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="s2">"columns=['A', 'B']"</span><span class="p">)</span>
<span class="gh">Out[517]: </span>
<span class="go">                   A         B</span>
<span class="go">2000-01-01  0.858644 -0.851236</span>
<span class="go">2000-01-02 -0.080372 -1.268121</span>
<span class="go">2000-01-03  0.816983  1.965656</span>
<span class="go">2000-01-04  0.712795 -0.062433</span>
<span class="go">2000-01-05 -0.298721 -1.988045</span>
<span class="go">2000-01-06  1.103675  1.382242</span>
<span class="go">2000-01-07 -0.729161 -0.142928</span>
<span class="go">2000-01-08 -1.005977  0.465222</span>
</pre>
</div>
</div>

<p><code>start</code> and <code>stop</code> parameters can be specified to limit the total search space.
These are in terms of the total number of rows in a table.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p><code>select</code> will raise a <code>ValueError</code> if the query expression has an unknown
variable reference. Usually this means that you are trying to select on a column
that is <strong>not</strong> a data_column.</p>
<p><code>select</code> will raise a <code>SyntaxError</code> if the query expression is not valid.</p>
</div>

### <h4>Query timedelta64[ns]</h4>

<p>You can store and query using the <code>timedelta64[ns]</code> type. Terms can be specified in the format: <code>&lt;float&gt;(&lt;unit&gt;</code>, where float may be signed (and fractional), and unit can be <code>D,s,ms,us,ns</code> for the timedelta. Here’s an example:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell233"><span></span><span class="gp">In [518]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">datetime</span><span class="w"> </span><span class="kn">import</span> <span class="n">timedelta</span>

<span class="gp">In [519]: </span><span class="n">dftd</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"A"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Timestamp</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span>
<span class="gp"></span>            <span class="n">pd</span><span class="o">.</span><span class="n">Timestamp</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">)</span> <span class="o">+</span> <span class="n">timedelta</span><span class="p">(</span><span class="n">days</span><span class="o">=</span><span class="n">i</span><span class="p">,</span> <span class="n">seconds</span><span class="o">=</span><span class="mi">10</span><span class="p">)</span>
<span class="gp"></span>            <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">10</span><span class="p">)</span>
<span class="gp"></span>        <span class="p">],</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [520]: </span><span class="n">dftd</span><span class="p">[</span><span class="s2">"C"</span><span class="p">]</span> <span class="o">=</span> <span class="n">dftd</span><span class="p">[</span><span class="s2">"A"</span><span class="p">]</span> <span class="o">-</span> <span class="n">dftd</span><span class="p">[</span><span class="s2">"B"</span><span class="p">]</span>

<span class="gp">In [521]: </span><span class="n">dftd</span>
<span class="gh">Out[521]: </span>
<span class="go">           A                   B                  C</span>
<span class="go">0 2013-01-01 2013-01-01 00:00:10  -1 days +23:59:50</span>
<span class="go">1 2013-01-01 2013-01-02 00:00:10  -2 days +23:59:50</span>
<span class="go">2 2013-01-01 2013-01-03 00:00:10  -3 days +23:59:50</span>
<span class="go">3 2013-01-01 2013-01-04 00:00:10  -4 days +23:59:50</span>
<span class="go">4 2013-01-01 2013-01-05 00:00:10  -5 days +23:59:50</span>
<span class="go">5 2013-01-01 2013-01-06 00:00:10  -6 days +23:59:50</span>
<span class="go">6 2013-01-01 2013-01-07 00:00:10  -7 days +23:59:50</span>
<span class="go">7 2013-01-01 2013-01-08 00:00:10  -8 days +23:59:50</span>
<span class="go">8 2013-01-01 2013-01-09 00:00:10  -9 days +23:59:50</span>
<span class="go">9 2013-01-01 2013-01-10 00:00:10 -10 days +23:59:50</span>

<span class="gp">In [522]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dftd"</span><span class="p">,</span> <span class="n">dftd</span><span class="p">,</span> <span class="n">data_columns</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>

<span class="gp">In [523]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"dftd"</span><span class="p">,</span> <span class="s2">"C&lt;'-3.5D'"</span><span class="p">)</span>
<span class="gh">Out[523]: </span>
<span class="go">                              A                   B                  C</span>
<span class="go">4 1970-01-01 00:00:01.356998400 2013-01-05 00:00:10  -5 days +23:59:50</span>
<span class="go">5 1970-01-01 00:00:01.356998400 2013-01-06 00:00:10  -6 days +23:59:50</span>
<span class="go">6 1970-01-01 00:00:01.356998400 2013-01-07 00:00:10  -7 days +23:59:50</span>
<span class="go">7 1970-01-01 00:00:01.356998400 2013-01-08 00:00:10  -8 days +23:59:50</span>
<span class="go">8 1970-01-01 00:00:01.356998400 2013-01-09 00:00:10  -9 days +23:59:50</span>
<span class="go">9 1970-01-01 00:00:01.356998400 2013-01-10 00:00:10 -10 days +23:59:50</span>
</pre>
</div>
</div>

### <h4>Query MultiIndex</h4>

<p>Selecting from a <code>MultiIndex</span></code> can be achieved by using the name of the level.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell234"><span></span><span class="gp">In [524]: </span><span class="n">df_mi</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">names</span>
<span class="gh">Out[524]: </span><span class="go">FrozenList(['foo', 'bar'])</span>

<span class="gp">In [525]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_mi"</span><span class="p">,</span> <span class="s2">"foo=baz and bar=two"</span><span class="p">)</span>
<span class="gh">Out[525]: </span>
<span class="go">                A         B         C</span>
<span class="go">foo bar                              </span>
<span class="go">baz two -1.646063 -0.695847 -0.429156</span>
</pre>
</div>
</div>

<p>If the <code>MultiIndex</code> levels names are <code>None</code>, the levels are automatically made available via the <code>level_n</code> keyword with <code>n</code> the level of the <code>MultiIndex</code> you want to select from.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell235"><span></span><span class="gp">In [526]: </span><span class="n">index</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">levels</span><span class="o">=</span><span class="p">[[</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"baz"</span><span class="p">,</span> <span class="s2">"qux"</span><span class="p">],</span> <span class="p">[</span><span class="s2">"one"</span><span class="p">,</span> <span class="s2">"two"</span><span class="p">,</span> <span class="s2">"three"</span><span class="p">]],</span>
<span class="gp"></span>    <span class="n">codes</span><span class="o">=</span><span class="p">[[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">3</span><span class="p">],</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]],</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [527]: </span><span class="n">df_mi_2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="n">index</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">])</span>

<span class="gp">In [528]: </span><span class="n">df_mi_2</span>
<span class="gh">Out[528]: </span>
<span class="go">                  A         B         C</span>
<span class="go">foo one   -0.219582  1.186860 -1.437189</span>
<span class="go">    two    0.053768  1.872644 -1.469813</span>
<span class="go">    three -0.564201  0.876341  0.407749</span>
<span class="go">bar one   -0.232583  0.179812  0.922152</span>
<span class="go">    two   -1.820952 -0.641360  2.133239</span>
<span class="go">baz two   -0.941248 -0.136307 -1.271305</span>
<span class="go">    three -0.099774 -0.061438 -0.845172</span>
<span class="go">qux one    0.465793  0.756995 -0.541690</span>
<span class="go">    two   -0.802241  0.877657 -2.553831</span>
<span class="go">    three  0.094899 -2.319519  0.293601</span>

<span class="gp">In [529]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df_mi_2"</span><span class="p">,</span> <span class="n">df_mi_2</span><span class="p">)</span>

<span class="go"># the levels are automatically included as data columns with keyword level_n</span>
<span class="gp">In [530]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_mi_2"</span><span class="p">,</span> <span class="s2">"level_0=foo and level_1=two"</span><span class="p">)</span>
<span class="gh">Out[530]: </span>
<span class="go">                A         B         C</span>
<span class="go">foo two  0.053768  1.872644 -1.469813</span>
</pre>
</div>
</div>

### <h4>Indexing</h4>

<p>You can create/modify an index for a table with <code>create_table_index</code> after data is already in the table (after and <code>append/put</code> operation). Creating a table index is <strong>highly</strong> encouraged. This will speed your queries a great deal when you use a <code>select</code> with the indexed dimension as the <code>where</code>.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Indexes are automagically created on the indexables and any data columns you specify. This behavior can be turned off by passing <code>index=False</code> to <code>append</code>.</p>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell236"><span></span><span class="go"># we have automagically already created an index (in the first section)</span>
<span class="gp">In [531]: </span><span class="n">i</span> <span class="o">=</span> <span class="n">store</span><span class="o">.</span><span class="n">root</span><span class="o">.</span><span class="n">df</span><span class="o">.</span><span class="n">table</span><span class="o">.</span><span class="n">cols</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">index</span>

<span class="gp">In [532]: </span><span class="n">i</span><span class="o">.</span><span class="n">optlevel</span><span class="p">,</span> <span class="n">i</span><span class="o">.</span><span class="n">kind</span>
<span class="gh">Out[532]: </span><span class="go">(6, 'medium')</span>

<span class="go"># change an index by passing new parameters</span>
<span class="gp">In [533]: </span><span class="n">store</span><span class="o">.</span><span class="n">create_table_index</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">optlevel</span><span class="o">=</span><span class="mi">9</span><span class="p">,</span> <span class="n">kind</span><span class="o">=</span><span class="s2">"full"</span><span class="p">)</span>

<span class="gp">In [534]: </span><span class="n">i</span> <span class="o">=</span> <span class="n">store</span><span class="o">.</span><span class="n">root</span><span class="o">.</span><span class="n">df</span><span class="o">.</span><span class="n">table</span><span class="o">.</span><span class="n">cols</span><span class="o">.</span><span class="n">index</span><span class="o">.</span><span class="n">index</span>

<span class="gp">In [535]: </span><span class="n">i</span><span class="o">.</span><span class="n">optlevel</span><span class="p">,</span> <span class="n">i</span><span class="o">.</span><span class="n">kind</span>
<span class="gh">Out[535]: </span><span class="go">(9, 'full')</span>
</pre>
</div>
</div>

<p>Oftentimes when appending large amounts of data to a store, it is useful to turn off index creation for each append, then recreate at the end.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell237"><span></span><span class="gp">In [536]: </span><span class="n">df_1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="s2">"AB"</span><span class="p">))</span>

<span class="gp">In [537]: </span><span class="n">df_2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="s2">"AB"</span><span class="p">))</span>

<span class="gp">In [538]: </span><span class="n">st</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">HDFStore</span><span class="p">(</span><span class="s2">"appends.h5"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">)</span>

<span class="gp">In [539]: </span><span class="n">st</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">df_1</span><span class="p">,</span> <span class="n">data_columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"B"</span><span class="p">],</span> <span class="n">index</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>

<span class="gp">In [540]: </span><span class="n">st</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">df_2</span><span class="p">,</span> <span class="n">data_columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"B"</span><span class="p">],</span> <span class="n">index</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>

<span class="gp">In [541]: </span><span class="n">st</span><span class="o">.</span><span class="n">get_storer</span><span class="p">(</span><span class="s2">"df"</span><span class="p">)</span><span class="o">.</span><span class="n">table</span>
<span class="gh">Out[541]: </span>
<span class="go">/df/table (Table(20,)) ''</span>
<span class="go">  description := {</span>
<span class="go">  "index": Int64Col(shape=(), dflt=0, pos=0),</span>
<span class="go">  "values_block_0": Float64Col(shape=(1,), dflt=0.0, pos=1),</span>
<span class="go">  "B": Float64Col(shape=(), dflt=0.0, pos=2)}</span>
<span class="go">  byteorder := 'little'</span>
<span class="go">  chunkshape := (2730,)</span>
</pre>
</div>
</div>

<p>Then create the index when finished appending.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell238"><span></span><span class="gp">In [542]: </span><span class="n">st</span><span class="o">.</span><span class="n">create_table_index</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"B"</span><span class="p">],</span> <span class="n">optlevel</span><span class="o">=</span><span class="mi">9</span><span class="p">,</span> <span class="n">kind</span><span class="o">=</span><span class="s2">"full"</span><span class="p">)</span>

<span class="gp">In [543]: </span><span class="n">st</span><span class="o">.</span><span class="n">get_storer</span><span class="p">(</span><span class="s2">"df"</span><span class="p">)</span><span class="o">.</span><span class="n">table</span>
<span class="gh">Out[543]: </span>
<span class="go">/df/table (Table(20,)) ''</span>
<span class="go">  description := {</span>
<span class="go">  "index": Int64Col(shape=(), dflt=0, pos=0),</span>
<span class="go">  "values_block_0": Float64Col(shape=(1,), dflt=0.0, pos=1),</span>
<span class="go">  "B": Float64Col(shape=(), dflt=0.0, pos=2)}</span>
<span class="go">  byteorder := 'little'</span>
<span class="go">  chunkshape := (2730,)</span>
<span class="go">  autoindex := True</span>
<span class="go">  colindexes := {</span>
<span class="go">    "B": Index(9, fullshuffle, zlib(1)).is_csi=True}</span>

<span class="gp">In [544]: </span><span class="n">st</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>
</pre>
</div>
</div>

<p>See <a href="https://stackoverflow.com/questions/17893370/ptrepack-sortby-needs-full-index">here</a> for how to create a completely-sorted-index (CSI) on an existing store.</p>

### <h4>Query via data columns</h4>

<p>You can designate (and index) certain columns that you want to be able to perform queries (other than the <code>indexable</code> columns, which you can always query). For instance say you want to perform this common
operation, on-disk, and return just the frame that matches this query. You can specify <code>data_columns = True</code> to force all columns to be <code>data_columns</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell239"><span></span><span class="gp">In [545]: </span><span class="n">df_dc</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">copy</span><span class="p">()</span>

<span class="gp">In [546]: </span><span class="n">df_dc</span><span class="p">[</span><span class="s2">"string"</span><span class="p">]</span> <span class="o">=</span> <span class="s2">"foo"</span>

<span class="gp">In [547]: </span><span class="n">df_dc</span><span class="o">.</span><span class="n">loc</span><span class="p">[</span><span class="n">df_dc</span><span class="o">.</span><span class="n">index</span><span class="p">[</span><span class="mi">4</span><span class="p">:</span><span class="mi">6</span><span class="p">],</span> <span class="s2">"string"</span><span class="p">]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="gp">In [548]: </span><span class="n">df_dc</span><span class="o">.</span><span class="n">loc</span><span class="p">[</span><span class="n">df_dc</span><span class="o">.</span><span class="n">index</span><span class="p">[</span><span class="mi">7</span><span class="p">:</span><span class="mi">9</span><span class="p">],</span> <span class="s2">"string"</span><span class="p">]</span> <span class="o">=</span> <span class="s2">"bar"</span>

<span class="gp">In [549]: </span><span class="n">df_dc</span><span class="p">[</span><span class="s2">"string2"</span><span class="p">]</span> <span class="o">=</span> <span class="s2">"cool"</span>

<span class="gp">In [550]: </span><span class="n">df_dc</span><span class="o">.</span><span class="n">loc</span><span class="p">[</span><span class="n">df_dc</span><span class="o">.</span><span class="n">index</span><span class="p">[</span><span class="mi">1</span><span class="p">:</span><span class="mi">3</span><span class="p">],</span> <span class="p">[</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">]]</span> <span class="o">=</span> <span class="mf">1.0</span>

<span class="gp">In [551]: </span><span class="n">df_dc</span>
<span class="gh">Out[551]: </span>
<span class="go">                   A         B         C string string2</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006    foo    cool</span>
<span class="go">2000-01-02 -0.080372  1.000000  1.000000    foo    cool</span>
<span class="go">2000-01-03  0.816983  1.000000  1.000000    foo    cool</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755    foo    cool</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308    NaN    cool</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762    NaN    cool</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038    foo    cool</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517    bar    cool</span>

<span class="go"># on-disk operations</span>
<span class="gp">In [552]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df_dc"</span><span class="p">,</span> <span class="n">df_dc</span><span class="p">,</span> <span class="n">data_columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">,</span> <span class="s2">"string"</span><span class="p">,</span> <span class="s2">"string2"</span><span class="p">])</span>

<span class="gp">In [553]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_dc"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="s2">"B &gt; 0"</span><span class="p">)</span>
<span class="gh">Out[553]: </span>
<span class="go">                   A         B         C string string2</span>
<span class="go">2000-01-02 -0.080372  1.000000  1.000000    foo    cool</span>
<span class="go">2000-01-03  0.816983  1.000000  1.000000    foo    cool</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762    NaN    cool</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517    bar    cool</span>

<span class="go"># getting creative</span>
<span class="gp">In [554]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_dc"</span><span class="p">,</span> <span class="s2">"B &gt; 0 &amp; C &gt; 0 &amp; string == foo"</span><span class="p">)</span>
<span class="gh">Out[554]: </span>
<span class="go">                   A    B    C string string2</span>
<span class="go">2000-01-02 -0.080372  1.0  1.0    foo    cool</span>
<span class="go">2000-01-03  0.816983  1.0  1.0    foo    cool</span>

<span class="go"># this is in-memory version of this type of selection</span>
<span class="gp">In [555]: </span><span class="n">df_dc</span><span class="p">[(</span><span class="n">df_dc</span><span class="o">.</span><span class="n">B</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">)</span> <span class="o">&amp;</span> <span class="p">(</span><span class="n">df_dc</span><span class="o">.</span><span class="n">C</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">)</span> <span class="o">&amp;</span> <span class="p">(</span><span class="n">df_dc</span><span class="o">.</span><span class="n">string</span> <span class="o">==</span> <span class="s2">"foo"</span><span class="p">)]</span>
<span class="gh">Out[555]: </span>
<span class="go">                   A    B    C string string2</span>
<span class="go">2000-01-02 -0.080372  1.0  1.0    foo    cool</span>
<span class="go">2000-01-03  0.816983  1.0  1.0    foo    cool</span>

<span class="go"># we have automagically created this index and the B/C/string/string2</span>
<span class="go"># columns are stored separately as ``PyTables`` columns</span>
<span class="gp">In [556]: </span><span class="n">store</span><span class="o">.</span><span class="n">root</span><span class="o">.</span><span class="n">df_dc</span><span class="o">.</span><span class="n">table</span>
<span class="gh">Out[556]: </span>
<span class="go">/df_dc/table (Table(8,)) ''</span>
<span class="go">  description := {</span>
<span class="go">  "index": Int64Col(shape=(), dflt=0, pos=0),</span>
<span class="go">  "values_block_0": Float64Col(shape=(1,), dflt=0.0, pos=1),</span>
<span class="go">  "B": Float64Col(shape=(), dflt=0.0, pos=2),</span>
<span class="go">  "C": Float64Col(shape=(), dflt=0.0, pos=3),</span>
<span class="go">  "string": StringCol(itemsize=3, shape=(), dflt=b'', pos=4),</span>
<span class="go">  "string2": StringCol(itemsize=4, shape=(), dflt=b'', pos=5)}</span>
<span class="go">  byteorder := 'little'</span>
<span class="go">  chunkshape := (1680,)</span>
<span class="go">  autoindex := True</span>
<span class="go">  colindexes := {</span>
<span class="go">    "index": Index(6, mediumshuffle, zlib(1)).is_csi=False,</span>
<span class="go">    "B": Index(6, mediumshuffle, zlib(1)).is_csi=False,</span>
<span class="go">    "C": Index(6, mediumshuffle, zlib(1)).is_csi=False,</span>
<span class="go">    "string": Index(6, mediumshuffle, zlib(1)).is_csi=False,</span>
<span class="go">    "string2": Index(6, mediumshuffle, zlib(1)).is_csi=False}</span>
</pre>
</div>
</div>

<p>There is some performance degradation by making lots of columns into <code>data columns</code>, so it is up to the user to designate these. In addition, you cannot change data columns (nor indexables) after the first append/put operation (Of course you can simply read in the data and create a new table!).</p>

### <h4>Iterator</h4>

<p>You can pass <code>iterator=True</code> or <code>chunksize=number_in_a_chunk</code> to <code>select</code> and <code>select_as_multiple</code> to return an iterator on the results.
The default is 50,000 rows returned in a chunk.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell240"><span></span><span class="gp">In [557]: </span><span class="k">for</span> <span class="n">df</span> <span class="ow">in</span> <span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">chunksize</span><span class="o">=</span><span class="mi">3</span><span class="p">):</span>
<span class="gp"></span>    <span class="nb">print</span><span class="p">(</span><span class="n">df</span><span class="p">)</span>
<span class="gp"></span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-01  0.858644 -0.851236  1.058006</span>
<span class="go">2000-01-02 -0.080372 -1.268121  1.561967</span>
<span class="go">2000-01-03  0.816983  1.965656 -1.169408</span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-04  0.712795 -0.062433  0.736755</span>
<span class="go">2000-01-05 -0.298721 -1.988045  1.475308</span>
<span class="go">2000-01-06  1.103675  1.382242 -0.650762</span>
<span class="go">                   A         B         C</span>
<span class="go">2000-01-07 -0.729161 -0.142928 -1.063038</span>
<span class="go">2000-01-08 -1.005977  0.465222 -0.094517</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>You can also use the iterator with <code>read_hdf</code> which will open, then automatically close the store when finished iterating.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell241"><span></span><span class="k">for</span> <span class="n">df</span> <span class="ow">in</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"store.h5"</span><span class="p">,</span> <span class="s2">"df"</span><span class="p">,</span> <span class="n">chunksize</span><span class="o">=</span><span class="mi">3</span><span class="p">):</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">df</span><span class="p">)</span>
</pre>
</div>
</div>
</div>

<p>Note, that the chunksize keyword applies to the <strong>source</strong> rows. So if you are doing a query, then the chunksize will subdivide the total rows in the table and the query applied, returning an iterator on potentially unequal sized chunks.</p>

<p>Here is a recipe for generating a query and using it to create equal sized return chunks.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell242"><span></span><span class="gp">In [558]: </span><span class="n">dfeq</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"number"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">11</span><span class="p">)})</span>

<span class="gp">In [559]: </span><span class="n">dfeq</span>
<span class="gh">Out[559]: </span>
<span class="go">   number</span>
<span class="go">0       1</span>
<span class="go">1       2</span>
<span class="go">2       3</span>
<span class="go">3       4</span>
<span class="go">4       5</span>
<span class="go">5       6</span>
<span class="go">6       7</span>
<span class="go">7       8</span>
<span class="go">8       9</span>
<span class="go">9      10</span>

<span class="gp">In [560]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dfeq"</span><span class="p">,</span> <span class="n">dfeq</span><span class="p">,</span> <span class="n">data_columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"number"</span><span class="p">])</span>

<span class="gp">In [561]: </span><span class="k">def</span><span class="w"> </span><span class="nf">chunks</span><span class="p">(</span><span class="n">l</span><span class="p">,</span> <span class="n">n</span><span class="p">):</span>
<span class="gp"></span>    <span class="k">return</span> <span class="p">[</span><span class="n">l</span><span class="p">[</span><span class="n">i</span><span class="p">:</span> <span class="n">i</span> <span class="o">+</span> <span class="n">n</span><span class="p">]</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="nb">len</span><span class="p">(</span><span class="n">l</span><span class="p">),</span> <span class="n">n</span><span class="p">)]</span>
<span class="gp"></span>

<span class="gp">In [562]: </span><span class="n">evens</span> <span class="o">=</span> <span class="p">[</span><span class="mi">2</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">10</span><span class="p">]</span>

<span class="gp">In [563]: </span><span class="n">coordinates</span> <span class="o">=</span> <span class="n">store</span><span class="o">.</span><span class="n">select_as_coordinates</span><span class="p">(</span><span class="s2">"dfeq"</span><span class="p">,</span> <span class="s2">"number=evens"</span><span class="p">)</span>

<span class="gp">In [564]: </span><span class="k">for</span> <span class="n">c</span> <span class="ow">in</span> <span class="n">chunks</span><span class="p">(</span><span class="n">coordinates</span><span class="p">,</span> <span class="mi">2</span><span class="p">):</span>
<span class="gp"></span>    <span class="nb">print</span><span class="p">(</span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"dfeq"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="n">c</span><span class="p">))</span>
<span class="gp"></span>
<span class="go">   number</span>
<span class="go">1       2</span>
<span class="go">3       4</span>
<span class="go">   number</span>
<span class="go">5       6</span>
<span class="go">7       8</span>
<span class="go">   number</span>
<span class="go">9      10</span>
</pre>
</div>
</div>

### <h4>Advanced queries</h4>

<h5>Select a single column</h5>

<p>To retrieve a single indexable or data column, use the method <code>select_column</code>. This will, for example, enable you to get the index very quickly. These return a <code>Series</code> of the result, indexed by the row number. These do not currently accept the <code>where</code> selector.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell243"><span></span><span class="gp">In [565]: </span><span class="n">store</span><span class="o">.</span><span class="n">select_column</span><span class="p">(</span><span class="s2">"df_dc"</span><span class="p">,</span> <span class="s2">"index"</span><span class="p">)</span>
<span class="gh">Out[565]: </span>
<span class="go">0   2000-01-01</span>
<span class="go">1   2000-01-02</span>
<span class="go">2   2000-01-03</span>
<span class="go">3   2000-01-04</span>
<span class="go">4   2000-01-05</span>
<span class="go">5   2000-01-06</span>
<span class="go">6   2000-01-07</span>
<span class="go">7   2000-01-08</span>
<span class="go">Name: index, dtype: datetime64[ns]</span>

<span class="gp">In [566]: </span><span class="n">store</span><span class="o">.</span><span class="n">select_column</span><span class="p">(</span><span class="s2">"df_dc"</span><span class="p">,</span> <span class="s2">"string"</span><span class="p">)</span>
<span class="gh">Out[566]: </span>
<span class="go">0    foo</span>
<span class="go">1    foo</span>
<span class="go">2    foo</span>
<span class="go">3    foo</span>
<span class="go">4    NaN</span>
<span class="go">5    NaN</span>
<span class="go">6    foo</span>
<span class="go">7    bar</span>
<span class="go">Name: string, dtype: object</span>
</pre>
</div>
</div>

<h5>Selecting coordinates</h5>

<p>Sometimes you want to get the coordinates (a.k.a the index locations) of your query. This returns an
<code>Index</code> of the resulting locations. These coordinates can also be passed to subsequent
<code>where</code> operations.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell244"><span></span><span class="gp">In [567]: </span><span class="n">df_coord</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">1000</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20000101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">1000</span><span class="p">)</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [568]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df_coord"</span><span class="p">,</span> <span class="n">df_coord</span><span class="p">)</span>

<span class="gp">In [569]: </span><span class="n">c</span> <span class="o">=</span> <span class="n">store</span><span class="o">.</span><span class="n">select_as_coordinates</span><span class="p">(</span><span class="s2">"df_coord"</span><span class="p">,</span> <span class="s2">"index &gt; 20020101"</span><span class="p">)</span>

<span class="gp">In [570]: </span><span class="n">c</span>
<span class="gh">Out[570]: </span>
<span class="go">Index([732, 733, 734, 735, 736, 737, 738, 739, 740, 741,</span>
<span class="go">       ...</span>
<span class="go">       990, 991, 992, 993, 994, 995, 996, 997, 998, 999],</span>
<span class="go">      dtype='int64', length=268)</span>

<span class="gp">In [571]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_coord"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="n">c</span><span class="p">)</span>
<span class="gh">Out[571]: </span>
<span class="go">                   0         1</span>
<span class="go">2002-01-02  0.007717  1.168386</span>
<span class="go">2002-01-03  0.759328 -0.638934</span>
<span class="go">2002-01-04 -1.154018 -0.324071</span>
<span class="go">2002-01-05 -0.804551 -1.280593</span>
<span class="go">2002-01-06 -0.047208  1.260503</span>
<span class="go">...              ...       ...</span>
<span class="go">2002-09-22 -1.139583  0.344316</span>
<span class="go">2002-09-23 -0.760643 -1.306704</span>
<span class="go">2002-09-24  0.059018  1.775482</span>
<span class="go">2002-09-25  1.242255 -0.055457</span>
<span class="go">2002-09-26  0.410317  2.194489</span>

<span class="go">[268 rows x 2 columns]</span>
</pre>
</div>
</div>

<h5>Selecting using a where mask</h5>

<p>Sometime your query can involve creating a list of rows to select. Usually this <code>mask</code> would be a resulting <code>index</code> from an indexing operation. This example selects the months of a datetimeindex which are 5.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell245"><span></span><span class="gp">In [572]: </span><span class="n">df_mask</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">1000</span><span class="p">,</span> <span class="mi">2</span><span class="p">),</span> <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20000101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">1000</span><span class="p">)</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [573]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df_mask"</span><span class="p">,</span> <span class="n">df_mask</span><span class="p">)</span>

<span class="gp">In [574]: </span><span class="n">c</span> <span class="o">=</span> <span class="n">store</span><span class="o">.</span><span class="n">select_column</span><span class="p">(</span><span class="s2">"df_mask"</span><span class="p">,</span> <span class="s2">"index"</span><span class="p">)</span>

<span class="gp">In [575]: </span><span class="n">where</span> <span class="o">=</span> <span class="n">c</span><span class="p">[</span><span class="n">pd</span><span class="o">.</span><span class="n">DatetimeIndex</span><span class="p">(</span><span class="n">c</span><span class="p">)</span><span class="o">.</span><span class="n">month</span> <span class="o">==</span> <span class="mi">5</span><span class="p">]</span><span class="o">.</span><span class="n">index</span>

<span class="gp">In [576]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df_mask"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="n">where</span><span class="p">)</span>
<span class="gh">Out[576]: </span>
<span class="go">                   0         1</span>
<span class="go">2000-05-01  1.479511  0.516433</span>
<span class="go">2000-05-02 -0.334984 -1.493537</span>
<span class="go">2000-05-03  0.900321  0.049695</span>
<span class="go">2000-05-04  0.614266 -1.077151</span>
<span class="go">2000-05-05  0.233881  0.493246</span>
<span class="go">...              ...       ...</span>
<span class="go">2002-05-27  0.294122  0.457407</span>
<span class="go">2002-05-28 -1.102535  1.215650</span>
<span class="go">2002-05-29 -0.432911  0.753606</span>
<span class="go">2002-05-30 -1.105212  2.311877</span>
<span class="go">2002-05-31  2.567296  2.610691</span>

<span class="go">[93 rows x 2 columns]</span>
</pre>
</div>
</div>

<h5>Storer object</h5>

<p>If you want to inspect the stored object, retrieve via <code>get_storer</code>. You could use this programmatically to say get the number of rows in an object.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell246"><span></span><span class="gp">In [577]: </span><span class="n">store</span><span class="o">.</span><span class="n">get_storer</span><span class="p">(</span><span class="s2">"df_dc"</span><span class="p">)</span><span class="o">.</span><span class="n">nrows</span>
<span class="gh">Out[577]: </span><span class="go">8</span>
</pre>
</div>
</div>

### <h4>Multiple table queries</h4>

<p>The methods <code>append_to_multiple</code> and <code>select_as_multiple</code> can perform appending/selecting from multiple tables at once. The idea is to have one table (call it the selector table) that you index most/all of the columns, and perform your queries. The other table(s) are data tables with an index matching the selector table’s index. You can then perform a very fast query on the selector table, yet get lots of data back. This method is similar to having a very wide table, but enables more efficient queries.</p>

<p>The <code>append_to_multiple</code> method splits a given single DataFrame into multiple tables according to <code>d</code>, a dictionary that maps the table names to a list of ‘columns’ you want in that table.
If <code>None</code> is used in place of a list, that table will have the remaining unspecified columns of the given DataFrame. The argument <code>selector</code> defines which table is the selector table (which you can make queries from).
The argument <code>dropna</code> will drop rows from the input <code>DataFrame</code> to ensure tables are synchronized. This means that if a row for one of the tables being written to is entirely <code>np.nan</code>, that row will be dropped from all tables.</p>

<p>If <code>dropna</code> is False, <strong>THE USER IS RESPONSIBLE FOR SYNCHRONIZING THE TABLES</strong>.
Remember that entirely <code>np.Nan</code> rows are not written to the HDFStore, so if you choose to call <code>dropna=False</code>, some tables may have more rows than others, and therefore <code>select_as_multiple</code> may not work or it may return unexpected results.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell247"><span></span><span class="gp">In [578]: </span><span class="n">df_mt</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">,</span> <span class="mi">6</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"1/1/2000"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">8</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">,</span> <span class="s2">"C"</span><span class="p">,</span> <span class="s2">"D"</span><span class="p">,</span> <span class="s2">"E"</span><span class="p">,</span> <span class="s2">"F"</span><span class="p">],</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [579]: </span><span class="n">df_mt</span><span class="p">[</span><span class="s2">"foo"</span><span class="p">]</span> <span class="o">=</span> <span class="s2">"bar"</span>

<span class="gp">In [580]: </span><span class="n">df_mt</span><span class="o">.</span><span class="n">loc</span><span class="p">[</span><span class="n">df_mt</span><span class="o">.</span><span class="n">index</span><span class="p">[</span><span class="mi">1</span><span class="p">],</span> <span class="p">(</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">)]</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span>

<span class="go"># you can also create the tables individually</span>
<span class="gp">In [581]: </span><span class="n">store</span><span class="o">.</span><span class="n">append_to_multiple</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span><span class="s2">"df1_mt"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"A"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">],</span> <span class="s2">"df2_mt"</span><span class="p">:</span> <span class="kc">None</span><span class="p">},</span> <span class="n">df_mt</span><span class="p">,</span> <span class="n">selector</span><span class="o">=</span><span class="s2">"df1_mt"</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [582]: </span><span class="n">store</span>
<span class="gh">Out[582]: </span>
<span class="go">&lt;class 'pandas.io.pytables.HDFStore'&gt;</span>
<span class="go">File path: store.h5</span>

<span class="go"># individual tables were created</span>
<span class="gp">In [583]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df1_mt"</span><span class="p">)</span>
<span class="gh">Out[583]: </span>
<span class="go">                   A         B</span>
<span class="go">2000-01-01  0.162291 -0.430489</span>
<span class="go">2000-01-02       NaN       NaN</span>
<span class="go">2000-01-03  0.429207 -1.099274</span>
<span class="go">2000-01-04  1.869081 -1.466039</span>
<span class="go">2000-01-05  0.092130 -1.726280</span>
<span class="go">2000-01-06  0.266901 -0.036854</span>
<span class="go">2000-01-07 -0.517871 -0.990317</span>
<span class="go">2000-01-08 -0.231342  0.557402</span>

<span class="gp">In [584]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"df2_mt"</span><span class="p">)</span>
<span class="gh">Out[584]: </span>
<span class="go">                   C         D         E         F  foo</span>
<span class="go">2000-01-01 -2.502042  0.668149  0.460708  1.834518  bar</span>
<span class="go">2000-01-02  0.130441 -0.608465  0.439872  0.506364  bar</span>
<span class="go">2000-01-03 -1.069546  1.236277  0.116634 -1.772519  bar</span>
<span class="go">2000-01-04  0.137462  0.313939  0.748471 -0.943009  bar</span>
<span class="go">2000-01-05  0.836517  2.049798  0.562167  0.189952  bar</span>
<span class="go">2000-01-06  1.112750 -0.151596  1.503311  0.939470  bar</span>
<span class="go">2000-01-07 -0.294348  0.335844 -0.794159  1.495614  bar</span>
<span class="go">2000-01-08  0.860312 -0.538674 -0.541986 -1.759606  bar</span>

<span class="go"># as a multiple</span>
<span class="gp">In [585]: </span><span class="n">store</span><span class="o">.</span><span class="n">select_as_multiple</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">[</span><span class="s2">"df1_mt"</span><span class="p">,</span> <span class="s2">"df2_mt"</span><span class="p">],</span>
<span class="gp"></span>    <span class="n">where</span><span class="o">=</span><span class="p">[</span><span class="s2">"A&gt;0"</span><span class="p">,</span> <span class="s2">"B&gt;0"</span><span class="p">],</span>
<span class="gp"></span>    <span class="n">selector</span><span class="o">=</span><span class="s2">"df1_mt"</span><span class="p">,</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>
<span class="gh">Out[585]: </span>
<span class="go">Empty DataFrame</span>
<span class="go">Columns: [A, B, C, D, E, F, foo]</span>
<span class="go">Index: []</span>
</pre>
</div>
</div>

## <h3>Delete from a table</h3>

<p>You can delete from a table selectively by specifying a <code>where</code>. In deleting rows, it is important to understand the <code>PyTables</code> deletes rows by erasing the rows, then <strong>moving</strong> the following data. Thus deleting can potentially be a very expensive operation depending on the orientation of your data. To get optimal performance, it’s worthwhile to have the dimension you are deleting be the first of the <code>indexables</code>.</p>

<p>Data is ordered (on the disk) in terms of the <code>indexables</code>. Here’s a simple use case. You store panel-type data, with dates in the <code>major_axis</code> and ids in the <code>minor_axis</code>. The data is then
interleaved like this:</p>

<ul class="simple">
<li><dl class="simple">
<dt>date_1</dt><dd><ul>
<li><p>id_1</p></li>
<li><p>id_2</p></li>
<li><p>.</p></li>
<li><p>id_n</p></li>
</ul>
</dd>
</dl>
</li>
<li><dl class="simple">
<dt>date_2</dt><dd><ul>
<li><p>id_1</p></li>
<li><p>.</p></li>
<li><p>id_n</p></li>
</ul>
</dd>
</dl>
</li>
</ul>

<p>It should be clear that a delete operation on the <code>major_axis</code> will be fairly quick, as one chunk is removed, then the following data moved. On the other hand a delete operation on the <code>minor_axis</code> will be very expensive. In this case it would almost certainly be faster to rewrite the table using a <code>where</code> that selects all but the missing data.</p>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Please note that HDF5 <strong>DOES NOT RECLAIM SPACE</strong> in the h5 files automatically. Thus, repeatedly deleting (or removing nodes) and adding again, <strong>WILL TEND TO INCREASE THE FILE SIZE</strong>.</p>
<p>To <em>repack and clean</em> the file, use <a href="#io-hdf5-ptrepack">ptrepack</a>.</p>
</div>

## <h3>Notes &amp; caveats</h3>

### <h4>Compression</h4>

<p><code>PyTables</code> allows the stored data to be compressed. This applies to all kinds of stores, not just tables. Two parameters are used to control compression: <code>complevel</code> and <code>complib</code>.</p>

<ul>
<li><p><code>complevel</code> specifies if and how hard data is to be compressed.
<code>complevel=0</code> and <code>complevel=None</code> disables compression and
<code>0&lt;complevel&lt;10</code> enables compression.</p></li>
<li><p><code>complib</code> specifies which compression library to use.
If nothing is  specified the default library <code>zlib</code> is used. A compression library usually optimizes for either good compression rates or speed and the results will depend on the type of data. Which type of compression to choose depends on your specific needs and data. The list of supported compression libraries:</p>
<ul>
<li><p><a href="https://zlib.net/">zlib</a>: The default compression library.
A classic in terms of compression, achieves good compression rates but is somewhat slow.</p></li>
<li><p><a href="https://www.oberhumer.com/opensource/lzo/">lzo</a>: Fast compression and decompression.</p></li>
<li><p><a href="https://sourceware.org/bzip2/">bzip2</a>: Good compression rates.</p></li>
<li><p><a href="https://www.blosc.org/">blosc</a>: Fast compression and decompression.</p>
<p>Support for alternative blosc compressors:</p>
<ul class="simple">
<li><p><a href="https://www.blosc.org/">blosc:blosclz</a> This is the
default compressor for <code>blosc</code></p></li>
<li><p><a href="https://fastcompression.blogspot.com/p/lz4.html">blosc:lz4</a>:
A compact, very popular and fast compressor.</p></li>
<li><p><a href="https://fastcompression.blogspot.com/p/lz4.html">blosc:lz4hc</a>:
A tweaked version of LZ4, produces better compression ratios at the expense of speed.</p></li>
<li><p><a href="https://google.github.io/snappy/">blosc:snappy</a>:
A popular compressor used in many places.</p></li>
<li><p><a href="https://zlib.net/">blosc:zlib</a>: A classic; somewhat slower than the previous ones, but achieving better compression ratios.</p></li>
<li><p><a href="https://facebook.github.io/zstd/">blosc:zstd</a>: An extremely well balanced codec; it provides the best compression ratios among the others above, and at reasonably fast speed.</p></li>
</ul>
</li>
</ul>
<p>If <code>complib</code> is defined as something other than the listed libraries a <code>ValueError</code> exception is issued.</p>
</li>
</ul>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If the library specified with the <code>complib</code> option is missing on your platform, compression defaults to <code>zlib</code> without further ado.</p>
</div>

<p>Enable compression for all objects within the file:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell248"><span></span><span class="n">store_compressed</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">HDFStore</span><span class="p">(</span>
    <span class="s2">"store_compressed.h5"</span><span class="p">,</span> <span class="n">complevel</span><span class="o">=</span><span class="mi">9</span><span class="p">,</span> <span class="n">complib</span><span class="o">=</span><span class="s2">"blosc:blosclz"</span>
<span class="p">)</span>
</pre>
</div>
</div>

<p>Or on-the-fly compression (this only applies to tables) in stores where compression is not enabled:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell249"><span></span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"df"</span><span class="p">,</span> <span class="n">df</span><span class="p">,</span> <span class="n">complib</span><span class="o">=</span><span class="s2">"zlib"</span><span class="p">,</span> <span class="n">complevel</span><span class="o">=</span><span class="mi">5</span><span class="p">)</span>
</pre>
</div>
</div>

### <h4>ptrepack</h4>

<p><code>PyTables</code> offers better write performance when tables are compressed after they are written, as opposed to turning on compression at the very beginning. You can use the supplied <code>PyTables</code> utility <code>ptrepack</code>. In addition, <code>ptrepack</code> can change compression levels after the fact.</p>

<div class="highlight-console notranslate"><div class="highlight"><pre id="codecell250"><span></span><span class="go">ptrepack --chunkshape=auto --propindexes --complevel=9 --complib=blosc in.h5 out.h5</span>
</pre>
</div>
</div>

<p>Furthermore <code>ptrepack in.h5 out.h5</code> will <em>repack</em> the file to allow you to reuse previously deleted space. Alternatively, one can simply remove the file and write again, or use the <code>copy</code> method.</p>

### <h4>Caveats</h4>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p><code>HDFStore</code> is <strong>not-threadsafe for writing</strong>. The underlying <code>PyTables</code> only supports concurrent reads (via threading or processes). If you need reading and writing <em>at the same time</em>, you need to serialize these operations in a single thread in a single process. You will corrupt your data otherwise. See the (<a class="extlink-issue reference external" href="https://github.com/pandas-dev/pandas/issues/2397">GH 2397</a>) for more information.</p>
</div>

<ul class="simple">
<li><p>If you use locks to manage write access between multiple processes, you may want to use
<a href="https://docs.python.org/3/library/os.html#os.fsync" title="(in Python v3.13)"><code>fsync()</code></a> before releasing write locks. For convenience you can use <code>store.flush(fsync=True)</code> to do this for you.</p></li>
<li><p>Once a <code>table</code> is created columns (DataFrame) are fixed; only exactly the same columns can be appended</p></li>
<li><p>Be aware that timezones (e.g., <code>pytz.timezone('US/Eastern')</code>) are not necessarily equal across timezone versions. So if data is localized to a specific timezone in the HDFStore using one version of a timezone library and that data is updated with another version, the data will be converted to UTC since these timezones are not considered equal. Either use the same version of timezone library or use <code>tz_convert</code> with the updated timezone definition.</p></li>
</ul>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p><code>PyTables</code> will show a <code>NaturalNameWarning</code> if a column name cannot be used as an attribute selector.
<em>Natural</em> identifiers contain only letters, numbers, and underscores, and may not begin with a number.
Other identifiers cannot be used in a <code>where</code> clause and are generally a bad idea.</p>
</div>

## <h3>DataTypes</h3>

<p><code>HDFStore</code> will map an object dtype to the <code>PyTables</code> underlying dtype.
This means the following types are known to work:</p>
<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>Type</p></th>
<th class="head"><p>Represents missing values</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>floating : <code>float64, float32, float16</code></p></td>
<td><p><code>np.nan</code></p></td>
</tr>
<tr class="row-odd"><td><p>integer : <code>int64, int32, int8, uint64,uint32, uint8</code></p></td>
<td></td>
</tr>
<tr class="row-even"><td><p>boolean</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p><code>datetime64[ns]</code></p></td>
<td><p><code>NaT</code></p></td>
</tr>
<tr class="row-even"><td><p><code>timedelta64[ns]</code></p></td>
<td><p><code>NaT</code></p></td>
</tr>
<tr class="row-odd"><td><p>categorical : see the section below</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p>object : <code>strings</code></p></td>
<td><p><code>np.nan</code></p></td>
</tr>
</tbody>
</table>
<p><code>unicode</code> columns are not supported, and <strong>WILL FAIL</strong>.</p>

### <h4>Categorical data</h4>

<p>You can write data that contains <code>category</code> dtypes to a <code>HDFStore</code>.
Queries work the same as if it was an object array. However, the <code>category</code> dtyped data is stored in a more efficient manner.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell251"><span></span><span class="gp">In [586]: </span><span class="n">dfcat</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span><span class="s2">"A"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Series</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="s2">"aabbcdba"</span><span class="p">))</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"category"</span><span class="p">),</span> <span class="s2">"B"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">8</span><span class="p">)}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [587]: </span><span class="n">dfcat</span>
<span class="gh">Out[587]: </span>
<span class="go">   A         B</span>
<span class="go">0  a -1.520478</span>
<span class="go">1  a -1.069391</span>
<span class="go">2  b -0.551981</span>
<span class="go">3  b  0.452407</span>
<span class="go">4  c  0.409257</span>
<span class="go">5  d  0.301911</span>
<span class="go">6  b -0.640843</span>
<span class="go">7  a -2.253022</span>

<span class="gp">In [588]: </span><span class="n">dfcat</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[588]: </span>
<span class="go">A    category</span>
<span class="go">B     float64</span>
<span class="go">dtype: object</span>

<span class="gp">In [589]: </span><span class="n">cstore</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">HDFStore</span><span class="p">(</span><span class="s2">"cats.h5"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">)</span>

<span class="gp">In [590]: </span><span class="n">cstore</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dfcat"</span><span class="p">,</span> <span class="n">dfcat</span><span class="p">,</span> <span class="nb">format</span><span class="o">=</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">data_columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"A"</span><span class="p">])</span>

<span class="gp">In [591]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">cstore</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"dfcat"</span><span class="p">,</span> <span class="n">where</span><span class="o">=</span><span class="s2">"A in ['b', 'c']"</span><span class="p">)</span>

<span class="gp">In [592]: </span><span class="n">result</span>
<span class="gh">Out[592]: </span>
<span class="go">   A         B</span>
<span class="go">2  b -0.551981</span>
<span class="go">3  b  0.452407</span>
<span class="go">4  c  0.409257</span>
<span class="go">6  b -0.640843</span>

<span class="gp">In [593]: </span><span class="n">result</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[593]: </span>
<span class="go">A    category</span>
<span class="go">B     float64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

### <h4>String columns</h4>

<p><strong>min_itemsize</strong></p>

<p>The underlying implementation of <code>HDFStore</code> uses a fixed column width (itemsize) for string columns.
A string column itemsize is calculated as the maximum of the length of data (for that column) that is passed to the <code>HDFStore</code>, <strong>in the first append</strong>. Subsequent appends, may introduce a string for a column <strong>larger</strong> than the column can hold, an Exception will be raised (otherwise you could have a silent truncation of these columns, leading to loss of information). In the future we may relax this and allow a user-specified truncation to occur.</p>

<p>Pass <code>min_itemsize</code> on the first table creation to a-priori specify the minimum length of a particular string column.
<code>min_itemsize</code> can be an integer, or a dict mapping a column name to an integer. You can pass <code>values</code> as a key to
allow all <em>indexables</em> or <em>data_columns</em> to have this min_itemsize.</p>

<p>Passing a <code>min_itemsize</code> dict will cause all passed columns to be created as <em>data_columns</em> automatically.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If you are not passing any <code>data_columns</code>, then the <code>min_itemsize</code> will be the maximum of the length of any string passed</p>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell252"><span></span><span class="gp">In [594]: </span><span class="n">dfs</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"B"</span><span class="p">:</span> <span class="s2">"bar"</span><span class="p">},</span> <span class="n">index</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">5</span><span class="p">)))</span>

<span class="gp">In [595]: </span><span class="n">dfs</span>
<span class="gh">Out[595]: </span>
<span class="go">     A    B</span>
<span class="go">0  foo  bar</span>
<span class="go">1  foo  bar</span>
<span class="go">2  foo  bar</span>
<span class="go">3  foo  bar</span>
<span class="go">4  foo  bar</span>

<span class="go"># A and B have a size of 30</span>
<span class="gp">In [596]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dfs"</span><span class="p">,</span> <span class="n">dfs</span><span class="p">,</span> <span class="n">min_itemsize</span><span class="o">=</span><span class="mi">30</span><span class="p">)</span>

<span class="gp">In [597]: </span><span class="n">store</span><span class="o">.</span><span class="n">get_storer</span><span class="p">(</span><span class="s2">"dfs"</span><span class="p">)</span><span class="o">.</span><span class="n">table</span>
<span class="gh">Out[597]: </span>
<span class="go">/dfs/table (Table(5,)) ''</span>
<span class="go">  description := {</span>
<span class="go">  "index": Int64Col(shape=(), dflt=0, pos=0),</span>
<span class="go">  "values_block_0": StringCol(itemsize=30, shape=(2,), dflt=b'', pos=1)}</span>
<span class="go">  byteorder := 'little'</span>
<span class="go">  chunkshape := (963,)</span>
<span class="go">  autoindex := True</span>
<span class="go">  colindexes := {</span>
<span class="go">    "index": Index(6, mediumshuffle, zlib(1)).is_csi=False}</span>

<span class="go"># A is created as a data_column with a size of 30</span>
<span class="go"># B is size is calculated</span>
<span class="gp">In [598]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dfs2"</span><span class="p">,</span> <span class="n">dfs</span><span class="p">,</span> <span class="n">min_itemsize</span><span class="o">=</span><span class="p">{</span><span class="s2">"A"</span><span class="p">:</span> <span class="mi">30</span><span class="p">})</span>

<span class="gp">In [599]: </span><span class="n">store</span><span class="o">.</span><span class="n">get_storer</span><span class="p">(</span><span class="s2">"dfs2"</span><span class="p">)</span><span class="o">.</span><span class="n">table</span>
<span class="gh">Out[599]: </span>
<span class="go">/dfs2/table (Table(5,)) ''</span>
<span class="go">  description := {</span>
<span class="go">  "index": Int64Col(shape=(), dflt=0, pos=0),</span>
<span class="go">  "values_block_0": StringCol(itemsize=3, shape=(1,), dflt=b'', pos=1),</span>
<span class="go">  "A": StringCol(itemsize=30, shape=(), dflt=b'', pos=2)}</span>
<span class="go">  byteorder := 'little'</span>
<span class="go">  chunkshape := (1598,)</span>
<span class="go">  autoindex := True</span>
<span class="go">  colindexes := {</span>
<span class="go">    "index": Index(6, mediumshuffle, zlib(1)).is_csi=False,</span>
<span class="go">    "A": Index(6, mediumshuffle, zlib(1)).is_csi=False}</span>
</pre>
</div>
</div>

<p><strong>nan_rep</strong></p>

<p>String columns will serialize a <code>np.nan</code> (a missing value) with the <code>nan_rep</code> string representation. This defaults to the string value <code>nan</code>.
You could inadvertently turn an actual <code>nan</span></code> value into a missing value.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell253"><span></span><span class="gp">In [600]: </span><span class="n">dfss</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span><span class="p">,</span> <span class="s2">"nan"</span><span class="p">]})</span>

<span class="gp">In [601]: </span><span class="n">dfss</span>
<span class="gh">Out[601]: </span>
<span class="go">     A</span>
<span class="go">0  foo</span>
<span class="go">1  bar</span>
<span class="go">2  nan</span>

<span class="gp">In [602]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dfss"</span><span class="p">,</span> <span class="n">dfss</span><span class="p">)</span>

<span class="gp">In [603]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"dfss"</span><span class="p">)</span>
<span class="gh">Out[603]: </span>
<span class="go">     A</span>
<span class="go">0  foo</span>
<span class="go">1  bar</span>
<span class="go">2  NaN</span>

<span class="go"># here you need to specify a different nan rep</span>
<span class="gp">In [604]: </span><span class="n">store</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">"dfss2"</span><span class="p">,</span> <span class="n">dfss</span><span class="p">,</span> <span class="n">nan_rep</span><span class="o">=</span><span class="s2">"_nan_"</span><span class="p">)</span>

<span class="gp">In [605]: </span><span class="n">store</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="s2">"dfss2"</span><span class="p">)</span>
<span class="gh">Out[605]: </span>
<span class="go">     A</span>
<span class="go">0  foo</span>
<span class="go">1  bar</span>
<span class="go">2  nan</span>
</pre>
</div>
</div>

## <h3>Performance</h3>

<ul class="simple">
<li><p><code>tables</code> format come with a writing performance penalty as compared to <code>fixed</code> stores. The benefit is the ability to append/delete and query (potentially very large amounts of data). Write times are generally longer as compared with regular stores. Query times can be quite fast, especially on an indexed axis.</p></li>
<li><p>You can pass <code>chunksize=&lt;int&gt;</code> to <code>append</code>, specifying the write chunksize (default is 50000).
This will significantly lower your memory usage on writing.</p></li>
<li><p>You can pass <code>expectedrows=&lt;int&gt;</code> to the first <code>append</code>, to set the TOTAL number of rows that <code>PyTables</code> will expect. This will optimize read/write performance.</p></li>
<li><p>Duplicate rows can be written to tables, but are filtered out in selection (with the last items being selected; thus a table is unique on major, minor pairs)</p></li>
<li><p>A <code>PerformanceWarning</code> will be raised if you are attempting to store types that will be pickled by PyTables (rather than stored as endemic types).
See <a href="https://stackoverflow.com/questions/14355151/how-to-make-pandas-hdfstore-put-operation-faster/14370190#14370190">Here</a> for more information and some solutions.</p></li>
</ul>

# <h2>Feather</h2>

<p>Feather provides binary columnar serialization for data frames. It is designed to make reading and writing data frames efficient, and to make sharing data across data analysis languages easy.</p>

<p>Feather is designed to faithfully serialize and de-serialize DataFrames, supporting all of the pandas dtypes, including extension dtypes such as categorical and datetime with tz.</p>

<p>Several caveats:</p>
                                                  
<ul class="simple">
<li><p>The format will NOT write an <code>Index</code>, or <code>MultiIndex</code> for the <code>DataFrame</code> and will raise an error if a non-default one is provided. You can <code>.reset_index()</code> to store the index or <code>.reset_index(drop=True)</code> to ignore it.</p></li>
<li><p>Duplicate column names and non-string columns names are not supported</p></li>
<li><p>Actual Python objects in object dtype columns are not supported. These will raise a helpful error message on an attempt at serialization.</p></li>
</ul>

<p>See the <a href="https://github.com/wesm/feather">Full Documentation</a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell254"><span></span><span class="gp">In [606]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"a"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"b"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">4</span><span class="p">)),</span>
<span class="gp"></span>        <span class="s2">"c"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"u1"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"d"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mf">4.0</span><span class="p">,</span> <span class="mf">7.0</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float64"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"e"</span><span class="p">:</span> <span class="p">[</span><span class="kc">True</span><span class="p">,</span> <span class="kc">False</span><span class="p">,</span> <span class="kc">True</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"f"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Categorical</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">)),</span>
<span class="gp"></span>        <span class="s2">"g"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"h"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">,</span> <span class="n">tz</span><span class="o">=</span><span class="s2">"US/Eastern"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"i"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">,</span> <span class="n">freq</span><span class="o">=</span><span class="s2">"ns"</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [607]: </span><span class="n">df</span>
<span class="gh">Out[607]: </span>
<span class="go">   a  b  c  ...          g                         h                             i</span>
<span class="go">0  a  1  3  ... 2013-01-01 2013-01-01 00:00:00-05:00 2013-01-01 00:00:00.000000000</span>
<span class="go">1  b  2  4  ... 2013-01-02 2013-01-02 00:00:00-05:00 2013-01-01 00:00:00.000000001</span>
<span class="go">2  c  3  5  ... 2013-01-03 2013-01-03 00:00:00-05:00 2013-01-01 00:00:00.000000002</span>

<span class="go">[3 rows x 9 columns]</span>

<span class="gp">In [608]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[608]: </span>
<span class="go">a                        object</span>
<span class="go">b                         int64</span>
<span class="go">c                         uint8</span>
<span class="go">d                       float64</span>
<span class="go">e                          bool</span>
<span class="go">f                      category</span>
<span class="go">g                datetime64[ns]</span>
<span class="go">h    datetime64[ns, US/Eastern]</span>
<span class="go">i                datetime64[ns]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Write to a feather file.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell255"><span></span><span class="gp">In [609]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_feather</span><span class="p">(</span><span class="s2">"example.feather"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Read from a feather file.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell256"><span></span><span class="gp">In [610]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_feather</span><span class="p">(</span><span class="s2">"example.feather"</span><span class="p">)</span>

<span class="gp">In [611]: </span><span class="n">result</span>
<span class="gh">Out[611]: </span>
<span class="go">   a  b  c  ...          g                         h                             i</span>
<span class="go">0  a  1  3  ... 2013-01-01 2013-01-01 00:00:00-05:00 2013-01-01 00:00:00.000000000</span>
<span class="go">1  b  2  4  ... 2013-01-02 2013-01-02 00:00:00-05:00 2013-01-01 00:00:00.000000001</span>
<span class="go">2  c  3  5  ... 2013-01-03 2013-01-03 00:00:00-05:00 2013-01-01 00:00:00.000000002</span>

<span class="go">[3 rows x 9 columns]</span>

<span class="go"># we preserve dtypes</span>
<span class="gp">In [612]: </span><span class="n">result</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[612]: </span>
<span class="go">a                        object</span>
<span class="go">b                         int64</span>
<span class="go">c                         uint8</span>
<span class="go">d                       float64</span>
<span class="go">e                          bool</span>
<span class="go">f                      category</span>
<span class="go">g                datetime64[ns]</span>
<span class="go">h    datetime64[ns, US/Eastern]</span>
<span class="go">i                datetime64[ns]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

# <h2>Parquet</h2>

<p><a href="https://parquet.apache.org/">Apache Parquet</a> provides a partitioned binary columnar serialization for data frames.
It is designed to make reading and writing data frames efficient, and to make sharing data across data analysis languages easy.
Parquet can use a variety of compression techniques to shrink the file size as much as possible while still maintaining good read performance.</p>

<p>Parquet is designed to faithfully serialize and de-serialize <code>DataFrame</code> s, supporting all of the pandas dtypes, including extension dtypes such as datetime with tz.</p>

<p>Several caveats.</p>

<ul class="simple">
<li><p>Duplicate column names and non-string columns names are not supported.</p></li>
<li><p>The <code>pyarrow</code> engine always writes the index to the output, but <code>fastparquet</code> only writes non-default indexes.
This extra column can cause problems for non-pandas consumers that are not expecting it. You can force including or omitting indexes with the <code>index</code> argument, regardless of the underlying engine.</p></li>
<li><p>Index level names, if specified, must be strings.</p></li>
<li><p>In the <code>pyarrow</code> engine, categorical dtypes for non-string types can be serialized to parquet, but will de-serialize as their primitive dtype.</p></li>
<li><p>The <code>pyarrow</code> engine preserves the <code>ordered</code> flag of categorical dtypes with string types. <code>fastparquet</code> does not preserve the <code>ordered</code> flag.</p></li>
<li><p>Non supported types include <code>Interval</code> and actual Python object types. These will raise a helpful error message
on an attempt at serialization. <code>Period</code> type is supported with pyarrow &gt;= 0.16.0.</p></li>
<li><p>The <code>pyarrow</code> engine preserves extension data types such as the nullable integer and string data
type (requiring pyarrow &gt;= 0.16.0, and requiring the extension type to implement the needed protocols,
see the <a href="https://pandas.pydata.org/docs/development/extending.html#extending-extension-arrow">extension types documentation</a>).</p></li>
</ul>
<p>You can specify an <code>engine</code> to direct the serialization. This can be one of <code>pyarrow</code>, or <code>fastparquet</code>, or <code>auto</code>.
If the engine is NOT specified, then the <code>pd.options.io.parquet.engine</code> option is checked; if this is also <code>auto</code>,
then <code>pyarrow</code> is tried, and falling back to <code>fastparquet</code>.</p>
<p>See the documentation for <a href="https://arrow.apache.org/docs/python/">pyarrow</a> and
<a href="https://fastparquet.readthedocs.io/en/latest/">fastparquet</a>.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>These engines are very similar and should read/write nearly identical parquet format files. <code>pyarrow&gt;=8.0.0</code> supports timedelta data, <code>fastparquet&gt;=0.1.4</code> supports timezone aware datetimes. These libraries differ by having different underlying dependencies (<code>fastparquet</code> by using <code>numba</code>, while <code>pyarrow</code> uses a c-library).</p>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell257"><span></span><span class="gp">In [613]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"a"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"b"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">4</span><span class="p">)),</span>
<span class="gp"></span>        <span class="s2">"c"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">6</span><span class="p">)</span><span class="o">.</span><span class="n">astype</span><span class="p">(</span><span class="s2">"u1"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"d"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mf">4.0</span><span class="p">,</span> <span class="mf">7.0</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float64"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"e"</span><span class="p">:</span> <span class="p">[</span><span class="kc">True</span><span class="p">,</span> <span class="kc">False</span><span class="p">,</span> <span class="kc">True</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"f"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"g"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">,</span> <span class="n">tz</span><span class="o">=</span><span class="s2">"US/Eastern"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"h"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Categorical</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">)),</span>
<span class="gp"></span>        <span class="s2">"i"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">Categorical</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span> <span class="n">ordered</span><span class="o">=</span><span class="kc">True</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [614]: </span><span class="n">df</span>
<span class="gh">Out[614]: </span>
<span class="go">   a  b  c    d      e          f                         g  h  i</span>
<span class="go">0  a  1  3  4.0   True 2013-01-01 2013-01-01 00:00:00-05:00  a  a</span>
<span class="go">1  b  2  4  5.0  False 2013-01-02 2013-01-02 00:00:00-05:00  b  b</span>
<span class="go">2  c  3  5  6.0   True 2013-01-03 2013-01-03 00:00:00-05:00  c  c</span>

<span class="gp">In [615]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[615]: </span>
<span class="go">a                        object</span>
<span class="go">b                         int64</span>
<span class="go">c                         uint8</span>
<span class="go">d                       float64</span>
<span class="go">e                          bool</span>
<span class="go">f                datetime64[ns]</span>
<span class="go">g    datetime64[ns, US/Eastern]</span>
<span class="go">h                      category</span>
<span class="go">i                      category</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Write to a parquet file.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell258"><span></span><span class="gp">In [616]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_parquet</span><span class="p">(</span><span class="s2">"example_pa.parquet"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>

<span class="gp">In [617]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_parquet</span><span class="p">(</span><span class="s2">"example_fp.parquet"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"fastparquet"</span><span class="p">)</span>
</pre>
</div>
</div>
<p>Read from a parquet file.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell259"><span></span><span class="gp">In [618]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_parquet</span><span class="p">(</span><span class="s2">"example_fp.parquet"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"fastparquet"</span><span class="p">)</span>

<span class="gp">In [619]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_parquet</span><span class="p">(</span><span class="s2">"example_pa.parquet"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>

<span class="gp">In [620]: </span><span class="n">result</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[620]: </span>
<span class="go">a                        object</span>
<span class="go">b                         int64</span>
<span class="go">c                         uint8</span>
<span class="go">d                       float64</span>
<span class="go">e                          bool</span>
<span class="go">f                datetime64[ns]</span>
<span class="go">g    datetime64[ns, US/Eastern]</span>
<span class="go">h                      category</span>
<span class="go">i                      category</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>By setting the <code>dtype_backend</code> argument you can control the default dtypes used for the resulting DataFrame.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell260"><span></span><span class="gp">In [621]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_parquet</span><span class="p">(</span><span class="s2">"example_pa.parquet"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">,</span> <span class="n">dtype_backend</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>

<span class="gp">In [622]: </span><span class="n">result</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[622]: </span>
<span class="go">a                                      string[pyarrow]</span>
<span class="go">b                                       int64[pyarrow]</span>
<span class="go">c                                       uint8[pyarrow]</span>
<span class="go">d                                      double[pyarrow]</span>
<span class="go">e                                        bool[pyarrow]</span>
<span class="go">f                               timestamp[ns][pyarrow]</span>
<span class="go">g                timestamp[ns, tz=US/Eastern][pyarrow]</span>
<span class="go">h    dictionary&lt;values=string, indices=int8, ordere...</span>
<span class="go">i    dictionary&lt;values=string, indices=int8, ordere...</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Note that this is not supported for <code>fastparquet</code>.</p>
</div>

<p>Read only certain columns of a parquet file.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell261"><span></span><span class="gp">In [623]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_parquet</span><span class="p">(</span>
<span class="gp"></span>    <span class="s2">"example_fp.parquet"</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">engine</span><span class="o">=</span><span class="s2">"fastparquet"</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [624]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_parquet</span><span class="p">(</span>
<span class="gp"></span>    <span class="s2">"example_pa.parquet"</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [625]: </span><span class="n">result</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[625]: </span>
<span class="go">a    object</span>
<span class="go">b     int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

## <h3>Handling indexes</h3>

<p>Serializing a <code>DataFrame</code> to parquet may include the implicit index as one or more columns in the output file. Thus, this code:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell262"><span></span><span class="gp">In [626]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]})</span>

<span class="gp">In [627]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_parquet</span><span class="p">(</span><span class="s2">"test.parquet"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>creates a parquet file with <em>three</em> columns if you use <code>pyarrow</code> for serialization:
<code>a</code>, <code>b</code>, and <code>__index_level_0__</code>. If you’re using <code>fastparquet</code>, the index
<a href="https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write">may or may not</a> be written to the file.</p>

<p>This unexpected extra column causes some databases like Amazon Redshift to reject the file, because that column doesn’t exist in the target table.</p>

<p>If you want to omit a dataframe’s indexes when writing, pass <code>index=False</code> to
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_parquet.html" title="pandas.DataFrame.to_parquet"><code>to_parquet()</code></a>:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell263"><span></span><span class="gp">In [628]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_parquet</span><span class="p">(</span><span class="s2">"test.parquet"</span><span class="p">,</span> <span class="n">index</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
</pre>
</div>
</div>

<p>This creates a parquet file with just the two expected columns, <code>a</code> and <code>b</code>.
If your <code>DataFrame</code> has a custom index, you won’t get it back when you load this file into a <code>DataFrame</code>.</p>

<p>Passing <code>index=True</code> will <em>always</em> write the index, even if that’s not the underlying engine’s default behavior.</p>

## <h3>Partitioning Parquet files</h3>

<p>Parquet supports partitioning of data based on the values of one or more columns.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell264"><span></span><span class="gp">In [629]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"a"</span><span class="p">:</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">],</span> <span class="s2">"b"</span><span class="p">:</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">]})</span>

<span class="gp">In [630]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_parquet</span><span class="p">(</span><span class="n">path</span><span class="o">=</span><span class="s2">"test"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">,</span> <span class="n">partition_cols</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">],</span> <span class="n">compression</span><span class="o">=</span><span class="kc">None</span><span class="p">)</span>
</pre>
</div>
</div>

<p>The <code>path</span></code> specifies the parent directory to which data will be saved. The <code>partition_cols</code> are the column names by which the dataset will be partitioned. Columns are partitioned in the order they are given. The partition splits are determined by the unique values in the partition columns. The above example creates a partitioned dataset that may look like:</p>

<div class="highlight-text notranslate"><div class="highlight"><pre id="codecell265"><span></span>test
├── a=0
│   ├── 0bac803e32dc42ae83fddfd029cbdebc.parquet
│   └──  ...
└── a=1
    ├── e6ab24a4f45147b49b54a662f0c412a3.parquet
    └── ...
</pre>
</div>
</div>

# <h2>ORC</h2>

<p>Similar to the <a href="https://pandas.pydata.org/docs/user_guide/io.html#io-parquet">parquet</a> format, the
<a href="https://orc.apache.org/">ORC Format</a> is a binary columnar serialization for data frames. It is designed to make reading data frames efficient. pandas provides both the reader and the writer for the ORC format, <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_orc.html" title="pandas.read_orc"><code>read_orc()</code></a> and
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_orc.html" title="pandas.DataFrame.to_orc"><code>to_orc()</code></a>.
This requires the <a href="https://arrow.apache.org/docs/python/">pyarrow</a> library.</p>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<ul class="simple">
<li><p>It is <em>highly recommended</em> to install pyarrow using conda due to some issues occurred by pyarrow.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_orc.html" title="pandas.DataFrame.to_orc"><code>to_orc()</code></a> requires pyarrow&gt;=7.0.0.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_orc.html" title="pandas.read_orc"><code>read_orc()</code></a> and
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_orc.html" title="pandas.DataFrame.to_orc"><code>to_orc()</code></a> are not supported on Windows yet, you can find valid environments on <a href="https://pandas.pydata.org/docs/getting_started/install.html">install optional dependencies</a>.</p></li>
<li><p>For supported dtypes please refer to <a href="https://arrow.apache.org/docs/cpp/orc.html#data-types">supported ORC features in Arrow</a>.</p></li>
<li><p>Currently timezones in datetime columns are not preserved when a dataframe is converted into ORC files.</p></li>
</ul>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell266"><span></span><span class="gp">In [631]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp"></span>    <span class="p">{</span>
<span class="gp"></span>        <span class="s2">"a"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"b"</span><span class="p">:</span> <span class="nb">list</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">4</span><span class="p">)),</span>
<span class="gp"></span>        <span class="s2">"c"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mf">4.0</span><span class="p">,</span> <span class="mf">7.0</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="s2">"float64"</span><span class="p">),</span>
<span class="gp"></span>        <span class="s2">"d"</span><span class="p">:</span> <span class="p">[</span><span class="kc">True</span><span class="p">,</span> <span class="kc">False</span><span class="p">,</span> <span class="kc">True</span><span class="p">],</span>
<span class="gp"></span>        <span class="s2">"e"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">date_range</span><span class="p">(</span><span class="s2">"20130101"</span><span class="p">,</span> <span class="n">periods</span><span class="o">=</span><span class="mi">3</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [632]: </span><span class="n">df</span>
<span class="gh">Out[632]: </span>
<span class="go">   a  b    c      d          e</span>
<span class="go">0  a  1  4.0   True 2013-01-01</span>
<span class="go">1  b  2  5.0  False 2013-01-02</span>
<span class="go">2  c  3  6.0   True 2013-01-03</span>

<span class="gp">In [633]: </span><span class="n">df</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[633]: </span>
<span class="go">a            object</span>
<span class="go">b             int64</span>
<span class="go">c           float64</span>
<span class="go">d              bool</span>
<span class="go">e    datetime64[ns]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Write to an orc file.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell267"><span></span><span class="gp">In [634]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_orc</span><span class="p">(</span><span class="s2">"example_pa.orc"</span><span class="p">,</span> <span class="n">engine</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>Read from an orc file.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell268"><span></span><span class="gp">In [635]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_orc</span><span class="p">(</span><span class="s2">"example_pa.orc"</span><span class="p">)</span>

<span class="gp">In [636]: </span><span class="n">result</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[636]: </span>
<span class="go">a            object</span>
<span class="go">b             int64</span>
<span class="go">c           float64</span>
<span class="go">d              bool</span>
<span class="go">e    datetime64[ns]</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

<p>Read only certain columns of an orc file.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell269"><span></span><span class="gp">In [637]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_orc</span><span class="p">(</span>
<span class="gp"></span>    <span class="s2">"example_pa.orc"</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">],</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [638]: </span><span class="n">result</span><span class="o">.</span><span class="n">dtypes</span>
<span class="gh">Out[638]: </span>
<span class="go">a    object</span>
<span class="go">b     int64</span>
<span class="go">dtype: object</span>
</pre>
</div>
</div>

# <h2>SQL queries</h2>

<p>The <code>pandas.io.sql</code> module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API.</p>

<p>Where available, users may first want to opt for <a href="https://arrow.apache.org/adbc/current/index.html">Apache Arrow ADBC</a> drivers.
These drivers should provide the best performance, null handling, and type detection.</p>

<blockquote>
<div><div class="versionadded">
<p><span class="versionmodified added">Added in version 2.2.0: Added native support for ADBC drivers</p>
</div></div>
</blockquote>

<p>For a full list of ADBC drivers and their development status, see the <a href="https://arrow.apache.org/adbc/current/driver/status.html">ADBC Driver Implementation Status</a> documentation.</p>

<p>Where an ADBC driver is not available or may be missing functionality, users should opt for installing SQLAlchemy alongside their database driver library.
Examples of such drivers are <a href="https://www.psycopg.org/">psycopg2</a> for PostgreSQL or
<a href="https://github.com/PyMySQL/PyMySQL">pymysql</a> for MySQL.
For <a href="https://docs.python.org/3/library/sqlite3.html">SQLite</a> this is included in Python’s standard library by default.
You can find an overview of supported drivers for each SQL dialect in the
<a href="https://docs.sqlalchemy.org/en/latest/dialects/index.html">SQLAlchemy docs</a>.</p>

<p>If SQLAlchemy is not installed, you can use a <a href="https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection" title="(in Python v3.13)"><code>sqlite3.Connection</code></a> in place of a SQLAlchemy engine, connection, or URI string.</p>

<p>See also some
<a href="https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-sql">cookbook examples</a> for some advanced strategies.</p>

<p>The key functions are:</p>

<table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html" title="pandas.read_sql_table"><code>read_sql_table</code></a>(table_name,&nbsp;con[,&nbsp;schema,&nbsp;...])</p></td>
<td><p>Read SQL database table into a DataFrame.</p></td>
</tr>
<tr class="row-even"><td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html" title="pandas.read_sql_query"><code>read_sql_query</code></a>(sql,&nbsp;con[,&nbsp;index_col,&nbsp;...])</p></td>
<td><p>Read SQL query into a DataFrame.</p></td>
</tr>
<tr class="row-odd"><td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html" title="pandas.read_sql"><code>read_sql</code></a>(sql,&nbsp;con[,&nbsp;index_col,&nbsp;...])</p></td>
<td><p>Read SQL query or database table into a DataFrame.</p></td>
</tr>
<tr class="row-even"><td><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html" title="pandas.DataFrame.to_sql"><code>DataFrame.to_sql</code></a>(name,&nbsp;con,&nbsp;*[,&nbsp;schema,&nbsp;...])</p></td>
<td><p>Write records stored in a DataFrame to a SQL database.</p></td>
</tr>
</tbody>
</table>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The function <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html" title="pandas.read_sql"><code>read_sql()</code></a> is a convenience wrapper around
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html" title="pandas.read_sql_table"><code>read_sql_table()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html" title="pandas.read_sql_query"><code>read_sql_query()</code></a> (and for backward compatibility) and will delegate to specific function depending on the provided input (database table name or sql query).
Table names do not need to be quoted if they have special characters.</p>
</div>

<p>In the following example, we use the <a href="https://www.sqlite.org/index.html">SQlite</a> SQL database engine. You can use a temporary SQLite database where data are stored in “memory”.</p>

<p>To connect using an ADBC driver you will want to install the <code>adbc_driver_sqlite</code> using your package manager. Once installed, you can use the DBAPI interface provided by the ADBC driver to connect to your database.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell270"><span></span><span class="kn">import</span><span class="w"> </span><span class="nn">adbc_driver_sqlite.dbapi</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="nn">sqlite_dbapi</span>

<span class="c1"># Create the connection</span>
<span class="k">with</span> <span class="n">sqlite_dbapi</span><span class="o">.</span><span class="n">connect</span><span class="p">(</span><span class="s2">"sqlite:///:memory:"</span><span class="p">)</span> <span class="k">as</span> <span class="n">conn</span><span class="p">:</span>
     <span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">conn</span><span class="p">)</span>
</pre>
</div>
</div>

<p>To connect with SQLAlchemy you use the <code>create_engine()</code> function to create an engine object from database URI.
You only need to create the engine once per database you are connecting to.
For more information on <code>create_engine()</code> and the URI formatting, see the examples below and the SQLAlchemy
<a href="https://docs.sqlalchemy.org/en/latest/core/engines.html">documentation</a></p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell271"><span></span><span class="gp">In [639]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">sqlalchemy</span><span class="w"> </span><span class="kn">import</span> <span class="n">create_engine</span>

<span class="go"># Create your engine.</span>
<span class="gp">In [640]: </span><span class="n">engine</span> <span class="o">=</span> <span class="n">create_engine</span><span class="p">(</span><span class="s2">"sqlite:///:memory:"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>If you want to manage your own connections you can pass one of those instead. The example below opens a connection to the database using a Python context manager that automatically closes the connection after the block has completed.
See the <a href="https://docs.sqlalchemy.org/en/latest/core/connections.html#basic-usage">SQLAlchemy docs</a> for an explanation of how the database connection is handled.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell272"><span></span><span class="k">with</span> <span class="n">engine</span><span class="o">.</span><span class="n">connect</span><span class="p">()</span> <span class="k">as</span> <span class="n">conn</span><span class="p">,</span> <span class="n">conn</span><span class="o">.</span><span class="n">begin</span><span class="p">():</span>
    <span class="n">data</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">conn</span><span class="p">)</span>
</pre>
</div>
</div>

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>When you open a connection to a database you are also responsible for closing it.
Side effects of leaving a connection open may include locking the database or other breaking behaviour.</p>
</div>

## <h3>Writing DataFrames</h3>

<p>Assuming the following data is in a <code>DataFrame</code> <code>data</code>, we can insert it into the database using
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html" title="pandas.DataFrame.to_sql"><code>to_sql()</code></a>.</p>

<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>id</p></th>
<th class="head"><p>Date</p></th>
<th class="head"><p>Col_1</p></th>
<th class="head"><p>Col_2</p></th>
<th class="head"><p>Col_3</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>26</p></td>
<td><p>2012-10-18</p></td>
<td><p>X</p></td>
<td><p>25.7</p></td>
<td><p>True</p></td>
</tr>
<tr class="row-odd"><td><p>42</p></td>
<td><p>2012-10-19</p></td>
<td><p>Y</p></td>
<td><p>-12.4</p></td>
<td><p>False</p></td>
</tr>
<tr class="row-even"><td><p>63</p></td>
<td><p>2012-10-20</p></td>
<td><p>Z</p></td>
<td><p>5.73</p></td>
<td><p>True</p></td>
</tr>
</tbody>
</table>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell273"><span></span><span class="gp">In [641]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span>

<span class="gp">In [642]: </span><span class="n">c</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"id"</span><span class="p">,</span> <span class="s2">"Date"</span><span class="p">,</span> <span class="s2">"Col_1"</span><span class="p">,</span> <span class="s2">"Col_2"</span><span class="p">,</span> <span class="s2">"Col_3"</span><span class="p">]</span>

<span class="gp">In [643]: </span><span class="n">d</span> <span class="o">=</span> <span class="p">[</span>
<span class="gp"></span>    <span class="p">(</span><span class="mi">26</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2010</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">18</span><span class="p">),</span> <span class="s2">"X"</span><span class="p">,</span> <span class="mf">27.5</span><span class="p">,</span> <span class="kc">True</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">(</span><span class="mi">42</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2010</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">19</span><span class="p">),</span> <span class="s2">"Y"</span><span class="p">,</span> <span class="o">-</span><span class="mf">12.5</span><span class="p">,</span> <span class="kc">False</span><span class="p">),</span>
<span class="gp"></span>    <span class="p">(</span><span class="mi">63</span><span class="p">,</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2010</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">20</span><span class="p">),</span> <span class="s2">"Z"</span><span class="p">,</span> <span class="mf">5.73</span><span class="p">,</span> <span class="kc">True</span><span class="p">),</span>
<span class="gp"></span><span class="p">]</span>
<span class="gp"></span>

<span class="gp">In [644]: </span><span class="n">data</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">d</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="n">c</span><span class="p">)</span>

<span class="gp">In [645]: </span><span class="n">data</span>
<span class="gh">Out[645]: </span>
<span class="go">   id       Date Col_1  Col_2  Col_3</span>
<span class="go">0  26 2010-10-18     X  27.50   True</span>
<span class="go">1  42 2010-10-19     Y -12.50  False</span>
<span class="go">2  63 2010-10-20     Z   5.73   True</span>

<span class="gp">In [646]: </span><span class="n">data</span><span class="o">.</span><span class="n">to_sql</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">con</span><span class="o">=</span><span class="n">engine</span><span class="p">)</span>
<span class="gh">Out[646]: </span><span class="go">3</span>
</pre>
</div>
</div>

<p>With some databases, writing large DataFrames can result in errors due to packet size limitations being exceeded. This can be avoided by setting the <code>chunksize</code> parameter when calling <code>to_sql</code>. For example, the following writes <code>data</code> to the database in batches of 1000 rows at a time:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell274"><span></span><span class="gp">In [647]: </span><span class="n">data</span><span class="o">.</span><span class="n">to_sql</span><span class="p">(</span><span class="s2">"data_chunked"</span><span class="p">,</span> <span class="n">con</span><span class="o">=</span><span class="n">engine</span><span class="p">,</span> <span class="n">chunksize</span><span class="o">=</span><span class="mi">1000</span><span class="p">)</span>
<span class="gh">Out[647]: </span><span class="go">3</span>
</pre>
</div>
</div>

### <h4>SQL data types</h4>

<p>Ensuring consistent data type management across SQL databases is challenging. Not every SQL database offers the same types, and even when they do the implementation of a given type can vary in ways that have subtle effects on how types can be preserved.</p>

<p>For the best odds at preserving database types users are advised to use ADBC drivers when available. The Arrow type system offers a wider array of types that more closely match database types than the historical pandas/NumPy type system. To illustrate, note this (non-exhaustive) listing of types available in different databases and pandas backends:</p>

<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>numpy/pandas</p></th>
<th class="head"><p>arrow</p></th>
<th class="head"><p>postgres</p></th>
<th class="head"><p>sqlite</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>int16/Int16</p></td>
<td><p>int16</p></td>
<td><p>SMALLINT</p></td>
<td><p>INTEGER</p></td>
</tr>
<tr class="row-odd"><td><p>int32/Int32</p></td>
<td><p>int32</p></td>
<td><p>INTEGER</p></td>
<td><p>INTEGER</p></td>
</tr>
<tr class="row-even"><td><p>int64/Int64</p></td>
<td><p>int64</p></td>
<td><p>BIGINT</p></td>
<td><p>INTEGER</p></td>
</tr>
<tr class="row-odd"><td><p>float32</p></td>
<td><p>float32</p></td>
<td><p>REAL</p></td>
<td><p>REAL</p></td>
</tr>
<tr class="row-even"><td><p>float64</p></td>
<td><p>float64</p></td>
<td><p>DOUBLE PRECISION</p></td>
<td><p>REAL</p></td>
</tr>
<tr class="row-odd"><td><p>object</p></td>
<td><p>string</p></td>
<td><p>TEXT</p></td>
<td><p>TEXT</p></td>
</tr>
<tr class="row-even"><td><p>bool</p></td>
<td><p><code>bool_</span></code></p></td>
<td><p>BOOLEAN</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p>datetime64[ns]</p></td>
<td><p>timestamp(us)</p></td>
<td><p>TIMESTAMP</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p>datetime64[ns,tz]</p></td>
<td><p>timestamp(us,tz)</p></td>
<td><p>TIMESTAMPTZ</p></td>
<td></td>
</tr>
<tr class="row-odd"><td></td>
<td><p>date32</p></td>
<td><p>DATE</p></td>
<td></td>
</tr>
<tr class="row-even"><td></td>
<td><p>month_day_nano_interval</p></td>
<td><p>INTERVAL</p></td>
<td></td>
</tr>
<tr class="row-odd"><td></td>
<td><p>binary</p></td>
<td><p>BINARY</p></td>
<td><p>BLOB</p></td>
</tr>
<tr class="row-even"><td></td>
<td><p>decimal128</p></td>
<td><p>DECIMAL <a class="footnote-reference brackets" href="#f1" id="id5" role="doc-noteref"><span class="fn-bracket">[</span>1<span class="fn-bracket">]</span></a></p></td>
<td></td>
</tr>
<tr class="row-odd"><td></td>
<td><p>list</p></td>
<td><p>ARRAY <a class="footnote-reference brackets" href="#f1" id="id6" role="doc-noteref"><span class="fn-bracket">[</span>1<span class="fn-bracket">]</span></a></p></td>
<td></td>
</tr>
<tr class="row-even"><td></td>
<td><p>struct</p></td>
<td><dl class="simple">
<dt>COMPOSITE TYPE</dt><dd><p><a class="footnote-reference brackets" href="#f1" id="id7" role="doc-noteref"><span class="fn-bracket">[</span>1<span class="fn-bracket">]</span></a></p>
</dd>
</dl>
</td>
<td></td>
</tr>
</tbody>
</table>

<p class="rubric">Footnotes</p>
<aside class="footnote-list brackets">
<aside class="footnote brackets" id="f1" role="doc-footnote">
<span class="label"><span class="fn-bracket">[</span>1<span class="fn-bracket">]</span></span>
<span class="backrefs">(<a role="doc-backlink" href="#id5">1</a>,<a role="doc-backlink" href="#id6">2</a>,<a role="doc-backlink" href="#id7">3</a>)</span>
<p>Not implemented as of writing, but theoretically possible</p>
</aside>
</aside>
<p>If you are interested in preserving database types as best as possible throughout the lifecycle of your DataFrame, users are encouraged to
leverage the <code>dtype_backend="pyarrow"</code> argument of <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html" title="pandas.read_sql"><code>read_sql()</code></a></p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell275"><span></span><span class="c1"># for roundtripping</span>
<span class="k">with</span> <span class="n">pg_dbapi</span><span class="o">.</span><span class="n">connect</span><span class="p">(</span><span class="n">uri</span><span class="p">)</span> <span class="k">as</span> <span class="n">conn</span><span class="p">:</span>
    <span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_sql</span><span class="p">(</span><span class="s2">"pandas_table"</span><span class="p">,</span> <span class="n">conn</span><span class="p">,</span> <span class="n">dtype_backend</span><span class="o">=</span><span class="s2">"pyarrow"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>This will prevent your data from being converted to the traditional pandas/NumPy type system, which often converts SQL types in ways that make them impossible to round-trip.</p>

<p>In case an ADBC driver is not available, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html" title="pandas.DataFrame.to_sql"><code>to_sql()</code></a> will try to map your data to an appropriate SQL data type based on the dtype of the data. When you have columns of dtype <code>object</code>, pandas will try to infer the data type.</p>

<p>You can always override the default type by specifying the desired SQL type of any of the columns by using the <code>dtype</code> argument.
This argument needs a dictionary mapping column names to SQLAlchemy types (or strings for the sqlite3 fallback mode).
For example, specifying to use the sqlalchemy <code>String</code> type instead of the default <code>Text</code> type for string columns:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell276"><span></span><span class="gp">In [648]: </span><span class="kn">from</span><span class="w"> </span><span class="nn">sqlalchemy.types</span><span class="w"> </span><span class="kn">import</span> <span class="n">String</span>

<span class="gp">In [649]: </span><span class="n">data</span><span class="o">.</span><span class="n">to_sql</span><span class="p">(</span><span class="s2">"data_dtype"</span><span class="p">,</span> <span class="n">con</span><span class="o">=</span><span class="n">engine</span><span class="p">,</span> <span class="n">dtype</span><span class="o">=</span><span class="p">{</span><span class="s2">"Col_1"</span><span class="p">:</span> <span class="n">String</span><span class="p">})</span>
<span class="gh">Out[649]: </span><span class="go">3</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Due to the limited support for timedelta’s in the different database flavors, columns with type <code>timedelta64</code> will be written as integer values as nanoseconds to the database and a warning will be raised. The only exception to this is when using the ADBC PostgreSQL driver in which case a timedelta will be written to the database as an <code>INTERVAL</code></p>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Columns of <code>category</code> dtype will be converted to the dense representation as you would get with <code>np.asarray(categorical)</code> (e.g. for string categories this gives an array of strings).
Because of this, reading the database table back in does <strong>not</strong> generate a categorical.</p>
</div>

## <h3>Datetime data types</h3>

<p>Using ADBC or SQLAlchemy, <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html" title="pandas.DataFrame.to_sql"><code>to_sql()</code></a> is capable of writing datetime data that is timezone naive or timezone aware. However, the resulting data stored in the database ultimately depends on the supported data type for datetime data of the database system being used.</p>

<p>The following table lists supported data types for datetime data for some common databases.
Other database dialects may have different data types for datetime data.</p>
<table class="table">
<thead>
<tr class="row-odd"><th class="head"><p>Database</p></th>
<th class="head"><p>SQL Datetime Types</p></th>
<th class="head"><p>Timezone Support</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>SQLite</p></td>
<td><p><code>TEXT</code></p></td>
<td><p>No</p></td>
</tr>
<tr class="row-odd"><td><p>MySQL</p></td>
<td><p><code>TIMESTAMP</code> or <code>DATETIME</code></p></td>
<td><p>No</p></td>
</tr>
<tr class="row-even"><td><p>PostgreSQL</p></td>
<td><p><code>TIMESTAMP</code> or <code>TIMESTAMP WITH TIME ZONE</code></p></td>
<td><p>Yes</p></td>
</tr>
</tbody>
</table>


<p>When writing timezone aware data to databases that do not support timezones, the data will be written as timezone naive timestamps that are in local time with respect to the timezone.</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html" title="pandas.read_sql_table"><code>read_sql_table()</code></a> is also capable of reading datetime data that is timezone aware or naive. When reading <code>TIMESTAMP WITH TIME ZONE</code> types, pandas will convert the data to UTC.</p>

### <h4>Insertion method</h4>

<p>The parameter <code>method</code> controls the SQL insertion clause used. Possible values are:</p>
<ul class="simple">
<li><p><code>None</code>: Uses standard SQL <code>INSERT</code> clause (one per row).</p></li>
<li><p><code>'multi'</code>: Pass multiple values in a single <code>INSERT</code> clause.
It uses a <em>special</em> SQL syntax not supported by all backends.
This usually provides better performance for analytic databases like <em>Presto</em> and <em>Redshift</em>, but has worse performance for
traditional SQL backend if the table contains many columns. For more information check the SQLAlchemy
<a href="https://docs.sqlalchemy.org/en/latest/core/dml.html#sqlalchemy.sql.expression.Insert.values.params.*args">documentation</a>.</p></li>
<li><p>callable with signature <code>(pd_table, conn, keys, data_iter)</code>:
This can be used to implement a more performant insertion method based on specific backend dialect features.</p></li>
</ul>

<p>Example of a callable using PostgreSQL <a href="https://www.postgresql.org/docs/current/sql-copy.html">COPY clause</a>:</p>

<div class="highlight-default notranslate"><div class="highlight"><pre id="codecell277"><span></span><span class="c1"># Alternative to_sql() *method* for DBs that support COPY FROM</span>
<span class="kn">import</span><span class="w"> </span><span class="nn">csv</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">io</span><span class="w"> </span><span class="kn">import</span> <span class="n">StringIO</span>

<span class="k">def</span><span class="w"> </span><span class="nf">psql_insert_copy</span><span class="p">(</span><span class="n">table</span><span class="p">,</span> <span class="n">conn</span><span class="p">,</span> <span class="n">keys</span><span class="p">,</span> <span class="n">data_iter</span><span class="p">):</span>
<span class="w">    </span><span class="sd">"""</span>
<span class="sd">    Execute SQL statement inserting data</span>

<span class="sd">    Parameters</span>
<span class="sd">    ----------</span>
<span class="sd">    table : pandas.io.sql.SQLTable</span>
<span class="sd">    conn : sqlalchemy.engine.Engine or sqlalchemy.engine.Connection</span>
<span class="sd">    keys : list of str</span>
<span class="sd">        Column names</span>
<span class="sd">    data_iter : Iterable that iterates the values to be inserted</span>
<span class="sd">    """</span>
    <span class="c1"># gets a DBAPI connection that can provide a cursor</span>
    <span class="n">dbapi_conn</span> <span class="o">=</span> <span class="n">conn</span><span class="o">.</span><span class="n">connection</span>
    <span class="k">with</span> <span class="n">dbapi_conn</span><span class="o">.</span><span class="n">cursor</span><span class="p">()</span> <span class="k">as</span> <span class="n">cur</span><span class="p">:</span>
        <span class="n">s_buf</span> <span class="o">=</span> <span class="n">StringIO</span><span class="p">()</span>
        <span class="n">writer</span> <span class="o">=</span> <span class="n">csv</span><span class="o">.</span><span class="n">writer</span><span class="p">(</span><span class="n">s_buf</span><span class="p">)</span>
        <span class="n">writer</span><span class="o">.</span><span class="n">writerows</span><span class="p">(</span><span class="n">data_iter</span><span class="p">)</span>
        <span class="n">s_buf</span><span class="o">.</span><span class="n">seek</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>

        <span class="n">columns</span> <span class="o">=</span> <span class="s1">', '</span><span class="o">.</span><span class="n">join</span><span class="p">([</span><span class="s1">'"</span><span class="si">{}</span><span class="s1">"'</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">k</span><span class="p">)</span> <span class="k">for</span> <span class="n">k</span> <span class="ow">in</span> <span class="n">keys</span><span class="p">])</span>
        <span class="k">if</span> <span class="n">table</span><span class="o">.</span><span class="n">schema</span><span class="p">:</span>
            <span class="n">table_name</span> <span class="o">=</span> <span class="s1">'</span><span class="si">{}</span><span class="s1">.</span><span class="si">{}</span><span class="s1">'</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">table</span><span class="o">.</span><span class="n">schema</span><span class="p">,</span> <span class="n">table</span><span class="o">.</span><span class="n">name</span><span class="p">)</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="n">table_name</span> <span class="o">=</span> <span class="n">table</span><span class="o">.</span><span class="n">name</span>

        <span class="n">sql</span> <span class="o">=</span> <span class="s1">'COPY </span><span class="si">{}</span><span class="s1"> (</span><span class="si">{}</span><span class="s1">) FROM STDIN WITH CSV'</span><span class="o">.</span><span class="n">format</span><span class="p">(</span>
            <span class="n">table_name</span><span class="p">,</span> <span class="n">columns</span><span class="p">)</span>
        <span class="n">cur</span><span class="o">.</span><span class="n">copy_expert</span><span class="p">(</span><span class="n">sql</span><span class="o">=</span><span class="n">sql</span><span class="p">,</span> <span class="n">file</span><span class="o">=</span><span class="n">s_buf</span><span class="p">)</span>
</pre>
</div>
</div>

## <h3>Reading tables</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html" title="pandas.read_sql_table"><code>read_sql_table()</code></a> will read a database table given the table name and optionally a subset of columns to read.</p>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>In order to use <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html" title="pandas.read_sql_table"><code>read_sql_table()</code></a>, you <strong>must</strong> have the ADBC driver or SQLAlchemy optional dependency installed.</p>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell278"><span></span><span class="gp">In [650]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">engine</span><span class="p">)</span>
<span class="gh">Out[650]: </span>
<span class="go">   index  id       Date Col_1  Col_2  Col_3</span>
<span class="go">0      0  26 2010-10-18     X  27.50   True</span>
<span class="go">1      1  42 2010-10-19     Y -12.50  False</span>
<span class="go">2      2  63 2010-10-20     Z   5.73   True</span>
</pre>
</div>
</div>

<div class="admonition note">
<p class="admonition-title">Note</p>
<p>ADBC drivers will map database types directly back to arrow types. For other drivers note that pandas infers column dtypes from query outputs, and not by looking up data types in the physical database schema. For example, assume <code>userid</code> is an integer column in a table. Then, intuitively, <code>select userid ...</code> will return integer-valued series, while <code>select cast(userid as text) ...</code> will return object-valued (str) series. Accordingly, if the query output is empty, then all resulting columns will be returned as object-valued (since they are most general). If you foresee that your query will sometimes generate an empty result, you may want to explicitly typecast afterwards to ensure dtype integrity.</p>
</div>

<p>You can also specify the name of the column as the <code>DataFrame</code> index, and specify a subset of columns to be read.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell279"><span></span><span class="gp">In [651]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">engine</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="s2">"id"</span><span class="p">)</span>
<span class="gh">Out[651]: </span>
<span class="go">    index       Date Col_1  Col_2  Col_3</span>
<span class="go">id                                      </span>
<span class="go">26      0 2010-10-18     X  27.50   True</span>
<span class="go">42      1 2010-10-19     Y -12.50  False</span>
<span class="go">63      2 2010-10-20     Z   5.73   True</span>

<span class="gp">In [652]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">engine</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"Col_1"</span><span class="p">,</span> <span class="s2">"Col_2"</span><span class="p">])</span>
<span class="gh">Out[652]: </span>
<span class="go">  Col_1  Col_2</span>
<span class="go">0     X  27.50</span>
<span class="go">1     Y -12.50</span>
<span class="go">2     Z   5.73</span>
</pre>
</div>
</div>

<p>And you can explicitly force columns to be parsed as dates:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell280"><span></span><span class="gp">In [653]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">engine</span><span class="p">,</span> <span class="n">parse_dates</span><span class="o">=</span><span class="p">[</span><span class="s2">"Date"</span><span class="p">])</span>
<span class="gh">Out[653]: </span>
<span class="go">   index  id       Date Col_1  Col_2  Col_3</span>
<span class="go">0      0  26 2010-10-18     X  27.50   True</span>
<span class="go">1      1  42 2010-10-19     Y -12.50  False</span>
<span class="go">2      2  63 2010-10-20     Z   5.73   True</span>
</pre>
</div>
</div>

<p>If needed you can explicitly specify a format string, or a dict of arguments to pass to
<a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html" title="pandas.to_datetime"><code>pandas.to_datetime()</code></a>:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell281"><span></span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">engine</span><span class="p">,</span> <span class="n">parse_dates</span><span class="o">=</span><span class="p">{</span><span class="s2">"Date"</span><span class="p">:</span> <span class="s2">"%Y-%m-</span><span class="si">%d</span><span class="s2">"</span><span class="p">})</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span>
    <span class="s2">"data"</span><span class="p">,</span>
    <span class="n">engine</span><span class="p">,</span>
    <span class="n">parse_dates</span><span class="o">=</span><span class="p">{</span><span class="s2">"Date"</span><span class="p">:</span> <span class="p">{</span><span class="s2">"format"</span><span class="p">:</span> <span class="s2">"%Y-%m-</span><span class="si">%d</span><span class="s2"> %H:%M:%S"</span><span class="p">}},</span>
<span class="p">)</span>
</pre>
</div>
</div>

<p>You can check if a table exists using <code>has_table()</code></p>

## <h3>Schema support</h3>

<p>Reading from and writing to different schema’s is supported through the <code>schema</code> keyword in the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html" title="pandas.read_sql_table"><code>read_sql_table()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html" title="pandas.DataFrame.to_sql"><code>to_sql()</code></a> functions. Note however that this depends on the database flavor (sqlite does not have schema’s). For example:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell282"><span></span><span class="n">df</span><span class="o">.</span><span class="n">to_sql</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">con</span><span class="o">=</span><span class="n">engine</span><span class="p">,</span> <span class="n">schema</span><span class="o">=</span><span class="s2">"other_schema"</span><span class="p">)</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_sql_table</span><span class="p">(</span><span class="s2">"table"</span><span class="p">,</span> <span class="n">engine</span><span class="p">,</span> <span class="n">schema</span><span class="o">=</span><span class="s2">"other_schema"</span><span class="p">)</span>
</pre>
</div>
</div>

## <h3>Querying</h3>

<p>You can query using raw SQL in the <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html" title="pandas.read_sql_query"><code>read_sql_query()</code></a> function. In this case you must use the SQL variant appropriate for your database.
When using SQLAlchemy, you can also pass SQLAlchemy Expression language constructs, which are database-agnostic.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell283"><span></span><span class="gp">In [654]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql_query</span><span class="p">(</span><span class="s2">"SELECT * FROM data"</span><span class="p">,</span> <span class="n">engine</span><span class="p">)</span>
<span class="gh">Out[654]: </span>
<span class="go">   index  id                        Date Col_1  Col_2  Col_3</span>
<span class="go">0      0  26  2010-10-18 00:00:00.000000     X  27.50      1</span>
<span class="go">1      1  42  2010-10-19 00:00:00.000000     Y -12.50      0</span>
<span class="go">2      2  63  2010-10-20 00:00:00.000000     Z   5.73      1</span>
</pre>
</div>
</div>

<p>Of course, you can specify a more “complex” query.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell284"><span></span><span class="gp">In [655]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql_query</span><span class="p">(</span><span class="s2">"SELECT id, Col_1, Col_2 FROM data WHERE id = 42;"</span><span class="p">,</span> <span class="n">engine</span><span class="p">)</span>
<span class="gh">Out[655]: </span>
<span class="go">   id Col_1  Col_2</span>
<span class="go">0  42     Y  -12.5</span>
</pre>
</div>
</div>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html" title="pandas.read_sql_query"><code>read_sql_query()</code></a> function supports a <code>chunksize</code> argument. Specifying this will return an iterator through chunks of the query result:</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell285"><span></span><span class="gp">In [656]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="mi">20</span><span class="p">,</span> <span class="mi">3</span><span class="p">),</span> <span class="n">columns</span><span class="o">=</span><span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">))</span>

<span class="gp">In [657]: </span><span class="n">df</span><span class="o">.</span><span class="n">to_sql</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s2">"data_chunks"</span><span class="p">,</span> <span class="n">con</span><span class="o">=</span><span class="n">engine</span><span class="p">,</span> <span class="n">index</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span>
<span class="gh">Out[657]: </span><span class="go">20</span>
</pre>
</div>
</div>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell286"><span></span><span class="gp">In [658]: </span><span class="k">for</span> <span class="n">chunk</span> <span class="ow">in</span> <span class="n">pd</span><span class="o">.</span><span class="n">read_sql_query</span><span class="p">(</span><span class="s2">"SELECT * FROM data_chunks"</span><span class="p">,</span> <span class="n">engine</span><span class="p">,</span> <span class="n">chunksize</span><span class="o">=</span><span class="mi">5</span><span class="p">):</span>
<span class="gp"></span>    <span class="nb">print</span><span class="p">(</span><span class="n">chunk</span><span class="p">)</span>
<span class="gp"></span>
<span class="go">          a         b         c</span>
<span class="go">0 -0.395347 -0.822726 -0.363777</span>
<span class="go">1  1.676124 -0.908102 -1.391346</span>
<span class="go">2 -1.094269  0.278380  1.205899</span>
<span class="go">3  1.503443  0.932171 -0.709459</span>
<span class="go">4 -0.645944 -1.351389  0.132023</span>
<span class="go">          a         b         c</span>
<span class="go">0  0.210427  0.192202  0.661949</span>
<span class="go">1  1.690629 -1.046044  0.618697</span>
<span class="go">2 -0.013863  1.314289  1.951611</span>
<span class="go">3 -1.485026  0.304662  1.194757</span>
<span class="go">4 -0.446717  0.528496 -0.657575</span>
<span class="go">          a         b         c</span>
<span class="go">0 -0.876654  0.336252  0.172668</span>
<span class="go">1  0.337684 -0.411202 -0.828394</span>
<span class="go">2 -0.244413  1.094948  0.087183</span>
<span class="go">3  1.125934 -1.480095  1.205944</span>
<span class="go">4 -0.451849  0.452214 -2.208192</span>
<span class="go">          a         b         c</span>
<span class="go">0 -2.061019  0.044184 -0.017118</span>
<span class="go">1  1.248959 -0.675595 -1.908296</span>
<span class="go">2 -0.125934  1.491974  0.648726</span>
<span class="go">3  0.391214  0.438609  1.634248</span>
<span class="go">4  1.208707 -1.535740  1.620399</span>
</pre>
</div>
</div>

## <h3>Engine connection examples</h3>

<p>To connect with SQLAlchemy you use the <code>create_engine()</code> function to create an engine object from database URI. You only need to create the engine once per database you are connecting to.</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell287"><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">sqlalchemy</span><span class="w"> </span><span class="kn">import</span> <span class="n">create_engine</span>

<span class="n">engine</span> <span class="o">=</span> <span class="n">create_engine</span><span class="p">(</span><span class="s2">"postgresql://scott:tiger@localhost:5432/mydatabase"</span><span class="p">)</span>

<span class="n">engine</span> <span class="o">=</span> <span class="n">create_engine</span><span class="p">(</span><span class="s2">"mysql+mysqldb://scott:tiger@localhost/foo"</span><span class="p">)</span>

<span class="n">engine</span> <span class="o">=</span> <span class="n">create_engine</span><span class="p">(</span><span class="s2">"oracle://scott:tiger@127.0.0.1:1521/sidname"</span><span class="p">)</span>

<span class="n">engine</span> <span class="o">=</span> <span class="n">create_engine</span><span class="p">(</span><span class="s2">"mssql+pyodbc://mydsn"</span><span class="p">)</span>

<span class="c1"># sqlite://&lt;nohostname&gt;/&lt;path&gt;</span>
<span class="c1"># where &lt;path&gt; is relative:</span>
<span class="n">engine</span> <span class="o">=</span> <span class="n">create_engine</span><span class="p">(</span><span class="s2">"sqlite:///foo.db"</span><span class="p">)</span>

<span class="c1"># or absolute, starting with a slash:</span>
<span class="n">engine</span> <span class="o">=</span> <span class="n">create_engine</span><span class="p">(</span><span class="s2">"sqlite:////absolute/path/to/foo.db"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>For more information see the examples the SQLAlchemy
<a href="https://docs.sqlalchemy.org/en/latest/core/engines.html">documentation</a></p>

## <h3>Advanced SQLAlchemy queries</h3>

<p>You can use SQLAlchemy constructs to describe your query.</p>

<p>Use <code>sqlalchemy.text()</code> to specify query parameters in a backend-neutral way</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell288"><span></span><span class="gp">In [659]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">sqlalchemy</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="nn">sa</span>

<span class="gp">In [660]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql</span><span class="p">(</span>
<span class="gp"></span>    <span class="n">sa</span><span class="o">.</span><span class="n">text</span><span class="p">(</span><span class="s2">"SELECT * FROM data where Col_1=:col1"</span><span class="p">),</span> <span class="n">engine</span><span class="p">,</span> <span class="n">params</span><span class="o">=</span><span class="p">{</span><span class="s2">"col1"</span><span class="p">:</span> <span class="s2">"X"</span><span class="p">}</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>
<span class="gh">Out[660]: </span>
<span class="go">   index  id                        Date Col_1  Col_2  Col_3</span>
<span class="go">0      0  26  2010-10-18 00:00:00.000000     X   27.5      1</span>
</pre>
</div>
</div>

<p>If you have an SQLAlchemy description of your database you can express where conditions using SQLAlchemy expressions</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell289"><span></span><span class="gp">In [661]: </span><span class="n">metadata</span> <span class="o">=</span> <span class="n">sa</span><span class="o">.</span><span class="n">MetaData</span><span class="p">()</span>

<span class="gp">In [662]: </span><span class="n">data_table</span> <span class="o">=</span> <span class="n">sa</span><span class="o">.</span><span class="n">Table</span><span class="p">(</span>
<span class="gp"></span>    <span class="s2">"data"</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">metadata</span><span class="p">,</span>
<span class="gp"></span>    <span class="n">sa</span><span class="o">.</span><span class="n">Column</span><span class="p">(</span><span class="s2">"index"</span><span class="p">,</span> <span class="n">sa</span><span class="o">.</span><span class="n">Integer</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">sa</span><span class="o">.</span><span class="n">Column</span><span class="p">(</span><span class="s2">"Date"</span><span class="p">,</span> <span class="n">sa</span><span class="o">.</span><span class="n">DateTime</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">sa</span><span class="o">.</span><span class="n">Column</span><span class="p">(</span><span class="s2">"Col_1"</span><span class="p">,</span> <span class="n">sa</span><span class="o">.</span><span class="n">String</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">sa</span><span class="o">.</span><span class="n">Column</span><span class="p">(</span><span class="s2">"Col_2"</span><span class="p">,</span> <span class="n">sa</span><span class="o">.</span><span class="n">Float</span><span class="p">),</span>
<span class="gp"></span>    <span class="n">sa</span><span class="o">.</span><span class="n">Column</span><span class="p">(</span><span class="s2">"Col_3"</span><span class="p">,</span> <span class="n">sa</span><span class="o">.</span><span class="n">Boolean</span><span class="p">),</span>
<span class="gp"></span><span class="p">)</span>
<span class="gp"></span>

<span class="gp">In [663]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql</span><span class="p">(</span><span class="n">sa</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="n">data_table</span><span class="p">)</span><span class="o">.</span><span class="n">where</span><span class="p">(</span><span class="n">data_table</span><span class="o">.</span><span class="n">c</span><span class="o">.</span><span class="n">Col_3</span> <span class="ow">is</span> <span class="kc">True</span><span class="p">),</span> <span class="n">engine</span><span class="p">)</span>
<span class="gh">Out[663]: </span>
<span class="go">Empty DataFrame</span>
<span class="go">Columns: [index, Date, Col_1, Col_2, Col_3]</span>
<span class="go">Index: []</span>
</pre>
</div>
</div>

<p>You can combine SQLAlchemy expressions with parameters passed to
<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html" title="pandas.read_sql"><code>read_sql()</code></a> using <code>sqlalchemy.bindparam()</code></p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell290"><span></span><span class="gp">In [664]: </span><span class="kn">import</span><span class="w"> </span><span class="nn">datetime</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="nn">dt</span>

<span class="gp">In [665]: </span><span class="n">expr</span> <span class="o">=</span> <span class="n">sa</span><span class="o">.</span><span class="n">select</span><span class="p">(</span><span class="n">data_table</span><span class="p">)</span><span class="o">.</span><span class="n">where</span><span class="p">(</span><span class="n">data_table</span><span class="o">.</span><span class="n">c</span><span class="o">.</span><span class="n">Date</span> <span class="o">&gt;</span> <span class="n">sa</span><span class="o">.</span><span class="n">bindparam</span><span class="p">(</span><span class="s2">"date"</span><span class="p">))</span>

<span class="gp">In [666]: </span><span class="n">pd</span><span class="o">.</span><span class="n">read_sql</span><span class="p">(</span><span class="n">expr</span><span class="p">,</span> <span class="n">engine</span><span class="p">,</span> <span class="n">params</span><span class="o">=</span><span class="p">{</span><span class="s2">"date"</span><span class="p">:</span> <span class="n">dt</span><span class="o">.</span><span class="n">datetime</span><span class="p">(</span><span class="mi">2010</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">18</span><span class="p">)})</span>
<span class="gh">Out[666]: </span>
<span class="go">   index       Date Col_1  Col_2  Col_3</span>
<span class="go">0      1 2010-10-19     Y -12.50  False</span>
<span class="go">1      2 2010-10-20     Z   5.73   True</span>
</pre>
</div>
</div>

## <h3>Sqlite fallback</h3>

<p>The use of sqlite is supported without using SQLAlchemy. This mode requires a Python database adapter which respect the <a href="https://www.python.org/dev/peps/pep-0249/">Python DB-API</a>.</p>

<p>You can create connections like so:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell291"><span></span><span class="kn">import</span><span class="w"> </span><span class="nn">sqlite3</span>

<span class="n">con</span> <span class="o">=</span> <span class="n">sqlite3</span><span class="o">.</span><span class="n">connect</span><span class="p">(</span><span class="s2">":memory:"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>And then issue the following queries:</p>

<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell292"><span></span><span class="n">data</span><span class="o">.</span><span class="n">to_sql</span><span class="p">(</span><span class="s2">"data"</span><span class="p">,</span> <span class="n">con</span><span class="p">)</span>
<span class="n">pd</span><span class="o">.</span><span class="n">read_sql_query</span><span class="p">(</span><span class="s2">"SELECT * FROM data"</span><span class="p">,</span> <span class="n">con</span><span class="p">)</span>
</pre>
</div>
</div>

# <h2>Google BigQuery</h2>

<p>The <code>pandas-gbq</code> package provides functionality to read/write from Google BigQuery.</p>

<p>pandas integrates with this external package. if <code>pandas-gbq</code> is installed, you can use the pandas methods <code>pd.read_gbq</code> and <code>DataFrame.to_gbq</code>, which will call the respective functions from <code>pandas-gbq</code>.</p>

<p>Full documentation can be found <a href="https://pandas-gbq.readthedocs.io/en/latest/">here</a>.</p>

# <h2>Other file formats</h2>

<p>pandas itself only supports IO with a limited set of file formats that map cleanly to its tabular data model. For reading and writing other file formats into and from pandas, we recommend these packages from the broader community.</p>

## <h3>netCDF</h3>

<p><a href="https://xarray.pydata.org/en/stable/">xarray</a> provides data structures inspired by the pandas <code>DataFrame</code> for working with multi-dimensional datasets, with a focus on the netCDF file format and easy conversion to and from pandas.</p>

# <h2>Performance considerations</h2>

<p>This is an informal comparison of various IO methods, using pandas 0.24.2. Timings are machine dependent and small differences should be
ignored.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell301"><span></span><span class="gp">In [1]: </span><span class="n">sz</span> <span class="o">=</span> <span class="mi">1000000</span>
<span class="gp">In [2]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s1">'A'</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="n">sz</span><span class="p">),</span> <span class="s1">'B'</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="o">*</span> <span class="n">sz</span><span class="p">})</span>

<span class="gp">In [3]: </span><span class="n">df</span><span class="o">.</span><span class="n">info</span><span class="p">()</span>
<span class="go">&lt;class 'pandas.core.frame.DataFrame'&gt;</span>
<span class="go">RangeIndex: 1000000 entries, 0 to 999999</span>
<span class="go">Data columns (total 2 columns):</span>
<span class="go">A    1000000 non-null float64</span>
<span class="go">B    1000000 non-null int64</span>
<span class="go">dtypes: float64(1), int64(1)</span>
<span class="go">memory usage: 15.3 MB</span>
</pre>
</div>
</div>

<p>The following test functions will be used below to compare the performance of several IO methods:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre id="codecell302"><span></span><span class="kn">import</span><span class="w"> </span><span class="nn">numpy</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="nn">np</span>

<span class="kn">import</span><span class="w"> </span><span class="nn">os</span>

<span class="n">sz</span> <span class="o">=</span> <span class="mi">1000000</span>
<span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="n">sz</span><span class="p">),</span> <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="o">*</span> <span class="n">sz</span><span class="p">})</span>

<span class="n">sz</span> <span class="o">=</span> <span class="mi">1000000</span>
<span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">seed</span><span class="p">(</span><span class="mi">42</span><span class="p">)</span>
<span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"A"</span><span class="p">:</span> <span class="n">np</span><span class="o">.</span><span class="n">random</span><span class="o">.</span><span class="n">randn</span><span class="p">(</span><span class="n">sz</span><span class="p">),</span> <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="o">*</span> <span class="n">sz</span><span class="p">})</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_sql_write</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="k">if</span> <span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">exists</span><span class="p">(</span><span class="s2">"test.sql"</span><span class="p">):</span>
        <span class="n">os</span><span class="o">.</span><span class="n">remove</span><span class="p">(</span><span class="s2">"test.sql"</span><span class="p">)</span>
    <span class="n">sql_db</span> <span class="o">=</span> <span class="n">sqlite3</span><span class="o">.</span><span class="n">connect</span><span class="p">(</span><span class="s2">"test.sql"</span><span class="p">)</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_sql</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s2">"test_table"</span><span class="p">,</span> <span class="n">con</span><span class="o">=</span><span class="n">sql_db</span><span class="p">)</span>
    <span class="n">sql_db</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_sql_read</span><span class="p">():</span>
    <span class="n">sql_db</span> <span class="o">=</span> <span class="n">sqlite3</span><span class="o">.</span><span class="n">connect</span><span class="p">(</span><span class="s2">"test.sql"</span><span class="p">)</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_sql_query</span><span class="p">(</span><span class="s2">"select * from test_table"</span><span class="p">,</span> <span class="n">sql_db</span><span class="p">)</span>
    <span class="n">sql_db</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_fixed_write</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span><span class="s2">"test_fixed.hdf"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"test"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_fixed_read</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"test_fixed.hdf"</span><span class="p">,</span> <span class="s2">"test"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_fixed_write_compress</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span><span class="s2">"test_fixed_compress.hdf"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"test"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">,</span> <span class="n">complib</span><span class="o">=</span><span class="s2">"blosc"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_fixed_read_compress</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"test_fixed_compress.hdf"</span><span class="p">,</span> <span class="s2">"test"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_table_write</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span><span class="s2">"test_table.hdf"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"test"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">,</span> <span class="nb">format</span><span class="o">=</span><span class="s2">"table"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_table_read</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"test_table.hdf"</span><span class="p">,</span> <span class="s2">"test"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_table_write_compress</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_hdf</span><span class="p">(</span>
        <span class="s2">"test_table_compress.hdf"</span><span class="p">,</span> <span class="n">key</span><span class="o">=</span><span class="s2">"test"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">,</span> <span class="n">complib</span><span class="o">=</span><span class="s2">"blosc"</span><span class="p">,</span> <span class="nb">format</span><span class="o">=</span><span class="s2">"table"</span>
    <span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_hdf_table_read_compress</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_hdf</span><span class="p">(</span><span class="s2">"test_table_compress.hdf"</span><span class="p">,</span> <span class="s2">"test"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_csv_write</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_csv</span><span class="p">(</span><span class="s2">"test.csv"</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s2">"w"</span><span class="p">)</span>

<span class="k">def</span><span class="w"> </span><span class="nf">test_csv_read</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_csv</span><span class="p">(</span><span class="s2">"test.csv"</span><span class="p">,</span> <span class="n">index_col</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_feather_write</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_feather</span><span class="p">(</span><span class="s2">"test.feather"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_feather_read</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_feather</span><span class="p">(</span><span class="s2">"test.feather"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_pickle_write</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"test.pkl"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_pickle_read</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_pickle</span><span class="p">(</span><span class="s2">"test.pkl"</span><span class="p">)</span>



<span class="k">def</span><span class="w"> </span><span class="nf">test_pickle_write_compress</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_pickle</span><span class="p">(</span><span class="s2">"test.pkl.compress"</span><span class="p">,</span> <span class="n">compression</span><span class="o">=</span><span class="s2">"xz"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_pickle_read_compress</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_pickle</span><span class="p">(</span><span class="s2">"test.pkl.compress"</span><span class="p">,</span> <span class="n">compression</span><span class="o">=</span><span class="s2">"xz"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_parquet_write</span><span class="p">(</span><span class="n">df</span><span class="p">):</span>
    <span class="n">df</span><span class="o">.</span><span class="n">to_parquet</span><span class="p">(</span><span class="s2">"test.parquet"</span><span class="p">)</span>


<span class="k">def</span><span class="w"> </span><span class="nf">test_parquet_read</span><span class="p">():</span>
    <span class="n">pd</span><span class="o">.</span><span class="n">read_parquet</span><span class="p">(</span><span class="s2">"test.parquet"</span><span class="p">)</span>
</pre>
</div>
</div>

<p>When writing, the top three functions in terms of speed are <code>test_feather_write</span></code>, <code>test_hdf_fixed_write</span></code> and <code>test_hdf_fixed_write_compress</span></code>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell303"><span></span><span class="gp">In [4]: </span><span class="o">%</span><span class="k">timeit</span> test_sql_write(df)
<span class="go">3.29 s ± 43.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [5]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_fixed_write(df)
<span class="go">19.4 ms ± 560 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [6]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_fixed_write_compress(df)
<span class="go">19.6 ms ± 308 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [7]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_table_write(df)
<span class="go">449 ms ± 5.61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [8]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_table_write_compress(df)
<span class="go">448 ms ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [9]: </span><span class="o">%</span><span class="k">timeit</span> test_csv_write(df)
<span class="go">3.66 s ± 26.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [10]: </span><span class="o">%</span><span class="k">timeit</span> test_feather_write(df)
<span class="go">9.75 ms ± 117 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)</span>

<span class="gp">In [11]: </span><span class="o">%</span><span class="k">timeit</span> test_pickle_write(df)
<span class="go">30.1 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [12]: </span><span class="o">%</span><span class="k">timeit</span> test_pickle_write_compress(df)
<span class="go">4.29 s ± 15.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [13]: </span><span class="o">%</span><span class="k">timeit</span> test_parquet_write(df)
<span class="go">67.6 ms ± 706 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>
</pre>
</div>
</div>

<p>When reading, the top three functions in terms of speed are <code>test_feather_read</span></code>, <code>test_pickle_read</span></code> and
<code>test_hdf_fixed_read</span></code>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell304"><span></span><span class="gp">In [14]: </span><span class="o">%</span><span class="k">timeit</span> test_sql_read()
<span class="go">1.77 s ± 17.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [15]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_fixed_read()
<span class="go">19.4 ms ± 436 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [16]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_fixed_read_compress()
<span class="go">19.5 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [17]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_table_read()
<span class="go">38.6 ms ± 857 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [18]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_table_read_compress()
<span class="go">38.8 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [19]: </span><span class="o">%</span><span class="k">timeit</span> test_csv_read()
<span class="go">452 ms ± 9.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [20]: </span><span class="o">%</span><span class="k">timeit</span> test_feather_read()
<span class="go">12.4 ms ± 99.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)</span>

<span class="gp">In [21]: </span><span class="o">%</span><span class="k">timeit</span> test_pickle_read()
<span class="go">18.4 ms ± 191 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)</span>

<span class="gp">In [22]: </span><span class="o">%</span><span class="k">timeit</span> test_pickle_read_compress()
<span class="go">915 ms ± 7.48 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [23]: </span><span class="o">%</span><span class="k">timeit</span> test_parquet_read()
<span class="go">24.4 ms ± 146 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>
</pre><p>When reading, the top three functions in terms of speed are <code>test_feather_read</span></code>, <code>test_pickle_read</span></code> and
<code>test_hdf_fixed_read</span></code>.</p>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell304"><span></span><span class="gp">In [14]: </span><span class="o">%</span><span class="k">timeit</span> test_sql_read()
<span class="go">1.77 s ± 17.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [15]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_fixed_read()
<span class="go">19.4 ms ± 436 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [16]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_fixed_read_compress()
<span class="go">19.5 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [17]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_table_read()
<span class="go">38.6 ms ± 857 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [18]: </span><span class="o">%</span><span class="k">timeit</span> test_hdf_table_read_compress()
<span class="go">38.8 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>

<span class="gp">In [19]: </span><span class="o">%</span><span class="k">timeit</span> test_csv_read()
<span class="go">452 ms ± 9.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [20]: </span><span class="o">%</span><span class="k">timeit</span> test_feather_read()
<span class="go">12.4 ms ± 99.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)</span>

<span class="gp">In [21]: </span><span class="o">%</span><span class="k">timeit</span> test_pickle_read()
<span class="go">18.4 ms ± 191 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)</span>

<span class="gp">In [22]: </span><span class="o">%</span><span class="k">timeit</span> test_pickle_read_compress()
<span class="go">915 ms ± 7.48 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)</span>

<span class="gp">In [23]: </span><span class="o">%</span><span class="k">timeit</span> test_parquet_read()
<span class="go">24.4 ms ± 146 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)</span>
</pre>
</div>
</div>

<p>The files <code>test.pkl.compress</span></code>, <code>test.parquet</span></code> and <code>test.feather</span></code> took the least space on disk (in bytes).</p>
<div class="highlight-none notranslate"><div class="highlight"><pre id="codecell305"><span></span>29519500 Oct 10 06:45 test.csv
16000248 Oct 10 06:45 test.feather
8281983  Oct 10 06:49 test.parquet
16000857 Oct 10 06:47 test.pkl
7552144  Oct 10 06:48 test.pkl.compress
34816000 Oct 10 06:42 test.sql
24009288 Oct 10 06:43 test_fixed.hdf
24009288 Oct 10 06:43 test_fixed_compress.hdf
24458940 Oct 10 06:44 test_table.hdf
24458940 Oct 10 06:44 test_table_compress.hdf
</pre>
</div>
</div>