<h1>Merge, join, concatenate and compare</h1>

<p>pandas provides various methods for combining and comparing <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>.</p>

<ul class="simple">

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a>: Merge multiple <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects along a shared index or column</p></li>

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join" title="pandas.DataFrame.join"><code>DataFrame.join()</code></a>: Merge multiple <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects along the columns</p></li>

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>DataFrame.combine_first()</code></a>: Update missing values with non-missing values in the same location</p></li>

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge.html#pandas.merge" title="pandas.merge"><code>merge()</code></a>: Combine two <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects with SQL-style joining</p></li>

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_ordered.html#pandas.merge_ordered" title="pandas.merge_ordered"><code>merge_ordered()</code></a>: Combine two <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects along an ordered axis</p></li>

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html#pandas.merge_asof" title="pandas.merge_asof"><code>merge_asof()</code></a>: Combine two <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects by near instead of exact matching keys</p></li>

<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.compare.html#pandas.Series.compare" title="pandas.Series.compare"><code>Series.compare()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.compare.html#pandas.DataFrame.compare" title="pandas.DataFrame.compare"><code>DataFrame.compare()</code></a>: Show differences in values between two <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects</p></li>

</ul>

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a></h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a> function concatenates an arbitrary amount of <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects along an axis while performing optional set logic (union or intersection) of the indexes on the other axes.
Like <code>numpy.concatenate</code>, <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a> takes a list or dict of homogeneously-typed objects and concatenates them.</p>

In [1]:
import pandas as pd

In [22]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A2"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

In [23]:
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

In [24]:
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

In [25]:
frames = [df1, df2, df3]

In [26]:
result = pd.concat(frames)

In [27]:
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A2   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

<img src="https://pandas.pydata.org/docs/_images/merging_concat_basic.png">

<div class="alert alert-block alert-info">

<p>Note</p>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a> makes a full copy of the data, and iteratively reusing <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a> can create unnecessary copies.
Collect all <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> objects in a list before using <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a>.</p>

<pre>frames = [process_your_file(f) for f in files]
result = pd.concat(frames)</pre>

</div>

<div class="alert alert-block alert-info">

<p>Note</p>

<p>When concatenating <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> with named axes, pandas will attempt to preserve these index/column names whenever possible.
In the case where all inputs share a common name, this name will be assigned to the result.
When the input names do not all agree, the result will be unnamed.
The same is true for <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a>, but the logic is applied separately on a level-by-level basis.</p>

</div>

## <h3>Joining logic of the resulting axis</h3>

<p>The <code>join</code> keyword specifies how to handle axis values that don’t exist in the first <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>.</p>

<p><code>join='outer'</code> takes the union of all axis values</p>

In [28]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[2, 3, 6, 7],
)

In [10]:
result = pd.concat([df1, df4], axis=1)

In [11]:
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A2   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

<img src="https://pandas.pydata.org/docs/_images/merging_concat_axis1.png">

<p><code>join='inner'</code> takes the intersection of the axis values</p>

In [12]:
result = pd.concat([df1, df4], axis=1, join="inner")

In [13]:
result

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A2  B3  C3  D3  B3  D3  F3

<img src="https://pandas.pydata.org/docs/_images/merging_concat_axis1_inner.png">

<p>To perform an effective “left” join using the <em>exact index</em> from the original <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>, result can be reindexed.</p>

In [14]:
result = pd.concat([df1, df4], axis=1).reindex(df1.index)

In [15]:
result

    A   B   C   D    B    D    F
0  A0  B0  C0  D0  NaN  NaN  NaN
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2   B2   D2   F2
3  A2  B3  C3  D3   B3   D3   F3

<img src="https://pandas.pydata.org/docs/_images/merging_concat_axis1_join_axes.png">

## <h3>Ignoring indexes on the concatenation axis</h3>

<p>For <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects which don’t have a meaningful index, the <code>ignore_index</code>
ignores overlapping indexes.</p>

In [19]:
result = pd.concat([df1, df4], ignore_index=True, sort=False)

In [20]:
result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A2  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

<img src="https://pandas.pydata.org/docs/_images/merging_concat_ignore_index.png">

## <h3>Concatenating <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> together</h3>

<p>You can concatenate a mix of <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects.
The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> will be transformed to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> with the column name as
the name of the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>.</p>

In [30]:
s1 = pd.Series(["X0", "X1", "X2", "X3"], name="X")

In [31]:
result = pd.concat([df1, s1], axis=1)

In [32]:
result

    A   B   C   D   X
0  A0  B0  C0  D0  X0
1  A1  B1  C1  D1  X1
2  A2  B2  C2  D2  X2
3  A2  B3  C3  D3  X3

<img src="https://pandas.pydata.org/docs/_images/merging_concat_mixed_ndim.png">

<p>Unnamed <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> will be numbered consecutively.</p>

In [34]:
s2 = pd.Series(["_0", "_1", "_2", "_3"])

In [35]:
result = pd.concat([df1, s2, s2, s2], axis=1)

In [36]:
result

    A   B   C   D   0   1   2
0  A0  B0  C0  D0  _0  _0  _0
1  A1  B1  C1  D1  _1  _1  _1
2  A2  B2  C2  D2  _2  _2  _2
3  A2  B3  C3  D3  _3  _3  _3

<img src="https://pandas.pydata.org/docs/_images/merging_concat_unnamed_series.png">

<p><code>ignore_index=True</code> will drop all name references.</p>

In [37]:
result = pd.concat([df1, s1], axis=1, ignore_index=True)

In [38]:
result

    0   1   2   3   4
0  A0  B0  C0  D0  X0
1  A1  B1  C1  D1  X1
2  A2  B2  C2  D2  X2
3  A2  B3  C3  D3  X3

<img src="https://pandas.pydata.org/docs/_images/merging_concat_series_ignore_index.png">

## <h3>Resulting <code>keys</code></h3>

<p>The <code>keys</code> argument adds another axis level to the resulting index or column (creating a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a>) associate specific keys with each original <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>.</p>

In [39]:
result = pd.concat(frames, keys=["x", "y", "z"])

In [40]:
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A2   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

In [41]:
result.loc["y"]

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

<img src="https://pandas.pydata.org/docs/_images/merging_concat_keys.png">

<p>The <code>keys</code> argument cane override the column names
when creating a new <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> based on existing <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>.</p>

In [42]:
s3 = pd.Series([0, 1, 2, 3], name="foo")

In [43]:
s4 = pd.Series([0, 1, 2, 3])

In [44]:
s5 = pd.Series([0, 1, 4, 5])

In [45]:
pd.concat([s3, s4, s5], axis=1)

   foo  0  1
0    0  0  0
1    1  1  1
2    2  2  4
3    3  3  5

In [46]:
pd.concat([s3, s4, s5], axis=1, keys=["red", "blue", "yellow"])

   red  blue  yellow
0    0     0       0
1    1     1       1
2    2     2       4
3    3     3       5

<p>You can also pass a dict to <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a> in which case the dict keys will be used for the <code>keys</code> argument unless other <code>keys</code> argument is specified:</p>

In [47]:
pieces = {"x": df1, "y": df2, "z": df3}

In [48]:
result = pd.concat(pieces)

In [49]:
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A2   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

<img src="https://pandas.pydata.org/docs/_images/merging_concat_dict.png">

In [50]:
result = pd.concat(pieces, keys=["z", "y"])

In [51]:
result

        A    B    C    D
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7

<img src="https://pandas.pydata.org/docs/_images/merging_concat_dict_keys.png">
<p>The <a href="../reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a> created has levels that are constructed from the passed keys and
the index of the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> pieces:</p>

In [52]:
result.index.levels

FrozenList([['z', 'y'], [4, 5, 6, 7, 8, 9, 10, 11]])

<p><code>levels</code> argument allows specifying resulting levels associated with the <code>keys</code></p>

In [53]:
result = pd.concat(
    pieces, keys=["x", "y", "z"], levels=[["z", "y", "x", "w"]], names=["group_key"]
)

In [54]:
result

                A    B    C    D
group_key
x         0    A0   B0   C0   D0
          1    A1   B1   C1   D1
          2    A2   B2   C2   D2
          3    A2   B3   C3   D3
y         4    A4   B4   C4   D4
          5    A5   B5   C5   D5
          6    A6   B6   C6   D6
          7    A7   B7   C7   D7
z         8    A8   B8   C8   D8
          9    A9   B9   C9   D9
          10  A10  B10  C10  D10
          11  A11  B11  C11  D11

<img src="https://pandas.pydata.org/docs/_images/merging_concat_dict_keys_names.png"><img src="https://pandas.pydata.org/docs/_images/merging_concat_dict_keys_names.png">

In [55]:
result.index.levels

FrozenList([['z', 'y', 'x', 'w'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]])

## <h3>Appending rows to a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a></h3>

<p>If you have a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> that you want to append as a single row to a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>, you can convert the row into a
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> and use <a href="https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat" title="pandas.concat"><code>concat()</code></a></p>

In [56]:
s2 = pd.Series(["X0", "X1", "X2", "X3"], index=["A", "B", "C", "D"])

In [57]:
result = pd.concat([df1, s2.to_frame().T], ignore_index=True)

In [58]:
result

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A2  B3  C3  D3
4  X0  X1  X2  X3

<img src="https://pandas.pydata.org/docs/_images/merging_append_series_as_row.png">

# <h2><a href="../reference/api/pandas.merge.html#pandas.merge" title="pandas.merge"><code>merge()</code></a></h2>

<p><a href="../reference/api/pandas.merge.html#pandas.merge" title="pandas.merge"><code>merge()</code></a> performs join operations similar to relational databases like SQL.
Users who are familiar with SQL but new to pandas can reference a
<a href="../getting_started/comparison/comparison_with_sql.html#compare-with-sql-join">comparison with SQL</a>.</p>

## <h3>Merge types</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge.html#pandas.merge" title="pandas.merge"><code>merge()</code></a> implements common SQL style joining operations.</p>

<ul class="simple">

<li><p><strong>one-to-one</strong>: joining two <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects on
their indexes which must contain unique values.</p></li>

<li><p><strong>many-to-one</strong>: joining a unique index to one or
more columns in a different <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>.</p></li>

<li><p><strong>many-to-many</strong> : joining columns on columns.</p></li>

</ul>

<div class="alert alert-block alert-info">
<p>Note</p>
<p>When joining columns on columns, potentially a many-to-many join, any
indexes on the passed <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> objects <strong>will be discarded</strong>.</p>
</div>

<p>For a <strong>many-to-many</strong> join, if a key combination appears more than once in both tables, the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> will have the <strong>Cartesian product</strong> of the associated data.</p>

In [60]:
left = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

In [59]:
right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

In [61]:
result = pd.merge(left, right, on="key")

In [62]:
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

<img src="https://pandas.pydata.org/docs/_images/merging_merge_on_key.png">

<p>The <code>how</code> argument to <a href="https://pandas.pydata.org/docs/reference/api/pandas.merge.html#pandas.merge" title="pandas.merge"><code>merge()</code></a> specifies which keys are included in the resulting table.
If a key combination <strong>does not appear</strong> in
either the left or right tables, the values in the joined table will be
<code>NA</code>. Here is a summary of the <code>how</code> options and their SQL equivalent names:</p>

<table>
<colgroup>
<col style="width: 20.0%">
<col style="width: 20.0%">
<col style="width: 60.0%">
</colgroup>
<thead>
<tr><th><p>Merge method</p></th>
<th><p>SQL Join Name</p></th>
<th><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr><td><p><code>left</code></p></td>
<td><p><code>LEFT OUTER JOIN</code></p></td>
<td><p>Use keys from left frame only</p></td>
</tr>
<tr><td><p><code>right</code></p></td>
<td><p><code>RIGHT OUTER JOIN</code></p></td>
<td><p>Use keys from right frame only</p></td>
</tr>
<tr><td><p><code>outer</code></p></td>
<td><p><code>FULL OUTER JOIN</code></p></td>
<td><p>Use union of keys from both frames</p></td>
</tr>
<tr><td><p><code>inner</code></p></td>
<td><p><code>INNER JOIN</code></p></td>
<td><p>Use intersection of keys from both frames</p></td>
</tr>
<tr><td><p><code>cross</code></p></td>
<td><p><code>CROSS JOIN</code></p></td>
<td><p>Create the cartesian product of rows of both frames</p></td>
</tr>
</tbody>
</table>

In [63]:
left = pd.DataFrame(
   {
      "key1": ["K0", "K0", "K1", "K2"],
      "key2": ["K0", "K1", "K0", "K1"],
      "A": ["A0", "A1", "A2", "A3"],
      "B": ["B0", "B1", "B2", "B3"],
   }
)

In [64]:
right = pd.DataFrame(
   {
      "key1": ["K0", "K1", "K1", "K2"],
      "key2": ["K0", "K0", "K0", "K0"],
      "C": ["C0", "C1", "C2", "C3"],
      "D": ["D0", "D1", "D2", "D3"],
   }
)

In [65]:
result = pd.merge(left, right, how="left", on=["key1", "key2"])

In [66]:
result

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

<img src="https://pandas.pydata.org/docs/_images/merging_merge_on_key_left.png">

In [67]:
result = pd.merge(left, right, how="right", on=["key1", "key2"])

In [68]:
result

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

<img src="https://pandas.pydata.org/docs/_images/merging_merge_on_key_right.png">

In [69]:
result = pd.merge(left, right, how="outer", on=["key1", "key2"])

In [70]:
result

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

<img src="https://pandas.pydata.org/docs/_images/merging_merge_on_key_outer.png">

In [71]:
result = pd.merge(left, right, how="inner", on=["key1", "key2"])

In [72]:
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

<img src="https://pandas.pydata.org/docs/_images/merging_merge_on_key_inner.png">

In [73]:
result = pd.merge(left, right, how="cross")

In [74]:
result

   key1_x key2_x   A   B key1_y key2_y   C   D
0      K0     K0  A0  B0     K0     K0  C0  D0
1      K0     K0  A0  B0     K1     K0  C1  D1
2      K0     K0  A0  B0     K1     K0  C2  D2
3      K0     K0  A0  B0     K2     K0  C3  D3
4      K0     K1  A1  B1     K0     K0  C0  D0
5      K0     K1  A1  B1     K1     K0  C1  D1
6      K0     K1  A1  B1     K1     K0  C2  D2
7      K0     K1  A1  B1     K2     K0  C3  D3
8      K1     K0  A2  B2     K0     K0  C0  D0
9      K1     K0  A2  B2     K1     K0  C1  D1
10     K1     K0  A2  B2     K1     K0  C2  D2
11     K1     K0  A2  B2     K2     K0  C3  D3
12     K2     K1  A3  B3     K0     K0  C0  D0
13     K2     K1  A3  B3     K1     K0  C1  D1
14     K2     K1  A3  B3     K1     K0  C2  D2
15     K2     K1  A3  B3     K2     K0  C3  D3

<img src="https://pandas.pydata.org/docs/_images/merging_merge_cross.png">

<p>You can <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> and a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> with a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a> if the names of
the <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a> correspond to the columns from the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>.
Transform the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a> to a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> using <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.reset_index.html#pandas.Series.reset_index" title="pandas.Series.reset_index"><code>Series.reset_index()</code></a> before merging</p>

In [75]:
df = pd.DataFrame({"Let": ["A", "B", "C"], "Num": [1, 2, 3]})

In [76]:
df

  Let  Num
0   A    1
1   B    2
2   C    3

In [77]:
ser = pd.Series(
    ["a", "b", "c", "d", "e", "f"],
    index=pd.MultiIndex.from_arrays(
        [["A", "B", "C"] * 2, [1, 2, 3, 4, 5, 6]], names=["Let", "Num"]
    ),
)

In [78]:
ser

Let  Num
A    1      a
B    2      b
C    3      c
A    4      d
B    5      e
C    6      f
dtype: object

In [79]:
pd.merge(df, ser.reset_index(), on=["Let", "Num"])

  Let  Num  0
0   A    1  a
1   B    2  b
2   C    3  c

<p>Performing an outer join with duplicate join keys in <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a></p>

In [80]:
left = pd.DataFrame({"A": [1, 2], "B": [2, 2]})

In [81]:
right = pd.DataFrame({"A": [4, 5, 6], "B": [2, 2, 2]})

In [82]:
result = pd.merge(left, right, on="B", how="outer")

In [83]:
result

   A_x  B  A_y
0    1  2    4
1    1  2    5
2    1  2    6
3    2  2    4
4    2  2    5
5    2  2    6

<img src="https://pandas.pydata.org/docs/_images/merging_merge_on_key_dup.png">

<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Merging on duplicate keys significantly increase the dimensions of the result
and can cause a memory overflow.</p>
</div>

## <h3>Merge key uniqueness</h3>

<p>The <code>validate</code> argument checks whether the uniqueness of merge keys.
Key uniqueness is checked before merge operations and can protect against memory overflows and unexpected key duplication.</p>

In [84]:
left = pd.DataFrame({"A": [1, 2], "B": [1, 2]})

In [85]:
right = pd.DataFrame({"A": [4, 5, 6], "B": [2, 2, 2]})

In [86]:
result = pd.merge(left, right, on="B", how="outer", validate="one_to_one")

MergeError: Merge keys are not unique in right dataset; not a one-to-one merge

<p>If the user is aware of the duplicates in the right <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> but wants to ensure there are no duplicates in the left <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>, one can use the <code>validate='one_to_many'</code> argument instead, which will not raise an exception.</p>

In [87]:
pd.merge(left, right, on="B", how="outer", validate="one_to_many")

   A_x  B  A_y
0    1  1  NaN
1    2  2  4.0
2    2  2  5.0
3    2  2  6.0

## <h3>Merge result indicator</h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge.html#pandas.merge" title="pandas.merge"><code>merge()</code></a> accepts the argument <code>indicator</code>.
If <code>True</code>, a Categorical-type column called <code>_merge</code> will be added to the output object
that takes on values:</p>

<blockquote>
<div><table>
<thead>
<tr><th><p>Observation Origin</p></th>
<th><p><code>_merge</code> value</p></th>
</tr>
</thead>
<tbody>
<tr><td><p>Merge key only in <code>'left'</code> frame</p></td>
<td><p><code>left_only</code></p></td>
</tr>
<tr><td><p>Merge key only in <code>'right'</code> frame</p></td>
<td><p><code>right_only</code></p></td>
</tr>
<tr><td><p>Merge key in both frames</p></td>
<td><p><code>both</code></p></td>
</tr>
</tbody>
</table>
</div>
</blockquote>

In [2]:
df1 = pd.DataFrame({"col1": [0, 1], "col_left": ["a", "b"]})

In [3]:
df2 = pd.DataFrame({"col1": [1, 2, 2], "col_right": [2, 2, 2]})

In [4]:
pd.merge(df1, df2, on="col1", how="outer", indicator=True)

   col1 col_left  col_right      _merge
0     0        a        NaN   left_only
1     1        b        2.0        both
2     2      NaN        2.0  right_only
3     2      NaN        2.0  right_only

<p>A string argument to <code>indicator</code> will use the value as the name for the indicator column.</p>

In [5]:
pd.merge(df1, df2, on="col1", how="outer", indicator="indicator_column")

   col1 col_left  col_right indicator_column
0     0        a        NaN        left_only
1     1        b        2.0             both
2     2      NaN        2.0       right_only
3     2      NaN        2.0       right_only

## <h3>Overlapping value columns</h3>

<p>The merge <code>suffixes</code> argument takes a tuple of list of strings to append to overlapping column names in the input <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> to disambiguate the result
columns:</p>

In [6]:
left = pd.DataFrame({"k": ["K0", "K1", "K2"], "v": [1, 2, 3]})

In [7]:
right = pd.DataFrame({"k": ["K0", "K0", "K3"], "v": [4, 5, 6]})

In [8]:
result = pd.merge(left, right, on="k")

In [9]:
result

    k  v_x  v_y
0  K0    1    4
1  K0    1    5

<img src="https://pandas.pydata.org/docs/_images/merging_merge_overlapped.png">

In [11]:
result = pd.merge(left, right, on="k", suffixes=("_l", "_r"))

In [12]:
result

    k  v_l  v_r
0  K0    1    4
1  K0    1    5

<img src="https://pandas.pydata.org/docs/_images/merging_merge_overlapped_suffix.png">

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join" title="pandas.DataFrame.join"><code>DataFrame.join()</code></a></h2>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join" title="pandas.DataFrame.join"><code>DataFrame.join()</code></a> combines the columns of multiple, potentially differently-indexed <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> into a single result
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>.</p>

In [13]:
left = pd.DataFrame(
    {"A": ["A0", "A1", "A2"], "B": ["B0", "B1", "B2"]}, index=["K0", "K1", "K2"]
)

In [14]:
right = pd.DataFrame(
    {"C": ["C0", "C2", "C3"], "D": ["D0", "D2", "D3"]}, index=["K0", "K2", "K3"]
)

In [15]:
result = left.join(right)

In [16]:
result

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

<img src="https://pandas.pydata.org/docs/_images/merging_join.png">

In [17]:
result = left.join(right, how="outer")

In [18]:
result

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

<img src="https://pandas.pydata.org/docs/_images/merging_join_outer.png">

In [19]:
result = left.join(right, how="inner")

In [20]:
result

     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2

<img src="https://pandas.pydata.org/docs/_images/merging_join_inner.png">

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join" title="pandas.DataFrame.join"><code>DataFrame.join()</code></a> takes an optional <code>on</code> argument which may be a column or multiple column names that the passed <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> is to be aligned.</p>

In [21]:
left = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "key": ["K0", "K1", "K0", "K1"],
    }
)

In [22]:
right = pd.DataFrame({"C": ["C0", "C1"], "D": ["D0", "D1"]}, index=["K0", "K1"])

In [23]:
result = left.join(right, on="key")

In [24]:
result

    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K0  C0  D0
3  A3  B3  K1  C1  D1

<img src="https://pandas.pydata.org/docs/_images/merging_join_key_columns.png">

In [25]:
result = pd.merge(
    left, right, left_on="key", right_index=True, how="left", sort=False
)

In [26]:
result

    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K0  C0  D0
3  A3  B3  K1  C1  D1

<img src="https://pandas.pydata.org/docs/_images/merging_merge_key_columns.png">
<p id="merging-multikey-join">To join on multiple keys, the passed <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> must have a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a>:</p>

In [27]:
left = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "key1": ["K0", "K0", "K1", "K2"],
        "key2": ["K0", "K1", "K0", "K1"],
    }
)

In [28]:
index = pd.MultiIndex.from_tuples(
    [("K0", "K0"), ("K1", "K0"), ("K2", "K0"), ("K2", "K1")]
)

In [29]:
right = pd.DataFrame(
    {"C": ["C0", "C1", "C2", "C3"], "D": ["D0", "D1", "D2", "D3"]}, index=index
)

In [31]:
result = left.join(right, on=["key1", "key2"])

In [32]:
result

    A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A3  B3   K2   K1   C3   D3

<img src="https://pandas.pydata.org/docs/_images/merging_join_multikeys.png">

<p id="merging-df-inner-join">The default for <a href="../reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join" title="pandas.DataFrame.join"><code>DataFrame.join</span></code></a> is to perform a left join which uses only the keys found in the calling <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a>. Other join types can be specified with <code>how</span></code>.</p>

In [33]:
result = left.join(right, on=["key1", "key2"], how="inner")

In [34]:
result

    A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
2  A2  B2   K1   K0  C1  D1
3  A3  B3   K2   K1  C3  D3

<img src="https://pandas.pydata.org/docs/_images/merging_join_multikeys_inner.png">

## <h3>Joining a single Index to a MultiIndex</h3>
<p>You can join a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> with a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</span></code></a> to a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> with a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</span></code></a> on a level.
The <code>name</span></code> of the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index"><code>Index</span></code></a> with match the level name of the <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</span></code></a>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell67"><span></span><span class="gp">In [104]: </span><span class="n">left</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"A0"</span><span class="p">,</span> <span class="s2">"A1"</span><span class="p">,</span> <span class="s2">"A2"</span><span class="p">],</span> <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"B0"</span><span class="p">,</span> <span class="s2">"B1"</span><span class="p">,</span> <span class="s2">"B2"</span><span class="p">]},</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">Index</span><span class="p">([</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K2"</span><span class="p">],</span> <span class="n">name</span><span class="o">=</span><span class="s2">"key"</span><span class="p">),</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [105]: </span><span class="n">index</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_tuples</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[(</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"Y0"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"Y1"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K2"</span><span class="p">,</span> <span class="s2">"Y2"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K2"</span><span class="p">,</span> <span class="s2">"Y3"</span><span class="p">)],</span>
<span class="gp">   .....: </span>    <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"key"</span><span class="p">,</span> <span class="s2">"Y"</span><span class="p">],</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [106]: </span><span class="n">right</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"C"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"C0"</span><span class="p">,</span> <span class="s2">"C1"</span><span class="p">,</span> <span class="s2">"C2"</span><span class="p">,</span> <span class="s2">"C3"</span><span class="p">],</span> <span class="s2">"D"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"D0"</span><span class="p">,</span> <span class="s2">"D1"</span><span class="p">,</span> <span class="s2">"D2"</span><span class="p">,</span> <span class="s2">"D3"</span><span class="p">]},</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">index</span><span class="p">,</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [107]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">left</span><span class="o">.</span><span class="n">join</span><span class="p">(</span><span class="n">right</span><span class="p">,</span> <span class="n">how</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">)</span>

<span class="gp">In [108]: </span><span class="n">result</span>
<span class="gh">Out[108]: </span>
<span class="go">         A   B   C   D</span>
<span class="go">key Y                 </span>
<span class="go">K0  Y0  A0  B0  C0  D0</span>
<span class="go">K1  Y1  A1  B1  C1  D1</span>
<span class="go">K2  Y2  A2  B2  C2  D2</span>
<span class="go">    Y3  A2  B2  C3  D3</span>
</pre>
</div>
</div>

<img src="https://pandas.pydata.org/docs/_images/merging_join_multiindex_inner.png">

## <h3>Joining with two <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</span></code></a></h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a> of the input argument must be completely used in the join and is a subset of the indices in the left argument.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell69"><span></span><span class="gp">In [109]: </span><span class="n">leftindex</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_product</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[</span><span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"xy"</span><span class="p">),</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]],</span> <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"abc"</span><span class="p">,</span> <span class="s2">"xy"</span><span class="p">,</span> <span class="s2">"num"</span><span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [110]: </span><span class="n">left</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"v1"</span><span class="p">:</span> <span class="nb">range</span><span class="p">(</span><span class="mi">12</span><span class="p">)},</span> <span class="n">index</span><span class="o">=</span><span class="n">leftindex</span><span class="p">)</span>

<span class="gp">In [111]: </span><span class="n">left</span>
<span class="gh">Out[111]: </span>
<span class="go">            v1</span>
<span class="go">abc xy num    </span>
<span class="go">a   x  1     0</span>
<span class="go">       2     1</span>
<span class="go">    y  1     2</span>
<span class="go">       2     3</span>
<span class="go">b   x  1     4</span>
<span class="go">       2     5</span>
<span class="go">    y  1     6</span>
<span class="go">       2     7</span>
<span class="go">c   x  1     8</span>
<span class="go">       2     9</span>
<span class="go">    y  1    10</span>
<span class="go">       2    11</span>

<span class="gp">In [112]: </span><span class="n">rightindex</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_product</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[</span><span class="nb">list</span><span class="p">(</span><span class="s2">"abc"</span><span class="p">),</span> <span class="nb">list</span><span class="p">(</span><span class="s2">"xy"</span><span class="p">)],</span> <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"abc"</span><span class="p">,</span> <span class="s2">"xy"</span><span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [113]: </span><span class="n">right</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"v2"</span><span class="p">:</span> <span class="p">[</span><span class="mi">100</span> <span class="o">*</span> <span class="n">i</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">7</span><span class="p">)]},</span> <span class="n">index</span><span class="o">=</span><span class="n">rightindex</span><span class="p">)</span>

<span class="gp">In [114]: </span><span class="n">right</span>
<span class="gh">Out[114]: </span>
<span class="go">         v2</span>
<span class="go">abc xy     </span>
<span class="go">a   x   100</span>
<span class="go">    y   200</span>
<span class="go">b   x   300</span>
<span class="go">    y   400</span>
<span class="go">c   x   500</span>
<span class="go">    y   600</span>

<span class="gp">In [115]: </span><span class="n">left</span><span class="o">.</span><span class="n">join</span><span class="p">(</span><span class="n">right</span><span class="p">,</span> <span class="n">on</span><span class="o">=</span><span class="p">[</span><span class="s2">"abc"</span><span class="p">,</span> <span class="s2">"xy"</span><span class="p">],</span> <span class="n">how</span><span class="o">=</span><span class="s2">"inner"</span><span class="p">)</span>
<span class="gh">Out[115]: </span>
<span class="go">            v1   v2</span>
<span class="go">abc xy num         </span>
<span class="go">a   x  1     0  100</span>
<span class="go">       2     1  100</span>
<span class="go">    y  1     2  200</span>
<span class="go">       2     3  200</span>
<span class="go">b   x  1     4  300</span>
<span class="go">       2     5  300</span>
<span class="go">    y  1     6  400</span>
<span class="go">       2     7  400</span>
<span class="go">c   x  1     8  500</span>
<span class="go">       2     9  500</span>
<span class="go">    y  1    10  600</span>
<span class="go">       2    11  600</span>
</pre>
</div>
</div>
<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell70"><span></span><span class="gp">In [116]: </span><span class="n">leftindex</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_tuples</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[(</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"X0"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"X1"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"X2"</span><span class="p">)],</span> <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"key"</span><span class="p">,</span> <span class="s2">"X"</span><span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [117]: </span><span class="n">left</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"A0"</span><span class="p">,</span> <span class="s2">"A1"</span><span class="p">,</span> <span class="s2">"A2"</span><span class="p">],</span> <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"B0"</span><span class="p">,</span> <span class="s2">"B1"</span><span class="p">,</span> <span class="s2">"B2"</span><span class="p">]},</span> <span class="n">index</span><span class="o">=</span><span class="n">leftindex</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [118]: </span><span class="n">rightindex</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">MultiIndex</span><span class="o">.</span><span class="n">from_tuples</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[(</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"Y0"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"Y1"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K2"</span><span class="p">,</span> <span class="s2">"Y2"</span><span class="p">),</span> <span class="p">(</span><span class="s2">"K2"</span><span class="p">,</span> <span class="s2">"Y3"</span><span class="p">)],</span> <span class="n">names</span><span class="o">=</span><span class="p">[</span><span class="s2">"key"</span><span class="p">,</span> <span class="s2">"Y"</span><span class="p">]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [119]: </span><span class="n">right</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"C"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"C0"</span><span class="p">,</span> <span class="s2">"C1"</span><span class="p">,</span> <span class="s2">"C2"</span><span class="p">,</span> <span class="s2">"C3"</span><span class="p">],</span> <span class="s2">"D"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"D0"</span><span class="p">,</span> <span class="s2">"D1"</span><span class="p">,</span> <span class="s2">"D2"</span><span class="p">,</span> <span class="s2">"D3"</span><span class="p">]},</span> <span class="n">index</span><span class="o">=</span><span class="n">rightindex</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [120]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">merge</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">left</span><span class="o">.</span><span class="n">reset_index</span><span class="p">(),</span> <span class="n">right</span><span class="o">.</span><span class="n">reset_index</span><span class="p">(),</span> <span class="n">on</span><span class="o">=</span><span class="p">[</span><span class="s2">"key"</span><span class="p">],</span> <span class="n">how</span><span class="o">=</span><span class="s2">"inner"</span>
<span class="gp">   .....: </span><span class="p">)</span><span class="o">.</span><span class="n">set_index</span><span class="p">([</span><span class="s2">"key"</span><span class="p">,</span> <span class="s2">"X"</span><span class="p">,</span> <span class="s2">"Y"</span><span class="p">])</span>
<span class="gp">   .....: </span>

<span class="gp">In [121]: </span><span class="n">result</span>
<span class="gh">Out[121]: </span>
<span class="go">            A   B   C   D</span>
<span class="go">key X  Y                 </span>
<span class="go">K0  X0 Y0  A0  B0  C0  D0</span>
<span class="go">    X1 Y0  A1  B1  C0  D0</span>
<span class="go">K1  X2 Y1  A2  B2  C1  D1</span>
</pre>
</div>
</div>
<img src="https://pandas.pydata.org/docs/_images/merging_merge_two_multiindex.png">

## <h3>Merging on a combination of columns and index levels</h3>

<p>Strings passed as the <code>on</code>, <code>left_on</code>, and <code>right_on</code> parameters may refer to either column names or index level names.
This enables merging <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> instances on a combination of index levels and columns without
resetting indexes.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell72"><span></span><span class="gp">In [122]: </span><span class="n">left_index</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Index</span><span class="p">([</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K2"</span><span class="p">],</span> <span class="n">name</span><span class="o">=</span><span class="s2">"key1"</span><span class="p">)</span>

<span class="gp">In [123]: </span><span class="n">left</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"A"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"A0"</span><span class="p">,</span> <span class="s2">"A1"</span><span class="p">,</span> <span class="s2">"A2"</span><span class="p">,</span> <span class="s2">"A3"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"B"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"B0"</span><span class="p">,</span> <span class="s2">"B1"</span><span class="p">,</span> <span class="s2">"B2"</span><span class="p">,</span> <span class="s2">"B3"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"key2"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="p">},</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">left_index</span><span class="p">,</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [124]: </span><span class="n">right_index</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">Index</span><span class="p">([</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K2"</span><span class="p">,</span> <span class="s2">"K2"</span><span class="p">],</span> <span class="n">name</span><span class="o">=</span><span class="s2">"key1"</span><span class="p">)</span>

<span class="gp">In [125]: </span><span class="n">right</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"C"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"C0"</span><span class="p">,</span> <span class="s2">"C1"</span><span class="p">,</span> <span class="s2">"C2"</span><span class="p">,</span> <span class="s2">"C3"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"D"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"D0"</span><span class="p">,</span> <span class="s2">"D1"</span><span class="p">,</span> <span class="s2">"D2"</span><span class="p">,</span> <span class="s2">"D3"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"key2"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="p">},</span>
<span class="gp">   .....: </span>    <span class="n">index</span><span class="o">=</span><span class="n">right_index</span><span class="p">,</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [126]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">left</span><span class="o">.</span><span class="n">merge</span><span class="p">(</span><span class="n">right</span><span class="p">,</span> <span class="n">on</span><span class="o">=</span><span class="p">[</span><span class="s2">"key1"</span><span class="p">,</span> <span class="s2">"key2"</span><span class="p">])</span>

<span class="gp">In [127]: </span><span class="n">result</span>
<span class="gh">Out[127]: </span>
<span class="go">       A   B key2   C   D</span>
<span class="go">key1                     </span>
<span class="go">K0    A0  B0   K0  C0  D0</span>
<span class="go">K1    A2  B2   K0  C1  D1</span>
<span class="go">K2    A3  B3   K1  C3  D3</span>
</pre>
</div>
</div>

<img src="https://pandas.pydata.org/docs/_images/merge_on_index_and_column.png">
<div class="alert alert-block alert-info">
<p>Note</p>
<p>When <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> are joined on a string that matches an index level in both
arguments, the index level is preserved as an index level in the resulting
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a>.</p>
</div>
<div class="alert alert-block alert-info">
<p>Note</p>
<p>When <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> are joined using only some of the levels of a <a href="../reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</span></code></a>,
the extra levels will be dropped from the resulting join. To
preserve those levels, use <a href="../reference/api/pandas.DataFrame.reset_index.html#pandas.DataFrame.reset_index" title="pandas.DataFrame.reset_index"><code>DataFrame.reset_index()</span></code></a> on those level
names to move those levels to columns prior to the join.</p>
</div>

## <h3>Joining multiple <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a></h3>

<p>A list or tuple of <code>:class:`DataFrame`</span></code> can also be passed to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join" title="pandas.DataFrame.join"><code>join()</span></code></a>
to join them together on their indexes.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell74"><span></span><span class="gp">In [128]: </span><span class="n">right2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"v"</span><span class="p">:</span> <span class="p">[</span><span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">]},</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K2"</span><span class="p">])</span>

<span class="gp">In [129]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">left</span><span class="o">.</span><span class="n">join</span><span class="p">([</span><span class="n">right</span><span class="p">,</span> <span class="n">right2</span><span class="p">])</span>
</pre>
</div>
</div>

<img src="https://pandas.pydata.org/docs/_images/merging_join_multi_df.png">

## <h3><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>DataFrame.combine_first()</code></a></h3>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first" title="pandas.DataFrame.combine_first"><code>DataFrame.combine_first()</span></code></a> update missing values from one <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a>
with the non-missing values in another <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</span></code></a> in the corresponding
location.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell76"><span></span><span class="gp">In [130]: </span><span class="n">df1</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">[[</span><span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="mf">5.0</span><span class="p">],</span> <span class="p">[</span><span class="o">-</span><span class="mf">4.6</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">],</span> <span class="p">[</span><span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">7.0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">]]</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [131]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">([[</span><span class="o">-</span><span class="mf">42.6</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="o">-</span><span class="mf">8.2</span><span class="p">],</span> <span class="p">[</span><span class="o">-</span><span class="mf">5.0</span><span class="p">,</span> <span class="mf">1.6</span><span class="p">,</span> <span class="mi">4</span><span class="p">]],</span> <span class="n">index</span><span class="o">=</span><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">])</span>

<span class="gp">In [132]: </span><span class="n">result</span> <span class="o">=</span> <span class="n">df1</span><span class="o">.</span><span class="n">combine_first</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>

<span class="gp">In [133]: </span><span class="n">result</span>
<span class="gh">Out[133]: </span>
<span class="go">     0    1    2</span>
<span class="go">0  NaN  3.0  5.0</span>
<span class="go">1 -4.6  NaN -8.2</span>
<span class="go">2 -5.0  7.0  4.0</span>
</pre>
</div>
</div>
<img src="https://pandas.pydata.org/docs/_images/merging_combine_first.png">

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_ordered.html#pandas.merge_ordered" title="pandas.merge_ordered"><code>merge_ordered()</span></code></a></h2>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_ordered.html#pandas.merge_ordered" title="pandas.merge_ordered"><code>merge_ordered()</code></a> combines order data such as numeric or time series data with optional filling of missing data with <code>fill_method</code>.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell78"><span></span><span class="gp">In [134]: </span><span class="n">left</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span><span class="s2">"k"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"K0"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K2"</span><span class="p">],</span> <span class="s2">"lv"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">],</span> <span class="s2">"s"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"c"</span><span class="p">,</span> <span class="s2">"d"</span><span class="p">]}</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [135]: </span><span class="n">right</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">({</span><span class="s2">"k"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"K1"</span><span class="p">,</span> <span class="s2">"K2"</span><span class="p">,</span> <span class="s2">"K4"</span><span class="p">],</span> <span class="s2">"rv"</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]})</span>

<span class="gp">In [136]: </span><span class="n">pd</span><span class="o">.</span><span class="n">merge_ordered</span><span class="p">(</span><span class="n">left</span><span class="p">,</span> <span class="n">right</span><span class="p">,</span> <span class="n">fill_method</span><span class="o">=</span><span class="s2">"ffill"</span><span class="p">,</span> <span class="n">left_by</span><span class="o">=</span><span class="s2">"s"</span><span class="p">)</span>
<span class="gh">Out[136]: </span>
<span class="go">     k   lv  s   rv</span>
<span class="go">0   K0  1.0  a  NaN</span>
<span class="go">1   K1  1.0  a  1.0</span>
<span class="go">2   K2  1.0  a  2.0</span>
<span class="go">3   K4  1.0  a  3.0</span>
<span class="go">4   K1  2.0  b  1.0</span>
<span class="go">5   K2  2.0  b  2.0</span>
<span class="go">6   K4  2.0  b  3.0</span>
<span class="go">7   K1  3.0  c  1.0</span>
<span class="go">8   K2  3.0  c  2.0</span>
<span class="go">9   K4  3.0  c  3.0</span>
<span class="go">10  K1  NaN  d  1.0</span>
<span class="go">11  K2  4.0  d  2.0</span>
<span class="go">12  K4  4.0  d  3.0</span>
</pre>
</div>
</div>

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html#pandas.merge_asof" title="pandas.merge_asof"><code>merge_asof()</code></a></h2>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html#pandas.merge_asof" title="pandas.merge_asof"><code>merge_asof()</code></a> is similar to an ordered left-join except that mactches are on the nearest key rather than equal keys. For each row in the <code>left</code> <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a>, the last row in the <code>right</code> <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> are selected where the <code>on</code> key is less than the left’s key.
Both <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> must be sorted by the key.</p>

<p>Optionally an <a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html#pandas.merge_asof" title="pandas.merge_asof"><code>merge_asof()</code></a> can perform a group-wise merge by matching the
<code>by</code> key in addition to the nearest match on the <code>on</code> key.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell79"><span></span><span class="gp">In [137]: </span><span class="n">trades</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"time"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">(</span>
<span class="gp">   .....: </span>            <span class="p">[</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.023"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.038"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.048"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.048"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.048"</span><span class="p">,</span>
<span class="gp">   .....: </span>            <span class="p">]</span>
<span class="gp">   .....: </span>        <span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"ticker"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"MSFT"</span><span class="p">,</span> <span class="s2">"MSFT"</span><span class="p">,</span> <span class="s2">"GOOG"</span><span class="p">,</span> <span class="s2">"GOOG"</span><span class="p">,</span> <span class="s2">"AAPL"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"price"</span><span class="p">:</span> <span class="p">[</span><span class="mf">51.95</span><span class="p">,</span> <span class="mf">51.95</span><span class="p">,</span> <span class="mf">720.77</span><span class="p">,</span> <span class="mf">720.92</span><span class="p">,</span> <span class="mf">98.00</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"quantity"</span><span class="p">:</span> <span class="p">[</span><span class="mi">75</span><span class="p">,</span> <span class="mi">155</span><span class="p">,</span> <span class="mi">100</span><span class="p">,</span> <span class="mi">100</span><span class="p">,</span> <span class="mi">100</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="p">},</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"time"</span><span class="p">,</span> <span class="s2">"ticker"</span><span class="p">,</span> <span class="s2">"price"</span><span class="p">,</span> <span class="s2">"quantity"</span><span class="p">],</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [138]: </span><span class="n">quotes</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"time"</span><span class="p">:</span> <span class="n">pd</span><span class="o">.</span><span class="n">to_datetime</span><span class="p">(</span>
<span class="gp">   .....: </span>            <span class="p">[</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.023"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.023"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.030"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.041"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.048"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.049"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.072"</span><span class="p">,</span>
<span class="gp">   .....: </span>                <span class="s2">"20160525 13:30:00.075"</span><span class="p">,</span>
<span class="gp">   .....: </span>            <span class="p">]</span>
<span class="gp">   .....: </span>        <span class="p">),</span>
<span class="gp">   .....: </span>        <span class="s2">"ticker"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"GOOG"</span><span class="p">,</span> <span class="s2">"MSFT"</span><span class="p">,</span> <span class="s2">"MSFT"</span><span class="p">,</span> <span class="s2">"MSFT"</span><span class="p">,</span> <span class="s2">"GOOG"</span><span class="p">,</span> <span class="s2">"AAPL"</span><span class="p">,</span> <span class="s2">"GOOG"</span><span class="p">,</span> <span class="s2">"MSFT"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"bid"</span><span class="p">:</span> <span class="p">[</span><span class="mf">720.50</span><span class="p">,</span> <span class="mf">51.95</span><span class="p">,</span> <span class="mf">51.97</span><span class="p">,</span> <span class="mf">51.99</span><span class="p">,</span> <span class="mf">720.50</span><span class="p">,</span> <span class="mf">97.99</span><span class="p">,</span> <span class="mf">720.50</span><span class="p">,</span> <span class="mf">52.01</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"ask"</span><span class="p">:</span> <span class="p">[</span><span class="mf">720.93</span><span class="p">,</span> <span class="mf">51.96</span><span class="p">,</span> <span class="mf">51.98</span><span class="p">,</span> <span class="mf">52.00</span><span class="p">,</span> <span class="mf">720.93</span><span class="p">,</span> <span class="mf">98.01</span><span class="p">,</span> <span class="mf">720.88</span><span class="p">,</span> <span class="mf">52.03</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="p">},</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"time"</span><span class="p">,</span> <span class="s2">"ticker"</span><span class="p">,</span> <span class="s2">"bid"</span><span class="p">,</span> <span class="s2">"ask"</span><span class="p">],</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [139]: </span><span class="n">trades</span>
<span class="gh">Out[139]: </span>
<span class="go">                     time ticker   price  quantity</span>
<span class="go">0 2016-05-25 13:30:00.023   MSFT   51.95        75</span>
<span class="go">1 2016-05-25 13:30:00.038   MSFT   51.95       155</span>
<span class="go">2 2016-05-25 13:30:00.048   GOOG  720.77       100</span>
<span class="go">3 2016-05-25 13:30:00.048   GOOG  720.92       100</span>
<span class="go">4 2016-05-25 13:30:00.048   AAPL   98.00       100</span>

<span class="gp">In [140]: </span><span class="n">quotes</span>
<span class="gh">Out[140]: </span>
<span class="go">                     time ticker     bid     ask</span>
<span class="go">0 2016-05-25 13:30:00.023   GOOG  720.50  720.93</span>
<span class="go">1 2016-05-25 13:30:00.023   MSFT   51.95   51.96</span>
<span class="go">2 2016-05-25 13:30:00.030   MSFT   51.97   51.98</span>
<span class="go">3 2016-05-25 13:30:00.041   MSFT   51.99   52.00</span>
<span class="go">4 2016-05-25 13:30:00.048   GOOG  720.50  720.93</span>
<span class="go">5 2016-05-25 13:30:00.049   AAPL   97.99   98.01</span>
<span class="go">6 2016-05-25 13:30:00.072   GOOG  720.50  720.88</span>
<span class="go">7 2016-05-25 13:30:00.075   MSFT   52.01   52.03</span>

<span class="gp">In [141]: </span><span class="n">pd</span><span class="o">.</span><span class="n">merge_asof</span><span class="p">(</span><span class="n">trades</span><span class="p">,</span> <span class="n">quotes</span><span class="p">,</span> <span class="n">on</span><span class="o">=</span><span class="s2">"time"</span><span class="p">,</span> <span class="n">by</span><span class="o">=</span><span class="s2">"ticker"</span><span class="p">)</span>
<span class="gh">Out[141]: </span>
<span class="go">                     time ticker   price  quantity     bid     ask</span>
<span class="go">0 2016-05-25 13:30:00.023   MSFT   51.95        75   51.95   51.96</span>
<span class="go">1 2016-05-25 13:30:00.038   MSFT   51.95       155   51.97   51.98</span>
<span class="go">2 2016-05-25 13:30:00.048   GOOG  720.77       100  720.50  720.93</span>
<span class="go">3 2016-05-25 13:30:00.048   GOOG  720.92       100  720.50  720.93</span>
<span class="go">4 2016-05-25 13:30:00.048   AAPL   98.00       100     NaN     NaN</span>
</pre>
</div>
</div>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html#pandas.merge_asof"><code>merge_asof()</code></a> within <code>2ms</code> between the quote time and the trade time.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell80"><span></span><span class="gp">In [142]: </span><span class="n">pd</span><span class="o">.</span><span class="n">merge_asof</span><span class="p">(</span><span class="n">trades</span><span class="p">,</span> <span class="n">quotes</span><span class="p">,</span> <span class="n">on</span><span class="o">=</span><span class="s2">"time"</span><span class="p">,</span> <span class="n">by</span><span class="o">=</span><span class="s2">"ticker"</span><span class="p">,</span> <span class="n">tolerance</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"2ms"</span><span class="p">))</span>
<span class="gh">Out[142]: </span>
<span class="go">                     time ticker   price  quantity     bid     ask</span>
<span class="go">0 2016-05-25 13:30:00.023   MSFT   51.95        75   51.95   51.96</span>
<span class="go">1 2016-05-25 13:30:00.038   MSFT   51.95       155     NaN     NaN</span>
<span class="go">2 2016-05-25 13:30:00.048   GOOG  720.77       100  720.50  720.93</span>
<span class="go">3 2016-05-25 13:30:00.048   GOOG  720.92       100  720.50  720.93</span>
<span class="go">4 2016-05-25 13:30:00.048   AAPL   98.00       100     NaN     NaN</span>
</pre>
</div>
</div>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html#pandas.merge_asof"><code>merge_asof()</code></a> within <code>10ms</code> between the quote time and the trade time and
exclude exact matches on time.
Note that though we exclude the exact matches (of the quotes), prior quotes <strong>do</strong> propagate to that point in time.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell81"><span></span><span class="gp">In [143]: </span><span class="n">pd</span><span class="o">.</span><span class="n">merge_asof</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="n">trades</span><span class="p">,</span>
<span class="gp">   .....: </span>    <span class="n">quotes</span><span class="p">,</span>
<span class="gp">   .....: </span>    <span class="n">on</span><span class="o">=</span><span class="s2">"time"</span><span class="p">,</span>
<span class="gp">   .....: </span>    <span class="n">by</span><span class="o">=</span><span class="s2">"ticker"</span><span class="p">,</span>
<span class="gp">   .....: </span>    <span class="n">tolerance</span><span class="o">=</span><span class="n">pd</span><span class="o">.</span><span class="n">Timedelta</span><span class="p">(</span><span class="s2">"10ms"</span><span class="p">),</span>
<span class="gp">   .....: </span>    <span class="n">allow_exact_matches</span><span class="o">=</span><span class="kc">False</span><span class="p">,</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>
<span class="gh">Out[143]: </span>
<span class="go">                     time ticker   price  quantity    bid    ask</span>
<span class="go">0 2016-05-25 13:30:00.023   MSFT   51.95        75    NaN    NaN</span>
<span class="go">1 2016-05-25 13:30:00.038   MSFT   51.95       155  51.97  51.98</span>
<span class="go">2 2016-05-25 13:30:00.048   GOOG  720.77       100    NaN    NaN</span>
<span class="go">3 2016-05-25 13:30:00.048   GOOG  720.92       100    NaN    NaN</span>
<span class="go">4 2016-05-25 13:30:00.048   AAPL   98.00       100    NaN    NaN</span>
</pre>
</div>
</div>

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.compare.html#pandas.Series.compare" title="pandas.Series.compare"><code>compare()</code></a></h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.compare.html#pandas.Series.compare" title="pandas.Series.compare"><code>Series.compare()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.compare.html#pandas.DataFrame.compare" title="pandas.DataFrame.compare"><code>DataFrame.compare()</code></a> methods allow you to compare two <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series"><code>Series</code></a>, respectively, and summarize their differences.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell82"><span></span><span class="gp">In [144]: </span><span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span>
<span class="gp">   .....: </span>    <span class="p">{</span>
<span class="gp">   .....: </span>        <span class="s2">"col1"</span><span class="p">:</span> <span class="p">[</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"a"</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"col2"</span><span class="p">:</span> <span class="p">[</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="n">np</span><span class="o">.</span><span class="n">nan</span><span class="p">,</span> <span class="mf">5.0</span><span class="p">],</span>
<span class="gp">   .....: </span>        <span class="s2">"col3"</span><span class="p">:</span> <span class="p">[</span><span class="mf">1.0</span><span class="p">,</span> <span class="mf">2.0</span><span class="p">,</span> <span class="mf">3.0</span><span class="p">,</span> <span class="mf">4.0</span><span class="p">,</span> <span class="mf">5.0</span><span class="p">],</span>
<span class="gp">   .....: </span>    <span class="p">},</span>
<span class="gp">   .....: </span>    <span class="n">columns</span><span class="o">=</span><span class="p">[</span><span class="s2">"col1"</span><span class="p">,</span> <span class="s2">"col2"</span><span class="p">,</span> <span class="s2">"col3"</span><span class="p">],</span>
<span class="gp">   .....: </span><span class="p">)</span>
<span class="gp">   .....: </span>

<span class="gp">In [145]: </span><span class="n">df</span>
<span class="gh">Out[145]: </span>
<span class="go">  col1  col2  col3</span>
<span class="go">0    a   1.0   1.0</span>
<span class="go">1    a   2.0   2.0</span>
<span class="go">2    b   3.0   3.0</span>
<span class="go">3    b   NaN   4.0</span>
<span class="go">4    a   5.0   5.0</span>

<span class="gp">In [146]: </span><span class="n">df2</span> <span class="o">=</span> <span class="n">df</span><span class="o">.</span><span class="n">copy</span><span class="p">()</span>

<span class="gp">In [147]: </span><span class="n">df2</span><span class="o">.</span><span class="n">loc</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="s2">"col1"</span><span class="p">]</span> <span class="o">=</span> <span class="s2">"c"</span>

<span class="gp">In [148]: </span><span class="n">df2</span><span class="o">.</span><span class="n">loc</span><span class="p">[</span><span class="mi">2</span><span class="p">,</span> <span class="s2">"col3"</span><span class="p">]</span> <span class="o">=</span> <span class="mf">4.0</span>

<span class="gp">In [149]: </span><span class="n">df2</span>
<span class="gh">Out[149]: </span>
<span class="go">  col1  col2  col3</span>
<span class="go">0    c   1.0   1.0</span>
<span class="go">1    a   2.0   2.0</span>
<span class="go">2    b   3.0   4.0</span>
<span class="go">3    b   NaN   4.0</span>
<span class="go">4    a   5.0   5.0</span>

<span class="gp">In [150]: </span><span class="n">df</span><span class="o">.</span><span class="n">compare</span><span class="p">(</span><span class="n">df2</span><span class="p">)</span>
<span class="gh">Out[150]: </span>
<span class="go">  col1       col3      </span>
<span class="go">  self other self other</span>
<span class="go">0    a     c  NaN   NaN</span>
<span class="go">2  NaN   NaN  3.0   4.0</span>
</pre>
</div>
</div>

<p>By default, if two corresponding values are equal, they will be shown as <code>NaN</code>.
Furthermore, if all values in an entire row / column, the row / column will be omitted from the result. The remaining differences will be aligned on columns.</p>

<p>Stack the differences on rows.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell83"><span></span><span class="gp">In [151]: </span><span class="n">df</span><span class="o">.</span><span class="n">compare</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">align_axis</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="gh">Out[151]: </span>
<span class="go">        col1  col3</span>
<span class="go">0 self     a   NaN</span>
<span class="go">  other    c   NaN</span>
<span class="go">2 self   NaN   3.0</span>
<span class="go">  other  NaN   4.0</span>
</pre>
</div>
</div>

<p>Keep all original rows and columns with <code>keep_shape=True</code></p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell84"><span></span><span class="gp">In [152]: </span><span class="n">df</span><span class="o">.</span><span class="n">compare</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">keep_shape</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
<span class="gh">Out[152]: </span>
<span class="go">  col1       col2       col3      </span>
<span class="go">  self other self other self other</span>
<span class="go">0    a     c  NaN   NaN  NaN   NaN</span>
<span class="go">1  NaN   NaN  NaN   NaN  NaN   NaN</span>
<span class="go">2  NaN   NaN  NaN   NaN  3.0   4.0</span>
<span class="go">3  NaN   NaN  NaN   NaN  NaN   NaN</span>
<span class="go">4  NaN   NaN  NaN   NaN  NaN   NaN</span>
</pre>
</div>
</div>

<p>Keep all the original values even if they are equal.</p>

<div class="highlight-ipython notranslate"><div class="highlight"><pre id="codecell85"><span></span><span class="gp">In [153]: </span><span class="n">df</span><span class="o">.</span><span class="n">compare</span><span class="p">(</span><span class="n">df2</span><span class="p">,</span> <span class="n">keep_shape</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">keep_equal</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
<span class="gh">Out[153]: </span>
<span class="go">  col1       col2       col3      </span>
<span class="go">  self other self other self other</span>
<span class="go">0    a     c  1.0   1.0  1.0   1.0</span>
<span class="go">1    a     a  2.0   2.0  2.0   2.0</span>
<span class="go">2    b     b  3.0   3.0  3.0   4.0</span>
<span class="go">3    b     b  NaN   NaN  4.0   4.0</span>
<span class="go">4    a     a  5.0   5.0  5.0   5.0</span>
</pre>
</div>
</div>
</section>
</section>