# <h1>MultiIndex / advanced indexing</h1>

<p>This section covers <a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-hierarchical">indexing with a MultiIndex</a> and <a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-index-types">other advanced indexing features</a>.</p>

<p>See the <a href="https://pandas.pydata.org/docs/user_guide/indexing.html">Indexing and Selecting Data</a> for general indexing documentation.</p>

<div class="alert alert-block alert-warning">
<p>Warning</p>
<p>Whether a copy or a reference is returned for a setting operation may
depend on the context.  This is sometimes called <code>chained assignment</code> and should be avoided.
See <a href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-view-versus-copy">Returning a View versus Copy</a>.</p>
</div>

<p>See the <a href="https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-selection">cookbook</a> for some advanced strategies.</p>

## <h2>Hierarchical indexing (MultiIndex)</h2>

<p>Hierarchical / Multi-level indexing is very exciting as it opens the door to some quite sophisticated data analysis and manipulation, especially for working with higher dimensional data.
In essence, it enables you to store and manipulate data with an arbitrary number of dimensions in lower dimensional data structures like <code>Series</code> (1d) and <code>DataFrame</code> (2d).</p>

<p>In this section, we will show what exactly we mean by “hierarchical” indexing and how it integrates with all of the pandas indexing functionality described above and in prior sections.
Later, when discussing <a href="https://pandas.pydata.org/docs/user_guide/groupby.html">group by</a> and <a href="https://pandas.pydata.org/docs/user_guide/reshaping.html">pivoting and reshaping data</a>, we’ll show non-trivial applications to illustrate how it aids in structuring data for analysis.</p>

<p>See the <a href="https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-multi-index">cookbook</a> for some advanced strategies.</p>

### <h3>Creating a MultiIndex (hierarchical index) object</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a> object is the hierarchical analogue of the standard
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html" title="pandas.Index"><code>Index</code></a> object which typically stores the axis labels in pandas objects.
You can think of <code>MultiIndex</code> as an array of tuples where each tuple is unique.
A <code>MultiIndex</code> can be created from a list of arrays (using
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_arrays.html" title="pandas.MultiIndex.from_arrays"><code>MultiIndex.from_arrays()</code></a>), an array of tuples (using
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_tuples.html" title="pandas.MultiIndex.from_tuples"><code>MultiIndex.from_tuples()</code></a>), a crossed set of iterables (using
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_product.html" title="pandas.MultiIndex.from_product"><code>MultiIndex.from_product()</code></a>), or a
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> (using
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_frame.html" title="pandas.MultiIndex.from_frame"><code>MultiIndex.from_frame()</code></a>).
The <code>Index</code> constructor will attempt to return a <code>MultiIndex</code> when it is passed a list of tuples.
The following examples demonstrate different ways to initialize MultiIndexes.</p>

In [345]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 10)

In [346]:
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]

tuples = list(zip(*arrays))

In [347]:
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [348]:
index  =  pd.MultiIndex.from_tuples(tuples, names = ["first", "second"])

In [349]:
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [350]:
s = pd.Series(np.random.randn(8), index=index)

In [351]:
s

first  second
bar    one      -0.724168
       two       0.711614
baz    one       1.730830
       two       0.039974
foo    one      -0.908814
       two      -0.481283
qux    one       0.179889
       two      -0.144442
dtype: float64

<p>When you want every pairing of the elements in two iterables, it can be easier to use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_product.html" title="pandas.MultiIndex.from_product"><code>MultiIndex.from_product()</code></a> method:</p>

In [352]:
iterables  =  [["bar", "baz", "foo", "qux" ], ["one", "two"]]

In [353]:
pd.MultiIndex.from_product(iterables, names=["first", "second"])

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

<p>You can also construct a <code>MultiIndex</code> from a <code>DataFrame</code> directly, using the method
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_frame.html" title="pandas.MultiIndex.from_frame"><code>MultiIndex.from_frame()</code></a>.
This is a complementary method to
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.to_frame.html" title="pandas.MultiIndex.to_frame"><code>MultiIndex.to_frame()</code></a>.</p>

In [354]:
df = pd.DataFrame(
    [["bar", "one"], ["bar", "two"], ["foo", "one"], ["foo", "two"]],
    columns=["first", "second"],
)

In [355]:
pd.MultiIndex.from_frame(df)

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('foo', 'one'),
            ('foo', 'two')],
           names=['first', 'second'])

<p>As a convenience, you can pass a list of arrays directly into <code>Series</code> or <code>DataFrame</code> to construct a <code>MultiIndex</code> automatically:</p>

In [356]:
arrays = [
    np.array(["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"]),
    np.array(["one", "two", "one", "two", "one", "two", "one", "two"]),
]

In [357]:
s = pd.Series(np.random.randn(8), index=arrays)

In [358]:
s

bar  one    0.011554
     two   -0.178596
baz  one    1.268582
     two    0.379947
foo  one   -0.181178
     two   -1.082725
qux  one    0.317221
     two   -0.039436
dtype: float64

In [359]:
df = pd.DataFrame(np.random.randn(8, 4), index=arrays)

In [360]:
df

                0         1         2         3
bar one -1.177901 -0.192077 -0.888372  0.681803
    two  0.594461  0.483519  2.418202  1.156949
baz one -1.129119  1.384867  1.073067 -0.861160
    two -1.072284  0.039071  0.269467  0.934607
foo one  2.495332 -1.161049 -1.181604  1.249451
    two -1.003180 -0.600530 -0.807518 -1.186071
qux one  1.143083  0.510748  0.748054  1.488531
    two -0.248832  0.169143 -0.168249  0.809027

<p>All of the <code>MultiIndex</code> constructors accept a <code>names</code> argument which stores string names for the levels themselves.
If no names are provided, <code>None</code> will be assigned:</p>

In [361]:
df.index.names

FrozenList([None, None])

<p>This index can back any axis of a pandas object, and the number of <strong>levels</strong> of the index is up to you:</p>

In [362]:
df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)

In [363]:
df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one
A       0.609851  1.304945 -1.131188  1.115425  0.745517  0.380439  0.163036
B      -1.138830  0.794615  0.105299 -0.152390  1.202336  1.241468  0.513058
C       0.314071 -1.386102 -0.805950 -0.817007  0.884211  0.090438 -0.995132

first
second       two
A      -0.143500
B       2.106628
C      -0.573703

In [364]:
pd.DataFrame(np.random.randn(6, 6), index=index[:6], columns=index[:6])

first              bar                 baz                 foo
second             one       two       one       two       one       two
first second
bar   one     1.149523 -1.089009 -2.315177  0.602318 -0.176243  1.227322
      two    -0.864867  0.762602 -0.052139 -1.891836 -0.400689 -0.480164
baz   one    -0.105059  1.509699  0.452284 -0.155169 -0.827132  2.981501
      two     0.866635 -1.783800  0.116942  1.230800 -0.774616  1.517824
foo   one     0.579008  1.057721  0.239492  0.926737  1.206787 -0.014996
      two    -0.270099  0.095850 -1.097012  2.033169  0.059637 -0.510249

<p>We’ve “sparsified” the higher levels of the indexes to make the console output a bit easier on the eyes.
Note that how the index is displayed can be controlled using the
<code>multi_sparse</code> option in <code>pandas.set_options()</code>:</p>

In [365]:
with pd.option_context("display.multi_sparse", False):
    df

<p>It’s worth keeping in mind that there’s nothing preventing you from using tuples as atomic labels on an axis:</p>

In [366]:
pd.Series(np.random.randn(8), index=tuples)

(bar, one)    0.254051
(bar, two)   -0.357498
(baz, one)    0.804463
(baz, two)    2.443177
(foo, one)    0.451622
(foo, two)    0.576661
(qux, one)    1.518532
(qux, two)    0.895661
dtype: float64

<p>The reason that the <code>MultiIndex</code> matters is that it can allow you to do grouping, selection, and reshaping operations as we will describe below and in subsequent areas of the documentation.
As you will see in later sections, you can find yourself working with hierarchically-indexed data without creating a <code>MultiIndex</code> explicitly yourself.
However, when loading data from a file, you may wish to generate your own <code>MultiIndex</code> when preparing the data set.</p>

## <h3>Reconstructing the level labels</h3>

<p>The method <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.get_level_values.html" title="pandas.MultiIndex.get_level_values"><code>get_level_values()</code></a> will return a vector of the labels for each location at a particular level:</p>

In [367]:
index.get_level_values(0)

Index(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

In [368]:
index.get_level_values("second")

Index(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'], dtype='object', name='second')

## <h3>Basic indexing on axis with MultiIndex</h3>

<p>One of the important features of hierarchical indexing is that you can select data by a “partial” label identifying a subgroup in the data. <strong>Partial</strong> selection “drops” levels of the hierarchical index in the result in a completely analogous way to selecting a column in a regular DataFrame:</p>

In [369]:
df["bar"]

second       one       two
A       0.609851  1.304945
B      -1.138830  0.794615
C       0.314071 -1.386102

In [370]:
df["bar", "one"]

A    0.609851
B   -1.138830
C    0.314071
Name: (bar, one), dtype: float64

In [371]:
df["bar"]["one"]

A    0.609851
B   -1.138830
C    0.314071
Name: one, dtype: float64

In [372]:
s["qux"]

one    0.317221
two   -0.039436
dtype: float64

<p>See <a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-xs">Cross-section with hierarchical index</a> for how to select on a deeper level.</p>

## <h3>Defined levels</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a> keeps all the defined levels of an index, even if they are not actually used. When slicing an index, you may notice this. For example:</p>

In [373]:
df.columns.levels  # original MultiIndex

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

In [374]:
df[["foo","qux"]].columns.levels  # sliced

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

<p>This is done to avoid a recomputation of the levels in order to make slicing highly performant. If you want to see only the used levels, you can use the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.get_level_values.html" title="pandas.MultiIndex.get_level_values"><code>get_level_values()</code></a> method.</p>

In [375]:
df[["foo", "qux"]].columns.to_numpy()

array([('foo', 'one'), ('foo', 'two'), ('qux', 'one'), ('qux', 'two')],
      dtype=object)

In [376]:
# for a specific level
df[["foo", "qux"]].columns.get_level_values(0)

Index(['foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

<p>To reconstruct the <code>MultiIndex</code> with only the used levels, the <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.remove_unused_levels.html" title="pandas.MultiIndex.remove_unused_levels"><code>remove_unused_levels()</code></a> method may be used.</p>

In [377]:
new_mi = df[["foo", "qux"]].columns.remove_unused_levels()

In [378]:
new_mi.levels

FrozenList([['foo', 'qux'], ['one', 'two']])

## <h3>Data alignment and using <code>reindex</code></h3>

<p>Operations between differently-indexed objects having <code>MultiIndex</code> on the axes will work as you expect; data alignment will work the same as an Index of tuples:</p>

In [379]:
s + s[:-2]

bar  one    0.023108
     two   -0.357191
baz  one    2.537163
     two    0.759894
foo  one   -0.362355
     two   -2.165450
qux  one         NaN
     two         NaN
dtype: float64

In [380]:
s + s[::2]

bar  one    0.023108
     two         NaN
baz  one    2.537163
     two         NaN
foo  one   -0.362355
     two         NaN
qux  one    0.634443
     two         NaN
dtype: float64

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html" title="pandas.DataFrame.reindex"><code>reindex()</code></a> method of <code>Series</code>/<code>DataFrames</code> can be called with another <code>MultiIndex</code>, or even a list or array of tuples:</p>

In [381]:
s.reindex(index[:3])

first  second
bar    one       0.011554
       two      -0.178596
baz    one       1.268582
dtype: float64

In [382]:
s.reindex([("foo", "two"), ("bar", "one"), ("qux", "one"), ("baz", "one")])

foo  two   -1.082725
bar  one    0.011554
qux  one    0.317221
baz  one    1.268582
dtype: float64

# <h2>Advanced indexing with hierarchical index</h2>

<p>Syntactically integrating <code>MultiIndex</code> in advanced indexing with <code>.loc</code> is a bit challenging, but we’ve made every effort to do so. In general, MultiIndex keys take the form of tuples. For example, the following works as you would expect:</p>

In [383]:
df = df.T

In [384]:
df

                     A         B         C
first second
bar   one     0.609851 -1.138830  0.314071
      two     1.304945  0.794615 -1.386102
baz   one    -1.131188  0.105299 -0.805950
      two     1.115425 -0.152390 -0.817007
foo   one     0.745517  1.202336  0.884211
      two     0.380439  1.241468  0.090438
qux   one     0.163036  0.513058 -0.995132
      two    -0.143500  2.106628 -0.573703

In [385]:
df.loc[("bar", "two")]

A    1.304945
B    0.794615
C   -1.386102
Name: (bar, two), dtype: float64

<p>Note that <code>df.loc['bar', 'two']</code> would also work in this example, but this shorthand notation can lead to ambiguity in general.</p>

<p>If you also want to index a specific column with <code>.loc</code>, you must use a tuple like this:</p>

In [386]:
df.loc[("bar", "two"), "A"]

1.3049452881285832

<p>You don’t have to specify all levels of the <code>MultiIndex</code> by passing only the first elements of the tuple. For example, you can use “partial” indexing to get all elements with <code>bar</code> in the first level as follows:</p>

In [387]:
df.loc["bar"]

               A         B         C
second
one     0.609851 -1.138830  0.314071
two     1.304945  0.794615 -1.386102

<p>This is a shortcut for the slightly more verbose notation <code>df.loc[('bar',),]</code> (equivalent to <code>df.loc['bar',]</code> in this example).</p>

<p>“Partial” slicing also works quite nicely.</p>

In [388]:
df.loc["baz":"foo"]

                     A         B         C
first second
baz   one    -1.131188  0.105299 -0.805950
      two     1.115425 -0.152390 -0.817007
foo   one     0.745517  1.202336  0.884211
      two     0.380439  1.241468  0.090438

<p>You can slice with a ‘range’ of values, by providing a slice of tuples.</p>

In [389]:
df.loc[("baz", "two"):("qux", "one")]

                     A         B         C
first second
baz   two     1.115425 -0.152390 -0.817007
foo   one     0.745517  1.202336  0.884211
      two     0.380439  1.241468  0.090438
qux   one     0.163036  0.513058 -0.995132

In [390]:
df.loc[("baz", "two"):"foo"]

                     A         B         C
first second
baz   two     1.115425 -0.152390 -0.817007
foo   one     0.745517  1.202336  0.884211
      two     0.380439  1.241468  0.090438

<p>Passing a list of labels or tuples works similar to reindexing:</p>

In [391]:
df.loc[[("bar", "two"), ("qux", "one")]]

                     A         B         C
first second
bar   two     1.304945  0.794615 -1.386102
qux   one     0.163036  0.513058 -0.995132

<div class="alert alert-block alert-info">
<p>Note</p>
<p>It is important to note that tuples and lists are not treated identically in pandas when it comes to indexing. Whereas a tuple is interpreted as one multi-level key, a list is used to specify several keys. Or in other words, tuples go horizontally (traversing levels), lists go vertically (scanning levels).</p>
</div>

<p>Importantly, a list of tuples indexes several complete <code>MultiIndex</code> keys, whereas a tuple of lists refer to several values within a level:</p>

In [392]:
s = pd.Series(
    [1, 2, 3, 4, 5, 6],
    index=pd.MultiIndex.from_product([["A", "B"], ["c", "d", "e"]]),
)

In [393]:
s.loc[[("A", "c"), ("B", "d")]]  # list of tuples

A  c    1
B  d    5
dtype: int64

In [394]:
s.loc[(["A", "B"], ["c", "d"])]  # tuple of lists

A  c    1
   d    2
B  c    4
   d    5
dtype: int64

## <h3>Using slicers</h3>

<p>You can slice a <code>MultiIndex</code> by providing multiple indexers.</p>

<p>You can provide any of the selectors as if you are indexing by label, see
<a href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-label">Selection by Label</a>, including slices, lists of labels, labels, and boolean indexers.</p>

<p>You can use <code>slice(None)</code> to select all the contents of <em>that</em> level. You do not need to specify all the <em>deeper</em> levels, they will be implied as <code>slice(None)</code>.</p>

<p>As usual, <strong>both sides</strong> of the slicers are included as this is label indexing.</p>

<div class="alert alert-block alert-warning">
<p>Warning</p>
<p>You should specify all axes in the <code>.loc</code> specifier, meaning the indexer for the <strong>index</strong> and for the <strong>columns</strong>. There are some ambiguous cases where the passed indexer could be misinterpreted as indexing <em>both</em> axes, rather than into say the <code>MultiIndex</code> for the rows.</p>
    
<p>You should do this:</p>

<pre>df.loc[(slice("A1", "A3"), ...), :]  # noqa: E999
</pre>

<p>You should <strong>not</strong> do this:</p>

<pre>df.loc[(slice("A1", "A3"), ...)]  # noqa: E999
</pre>

In [395]:
def mklbl(prefix, n):
    return ["%s%s" % (prefix, i) for i in range(n)]

In [396]:
miindex = pd.MultiIndex.from_product(
    [mklbl("A", 4), mklbl("B", 2), mklbl("C", 4), mklbl("D", 2)]
)

In [397]:
micolumns = pd.MultiIndex.from_tuples(
    [("a", "foo"), ("a", "bar"), ("b", "foo"), ("b", "bah")], names=["lvl0", "lvl1"]
)

In [398]:
dfmi = (
    pd.DataFrame(
        np.arange(len(miindex) * len(micolumns)).reshape(
            (len(miindex), len(micolumns))
        ),
        index=miindex,
        columns=micolumns,
    )
    .sort_index()
    .sort_index(axis=1)
)

In [399]:
dfmi

lvl0           a         b
lvl1         bar  foo  bah  foo
A0 B0 C0 D0    1    0    3    2
         D1    5    4    7    6
      C1 D0    9    8   11   10
         D1   13   12   15   14
      C2 D0   17   16   19   18
...          ...  ...  ...  ...
A3 B1 C1 D1  237  236  239  238
      C2 D0  241  240  243  242
         D1  245  244  247  246
      C3 D0  249  248  251  250
         D1  253  252  255  254

[64 rows x 4 columns]

<p>Basic MultiIndex slicing using slices, lists, and labels.</p>

In [400]:
dfmi.loc[(slice("A1", "A3"), slice(None), ["C1", "C3"]), :]

lvl0           a         b
lvl1         bar  foo  bah  foo
A1 B0 C1 D0   73   72   75   74
         D1   77   76   79   78
      C3 D0   89   88   91   90
         D1   93   92   95   94
   B1 C1 D0  105  104  107  106
...          ...  ...  ...  ...
A3 B0 C3 D1  221  220  223  222
   B1 C1 D0  233  232  235  234
         D1  237  236  239  238
      C3 D0  249  248  251  250
         D1  253  252  255  254

[24 rows x 4 columns]

<p>You can use <a href="https://pandas.pydata.org/docs/reference/api/pandas.IndexSlice.html" title="pandas.IndexSlice"><code>pandas.IndexSlice</code></a> to facilitate a more natural syntax using <code>:</code>, rather than using <code>slice(None)</code>.</p>

In [401]:
idx = pd.IndexSlice

In [402]:
dfmi.loc[idx[:, :, ["C1", "C3"]], idx[:, "foo"]]

lvl0           a    b
lvl1         foo  foo
A0 B0 C1 D0    8   10
         D1   12   14
      C3 D0   24   26
         D1   28   30
   B1 C1 D0   40   42
...          ...  ...
A3 B0 C3 D1  220  222
   B1 C1 D0  232  234
         D1  236  238
      C3 D0  248  250
         D1  252  254

[32 rows x 2 columns]

<p>It is possible to perform quite complicated selections using this method on multiple axes at the same time.</p>

In [403]:
dfmi.loc["A1", (slice(None), "foo")]

lvl0        a    b
lvl1      foo  foo
B0 C0 D0   64   66
      D1   68   70
   C1 D0   72   74
      D1   76   78
   C2 D0   80   82
...       ...  ...
B1 C1 D1  108  110
   C2 D0  112  114
      D1  116  118
   C3 D0  120  122
      D1  124  126

[16 rows x 2 columns]

In [404]:
dfmi.loc[idx[:, :, ["C1", "C3"]], idx[:, "foo"]]

lvl0           a    b
lvl1         foo  foo
A0 B0 C1 D0    8   10
         D1   12   14
      C3 D0   24   26
         D1   28   30
   B1 C1 D0   40   42
...          ...  ...
A3 B0 C3 D1  220  222
   B1 C1 D0  232  234
         D1  236  238
      C3 D0  248  250
         D1  252  254

[32 rows x 2 columns]

<p>Using a boolean indexer you can provide selection related to the <em>values</em>.</p>

In [405]:
mask = dfmi[("a", "foo")] > 200

In [406]:
dfmi.loc[idx[mask, :, ["C1", "C3"]], idx[:, "foo"]]

lvl0           a    b
lvl1         foo  foo
A3 B0 C1 D1  204  206
      C3 D0  216  218
         D1  220  222
   B1 C1 D0  232  234
         D1  236  238
      C3 D0  248  250
         D1  252  254

<p>You can also specify the <code>axis</code> argument to <code>.loc</code> to interpret the passed slicers on a single axis.</p>

In [407]:
dfmi.loc(axis=0)[:, :, ["C1", "C3"]]

lvl0           a         b
lvl1         bar  foo  bah  foo
A0 B0 C1 D0    9    8   11   10
         D1   13   12   15   14
      C3 D0   25   24   27   26
         D1   29   28   31   30
   B1 C1 D0   41   40   43   42
...          ...  ...  ...  ...
A3 B0 C3 D1  221  220  223  222
   B1 C1 D0  233  232  235  234
         D1  237  236  239  238
      C3 D0  249  248  251  250
         D1  253  252  255  254

[32 rows x 4 columns]

<p>Furthermore, you can <em>set</em> the values using the following methods.</p>

In [408]:
df2 = dfmi.copy()

In [409]:
df2.loc(axis=0)[:, :, ["C1", "C3"]] = -10

In [410]:
df2

lvl0           a         b
lvl1         bar  foo  bah  foo
A0 B0 C0 D0    1    0    3    2
         D1    5    4    7    6
      C1 D0  -10  -10  -10  -10
         D1  -10  -10  -10  -10
      C2 D0   17   16   19   18
...          ...  ...  ...  ...
A3 B1 C1 D1  -10  -10  -10  -10
      C2 D0  241  240  243  242
         D1  245  244  247  246
      C3 D0  -10  -10  -10  -10
         D1  -10  -10  -10  -10

[64 rows x 4 columns]

<p>You can use a right-hand-side of an alignable object as well.</p>

In [411]:
df2 = dfmi.copy()

In [412]:
df2.loc[idx[:, :, ["C1", "C3"]], :] = df2 * 1000

In [413]:
df2

lvl0              a               b
lvl1            bar     foo     bah     foo
A0 B0 C0 D0       1       0       3       2
         D1       5       4       7       6
      C1 D0    9000    8000   11000   10000
         D1   13000   12000   15000   14000
      C2 D0      17      16      19      18
...             ...     ...     ...     ...
A3 B1 C1 D1  237000  236000  239000  238000
      C2 D0     241     240     243     242
         D1     245     244     247     246
      C3 D0  249000  248000  251000  250000
         D1  253000  252000  255000  254000

[64 rows x 4 columns]

## <h3>Cross-section</h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.xs.html" title="pandas.DataFrame.xs"><code>xs()</code></a> method of <code>DataFrame</code> additionally takes a level argument to make selecting data at a particular level of a <code>MultiIndex</code> easier.</p>

In [414]:
df

                     A         B         C
first second
bar   one     0.609851 -1.138830  0.314071
      two     1.304945  0.794615 -1.386102
baz   one    -1.131188  0.105299 -0.805950
      two     1.115425 -0.152390 -0.817007
foo   one     0.745517  1.202336  0.884211
      two     0.380439  1.241468  0.090438
qux   one     0.163036  0.513058 -0.995132
      two    -0.143500  2.106628 -0.573703

In [415]:
df.xs("one", level="second")

              A         B         C
first
bar    0.609851 -1.138830  0.314071
baz   -1.131188  0.105299 -0.805950
foo    0.745517  1.202336  0.884211
qux    0.163036  0.513058 -0.995132

In [416]:
# using the slicers
df.loc[(slice(None), "one"), :]

                     A         B         C
first second
bar   one     0.609851 -1.138830  0.314071
baz   one    -1.131188  0.105299 -0.805950
foo   one     0.745517  1.202336  0.884211
qux   one     0.163036  0.513058 -0.995132

<p>You can also select on the columns with <code>xs</code>, by
providing the axis argument.</p>

In [417]:
df = df.T

In [418]:
df.xs("one", level="second", axis=1)

first       bar       baz       foo       qux
A      0.609851 -1.131188  0.745517  0.163036
B     -1.138830  0.105299  1.202336  0.513058
C      0.314071 -0.805950  0.884211 -0.995132

In [419]:
# using the slicers
df.loc[:, (slice(None), "one")]

first        bar       baz       foo       qux
second       one       one       one       one
A       0.609851 -1.131188  0.745517  0.163036
B      -1.138830  0.105299  1.202336  0.513058
C       0.314071 -0.805950  0.884211 -0.995132

<p><code>xs</code> also allows selection with multiple keys.</p>

In [420]:
df.xs(("one", "bar"), level=("second", "first"), axis=1)

first        bar
second       one
A       0.609851
B      -1.138830
C       0.314071

In [421]:
# using the slicers
df.loc[:, ("bar", "one")]

A    0.609851
B   -1.138830
C    0.314071
Name: (bar, one), dtype: float64

<p>You can pass <code>drop_level=False</code> to <code>xs</code> to retain the level that was selected.</p>

In [422]:
df.xs("one", level="second", axis=1, drop_level=False)

first        bar       baz       foo       qux
second       one       one       one       one
A       0.609851 -1.131188  0.745517  0.163036
B      -1.138830  0.105299  1.202336  0.513058
C       0.314071 -0.805950  0.884211 -0.995132

<p>Compare the above with the result using <code>drop_level=True</code> (the default value).</p>

In [423]:
df.xs("one", level="second", axis=1, drop_level=True)

first       bar       baz       foo       qux
A      0.609851 -1.131188  0.745517  0.163036
B     -1.138830  0.105299  1.202336  0.513058
C      0.314071 -0.805950  0.884211 -0.995132

## <h3>Advanced reindexing and alignment</h3>

<p>Using the parameter <code>level</code> in the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html" title="pandas.DataFrame.reindex"><code>reindex()</code></a> and
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.align.html" title="pandas.DataFrame.align"><code>align()</code></a> methods of pandas objects is useful to broadcast values across a level. For instance:</p>

In [424]:
midx = pd.MultiIndex(
    levels=[["zero", "one"], ["x", "y"]], codes=[[1, 1, 0, 0], [1, 0, 1, 0]]
)

In [425]:
df = pd.DataFrame(np.random.randn(4, 2), index=midx)

In [426]:
df

               0         1
one  y  1.246890  0.371150
     x  0.305516 -0.449620
zero y  0.814671  0.123189
     x -1.257426 -0.503141

In [427]:
df2 = df.groupby(level=0).mean()

In [428]:
df2

             0         1
one   0.776203 -0.039235
zero -0.221378 -0.189976

In [429]:
df2.reindex(df.index, level=0)

               0         1
one  y  0.776203 -0.039235
     x  0.776203 -0.039235
zero y -0.221378 -0.189976
     x -0.221378 -0.189976

In [430]:
# aligning
df_aligned, df2_aligned = df.align(df2, level=0)

In [431]:
df_aligned

               0         1
one  y  1.246890  0.371150
     x  0.305516 -0.449620
zero y  0.814671  0.123189
     x -1.257426 -0.503141

In [432]:
df2_aligned

               0         1
one  y  0.776203 -0.039235
     x  0.776203 -0.039235
zero y -0.221378 -0.189976
     x -0.221378 -0.189976

## <h3>Swapping levels with <code>swaplevel</code></h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.swaplevel.html" title="pandas.MultiIndex.swaplevel"><code>swaplevel()</code></a> method can switch the order of two levels:</p>

In [433]:
df[:5]

               0         1
one  y  1.246890  0.371150
     x  0.305516 -0.449620
zero y  0.814671  0.123189
     x -1.257426 -0.503141

In [434]:
df[:5].swaplevel(0, 1, axis=0)

               0         1
y one   1.246890  0.371150
x one   0.305516 -0.449620
y zero  0.814671  0.123189
x zero -1.257426 -0.503141

## <h3>Reordering levels with <code>reorder_levels</code></h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.reorder_levels.html" title="pandas.MultiIndex.reorder_levels"><code>reorder_levels()</code></a> method generalizes the <code>swaplevel</code> method, allowing you to permute the hierarchical index levels in one step:</p>

In [435]:
df[:5].reorder_levels([1, 0], axis=0)

               0         1
y one   1.246890  0.371150
x one   0.305516 -0.449620
y zero  0.814671  0.123189
x zero -1.257426 -0.503141

## <h3>Renaming names of an <code>Index</code> or <code>MultiIndex</code></h3>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html" title="pandas.DataFrame.rename"><code>rename()</code></a> method is used to rename the labels of a <code>MultiIndex</code>, and is typically used to rename the columns of a <code>DataFrame</code>.
The <code>columns</code> argument of <code>rename</code> allows a dictionary to be specified that includes only the columns you wish to rename.</p>

In [436]:
df.rename(columns={0: "col0", 1: "col1"})

            col0      col1
one  y  1.246890  0.371150
     x  0.305516 -0.449620
zero y  0.814671  0.123189
     x -1.257426 -0.503141

<p>This method can also be used to rename specific labels of the main index of the <code>DataFrame</code>.</p>

In [437]:
df.rename(index={"one": "two", "y": "z"})

               0         1
two  z  1.246890  0.371150
     x  0.305516 -0.449620
zero z  0.814671  0.123189
     x -1.257426 -0.503141

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename_axis.html" title="pandas.DataFrame.rename_axis"><code>rename_axis()</code></a> method is used to rename the name of a <code>Index</code> or <code>MultiIndex</code>. In particular, the names of the levels of a <code>MultiIndex</code> can be specified, which is useful if <code>reset_index()</code> is later used to move the values from the <code>MultiIndex</code> to a column.</p>

In [438]:
df.rename_axis(index=["abc", "def"])

                 0         1
abc  def
one  y    1.246890  0.371150
     x    0.305516 -0.449620
zero y    0.814671  0.123189
     x   -1.257426 -0.503141

<p>Note that the columns of a <code>DataFrame</code> are an index, so that using <code>rename_axis</code> with the <code>columns</code> argument will change the name of that index.</p>

In [439]:
df.rename_axis(columns="Cols").columns

RangeIndex(start=0, stop=2, step=1, name='Cols')

<p>Both <code>rename</code> and <code>rename_axis</code> support specifying a dictionary, <code>Series</code> or a mapping function to map labels/names to new values.</p>

<p>When working with an <code>Index</code> object directly, rather than via a <code>DataFrame</code>,
<a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.set_names.html" title="pandas.Index.set_names"><code>Index.set_names()</code></a> can be used to change the names.</p>

In [440]:
mi = pd.MultiIndex.from_product([[1, 2], ["a", "b"]], names=["x", "y"])

In [441]:
mi.names

FrozenList(['x', 'y'])

In [442]:
mi2 = mi.rename("new name", level=0)

In [443]:
mi2

MultiIndex([(1, 'a'),
            (1, 'b'),
            (2, 'a'),
            (2, 'b')],
           names=['new name', 'y'])

<p>You cannot set the names of the MultiIndex via a level.</p>

In [444]:
mi.levels[0].name = "name via level"

RuntimeError: Cannot set name on a level of a MultiIndex. Use 'MultiIndex.set_names' instead.

<p>Use <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.set_names.html" title="pandas.Index.set_names"><code>Index.set_names()</code></a> instead.</p>

# <h2>Sorting a <code>MultiIndex</code></h2>

<p>For <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a>-ed objects to be indexed and sliced effectively, they need to be sorted. As with any index, you can use <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html" title="pandas.DataFrame.sort_index"><code>sort_index()</code></a>.</p>

In [ ]:
import random

In [ ]:
random.shuffle(tuples)

In [ ]:
s = pd.Series(np.random.randn(8), index=pd.MultiIndex.from_tuples(tuples))

In [ ]:
s

In [ ]:
s.sort_index()

In [ ]:
s.sort_index(level=0)

In [ ]:
s.sort_index(level=1)

<p>You may also pass a level name to <code>sort_index</code> if the <code>MultiIndex</code> levels are named.</p>

In [ ]:
s.index = s.index.set_names(["L1", "L2"])

In [ ]:
s.sort_index(level="L1")

In [ ]:
s.sort_index(level="L2")

<p>On higher dimensional objects, you can sort any of the other axes by level if they have a <code>MultiIndex</code>:</p>

In [ ]:
df.T.sort_index(level=1, axis=1)

<p>Indexing will work even if the data are not sorted, but will be rather inefficient (and show a <code>PerformanceWarning</code>). It will also return a copy of the data rather than a view:</p>

In [ ]:
dfm = pd.DataFrame(
    {"jim": [0, 0, 1, 1], "joe": ["x", "x", "z", "y"], "jolie": np.random.rand(4)}
)

In [ ]:
dfm = dfm.set_index(["jim", "joe"])

In [445]:
dfm

            jolie
jim joe
0   x    0.151217
    x    0.753130
1   z    0.949623
    y    0.809055

In [446]:
dfm.loc[(1, 'z')]

/var/folders/rt/k30tjkvx04vdq1qxvtwsb47m0000gn/T/ipykernel_65937/1188037207.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  dfm.loc[(1, 'z')]

            jolie
jim joe
1   z    0.949623

<p>Furthermore, if you try to index something that is not fully lexsorted, this can raise:</p>

In [447]:
dfm.loc[(0, 'y'):(1, 'z')]

UnsortedIndexError: 'Key length (2) was greater than MultiIndex lexsort depth (1)'

<p>The <code>is_monotonic_increasing()</code> method on a <code>MultiIndex</code> shows if the index is sorted:</p>

In [ ]:
dfm.index.is_monotonic_increasing

In [ ]:
dfm = dfm.sort_index()

In [ ]:
dfm

In [ ]:
dfm.index.is_monotonic_increasing

<p>And now selection works as expected.</p>

In [ ]:
dfm.loc[(0, "y"):(1, "z")]