<h1>Reshaping and pivot tables</h1>

<p id="reshaping-reshaping">pandas provides methods for manipulating a <a https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> to alter the representation of the data for further data processing or data summarization.</p>

<ul>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot.html" title="pandas.pivot"><code>pivot()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html" title="pandas.pivot_table"><code>pivot_table()</code></a>: Group unique values within one or more discrete categories.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html" title="pandas.DataFrame.unstack"><code>unstack()</code></a>: Pivot a column or row level to the opposite axis respectively.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.melt.html" title="pandas.melt"><code>melt()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.wide_to_long.html" title="pandas.wide_to_long"><code>wide_to_long()</code></a>: Unpivot a wide <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> to a long format.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html" title="pandas.get_dummies"><code>get_dummies()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.from_dummies.html" title="pandas.from_dummies"><code>from_dummies()</code></a>: Conversions with indicator variables.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.explode.html" title="pandas.Series.explode"><code>explode()</code></a>: Convert a column of list-like values to individual rows.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html" title="pandas.crosstab"><code>crosstab()</code></a>: Calculate a cross-tabulation of multiple 1 dimensional factor arrays.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.cut.html" title="pandas.cut"><code>cut()</code></a>: Transform continuous variables to discrete, categorical values</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.factorize.html" title="pandas.factorize"><code>factorize()</code></a>: Encode 1 dimensional variables into integer labels.</p></li>
</ul>

In [343]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 10)

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot.html" title="pandas.pivot"><code>pivot()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html" title="pandas.pivot_table"><code>pivot_table()</code></a></h2>

<img src="https://pandas.pydata.org/docs/_images/reshaping_pivot.png">

## <h3><a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot.html" title="pandas.pivot"><code>pivot()</code></a></h3>

<p>Data is often stored in so-called “stacked” or “record” format. In a “record” or “wide” format, typically there is one row for each subject. In the “stacked” or “long” format there are multiple rows for each subject where applicable.</p>

In [344]:
data = {
   "value": range(12),
   "variable": ["A"] * 3 + ["B"] * 3 + ["C"] * 3 + ["D"] * 3,
   "date": pd.to_datetime(["2020-01-03", "2020-01-04", "2020-01-05"] * 4)
}

df = pd.DataFrame(data)

<p>To perform time series operations with each unique variable, a better representation would be where the <code>columns</code> are the unique variables and an <code>index</code> of dates identifies individual observations. To reshape the data into this form, we use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html" title="pandas.DataFrame.pivot"><code>DataFrame.pivot()</code></a> method (also implemented as a top level function <a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot.html" title="pandas.pivot"><code>pivot()</code></a>):</p>

In [345]:
pivoted = df.pivot(index="date", columns="variable", values="value")

In [346]:
pivoted

variable    A  B  C   D
date
2020-01-03  0  3  6   9
2020-01-04  1  4  7  10
2020-01-05  2  5  8  11

<p>If the <code>values</code> argument is omitted, and the input <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> has more than one column of values which are not used as column or index inputs to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html" title="pandas.DataFrame.pivot"><code>pivot()</code></a>, then the resulting “pivoted” <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> will have <a href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-hierarchical">hierarchical columns</a> whose topmost level indicates the respective value column:</p>

In [347]:
df["value2"] = df["value"] * 2

In [348]:
pivoted = df.pivot(index="date", columns="variable")

In [349]:
pivoted

           value           value2
variable       A  B  C   D      A   B   C   D
date
2020-01-03     0  3  6   9      0   6  12  18
2020-01-04     1  4  7  10      2   8  14  20
2020-01-05     2  5  8  11      4  10  16  22

<p>You can then select subsets from the pivoted <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a>:</p>

In [350]:
pivoted["value2"]

variable    A   B   C   D
date
2020-01-03  0   6  12  18
2020-01-04  2   8  14  20
2020-01-05  4  10  16  22

<p>Note that this returns a view on the underlying data in the case where the data are homogeneously-typed.</p>

<div class="alert alert-block alert-info">
<p class="admonition-title">Note</p>
<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot.html" title="pandas.pivot"><code>pivot()</code></a> can only handle unique rows specified by <code>index</code> and <code>columns</code>.
If you data contains duplicates, use <a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html" title="pandas.pivot_table"><code>pivot_table()</code></a>.</p>
</div>

## <h3><a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html" title="pandas.pivot_table"><code>pivot_table()</code></a></h3>

<p>While <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html" title="pandas.DataFrame.pivot"><code>pivot()</code></a> provides general purpose pivoting with various data types, pandas also provides <a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html" title="pandas.pivot_table"><code>pivot_table()</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html" title="pandas.DataFrame.pivot_table"><code>pivot_table()</code></a> for pivoting with aggregation of numeric data.</p>

<p>The function <a href="https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html" title="pandas.pivot_table"><code>pivot_table()</code></a> can be used to create spreadsheet-style pivot tables. See the <a href="cookbook.html#cookbook-pivot">cookbook</a> for some advanced strategies.</p>

In [351]:
import datetime

In [352]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 6,
        "B": ["A", "B", "C"] * 8,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 4,
        "D": np.random.randn(24),
        "E": np.random.randn(24),
        "F": [datetime.datetime(2013, i, 1) for i in range(1, 13)]
        + [datetime.datetime(2013, i, 15) for i in range(1, 13)],
    }
)

In [353]:
df

        A  B    C         D         E          F
0     one  A  foo  0.320134  0.757784 2013-01-01
1     one  B  foo  1.341963 -0.157516 2013-02-01
2     two  C  foo  1.432911 -1.272880 2013-03-01
3   three  A  bar  0.656144 -0.512447 2013-04-01
4     one  B  bar  0.426697 -0.620229 2013-05-01
..    ... ..  ...       ...       ...        ...
19  three  B  foo  1.136123 -0.642556 2013-08-15
20    one  C  foo  0.118707 -0.153915 2013-09-15
21    one  A  bar  0.750720 -0.478476 2013-10-15
22    two  B  bar -0.390268 -1.009733 2013-11-15
23  three  C  bar  0.238409 -1.851006 2013-12-15

[24 rows x 6 columns]

In [354]:
pd.pivot_table(df, values="D", index=["A", "B"], columns="C")

C             bar       foo
A     B
one   A  0.240874  0.314425
      B  0.843420  0.109912
      C -1.584080  0.343984
three A  0.109136       NaN
      B       NaN  2.069431
      C  0.579801       NaN
two   A       NaN -0.331442
      B -0.269297       NaN
      C       NaN -0.161555

In [355]:
pd.pivot_table(
    df, values=["D", "E"],
    index=["B"],
    columns=["A", "C"],
    aggfunc="sum",
)

          D                                                           E  \
A       one               three                 two                 one
C       bar       foo       bar       foo       bar       foo       bar
B
A  0.481747  0.628851  0.218272       NaN       NaN -0.662883  0.825080
B  1.686840  0.219825       NaN  4.138862 -0.538593       NaN -0.749610
C -3.168159  0.687967  1.159601       NaN       NaN -0.323110 -0.901377


A               three                 two
C       foo       bar       foo       bar       foo
B
A  1.459000 -2.302246       NaN       NaN  1.419700
B -0.450151       NaN -1.476341 -1.688301       NaN
C  0.958431 -1.735144       NaN       NaN -0.274811

<p>Also, you can use <a href="https://pandas.pydata.org/docs/reference/api/pandas.Grouper.html" title="pandas.Grouper"><code>Grouper</code></a> for <code>index</code> and <code>columns</code> keywords. For detail of <a href="https://pandas.pydata.org/docs/reference/api/pandas.Grouper.html" title="pandas.Grouper"><code>Grouper</code></a>, see <a href="https://pandas.pydata.org/docs/user_guide/groupby.html#groupby-specify">Grouping with a Grouper specification</a>.</p>

In [356]:
pd.pivot_table(df, values="D", index=pd.Grouper(freq="M", key="F"), columns="C")

C                bar       foo
F
2013-01-31       NaN  0.314425
2013-02-28       NaN  0.109912
2013-03-31       NaN -0.161555
2013-04-30  0.109136       NaN
2013-05-31  0.843420       NaN
...              ...       ...
2013-08-31       NaN  2.069431
2013-09-30       NaN  0.343984
2013-10-31  0.240874       NaN
2013-11-30 -0.269297       NaN
2013-12-31  0.579801       NaN

[12 rows x 2 columns]

<p>The result is a <a href="../reference/api/pandas.DataFrame.html#pandas.DataFrame" title="pandas.DataFrame"><code>DataFrame</code></a> potentially having a <a href="../reference/api/pandas.MultiIndex.html#pandas.MultiIndex" title="pandas.MultiIndex"><code>MultiIndex</code></a> on the index or column. If the <code>values</code> column name is not given, the pivot table will include all of the data in an additional level of hierarchy in the columns:</p>

In [357]:
pd.pivot_table(df[["A", "B", "C", "D", "E"]], index=["A", "B"], columns=["C"])

                D                   E
C             bar       foo       bar       foo
A     B
one   A  0.240874  0.314425  0.412540  0.729500
      B  0.843420  0.109912 -0.374805 -0.225075
      C -1.584080  0.343984 -0.450688  0.479216
three A  0.109136       NaN -1.151123       NaN
      B       NaN  2.069431       NaN -0.738171
      C  0.579801       NaN -0.867572       NaN
two   A       NaN -0.331442       NaN  0.709850
      B -0.269297       NaN -0.844150       NaN
      C       NaN -0.161555       NaN -0.137405

### <h4>Adding margins</h4>

<p>Passing <code>margins=True</code> to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot_table.html" title="pandas.DataFrame.pivot_table"><code>pivot_table()</code></a> will add a row and column with an <code>All</code> label with partial group aggregates across the categories on the rows and columns:</p>

In [358]:
table = df.pivot_table(
    index=["A", "B"],
    columns="C",
    values=["D", "E"],
    margins=True,
    aggfunc="std"
)

In [359]:
table

                D                             E
C             bar       foo       All       bar       foo       All
A     B
one   A  0.721031  0.008073  0.418474  1.260086  0.039999  0.750529
      B  0.589336  1.742383  1.143277  0.347081  0.095543  0.225102
      C  0.941552  0.318589  1.252391  1.755382  0.895382  1.258014
three A  0.773585       NaN  0.773585  0.903224       NaN  0.903224
      B       NaN  1.319897  1.319897       NaN  0.135219  0.135219
      C  0.482800       NaN  0.482800  1.390785       NaN  1.390785
two   A       NaN  0.236866  0.236866       NaN  0.748260  0.748260
      B  0.171080       NaN  0.171080  0.234169       NaN  0.234169
      C       NaN  2.254915  2.254915       NaN  1.605803  1.605803
All      0.953985  1.260709  1.112659  0.982849  0.826081  0.953837

<p>Additionally, you can call <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>DataFrame.stack()</code></a> to display a pivoted DataFrame as having a multi-level index:</p>

In [360]:
table.stack(future_stack=True)

                  D         E
A   B C
one A bar  0.721031  1.260086
      foo  0.008073  0.039999
      All  0.418474  0.750529
    B bar  0.589336  0.347081
      foo  1.742383  0.095543
...             ...       ...
two C foo  2.254915  1.605803
      All  2.254915  1.605803
All   bar  0.953985  0.982849
      foo  1.260709  0.826081
      All  1.112659  0.953837

[30 rows x 2 columns]

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html" title="pandas.DataFrame.unstack"><code>unstack()</code></h2>

<img src="https://pandas.pydata.org/docs/_images/reshaping_stack.png">

<p>Closely related to the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html" title="pandas.DataFrame.pivot"><code>pivot()</code></a> method are the related <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html" title="pandas.DataFrame.unstack"><code>unstack()</code></a> methods available on <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a>. These methods are designed to work together with <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a> objects (see the section on <a href="advanced.html#advanced-hierarchical">hierarchical indexing</a>).</p>

<ul>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a>: “pivot” a level of the (possibly hierarchical) column labels, returning a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> with an index with a new inner-most level of row labels.</p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html" title="pandas.DataFrame.unstack"><code>unstack()</code></a>: (inverse operation of <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a>) “pivot” a level of the (possibly hierarchical) row index to the column axis, producing a reshaped <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> with a new inner-most level of column labels.</p></li>
</ul>

<img src="https://pandas.pydata.org/docs/_images/reshaping_unstack.png">

In [361]:
tuples = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]

In [362]:
index = pd.MultiIndex.from_arrays(tuples, names=["first", "second"])

In [363]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

In [364]:
df2 = df[:4]

In [365]:
df2

                     A         B
first second
bar   one     0.035754 -1.249572
      two    -0.321411 -0.566942
baz   one    -0.216388  1.541607
      two    -0.354812 -1.148585

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a> function “compresses” a level in the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> columns to produce either:</p>

<ul>
<li><p>A <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a>, in the case of a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html" title="pandas.Index"><code>Index</code></a> in the columns.</p></li>
<li><p>A <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a>, in the case of a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a> in the columns.</p></li>
</ul>

<p>If the columns have a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a>, you can choose which level to stack. The stacked level becomes the new lowest level in a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a> on the columns:</p>

In [366]:
stacked = df2.stack(future_stack=True)

In [367]:
stacked

first  second
bar    one     A    0.035754
               B   -1.249572
       two     A   -0.321411
               B   -0.566942
baz    one     A   -0.216388
               B    1.541607
       two     A   -0.354812
               B   -1.148585
dtype: float64

<p>With a “stacked” <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> (having a <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html" title="pandas.MultiIndex"><code>MultiIndex</code></a> as the <code>index</code>), the inverse operation of <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a> is <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html" title="pandas.DataFrame.unstack"><code>unstack()</code></a>, which by default unstacks the <strong>last level</strong>:</p>

In [368]:
stacked.unstack()

                     A         B
first second
bar   one     0.035754 -1.249572
      two    -0.321411 -0.566942
baz   one    -0.216388  1.541607
      two    -0.354812 -1.148585

In [369]:
stacked.unstack(1)

second        one       two
first
bar   A  0.035754 -0.321411
      B -1.249572 -0.566942
baz   A -0.216388 -0.354812
      B  1.541607 -1.148585

In [370]:
stacked.unstack(0)

first          bar       baz
second
one    A  0.035754 -0.216388
       B -1.249572  1.541607
two    A -0.321411 -0.354812
       B -0.566942 -1.148585

<img id="reshaping-unstack-by-name" src="https://pandas.pydata.org/docs/_images/reshaping_unstack_1.png">

<p>If the indexes have names, you can use the level names instead of specifying the level numbers:</p>

In [371]:
stacked.unstack("second")

second        one       two
first
bar   A  0.035754 -0.321411
      B -1.249572 -0.566942
baz   A -0.216388 -0.354812
      B  1.541607 -1.148585

<img src="https://pandas.pydata.org/docs/_images/reshaping_unstack_0.png">

<p>Notice that the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html#pandas.DataFrame.unstack" title="pandas.DataFrame.unstack"><code>unstack()</code></a> methods implicitly sort the index levels involved. Hence a call to <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html" title="pandas.DataFrame.stack"><code>stack()</code></a> and then <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html" title="pandas.DataFrame.unstack"><code>unstack()</code></a>, or vice versa, will result in a <strong>sorted</strong> copy of the original <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> or <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html"><code>Series</code></a>:</p>

In [372]:
index = pd.MultiIndex.from_product([[2, 1], ["a", "b"]])

In [373]:
df = pd.DataFrame(np.random.randn(4), index=index, columns=["A"])

In [374]:
df

            A
2 a  0.421095
  b  0.748325
1 a  0.205388
  b -0.083436

In [375]:
all(df.unstack().stack(future_stack=True) == df.sort_index())

True

## <h3>Multiple levels</h3>

<p>You may also stack or unstack more than one level at a time by passing a list of levels, in which case the end result is as if each level in the list were processed individually.</p>

In [376]:
columns = pd.MultiIndex.from_tuples(
    [
        ("A", "cat", "long"),
        ("B", "cat", "long"),
        ("A", "dog", "short"),
        ("B", "dog", "short"),
    ],
    names=["exp", "animal", "hair_length"],
)

In [377]:
df = pd.DataFrame(np.random.randn(4, 4), columns=columns)

In [378]:
df

exp                 A         B         A         B
animal            cat       cat       dog       dog
hair_length      long      long     short     short
0            0.086105 -0.694739 -0.281815  0.647228
1            0.320408 -0.328497  0.426273 -1.323676
2            0.537418 -1.408562 -2.934896 -0.591364
3            0.570544 -3.347402 -0.755318 -0.051284

In [379]:
df.stack(level=["animal", "hair_length"], future_stack=True)

exp                          A         B
  animal hair_length
0 cat    long         0.086105 -0.694739
  dog    short       -0.281815  0.647228
1 cat    long         0.320408 -0.328497
  dog    short        0.426273 -1.323676
2 cat    long         0.537418 -1.408562
  dog    short       -2.934896 -0.591364
3 cat    long         0.570544 -3.347402
  dog    short       -0.755318 -0.051284

<p>The list of levels can contain either level names or level numbers but not a mixture of the two.</p>

In [380]:
# df.stack(level=['animal', 'hair_length'], future_stack=True)
# from above is equivalent to:
df.stack(level=[1, 2], future_stack=True)

exp                          A         B
  animal hair_length
0 cat    long         0.086105 -0.694739
  dog    short       -0.281815  0.647228
1 cat    long         0.320408 -0.328497
  dog    short        0.426273 -1.323676
2 cat    long         0.537418 -1.408562
  dog    short       -2.934896 -0.591364
3 cat    long         0.570544 -3.347402
  dog    short       -0.755318 -0.051284

## <h3>Missing data</h3>

<p>Unstacking can result in missing values if subgroups do not have the same set of labels. By default, missing values will be replaced with the default fill value for that data type.</p>

In [381]:
columns = pd.MultiIndex.from_tuples(
    [
        ("A", "cat"),
        ("B", "dog"),
        ("B", "cat"),
        ("A", "dog"),
    ],
    names=["exp", "animal"],
)

In [382]:
index = pd.MultiIndex.from_product(
    [("bar", "baz", "foo", "qux"), ("one", "two")], names=["first", "second"]
)

In [383]:
df = pd.DataFrame(np.random.randn(8, 4), index=index, columns=columns)

In [384]:
df3 = df.iloc[[0, 1, 4, 7], [1, 2]]

In [385]:
df3

exp                  B
animal             dog       cat
first second
bar   one     0.600686  2.453354
      two    -0.817509 -0.704460
foo   one    -0.261714  0.636527
qux   two     0.514425  0.157100

In [386]:
df3.unstack()

exp            B
animal       dog                 cat
second       one       two       one      two
first
bar     0.600686 -0.817509  2.453354 -0.70446
foo    -0.261714       NaN  0.636527      NaN
qux          NaN  0.514425       NaN  0.15710

<p>The missing value can be filled with a specific value with the <code>fill_value</code> argument.</p>

In [387]:
df3.unstack(fill_value=-1e9)

exp                B
animal           dog                         cat
second           one           two           one           two
first
bar     6.006856e-01 -8.175095e-01  2.453354e+00 -7.044601e-01
foo    -2.617141e-01 -1.000000e+09  6.365269e-01 -1.000000e+09
qux    -1.000000e+09  5.144248e-01 -1.000000e+09  1.570996e-01

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.melt.html" title="pandas.melt"><code>melt()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.wide_to_long.html" title="pandas.wide_to_long"><code>wide_to_long()</code></a></h2>

<img src="https://pandas.pydata.org/docs/_images/reshaping_melt.png">

<p>The top-level <a href="https://pandas.pydata.org/docs/reference/api/pandas.melt.html" title="pandas.melt"><code>melt()</code></a> function and the corresponding <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.melt.html" title="pandas.DataFrame.melt"><code>DataFrame.melt()</code></a> are useful to massage a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> into a format where one or more columns are <em>identifier variables</em>, while all other columns, considered <em>measured variables</em>, are “unpivoted” to the row axis, leaving just two non-identifier columns, “variable” and “value”. The names of those columns can be customized by supplying the <code>var_name</code> and <code>value_name</code> parameters.</p>

In [388]:
cheese = pd.DataFrame(
    {
        "first": ["John", "Mary"],
        "last": ["Doe", "Bo"],
        "height": [5.5, 6.0],
        "weight": [130, 150],
    }
)

In [389]:
cheese

  first last  height  weight
0  John  Doe     5.5     130
1  Mary   Bo     6.0     150

In [390]:
cheese.melt(id_vars=["first", "last"])

  first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

In [391]:
cheese.melt(id_vars=["first", "last"], var_name="quantity")

  first last quantity  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

<p>When transforming a DataFrame using <a href="https://pandas.pydata.org/docs/reference/api/pandas.melt.html" title="pandas.melt"><code>melt()</code></a>, the index will be ignored.
The original index values can be kept by setting the <code>ignore_index=False</code> parameter to <code>False</code> (default is <code>True</code>).
<code>ignore_index=False</code> will however duplicate index values.</p>

In [392]:
index = pd.MultiIndex.from_tuples([("person", "A"), ("person", "B")])

In [393]:
cheese = pd.DataFrame(
    {
        "first": ["John", "Mary"],
        "last": ["Doe", "Bo"],
        "height": [5.5, 6.0],
        "weight": [130, 150],
    },
    index=index,
)

In [394]:
cheese

         first last  height  weight
person A  John  Doe     5.5     130
       B  Mary   Bo     6.0     150

In [395]:
cheese.melt(id_vars=["first", "last"])

  first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

In [396]:
cheese.melt(id_vars=["first", "last"], ignore_index=False)

         first last variable  value
person A  John  Doe   height    5.5
       B  Mary   Bo   height    6.0
       A  John  Doe   weight  130.0
       B  Mary   Bo   weight  150.0

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.wide_to_long.html" title="pandas.wide_to_long"><code>wide_to_long()</code></a> is similar to <a href="https://pandas.pydata.org/docs/reference/api/pandas.melt.html" title="pandas.melt"><code>melt()</code></a> with more customization for column matching.</p>

In [397]:
dft = pd.DataFrame(
    {
        "A1970": {0: "a", 1: "b", 2: "c"},
        "A1980": {0: "d", 1: "e", 2: "f"},
        "B1970": {0: 2.5, 1: 1.2, 2: 0.7},
        "B1980": {0: 3.2, 1: 1.3, 2: 0.1},
        "X": dict(zip(range(3), np.random.randn(3))),
    }
)

In [398]:
dft["id"] = dft.index

In [399]:
dft

  A1970 A1980  B1970  B1980         X  id
0     a     d    2.5    3.2  1.161700   0
1     b     e    1.2    1.3 -0.255405   1
2     c     f    0.7    0.1 -1.874560   2

In [400]:
pd.wide_to_long(dft, ["A", "B"], i="id", j="year")

                X  A    B
id year
0  1970  1.161700  a  2.5
1  1970 -0.255405  b  1.2
2  1970 -1.874560  c  0.7
0  1980  1.161700  d  3.2
1  1980 -0.255405  e  1.3
2  1980 -1.874560  f  0.1

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html" title="pandas.get_dummies"><code>get_dummies()</code></a> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.from_dummies.html" title="pandas.from_dummies"><code>from_dummies()</code></a></h2>

<p>To convert categorical variables of a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> into a “dummy” or “indicator”, <a href="https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html" title="pandas.get_dummies"><code>get_dummies()</code></a> creates a new <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> with columns of the unique variables and the values representing the presence of those variables per row.</p>

In [401]:
df = pd.DataFrame({"key": list("bbacab"), "data1": range(6)})

In [402]:
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [403]:
df["key"].str.get_dummies()

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

<p><code>prefix</code> adds a prefix to the the column names which is useful for merging the result with the original <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a>:</p>

In [404]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [405]:
dummies

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [406]:
df[["data1"]].join(dummies)

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

<p>This function is often used along with discretization functions like <a href="https://pandas.pydata.org/docs/reference/api/pandas.cut.html" title="pandas.cut"><code>cut()</code></a>:</p>

In [407]:
values = np.random.randn(10)

In [408]:
values

array([-0.57250966,  1.25150776,  2.50076789,  0.40751943,  1.10750775,
        0.85474622,  0.66223194, -0.81617234, -0.4462871 ,  1.61260411])

In [409]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [410]:
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False       False
1       False       False       False       False       False
2       False       False       False       False       False
3       False       False        True       False       False
4       False       False       False       False       False
5       False       False       False       False        True
6       False       False       False        True       False
7       False       False       False       False       False
8       False       False       False       False       False
9       False       False       False       False       False

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html" title="pandas.get_dummies"><code>get_dummies()</code></a> also accepts a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a>. By default, <code>object</code>, <code>string</code>, or <code>categorical</code> type columns are encoded as dummy variables with other columns unaltered.</p>

In [411]:
df = pd.DataFrame({"A": ["a", "b", "a"], "B": ["c", "c", "b"], "C": [1, 2, 3]})

In [412]:
pd.get_dummies(df)

   C    A_a    A_b    B_b    B_c
0  1   True  False  False   True
1  2  False   True  False   True
2  3   True  False   True  False

<p>Specifying the <code>columns</code> keyword will encode a column of any type.</p>

In [413]:
pd.get_dummies(df, columns=["A"])

   B  C    A_a    A_b
0  c  1   True  False
1  c  2  False   True
2  b  3   True  False

<p>As with the <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> version, you can pass values for the <code>prefix</code> and <code>prefix_sep</code>. By default the column name is used as the prefix and <code>_</code> as the prefix separator. You can specify <code>prefix</code> and <code>prefix_sep</code> in 3 ways:</p>

<ul>
<li><p>string: Use the same value for <code>prefix</code> or <code>prefix_sep</code> for each column to be encoded.</p></li>
<li><p>list: Must be the same length as the number of columns being encoded.</p></li>
<li><p>dict: Mapping column name to prefix.</p></li>
</ul>

In [414]:
simple = pd.get_dummies(df, prefix="new_prefix")

In [415]:
simple

   C  new_prefix_a  new_prefix_b  new_prefix_b  new_prefix_c
0  1          True         False         False          True
1  2         False          True         False          True
2  3          True         False          True         False

In [416]:
from_list = pd.get_dummies(df, prefix=["from_A", "from_B"])

In [417]:
from_list

   C  from_A_a  from_A_b  from_B_b  from_B_c
0  1      True     False     False      True
1  2     False      True     False      True
2  3      True     False      True     False

In [418]:
from_dict = pd.get_dummies(df, prefix={"B": "from_B", "A": "from_A"})

In [419]:
from_dict

   C  from_A_a  from_A_b  from_B_b  from_B_c
0  1      True     False     False      True
1  2     False      True     False      True
2  3      True     False      True     False

<p>To avoid collinearity when feeding the result to statistical models, specify <code>drop_first=True</code>.</p>

In [420]:
s = pd.Series(list("abcaa"))

In [421]:
pd.get_dummies(s)

       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False
4   True  False  False

In [422]:
pd.get_dummies(s, drop_first=True)

       b      c
0  False  False
1   True  False
2  False   True
3  False  False
4  False  False

<p>When a column contains only one level, it will be omitted in the result.</p>

In [423]:
df = pd.DataFrame({"A": list("aaaaa"), "B": list("ababc")})

In [424]:
pd.get_dummies(df)

    A_a    B_a    B_b    B_c
0  True   True  False  False
1  True  False   True  False
2  True   True  False  False
3  True  False   True  False
4  True  False  False   True

In [425]:
pd.get_dummies(df, drop_first=True)

     B_b    B_c
0  False  False
1   True  False
2  False  False
3   True  False
4  False   True

<p>The values can be cast to a different type using the <code>dtype</code> argument.</p>

In [426]:
df = pd.DataFrame({"A": list("abc"), "B": [1.1, 2.2, 3.3]})

In [427]:
pd.get_dummies(df, dtype=np.float32).dtypes

B      float64
A_a    float32
A_b    float32
A_c    float32
dtype: object

<div class="versionadded">
<p><span class="versionmodified added">Added in version 1.5.0.</p>
</div>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.from_dummies.html" title="pandas.from_dummies"><code>from_dummies()</code></a> converts the output of <a href="https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html" title="pandas.get_dummies"><code>get_dummies()</code></a> back into
a <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> of categorical values from indicator values.</p>

In [428]:
df = pd.DataFrame({"prefix_a": [0, 1, 0], "prefix_b": [1, 0, 1]})

In [429]:
df

   prefix_a  prefix_b
0         0         1
1         1         0
2         0         1

In [430]:
pd.from_dummies(df, sep="_")

  prefix
0      b
1      a
2      b

<p>Dummy coded data only requires <code>k - 1</code> categories to be included, in this case the last category is the default category. The default category can be modified with <code>default_category</code>.</p>

In [431]:
df = pd.DataFrame({"prefix_a": [0, 1, 0]})

In [432]:
df

   prefix_a
0         0
1         1
2         0

In [433]:
pd.from_dummies(df, sep="_", default_category="b")

  prefix
0      b
1      a
2      b

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.explode.html" title="pandas.Series.explode"><code>explode()</code></a></h2>

<p>For a <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a> column with nested, list-like values, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.explode.html" title="pandas.Series.explode"><code>explode()</code></a> will transform each list-like value to a separate row. The resulting <a href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html" title="pandas.Index"><code>Index</code></a> will be duplicated corresponding to the index label from the original row:</p>

In [434]:
keys = ["panda1", "panda2", "panda3"]

In [435]:
values = [["eats", "shoots"], ["shoots", "leaves"], ["eats", "leaves"]]

In [436]:
df = pd.DataFrame({"keys": keys, "values": values})

In [437]:
df

     keys            values
0  panda1    [eats, shoots]
1  panda2  [shoots, leaves]
2  panda3    [eats, leaves]

In [438]:
df["values"].explode()

0      eats
0    shoots
1    shoots
1    leaves
2      eats
2    leaves
Name: values, dtype: object

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html" title="pandas.DataFrame.explode"><code>DataFrame.explode</code></a> can also explode the column in the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html" title="pandas.DataFrame"><code>DataFrame</code></a>.</p>

In [439]:
df.explode("values")

     keys  values
0  panda1    eats
0  panda1  shoots
1  panda2  shoots
1  panda2  leaves
2  panda3    eats
2  panda3  leaves

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.explode.html" title="pandas.Series.explode"><code>Series.explode()</code></a> will replace empty lists with a missing value indicator and preserve scalar entries.</p>

In [440]:
s = pd.Series([[1, 2, 3], "foo", [], ["a", "b"]])

In [441]:
s

0    [1, 2, 3]
1          foo
2           []
3       [a, b]
dtype: object

In [442]:
s.explode()

0      1
0      2
0      3
1    foo
2    NaN
3      a
3      b
dtype: object

<p>A comma-separated string value can be split into individual values in a list and then exploded to a new row.</p>

In [443]:
df = pd.DataFrame([{"var1": "a,b,c", "var2": 1}, {"var1": "d,e,f", "var2": 2}])

In [444]:
df.assign(var1=df.var1.str.split(",")).explode("var1")

  var1  var2
0    a     1
0    b     1
0    c     1
1    d     2
1    e     2
1    f     2

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html" title="pandas.crosstab"><code>crosstab()</code></a></h2>

<p>Use <a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html" title="pandas.crosstab"><code>crosstab()</code></a> to compute a cross-tabulation of two (or more) factors. By default <a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html" title="pandas.crosstab"><code>crosstab()</code></a> computes a frequency table of the factors unless an array of values and an aggregation function are passed.</p>

<p>Any <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> passed will have their name attributes used unless row or column names for the cross-tabulation are specified</p>

In [472]:
a = np.array(["foo", "foo", "bar", "bar", "foo", "foo"], dtype=object)

In [473]:
b = np.array(["one", "one", "two", "one", "two", "one"], dtype=object)

In [474]:
c = np.array(["dull", "dull", "shiny", "dull", "dull", "shiny"], dtype=object)

In [475]:
pd.crosstab(a, [b, c], rownames=["a"], colnames=["b", "c"])

b    one        two
c   dull shiny dull shiny
a
bar    1     0    0     1
foo    2     1    1     0

<p>If <a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html" title="pandas.crosstab"><code>crosstab()</code></a> receives only two <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a>, it will provide a frequency table.</p>

In [448]:
df = pd.DataFrame(
    {"A": [1, 2, 2, 2, 2], "B": [3, 3, 4, 4, 4], "C": [1, 1, np.nan, 1, 1]}
)

In [449]:
df

   A  B    C
0  1  3  1.0
1  2  3  1.0
2  2  4  NaN
3  2  4  1.0
4  2  4  1.0

In [450]:
pd.crosstab(df["A"], df["B"])

B  3  4
A
1  1  0
2  1  3

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html" title="pandas.crosstab"><code>crosstab()</code></a> can also summarize to <a href="https://pandas.pydata.org/docs/reference/api/pandas.Categorical.html" title="pandas.Categorical"><code>Categorical</code></a> data.</p>

In [451]:
foo = pd.Categorical(["a", "b"], categories=["a", "b", "c"])

In [452]:
bar = pd.Categorical(["d", "e"], categories=["d", "e", "f"])

In [453]:
pd.crosstab(foo, bar)

col_0  d  e
row_0
a      1  0
b      0  1

<p>For <a href="https://pandas.pydata.org/docs/reference/api/pandas.Categorical.html" title="pandas.Categorical"><code>Categorical</code></a> data, to include <strong>all</strong> of data categories even if the actual data does not contain any instances of a particular category, use <code>dropna=False</code>.</p>

In [454]:
pd.crosstab(foo, bar, dropna=False)

col_0  d  e  f
row_0
a      1  0  0
b      0  1  0
c      0  0  0

## <h3>Normalization</h3>

<p>Frequency tables can also be normalized to show percentages rather than counts using the <code>normalize</code> argument:</p>

In [455]:
pd.crosstab(df["A"], df["B"], normalize=True)

B    3    4
A
1  0.2  0.0
2  0.2  0.6

<p><code>normalize</code> can also normalize values within each row or within each column:</p>

In [456]:
pd.crosstab(df["A"], df["B"], normalize="columns")

B    3    4
A
1  0.5  0.0
2  0.5  1.0

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html" title="pandas.crosstab"><code>crosstab()</code></a> can also accept a third <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> and an aggregation function (<code>aggfunc</code>) that will be applied to the values of the third <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a> within each group defined by the first two <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html" title="pandas.Series"><code>Series</code></a>:</p>

In [457]:
pd.crosstab(df["A"], df["B"], values=df["C"], aggfunc="sum")

B    3    4
A
1  1.0  NaN
2  1.0  2.0

## <h3>Adding margins</h3>

<p><code>margins=True</code> will add a row and column with an <code>All</code> label with partial group aggregates across the categories on the rows and columns:</p>

In [458]:
pd.crosstab(
    df["A"], df["B"], values=df["C"], aggfunc="sum", normalize=True, margins=True
)

B       3    4   All
A
1    0.25  0.0  0.25
2    0.25  0.5  0.75
All  0.50  0.5  1.00

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.cut.html" title="pandas.cut"><code>cut()</code></a></h2>

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.cut.html" title="pandas.cut"><code>cut()</code></a> function computes groupings for the values of the input array and is often used to transform continuous variables to discrete or categorical variables:</p>

<p>An integer <code>bins</code> will form equal-width bins.</p>

In [459]:
ages = np.array([10, 15, 13, 12, 23, 25, 28, 59, 60])

In [460]:
pd.cut(ages, bins=3)

[(9.95, 26.667], (9.95, 26.667], (9.95, 26.667], (9.95, 26.667], (9.95, 26.667], (9.95, 26.667], (26.667, 43.333], (43.333, 60.0], (43.333, 60.0]]
Categories (3, interval[float64, right]): [(9.95, 26.667] < (26.667, 43.333] < (43.333, 60.0]]

<p>A list of ordered bin edges will assign an interval for each variable.</p>

In [461]:
pd.cut(ages, bins=[0, 18, 35, 70])

[(0, 18], (0, 18], (0, 18], (0, 18], (18, 35], (18, 35], (18, 35], (35, 70], (35, 70]]
Categories (3, interval[int64, right]): [(0, 18] < (18, 35] < (35, 70]]

<p>If the <code>bins</code> keyword is an <a href="https://pandas.pydata.org/docs/reference/api/pandas.IntervalIndex.html" title="pandas.IntervalIndex"><code>IntervalIndex</code></a>, then these will be used to bin the passed data.</p>

In [462]:
pd.cut(ages, bins=pd.IntervalIndex.from_breaks([0, 40, 70]))

[(0, 40], (0, 40], (0, 40], (0, 40], (0, 40], (0, 40], (0, 40], (40, 70], (40, 70]]
Categories (2, interval[int64, right]): [(0, 40] < (40, 70]]

# <h2><a href="https://pandas.pydata.org/docs/reference/api/pandas.factorize.html" title="pandas.factorize"><code>factorize()</code></a></h2>

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.factorize.html" title="pandas.factorize"><code>factorize()</code></a> encodes 1 dimensional values into integer labels. Missing values are encoded as <code>-1</code>.</p>

In [463]:
x = pd.Series(["A", "A", np.nan, "B", 3.14, np.inf])

In [464]:
x

0       A
1       A
2     NaN
3       B
4    3.14
5     inf
dtype: object

In [465]:
labels, uniques = pd.factorize(x)

In [466]:
labels

array([ 0,  0, -1,  1,  2,  3])

In [467]:
uniques

Index(['A', 'B', 3.14, inf], dtype='object')

<p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Categorical.html" title="pandas.Categorical"><code>Categorical</code></a> will similarly encode 1 dimensional values for further categorical operations</p>

In [468]:
pd.Categorical(x)

['A', 'A', NaN, 'B', 3.14, inf]
Categories (4, object): [3.14, inf, 'A', 'B']